### ISSUE TITLE
Can you post a working sample with http basic auth for both server/client with Spring Boot 2.0

### ISSUE THREAD

**Issue by zhaoshenhao** [codecentric/spring-boot-admin#1001]
I followed the doc and some samples to setup boot admin with http auth, but no luck. I tried Spring Boot 2.1.0-RELEASE with Boot Admin 2.1.0. Once I enabled the http security, I always get registration failed 401 null issue. I tested with curl and found GET /instances is OK. And POST /instance returns 401.

I believe basic protection is always required. If you can make it as a out-of-box solution or put them in a simple project, it will be great. 

The current sample code, is not very friendly and nice as it requires "parent" projects and many other unnecessary modules/projects. 

Thank you.

**Comment by joshiste** [comment]
The sample doesn't require any parent project, it just requires spring security. The samples are also in our guide http://codecentric.github.io/spring-boot-admin/current/#securing-spring-boot-admin

(To make it easier to build and test the samples they are submodules in our maven build)

**Comment by zhaoshenhao** [comment]
I followed that link, but keep getting 401 null. I can login to UI with same password. GET /instances works, POST /instances with test data (I copied from tcpdump) returns 401 null. Anyway, turned off some security related endpoints, it should ok for now.

**Comment by joshiste** [comment]
You need to tell the spring boot admin client the correct password via `spring.boot.admin.client.username` and `spring.boot.admin.client.password`

**Comment by joshiste** [comment]
sorry this was missing in the docs. fixed it. f02b38dff1cc6702700a66740f3a50a82adb8d30

**Comment by joshiste** [comment]
Did you enable http basic in your spring security config ?
