### ISSUE TITLE
Getting OutOfDirectMemoryError errors

### ISSUE THREAD

**Issue by Sarvesh-D** [codecentric/spring-boot-admin#1002]
Hi, i am using SBA 2.0.3 with 3 apps (7 instances) registered to it. The app is deployed to PCF with below configuration: 
```yaml
memory: 2048M
disk_quota: 1024M
```
the app was running fine till couple of days back when i got many `io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 256 byte(s) of direct memory (used: 10485751, max: 10485760)` and due to which the admin server was not able to function properly. The admin server post restarting was able to function properly, but i just want to confirm is this a known issue (or something to deal with memory leak somewhere?). For safe side, i will increase the disk_quota. Thanks.

**Comment by joshiste** [comment]
1 ) Did you upgrade to the latest spring boot (2.0.x) and spring boot admin (2.0.x) versions? 
2) Are you running on tomcat or netty? Please try on tomcat (via including `spring-boot-starter-web`)
3) The disk_quota will not increase your available memory...

**Comment by Sarvesh-D** [comment]
Yes i am on latest versions:
```
springBootVersion = '2.0.5.RELEASE'
springBootAdminVersion = '2.0.3'
```
I am using Netty, will try using tomcat and reducing the memory to see if i can reproduce it.
Thanks for the suggestion, you can close this issue if it's not related to SBA.

**Comment by joshiste** [comment]
@Sarvesh-D any update on this?

**Comment by Sarvesh-D** [comment]
Sorry I'm still in between other things so didn't get time to look into this, as I said you can close this, probably the issue is with netty. Ill try to switch to tomcat. Is any other configuration required to get SBA working with tomcat?
FYI: we did not face this issue since I posted this, we however got same issue on other environment. So maybe I'll investigate it a bit further and reply if any possible solution I get. But for now you can close this issue. Thanks

**Comment by joshiste** [comment]
>  Is any other configuration required to get SBA working with tomcat?

no just include the `starter-web`

**Comment by Sarvesh-D** [comment]
@joshiste I was able to resolve the issue by upgrading libraries to below versions:
```
        springBootVersion = '2.1.1.RELEASE'
        springCloudVersion = 'Greenwich.RC2'
        springBootAdminVersion = '2.1.1'
```
Looks like the leak was in Spring WebClient [https://jira.spring.io/browse/SPR-17473](https://jira.spring.io/browse/SPR-17473).
