### ISSUE TITLE
SBA 2.0.4 behind zuul get status code 406

### ISSUE THREAD

**Issue by mattwmj** [codecentric/spring-boot-admin#1005]
I am deploying SBA behind zuul gateway. Every thing works fine but the SBA ui shows Server connection failed every five seconds. Chrome console shows /applications returns 406 when content type is Content-Type: text/event-stream;charset=UTF-8. 

Zuul shows exception:

org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected

Is this because zuul does not support text/event-stream? If is, can you provide config to disable some function that relies event stream? Or any alternative config without event stream?
Thank you very much!

**Comment by joshiste** [comment]
> Is this because zuul does not support text/event-stream? 

Yes, afaik zuul has problems with indefinite chunked streams.

>  If is, can you provide config to disable some function that relies event stream? Or any alternative config without event stream?

No. The stream is needed to update the UI.
