### ISSUE TITLE
The scheme of the 'spring.boot.admin.ui.public-url' is ignored

### ISSUE THREAD

**Issue by yleguern** [codecentric/spring-boot-admin#1007]
Hello,

I'm using Spring Boot Admin 2.1.1 (Spring boot 2.1.0).

My "Spring Boot Admin" app is running in a Docker container and exposes an http port. An ALB is handling the https part.

I set the `spring.boot.admin.ui.public-url` property with an https URL. But the [UriComponentsBuilder](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java#L59) ignores the scheme of the public URL.

I'll provide a PR to fix this.
Thanks.

**Comment by joshiste** [comment]
The scheme is determined by the servlet container. If you want that the https scheme is used (because you have a reverese proxy in front) make sure that the "forwarded" headers are used. See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server
