### ISSUE TITLE
When use preferIpAddress setting, there are two instances in spring boot admin

### ISSUE THREAD

**Issue by liyj144** [codecentric/spring-boot-admin#1010]
I'm using  `spring-boot-admin 2.0.4` with `spring boot 2.0.6`. When using preferIpAddress in application, there will be two instances in admin page, one is in upper-case, one is lower-case. Application setting is as follows
```
spring.application.name = fmc-order-service-web
eureka.instance.preferIpAddress = true
eureka.client.fetchRegistry = true
eureka.client.registerWithEureka = true
eureka.client.serviceUrl.defaultZone = http://127.0.0.1:8761/eureka/

spring.boot.admin.client.url = http://127.0.0.1:8788
spring.boot.admin.client.instance.prefer-ip = true
management.endpoints.web.exposure.include = *
management.endpoint.health.show-details = always
```
Then two instances is :  `1. fmc-order-service-web`, `2. FMC-ORDER-SERVICE-WEB `. 
The two instances is the same and all of them can show the application info. If i add the uppercase application name setting
```
spring.boot.admin.client.instance.name = FMC-ORDER-SERVICE-WEB
```
there will be only one instance. I don't think it's a good idea to assign the uppercase application name each time with `spring.boot.admin.client.instance.name`.Please help to fix it, thanks.

**Comment by joshiste** [comment]
you must not use eureka and sba-client. Choose one.

**Comment by liyj144** [comment]
Thanks! I remove the sba-client and it works perfect now.
