### ISSUE TITLE
OPTIONS http://locahost:8080/notifications/filters 404

### ISSUE THREAD

**Issue by chunzhenzyd** [codecentric/spring-boot-admin#1011]
** Question **
There is alway a 404 error when I view applications in Spring Boot Admin page. 
Admin url: http://localhost:8000
Request: http://localhost:8000/notifications/filters
Request Method: OPTIONS
Response: 404

**Comment by chunzhenzyd** [comment]
springboot version: 2.1.0
admin version: 2.1.0

**Comment by joshiste** [comment]
This is OK. It's used by the UI to determine if the api for notification filters is available.
