### ISSUE TITLE
How to add notifications filters api?

### ISSUE THREAD

**Issue by chunzhenzyd** [codecentric/spring-boot-admin#1012]
Hi @joshiste 
OPTIONS http://locahost:8080/notifications/filters 404
https://github.com/codecentric/spring-boot-admin/issues/1011

I'm sorry, I still don't understand though it's not a problem.
So, how to add/set the api for notification filters?

I have already add a FilteringNotifier to my application as the tutorial said:

@Configuration
public static class NotifierConfig {
    private final InstanceRepository repository;
    private final ObjectProvider<List<Notifier>> otherNotifiers;

    public NotifierConfig(InstanceRepository repository, ObjectProvider<List<Notifier>> otherNotifiers) {
        this.repository = repository;
        this.otherNotifiers = otherNotifiers;
    }

    @Bean
    public FilteringNotifier filteringNotifier() { 
        CompositeNotifier delegate = new CompositeNotifier(otherNotifiers.getIfAvailable(Collections::emptyList));
        return new FilteringNotifier(delegate, repository);
    }

    @Primary
    @Bean(initMethod = "start", destroyMethod = "stop")
    public RemindingNotifier remindingNotifier() { 
        RemindingNotifier notifier = new RemindingNotifier(filteringNotifier(), repository);
        notifier.setReminderPeriod(Duration.ofMinutes(10));
        notifier.setCheckReminderInverval(Duration.ofSeconds(10));
        return notifier;
    }
}

**Comment by joshiste** [comment]
When a `FilteringNotifier` is present the corresponding controller should be instantiated by this autoconfiguration https://github.com/codecentric/spring-boot-admin/blob/5e9b1eb681539312155d56cff9ddec4e838d5a5b/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerNotifierAutoConfiguration.java#L97
