### ISSUE TITLE
Caches and MBeans are not displayed within some browsers

### ISSUE THREAD

**Issue by krysto** [codecentric/spring-boot-admin#1013]
Spring Boot Admin : 2.1.1
Spring Boot: 2.1.0
Google Chrome: 64

When I open either Caches or JMX>JMX tabs, the `Fetching caches failed. Object.entries(...).flatMap is not a function` error message is displayed.

The `Array.flatMap()` function has a very limited support (Chrome 69, no IE... more [here](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/flatMap#Compatibilité_des_navigateurs)).

FYI : As a fallback, I added the following file `META-INF/spring-boot-admin-server-ui/assets/js/chunk-common.82a7af35.js` in order to override provided one : 
`(window["webpackJsonp"]=window["webpackJsonp"]||[]).push([["chunk-common"],{6719:function(n,o,w){}}]);
const concat = (x,y) =>
  x.concat(y)
const flatMap = (f,xs) =>
  xs.map(f).reduce(concat, [])
Array.prototype.flatMap = function(f) {
  return flatMap(f,this)
}
//# sourceMappingURL=chunk-common.82a7af35.js.map`

This sample code provides its own implementation of `flatMap()` with [concat()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/concat), [map()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/map) and [reduce()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/reduce) functions which are widely supported as mentionned here, here and here.

Could you please provide a real fix for this issue ?

**Comment by melloware** [comment]
Can you tell is that the cause of my issue running SBA 2.1.1.  Everything works except the JMX page I documented everything here: https://stackoverflow.com/questions/53308335/why-is-sba-jmx-bean-management-reporting-an-error
