### ISSUE TITLE
Enable custom title for login page

### ISSUE THREAD

**Issue by phil-schneider** [codecentric/spring-boot-admin#1015]
It is possible to set a custom title for the website with
`spring.boot.admin.ui = title: ${spring.profiles} Spring Boot Admin`

This is really helpful, like when you have one instance on dev, integration and production.
This index.html page supports this:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/index.html#L39

The login page **does not** support this feature:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/login.html#L27
For the login page this is also needed.
E.g. when entering passwords for different enviroments. The password tool "keepass" can do an auto login based on the webpage title.

**Comment by sundayha** [comment]
@joshiste 
hi joshiste, Can the 39 lines of login page implement the custom title and brand?
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/login.html#L39

**Comment by phil-schneider** [comment]
Hello sundayha,
Yes they can. This is an opensource project. Look at the code, change it and create a pull request. 
Welcome to the community

**Comment by sundayha** [comment]
@phil-schneider ok， i will do that 😄
