### ISSUE TITLE
Allow the WebClient used by the InstanceWebClient to be customized

### ISSUE THREAD

**Issue by shollander** [codecentric/spring-boot-admin#1019]
I would like to hook up SBA to an application that requires 2 way SSL. There is not currently a clean solution for doing this. I was required to create my own instance of `InstanceWebClient` and manually provide a `WebClientCustomizer`. It would be better if SBA would automatically use a `WebClientCustomizer` from the context (similar to the way that `HttpHeadersProvider` is used from the spring context.)

**Comment by joshiste** [comment]
From #1094: A solution of this issue should contain a sample in the docs.
