### ISSUE TITLE
Ability to add custom dashboards for metrics

### ISSUE THREAD

**Issue by Sarvesh-D** [codecentric/spring-boot-admin#1020]
** Enhancement **
The metrics tab for SBA is not persistent and all the metrics selected for analysing tend to get lost with browser refresh. Please provide a way to add/club multiple metrics into a dashboard (maybe persistent or something which can be imported/exported in json form). This way for any instance we can just import the dashboard and all the metrics do not need to be added again.
It would be good to have time-series view of metics as well (i think there is already request for this)

P.S: As a workaround, currently i save the request url from browser after adding some metrics, and then just change the instance id in request url to view those metrics for another instance.

e.g:
For analysing memory in JVM:
http://localhost:9000/#/instances/{instance-id}/metrics?q=%7B%22name%22%3A%22jvm.buffer.count%22,%22tagSelections%22%3A%5B%7B%22id%22%3A%22direct%22%7D,%7B%22id%22%3A%22mapped%22%7D%5D,%22types%22%3A%7B%22VALUE%22%3A%22%22%7D%7D&q=%7B%22name%22%3A%22jvm.buffer.memory.used%22,%22tagSelections%22%3A%5B%7B%22id%22%3A%22direct%22%7D,%7B%22id%22%3A%22mapped%22%7D%5D,%22types%22%3A%7B%22VALUE%22%3A%22bytes%22%7D%7D&q=%7B%22name%22%3A%22jvm.buffer.total.capacity%22,%22tagSelections%22%3A%5B%7B%22id%22%3A%22direct%22%7D,%7B%22id%22%3A%22mapped%22%7D%5D,%22types%22%3A%7B%22VALUE%22%3A%22bytes%22%7D%7D&q=%7B%22name%22%3A%22jvm.memory.max%22,%22tagSelections%22%3A%5B%7B%22area%22%3A%22heap%22%7D%5D,%22types%22%3A%7B%22VALUE%22%3A%22bytes%22%7D%7D&q=%7B%22name%22%3A%22jvm.memory.used%22,%22tagSelections%22%3A%5B%7B%22area%22%3A%22heap%22%7D%5D,%22types%22%3A%7B%22VALUE%22%3A%22bytes%22%7D%7D

**Comment by joshiste** [comment]
With the latest and greatest the selected metrics are stored per application.

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.
