### ISSUE TITLE
Development mode is working but production is not!

### ISSUE THREAD

**Issue by deamon999** [codecentric/spring-boot-admin#1025]
So basicaly i heve two application: one for client, second for admin boot server. When i am running these two application  on my local machine everything is working, but when i deployed the application to hosting server i can see error 503 for my application at spring boot server because of timeout read operation for netty abstract channel. i did change time out limit for server application but it is not helping because i am getting the 503 error for status of health 
********************************************************************
(Fetching live health status failed. This is the last known information.
Request failed with status code 503)
********************************************************************
 , but i can json like data by link. Can you help me?

**Comment by MatthewAry** [comment]
I work with @deamon999 the server is set up to operate behind an nginx reverse proxy. We've seen also seen issues similar to #990 but have not been and to resolve them.

**Comment by joshiste** [comment]
The sba server must be able to reach the clients via the management adress the client submits during registration. If you are using the sba client this address is guessed based on the hostname and port. If your app is running behind a rev. proxy it's most likely wrong. You can override it via `spring.boot.admin.client.instance.service-base-url`

**Comment by deamon999** [comment]
#admin client settings
spring.boot.admin.client.url=http://host for server application/
spring.boot.admin.client.instance.management-url=http://ip address with:8080/admin/actuator
spring.boot.admin.client.instance.health-url=http://ip address with:8080/admin/actuator/health
spring.boot.admin.client.instance.service-base-url=http://ip address with:8080/admin/
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/admin/actuator/
#update connection
spring.boot.admin.client.period=1000
# Such password is visible in the console during app startup
# Credentials to authenticate with the Admin Server
spring.boot.admin.client.username=sba user
spring.boot.admin.client.password=sba password

#server admin application settings
server.port = 9090
spring.security.user.name=spa user
spring.security.user.password=sba password

spring.boot.admin.monitor.default-retries=3
spring.boot.admin.monitor.connect-timeout=100000
spring.boot.admin.monitor.read-timeout=100000

spring.boot.admin.ui.cache-templates=false
spring.boot.admin.ui.cache.no-cache=true

**************************************************
so these are our settings, and it is showing this:
![2018-12-03](https://user-images.githubusercontent.com/29608816/49395027-a813d700-f735-11e8-9e0f-7833be0b3c19.png).
i tried disable spring security for both application, and nothing - only this error 503

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by kiritsev** [comment]
> The sba server must be able to reach the clients via the management adress the client submits during registration. If you are using the sba client this address is guessed based on the hostname and port. If your app is running behind a rev. proxy it's most likely wrong. You can override it via `spring.boot.admin.client.instance.service-base-url`

It is not enough. When SBA calls /client1/actuator then it gets in the response addresses looking like /actuator/info, /actuator/health and so on. Then SBA goes on this address and gets ERROR 503, because the real address is /client1/actuator/info and so on. 

server:
  forward-headers-strategy: framework

This did not help too.
