### ISSUE TITLE
Actuator end point is comming as unable to resolve host ip-10-0-xx-xx inspite of 10.0.0.0

### ISSUE THREAD

**Issue by rahul34167** [codecentric/spring-boot-admin#1027]
I am getting unknown Host Exception . As i have enabled box the ip address on aws which fetched domain using the meta data api of aws but still ip address is not coming in the format 127.0.0.1

but inspite of it is coming as ip-127.0.0.1 or either ec2 instance name.

**Comment by joshiste** [comment]
are you using the sba client?

**Comment by joshiste** [comment]
closed due to missing feedback
