### ISSUE TITLE
404 ERROR for all HEAD requests

### ISSUE THREAD

**Issue by mayureshharsha** [codecentric/spring-boot-admin#1030]

**Comment by joshiste** [comment]
>  I have exposed management endpoints to "*" . can anyone help on this issue. I am using 1.5x version

The exposure is a Spring Boot 2.0 thing, iirc.
Are you using SBA 1.5.x whith Boot 2.0? that won't work.

**Comment by joshiste** [comment]
If you can't reach the routes from your browser I guess your cf setup is not correct. I can't help you with that.

**Comment by mayureshharsha** [comment]
> > I have exposed management endpoints to "*" . can anyone help on this issue. I am using 1.5x version
> 
> The exposure is a Spring Boot 2.0 thing, iirc.
> Are you using SBA 1.5.x whith Boot 2.0? that won't work.

I am using 1.5x for both SB and SBA. I get 404 HEAD on network tab , but when I hit the same URL via browser (GET) ,  I get the payload in JSON

**Comment by joshiste** [comment]
I don't know much about cf but I guess it's router is somehow not handling HEAD requests correctly.
I'd advise you to upgrade to one of our 2.x releases as they don't make these requests.
