### ISSUE TITLE
Resources cannot be loaded via HTTPS?

### ISSUE THREAD

**Issue by sddakoty** [codecentric/spring-boot-admin#1031]
Was there a major change in the latest release regarding HTTPS access?
I have a webserver that can only be accessed via `https`.

On `2.0.4` (with spring-boot.2.0.6) everything worked fine, but on `2.1.1` (with spring-boot.2.1.1) the following errors are shown in the console:

```
Loading mixed (insecure) active content “http://my.api.com/my-adminui/assets/css/chunk-common.9808b72e.css” on a secure page[Learn More]
my-adminui
Loading mixed (insecure) active content “http://my.api.com/my-adminui/assets/css/sba-core.360886fb.css” on a secure page[Learn More]
my-adminui
Loading mixed (insecure) active content “http://my.api.com/my-adminui/assets/js/chunk-vendors.1df687d0.js” on a secure page[Learn More] my-adminui
Loading mixed (insecure) display content “https://my.api.com/my-adminui/img/my-logo.png” on a secure page[Learn More] vue.runtime.esm.js:6613
Loading mixed (insecure) active content “http://my.api.com/my-adminui/applications” on a secure page[Learn More] xhr.js:178
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://my.api.com/my-adminui/applications. (Reason: CORS request did not succeed).[Learn More]
Connection to server failed: Error: "Network Error"
	exports http://my.api.com/my-adminui/assets/js/chunk-vendors.1df687d0.js:14:65555
	onerror http://my.api.com/my-adminui/assets/js/chunk-vendors.1df687d0.js:28:91202
```

The main problem seems to be: the webserver is only accessible via https. An `apache proxy` handles the request and forwards it as a reverse proxy to `localhost:8080/my-adminui`.

With the reverse proxy configured as:
```
 	ProxyRequests Off
        ProxyPreserveHost On
        RequestHeader set X-Forwarded-Proto "https"
        Header edit Location ^http: https:
```
This worked in 2.0.4!! So configuration should be fine.

But not as of 2.1.1: now the adminui javascript probably thinks it is accessed via http only.
Strange is that it worked before, but stopped working in the latest release. How can this be fixed?

I tried setting `spring.boot.admin.ui.public-url=https://my.api.com` but that did not help in any way.

Interestingly the applications url `https://my.api.com/my-adminui/applications` is accessible just fine, and shows all my applications are UP correctly!

**Comment by joshiste** [comment]
Try configuring your application to respect the forward headers. See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server

**Comment by sddakoty** [comment]
Sorry, but your link is for an *embedded* tomcat webserver ("78. Embedded Web Servers"). Therefor any  `server.*` properties affect the application only in embedded mode.

But as said, I'm running the war file on a normal dedicated tomcat webserver! Therefore I set the reverse proxy configurations as stated above (eg `X-Forwarded-Proto`).
And also, it worked in all the previous versions. So I assume this is probably a bug due to some changes since spring-boot 2.1.x?

**Comment by sddakoty** [comment]
I could solve it adding the following to `server.xml` before AccessLogValve:
```
<Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="X-Forwarded-For"  protocolHeader="X-Forwarded-Proto" />
```

**Comment by najafian** [comment]
I have same issue with spring boot server admin to run resources such as *.js and *.css files. @membersound would you please tell me where can I find the `server.xml` to set those Items.

FYI: I have a spring boot application with the version `2.7.0` and and I an using `spring-boot-admin-starter-server` and i have reverse proxy with Apache2 server in my server.

Here I added these properties in my bootstrap.yml but it is not redirecting correctly, my configuration in Apache2 server is correct because when I run the resource link(js/css) directly in browser with Http, it will redirected to Https by Apache2 but not in spring boot.

```
server:
  port: ${PORT}
  use-forward-headers: true
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
```

Here is my browser's console 

```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://XXX/admin' was loaded over HTTPS, but requested an insecure stylesheet 'http://XXX/admin/assets/css/chunk-common.768fcb31.css'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by membersound** [comment]
You only have the `server.xml` when running a tomcat standalone.
