### ISSUE TITLE
Services that start with "down" health are never listed.

### ISSUE THREAD

**Issue by momothereal** [codecentric/spring-boot-admin#1036]
In Spring Boot Admin 2.1.1 and using Spring Cloud Discovery to list the instances. Spring Boot Admin will not list an instance if its status is `DOWN` at SBA's startup, or if the instance's first health check is `DOWN`. No event is logged in the Journal. An instance that is first healthy and then becomes `DOWN` is correctly displayed.

**Comment by joshiste** [comment]
I guess this is due to the fact that the underlying discovery implementation most likely doesn't report the instances being down. So they're not added to spring boot admin. SBA doesn't do any filtering here.
