### ISSUE TITLE
[Question]how can i get all STATUS_UP client in my server

### ISSUE THREAD

**Issue by jiangyitao** [codecentric/spring-boot-admin#1041]
server -> spring-boot-admin-starter-server
client -> spring-boot-admin-starter-client

i want to get STATUS_UP clients with my server code ,how?

thanks!

**Comment by joshiste** [comment]
Sorry I don't get your question. What do you want to achieve?

**Comment by jiangyitao** [comment]
> Sorry I don't get your question. What do you want to achieve?

Sorry, I didn't make it clear.My pom has added <dependency spring-boot-admin-starter-server/>

how can i get registered application instances in my code .

For example, implement some interfaces，or injected object.

thanks!

**Comment by joshiste** [comment]
All registered applications can be obtained via the `InstanceRegistry`
