### ISSUE TITLE
[Question] How can I set the http port to something other than 8080

### ISSUE THREAD

**Issue by robinroos** [codecentric/spring-boot-admin#1042]
Looking at this, but I have other services at 8080.  I'd like to know the .properties or .yml for making spring-boot-admin start at 8200

**Comment by TarunBhateja** [comment]
You can use" server.port" property in application.yml flie or application.properties file. eg server.port: 8081

**Comment by joshiste** [comment]
By the way. That's not a Spring Boot Admin question. Just use Spring Boot's `server.port` as mentioned by @TarunBhateja

**Comment by robinroos** [comment]
That's great, thanks guys.  I have the Admin app started and the clients successfully connected.
