### ISSUE TITLE
[Question] How to send the header parameters to a client application from spring boot admin ?

### ISSUE THREAD

**Issue by TarunBhateja** [codecentric/spring-boot-admin#1043]
Hello, 
I have a Spring boot application which have filter for every requests. I need to send a header parameter with every request in my application. I am not able to do it from SBA. Please help

**Comment by joshiste** [comment]
Add a `HeadersProvider` to your SBA server. See https://codecentric.github.io/spring-boot-admin/current/#customizing-headers

**Comment by TarunBhateja** [comment]
Thank you so much :)
