### ISSUE TITLE
OOM in io.micrometer.core.instrument.MeterRegistry#meterMap

### ISSUE THREAD

**Issue by youzipi** [codecentric/spring-boot-admin#1055]
I got OOM when using `spring-boot-admin`
after I analyze the heap dump.
I found the problem is the SimpleMeterRegistry.meterMap fill the memory and after many times GC, the map content still alive.
https://user-images.githubusercontent.com/5629307/50621747-e8d45b00-0f42-11e9-8fe2-f319a9dded80.png
![](https://user-images.githubusercontent.com/5629307/50582024-229d5700-0e9a-11e9-9e16-179d61bbe662.png)

![image](https://user-images.githubusercontent.com/5629307/50628280-695e8000-0f72-11e9-8fe9-45eafe418174.png)

![image](https://user-images.githubusercontent.com/5629307/50628558-86e01980-0f73-11e9-8a4e-79a5fcaf08f9.png)

I only found one way to clear the meterMap here: `io.micrometer.core.instrument.MeterRegistry#close`

```java
       /**
     * Closes this registry, releasing any resources in the process. Once closed, this registry will no longer
     * accept new meters and any publishing activity will cease.
     */
    @Override
    public void close() {
        if (closed.compareAndSet(false, true)) {
            synchronized (meterMapLock) {
                for (Meter meter : meterMap.values()) {
                    meter.close();
                }
            }
        }
    }
```
In `org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter`, the ·registry` not 
call `close` and from the name `MetricsWebFilter` I think it won't be destoried until the server close.

related code:
```java
	private void success(ServerWebExchange exchange, long start) {
		Iterable<Tag> tags = this.tagsProvider.httpRequestTags(exchange, null);
		this.registry.timer(this.metricName, tags).record(System.nanoTime() - start,
				TimeUnit.NANOSECONDS);
	}
```
I wonder where and when the `timer` here be released?
I do not start a spring-boot-admin-server.
I assume that the timer not be consumed because there is no server side to fetch it ? or there is a strategy  to clear these timer?

## environment
spring-boot-admin-client  2.0.1
spring-boot-actuator  2.0.0 RELEASE
micrometer-core  1.0.1

**Comment by joshiste** [comment]
Looking all at your screenshots and code I have no clue how this issue is related to Spring Boot Admin (SBA):
- The code you are talking about is from micrometer / spring boot (and not SBA)
- The URLs shown in the screenshots are not one of SBA

May be you wanted to open an issue on a different project?

**Comment by youzipi** [comment]
it's `spring-boot-actuator`'s problem,
PR here: https://github.com/spring-projects/spring-boot/pull/15609

**Comment by silh** [comment]
> it's `spring-boot-actuator`'s problem,
> PR here: [spring-projects/spring-boot#15609](https://github.com/spring-projects/spring-boot/pull/15609)

Referenced PR doesn't affect the files mentioned in this issue.
