### ISSUE TITLE
Notification is done even for the maven build

### ISSUE THREAD

**Issue by Kishn0211** [codecentric/spring-boot-admin#1063]
SBA version ,Spring Boot > 2.
When we enable slack/mail notification in the SBA , the client will notify the events  for   
maven clean install   (build).

**Comment by joshiste** [comment]
you should disable it for your tests - there is a property for that.

**Comment by Kishn0211** [comment]
Hi ,

Could you suggest what is the name of the property?

**Comment by joshiste** [comment]
see https://codecentric.github.io/spring-boot-admin/current/#slack-notifications

**Comment by Kishn0211** [comment]
> see https://codecentric.github.io/spring-boot-admin/current/#slack-notifications

Hi Joshite,

This tells  how to enable slack notification.
But there is no mention on the how to disable the notification  for maven clean build of the client.
![slack](https://user-images.githubusercontent.com/44531489/51041336-6262ed80-15c2-11e9-86cd-79795af5fe05.PNG).

**Comment by Kishn0211** [comment]
Hi Joshiste,

Thanks for your suggestion.
