### ISSUE TITLE
How to use pure spring mvc without webflux

### ISSUE THREAD

**Issue by TruthBean** [codecentric/spring-boot-admin#1066]
As the question say, how to use pure spring mvc without webflux. 
I use spring-boot-admin-starter-server 2.1.1 with spring-boot-starter-web 2.1.2, but admin depend spring-boot-starter-webflux, so what should i do，or it has to use webflux ?

**Comment by joshiste** [comment]
SBA depends on webflux in order to support servlet as well as nett. Also the reactive webclient is used for making the requests. So there is no way around using it.

**Comment by TruthBean** [comment]
I am sorry to tell you that reactor netty is not stable as tomcat or undertow, with visits and  concurrency grow, it throw exception so frequent, so SBA should support it

**Comment by TruthBean** [comment]
I have to say no working well with webflux，so frequently do it throw exception. Thus, project used sba in my company's code is rewrited without netty，I suggest the sba project should have a good way to supply webflux and servlet in one factory.
