### ISSUE TITLE
Prevent too much info shown in application list.

### ISSUE THREAD

**Issue by dacofr** [codecentric/spring-boot-admin#107]
First Thanks for your application for admin boot apps.

If endpoint /info expose some nested properties, then the vue in the "Applications" and in "Details" are little confusing when dealing with info properties. See screenshots.

In the main panel, is it possible to chose which properties to display in the "Info" column.
And in the detail panel, is it possible to improve better parsing like Health check?

![image](https://cloud.githubusercontent.com/assets/1257842/10031744/2fbeda60-617f-11e5-8640-0a3da226cc14.png)

![image](https://cloud.githubusercontent.com/assets/1257842/10031755/44cbf640-617f-11e5-84c9-8f5b9055849b.png)

![image](https://cloud.githubusercontent.com/assets/1257842/10031767/55042f28-617f-11e5-8ad6-a7268a27b423.png)

**Comment by joshiste** [comment]
With #104 I did a little work on this. In the current master the objetcts' properties will be flattened. E.g. in the overview `versions.springboot: 1.3.0.M5` will show up and for the details-page the table would have a row:

| | |
| --- | --- |
| git | branch: master<br>commit.id: e9015a<br>commit.time: 15.9.2015 11:21:58 |

would that suffice?

**Comment by joshiste** [comment]
closing due to missing feedback

**Comment by dacofr** [comment]
Sorry for may late response.and feedback.

The 1.3.0-SNAPSHOT works fine in my case, json is correctly flatten.

Any plan on release ? Maybe waiting for SpringBoot 1.3 release ?

An enhancement possible : capability to choose which information to display in the main page or standardize one (like version)
Because with lot of apps and lot of info, the result could be a huge page

**Comment by joshiste** [comment]
In the application list the version has a separate column. So i would suggest for the info-column we could display the first three "simple" infos and show an ellipsis if there is more. Clicking on the ellipsis will expand the infos.
I do not tend to make a default guess on what the user wants to see and currently the UI is only static and not configurable or easily customizable.

**Comment by joshiste** [comment]
>Any plan on release ? Maybe waiting for SpringBoot 1.3 release ?
The boot admin 1.3.0 will be released after boots 1.3.0 release.
I really didn't expected so much changes in the meantime. So I think we'll ship admin 1.2.4 when boot 1.2.7 is released.
