### ISSUE TITLE
(U) Clustering SBA with encryption

### ISSUE THREAD

**Issue by rhosman** [codecentric/spring-boot-admin#1072]
As far as I can tell I cannot encrypt traffic between hazelcast nodes without using the payed version.  I have spent quite a bit of time trying.  I would like to run SBA in a clustered setup but I have a requirement to encrypt all data at rest and in transit.  I am able to meet this requirement to my satisfaction through configuration for all other aspects of SBA.

This same requirement has prevented me from using hazelcast as a distributed cache within my application but there are several other options to fulfill that need.

To clarify a bit, I just want to be able to force any connections between nodes to use TLS1.2.

PS: I'm not interested in defending or discussing the need for encryption or ways to 'feel good' without using it as that seemed to be something that came up a lot when looking into doing this with hazelcast.

**Comment by joshiste** [comment]
I currently see only the following solutions to your problem:
1) Don't cluster at all. Tell the clients to register at both instances
2) Pay for hazelcast
3) Establish a ssh tunnel between the instances and let hazelcast replicate using this tunnel.
4) Implement your own `InstanceEventStore` which uses some encryption to replicate the data
