### ISSUE TITLE
Deploying Spring Boot Admin On Weblogic  401 unauthorized error

### ISSUE THREAD

**Issue by Thabizolo** [codecentric/spring-boot-admin#1074]
I have deployed a spring boot application onto to Weblogic when the client tries to register I keep on getting a 401 unauthorized error. i.e. 

Failed to register application as Application(name=Client, managementUrl=http://172.23.176.1:7001/helloworld/actuator, healthUrl=http://172.23.176.1:7001/helloworld/actuator/health, serviceUrl=http://172.23.176.1:7001/helloworld) at spring-boot-admin ([http://172.23.176.1:7001/admin/instances]): 401 Unauthorized

*********************************************************************
My application.yml file looks like this:

app:
  name: '@pom.artifactId@'
  description: '@pom.description@'
  version: '@pom.version@'

server.port: 7001
server:
  address: 127.0.0.1

# Security config
spring.security.user:
  name: admin
  password: admin

# Actuator config
management:
  endpoint:
    shutdown.enabled: true
    health.show-details: always
  endpoints.web.exposure.include: '*'

# Spring boot admin config
spring.boot.admin:
  context-path: /admin
  client:
    url: http://127.0.0.1:7001
    username: ${spring.security.user.name}
    password: ${spring.security.user.password}
    instance:
      name: ${app.name}
      metadata:
        user.name: ${spring.security.user.name}
        user.password: ${spring.security.user.password}
      service-base-url: http://127.0.0.1:7001

Is there something Im missing here ?

**Comment by Thabizolo** [comment]
Update managed to get it to work but now Im getting the following error:

https://stackoverflow.com/questions/54078233/error-resolving-template-instances-when-running-on-weblogic

**Comment by joshiste** [comment]
Sorry I'm no weblogic expert, I can't help you with that.

**Comment by silentFred** [comment]
@Thabizolo funny enough i'm getting the same issue where the health endpoint is not secured, works just fine running as standalone jar. Can access it just fine directly when running on weblogic, but for some odd reason SBA cannot access the health endpoint and I get prompted inside SBA on the instance page with the basic auth prompt on the proxied health call.

**Comment by silentFred** [comment]
Ok @Thabizolo the issue lies with Weblogic's default basic auth. You need to add the following property in your security-configuration directive in your domain config.xml

<enforce-valid-basic-auth-credentials>false</enforce-valid-basic-auth-credentials>
