### ISSUE TITLE
ui problem with health json string

### ISSUE THREAD

**Issue by lohcve** [codecentric/spring-boot-admin#1076]
I'm using fastjson，and when i visted "http://192.168.116.44:28088/actuator/health"，it returns json like this：
`{"details":{"diskSpace":{"details":{"total":253959147520,"free":50126434304,"threshold":10485760},"status":{"code":"UP","description":""}},"redis":{"details":{"version":"5.0.3"},"status":{"code":"UP","description":""}},"db":{"details":{},"status":{"code":"UNKNOWN","description":""}},"refreshScope":{"details":{},"status":{"code":"UP","description":""}}},"status":{"code":"UP","description":""}}`
**and the admin ui look like this：**

![Markdown](http://i1.bvimg.com/675771/141b8323a30afe16.png)

**Comment by joshiste** [comment]
We rely on the the default jackson json mapping configured by spring boot for the actuator endpoints. It would be to much effort to sort all variants of json encoders and options.

**Comment by joshiste** [comment]
If you can somehow align the json encoding for `org.springframework.boot.actuate.health.Status` like it is for jackson, the error should disappear.

**Comment by lohcve** [comment]
thanks,i have resolved the problem.

**Comment by mrwangyin** [comment]
> 
How can I solve this problem?

**Comment by erikpetzold** [comment]
@mrwangyin as written before, Spring Boot Admin requires the default json output of the actuators. Please do not change the ObjectMapper config for the actuators. If you use some other framework, make sure the json output is similar to the default.
In Spring Boot 3 there will be a separate ObjectMapper instance for the actuators (by Spring Boot itself) to enforce this.
