### ISSUE TITLE
Is there any interest in publishing a docker image?

### ISSUE THREAD

**Issue by jbedalov** [codecentric/spring-boot-admin#1077]
I was able to get something working pretty quickly but was there any interest in publishing an image to docker hub?

I've seen a few out there, this was had the most downloads but was very out of date https://hub.docker.com/r/aetas/spring-boot-admin-docker

Thanks!

**Comment by joshiste** [comment]
As there are too many options (eg. Authentication using Session, OAuth or JWT; Discovery using Eureka, Consul, Zookeeper...) that requires modification of the binaries I don't see any benefit in providing a docker image.
Also I don't see Spring Boot Admin as ready baked runtime, but more like a framework that can be customized and extended.
