### ISSUE TITLE
Not able to connect to client from docker

### ISSUE THREAD

**Issue by Kishn0211** [codecentric/spring-boot-admin#1080]
Hi,

Client side the have added the SBA client dependency 
           "<groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>2.0.4</version>"
and the  spring.boot.admin.client.url=http://localhost:8080 in property file.

Running the client locally i'm able to register with the server.
When run the same on docker i'm not able register and get the error on client side when its trying to register with spring boot admin
"([http://localhost:8080/instances]): I/O error on POST request for "http://localhost:8080/instances": Connection refused (Connection refused)
; nested exception is java.net.ConnectException: Connection refused (Connection refused). Further attempts are logged on DEBUG level."

Regards,

**Comment by joshiste** [comment]
If you get a connection refused. The client can't establish a tcp connection with the host. It's most likely that the the url to the admin server or the docker/container config  is wrong.

**Comment by Kishn0211** [comment]
Hi ,
Could you share the proper docker/container config .
