### ISSUE TITLE
Endpoint request paths like“instances/b1ccf01ebbb8/actuator/logFileType?logType=info” are not supported

### ISSUE THREAD

**Issue by SoftwareKing** [codecentric/spring-boot-admin#1081]
My Endpoint request paths is **logFileType?logType=info**，but don't supported
>Endpoint request paths like“**instances/b1ccf01ebbb8/actuator/logFileType?logType=info**”

**Comment by SoftwareKing** [comment]
![image](https://user-images.githubusercontent.com/6858857/51901395-89a72080-23f2-11e9-826c-0928268b70d1.png)

**Comment by joshiste** [comment]
The `logFileType` is a custom actuator endpoint? Can you make a request to `instances/b1ccf01ebbb8` and look if it's listed in the json?

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by SoftwareKing** [comment]
i can see result,@joshiste
![image](https://user-images.githubusercontent.com/6858857/52610218-3dacaf00-2ebb-11e9-8919-a870e9c859d7.png)

**Comment by SoftwareKing** [comment]
![image](https://user-images.githubusercontent.com/6858857/52610319-ab58db00-2ebb-11e9-9094-cc58203e3161.png)
@joshiste

**Comment by SoftwareKing** [comment]
but request http://localhost:8080/admin/instances/dc5a21d82a6d/actuator/logFileType?logType=info
![image](https://user-images.githubusercontent.com/6858857/52610474-389c2f80-2ebc-11e9-9a52-c5924dfa240f.png)

**Comment by joshiste** [comment]
make sure the endpoint is listed in the `endpoints` section of `/instances/b1ccf01ebbb8`
