### ISSUE TITLE
Docs: Note about monitor.read-timeout and database connection-timeout

### ISSUE THREAD

**Issue by sddakoty** [codecentric/spring-boot-admin#1082]
Please add a note to the docs targeting the global `monitor.read-timeout` in conjunction with the global `hikaricp` connection timeout.

The defaults are:
```
spring.boot.admin.monitor.read-timeout=10000
spring.datasource.hikari.connection-timeout=30000
```

Problem: when a db connection runs into a timeout, prior the SBA already ran into the web timeout exception of 10s. As a result, the application will be reported as `OFFLINE`, even though only the DB test connection takes too long.

Most SBA users will also make use of  `spring-boot-starter`, which uses`hikaricp` as the default connection pool, and thus having set the 30s db timeout by default.

I was not aware of this and wondered why my application has been shown as OFFLINE, even though all connections could pass. Then I found out that my failover/slave database connection exceeded the  `connection-timeout`. But as it is just the failover con, it's not critical. Anyhow having an application being shown as OFFLINE in that case was not that nice.

Hope you could add that into the docs somehow, so that other users might not run into the same issue.

**Comment by joshiste** [comment]
Imho if the health check can hit stale db connections, it is most likely that your users will do as well. So you'd better fix the underlying issue of the stale connections instead of raising the monitor read timeout.

Also you are describing a very special case, but it should be obvious that any health check wich might succeed, but doesn't finish in time will lead to a OFFLINE status report.

What currently comes to my mind if SBA should distinguish between OFFLINE (cannot connect to the address; connection timeout) and a TIMED OUT (could connect, but not responded in time; read timeout)...

**Comment by sddakoty** [comment]
Of course my users will hit those stale connections as well.
Anyways, if spring-boot users rely on both the spring-hikari and the spring-sba configuration, they might be confused as me that the application shows offline, even though it is working fine in general.

Offline state is eg if the *.war application is undeployed in tomcat and thus physically removed. Then SBA usually shows the OFFLINE state. I think, as you suggested, that should be the only case when offline is to be shown. So TIMEOUT could be a nice improvement.

**Comment by joshiste** [comment]
>Offline state is eg if the *.war application is undeployed in tomcat and thus physically removed. Then SBA usually shows the OFFLINE state.

When Tomcat itself is running and just your application was undeployed I'd expect a DOWN status as the Tomcat should respond with a 404.

**Comment by joshiste** [comment]
After having a night of sleep over this, I currently don't want to introduce a new TIMED_OUT status. The details of the OFFLINE status do contain an `error`-detail which tells you whether it was a connect  or a read timeout.

**Comment by sddakoty** [comment]
That's true indeed. Thanks for the discussion though!
