### ISSUE TITLE
For Spring Boot 1.x applications SBA probes for the specified endpoints using an OPTIONS request.

### ISSUE THREAD

**Issue by SoftwareKing** [codecentric/spring-boot-admin#1089]
For Spring Boot 1.x applications SBA probes for the specified endpoints using an OPTIONS request.
add EndPoint？
![image](https://user-images.githubusercontent.com/6858857/52621834-3bf6e180-2ee3-11e9-8176-0889cb136443.png)
de.codecentric.boot.admin.server.config.AdminServerProperties.java
```java
private String[] probedEndpoints = {"jardeps","appInfo","logfileType","health", "env", "metrics", "httptrace:trace", "httptrace", "threaddump:dump", "threaddump", "jolokia", "info", "logfile", "refresh", "flyway", "liquibase", "heapdump", "loggers", "auditevents", "mappings", "scheduledtasks", "configprops", "caches", "beans"};

```

**Comment by joshiste** [comment]
As  these are non-standard boot endpoints and SBA provides no views for them you need to configure it yourself using `spring.boot.admin.probed-endpoints`
