### ISSUE TITLE
使用spring boot admin，获取到最新注册到consul的服务

### ISSUE THREAD

**Issue by gxl191911** [codecentric/spring-boot-admin#1091]
您好，我现在的spring boo admin是使用consul服务发现的方式去监控应用的，但是我发现有俩种情况admin不会更新信息：
1. 当有新的服务注册到consul，admin不会显示这个新的服务
2. 已有的服务重启后，ip发生变化，这个时候admin保持的地址还是原来的ip地址

**Comment by joshiste** [comment]
Please use english.
