### ISSUE TITLE
new services are not registered using consul

### ISSUE THREAD

**Issue by gxl191911** [codecentric/spring-boot-admin#1092]
Hello, my current spring boo admin is using the method of consul service discovery to monitor the application, but I found that there are two situations where admin does not update the information:

1. When a new service is registered to consul, admin will not display this new service.
2. After the existing service is restarted, the ip changes. At this time, the address maintained by the admin is still the original ip address.

**Comment by joshiste** [comment]
Please make sure that the catalog watch (in SBA) recieves the update by setting the logger of `org.springframework.cloud.consul.discovery.ConsulCatalogWatch` to `TRACE`

**Comment by gxl191911** [comment]
> Please make sure that the catalog watch (in SBA) recieves the update by setting the logger of `org.springframework.cloud.consul.discovery.ConsulCatalogWatch` to `TRACE`

>
![image](https://user-images.githubusercontent.com/16099707/52759269-2ea63800-3046-11e9-8735-a9d8a181197b.png)
As shown above, I set `org.springframework.cloud.consul.discovery.ConsulCatalogWatch` to `TRACE`, my spring boot admin program log also shows that the new service demo-test is registered to consul. But spring boot admin The latest service demo-test is not displayed on ui, and the email notification I set is not received. Why is that?

**Comment by joshiste** [comment]
Could you please also set the `de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener` to `DEBUG`.

**Comment by zrd1314** [comment]
i have the same problem , Is there a solution?

**Comment by zrd1314** [comment]
When a new service is registered to consul, admin will not display this new service

**Comment by gxl191911** [comment]
> Could you please also set the `de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener` to `DEBUG`.

![image](https://user-images.githubusercontent.com/16099707/52845811-00f2e900-3143-11e9-91b6-fc022327e6b9.png)
As shown in the figure above, I debug the admin update mechanism in debug mode. When a new service comes in, there will be a heartbeat event triggered, and the DiscoveryClientConfigServiceBootstrapConfiguration class also performs the refresh() call in the above figure. The problem occurs in this refresh() method. The specific code is as follows:
  String serviceId = this.config.getDiscovery().getServiceId();
This line of code I think is used to get the list of current consul or newly registered service information. But what I see here is the service registered on consul, and it is the first service config-center of the service list. Instead of the newly registered service demo-test. See the image below:
![image](https://user-images.githubusercontent.com/16099707/52845840-10723200-3143-11e9-9851-56c4a60d6756.png)

**Comment by gxl191911** [comment]
> > Could you please also set the `de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener` to `DEBUG`.
> 
> ![image](https://user-images.githubusercontent.com/16099707/52845811-00f2e900-3143-11e9-91b6-fc022327e6b9.png)
> As shown in the figure above, I debug the admin update mechanism in debug mode. When a new service comes in, there will be a heartbeat event triggered, and the DiscoveryClientConfigServiceBootstrapConfiguration class also performs the refresh() call in the above figure. The problem occurs in this refresh() method. The specific code is as follows:
>   String serviceId = this.config.getDiscovery().getServiceId();
> This line of code I think is used to get the list of current consul or newly registered service information. But what I see here is the service registered on consul, and it is the first service config-center of the service list. Instead of the newly registered service demo-test. See the image below:
> ![image](https://user-images.githubusercontent.com/16099707/52845840-10723200-3143-11e9-9851-56c4a60d6756.png)

The spring boot version I am using is: 2.1.2.RELEASE,
The spring cloud version is: Greenwich.RELEASE,
The spring boot admi version is: 2.1.2.
How to solve the above problems?

**Comment by gxl191911** [comment]
> i have the same problem , Is there a solution?

I am still following up, but I have found the problem. And feedback was made. And the contemporary response. .

**Comment by zrd1314** [comment]
Why can't consul monitor service startup

**Comment by joshiste** [comment]
>the problem occurs in this refresh() method. The specific code is as follows:
  String serviceId = this.config.getDiscovery().getServiceId();

The code is not inside the SBA project, isn't it?

**Comment by gxl191911** [comment]
> > the problem occurs in this refresh() method. The specific code is as follows:
> >   String serviceId = this.config.getDiscovery().getServiceId();
> 
> The code is not inside the SBA project, isn't it?

After the SBA's consul client receives the heartbeat of the consul, it sends a HeartbeatEvent. Then I saw SBA's InstanceDiscoveryListener will listen for this HeartbeatEvent event and then update it. However, I found that this event is only refreshed in the DiscoveryClientConfigServiceBootstrapConfiguration, and the InstanceDiscoveryListener does not seem to be refreshed. Where is the problem?

**Comment by gxl191911** [comment]
> > > the problem occurs in this refresh() method. The specific code is as follows:
> > >   String serviceId = this.config.getDiscovery().getServiceId();
> > 
> > 
> > The code is not inside the SBA project, isn't it?
> 
> After the SBA's consul client receives the heartbeat of the consul, it sends a HeartbeatEvent. Then I saw SBA's InstanceDiscoveryListener will listen for this HeartbeatEvent event and then update it. However, I found that this event is only refreshed in the DiscoveryClientConfigServiceBootstrapConfiguration, and the InstanceDiscoveryListener does not seem to be refreshed. Where is the problem?

**Comment by gxl191911** [comment]
> > > the problem occurs in this refresh() method. The specific code is as follows:
> > >   String serviceId = this.config.getDiscovery().getServiceId();
> > 
> > 
> > The code is not inside the SBA project, isn't it?
> After the SBA's consul client receives the heartbeat of the consul, it sends a HeartbeatEvent. Then I saw SBA's InstanceDiscoveryListener will listen for this HeartbeatEvent event and then update it. However, I found that this event is only refreshed in the DiscoveryClientConfigServiceBootstrapConfiguration, and the InstanceDiscoveryListener does not seem to be refreshed. Where is the problem?

> After the SBA's consul client receives the heartbeat of the consul, it sends a HeartbeatEvent. Then I saw SBA's InstanceDiscoveryListener will listen for this HeartbeatEvent event and then update it. However, I found that this event is only refreshed in the DiscoveryClientConfigServiceBootstrapConfiguration, and the InstanceDiscoveryListener does not seem to be refreshed. Where is the problem?

In the case of debug debugging, I found that only the refresh mechanism in the InstanceDiscoveryListener will be used at startup, the debug level log is also generated, the colleague SBA will refresh the ui and send the mail; but it can be determined that when there is a new service registration When it comes to consul, the refresh function in InstanceDiscoveryListener is not executed, and the log is not printed.

**Comment by gxl191911** [comment]
> > the problem occurs in this refresh() method. The specific code is as follows:
> >   String serviceId = this.config.getDiscovery().getServiceId();
> 
> The code is not inside the SBA project, isn't it?

In the case of debug debugging, I found that only the refresh mechanism in the InstanceDiscoveryListener will be used at startup, the debug level log is also generated, the colleague SBA will refresh the ui and send the mail; but it can be determined that when there is a new service registration When it comes to consul, the refresh function in InstanceDiscoveryListener is not executed, and the log is not printed.

**Comment by zrd1314** [comment]
iI'm the same question，the new service registration When it comes to consul，the SBA no monitoring the new service

**Comment by gxl191911** [comment]
> > the problem occurs in this refresh() method. The specific code is as follows:
> >   String serviceId = this.config.getDiscovery().getServiceId();
> 
> The code is not inside the SBA project, isn't it?
After the SBA's consul client receives the heartbeat of the consul, it sends a HeartbeatEvent. Then I saw SBA's InstanceDiscoveryListener will listen for this HeartbeatEvent event and then update it. However, I found that this event is only refreshed in the DiscoveryClientConfigServiceBootstrapConfiguration, and the InstanceDiscoveryListener does not seem to be refreshed. Where is the problem?

In the case of debug debugging, I found that only the refresh mechanism in the InstanceDiscoveryListener will be used at startup, the debug level log is also generated, the colleague SBA will refresh the ui and send the mail; but it can be determined that when there is a new service registration When it comes to consul, the refresh function in InstanceDiscoveryListener is not executed, and the log is not printed.

**Comment by joshiste** [comment]
>When it comes to consul, the refresh function in InstanceDiscoveryListener is not executed, and the log is not printed.

Which leads me to the conclusion that the spring cloud consul discovery client does not properly publish the Heartbeat event... Can you verify that? If yes it has to be fixed there.

**Comment by joshiste** [comment]
@gxl191911 when having a close look at https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulCatalogWatch.java it looks to me that the `HeartBeatEvent` is only published when a new service name appears (and not when a new node appears)  - can you verify that?

**Comment by gxl191911** [comment]
> @gxl191911 when having a close look at https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulCatalogWatch.java it looks to me that the `HeartBeatEvent` is only published when a new service name appears (and not when a new node appears) - can you verify that?

I am sure that I am a new service, not a new node with an existing service.

**Comment by gxl191911** [comment]
> > When it comes to consul, the refresh function in InstanceDiscoveryListener is not executed, and the log is not printed.
> 
> Which leads me to the conclusion that the spring cloud consul discovery client does not properly publish the Heartbeat event... Can you verify that? If yes it has to be fixed there.

In debug mode, you can see it clearly. After the new service is registered, there will be a `HeartBeatEvent` issued, but the InstanceDiscoveryListener does not refresh here, and the debug level log is not printed. You can try it yourself.

**Comment by gxl191911** [comment]
> > > When it comes to consul, the refresh function in InstanceDiscoveryListener is not executed, and the log is not printed.
> > 
> > 
> > Which leads me to the conclusion that the spring cloud consul discovery client does not properly publish the Heartbeat event... Can you verify that? If yes it has to be fixed there.
> 
> In debug mode, you can see it clearly. After the new service is registered, there will be a `HeartBeatEvent` issued, but the InstanceDiscoveryListener does not refresh here, and the debug level log is not printed. You can try it yourself.

One of the existing services restarts, and the SBA will not update after the ip changes. This situation is the same as the new registration service in SBA.

**Comment by gxl191911** [comment]
> > When it comes to consul, the refresh function in InstanceDiscoveryListener is not executed, and the log is not printed.
> 
> Which leads me to the conclusion that the spring cloud consul discovery client does not properly publish the Heartbeat event... Can you verify that? If yes it has to be fixed there.

One of the existing services restarts, and the SBA will not update after the ip changes. This situation is the same as the new registration service in SBA.

**Comment by joshiste** [comment]
Using SBA 2.1.3 and Spring Cloud Consul 2.1.0.RELEASE I couldn't reproduce the issue. Registering additional services/nodes in consul are reflected in SBA.

**Comment by gxl191911** [comment]
> Using SBA 2.1.3 and Spring Cloud Consul 2.1.0.RELEASE I couldn't reproduce the issue. Registering additional services/nodes in consul are reflected in SBA.

Using SBA 2.1.2 and Spring Cloud Consul Greenwich.RELEASE I could reproduce the issue.

**Comment by gxl191911** [comment]
> Using SBA 2.1.3 and Spring Cloud Consul 2.1.0.RELEASE I couldn't reproduce the issue. Registering additional services/nodes in consul are reflected in SBA.

As shown above:
The consul registration list clearly shows that there are three services registered config-center, SBA, demo-test (excluding consul itself), the three service registration order is condig-center->SBA->demo-test.
But the SBA ui list can only see the registered config and itself, there is no demo-test, there is no log related to InstanceDiscoveryListener in the screenshot log, the log printed in the InstanceDiscoveryListener class can only be seen when the SBA is started. Go to the DEBUG log.

**Comment by gxl191911** [comment]
> > Using SBA 2.1.3 and Spring Cloud Consul 2.1.0.RELEASE I couldn't reproduce the issue. Registering additional services/nodes in consul are reflected in SBA.
>
![image](https://user-images.githubusercontent.com/16099707/53216078-5755af80-368e-11e9-9de0-52cadb202c35.png)
 
![image](https://user-images.githubusercontent.com/16099707/53216086-5b81cd00-368e-11e9-9066-74c090ba6767.png)
![image](https://user-images.githubusercontent.com/16099707/53216093-5fadea80-368e-11e9-8764-5ddffab19400.png)


> As shown above:
> The consul registration list clearly shows that there are three services registered config-center, SBA, demo-test (excluding consul itself), the three service registration order is condig-center->SBA->demo-test.
> But the SBA ui list can only see the registered config and itself, there is no demo-test, there is no log related to InstanceDiscoveryListener in the screenshot log, the log printed in the InstanceDiscoveryListener class can only be seen when the SBA is started. Go to the DEBUG log.

**Comment by joshiste** [comment]
I've improved the logging a bit. Could you please try the `2.1.4-SNAPSHOT` version from our snapshot (repo https://oss.sonatype.org/content/repositories/snapshots/) with TRACE logging for `org.springframework.cloud.consul.discovery.ConsulCatalogWatch` and `de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener` and provide the full log?

**Comment by joshiste** [comment]
closed due to missing feedback.

**Comment by gxl191911** [comment]
> closed due to missing feedback.
![image](https://user-images.githubusercontent.com/16099707/53724094-176ba500-3ea4-11e9-801b-3fe889950547.png)
As shown above:
I try to user 2.1.4-SNAPSHOT version, but SBA still do not update for ui

**Comment by joshiste** [comment]
Please somehow provide a project to reproduce the issue, as I can't...

**Comment by gxl191911** [comment]
> Please somehow provide a project to reproduce the issue, as I can't...

Yes, but how do I send my demo to you?

**Comment by gxl191911** [comment]
> Please somehow provide a project to reproduce the issue, as I can't...

I tried SBA again today. I have three services here: config-server, spring boot admin, demo-test. The order of the three services registered to consul is: config-center -> sba -> demo-test When config-center and sba are registered to consul's
When the new service demo-test is registered to consul, the code inside InstanceDiscoveryListener is fast:
Protected Mono<InstanceId> registerInstance(ServiceInstance instance) {
        Try {
            Registration registration = this.converter.convert(instance).toBuilder().source("discovery").build();
            Log.debug("Registering discovered instance {}", registration);
            Return this.registry.register(registration);
        } catch (Exception var3) {
            Log.error("Couldn't register instance for service ({})", this.toString(instance), var3);
            Return Mono.empty();
        }
    } is called, but the log printed here is: 'Registering discovered instance Registration(name=config-center, managementUrl=http://localhost:10011/actuator, healthUrl=http://localhost:10011/actuator/health , serviceUrl=http://localhost:10011/, source=discovery)'

The log shows that the service refreshed by SBA is config-center, not the new service demo-test. Can you try to solve it?

**Comment by gxl191911** [comment]
> Please somehow provide a project to reproduce the issue, as I can't...

I tried SBA again today. I have three services here: config-server, spring boot admin, demo-test. The order of the three services registered to consul is: config-center -> sba -> demo-test When config-center and sba are registered to consul, I can see that sba's ui has a service config-center displayed, but when the new service demo-test is registered to consul, the code inside InstanceDiscoveryListener is fast:

Protected Mono<InstanceId> registerInstance(ServiceInstance instance) {
        Try {
            Registration registration = this.converter.convert(instance).toBuilder().source("discovery").build();
            Log.debug("Registering discovered instance {}", registration);
            Return this.registry.register(registration);
        } catch (Exception var3) {
            Log.error("Couldn't register instance for service ({})", this.toString(instance), var3);
            Return Mono.empty();
        }
    } is indeed called, but the log printed here is: 'Registering discovered instance Registration(name=config-center, managementUrl=http://localhost:10011/actuator, healthUrl=http://localhost:10011/actuator/ Health, serviceUrl=http://localhost:10011/, source=discovery)'.

The log shows that the service refreshed by sba is config-center, not the new service demo-test. Can you try to solve it?

**Comment by joshiste** [comment]
> Can you try to solve it?

Only if you provide a project to reproduce the issue.

**Comment by joshiste** [comment]
> Yes, but how do I send my demo to you?

just upload it as zip-file here (via drag 'n' drop)

**Comment by gxl191911** [comment]
> > Yes, but how do I send my demo to you?
> 
> just upload it as zip-file here (via drag 'n' drop)

[admin-demo.zip](https://github.com/codecentric/spring-boot-admin/files/2935080/admin-demo.zip)
This zip file contains three services that I debug locally. You can try it.

**Comment by joshiste** [comment]
Any particular order for starting the services?

**Comment by gxl191911** [comment]
Config-center—>sba—>demo

**Comment by gxl191911** [comment]
> Any particular order for starting the services?

Need consul, have you tried it?

**Comment by joshiste** [comment]
The new service is reported to SBA, but the discovery client doesn't report the new instance.
If you set `spring.cloud.consul.discovery.query-passing=false` the service instance is registered properly.

**Comment by athishsreeram** [comment]
heartbeat url is not working if i have https url in consul how do i configure that to support https
