### ISSUE TITLE
Document support usage behind HTTPS

### ISSUE THREAD

**Issue by favetelinguis** [codecentric/spring-boot-admin#1093]
** Enhancement **
Currently we are running our spring boot services as AWS fargate tasks using HTTPS together with an ALB. When accessing SBA we are getting mixed content errors. Since running with HTTPS is standard thees days it would be nice with documentation on how to set this up for SBA since we have not been able to find any resources online for how to do this.

**Comment by joshiste** [comment]
See https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server
