### ISSUE TITLE
Spring boot Admin and Kubernetes and all namespaces discovery

### ISSUE THREAD

**Issue by marcin-kasinski** [codecentric/spring-boot-admin#1095]
I've tried Spring Boot Admin with with spring-cloud-starter-kubernetes.

I can discovery services from the namespace I installed Spring Boot Admin Pod.

How can I discover services from all namespaces?
Is there any config parameter?

**Comment by joshiste** [comment]
Please investigate spring-cloud-kubernetes for that as SBA just picks up all instances retrieved via the discovery client
