### ISSUE TITLE
RestTemplateBuilder is missing, reactive client app wont start

### ISSUE THREAD

**Issue by Ben-Mark** [codecentric/spring-boot-admin#1099]
SpringBoot version: 2.1.2.RELEASE
SpringBoot Admin 2.1.2

Running both spring boot admin server and my spring boot application on localhost for just testing the admin ui, but I fail to register to the admin server with the following exception:

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method registrator in de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfiguration required a bean of type 'org.springframework.boot.web.client.RestTemplateBuilder' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'restTemplateBuilder' in 'RestTemplateAutoConfiguration' not loaded because NoneNestedConditions 1 matched 0 did not; NestedCondition on RestTemplateAutoConfiguration.NotReactiveWebApplicationCondition.ReactiveWebApplication found ConfigurableReactiveWebEnvironment

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.boot.web.client.RestTemplateBuilder' in your configuration.

Process finished with exit code 1

**Comment by joshiste** [comment]
Please provide a project to reproduce the problem. 
I just generated a off-the-shelf project on start.spring.io and everything is working fine.

**Comment by joshiste** [comment]
closed due to missing feedback
