### ISSUE TITLE
client not has fixed ip

### ISSUE THREAD

**Issue by xylangyan** [codecentric/spring-boot-admin#110]
I found the service side can take the initiative to call the client url,
But in most cases, the server runs on the Internet and have a fixed IP, but the client does not,
Thus, the server can not monitor the client's condition.
Can I go to communicate with each other via JMS middleware like?

**Comment by joshiste** [comment]
Currently this is not possible. And I don't think we won't support this in the future.
You somehow have to tunnel the http via jms - which sounds crazy. 

But I wonder why you just don't make use of a dynamic dns service and register the client with the dynamic dns-name. You need to set `spring.boot.admin.client.managementUrl` and `spring.boot.admin.client.healthUrl` on the client.
Or you have to remove the old registration and make a ner registration whenever your client IP changes
