### ISSUE TITLE
Spring Boot Admin 2.1.3 Environment Manager is no display

### ISSUE THREAD

**Issue by jarvis0325** [codecentric/spring-boot-admin#1100]
Hi, My Spring Boot Admin Server Version is 2.1.3 , when use Environment is no display

![image](https://user-images.githubusercontent.com/8055266/52933180-63d7c080-338d-11e9-8eee-e2c80ad7a638.png)

I check  chrome  network  res is correct. 

![image](https://user-images.githubusercontent.com/8055266/52933284-c92bb180-338d-11e9-80e9-253e0ec1642b.png)

![image](https://user-images.githubusercontent.com/8055266/52933312-dea0db80-338d-11e9-92b8-953fe996168d.png)

**Comment by joshiste** [comment]
You're using snake casing for your json. SBA relies on the default format.

**Comment by jarvis0325** [comment]
is work ok ,   add LOWER_CAMEL_CASE in client


	@Bean
	public MappingJackson2HttpMessageConverter actuatorHttpMessageConverter() {
		MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter(
				new Jackson2ObjectMapperBuilder()
                .propertyNamingStrategy(PropertyNamingStrategy.LOWER_CAMEL_CASE).build());
		converter.setSupportedMediaTypes(Collections.singletonList(MediaType.parseMediaType(ActuatorMediaType.V2_JSON)));
		return converter;
	}
