### ISSUE TITLE
Spring boot admin with blue/green PCF deployments

### ISSUE THREAD

**Issue by itsPoo** [codecentric/spring-boot-admin#1101]
Hi,

I have implemented Spring boot Admin client & server in my project and its successfully registering-an-application on the Spring boot Admin UI.

We are using PCF env for production/QA. Whenever application is deployed from PCF blue region to PCF green region it does not show the updates on the Spring boot Admin UI and we end up restaging all our applications on the production during deployment time. We would not want to do this activity. I understand Spring Boot application auto-registers when the applicationContext is started and ready and this does not happen for PCF Blue to PCF Green deployments.

Is there a solution already there in place or does it need any enhancement to the framework?

Thanks for helping.
Poonam

**Comment by joshiste** [comment]
>I have implemented Spring boot Admin client & server in my project and its successfully registering-an-application on the Spring boot Admin UI.

Which version are you using?

> Whenever application is deployed from PCF blue region to PCF green region it does not show the updates on the Spring boot Admin UI

Do you miss the new version information or do you miss entire services? Do the instances from blue and green register at the same spring boot admin instance? Or do you use different admin servers for each region?

> I understand Spring Boot application auto-registers when the applicationContext is started and ready and this does not happen for PCF Blue to PCF Green deployments.

In fact (if you use spring-boot-admin-client) the application uses a scheduled task and registers over and over again.

**Comment by itsPoo** [comment]
Thank you so much for responding. Please find my answers in italics below.

Overall I didn't yet understand your exact problem so here are some questions:

> I have implemented Spring boot Admin client & server in my project and its successfully registering-an-application on the Spring boot Admin UI.

Which version are you using? 
_(Spring-boot-admin-server - version 1.5.1) (Spring-boot-admin-client - version 1.5.7)_

> Whenever application is deployed from PCF blue region to PCF green region it does not show the updates on the Spring boot Admin UI

Do you miss the new version information or do you miss entire services? _In green region I miss seeing entire services_

Do the instances from blue and green register at the same spring boot admin instance? _We have Jenkins pipeline which first deploys in blue region and then to green region for any environment. When blue pipeline step is completed, it registers on admin server and it shows the new version and also no of instances correctly. When the pipeline moves from blue to green region, it stops the blue services (which is correct) but it does not show the green services at all._

Or do you use different admin servers for each region? _Each region (dev/qa/prod) has its own Spring-boot-admin-server application deployed._

> I understand Spring Boot application auto-registers when the applicationContext is started and ready and this does not happen for PCF Blue to PCF Green deployments.

In fact (if you use spring-boot-admin-client) the application uses a scheduled task and registers over and over again. _Then why my client is not registering over and over again? What am I missing?_

**Comment by joshiste** [comment]
> Then why my client is not registering over and over again? What am I missing?

Try setting `de.codecentric.boot.admin.client.registration.ApplicationRegistrator` to `DEBUG` it may give you some insights

> (Spring-boot-admin-server - version 1.5.1) (Spring-boot-admin-client - version 1.5.7)

I strongly advise you to upgrade to a 2.x version as it does have better support for CF

**Comment by itsPoo** [comment]
I did set the de.codecentric.boot.admin.client.registration.ApplicationRegistrator to Debug and I see everytime the instance routes from blue to green, it does keep registering with [registrationTask1] [de.codecentric.boot.admin.client.registration.ApplicationRegistrator] - Application refreshed itself as 4b287e58

I was trying the approach to invoke a rest service after each Blue/Green deployment which would invoke RegistrationApplicationListener.startRegisterTask(). Will this work? 

I cannot update Spring boot Admin to 2.X as it would require all my applications also to be upgraded to Spring boot 2.X. I also read (http://codecentric.github.io/spring-boot-admin/current/#monitoring-spring-boot-1.5.x) does it mean only Spring boot Admin should be upgraded to 2.X and Client can stay on 1.5.X?

**Comment by joshiste** [comment]
> Spring boot Admin should be upgraded to 2.X and Client can stay on 1.5.X?

yes.

>[de.codecentric.boot.admin.client.registration.ApplicationRegistrator] - Application refreshed itself as 4b287e58
I was trying the approach to invoke a rest service after each Blue/Green deployment which would invoke RegistrationApplicationListener.startRegisterTask(). Will this work?

When the registering task is running, starting it has no effect. Did you cross check that the services are registering at the correct instance?

**Comment by itsPoo** [comment]
When the registering task is running, starting it has no effect. Did you cross check that the services are registering using the correct `spring.boot.admin.url`?

Both my Blue & Green instances should register to the same spring.boot.admin.url as the code package is same and its declared once only.

Futher more to this: When blue registers it shows Application refreshed itself as 232a8ac2 (my app instance id) - which is correct and it shows on my admin UI also.

Then when Blue -> Green deployment happens I see in logs Updated app with guid 6d685f0e-6041-424d-bb77-8f7ead050a9e ({"name"=>"billing-dev"}) and Application refreshed itself as 232a8ac2 (my app instance id).

This is correct, as the when blue -> green deployment happens, the same instance becomes green. So the instance id should remain same.

Looks like the problem is with my Admin server, its not showing the instance registered rather than shows it offline.  Which admin server logs can be enabled to see if Admin server is picking up or not?

I really appreciate your help on this.
Thanks,
Poonam.

**Comment by joshiste** [comment]
So do your applications get a new name when going from blue to green?

**Comment by itsPoo** [comment]
Yes, the name in Blue is billing-dev-candidate and the name in Green is billing-dev.
When PCF deploys from Blue to Green, it updates the route and the name of the application. 
Instance remains same, it will not be restarted and there would be zero impact to live traffic.

Currently we are restaging each application after blue->green deployments, just for Spring-boot-Admin to show the green instances registered. Thats why I want to find out if its possible not to restage applications after blue->green deployment coz its like an add on chore for us.

**Comment by joshiste** [comment]
>When PCF deploys from Blue to Green, it updates the route and the name of the application.
Instance remains same, it will not be restarted and there would be zero impact to live traffic.

Do you reconfigure the application at runtime? Are you using the Spring Cloud's `@RefreshScope`?
The sba-client needs to be aware of the new name (by reconfiguring `spring.boot.admin.client.instance.name`).

**Comment by itsPoo** [comment]
The sba-client needs to be aware of the new name (by reconfiguring `spring.boot.admin.client.instance.name`). How can this be done? Is application restart/restage the only option?

Do you reconfigure the application at runtime? Yes we reconfigure application at runtime, updating the app route and name of the application.

Are you using the Spring Cloud's `@RefreshScope`? What should I do @RefreshScope?

**Comment by joshiste** [comment]
> **How can this be done? Is application restart/restage the only option?**

No you could use Spring Cloud's `@RefreshScope`. See https://cloud.spring.io/spring-cloud-static/Greenwich.RELEASE/single/spring-cloud.html#_environment_changes

> **Yes we reconfigure application at runtime, updating the app route and name of the application.**

So this means you're updating the `spring.appliacation.name` property? Did you check the env endpoint for this?

**Comment by joshiste** [comment]
close due to missing feedback
