### ISSUE TITLE
Spring Boot Admin only showing health

### ISSUE THREAD

**Issue by alexanderehi** [codecentric/spring-boot-admin#1102]
I just upgraded spring boot and spring boot admin server from 1.5.9 to 2.1.1. I am using the spring boot admin start client for registration, also v. 2.1.1. In my client application.properties i have spring.boot.admin.client.url=http://localhost:8090 and management.endpoints.web.exposure.include=*. When I boot up, the client app outputs : "Application registered itself as bc19fcb087b5". 

HOWEVER, the spring admin UI only shows the health, and nothing else. I dont know why it is not getting the other actuator enpoints. If I browse to the client actuator endpoint like "http://localhost:8080/actuator/metrics", or any other endpoint, all the information is there. So i don't think it is a security thing. One more piece of information is in the spring admin console I am getting the messages 
"java.io.IOException: An established connection was aborted by the software in your host machine" 
and 
".w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]". 

I will post a screen shot of what the admin console looks like with only the health showing.
Please HELP, this has been a very inconvenient problem for me as this upgrade has taken WAY too long now.
![spring-boot-admin-2 1 1-only_health](https://user-images.githubusercontent.com/47869144/53200495-49991f00-35e7-11e9-95b7-1238440b3604.PNG)
Here is a screen shot of the env actuator endpoint verifying it is open with security
![spring-boot-admin-env](https://user-images.githubusercontent.com/47869144/53200665-bb716880-35e7-11e9-9a78-3dbc4093de55.PNG)

**Comment by joshiste** [comment]
SBA queries the `/actuator` endpoint to index all the actuator endpoints listed there. Make sure your security config allows accessing it.

**Comment by alexanderehi** [comment]
thanks for the feedback. In my security config i opened the actuator path with "/actuator/**". If I browse to "localhost:8080/actuator" I get a list of all of the actuator endpoints. I can also click the button to achieve the same from the spring boot admin ui.

**Comment by joshiste** [comment]
> I can also click the button to achieve the same from the spring boot admin ui.

???

**Comment by alexanderehi** [comment]
I just meant that I can click that middle button from the ui to see the list of available actuator endpoints.
![actuator-buttons](https://user-images.githubusercontent.com/47869144/53206992-19a64780-35f8-11e9-8dc2-8efa265455f7.PNG)

**Comment by joshiste** [comment]
Is there any error logged in the SBA server log?

**Comment by joshiste** [comment]
Could you provide a project to reproduce the issue?

**Comment by alexanderehi** [comment]
I would share the project, however it is confidential to my organization. I apologize, hopefully we can narrow the problem down without a providing a full project.

the only errors I am getting on the SBA server is:
"java.io.IOException: An established connection was aborted by the software in your host machine" and 
".w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]"
On the client side I get:
"o.s.b.a.audit.listener.AuditListener     : AuditEvent [timestamp=2019-02-21T20:48:10.394Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]"

I am not sure why the client is audit event is throwing access denied, as I do not have security set up on those endpoints right now.

**Comment by joshiste** [comment]
>I would share the project, however it is confidential to my organization.

Are you including the SBA into you business application? Please don't do that.

>java.io.IOException: An established connection was aborted by the software in your host machine

Is there any special firewall (or WAF; or special servlet filters) in place that could cause this?

>.w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]

Did you observe any HTTP 406 responses?

**Comment by alexanderehi** [comment]
The SBA and client are 2 separate app projects. I did not see any 406 status codes. And on the servers, there should not be any problem with the network, as before upgrading the SBA and client from 1.5.9 to 2.1.1, they communicated well. Right now I am just testing on localhost SBA port 8090 and client on 8080, which also worked just fine on the old version.

**Comment by alexanderehi** [comment]
now it looks like the client is trying to register at the endpoint "/instances". So in my case right now http://localhost:8090/instances. is that correct for registration?

**Comment by joshiste** [comment]
> http://localhost:8090/instances. is that correct for registration?

yes. the path has changed with 2.0.x

**Comment by alexanderehi** [comment]
Have you came across anyone else having this issue where SBA only grabs the "/actuator/health", but does not hit any other actuator endpoints or display any other tabs other than health? It does not seem like the SBA is even attempting to grab any other data from the client. I really appreciate your help with this, it has been frustrating me for a while.

**Comment by joshiste** [comment]
The admin discovers the endpoint either via querying the actuator-index or by probing the different endpoints.
You could set the loggers `de.codecentric.boot.admin.server.services.EndpointDetector` and `de.codecentric.boot.admin.server.services.endpoints` to `TRACE` to see what happens...

**Comment by joshiste** [comment]
close due to missing feedback

**Comment by manojprasad96** [comment]
I have the same problem as mentioned by @alexanderehi can u plz help me with it.

**Comment by manojprasad96** [comment]
In network call it is only hitting health endpoint. I have given management.endpoints.web.exposure.include=* in my application.properties.
plz help me asap.

**Comment by manojprasad96** [comment]
But i was able to access the actuator in browser from my client url

**Comment by alexanderehi** [comment]
@manojprasad96 I was able to solve my issue. We were using hazelcast to sync data between our multiple spring admin instances. When migrating to 2.0, I overlooked the hazelcast config changes in the migration guide. After updating the hazelcast config, everything is working properly.

**Comment by manojprasad96** [comment]
@alexanderehi  Thanks for your reply. But I am not using hazelcast, and that i am using client version and server version as 2.0.2. I tried using that guide yet same result. I tried to print props application in vue js custom tab the result is given below: 
{
        "name": "MAN",
        "buildVersion": null,
        "status": "UP",
        "statusTimestamp": "2019-07-12T06:25:10.873Z",
        "instances": [
            {
                "id": "98fe72948ac9",
                "version": 1,
                "registration": {
                    "name": "MAN",
                    "managementUrl": "http://manoj-prasad6.loc/man/actuator",
                    "healthUrl": "http://manoj-prasad6.loc/man/actuator/health",
                    "serviceUrl": "http://manoj-prasad6.loc/man",
                    "source": "http-api",
                    "metadata": {
                        "startup": "2019-07-12T11:55:06.506+05:30"
                    }
                },
                "registered": true,
                "statusInfo": {
                    "status": "UP",
                    "details": {}
                },
                "statusTimestamp": "2019-07-12T06:25:10.873Z",
                "info": {},
                "endpoints": [
                    {
                        "id": "health",
                        "url": "http://manoj-prasad6.loc/man/actuator/health"
                    }
                ],
                "buildVersion": null
            }
        ]
    }
But when i create a sample app its coming as below:
{
        "name": "Admin_Test",
        "buildVersion": null,
        "status": "UP",
        "statusTimestamp": "2019-07-12T06:24:10.647Z",
        "instances": [
            {
                "id": "430dafda3bfa",
                "version": 3,
                "registration": {
                    "name": "Admin_Test",
                    "managementUrl": "http://192.168.51.221:9095/actuator",
                    "healthUrl": "http://192.168.51.221:9095/actuator/health",
                    "serviceUrl": "http://192.168.51.221:9095/",
                    "source": "http-api",
                    "metadata": {
                        "startup": "2019-07-12T11:30:19.902+05:30"
                    }
                },
                "registered": true,
                "statusInfo": {
                    "status": "UP",
                    "details": {
                        "diskSpace": {
                            "status": "UP",
                            "details": {
                                "total": 250790436864,
                                "free": 145570467840,
                                "threshold": 10485760
                            }
                        }
                    }
                },
                "statusTimestamp": "2019-07-12T06:24:10.647Z",
                "info": {
                    "doc": "Admin Test"
                },
                "endpoints": [
                    {
                        "id": "httptrace",
                        "url": "http://192.168.51.221:9095/actuator/httptrace"
                    },
                    {
                        "id": "loggers",
                        "url": "http://192.168.51.221:9095/actuator/loggers"
                    },
                    {
                        "id": "health",
                        "url": "http://192.168.51.221:9095/actuator/health"
                    },
                    {
                        "id": "customtab1",
                        "url": "http://192.168.51.221:9095/actuator/customtab1"
                    },
                    {
                        "id": "env",
                        "url": "http://192.168.51.221:9095/actuator/env"
                    },
                    {
                        "id": "heapdump",
                        "url": "http://192.168.51.221:9095/actuator/heapdump"
                    },
                    {
                        "id": "mappings",
                        "url": "http://192.168.51.221:9095/actuator/mappings"
                    },
                    {
                        "id": "scheduledtasks",
                        "url": "http://192.168.51.221:9095/actuator/scheduledtasks"
                    },
                    {
                        "id": "configprops",
                        "url": "http://192.168.51.221:9095/actuator/configprops"
                    },
                    {
                        "id": "beans",
                        "url": "http://192.168.51.221:9095/actuator/beans"
                    },
                    {
                        "id": "threaddump",
                        "url": "http://192.168.51.221:9095/actuator/threaddump"
                    },
                    {
                        "id": "metrics",
                        "url": "http://192.168.51.221:9095/actuator/metrics"
                    },
                    {
                        "id": "conditions",
                        "url": "http://192.168.51.221:9095/actuator/conditions"
                    },
                    {
                        "id": "auditevents",
                        "url": "http://192.168.51.221:9095/actuator/auditevents"
                    },
                    {
                        "id": "shutdown",
                        "url": "http://192.168.51.221:9095/actuator/shutdown"
                    },
                    {
                        "id": "jolokia",
                        "url": "http://192.168.51.221:9095/actuator/jolokia"
                    },
                    {
                        "id": "info",
                        "url": "http://192.168.51.221:9095/actuator/info"
                    }
                ],
                "buildVersion": null
            }
        ]
    }
But i was able to get logger ,info and other endpoint by normal web browser call like:
 http://manoj-prasad6.loc/man/actuator/env

**Comment by manojprasad96** [comment]
Even I checked the network call in inspect element it is only calling health endpoint. But not call other endpoints. Thanks for your reply in advance.

**Comment by manojprasad96** [comment]
@joshiste can u plz help me with this

**Comment by Dromzel** [comment]
@manojprasad96 Setting the property "management.endpoint.health.show-details=always" worked for me to show missing endpoints in spring boot admin 2.x.

**Comment by benvindo** [comment]
You need make the actuator endpoints accessible, this way:

.antMatchers(HttpMethod.GET, "/actuator/**").permitAll() 

don't put "/actuator/*"

**Comment by veerumallavarapu** [comment]
> Is there any error logged in the SBA server log?

Hi Joshiste

I have a basic question.  How does spring boot admin is allowed to make calls to services registered from public URL? as all the instances are restricted public access via IP Address
