### ISSUE TITLE
SBA 2.1.2 can not update ui

### ISSUE THREAD

**Issue by gxl191911** [codecentric/spring-boot-admin#1103]
![image](https://user-images.githubusercontent.com/16099707/53216198-cd5a1680-368e-11e9-93ca-abab43dd7f9e.png)
![image](https://user-images.githubusercontent.com/16099707/53216201-d0550700-368e-11e9-808c-b0c40499dd5f.png)
![image](https://user-images.githubusercontent.com/16099707/53216211-d34ff780-368e-11e9-9cb5-af0355ac64de.png)

As shown above:
The consul registration list clearly shows that there are three services registered config-center, SBA, demo-test (excluding consul itself), the three service registration order is condig-center->SBA->demo-test.
But the SBA ui list can only see the registered config and itself, there is no demo-test, there is no log related to InstanceDiscoveryListener in the screenshot log, the log printed in the InstanceDiscoveryListener class can only be seen when the SBA is started. Go to the DEBUG log.

**Comment by joshiste** [comment]
duolicate of #1092
