### ISSUE TITLE
Health show which message is Unauthorized

### ISSUE THREAD

**Issue by tutuerhao** [codecentric/spring-boot-admin#1106]
Unauthorized
--

![image](https://user-images.githubusercontent.com/29938085/53317520-e836c000-3906-11e9-837f-26cd536beca8.png)

**Comment by tutuerhao** [comment]
how to solve  when project has content-path..

**Comment by joshiste** [comment]
Please have a look at the security section of our guide https://codecentric.github.io/spring-boot-admin/current/#securing-spring-boot-admin
