### ISSUE TITLE
cannot connection to gateway

### ISSUE THREAD

**Issue by WunHwanTseng** [codecentric/spring-boot-admin#1109]
my spring cloud version is Greenwich.RELEASE，but admin can not connection to gateway

**Comment by joshiste** [comment]
Please provide a proper explanation and more details of your problem. With this little information I cannot help you. At best provide a project to reproduce the problem.

**Comment by WunHwanTseng** [comment]
> Please provide a proper explanation and more details of your problem. With this little information I cannot help you. At best provide a project to reproduce the problem.

sorry，my mistake。Its work now
