### ISSUE TITLE
Eureka statusPageUrlPath and healthCheckUrlPath not taken into consideration

### ISSUE THREAD

**Issue by sfat** [codecentric/spring-boot-admin#111]
Hi,
Basically I'm trying to change the status page url and health check url since I've added 
```
server:
   contextPath: /blah
````
But in ```ApplicationDiscoveryListener.convert()``` the urls are not taken into consideration.
Any thoughts on this? Is this working as-is and there is a workaround to take the correct /health url because as for now, my service looks OFFLINE in spring-boot-admin.

**Comment by joshiste** [comment]
Problem here is that spring clouds ServiceInstance-interface does not give access to all informations from the eureka service. I tried to stay independent from spring-cloud-netfilx to support easily other implementations.

What you can do is override the applicationDiscoveryListener-bean and run your own conversion.

**Comment by joshiste** [comment]
duplicates #94 somehow
