### ISSUE TITLE
Cache metrics not shown when 'misses' are not reported

### ISSUE THREAD

**Issue by tomd8451** [codecentric/spring-boot-admin#1110]
### Details and steps to reproduce
An application that serves cache metrics, but doesn't expose misses will result in the graph serving a 404 error. Register an Spring Boot application that serves a /metrics/cache.gets endpoint with 'hit' but not 'miss'.

It would be beneficial if `miss` could also be disabled similar to the `size` metric so that a graph of `hit` is still available. Possibly make the graph fail gracefully by checking that the 'miss' tag exists before attempting the request.

### Sample application
[SpringBootAdminHazelcastApplication](https://github.com/tomd8451/spring-boot-admin/tree/cache-404-issue) 

### Screenshot of error
![Image of Hazelcast Cache Misses 404](https://raw.githubusercontent.com/tomd8451/spring-boot-admin/cache-404-issue/images/screenshot-hazelcast_misses_error.png)

**Comment by joshiste** [comment]
Thanks for the accurate description and the sample project. Was fun to fix it!

**Comment by tomd8451** [comment]
Thank you for the rapid fix!
