### ISSUE TITLE
/actuator/bus-refresh is not exposed with spring-boot-admin-starter-client 

### ISSUE THREAD

**Issue by guerricm** [codecentric/spring-boot-admin#1111]
Bug report
spring-cloud-version: Greenwich.RELEASE
spring-boot-version: 2.1.3.RELEASE
spring-boot-admin-version: 2.1.3

here is an example :
https://github.com/guerricm/spring-cloud-config-bus-refresh-example.git

if you comment in the pom.xml of `department-service` or `employee-service`
```
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-starter-client</artifactId>
</dependency>
```
applications expose the actuator `/bus-refresh`
![image](https://user-images.githubusercontent.com/20113664/51541311-ce621300-1e58-11e9-86a9-f793f6b2adf5.png)

if you uncomment the dependency  `spring-boot-admin-starter-client`, the actuator is not exposed

**Comment by joshiste** [comment]
Thanks for the detailed bug report. 
After investigating the issue, I filed https://github.com/spring-cloud/spring-cloud-bus/issues/151 in spring-cloud-bus as the problem is not caused by spring boot admin.
