### ISSUE TITLE
Long migration filenames are causing flyway tab to look broken

### ISSUE THREAD

**Issue by klopfdreh** [codecentric/spring-boot-admin#1119]
Spring Boot Admin version: 2.0.2

If you have long filenames that were executed the flyway migration view looks broken. 

<img width="1333" alt="screen shot 2019-03-08 at 10 34 17 am" src="https://user-images.githubusercontent.com/980773/54020512-3b720380-418e-11e9-8cf8-592e8fa5e966.png">

I think there are two ways to fix this:
1. word-wrap: break-word; on the td which is causing the issue (I think this one should be preferred) a short look into the css: it should be .table td { word-wrap: break-word; } (to not cause the th fields to be word-wrapped)
2. do not set the max with for the element that is containing the table

**Comment by klopfdreh** [comment]
I had a closer look at this now and this seems to be a bit more complex.

I just tried around a bit and when I set the div with the class "card panel migration" to overflow: auto and change the top:140px to top:0 of the header with the class "card-header panel__header--sticky" you can scroll the panel sidewise.

But I don't know were the sba-panel.vue component is used else and if this would not brake something else.

**Comment by joshiste** [comment]
reopened.. mixed up the numbers
