### ISSUE TITLE
Constructing serviceUrl with IP in spring-boot-starter-admin-client

### ISSUE THREAD

**Issue by lidkowiak** [codecentric/spring-boot-admin#112]
I want to achieve that serviceUrl will be construct based on IP, because there is situation when multiple IP addresses are bind to server. So each of my Spring Boot app is bound to IP address I define in server.address property or SERVER_ADDRESS env variable.

I tried to achieve this by following definition but it doesn't work ([please see](http://stackoverflow.com/questions/32848718/placeholders-in-spring-boot-configurationproperties)):
`spring.boot.admin.client.serviceUrl=http://${server.address}:${server.port}${server.context-path}`

I know I can explicit define it without placeholders but it will complicate my configuration and I can't use single configuration to apps running on different addresses.

So I suggest to add configuration possibility to prefer IP with e.g. spring.boot.admin.client.preferIp and use `serverProperties.getAddress()` to construct serviceUrl.

**Comment by joshiste** [comment]
With 1.2.2 a similar option was added (Commit https://github.com/codecentric/spring-boot-admin/commit/4ac7ea82f9e7ea00cef5529234672d2c819fdb46) 

You have to specify an interfacename in `spring.boot.admin.client.useIpAddressOf`

**Comment by lidkowiak** [comment]
I saw it but with single interface multiple ip addresses could be bound, so prefere ip option is justified in my opinion.

**Comment by joshiste** [comment]
Ok I got the point. I think it's really worth implementing this. But I think the `spring.boot.admin.client.useIpAddressOf` should be removed in the same step

**Comment by adnapster** [comment]
Hello, I am struggling with a scenario where I want my spring boot will recognize available ip-address.
I am running the microservices instance on multiple clusters inside Docker each cluster will have its own Ip-Addresses. Can you please suggest something which can be useful for me,
first, up all, I want to know whether I am moving in the correct direction or not.
Is it possible

**Comment by joshiste** [comment]
@adnapster intsead of resurrecting dead issues pleasue use our [gitter channel](https://gitter.im/codecentric/spring-boot-admin). If your container only has one ip for the localhost-adress the `spring.boot.admin.client.prefer-ip` setting should do it. Otherwise you'll need to set `server.adress` or `management.adress` too.
In my (non-production) env it work's well.
