### ISSUE TITLE
Custom extensions - runnig for local development, custom endpoint not showing

### ISSUE THREAD

**Issue by michformanek** [codecentric/spring-boot-admin#1123]
Hi, 
I am trying to develop some custom endpoint vizualization. I created spring boot app using spring initializr, added new module for FE sources and for start copied your custom endpoint sample. 

Now I want to start adding my changes, but I don't know how to setup my development environment properly. What should I do to get all the fancy stuff {devtools, hot reload,...} working properlty?

Also, from app logs i can see that custom.js was loaded and registered, hovewer, I can't see it anywhere in menu.  When I try to there by using URL, it works. I think it is an issue [with index.js](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/src/index.js) when you are registering it under parent "parent: 'instances',", but i dont have any "instances" item in navigation. Is my config all messed up, or is the sample wrong?

**Comment by joshiste** [comment]
>Is my config all messed up, or is the sample wrong?

can you provide a sample project?

**Comment by joshiste** [comment]
Did you solve your issue yourself? The best is to start with a copy of our `spring-boot-admin-sample-custom-ui` module...

**Comment by michformanek** [comment]
Hi, sorry. Yes. problem solved :) It was sort of stupid issue, because I changed extension-resource-locations as stated in docs, so that extension was registered, but did not configure spring boot app to allow static resources from that folder.  I just did ResourceHandlerRegistry.addResourceLocations and problem solved.

I found two more things that would be nice:
Allow Vue DevTools -> they are disabled, because main Spring Boot Admin bundle was build with production profile, and one has to allow them before first Vue is mounted.

Some way to import from Spring Boot Admin UI in my javascript - services and utils. But I think there should be some way to accomplish this through webpack configuration?

**Comment by joshiste** [comment]
I guess DevTools would require a development profile build, which needs to be published with a different maven classifier. 

Also importing from our bundle currently isn't possible as we don't export anything (and also the ui can't be required as npm module)

I'm closing this issue as your original problem is solved.
I'll think about your feedback regarding devTools and importing...
