### ISSUE TITLE
Modifier static in documentation Security section.

### ISSUE THREAD

**Issue by y-luis** [codecentric/spring-boot-admin#1126]
I am implementing a Spring Boot Admin Server from scratch following [v2.1.3 documentation](http://codecentric.github.io/spring-boot-admin/2.1.3/#_securing_spring_boot_admin_server), and trying to secure server with the fragment of code showed:

```
@Configuration
public static class SecuritySecureConfig extends WebSecurityConfigurerAdapter {
	//...
}
```

but it shows the error `modifier static not allowed here`. It seems like an error in the documentation.

**Comment by joshiste** [comment]
The code is from a sample where the SecuritySecureConfig is a nested class...
