### ISSUE TITLE
Removal of Hazelcast support?

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#113]
Is anyone really relying on the clustering support through Hazelcast?
I don't and want to get rid of the bloated code...
The option to implement your own ApplicationStore will remain.

**Comment by RobWin** [comment]
I like the HazelCast implementation of the ApplicationStore.
* It allows me to set-up spring-boot-admin in a reliable cluster.
* The data is not lost, if I deploy a newer version of spring-boot-admin.
* I would even store the Journal Events in the Hazelcast data grid.

**Comment by RobWin** [comment]
You could also extract it into an own optional module and use auto-configuration if it is added to the classpath.

**Comment by joshiste** [comment]
My Problem isn't the the code being in the core project. Just wondered if I
can get rid of it completly :)

**Comment by joshiste** [comment]
So I did a rework on the Hazelcast support and decided to not remove this feature at the moment
