### ISSUE TITLE
Admin Dashboard after failures

### ISSUE THREAD

**Issue by sanek640** [codecentric/spring-boot-admin#1131]
Hi, thanks for the great tool

I firstly asked my question on stackoverflow (https://stackoverflow.com/questions/55285481/admin-dashboard-after-failures), but i don't think there will be suitable answer.

After one of my service (that is registered in admin server) goes down, i want to continue view logfile in UI to understand the reason of such behavior or maybe some metrics/dumps/etc., but now SBA after a very short time will only show me the health status down and fetches excepions.

Is it a way to cache and store some Info before the failure (last healthy state) in UI?
Maybe it will be good for enhancement?

**Comment by joshiste** [comment]
Currently SBA doesn't store/cache any data. Currently I consider "professional" log and metrics management (with persistence, aggregation, ...) out of scope for SBA as there are already really good tools available for that (ELK-Stack, Splunk, Promtheus, Influxdb, Grafana....)
