### ISSUE TITLE
Long Content in Details (Details -> Metadata) makes panel unviewable

### ISSUE THREAD

**Issue by cschoell** [codecentric/spring-boot-admin#1132]
When the metadata contains a very long string, the Metadata View will move the second column out of view. 
Since there is no horizontal scrolling, the second column cannot be (easily) viewed any more.

![SpringBootAdminserver-MetadataViewBug](https://user-images.githubusercontent.com/890409/54826920-27132800-4cb1-11e9-9838-50c5ff7d4fed.png)

Related to https://github.com/codecentric/spring-boot-admin/issues/960

**Comment by joshiste** [comment]
Which version?

**Comment by cschoell** [comment]
Oh sorry, I meant to add the version.

Anyway I had the bug in 2.1.2 & 2.1.3
