### ISSUE TITLE
When there are hundreds of managed applications, the load time can take over 30 seconds.

### ISSUE THREAD

**Issue by asibross** [codecentric/spring-boot-admin#1133]
UI load time can take a long time when many applications are being managed.
In my case I have over 300 applications with ~2000 instances.

When I browse to a specific instance directly (deep-link), the `/applications` endpoint still downloads all of the applications, although it only really need a single application (and also that specific instance).

A possible optimization is to lookup the `referer` header and if it contains the instance id i.e. `https://../instances/{instance id}/details` then to only return the associated application.

A caveat to this optimization is that if you navigate to the applications list view (without refreshing the page) only a single application will appear. This can be addresses in the UI side by actually making a second call to get all applications.

**Comment by yevtsy** [comment]
I think the issue https://github.com/codecentric/spring-boot-admin/issues/1044 is similar to this one

**Comment by SteKoe** [comment]
Will be tracked in #1283.
