### ISSUE TITLE
using inmemory database?

### ISSUE THREAD

**Issue by chh315** [codecentric/spring-boot-admin#1134]
Is it using inmemory database?
I have 200 apps to  be monitored. how can i change it?

**Comment by joshiste** [comment]
SBA keeps the data in memory by default. There is an option to use hazelcast (which can be configured to persist the data).
Also you could implement the `InstanceEventStore` using your favorite datastore technology.
Having 200 apps in memory is no problem in terms of size. Why do you want to persist the data?

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by chh315** [comment]
sorry for the late reply.
I have doubted whether it is a oom.but got logs like this.
5月 14 08:41:28 tk2****sharetonadmin-1.0.0-Release.jar[18856]: /root/admin/sharetonadmin-1.0.0-Release.jar: line 260: 18873 Killed                  "$javaexe" "${arguments[@]}"
 5月 14 08:41:28 tk2**** systemd[1]: shareton-admin.service: main process exited, code=exited, status=137/n/a
 5月 14 08:41:28 tk2**** systemd[1]: Unit shareton-admin.service entered failed state.
 5月 14 08:41:28 tk2**** systemd[1]: shareton-admin.service failed.
 5月 14 08:43:29 tk2**** systemd[1]: shareton-admin.service holdoff time over, scheduling restart.
