### ISSUE TITLE
after set the JsonInclude.Include.NON_NULL the environment is no display

### ISSUE THREAD

**Issue by yugijiudai** [codecentric/spring-boot-admin#1135]
after set the JsonInclude.Include.NON_NULL, the environment is no display

@Configuration
public class JacksonConfig {

    @Bean
    @Primary
    @ConditionalOnMissingBean(ObjectMapper.class)
    public ObjectMapper jacksonObjectMapper(Jackson2ObjectMapperBuilder builder) {
        ObjectMapper objectMapper = builder.createXmlMapper(false).build();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        return objectMapper;
    }
}

if I set JsonInclude.Include.NON_DEFAULT,the environment  can display

**Comment by joshiste** [comment]
We rely currently on the default jackson config for the actuator endpoints see https://github.com/codecentric/spring-boot-admin/issues/751#issuecomment-391711080
