### ISSUE TITLE
Custom view does not load 

### ISSUE THREAD

**Issue by FedyaLutkovski** [codecentric/spring-boot-admin#1136]
The custom view does not load if you put it in the "classpath: /META-INF/spring-boot-admin-server-ui/extensions/custom/"

At the same time at the start of the application in the log, I see this "Loaded Spring Boot Admin UI Extension: UiExtension (resourcePath = index.js, resourceLocation = classpath: /META-INF/spring-boot-admin-server-ui/extensions/index.js ) "

As a custom view, I used the view from this repository https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui / 

What am I doing wrong?

**Comment by joshiste** [comment]
can you provide a project to reproduce the issue?

**Comment by FedyaLutkovski** [comment]
> can you provide a project to reproduce the issue?

Yes of course

**Comment by joshiste** [comment]
It's not sufficient to just put the vue file there. You need to transpile it to a javascript bundle. The sample includes the build script and config for the vue cli (the pom.xml is invoking a npm run build script).

**Comment by FedyaLutkovski** [comment]
> It's not sufficient to just put the vue file there. You need to transpile it to a javascript bundle. The sample includes the build script and config for the vue cli (the pom.xml is invoking a npm run build script).

Thanks for the answer. It turns out I misread your answer. Tell me if you have an example for the builder "Gradle"

**Comment by joshiste** [comment]
>Tell me if you have an example for the builder "Gradle"

no. But Gradle only needs to exec a shell command and add the output to the resource path (as the example does with maven).
