### ISSUE TITLE
Can not Login when run SBA on kubernetes with more than one instances

### ISSUE THREAD

**Issue by jasmine4y** [codecentric/spring-boot-admin#1137]
** Question **
When I run SBA  on kubernetes with 2 instances ，so I can't login，clicking button for logining，there is only to reset form and no tip  , which means the username and password is correct，
so I change SBA to 1 instance ， I find login is enabled。

![图片](https://user-images.githubusercontent.com/29448988/55528449-77d24a00-56cf-11e9-8502-6bce83b63aca.png)

** Version**
SBA：2.0.5
SpringBoot: 2.0.5
SpringCloud: Finchley.RELEASE

** Config**
eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
spring:
    security:
        user:
          name: root
          password: cdd123

**Comment by joshiste** [comment]
Either you need to use a stateless authentication mechanism (as JWT) or you need to replicate the state (session) between the instances (e.g. by using spring session). This is not a spring boot admin issue but rather one of your security config.

**Comment by FeriHansagi** [comment]
@jasmine4y did you find a solution for this?
I have the same problem when deployed with kube in AWS.
Infinite login page... redirect after login to the login page. I have auth wiht ingress which works and spring security with user/pass. I also think like joshiste that the login si somehow not persistent. I also receive 302 response code.
![image](https://user-images.githubusercontent.com/12622671/55972297-ef821500-5c8b-11e9-9004-47b4b2a92af7.png)

**Comment by FeriHansagi** [comment]
LE: I fixed this by adding this to my ingress controller to keep the session alive, hope this helps.
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"

**Comment by joshiste** [comment]
@FeriHansagi if you are using session based authentication and multiple instances you either need to replicate the sessions between the instances or doing sticky load balancing. not an sba issue

**Comment by jasmine4y** [comment]
@FeriHansagi I fixed this issue by sticky load balancing
