### ISSUE TITLE
SBA registered vue-view error rendering

### ISSUE THREAD

**Issue by cristian-balan** [codecentric/spring-boot-admin#1141]
Hello Johannes,
I need your help for a particular issue.
I have a Vue.js component "App" with "vue-table-2". The "App" works fine into a Spring boot application.
But if I try to register the component to a SpringBootAdmin from de.codecentric (version 2.1.3), the rendering doesn't work anymore, the problem is a conflict with "vue-table-2". 
If I remove the "import {ClientTable} from 'vue-tables-2'" the App can register itself as view to the SBA and works fine, but of course without the vue table.

Do you have any ideea where could be the problem ?
Thank you & Best regards, 
Cristian

- SBA version 2.1.3
- Vue.js version: 3.4.0

- error message:
TypeError: t is undefined vue.runtime.esm.js:5046
use VueJS
e906 index.js:30
    e906 viewRegistry.js:38

- relevant code, here just the relevant code part of my "main.js":
```
import {ClientTable} from 'vue-tables-2';
Vue.use(ClientTable);
SBA.use({
  install({viewRegistry}) {
    viewRegistry.addView({
      name: 'app',  //<1>
      path: '/app', //<2>
      component: app, //<3>
      label: 'App', //<4>
      order: 1000, //<5>
    }); 
  }
});
```

**Comment by joshiste** [comment]
Try reusing our instance of the vue instance:

```

SBA.use({
  install({viewRegistry, vue}) {
    vue.use(ClientTable);
    viewRegistry.addView({
      name: 'app',  //<1>
      path: '/app', //<2>
      component: app, //<3>
      label: 'App', //<4>
      order: 1000, //<5>
    }); 
  }
});
```

**Comment by cristian-balan** [comment]
Thanks for the quick answer, unfortunately the same err message appears after the login.

Here the whole main.js, if it helps

import Vue from 'vue'
import app from './App.vue'
import VueFlashMessage from 'vue-flash-message';
import VModal from 'vue-js-modal';
import {ClientTable} from 'vue-tables-2';
SBA.use({
  install({viewRegistry, Vue}) {
    Vue.use(VueFlashMessage);
    Vue.use(VModal);
    Vue.use(ClientTable);
    viewRegistry.addView({
      name: 'app',  //<1>
      path: '/app', //<2>
      component: app, //<3>
      label: 'App', //<4>
      order: 1000, //<5>
    }); 
  }
});

**Comment by joshiste** [comment]
It's a bit misleading, but you need to use the lowercase `vue` inside the install method!

**Comment by cristian-balan** [comment]
changed to lowercase, but stil the same err.
I'm doing something wrong or is the a library conflict ?

```
SBA.use({
  install({viewRegistry, vue}) {
    vue.use(VueFlashMessage);
    vue.use(VModal);
    vue.use(ClientTable);
    viewRegistry.addView({
      name: 'app',  //<1>
      path: '/app', //<2>
      component: app, //<3>
      label: 'App', //<4>
      order: 1000, //<5>
    }); 
  }
});
```

**Comment by joshiste** [comment]
you don't neeed to import vue.

> I'm doing something wrong or is the a library conflict ?

hard to tell can you provide a sample project for me?

**Comment by cristian-balan** [comment]
remove the import, but no success.
sure, here the vue files:

**main.js**
```
import app from './App.vue'
import VueFlashMessage from 'vue-flash-message';
import VModal from 'vue-js-modal';
import {ClientTable} from 'vue-tables-2';
SBA.use({
  install({viewRegistry, vue}) {
    vue.use(VueFlashMessage);
    vue.use(VModal);
    vue.use(ClientTable);
    viewRegistry.addView({
      name: 'app',  //<1>
      path: '/app', //<2>
      component: app, //<3>
      label: 'App', //<4>
      order: 1000, //<5>
    }); 
  }
});
```

**App.vue**
```
<template>
  <div id="app">
    <DlqView/>
  </div>
</template>
<script>
import { Base64 } from 'js-base64'
import DlqView from './components/Dlq.vue'
export default {
  name: 'app',
  components: {
    DlqView
  }
}
</script>
```

**Dlq.vue**
```
<template>
<div class="container">
...
<div class="row">
<div>
   <v-client-table  :data="messages" :columns="columns" :options="options" >
      <a slot="request" slot-scope="props" class="glyphicon glyphicon-eye-open" v-on:click="show(props.row.id, props.row.topic, props.row.errorCode, props.row.errorMessage, props.row.request)" ></a>
      <a slot="resend" slot-scope="props" v-on:click="resendMessage(props.row.id)" class="glyphicon glyphicon-play"></a>
      <a slot="delete" slot-scope="props" v-on:click="deleteMessage(props.row.id)" class="glyphicon glyphicon-trash"></a>
   </v-client-table>
</div>
</div>
</div>
</template>
<script>
import * as flash from 'vue-flash-message/dist/vue-flash-message.min.css'
import axios from 'axios'
require('vue-flash-message/dist/vue-flash-message.min.css');
....
</script>

```

**Comment by joshiste** [comment]
please upload a zip containing the whole project via drag and drop

**Comment by cristian-balan** [comment]
sure, here the project files as zip
After "npm run build" the dist files are copied into SBA (src/main/resources/META-INF/spring-boot-admin-server-ui/extensions/dlq/)
[app.zip](https://github.com/codecentric/spring-boot-admin/files/3048997/app.zip)

**Comment by joshiste** [comment]
@cristian-balan the package.json is missing are you sure the project is complete?

**Comment by cristian-balan** [comment]
soory, 
[package-json.zip](https://github.com/codecentric/spring-boot-admin/files/3049224/package-json.zip)

**Comment by joshiste** [comment]
The build fails with errors for missing files.
Please provide a complete project which I am able to build using a simple commands.
It just wastes too much of my limited time stitching the files together, figuring out what's missing and getting back to you.

If you can't provide all the project in this public place, you either can send it me via email or you need to create a stripped down sample.

**Comment by cristian-balan** [comment]
I tried via email, but doesn't work
For build, please execute the npm commandos:
```
npm install --save axios vue-router
npm run build
```
Thanks a lot for any ideea or advice.
[dlq.zip](https://github.com/codecentric/spring-boot-admin/files/3049510/dlq.zip)

**Comment by joshiste** [comment]
@cristian-balan sorry, but in the last days I couldn't have a look at the project.

Imho the fix is rather simple: 
Copy the [vue.config.js](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/vue.config.js) from our custom-ui sample.
You may need to change the main entry name (your project uses main.js, the sample uses index.js)
