### ISSUE TITLE
Unable to download heapdump - 406 - Not Acceptable

### ISSUE THREAD

**Issue by aantono** [codecentric/spring-boot-admin#1142]
It seems that the heapdump downloading doesn't work due to incorrect `Accept` header being sent by the browser:

In Chrome network inspect, the following `Accept` header seems to be sent on the request:
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8`, which doesn't seem to be the right one, as expected by the Spring Boot

**Comment by joshiste** [comment]
Which SBA version are you referring to?
Is there some proxy or firewall in between?

As the browser includes `*/*` in the Accept header... any Content-Type should match.

**Comment by aantono** [comment]
Using `2.1.3` of Spring Boot Admin

**Comment by aantono** [comment]
I've tested this on a local instance of SBA, so same error even without any network proxies. :(  Not too sure what gives. :(

**Comment by joshiste** [comment]
What version is the client application you want to download the heapdump from?

**Comment by aantono** [comment]
Spring Boot 2.1.3 on the client instance

**Comment by joshiste** [comment]
It works for me using chrome and the sample from this repo.

Could you please provide a project to reproduce the issue?

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by saanl** [comment]
Hi, I just met the same issue and I think I found the reason:

It likely allows only the request with the header: Accept:application/json, while some browser doesn't set it.

![image](https://user-images.githubusercontent.com/20855630/59959873-cedb0480-94f1-11e9-8704-58842bc0aa83.png)

![image](https://user-images.githubusercontent.com/20855630/59959877-eadea600-94f1-11e9-9c10-fa3cdbdb907c.png)

![image](https://user-images.githubusercontent.com/20855630/59959887-05188400-94f2-11e9-8d07-7b9564abddea.png)
