### ISSUE TITLE
Some calls are throwing 404 in background when admin console loads.

### ISSUE THREAD

**Issue by tejas-rane** [codecentric/spring-boot-admin#1143]
** Question **
1.) I am able to boot admin and attach one client. Also, all tabs are showing up. but some of my background calls are failing.

/api/notifications/filters
/api/applications/a8ee5a7e/logfile
/api/applications/a8ee5a7e/flyway
/api/applications/a8ee5a7e/refresh

The environment is not in my local, the calls are going through a HA proxy. And its dockerized.

Can you advise here?

I am using version 1.5.7. 

2.) i see in logs :
Application registered itself as **a8ee5a7e**

where is this unique id coming from? I wonder if i spin up 3 containers, its not showing me 3 entries.

3.) 

the disk space and other parameters are coming for the host which is running docker. Can we configure it just to give container info?

4.) Is there a way to see the cache of a springboot client container.

**Comment by joshiste** [comment]
ad 1) These OPTIONS requests are made to detect the available endpoints and are ok to fail

ad 2) The id is assigned by the sba server for this particular instance. By default it's a hash of the health-url but the algorithm can be customised.

ad 3) see the spring boot manual for this. This is part of the spring boot actuator

ad 4) with Spring boot 2 and  SBA 2you can get some statistics for caches
