### ISSUE TITLE
Add swagger-ui link to application links in an instance's page

### ISSUE THREAD

**Issue by ddcruver** [codecentric/spring-boot-admin#1150]
Spring Boot Admin is a good way to get a list of all your running applications but for testing and development purposes but there are times when you may want to hit the endpoints of your application.  Swagger UI provides a good way to do this and would like a fast way to go from an instance of an application in Spring Boot Admin to the Swagger UI of that corresponding application.

Under an application's in Spring Boot Admin there are links for the following:

- Home (http://example.com/)
- Actuator (http://example.com/actuator)
- Health (http://example.com/actuator/health)

I would like to see this added:
- Swagger UI (http://example.com/swagger-ui.html)

To make swagger available on the application you just need to add this to the pom.xml
```	
<dependency>
   <groupId>io.springfox</groupId>
   <artifactId>springfox-swagger2</artifactId>
</dependency>

<dependency>
   <groupId>io.springfox</groupId>
   <artifactId>springfox-swagger-ui</artifactId>
</dependency>
```

**Comment by joshiste** [comment]
You can add URLs to the `info.*` attributes which will be rendered as hyperlinks. The only problem here is that you currently can't make them relative to your application and must be absolute.

**Comment by ddcruver** [comment]
Yeah that may work with standalone apps because you possibly have the protocol, host and port defined in other properties in which you can build this url but if you deploy this to an application server in a war you might have some more trouble building this URL.

**Comment by joshiste** [comment]
> ... you might have some more trouble building this URL.

so does the admin server (which requires manual config). And it event gets worse if you're running behind a loadbalancer/reverse-proxy. So imho the best is that you configure the public for the swagger ui yourself...
