### ISSUE TITLE
java.net.UnknownHostException: 

### ISSUE THREAD

**Issue by jingshenbusi6530** [codecentric/spring-boot-admin#1151]
d.c.b.a.server.services.StatusUpdater    : Couldn't retrieve status for Instance(id=8a08ea01de1a, version=4, registration=Registration(name=bhg-admin, managementUrl=http://DESKTOP-57EE69B:8019/actuator, healthUrl=http://DESKTOP-57EE69B:8019/actuator/health, serviceUrl=http://DESKTOP-57EE69B:8019/, source=http-api), registered=true, statusInfo=StatusInfo(status=UNKNOWN, details={}), statusTimestamp=2019-04-26T09:35:52.779Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://DESKTOP-57EE69B:8019/actuator/health)}), buildVersion=null, tags=Tags(values={}))
java.net.UnknownHostException: DESKTOP-57EE69B
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[na:1.8.0_191]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[na:1.8.0_191]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[na:1.8.0_191]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[na:1.8.0_191]

Spring Boot Admin：v2.1.0
Spring Boot: v2.1.0.RELEASE

I deployed the client on the A server, the server on the B server, and then reported this error.
When the client and server are deployed on the same server, they will succeed. Depressed

![image](https://user-images.githubusercontent.com/19492294/56798998-8d5c0f00-684a-11e9-9f1f-737c8bc76a30.png)

**Comment by joshiste** [comment]
This is not an SBA issue. The monitored applications needs to be reachable from the SBA server. Obviously the dns resolution fails for your registered application and the SBA server can't reach the application. You may need to alter the url the client applications submits with the registration by configuring `spring.boot.client.instance.*` (see https://codecentric.github.io/spring-boot-admin/current/#spring-boot-admin-client)
