### ISSUE TITLE
DispatcherMappings.vue shows a "methods" of null error

### ISSUE THREAD

**Issue by guohaijian** [codecentric/spring-boot-admin#1152]
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/mappings/DispatcherMappings.vue

line 116  will show an error with SimpleUrlMapping.
because the mapping described by provider will set the details null.

code from:
org.springframework.boot.actuate.web.mappings.reactive.DispatcherHandlersMappingDescriptionProvider$UrlHandlerMappingDescriptionProvider=>
```
private DispatcherHandlerMappingDescription describe(Entry<PathPattern, Object> mapping) {
			return new DispatcherHandlerMappingDescription(
					mapping.getKey().getPatternString(), mapping.getValue().toString(),
					null);
		}
```

version: 2.1.4

**Comment by joshiste** [comment]
Could you please post the stacktrace from the browsers console and the output from the endpoint?

**Comment by guohaijian** [comment]
mappings output:

{
    "contexts": {
        "application": {
            "mappings": {
                "dispatcherHandlers": {
                    "webHandler": [
                        {
                            "predicate": "/webjars/**",
                            "handler": "ResourceWebHandler [\"classpath:/META-INF/resources/webjars/\"]",
                            "details": null
                        },
                        {
                            "predicate": "/**",
                            "handler": "ResourceWebHandler [\"file:E:/Work/Git/aries-vue/WebRoot/\", \"classpath:/WebRoot/\", \"classpath:/resources/\", \"classpath:/META-INF/resources/\"]",
                            "details": null
                        },
                        {
                            "predicate": "/m/**",
                            "handler": "ResourceWebHandler [\"classpath:/META-INF/spring-boot-admin-server-ui/\", \"classpath:/META-INF/spring-boot-admin-server-ui/extensions/\"]",
                            "details": null
                        }
                    ]
                }
            },
            "parentId": null
        }
    }
}
stacktrace on chrome console:
vue.runtime.esm.js:1887 TypeError: Cannot read property 'methods' of null
    at DispatcherMappings.vue:116
    at Array.map (<anonymous>)
    at o.countNonEmptyArrays (DispatcherMappings.vue:116)
    at DispatcherMappings.vue?7af9:1
    at o.Ce [as _l] (vue.runtime.esm.js:2624)
    at DispatcherMappings.vue?7af9:1
    at o.Ce [as _l] (vue.runtime.esm.js:2645)
    at o (DispatcherMappings.vue?7af9:1)
    at o.t._render (vue.runtime.esm.js:3535)
    at o.r (vue.runtime.esm.js:4041)

![chrome console err](https://user-images.githubusercontent.com/37853739/56880888-09479880-6a91-11e9-9bfe-a776a6644cf7.PNG)
