### ISSUE TITLE
Spring Boot Admin - Insights - Environment view should list profile(s) of each configuration source (YAML)

### ISSUE THREAD

**Issue by ddcruver** [codecentric/spring-boot-admin#1156]
It would be helpful if the title of each section also has the effective profile that item is being included in.

For property files this may be obvious based on the name but for things such as YAML it might not be as clear.

For example:
If you have a YAML document with JPA (jpa) and MongoDB (mongo) sub-documents the title will say this:
- `applicationConfig: [classpath:/config/application.yaml] (document #0)`
- `applicationConfig: [classpath:/config/application.yaml] (document #1)`

But it would be more helpful if it listed: 
- `applicationConfig: [classpath:/config/application.yaml] (document #0) (profiles: jpa)`
- `applicationConfig: [classpath:/config/application.yaml] (document #1) (profiles: mongo)`

Where the profiles would come from the spring.profiles property of the YAML document.  This may not be easy to get in other property sources like application-jpa.properties and non-relevant in other such as systemProperties but very helpful in YAML property sources.

Note this value from the endpoint is returned is based on how it is defined in the document.  So if only one profile is defined it will define a property spring.profiles or if multiple profiles are defined it will expose them as spring.profiles[0] ... spring.profiles[n].

**Comment by joshiste** [comment]
We take this string from the `/env` actuator endpoint as-is, so please open an issue for spring-boot, as I don't think this easy to implement with the current information given by the endpointn
