### ISSUE TITLE
make notifications reusable outside spring boot admin

### ISSUE THREAD

**Issue by remmeier** [codecentric/spring-boot-admin#1158]
It would be great to see the notification part of spring boot admin become a dedicated project in this repository to be reusable outside the scope of Spring Boot Admin. It seems flexible and integrates well with many messaging systems. As far as I have seen, there seems not really anything comparable in the Java ecosystem.

**Comment by joshiste** [comment]
Imho the implementation is currently very tightly coupled to spring boot admin and in the end most of the notifiers are just doing http requests, so I don't think it's worth the effort to rip this out. 
Also I'm lacking the time to maintain a further library.
But as it's open source code feel free to copy it and make it a library on your own.
