### ISSUE TITLE
Fetching logfile failed

### ISSUE THREAD

**Issue by swiftech** [codecentric/spring-boot-admin#1159]
Error shows on the page when I open "Logging" -> "Logfile" menu: 

Fetching logfile failed
Cannot read property 'split' of undefined

My Configuration: 
```yaml
logging:
  file: /var/log/myapp.log
```
And the Download button is OK to open the logfile in the browser.

Spring Boot & SBA version : 2.1.4

![屏幕快照 2019-05-10 上午11 41 40](https://user-images.githubusercontent.com/3277107/57510542-ad56fc80-7339-11e9-97cf-6c275dda7593.jpg)

**Comment by joshiste** [comment]
Could you please provide a minimal reproducible sample?

What browser are you using?

**Comment by joshiste** [comment]
Please at least show me the response headers for the reponse to `/logfile`

**Comment by swiftech** [comment]
My Browser is Chrome 73, response header:

Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: session_id,Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With,Access-Control-Request-Headers,Access-Control-Request-Method
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Mon, 13 May 2019 01:34:18 GMT
Expires: 0
Pragma: no-cache
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

**Comment by joshiste** [comment]
It looks like the endpoint is returning json. It should return text.

**Comment by joshiste** [comment]
closed due to missing feedback
