### ISSUE TITLE
Is there any API documentation to make it easy for us to build front-end pages and make calls?

### ISSUE THREAD

**Issue by zwdgit** [codecentric/spring-boot-admin#1160]
Is there any API documentation to make it easy for us to build front-end pages and make calls?

**Comment by joshiste** [comment]
currently not. only the code...
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/services/application.js
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/services/instance.js

small example: https://github.com/joshiste/spring-boot-admin-samples/blob/develop/sba-custom-ui/src/main/frontend/
