### ISSUE TITLE
add link to admin page

### ISSUE THREAD

**Issue by rjsuzuki** [codecentric/spring-boot-admin#1162]
The docs don't really explain how to add links to an admin page. I created a CRUD page for my spring boot app using Vaadin. I was wondering how I can reference that within spring boot admin? 

am i supposed to use "info.*" ? 

if so, can you please provide an example, as I can't find any examples on the web. Thank you.

**Comment by joshiste** [comment]
so is this page running in the sba server or on the application you monitor? if yes, then you should go with `info.*`
If you want to add it to sba: with 2.2.x we have a way to add "top level" links to the SBA ui

**Comment by rjsuzuki** [comment]
ok thank you for the response, but I still would like to know how to actually apply `info.*`
I can't find any documentation on where this goes and how to use this with a real link. 

please excuse my persistence :)

**Comment by joshiste** [comment]
on the client application just add a property like `info.homepage=http://codecentric.de`
