### ISSUE TITLE
Failed to show all endpoints of eureka instance

### ISSUE THREAD

**Issue by zurhan** [codecentric/spring-boot-admin#1164]
Hi!
spring-boot.version:2.1.4.RELEASE, spring-cloud.version:Greenwich.SR1, spring-boot-admin.version:2.1.4
the application registered to EUREAK-SERVER uses application.properties like that :
management.server.port=8087
management.server.servlet.context-path=/core
spring.cloud.inetutils.default-ip-address=127.0.0.1
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

but the sba server couldn't show all endpoints of the application
![TIM截图20190516172845](https://user-images.githubusercontent.com/26533310/57842989-1b9b3380-7800-11e9-8dc7-16ef9d3ab9ef.png)

**Comment by joshiste** [comment]
> management.server.servlet.context-path=/core

if you move the path of the actuator endpoints you need to tell sba via metadata (using `management.context.path` ...
see https://codecentric.github.io/spring-boot-admin/current/#_converting_serviceinstances
