### ISSUE TITLE
Issue with logging

### ISSUE THREAD

**Issue by josetesan** [codecentric/spring-boot-admin#117]
Hi, 

I've just upgraded my admin server to 1.2.4, and so did with my spring boot client application.

But on startup, it yields this error :
```
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'de.codecentric.boot.admin.actuate.LogfileMvcEndpoint@41dd5380' method 
public void de.codecentric.boot.admin.actuate.LogfileMvcEndpoint.invoke(javax.servlet.http.HttpServletResponse) throws java.io.IOException
to {[/logfile],methods=[GET]}: There is already 'org.springframework.boot.actuate.endpoint.mvc.LogFileMvcEndpoint@27772e2f' bean method
public org.springframework.http.ResponseEntity<?> org.springframework.boot.actuate.endpoint.mvc.LogFileMvcEndpoint.invoke() throws java.io.IOException mapped.
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry.assertUniqueMethodMapping(AbstractHandlerMethodMapping.java:56
```

It happened both in the client and the server side.
I could *fix* it by removing logging configuration from my config file,
```
logging:
    file: /var/log/apps/app.log
    path: /var/log/apps/
```

but this is not the desired behaviour.

Any help ?

Thanks for such a GREAT work.

**Comment by joshiste** [comment]
So I bet you are using Spring Boot 1.3.0? Spring Boot Admin 1.2.x won't work with boot 1.3 unless you set `endpoints.logfile.enabled` to  `false`.

**Comment by josetesan** [comment]
Yes, you are true.
On 1.3.x
And yes, it work now :)
Thanks.
