### ISSUE TITLE
sba-settings.js generating 406

### ISSUE THREAD

**Issue by azizabah** [codecentric/spring-boot-admin#1170]
sba-settings.js is throwing a 406 Not Acceptable in the application when upgrading to 2.1.5. I see that the file was new to that version and am assuming something is off in how it's being bundled up. 

When I look at the HTML generated for this page, that .js file is very different looking:
```
<!DOCTYPE html><html><head><base href=https://spring-boot-admin.internal.com/ ><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1"><meta name=format-detection content="telephone=no,email=no"><meta name=theme-color content=#42d3a5>
<link rel="shortcut icon" href=assets/img/favicon.png type=image/png><title>Spring Boot Admin</title><link href=assets/css/chunk-common.6aba055e.css rel=preload as=style>
<link href=assets/css/sba-core.9ab149c3.css rel=preload as=style>
<link href=assets/js/chunk-common.dec76664.js rel=preload as=script>
<link href=assets/js/chunk-vendors.ec700424.js rel=preload as=script>
<link href=assets/js/sba-core.934778a9.js rel=preload as=script>
<link href=assets/css/chunk-common.6aba055e.css rel=stylesheet>
<link href=assets/css/sba-core.9ab149c3.css rel=stylesheet></head><body>
<div id=app></div>
<script lang=javascript src=sba-settings.js></script>
<script src=assets/js/chunk-vendors.ec700424.js></script>
<script src=assets/js/chunk-common.dec76664.js></script>
<script src=assets/js/sba-core.934778a9.js></script></body></html>
```

I'm not really an expert on webpack or vue behavior but my gut it something is off there.

**Comment by joshiste** [comment]
Generating an admin server from start.spring.io and firing up works for me on a current Chrome. Could you please provide a project to reproduce the issue?

**Comment by azizabah** [comment]
@joshiste - Some bad internal security settings that used to work for us but no longer. After adjusting them, worked without issue. Sorry about that!

**Comment by sontruong** [comment]
@azizabah I got the same error with you, please help me update it.

I used spring boot admin with springboot 2.16 and Oauth2.

I tried to set cors header and web sercurity ignore but the issue still happen

Thanks & Best Regards,

**Comment by azizabah** [comment]
@SonSeungWoo we used to have some security config that looked like this
```
@Component
public class ServiceSecurityAuthorizationConfiguration implements HttpSecurityAuthorizeRequestsConfigurer {

    @Override
    public void configure(
            ExpressionUrlAuthorizationConfigurer<HttpSecurity>
                    .ExpressionInterceptUrlRegistry expressionInterceptUrlRegistry) {
        expressionInterceptUrlRegistry
                .antMatchers("/**").permitAll();
    }
}
```
We updated it to look like this
```
@Component
@EnableWebSecurity
public class ServiceSecurityAuthorizationConfiguration extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().disable()
                .authorizeRequests()
                .antMatchers("/**").permitAll()
                .anyRequest().authenticated();
    }
}
```

**Comment by sontruong** [comment]
thanks @aarrbbii  , I pass this issue but I got the new "org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation" I will continue with the new issue!
