### ISSUE TITLE
SBA UI does not pass CSRF header in version 2.1.5

### ISSUE THREAD

**Issue by Sarvesh-D** [codecentric/spring-boot-admin#1171]
When refreshing the context thru UI or changing the log levels (in general making any POST/PUT/DELETE request), the CSRF header is missing in request which is causing 403 errors. There seems to be a header in request with key `null` which has value of CSRF token. I verfied in 2.1.2 version and it passes header named `X-XSRF-TOKEN` correctly. Can you take a look? thanks.

Steps to reproduce:

1. Use SBA version 2.1.5.
2. Secure the client application using spring security, which will automatically add CSRF protection to your app.
3. Expose all endpoints of your monitored application.
4. From the SBA UI, go to environment section, and hit the refresh button.
5. Check the networks tab in Chrome debugger, In the request header for `/refresh` request, you will find a header with name `null` which holds the value of CSRF token.
6. The request will result in 403. with message `Invalid CSRF Token &#39;null&#39; was found on the request parameter &#39;_csrf&#39; or header &#39;X-XSRF-TOKEN&#39;.`

**Comment by joshiste** [comment]
using the sample from https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet it works for me.

Please have a look at the `/sba-settings.js` in your browsers console. It should look similar to this
```
var SBA = {
  uiSettings: {"title":"Spring Boot Admin","brand":"<img src=\"assets\/img\/icon-spring-boot-admin.svg\"><span>Spring Boot Admin<\/span>","favicon":"assets\/img\/favicon.png","faviconDanger":"assets\/img\/favicon-danger.png","notificationFilterEnabled":true,"routes":["\/about\/**","\/applications\/**","\/instances\/**","\/journal\/**","\/wallboard\/**","\/external\/**","\/custom\/**"],"externalViews":[{"label":"\uD83D\uDE80","url":"http:\/\/codecentric.de","order":2000,"iframe":false}]},
  user: {"name":"user"},
  extensions: [],
  csrf: {
    parameterName: "_csrf",
    headerName: "X-XSRF-TOKEN"
  },
  use: function (ext) {
    this.extensions.push(ext);
  }
};
```

The file gets rendered on the server using the "_csrf" request attribute, which should be added via the `CsrfFilter` from Spring Security. So I'd guess you have some culprit in your configuration.

If you don't think so, please provide a minimal project reproducing the issue which I can download/clone and run.

**Comment by Sarvesh-D** [comment]
I tried different versions of SBA (2.1.2 and 2.1.5) with same security config. The issue was not reproducible in SBA 2.1.2 but its there in 2.1.5. So i guess something is causing the problem in 2.1.5. BTW i am using Spring boot 2.1.2 with SBA 2.1.5 (hope that's not the problem). But for now i have included sba-settings.js in my classpath and have hard-coded the header name to "X-XSRF-TOKEN". I am trying to compare the code base with changes you made in commit https://github.com/codecentric/spring-boot-admin/commit/48abe691c5d244a864d6ad95e71c3f54366051e1 to see what is causing the issue.

**Comment by joshiste** [comment]
Can you share a sample project with your security config?

**Comment by joshiste** [comment]
closed due to missing feedback
