### ISSUE TITLE
Spring Data JPA integration

### ISSUE THREAD

**Issue by coffman21** [codecentric/spring-boot-admin#1172]
I may assume that availability to access repositories with CRUD operations might be helpful, but not sure if it fits to Spring Boot Admin project. The nearest example would probably be [Django Admin](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/) interface.

**Comment by joshiste** [comment]
IIRC there is a project calles lightadmin which has similar functionalities.

For SBA we would need a actuator endpoint providing all the data and metadata, which doesn't exist.
