### ISSUE TITLE
Spring Security+JWT in Spring boot admin client

### ISSUE THREAD

**Issue by biq12** [codecentric/spring-boot-admin#1173]
spring security + jwt in the client application (Spring boot admin) stops the communication between spring boot admin client and spring boot admin server, the instance is offline or down all the time

**Comment by joshiste** [comment]
The SBA server does some health-checks in the background. For this health-check you also need a valid token. So must write an `HttpHeadersProvider` which adds the token to the request.

**Comment by biq12** [comment]
thinks for you reply Mr johsiste but i can t implements this problem i have a projet at school in this subject and i don t have much time, please more explaination 


	@Autowired
	private BCryptPasswordEncoder bCryptPasswordEncoder;
	@Autowired


	@Override
	public HttpHeaders getHeaders(Instance instance) {
	    String username = instance.getRegistration().getMetadata().get("yas9");
        String password = instance.getRegistration().getMetadata().get("123");
		   HttpHeaders headers = new HttpHeaders();
		   if (StringUtils.hasText(username) && StringUtils.hasText(password)) {
	            headers.set("Authorization", encode(username, password));
	        }

	        return headers;
	}
	
	
	

    protected String encode(String username, String password) {
    	List<String> roles=new ArrayList<String>();
    	roles.add("ADMIN");
        bCryptPasswordEncoder.encode(password);
        String jwt=JWT.create() 
				 .withIssuer("jj")
				 .withSubject(username)
				 .withArrayClaim("roles",roles.toArray(new String[roles.size()]))
				 .withExpiresAt(new Date(System.currentTimeMillis()+10*24*3600*10000))
				  .sign(Algorithm.HMAC256("secretNom"));//un Secret de nom .........
		 
	

		 return jwt;
    }
