### ISSUE TITLE
Wrong MIME type for sba-settings.js

### ISSUE THREAD

**Issue by dadangeuy** [codecentric/spring-boot-admin#1176]
I got Mime Type issue with spring-webflux + spring-boot-admin-server + spring-security 2.1.5.
The page wont load, and this is the message from chrome console:
~~~~javascript
Refused to execute script from 'http://localhost:8000/sba-settings.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
~~~~

According to [Mozilla List of MimeType](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types), the correct value for .js file is `text/javascript`.
I believe the code below from `spring-boot-admin-server-ui` is the culprit.
~~~~java
@AdminController
public class UiController {
    @GetMapping(path = "/sba-settings.js", produces = MediaType.APPLICATION_JSON_VALUE)
    public String sbaSettings() {
        return "sba-settings.js";
    }
}
~~~~

**Comment by dadangeuy** [comment]
this is the sample project if you want to test it out: [sba-mime](https://github.com/dadangeuy/sba-mime)

**Comment by TivJsou** [comment]
This bug still exists in 2.1.6 . "text/javascript" is unsupported.
if remove [ produces = "text/javascript" ], everything is ok.

**Comment by joshiste** [comment]
@TivJsou for the master branch / the upcoming 2.2.0 we already switched to `applictaion/javascript`.
