### ISSUE TITLE
management.endpoints.web.exposure.include incorrect documentation

### ISSUE THREAD

**Issue by davidnewcomb** [codecentric/spring-boot-admin#1177]
Referring to #952 there was some confusion over to `"*"` or to `*` for `management.endpoints.web.exposure.include`.

Your documentation uses `"*"` in all your examples. Search for `"*"` in page: http://codecentric.github.io/spring-boot-admin/2.1.5/

**Comment by joshiste** [comment]
in `.yml` you need to use  `"*"` and in `.properties `*`...
