### ISSUE TITLE
Still show health details if Health returns DOWN (if possible)

### ISSUE THREAD

**Issue by grantlittle** [codecentric/spring-boot-admin#118]
Hi all,

First off this looks like a really promising tool, I've only used it a little so far, but I've been impressed, so keep up the good work.

One thing I've noticed though, is that when the component being monitored returns DOWN, it doesn't seem possible to click on the "Details" link next to the component to see why the component is actually down.

We use the health indicators to not only show if a component is up or down, but to also provide some reason as to why that component is "down", exception, text etc. From my experience so far, it appears you cannot view this and therefore loose valuable centralised information which may help you diagnose problems quickly.

I can understand why you might not allow access to "Details" if the component is not providing any information, but in the situation I have hopefully described well enough, I believe that information should be available for administration and diagnosis reasons.

I haven't looked at any of the code, so there may be a reason for this, if so I'd like to understand the restrictions etc.

Thanks,

Grant

**Comment by joshiste** [comment]
Hi Grant,

Is the application listed as `DOWN` or `OFFLINE`? In former case the link should be visible and latter not. I've tested this in the current master branch.
Which version of spring boot admin are you using? the behaviour has changed sometime ago.

**Comment by grantlittle** [comment]
Hey,

Thanks for that. I upgraded to the latest version and it's all working as I expected. 

Great, cheers for that.
