### ISSUE TITLE
HTTP Trace Tab Crashes Spring Boot Admin Console

### ISSUE THREAD

**Issue by ernakulgoyal** [codecentric/spring-boot-admin#1181]
Hello Guys!

Its been great using SBA, a problem which has already been reported in some threads: while opening SBA's HTTP trace tab, browser runs out of memory and SBA console crashes.

Has this been fixed by any means? It would be great if someone can please post the resolution/workaround ASAP. Thanks in advance.

I am using:
- **SBA Client Application with**:
[Spring Boot version '2.0.4';
Spring Boot Admin Client version '2.0.6']
- **SBA Server Application with**:
[Spring Boot Web version: '2.1.5';
spring boot starter server version: '2.1.5;
spring boot starter server UI version: '2.1.5;]

**Comment by joshiste** [comment]
Do you have a custom configured jackson mapper? SBA relies on the default jackson configuration...

**Comment by ernakulgoyal** [comment]
Hi @joshiste, I have define a Object Mapper bean in my application configuration.
One of the threads suggested to use:

@Override
    public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
        for (HttpMessageConverter<?> converter : converters) {
            if (converter instanceof MappingJackson2HttpMessageConverter) {
                MappingJackson2HttpMessageConverter jsonMessageConverter = (MappingJackson2HttpMessageConverter) converter;
                ObjectMapper objectMapper = jsonMessageConverter.getObjectMapper();
                objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
                break;
            }
        }
    }

This solved the issue, but not sure if its going to affect behaviour of REST APIs of my application.

What do you suggest?

**Comment by joshiste** [comment]
Yes it will have an impact on all of your endpoints. There is currently no good solutions due to https://github.com/spring-projects/spring-boot/issues/12951

**Comment by ernakulgoyal** [comment]
What impact it would have?
