### ISSUE TITLE
Issue Deploying SBA app as war in Azure web apps

### ISSUE THREAD

**Issue by jonnauday** [codecentric/spring-boot-admin#1184]
Hi Team ,

I am Trying to Deploy SBA server app as war into Azure webapp i am getting below exception on login to admin server UI and no application is getting registered as client to the SBA server 

**Exception:** ERROR 114 --- [p-nio-80-exec-9] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/applications] due to exception [Async support must be enabled on a servlet and for all filters involved in async request processing. This is done in Java code using the Servlet API or by adding "<async-supported>true</async-supported>" to servlet and filter declarations in web.xml.]

**Versions:** 
compile("de.codecentric:spring-boot-admin-server:2.0.0")
compile("de.codecentric:spring-boot-admin-server-ui:2.0.0")

Same App is running and able to register applications from localhost both client and server running in localhost

**Comment by jonnauday** [comment]
Any update on the above issue

**Comment by joshiste** [comment]
Sorry for the late response - I was on vacation.

I am not using Azure for war deployments (I don't use Azure not at all). Therefore I can't help you with this if everything works fine for your local tomcat deployments. 

But as the exception tells you that the async support isn't enabled for your servlet, I'd suggest you dig in that direction.

**Comment by joshiste** [comment]
close due to missing feedback

**Comment by martin-schaefer** [comment]
Hello @joshiste 
I have the same issue when packaging SBA as war file and then deploy it to a Tomcat 9.0.30 running on Red Hat Linux. In Tomcat all registered servlets have the tag `<async-supported>true</async-supported>` set and `org.springframework.boot.autoconfigure.web.servlet.DispatcherServletRegistrationBean.isAsyncSupported()` returns true on startup. Is there any new knowldege about the issue?

**Comment by joshiste** [comment]
> Is there any new knowldege about the issue?

nope. I never recevied any code to reproduce the issue - so I wasn't able to debug it.
