### ISSUE TITLE
No Error but no application

### ISSUE THREAD

**Issue by LinggaAskaEdo** [codecentric/spring-boot-admin#1189]
This is my project to test the Spring Boot Admin. I did not get an error but no application appeared. For information, I have to use SpringBoot version 1.5

[SpringBootActuatorTest.zip](https://github.com/codecentric/spring-boot-admin/files/3331201/SpringBootActuatorTest.zip)
[SpringBootAdminTest.zip](https://github.com/codecentric/spring-boot-admin/files/3331202/SpringBootAdminTest.zip)

Please help...

**Comment by joshiste** [comment]
If you are using the 1.5.x client the property for setting the SBA server url is `spring.boot.admin.url` (this was changed with SBA 2.x)
