### ISSUE TITLE
Spring Boot Admin with Public IP configurations

### ISSUE THREAD

**Issue by ernakulgoyal** [codecentric/spring-boot-admin#1191]
Hi @joshiste ,

I have a SBA server and some SBA clients sitting on different machines.

I am configuring public IP of SBA server in all the clients.

SBA UI displays clients but with status down, with their private IPs. On checking in network API calls, its returning 502.

Is it possible to configure SBA server-client using public IP/DNS configuration?

**Comment by joshiste** [comment]
Yes you can set the `spring.boot.admin.client.service-base-url` using the public IP.
But keep in mind that if the public address is loadbalanced you can't predict which instance you are accessing...

I'd suggest that you put the SBA server into the same network as your applications
