### ISSUE TITLE
Reduce registration requests when the app is known to be health checked

### ISSUE THREAD

**Issue by membersound** [codecentric/spring-boot-admin#1198]
The `RegistrationApplicationListener.startRegisterTask()` starts the auto lookup registration after startup, and repeats it every `Duration registerPeriod = Duration.ofSeconds(10);`.

While this is great for initial registration, I think it should be possible to skip the registration task once registered. Personally I'd be fine if, once registered on the sba server, the period could be 5 minutes.

For example, the registration task could always check "when did I get the latest GET request from sba server?". If this is more than X minutes ago, then POST the registration to sba. Otherwise skip-

This could be achieved for example by adding an interceptor on the `/health` endpoint:

```
@Configuration
public class WebMvcConfig implements WebMvcConfigurer {
  @Autowired
  private LastAccessInterceptor interceptor;

  @Override
  public void addInterceptors(InterceptorRegistry registry) {
    registry.addInterceptor(interceptor).addPathPatterns("/actuator/health");
  }
}
```

Then `ApplicationRegistrator.register()` could check `LastAccessInterceptor.isOutdate()` and only then send the registration.

If not, it would be great if `ApplicationRegistrator` could be an interface, so one could provide it's own functionality for `register()`.

**Comment by joshiste** [comment]
Hmm interesting approach... 
I'd suggest that the SBA server adds a custom header (e.g. `X-SBA-HEALTH-CHECK`) to the request so that the client checks the presence of this header.

Do you want to create a pull request? Currently I don't need this feature and I am totally lacking the time to do it.

> If not, it would be great if ApplicationRegistrator could be an interface, so one could provide it's own functionality for register().

Yeah we should do that regardless of the things above.

**Comment by ulischulte** [comment]
The period is configurable within a client via `spring.boot.admin.client`.
