### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [codecentric/spring-boot-admin#1199]
Hi
The following lines have cryptographic API misuses. <br> File name => spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/HashingInstanceUrlIdGenerator.java: Line number => 37: API name => MessageDigest:<BR> File name => spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/HashingInstanceUrlIdGenerator.java: Line number => 37: API name => MessageDigest:<BR> File name => spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/HashingInstanceUrlIdGenerator.java: Line number => 36: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by joshiste** [comment]
As we use the SHA-1 just to hash the health url, I don't see any problem with using the outdated algorithm.

Feel free to provide a PR to update the used algorithm.

**Comment by mhp0rtal** [comment]
Then it should be fine.
