### ISSUE TITLE
Some ideas for enhancements

### ISSUE THREAD

**Issue by RobWin** [codecentric/spring-boot-admin#12]
Hello,

I would like to contribute to spring-boot-admin in the future.
I have the following enhancement-ideas and we plan to implement them:
-  Health Checking: spring-boot-admin-server runs health checks regularly against a Spring Boot Actuator endpoint which is provided by the client-application during registration. If a client-application is down, the application is removed from the list.
- Distributed-Cache: We include hazelcast as a JCace-Provider.
- Service Discovery: spring-boot-admin-server can be deployed on multiple host and the state (registered applications) is replicated via hazelcast and can be used by client-applications to find services for client-side load balancing. 
- Spring Security: Add Spring Security to secure the spring-boot-admin-server endpoints (OAuth2, Basic Auth)

It could be a bootiful alternative to Netflix Eureka or HashiCorps Consul.

Kind regards,

Robert Winkler

**Comment by ouaibsky** [comment]
+1 for EnableAdminServerSwagger

**Comment by RobWin** [comment]
Have a look at my new project https://github.com/RobWin/swagger2asciidoc
If you want to document a RESTful API with Swagger, but dont' want habe the runtime overhead.

**Comment by joshiste** [comment]
Some features were added (e.g Hazelcast, more RESTful api, multiple instances with the same name).
Some will never make it (e.g. Swagger).
If something is still missing what you'd like to see please open new issue(s)

**Comment by RobWin** [comment]
Great thx.
