### ISSUE TITLE
Make plain text thread dump downloadable

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#1200]
see https://github.com/spring-projects/spring-boot/commit/c5cae282613d4229a8e4e9b0c3de5a1924d177a9

**Comment by skosijer** [comment]
Hello @joshiste , I started working on this one.

**Comment by joshiste** [comment]
Nice!

**Comment by skosijer** [comment]
@joshiste I have made the pull request. I'm open to any suggestions.
