### ISSUE TITLE
Custom brand name on login page

### ISSUE THREAD

**Issue by bjoernb94** [codecentric/spring-boot-admin#1201]
I wanted to give our spring boot admin instance a name. Everything works fine like in the documentation and works well. Except the brand name. It doesn't show up on the login page, which is a bit confusing for people who don't know the project behind it.

Would it be possible to let the name on the login page be configurable?

**Comment by ozkanpakdil** [comment]
after the merge title can be configured from application properties. example
`spring.boot.admin.ui.title: Project name - Spring boot admin`
