### ISSUE TITLE
Detect running port of a standalone Tomcat webserver

### ISSUE THREAD

**Issue by membersound** [codecentric/spring-boot-admin#1206]
Could you detect the running port of a standalone webserver running the war application?

Possible solutions:
https://stackoverflow.com/a/7482746/1194415
https://stackoverflow.com/questions/3867197/get-the-server-port-number-from-tomcat-without-a-request

**Comment by joshiste** [comment]
I'm not keen on implementing this:

1) Accessing it via JMX is not a viable solution, iirc with Spring Boot 2.2 the tomcat jmx beans are not registered by default anymore.
2) Accessing it from a filter's `init()` via reflection and traversing a complex hierarchy may be errorprone and cumbersome. Also it may not work if a SercurityManager is in place
3) Which connector from which engine should we choose if multiple are found?
4) What about other servlet containers like jetty and undertow?

But the good news is: Feel free to subclass the `DefaultApplicationFactory` and override the `getLocalServerPort()` for your project.

**Comment by membersound** [comment]
So I might even better override `ServletApplicationFactory` as when using in a tomcat environment?

**Comment by joshiste** [comment]
> So I might even better override `ServletApplicationFactory` as when using in a tomcat environment?

Ah yes, you're right.
