### ISSUE TITLE
Customise Image On Login Screen

### ISSUE THREAD

**Issue by michaelmcfadyensky** [codecentric/spring-boot-admin#1207]
The image used on the login screen is always the default image. This can be slightly confusing when we override the image using the property `spring.boot.admin.ui.brand`.

So can we either have the image on the login screen use the image set in the brand property or have a new property exposed that allows us to override the image in the login page?

**Comment by joshiste** [comment]
As a workaround for now you could use a completely customized login page by copying our template and adding it to the classpath and configuring a different login url.

But i'm also happy to accept a PR for this issue.

**Comment by michaelmcfadyensky** [comment]
Kl, I'll look at creating a PR for this this weekend
