### ISSUE TITLE
some service is offline

### ISSUE THREAD

**Issue by king-john** [codecentric/spring-boot-admin#1209]
I have a problem. When I use Spring Boot Admin Server and eureka, some services have been offline. A total of 34 services, 14 services are offline, how to deal with?
![image](https://user-images.githubusercontent.com/19261919/61172195-a22b8180-a5b3-11e9-922b-330a043d2cb9.png)

**Comment by joshiste** [comment]
You can either check the details page of one of the services which should give you a hint about the reason being offline. 
(In addition there should be some information about the reason identifying the service as offline should be in the sba servers logfile)

**Comment by king-john** [comment]
details page and log
![image](https://user-images.githubusercontent.com/19261919/61192272-bf606d00-a6e5-11e9-854e-570eb0e3e0a2.png)
![image](https://user-images.githubusercontent.com/19261919/61192296-eae35780-a6e5-11e9-828d-135c6d48fcd5.png)

Do you know why? Thank you.

**Comment by king-john** [comment]
I found the reason.
Services are offline because of they connect mongo or db fail .
Why does SBA 2.1.x not provide the following page:
![image](https://user-images.githubusercontent.com/19261919/61194714-e030be80-a6f5-11e9-9738-f9c8327121b2.png)
Does spring-boot-starter-actuator provide this information?

**Comment by king-john** [comment]
@

**Comment by king-john** [comment]
@joshiste

**Comment by joshiste** [comment]
It does. For spring boot 2.x client applications you need to configure ‘management.endpoint.health.show-details’ accordingly

**Comment by king-john** [comment]
Thank you very much
