### ISSUE TITLE
Preformat object values

### ISSUE THREAD

**Issue by sverhagen** [codecentric/spring-boot-admin#1213]
We have a bunch of health indicators that include additional details, some of which are objects (non-primitive values). These end up being rendered as JSON.

Ideally it would be nice if they weren't rendered as JSON. But as a start I propose to format the JSON. Something like this seems to work (in `health-details.vue`):

```
    <tr v-if="details && details.length > 0">
      <td class="health-details__nested" colspan="2">
        <table class="health-details table is-fullwidth">
          <tr class="health-details__detail" v-for="detail in details" :key="detail.name">
            <td v-text="detail.name" />
            <td v-if="name === 'diskSpace'" v-text="prettyBytes(detail.value)" />
+            <td v-else-if="typeof detail.value == 'object'">
+                <div class="object-value">{{ JSON.stringify(detail.value, null, 2) }}</div>
+            </td>
            <td class="is-breakable" v-else v-text="detail.value" />
          </tr>
        </table>
      </td>
    </tr>
```

This can be used in combination with the following CSS:

```
.object-value {
    white-space: pre;
    font-family: monospace;
    font-size: 0.8rem;
}
```

I think this would be a nice improvement. But I'd be also happy if I could do this as a [custom view](https://codecentric.github.io/spring-boot-admin/2.1.6/#customizing-custom-views). I just don't think that's how those work (without maybe me replacing all of the existing health details view), but I'm open to suggestions.

**Comment by joshiste** [comment]
do you want to raise a PR?

**Comment by sverhagen** [comment]
That's a good and, yeah, obvious response :wink: Could you please provide some guidance, though:
- Is this a valid approach, or is there a more-pluggable alternative?
- Do you think `health-details.vue` and `base.scss` are appropriate places to make this change?
- What tests would you expect to get updated?

I've not done anything with Vue before (plenty with Java), so I'm slightly uncomfortable _yet_ to make a public PR; let's get me over that :wink:

**Comment by joshiste** [comment]
> Is this a valid approach, or is there a more-pluggable alternative?

I totally think it is

> Do you think health-details.vue and base.scss are appropriate places to make this change?

the health-details.vue is the correct place, but you don't need that css class. Just use a ` <pre class="is-breakable">...</pre>`. (The is-breakable class is for preventing overflows on long strings)

> What tests would you expect to get updated?

None, as we only have a very few tests in the ui... 😢 

> I've not done anything with Vue before (plenty with Java), so I'm slightly uncomfortable yet to make a public PR

Just go ahead. I think it's a good opportunity if you want to learn new things. There is nothing you can do wrong.
