### ISSUE TITLE
Monitoring Scheduled Task Details

### ISSUE THREAD

**Issue by enesify** [codecentric/spring-boot-admin#1214]
Hi,

It would be nice that we are able to monitor extra information about scheduled tasks(crons) in addition to **Runnable** and **Expression**  like:

- Last Execution Time 

- Last Execution Status

- Next Execution Time (as mentioned in #432 

> may be the calculated next execution time

)

- Ability to change expression

- Ability to run a scheduled task manually

What you guys thinking about this?

Thanks.

**Comment by joshiste** [comment]
Yeah would be nice, but the spring boot actuator endpoint doesn't expose these details.
So do you raise an issue there?

**Comment by enesify** [comment]
OK. I raised an issue: [Spring Boot Actuator #17585](https://github.com/spring-projects/spring-boot/issues/17585)

Thanks again.
