### ISSUE TITLE
Add the ability to have a list of expected services

### ISSUE THREAD

**Issue by ddebree** [codecentric/spring-boot-admin#1215]
Currently in our environment we expect there to be an instance of service-x, however the wallboard doesn't show a block if there is no instances of the service available. Would like it to rather show a grey/red block with 0 instances. 
This is the same issue as found in this SO question https://stackoverflow.com/questions/54197214/show-missing-services-in-spring-boot-admin
This is also related to issue #1033

**Comment by joshiste** [comment]
Sound's like a duplicate to #1033
