### ISSUE TITLE
Applications are registered with pod name instead of service name

### ISSUE THREAD

**Issue by AshishRoyJava** [codecentric/spring-boot-admin#1218]
Hi,
I am trying to register my application to the SBA server. When The application is successfully deployed on kubernetes, I can see the application in the SBA dashboard but getting the following error.
![image](https://user-images.githubusercontent.com/19311770/61526762-b4387480-aa38-11e9-86a0-4f83335c558f.png)
The reason for this is the SBA server is trying access the application using the k8s pod name. But what it really needs to do is to check via k8s service name and port. This is what it is trying to access.
![image](https://user-images.githubusercontent.com/19311770/61526961-08dbef80-aa39-11e9-82b2-974ea244a12a.png)
Can anyone please help me resolve this issue?

**Comment by joshiste** [comment]
I'd suggest that you don't use our sba client, but the spring-cloud-kubernetes' discovery instead. 
I don't have a guide on this, but  talk on youtube (https://www.youtube.com/watch?v=Ql1Gnz4L_-c&t=8s) and some code (https://github.com/joshiste/chaos-monkey-spring-boot-demo/tree/SBA-K8s/admin)
