### ISSUE TITLE
InstanceRegistry contains stale data about client health status

### ISSUE THREAD

**Issue by Pashulity** [codecentric/spring-boot-admin#1221]
We use:
- Spring Boot 2.0.5 
- SBA-client 2.0.4 
- SBA-server 2.1.2

From time to time when accessing  _/applications_  url it is shown that our client is OFFLINE with io.netty.handler.timeout.ReadTimeoutException - but all health checks are UP. 

Debugging client side library shows that our app do registration properly at fixed rate and receives 201 code from admin-server. But server-side do not update info in Registry which caches OFFLINE state.

Moreover deregistering app solves the problem.

**Comment by joshiste** [comment]
> From time to time when accessing /applications url it is shown that our client is OFFLINE with io.netty.handler.timeout.ReadTimeoutException - but all health checks are UP.

Looks like your health check is too slow and doesn't respond in time. Either speed it up or increase `spring.boot.admin.monitor.read-timeout`

**Comment by Pashulity** [comment]
But is it okay that SBA caches info in registry and do not recover from exception? 

Imho if all checks are UP after fail info have to be updated and be up-to-date?

**Comment by joshiste** [comment]
It recovers from the exceptions, by periodically checking health. IIRC there was a bugfix on this. You should update to the latest & greatest (currently `2.1.6`)

**Comment by Pashulity** [comment]
Ok, hope this helps. Thank you!
