### ISSUE TITLE
Release a 2.2.0-Mx milestone for Spring Boot 2.2.x compatibility

### ISSUE THREAD

**Issue by sgautrin** [codecentric/spring-boot-admin#1222]
With a setup using SBA and cloud config for externalised configuration, SBA client version 2.1.x is currently not compatible with Spring Boot 2.2.0-Mx, as it leads to error of the type

```
Failed to bind properties under 'spring.boot.admin.client' to de.codecentric.boot.admin.client.config.ClientProperties:
    Reason: Environment must not be null
```

If there was a milestone release of SBA for 2.2.0-Mx based on the current snapshot, it would allow us to use 2.2.0-Mx together with SBA (the issue above is not present with the latest 2.2.0-SNAPSHOT)

**Comment by joshiste** [comment]
As sonatype doesn't provide a milestone repo - we don't publish milstones. But you can use your SNAPSHOT versions

**Comment by sgautrin** [comment]
Oh, that's a bummer indeed. Makes sense then why there's no milestone.
Snapshots will have to make do then.
