### ISSUE TITLE
couldn't load js css files

### ISSUE THREAD

**Issue by Nyamkhuub** [codecentric/spring-boot-admin#1225]
I gonna built microservice with Eureka, Zuul, and Config service. So I decided to add admin service on my microservices. Then, I deploy on Tomcat server with the war file. Finally, my admin service couldn't load js and CSS files.
I added to a yaml file this config:
``server:
  port: 8443
  servlet:
    context-path: /adminservice``

However, couldn't solve my problem! 
**Tomcat url:** localhost:8443/
**Admin service:** localhost:8443/adminservice
**All resource files url:** localhost:8443/assets/css/chunk-common.9808b72e.css
**Expected resource files url:** localhost:8443/adminservice/assets/css/chunk-common.9808b72e.css

Screenshot: <a href="https://imgur.com/7YNnOP0">click here</a>
Help me!

**Comment by joshiste** [comment]
see https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server

**Comment by Nyamkhuub** [comment]
@joshiste 
I am using this property spring.boot.admin.ui.public-url. Unfortunately, all js and CSS files URL couldn't change. 
For example:
I am gonna change localhost:8443/assets/js/chunk-vendors.1df687d0.js to localhost:8443/adminservice/assets/js/chunk-vendors.1df687d0.js

**Comment by Nyamkhuub** [comment]
I solve this problem :D just changing version to lastest version.
