### ISSUE TITLE
Couldn't get information of services from Eureka server

### ISSUE THREAD

**Issue by Nyamkhuub** [codecentric/spring-boot-admin#1228]
I am using these dependencies.
```
<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>spring-boot-admin-server</artifactId>
  <version>2.1.6</version>
</dependency>
<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>spring-boot-admin-server-ui</artifactId>
  <version>2.1.6</version>
</dependency>
```
But Admin service could fetch info from Eureka server. Help me?
![112](https://user-images.githubusercontent.com/40166245/62263029-5a2eaa80-b44d-11e9-8387-d4d29416ee15.PNG)
![1234](https://user-images.githubusercontent.com/40166245/62263030-5bf86e00-b44d-11e9-876d-ba4ee341d253.PNG)

**Comment by joshiste** [comment]
hmm hard to tell. can you pkease prove a project to reproduce the issue?
