### ISSUE TITLE
How to Make the Home Address of “Applications” Page Unclickable

### ISSUE THREAD

**Issue by huangpang** [codecentric/spring-boot-admin#1232]
** Question **

How to make the home page address of the Application page unable to click is currently a hyperlink

Not every service has a home page

This hyperlink is obvious, misleading me to click on it, resulting in a jump to an error page.

It was a bad experience.

I looked at the document and found no configuration items.

Can I change it? Thank you

` <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>2.1.6</version>
        </dependency>`

![QQ图片20190806110950](https://user-images.githubusercontent.com/31001984/62508576-bc672100-b83a-11e9-8405-786a824706d1.png)

**Comment by joshiste** [comment]
Currently it's not possibe to disable this link. But in case you are using the sba client you could configure an URL that's actually working (using `spring.boot.admin.client.instance.service-url`)
