### ISSUE TITLE
The urls are bad with docker

### ISSUE THREAD

**Issue by raulvillalbamedina** [codecentric/spring-boot-admin#1238]
Hello,

In SpringBootadmin I see my apps but the urls are bad.
With prefer-ip=false I see this urls http://4dd5b59afd25:9085/
With prefer-ip=true I see this urls http://10.0.5.58:9085/

In both cases are not working. 

I need see the correct url.

My springbootadmin version 2.0.5.

Thank you

**Comment by joshiste** [comment]
then you need to set the `service-base-url`
