### ISSUE TITLE
Can not find logfile when using Spring Cloud Config

### ISSUE THREAD

**Issue by AnsonCong** [codecentric/spring-boot-admin#1239]
Hello,
      When i set up a Spring Cloud Admin server  and Admin client without Spring Cloud config, i can get the logfile successfully in Admin UI, below is my properties:

logging:
  file: /app/log/app.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

But when i try to integrate with Spring cloud config with same yml property, i got 404 error.
BTW my spring cloud config properties files are set in local instead of using git 
And i tried different property such as 
endpoints.logfile.enabled = true
endpoints.logfile.external-file = ''
No one is active.
Do u have any idea about this?

**Comment by AnsonCong** [comment]
Updated:
    When i try to move the logging configuration from Spring Cloud Conifg  to Spring Cloud Admin client's bootstrap.yml,  it works.

**Comment by joshiste** [comment]
I'm closing this issue as it looks to me that you could resolve the issue on your own.

**Comment by AnsonCong** [comment]
Why Spring cloud config not working for logging.file or logging.path?  If i have 100 Admin client services i need to config 100 times in each bootstrap.yml file. That's bad  :(

**Comment by joshiste** [comment]
I don’t know. I guess it is a question you have to ask the spring cloud/boot folks, as the neither the logging endpoint nor the bootstrap-context are part of spring boot admin.

**Comment by dragon74** [comment]
Did you guys opened an issue there?

**Comment by snqlby** [comment]
```
logging:
  file: ${spring.application.name}.log
management:
  endpoint:
    logfile:
      external_file: ${spring.application.name}.log
```
Setting `external_file` should fix the problem.
