### ISSUE TITLE
[2.2.0-SNAPSHOT][Client] impossible to add username password

### ISSUE THREAD

**Issue by patpatpat123** [codecentric/spring-boot-admin#1245]
Hello SBA Team,

This issue is about client side, on the latest 2.2.0 snapshot.
As of now, I believe it is impossible to use username and password against a SBA server protected by Spring Security (which is highly probable)

Because it is not possible to add credential here:
```
 @Bean
    public ApplicationRegistrator getCustomApplicationRegistrator() {
        return new ApplicationRegistrator( applicationFactoryBean, new ReactiveRegistrationClient( getWebClient( ), Duration.ofSeconds(5L) ), new String[]{"https://localhost:8080/instances"}, true );
    }
```
The underneath implementation for ReactiveRegistrationClient does not allow to add credentials while it performs the post request. This is tested and working while SBAServer does not need credentials, but not working and impossible to workaround when it requires.
Please let me know if my understanding is incorrect.
Thank you for your help.
This project is awesome, cheers.

P.S: It is a bit painful to have to add an explicit duration for the block() and not to be able to get the admin URL with the Environment, and having to append /instances at the end.

**Comment by joshiste** [comment]
> The underneath implementation for ReactiveRegistrationClient does not allow to add credentials while it performs the post request

Yes, you need to configure a ExchangeFilterFunction on the WebClient which does that.

>  It is a bit painful to have to add an explicit duration for the block() and not to be able to get the admin URL with the Environment, and having to append /instances at the end.

You can use the `ClientProperties` to get that values from the configuration...

Here is some sample code:
the `getWebClientBuilder()` would be the section, where you do your custom webclient configuration...

```
import de.codecentric.boot.admin.client.config.ClientProperties;
import static org.springframework.web.reactive.function.client.ExchangeFilterFunctions.basicAuthentication;

...

@Configuration
@EnableConfigurationProperties({ClientProperties.class})
public class CustomConfig {

        @Bean
        public ReactiveRegistrationClient registrationClient(ClientProperties client) 
            WebClient.Builder webClient = getWebClientBuilder();
            if (client.getUsername() != null && client.getPassword() != null) {
                webClient = webClient.filter(basicAuthentication(client.getUsername(), client.getPassword()));
            }
            return new ReactiveRegistrationClient(webClient.build(), client.getReadTimeout());
        }
}

**Comment by patpatpat123** [comment]
Hello,

Indeed, much appreciated for your working solution.
Good day.
