### ISSUE TITLE
Insights->metrics->hikaricp.connections （/actuator/metrics/hikaricp.connections ）The service returns an exception after a period of normal operation.

### ISSUE THREAD

**Issue by fenghualiusha** [codecentric/spring-boot-admin#1246]
![image](https://user-images.githubusercontent.com/22256233/64173122-28b06100-ce89-11e9-97e2-0422a08da1d7.png)

Exeption Info：<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Sep 02 21:53:23 CST 2019</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>Could not write JSON: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.; nested exception is java.lang.IllegalArgumentException: NaN is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.</div></body></html>

**Comment by joshiste** [comment]
sorry I don't speak chinese. Please provide a proper error description in english please.

**Comment by fenghualiusha** [comment]
No reason found，why

**Comment by joshiste** [comment]
It looks to me as if the underlying spring boot application has problem writing the response. I guess this is more a spring boot issue.

**Comment by fenghualiusha** [comment]
Thank you, I've now understood
