### ISSUE TITLE
Do not spam logs with StatusUpdater WARN messages for offline apps

### ISSUE THREAD

**Issue by lightoze** [codecentric/spring-boot-admin#125]
Hi,

I have a suggestion to change WARN logging level to INFO in `StatusUpdater.queryStatus#100` if the application is already offline. This way it will be easy to get only the first offline message to the log file.
Consider the case when spring-boot-admin is an embedded part of master server and there's a combined warnings/errors log for all components.

**Comment by joshiste** [comment]
I really like your suggestion, so I implemented it instantly. Thanks!

**Comment by lightoze** [comment]
Great, just in time before 1.3 release! :)
