### ISSUE TITLE
HttpHeadersProvider doesn't seem to work

### ISSUE THREAD

**Issue by dtitov** [codecentric/spring-boot-admin#1253]
**Spring Boot version**: 2.1.7.RELEASE

**Spring Boot Admin version**: 2.1.6

I have a header-based authentication in my app. Let's assume, for simplicity, that Spring security filter just checks whether header `X` has value `Y`, and if so, authentication is granted.

So, in order to let SBA client be able to authenticate against the server (`/instances` endpoint and `/actuator` endpoints are protected), I have registered a `HttpHeadersProvider` bean [as per reference](https://codecentric.github.io/spring-boot-admin/current/#_securing_client_actuator_endpoints):

```
    @Bean
    public HttpHeadersProvider myHttpHeadersProvider() {
        return instance -> {
            HttpHeaders httpHeaders = new HttpHeaders();
            httpHeaders.add("X", "Y");
            return httpHeaders;
        };
    }
```

The approach above didn't work. SBA Client just fails with `Failed to register application as...` and I don't see the header `X` in my security filter. If I make `/instances` public, but keep `/actuator` protected, the SBA Client is able to register itself, but then there's no data in the SBA interface and the instance is marked red.

**Comment by joshiste** [comment]
@dtitov the `HttpHeadersProvider` is used only in requests from the SBA server to the clients and not the other way around. If you need to add extra headers to the registration request you need to either use a custom configured RestTemplate and instantiate the ApplicationRegistrator with it or customize the ApplicationRegistrator itself.

**Comment by dtitov** [comment]
Thank you, I will try. But isn't it something you could consider adding to the Spring Boot Client, the same way it's done on the Server side? IMHO, the need for using custom headers is not something very rare...

**Comment by dtitov** [comment]
Also, it's quite cumbersome to customize `ApplicationRegistrator`, because `RestTemplate`, for example, has `private` access. Eventually one needs to copy-paste almost the whole class...

**Comment by joshiste** [comment]
Yes, adding custom headers is also useful in the client, but can be done via customizing the RestTemplate, as the headers are always for the same target and therefore mostly static.

On the SBA server the requests are made to different targets so computing the headers depending on which application the request is made to, is a bit more complex,  so we added this concept in the past.

Also customizing the used RestTemplate is a bit easier with SBA 2.2.0, as you don't need to instantiate the ApplicationRegistrator with all the dependencies yourself, but only a `BlockingRegistrationClient`, which has less dependencies.

**Comment by dtitov** [comment]
The problem is that, AFAIK, once can't just inject custom headers to the `RestTemplate`: custom headers are applied upon a particular call, i.e. `exchange(..)` method. So it doesn't seem to be possible to just create `RestTemplate` with pre-populated custom headers. Correct me, if I'm wrong.

But thank you anyway, I will try SBA 2+. Meanwhile, I can confirm that overriding `ApplicationRegistrator ` worked 👍 

However, I'm still facing issues with management endpoints. Actuator doesn't seem to be accessible, even though I kept `HttpHeadersProvider`.

**Comment by joshiste** [comment]
IIRC when using the RestTemplateBuilder you can set default headers or register interceptors that add the headers to each request.

**Comment by dtitov** [comment]
You are correct. I used `RestTemplateBuilder` to pre-populate `RestTemplate` with headers and it worked.

Also, I've solved the Actuator problem: it appeared that custom headers from `HttpHeadersProvider` are not added to probe-requests to the Actuator endpoints (`OPTIONS`). Thus, my authentication mechanism was blocking such requests. Eventually, I removed authentication from `OPTIONS` requests to the Actuator endpoint and it started to work after that.

Can you confirm that this is expected behavior (I mean not adding custom headers to probe requests)?

**Comment by joshiste** [comment]
> Can you confirm that this is expected behavior (I mean not adding custom headers to probe requests)?

No. This is not expected.

**Comment by dtitov** [comment]
Should I file an issue about it then?

**Comment by joshiste** [comment]
Yeah.
