### ISSUE TITLE
Set the logging level for a not explicitly configured logger

### ISSUE THREAD

**Issue by wildhai** [codecentric/spring-boot-admin#1256]
Currently (version 2.1.6) we are not able to set the logging level for a not explicitly configured logger via Spring Boot Admin UI. But with the original Spring Boot Actuator API it is possible to set the logging level for a not explicitly configured logger.

Supposed in the logging configuration is only specified a package logger "com.company". Nevertheless we are able to set the logging level for a specific logger "com.company.ControllerX" (which was not explicitly specified in the logging configuration file) via POST to "https://spring-boot-host/actuator/loggers/com.company.ControllerX".

Unfortunately it seems not possible to set such a specific logger below logger "com.company" via Spring Boot Admin UI because the Loggers dialog of the UI provides only the explicitly configured loggers. The input field of this dialog works only as a filter.

Thank you very much for your very useful tool. If you would support this feature it would be even more valuable.

**Comment by joshiste** [comment]
IIRC this is currently only a problem for the log4j2 backend. 
It looks like the loggers endpoint does support the creation of new loggers.
Would you like to work on a PR for this?
