### ISSUE TITLE
Pls handle -> BeanCreationNotAllowedException #833

### ISSUE THREAD

**Issue by luodongseu** [codecentric/spring-boot-admin#1258]
I have the same error when shutdown spring cloud project with feign clients;

pls solve  it!

Demo is here: BeanCreationNotAllowedException #833

**Comment by joshiste** [comment]
@luodongseu I don't know. I haven't looked at the sample project, as it is pretty outdated. And I'm lacking the time to reproduce the error from scratch. So If you want me to have a look at it please provide an up-to-date sample to reproduce the error.

**Comment by joshiste** [comment]
> Is that we need implements BeanFactoryPostProcessor to set feignContext bean depends on registrainListener?

just give it a try.

**Comment by joshiste** [comment]
closing due to missing feedback

**Comment by luodongseu** [comment]
Finally, i set bean dependencies in custom BeanFactoryPostProcessor, which like this:
`
BeanDefinition bd1 = beanFactory.getBeanDefinition("feignContext");
bd1.setDependsOn("registrationListener");

BeanDefinition bd2 = beanFactory.getBeanDefinition("springClientFactory");
bd2.setDependsOn("registrationListener");
`
