### ISSUE TITLE
fetched Environment from Instance breaks Environment-UI

### ISSUE THREAD

**Issue by duffy356** [codecentric/spring-boot-admin#1261]
I have an Spring-Application, which registers at Spring-Boot-Admin and I can open it and watch the Details. (=Click on the instance on the Application overview in Spring-Boot-Admin/Applications)
When I want to take a deeper look at the Environment of the selected instance I get only a loading spinner. (see Screenshot: "sba_env_null.jpg").

I figured out, that the problem is the env/-Response from my Instance-Application:
There is one entry which only has a name and no properties-object embedded. (wee Screenshot: "sba_env_null.jpg" at Response-View). I think usually the properties-object should be an empty object, but in my case it is missing.
The result of that propertySource-entry is a JavaScript Error in Chrome => "TypeError: Cannot convert undefined or null to object" - so the result is a broken environment-page with a spinner of death.

I think i found the problem:

 in `spring-boot-admin-server-ui/src/main/frontend/views/instances/env/index.vue:59` there is the if-condition  v-if="Object.keys(propertySource.properties).length > 0" which produces the error, because propertySource.properties is undefined.
 
I fixed it to `v-if="!!propertySource.properties && Object.keys(propertySource.properties).length > 0"` which solves the problem. The UI loads and shows the message of "No properties set" (the else-path). See the result in Screenshot "sba_env_fixed.jpg".

There might be another place, in env-manager.vue where the same reason produces an error.

**Version of Spring-Boot-Admin**: 2.1.5

**Version of Spring in Instance-Application**:
Spring-Boot:2.1.4.RELEASE
Spring-Cloud:Greenwich.SR1
Spring-Framework: 5.1.6.RELEASE
de.codecentric:spring-boot-admin-starter-client:2.1.4

I embedded a Screenshot of the Spring-Boot-Admin UI with the repsonse of "env/" and the message in console.

the result of environment view (="sba_env_null.jpg"):
![sba_env_null.jpg](https://user-images.githubusercontent.com/4521548/65028883-129ca900-d93d-11e9-9288-b4bc41c7e452.jpg)
The result after the fix in `.../env/index.vue:59` (="sba_env_fixed.jpg")
![sba_env_fixed.jpg](https://user-images.githubusercontent.com/4521548/65032748-fea87580-d943-11e9-8a52-0a50aae6d14f.jpg)
[sb_evn_response.txt](https://github.com/codecentric/spring-boot-admin/files/3620373/sb_evn_response.txt)

**Comment by joshiste** [comment]
Did you set `spring.jackson.serialization-inclusion=NON_EMPTY` or applied a similar configuration to your object mapper?
If no: I'd guess this is a bug. As you already figured what need's to be changed, to you want to submit a PR?
If yes: We rely on the default jackson config for the actuator endpionts. I'd expect that you experience similar issues all over SBA?

**Comment by duffy356** [comment]
Hi,
I figured out a similar problem at the "liquibase"-view and could find out, that the reason is an ObjectMapper with `spring.jackson.serialization-inclusion=NON_EMPTY`.
So **yes** is the answer to your question.
So when SBA has to be "served" with the default Spring-Jackson properties, we have to change our serialization configurations, and you don't have a Bug, because you can't have a bug for something you don't support. Do you think it's a feature request?

**Comment by joshiste** [comment]
> Do you think it's a feature request?

Imho regardless wether it's a bug or a feature request, the question is: do we want to support custom jackson configurations? 
We had a similar request for snake-case, which imho would require higher efforts.

In the end I think I'd accept PRs to support the NON_EMPTY option,  but won't support it officially . So If you wan't to propose a PR: go ahead!

**Comment by joshiste** [comment]
@duffy356 so will you do some PR on this?
