### ISSUE TITLE
Challenging the disposal of scheduler in AbstractEventHandlers

### ISSUE THREAD

**Issue by simonbasle** [codecentric/spring-boot-admin#1263]
Hi,
I've only quickly looked at the code while evaluating reactor/reactor-core#1777 and #1175, and it seems to me that there is an overeager disposal of schedulers in various `AbstractEventHandler`, like the `NotificationTrigger` here:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/NotificationTrigger.java#L42

The problem I see with this is that the `Scheduler` is instantiated only once, at least per call to `handle`, while the resulting `Flux` can be subscribed several times, due to `retryWhen` in `AbstractEventHandler#start`:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/AbstractEventHandler.java#L48

I see three possible solutions:
 * introduce the notion of handler resource in the API, to be established in `start()` and destroyed in `stop()`. The `Scheduler` becomes such a "resource" and doesn't need to be disposed in the `doFinally`, but rather will be disposed in `stop()`
 * defer the instantiation of the `Scheduler` to instantiate one new for each subscription to the `handler` `Publisher` (ie wrap the content of that whole `handler` method I linked in a `Flux.defer(() -> {...})` block). each will be properly disposed in `doFinally`
 * use `compose` (or `transformDeferred` in 3.3.0) instead of `transform` in `start`, as an alternative syntax to achieve the same as above

**Comment by simonbasle** [comment]
(note I'm not a user of `spring-boot-admin`, this just stemmed from looking at the source following up on the above reactor-core issue)

**Comment by joshiste** [comment]
@simonbasle thanks for your advise. I'll take a look at it.
