### ISSUE TITLE
conflict  org.springframework.boot：2.1.7.RELEASE  with  springBootAdmin 2.0.2

### ISSUE THREAD

**Issue by ffeiko** [codecentric/spring-boot-admin#1264]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.7.RELEASE</version>
    </parent>

    <groupId>com.ffeiko</groupId>
    <artifactId>springBootAdmin</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>springBootAdmin</name>
    <description>Demo springBootAdmin for Spring Boot</description>

    <dependencies>

        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

    </dependencies>

</project>
`
**
***************************
APPLICATION FAILED TO START
***************************

Description:

Method requestMappingHandlerAdapter in org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration required a bean named 'webMvcAsyncTaskExecutor' that could not be found.

Action:

Consider defining a bean named 'webMvcAsyncTaskExecutor' in your configuration.

Disconnected from the target VM, address: '127.0.0.1:65499', transport: 'socket'

Process finished with exit code 
**

**Comment by joshiste** [comment]
Please upgrade to SBA 2.1.6
