### ISSUE TITLE
Admin UI 'applications' event stream toggle or improved fallback

### ISSUE THREAD

**Issue by jrobison153** [codecentric/spring-boot-admin#1265]
We are running Spring Boot Admin 2.1.x behind Zuul 1.x. Zuul does not support the text/stream content type. When the Admin Server UI attempts to setup the application stream we get an error because Zuul doesn't not respect the stream. The Admin Server UI then attempts to re-establish the stream, which fails again. Rinse and repeat every 10 seconds. This behavior generates a lot of error logging (polluting the log files) and also results in the UI flashing a "
Server connection failed." warning every 10 seconds or so. It looks like the 'applications' stream and the synchronous polling call to 'applications' return the same data, so the stream doesn't appear to be necessary to get the full benefit of the Admin Server (please correct me if this thinking is flawed). 

It seems reasonable to either have the ability to disable the attempt to establish the stream or enhance the retry logic to abort on initial failure and/or key off of a 406 response code to stop trying to establish the stream.

Is this something you would consider taking a PR for? If so which strategy would prefer: config property to disable, retry logic changes on failures and/or 406 status, all of the above?

Thanks in advance for any help

**Comment by joshiste** [comment]
I'd be ok with stop retrying after a 406 and switching to a regular polling. 
But since we're using the `EventSource` from the Browser this may be hard to achieve - so in the end it depends on the complexity of the solution...

Also may be you'd be better of with upgrading to spring-cloud-gateway as zuul v1 is afaik not maintained anymore.

**Comment by jrobison153** [comment]
Hi @joshiste,
thanks for the quick response. Changing over to spring-cloud-gateway is an option but we've been punting because Zuul is part of a pattern we're deprecating (support for another year ish tops). The upgrade of SB Admin jibes with a number of other upgrades we are making in the Spring Cloud ecosystem we're working with. Let me take a look at what a solution might look like and see where we land. 

Cheers!

**Comment by SteKoe** [comment]
As Zuul still does not support websockets and https://github.com/spring-cloud/spring-cloud-gateway/ has taken Zuuls place, I will close this issue here.
