### ISSUE TITLE
Use Admin with consul for different management port

### ISSUE THREAD

**Issue by zznnqq210** [codecentric/spring-boot-admin#1267]

**Comment by zznnqq210** [comment]
![图片](https://user-images.githubusercontent.com/12114031/65740957-1a1e3800-e11d-11e9-882c-4f441a198ac6.png)
![图片](https://user-images.githubusercontent.com/12114031/65740969-26a29080-e11d-11e9-9494-7a9879738e65.png)
The service are not well and I found a error in console:
![图片](https://user-images.githubusercontent.com/12114031/65741079-81d48300-e11d-11e9-8074-f6990e02f3f0.png)

**Comment by joshiste** [comment]
Please provide a proper description of this issue and please provide a project to reproduce this issue.

**Comment by joshiste** [comment]
Also please consult the documentation on the part for adjusting the registration using discovery metadata:  https://codecentric.github.io/spring-boot-admin/current/#_converting_serviceinstances

**Comment by zznnqq210** [comment]
Ok, I have add the `management.port` metadata, so this problem is be resolved, thank you!
