### ISSUE TITLE
There is a way to embed spring-boot-admin to existing webapp ?

### ISSUE THREAD

**Issue by M3lkior** [codecentric/spring-boot-admin#127]
Hello,

There is a way to embed spring-boot-admin to existing webapp, not standalone deployed (i.e in tomcat container)  ?
I try to embed your project in my webapp to simply display actuator-endpoints datas but RevereseZuulProxyConfiguration causes me troubles with Spring ServerConfiguration (not existing because of i am using an external container)

Thanks

**Comment by joshiste** [comment]
You should be able to deploy it as .war-file in the same container, but integrating into existing apps is not supported.
There would be also be an conflict with the http-paths since boot admin is serving on `/`
