### ISSUE TITLE
Show content-type and content-length for the request in http traces

### ISSUE THREAD

**Issue by thanhphi0401** [codecentric/spring-boot-admin#1287]
I want to get the length of response and show in Spring Admin . But  Why the Length tab don't show data? 
![67256824-365e8c00-f4b3-11e9-9f1c-f9e26c112e7d](https://user-images.githubusercontent.com/32038840/67256968-e3d19f80-f4b3-11e9-9b24-bb55f0e9833e.png)

My config: 
```
management.endpoints.web.exposure.include=*
management.security.enabled = false
endpoints.health.sensitive = false
management.endpoint.health.show-details=always
management.health.consul.enabled=false

spring.boot.admin.client.username=***
spring.boot.admin.client.password=***
```

**Comment by joshiste** [comment]
The length (as well as the content-type) are currently just displaying the values for the response and not for the request. And they also rely on the content-length header to be present which is not the case when the transfer encoding is chunked.

**Comment by joshiste** [comment]
Would you volunteer to work an a pull request for this?

**Comment by 1412392** [comment]
> The length (as well as the content-type) are currently just displaying the values for the response and not for the request. And they also rely on the content-length header to be present which is not the case when the transfer encoding is chunked.

But why it doesn't display the values for the response? i want display the weight  of output response data ? any  more config or we need to work on it?

**Comment by joshiste** [comment]
does your response have a content-length header?

**Comment by 1412392** [comment]
> does your response have a content-length header?

yes, some response has content-length header
![image](https://user-images.githubusercontent.com/32038840/67380672-e49e2a80-f5b4-11e9-9f9c-1157f2cc5ed2.png)

**Comment by joshiste** [comment]
This is the request, not the response.

**Comment by 1412392** [comment]
> This is the request, not the response.

thank you. i got it

**Comment by skosijer** [comment]
Do you plan on doing something here @1412392 ? 
What behavior would you guys want here when the actual content-length is missing from the response like @joshiste mentioned?
I would be happy to contribute, just give me a hand here to understand your needs better.

**Comment by aeasylife** [comment]
Say something else.

I see that in your figure, there is an application in down state. I guess it's SBA. Is it true that everyone is like this? Is SBA in down state OK?

**Comment by ulischulte** [comment]
#1593
