### ISSUE TITLE
Error creating bean with name 'adminHandlerMapping' defined in class path resource

### ISSUE THREAD

**Issue by Adhders** [codecentric/spring-boot-admin#1292]
error message shows when I start the programm,
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'adminHandlerMapping' defined in class path resource with springboot 2.2.0, spring-boot-admin2.1.6

**Comment by joshiste** [comment]
duplicate of https://github.com/codecentric/spring-boot-admin/issues/1279#issuecomment-543121890
