### ISSUE TITLE
as the time axis of charts could be longer?

### ISSUE THREAD

**Issue by ygsama** [codecentric/spring-boot-admin#1295]
** Question **
As I want to see the charts in the last night , but the time axis so short .
How could I do ? 
Is there some settings can make it?

**Comment by ygsama** [comment]
I had attempt to use the `spring-boot-admin`  &  `prometheus+grafana`.
Then , I find the `prometheus+grafana` is too heavy weight to my application, 
    and the chart axis  of `spring-boot-admin`  is stiff.

**Comment by joshiste** [comment]
Which chart are you referring to?

**Comment by ygsama** [comment]
![image](https://user-images.githubusercontent.com/28083474/68108982-5f0b6a80-ff24-11e9-96e5-248d9a78755b.png)

like this , the time axis is so short.
If I want to see the charts in the last night, how to do ?

**Comment by joshiste** [comment]
Currently this is not possible. 
Also having all the data in memory for > 10h in your browsers memory is a problem. That would need some kind of condensing the data.

Imho that's what timeseries DBs are made for. Currently having long term data is out-of-scope for spring boot admin. 

You could though add a custom view that does exactly what you want...

**Comment by ygsama** [comment]
I see , thank you .
