### ISSUE TITLE
The parent pom.xml can't  resolve symbol  "repositoryId"

### ISSUE THREAD

**Issue by Adhders** [codecentric/spring-boot-admin#1296]

**Comment by Adhders** [comment]
The parent pom.xml can't  resolve symbol  "repositoryId" 

<plugin>
                        <groupId>org.sonatype.plugins</groupId>
                        <artifactId>nexus-staging-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>default-deploy</id>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>deploy</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <serverId>${repositoryId}</serverId>
                            <nexusUrl>https://oss.sonatype.org</nexusUrl>
                            
                            <stagingProfileId>1e79a0f1acc1b8</stagingProfileId>
                        </configuration>
 </plugin>

**Comment by joshiste** [comment]
Sorry, but I don't know what you trying to do. Could you please elaborate on what you want to do?

**Comment by Adhders** [comment]
<serverId>${repositoryId}</serverId>

**Comment by Adhders** [comment]
> Sorry, but I don't know what you trying to do. Could you please elaborate on what you want to do?

there is error in  line 479  of  pom.xml , "repositoryId" isn't defined

**Comment by joshiste** [comment]
Yes. It is set by our deplyoment process from the environment. But what are you trying to do?

**Comment by Adhders** [comment]
> Yes. It is set by our deployment process to maven central in the environment. But what are you trying to do?

thanks,It's run normally ,I just want to learn the configuration of pom.
