### ISSUE TITLE
403 FORBIDDEN from client side when security switched on.

### ISSUE THREAD

**Issue by salexandrs** [codecentric/spring-boot-admin#1302]
Hello
I'm using SBA "de.codecentric:spring-boot-admin-starter-server:2.1.6" on server side and
"de.codecentric:spring-boot-admin-starter-client:2.1.6" on client side and
 springBootVersion = "2.1.5.RELEASE" on both sides.

Without any security configuration my client application registered at SBA server without any issue, I can see all info, which I've opened at client actuator.

If I only switch on security at SBA server side, my client can't connect to the SBA server to HTTP POST localhost:8090/instances and I see an exception from client side 

```
o.s.web.client.RestTemplate              : HTTP POST http://localhost:8090/instances
o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
o.s.web.client.RestTemplate              : Writing [Application(name=demo-worker, managementUrl=http://localhost:8091/actuator, healthUrl=http://localhost:8091/actuator/health, serviceUrl=http://localhost:8091/)] as "application/json"
s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@3fa4b4548 pairs: {POST /instances HTTP/1.1: null}{Accept: application/json}{Content-Type: application/json}{Authorization: Basic YWRtaW46YWRtaW4=}{User-Agent: Java/1.8.0_211}{Host: localhost:8090}{Connection: keep-alive}{Content-Length: 267}
s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@15f6600711 pairs: {null: HTTP/1.1 403}{Content-Type: text/plain}{Cache-Control: no-cache, no-store, max-age=0, must-revalidate}{Pragma: no-cache}{Expires: 0}{X-Content-Type-Options: nosniff}{X-Frame-Options: DENY}{X-XSS-Protection: 1 ; mode=block}{Referrer-Policy: no-referrer}{Transfer-Encoding: chunked}{Date: Mon, 18 Nov 2019 16:47:45 GMT}
o.s.web.client.RestTemplate              : Response 403 FORBIDDEN
```
and I see empty list of manages clients at SBA server UI after login.
My SBA server and client configuration is very simple.

On SBA server side I've just added dependency 
```
implementation 'org.springframework.boot:spring-boot-starter-security'
```
and properties  on server side are
```
info.build.name="${name}"
info.build.version="${version}"
info.app.description=SBA server

spring.application.name=admin-service
spring.application.team="${name}"
spring.application.service="${name}"
spring.application.component=backend-app

instance.name=admin
feed.generation.type=ADMIN

spring.security.user.name=admin
spring.security.user.password=admin
server.port=8090

management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/_manage
management.endpoints.jmx.exposure.include=*
management.endpoint.shutdown.enabled=true
management.server.port=8090
```

Properties at SBA client side contains the same user and password  for success connection to server.
SBA client properties are
```
info.build.name="adminClientDemo"
info.build.version="0.0.1"
info.app.description=SBA client
management.info.git.mode=simple

spring.application.name=demo-worker
spring.application.team=PSF
spring.application.service=PIM
spring.application.component=backend-app

instance.name=clientdemo
feed.generation.type=CLIENTDEMO

spring.boot.admin.url=http://localhost:8090
spring.boot.admin.client.url=http://localhost:8090  

spring.boot.admin.username=admin
spring.boot.admin.password=admin
spring.boot.admin.client.metadata.user.name = admin
spring.boot.admin.client.metadata.user.password = admin
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin
```

**Comment by joshiste** [comment]
having a quick look at the properties, it looks ok.

If you want me to take a look at it please provide a project wich I can build and execute.

**Comment by salexandrs** [comment]
Hello @joshiste 
SBA server can be reached from the link [repository with SBA server](https://github.com/salexandrs/sbatest)
SBA client can be reached from the link [repository with SBA client](https://github.com/salexandrs/sbaclient)
Both server and client were created according to SBA documentation and without authentication at server side client can register himself at the server.
The issue is, that with security at SBA server side client can't connect to the server.But I also wish to add security at client side also.

**Comment by joshiste** [comment]
you need to disable the csrf protection for POST on `/instances`

**Comment by joshiste** [comment]
At best you adapt the security config from our docs
