### ISSUE TITLE
configuring spring boot admin in kubernetes

### ISSUE THREAD

**Issue by RanjanaG** [codecentric/spring-boot-admin#1303]
Hello,

We are not able to configure spring boot admin in kubernetes envirnoment.
Please share the configuration steps

**Comment by joshiste** [comment]
In SBA you don't have to configure something special, but for the spring-cloud-kubernetes you have to. I don't have a step-by-step guide for this, but you can find some sample code here: https://github.com/joshiste/chaos-monkey-spring-boot-demo/tree/SBA-K8s
