### ISSUE TITLE
Browser notification shows wrong hostname

### ISSUE THREAD

**Issue by kreyssel** [codecentric/spring-boot-admin#131]
Hi,

if I have my spring-boot app registered two times on the spring-boot-admin server on two different hosts, the browser notifications (popups) for the second app shows the hostname of the first registered app. Maybe you can fix it.

I use spring-boot and spring-boot-admin 1.3.0 - Chrome 47 on WIndows.

Thanks 
Conny

**Comment by joshiste** [comment]
![image](https://cloud.githubusercontent.com/assets/8779225/11728620/280afbce-9f8b-11e5-814b-18b8d3be24f6.png)

Are you referring to the url at the bottom of the message? This isn't the url of the application went down. Its the url of the website sending you the notifiacation. The url of the concerning ain't shown in the message at all, but if you click on it you will get to the detail-page.
