### ISSUE TITLE
Requirement to register the services by an environment parameter

### ISSUE THREAD

**Issue by Ask149** [codecentric/spring-boot-admin#1310]
Preview 
I am working on developing a spring boot admin application, for monitoring the spring boot services that are currently hosted on a cloud server which uses OpenShift for balancing the load of different services across a particular set data centers. Inorder to successfully registered all the applications to the monitoring service ( Spring Boot Admin Server ), the applications makes an API call to register itself to the Server, which then gets registered to the server by providing it's unique management url on which the Spring Boot applications are running.

Feature Request
To complete the above mentioned application, I need to register the client application by a environment property that is unique for every POD in the application.

**Comment by pJaideep** [comment]
> Preview
> I am working on developing a spring boot admin application, for monitoring the spring boot services that are currently hosted on a cloud server which uses OpenShift for balancing the load of different services across a particular set data centers. Inorder to successfully registered all the applications to the monitoring service ( Spring Boot Admin Server ), the applications makes an API call to register itself to the Server, which then gets registered to the server by providing it's unique management url on which the Spring Boot applications are running.
> 
> Feature Request
> To complete the above mentioned application, I need to register the client application by a environment property that is unique for every POD in the application.

I am facing a similar requirement, could anyone please reply at the earliest

**Comment by joshiste** [comment]
>To complete the above mentioned application, I need to register the client application by a environment property that is unique for every POD in the application.

So you want to have applications with the same name but with a different environment set distinguishable in the admin UI?

Imho you should use a SBA instance for each environment, to keep em fully separated and also being able to deploy different versions of SBA.

**Comment by joshiste** [comment]
As i've received no feedback on my suggestion, I guess the problem has been solved and I close this feature request.
