### ISSUE TITLE
starter-server 2.1.5.RELEASE doesn't show application upgraded to spring boot 2.2.1.RELEASE

### ISSUE THREAD

**Issue by jhartotr** [codecentric/spring-boot-admin#1311]
starter-server 2.1.5.RELEASE worked without issues showing an application running spring boot 2.1.5.RELEASE. After upgrading that application to spring boot 2.2.1.RELEASE, the following starter-server URL 

http://localhost:8080/admin/#/applications

doesn't show any applications. The starter-server DEBUG logs show:

> 2019-11-25 21:32:20.317 DEBUG 6610 --- [nio-8080-exec-2] o.a.coyote.http11.Http11InputBuffer      : Received [POST /instances HTTP/1.1
> Authorization: Basic ZTJkeDo5Yjc4ODNiMjcwZDUxYjgxNDk5NTRlM2FhYTlmZTBhNWJlNGFiMWY1ZDUxMWY0ZjAxMjkyMzA4MjNlYTViOGEyNmNiY2QwYjkwYWZkNDVhZTUyYWIzOTk4ZWM4NDQ0N2JiYWU3YzY2MDY3NGZlM2Q3OWU5YmJiYmNlZjk4MWFhZGI5NDFhODM1ZGQ5OTdmZTE5MTdjNjVhM2Y0OTRkNWM3YmU1NTZmNTZkZmRjODU2ZGI0NGQ5MDljMjg0ZWY4NjA=
> Accept: application/json
> Content-Type: application/json
> Content-Length: 230
> Host: localhost:8080
> Connection: Keep-Alive
> User-Agent: Apache-HttpClient/4.5.2 (Java/11.0.3)
> Accept-Encoding: gzip,deflate
> 
> {"name":"spring-boot-application","managementUrl":"http://localhost:9091/actuator","healthUrl":"http://localhost:9091/actuator/health","serviceUrl":"http://localhost:9080/myapp","metadata":{"startup":"2019-11-25T18:53:55.702256Z"}}]

And the actuator endpoints of the upgraded application are accessible for example,

> $ http get http://localhost:9091/actuator/health
> GET /actuator/health HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Host: localhost:9091
> User-Agent: HTTPie/0.9.8
> 
> 
> 
> HTTP/1.1 200 
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> Content-Type: application/vnd.spring-boot.actuator.v3+json
> Date: Mon, 25 Nov 2019 20:37:28 GMT
> Expires: 0
> Pragma: no-cache
> Transfer-Encoding: chunked
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 1; mode=block
> 
> {
>     "components": {
>         "db": {
>             "components": {
>                 "myDataSource": {
>                     "details": {
>                         "database": "Oracle",
>                         "result": "Hello",
>                         "validationQuery": "SELECT 'Hello' from DUAL"
>                     },
>                     "status": "UP"
>                 },
>         "diskSpace": {
>             "details": {
>                 "free": 88646856704,
>                 "threshold": 10485760,
>                 "total": 196447162368
>             },
>             "status": "UP"
>         },
>         "ping": {
>             "status": "UP"
>         }
>     },
>     "status": "UP"
> }

However accessing the stater-server UI doesn't show any applications:

![image](https://user-images.githubusercontent.com/22501936/69576270-3aa72900-0fcc-11ea-9e50-afada4635856.png)

> $ http http://localhost:8080/admin/applications
> GET /admin/applications HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Host: localhost:8080
> User-Agent: HTTPie/0.9.8
> 
> 
> 
> HTTP/1.1 200 
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> Content-Type: application/json;charset=UTF-8
> Date: Mon, 25 Nov 2019 20:39:50 GMT
> Expires: 0
> Pragma: no-cache
> Transfer-Encoding: chunked
> X-Content-Type-Options: nosniff
> X-Content-Type-Options: nosniff
> X-Frame-Options: DENY
> X-XSS-Protection: 1; mode=block
> 
> []

Is this a known issue? Does the starter-server version 2.1.5.RELEASE support applications running on spring boot  2.2.1.RELEASE?

Thanks!

**Comment by joshiste** [comment]
This should work. 
Please look in the sba client log for `Application registered itself as ...`. If the message isn't present an error should be logged instead.

**Comment by joshiste** [comment]
Did you have a look at your logs?

**Comment by joshiste** [comment]
Closed due to missing feedback.
