### ISSUE TITLE
Need to be able use spring boot admin with non-java services

### ISSUE THREAD

**Issue by nikitsenka** [codecentric/spring-boot-admin#1312]
Kubernetes service discovery works great with SBA, however i have some services which are not java based and don't have actuator endpoint. 
How can i customize health checks for non java services? Or how can i disable some non-important services from discovering

**Comment by joshiste** [comment]
There are some options to ignore services. (e.g. `spring.boot.admin.discovery.ignored-services`, `spring.boot.admin.discovery.ignored-instances-metadata`)

https://codecentric.github.io/spring-boot-admin/current/#_converting_serviceinstances
