### ISSUE TITLE
The admin UI showing blank on ie8 and chrome

### ISSUE THREAD

**Issue by 327117143** [codecentric/spring-boot-admin#1313]
** Question **
The admin UI showon blank on ie8 and chrome, chrome's version is 48.X ，it's normal on 65.X chrome。But the browser version of the production cannot be upgraded

** Bug report **
spring-boot.version is 2.1.4.RELEASE ,same with the admin version
the browser console show errors:
Uncaught SyntaxError: Unexpected token [      chunk-vendors.ec700424.js:29 

is there a solution that adapts to the  lower versions browser, thank you

**Comment by joshiste** [comment]
sorry there is not support for ie 11 (and older). Chrome 48 is nearly 3 years old.
I don't have the time to support this wide version range.

**Comment by joshiste** [comment]
If you have the time to do that I'm happy to accept the PRs.
