### ISSUE TITLE
data cannot be loaded when spring boot admin is started the earliest,

### ISSUE THREAD

**Issue by pigxcloud** [codecentric/spring-boot-admin#1315]
spring boot admin version: 2.2.0-SNAPSHOT

spring  cloud version:  hoxton.rc2

data cannot be loaded when `spring boot admin` is started the earliest,

![](http://pigx.vip/20191128141551_UXDfWG_Screenshot.jpeg)

finally start `spring boot admin`, it will be normal

![](http://pigx.vip/20191128141700_DawQHO_Screenshot.jpeg)

**Comment by joshiste** [comment]
Are you using the Spring Boot Admin Client or some Spring Cloud Discovery implementation?

**Comment by pigxcloud** [comment]
Of course, Of course, the last boot loads correctly

**Comment by joshiste** [comment]
> Of course, Of course, the last boot loads correctly

I don't get it. Are you using some discovery or not?

**Comment by pigxcloud** [comment]
eureka  

`SBA` the last boot,  can pull all app from eureka

 behind `SBA`, cannot pull  and `SBA` do not show

**Comment by joshiste** [comment]
I guess your eureka config is not properly setup. I can't help you whit that.

**Comment by pigxcloud** [comment]
Don't you look at the picture?  Why closed

**Comment by joshiste** [comment]
@pigxcloud did you try to set the `eureka.client.registryFetchIntervalSeconds` to a smaller value?

**Comment by pigxcloud** [comment]
You're right. I should  degger eureka

**Comment by pigxcloud** [comment]
> @pigxcloud did you try to set the `eureka.client.registryFetchIntervalSeconds` to a smaller value?

You're right. I should degger eureka
