### ISSUE TITLE
endpoint-detector-* thread  become more and mroe 

### ISSUE THREAD

**Issue by JSON-ZHOUHAI** [codecentric/spring-boot-admin#1317]
We are use  spring boot admin 2.0.6. we have  600+ instace.  I foud that  endpoint-detector-*  thread  sustained growth,The SBA will   periodic stop。

**Comment by joshiste** [comment]
please upgrade to either 2.1.6 or 2.2.0 of Spring Boot Admin and verify if the issue still remains.

**Comment by JSON-ZHOUHAI** [comment]
> please upgrade to either 2.1.6 or 2.2.0 of Spring Boot Admin and verify if the issue still remains.

Thanks, when i upgrade to  2.16 ,this   problem was solved.
