### ISSUE TITLE
Upgrading to spring-boot-admin-starter-client:1.3.0 fails with errors

### ISSUE THREAD

**Issue by aayushgupta** [codecentric/spring-boot-admin#132]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'de.codecentric.boot.admin.config.SpringBootAdminClientAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private de.codecentric.boot.admin.config.AdminClientProperties de.codecentric.boot.admin.config.SpringBootAdminClientAutoConfiguration.client; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/event/ApplicationReadyEvent
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)

**Comment by joshiste** [comment]
Which boot version are you using?

**Comment by aayushgupta** [comment]
Thanks a lot!.. Code deployment is successful. But now the admin UI does not show anything for Memory, GC, Metrics, Thread dump after upgrading to client1.3.0. Is there any other specific change. I checked that my code is pulling all 1.3.0 version of jars for actuator, client and admin.
One more thing the Logging tab is showing data as expected, but there is no way to download the log files (as mentioned in the readme file)

![image](https://cloud.githubusercontent.com/assets/5401058/11747109/03e725fe-9fe7-11e5-8903-1d356c58e39a.png)

**Comment by joshiste** [comment]
Did you check the /metrics endpoint of the client app? Does it look right?

**Comment by aayushgupta** [comment]
The output for /metrics endpoint with newer version of client 1.3.0;
{
    "value": {
        "mem": 217628,
        "mem.free": 69775,
        "processors": 1,
        "instance.uptime": 54426048,
        "uptime": 54463690,
        "systemload.average": 0,
        "heap.committed": 217628,
        "heap.init": 32768,
        "heap.used": 147852,
        "heap": 496960,
        "threads.peak": 345,
        "threads.daemon": 342,
        "threads.totalStarted": 3694,
        "threads": 345,
        "classes": 17823,
        "classes.loaded": 17965,
        "classes.unloaded": 142,
        "gc.copy.count": 347,
        "gc.copy.time": 2815,
        "gc.marksweepcompact.count": 7,
        "gc.marksweepcompact.time": 792,
        "counter.status.200.v1.validate.root": 4
    },
    "serializationView": null,
    "filters": null,
    "jsonpFunction": null,
    "_links": {
        "self": {
            "href": "http://localhost.com:8080/app/metrics"
        }
    }
}

but if we downgrade the application to lower version of client, it gives the output as ;
{
    "mem": 232116,
    "mem.free": 62300,
    "processors": 1,
    "instance.uptime": 1359539318,
    "uptime": 1359568083,
    "systemload.average": 0.03,
    "heap.committed": 232116,
    "heap.init": 32768,
    "heap.used": 169815,
    "heap": 496960,
    "threads.peak": 807,
    "threads.daemon": 804,
    "threads": 807,
    "classes": 15234,
    "classes.loaded": 25538,
    "classes.unloaded": 10304,
    "gc.copy.count": 13462,
    "gc.copy.time": 233478,
    "gc.marksweepcompact.count": 459,
    "gc.marksweepcompact.time": 115100,
    "counter.status.200.info": 3340,
    "gc.MarkSweepCompact.count": 459,
}

The JSON response structure is different for both the versions. I am using admin server 1.3.0, so I assume, it will be taking care of JSON structure change.

**Comment by joshiste** [comment]
K. I see you got hateoas for the endoints activated. Either you disable this on your client by setting `endpoints.actuator.enabled=false` or you must upgrade you admin server to 1.3.0 also

**Comment by aayushgupta** [comment]
Thanks!! I am gonna try by removing the spring-hateaos, but like already mentioned, I have already upgraded my admin server to 1.3.0..

**Comment by joshiste** [comment]
...ok then I think it is a bug. I will dig into this..

**Comment by joshiste** [comment]
When I add `spring-boot-starter-hateaos` to my boot 1.3.0 sample the /metrics renders the way shown below and everything renders fine.
Can you figure out which spring-hateoas version is pulled in to your app? Do you have also included spring-data-rest or something else?

```
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/api/applications/b1fd46f8/metrics/metrics"
    }
  },
  "mem" : 523776,
  "mem.free" : 289612,
  "processors" : 4,
  "instance.uptime" : 48345,
  "uptime" : 57041,
  "systemload.average" : 0.44,
  "heap.committed" : 523776,
  "heap.init" : 126976,
  "heap.used" : 234163,
  "heap" : 1797120,
  "threads.peak" : 29,
  "threads.daemon" : 25,
  "threads.totalStarted" : 35,
  "threads" : 29,
  "classes" : 10528,
  "classes.loaded" : 10528,
  "classes.unloaded" : 0,
  "gc.ps_scavenge.count" : 8,
  "gc.ps_scavenge.time" : 161,
  "gc.ps_marksweep.count" : 2,
  "gc.ps_marksweep.time" : 265,
  "httpsessions.max" : -1,
  "httpsessions.active" : 0,
  "gauge.servo.zuul.filter-simplehostroutingfilter" : 0.0,
  "gauge.response.health" : 17.0,
  "gauge.servo.zuul.filter-predecorationfilter" : 0.0,
  "gauge.response.metrics" : 4.0,
  "gauge.response.api.applications.b1fd46f8.info.star-star" : 12.0,
  "gauge.servo.zuul.filter-servlet30wrapperfilter" : 0.0,
  "gauge.response.api.applications" : 11.0,
  "gauge.response.star-star" : 22.0,
  "gauge.response.info" : 7.0,
  "gauge.response.api.applications.b1fd46f8.configprops.star-star" : 74.0,
  "gauge.response.star-star.favicon.ico" : 8.0,
  "gauge.response.api.applications.b1fd46f8.metrics.star-star" : 10.0,
  "gauge.servo.zuul.filter-senderrorfilter" : 0.0,
  "gauge.servo.zuul.filter-debugfilter" : 0.0,
  "gauge.response.api.applications.id" : 11.0,
  "gauge.response.configprops" : 68.0,
  "gauge.response.api.applications.b1fd46f8.health.star-star" : 23.0,
  "gauge.servo.zuul.filter-sendresponsefilter" : 0.0,
  "gauge.servo.zuul.filter-formbodywrapperfilter" : 0.0,
  "counter.status.200.configprops" : 3,
  "counter.status.200.api.applications" : 1,
  "counter.status.200.health" : 5,
  "counter.status.200.api.applications.b1fd46f8.info.star-star" : 4,
  "counter.status.200.api.applications.b1fd46f8.health.star-star" : 2,
  "counter.status.201.api.applications" : 5,
  "counter.status.200.info" : 4,
  "counter.status.200.star-star.favicon.ico" : 1,
  "counter.status.200.metrics" : 4,
  "counter.status.200.star-star" : 14,
  "counter.status.200.api.applications.b1fd46f8.configprops.star-star" : 3,
  "counter.status.200.api.applications.b1fd46f8.metrics.star-star" : 4,
  "counter.status.200.api.applications.id" : 1
}
```

**Comment by psathu** [comment]
Johannes, Thank you for your time and help looks like issue was with hateoas.  I was using spring-hateoas-0.19.0.RELEASE.

After excluding 'org.springframework.hateoas' everything working as expected.

**Comment by aayushgupta** [comment]
Thanks a lot!! As mentioned by Praveen, it is resolved now. We are using swagger2 (2.3.0) that internally pulls hateoas-0.19.0.RELEASE.

**Comment by aayushgupta** [comment]
Hey Johannes, I had explicitly excluded the hateoas-0.19.0.RELEASE jar file, and that led the boot 1.3.0 to generate the output as expected.
 But swagger fails to generate the API documentation, as it looks for hateoas-0.19.0.RELEASE jar.

I think its not the swagger behavior that affects the /metrics output, because I also created a sample application adding spring-boot-starter-hateaos to boot 1.3.0, it still generates the /metrics output in format as follows.

{
    "value": {
        "mem": 217628,
        ..
    },
    "serializationView": null,
    "filters": null,
    "jsonpFunction": null,
    "_links": {
        "self": {
            "href": "http://localhost.com:8080/app/metrics"
        }
    }
}
spring-boot-starter-hateaos automatically pulls in hateoas-0.19.0.RELEASE jar dependency.
Can you make sure your sample app (adding spring-boot-starter-hateaos to boot 1.3.0) has boot 1.3.0 dependencies there in classpath. As it happened to me as well, when I scanned libraries in my eclipse project, it was referencing to boot 1.2.6 jar files.

**Comment by joshiste** [comment]
@aayushgupta If I just use the spring-boot-starter-hateoas, the endpoint renders the way I shown.
Can you give me your sample project? May be there is also some strange jackson configuration going on...

**Comment by aayushgupta** [comment]
@joshiste Hey you can pull the code from GIT
https://github.com/aayushgupta/test_boot_hateoas

**Comment by joshiste** [comment]
@aayushgupta
It's your `JsonpAdvice` in `Application.java` causing the /metrics-endpoint render that way. 
You have to  manage that it doesn't affect the acutator-endpoints. For example by setting `basePackages` for the `@ControllerAdvice`.

**Comment by aayushgupta** [comment]
@joshiste Thanks a lot!!! It worked.
