### ISSUE TITLE
java.lang.IllegalStateException: No suitable default ClientHttpConnector found error on start up

### ISSUE THREAD

**Issue by ameyg7** [codecentric/spring-boot-admin#1322]
Getting below error during start up of the server:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.codecentric.boot.admin.server.web.servlet.InstancesProxyController]: Factory method 'instancesProxyController' threw exception; nested exception is java.lang.IllegalStateException: No suitable default ClientHttpConnector found
Caused by: java.lang.IllegalStateException: No suitable default ClientHttpConnector found

Config:

-- client ---

de.codecentric
spring-boot-admin-starter-client
2.2.0

properties -> client
spring.boot.admin.client.url=http://localhost:8093
management.endpoints.web.exposure.include=*
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin

-------------------server--------------------------------------------

de.codecentric spring-boot-admin-starter-server 2.2.0 de.codecentric spring-boot-admin-server-ui 2.2.0
properties -> server

spring.application.name=admin-server
#eureka.client.service-url.default-zone=http://localhost:8761/admin

spring.security.user.name=admin
spring.security.user.password=admin
server.port=8093

springBoot.version=2.2.1.RELEASE

Using Undertow Spring WebFlux.
Both Spring Boot & SBA are on the latest versions.

**Comment by joshiste** [comment]
Could you please provide a sample project to reproduce the issue?

**Comment by ameyg7** [comment]
PFA zip

> Could you please provide a sample project to reproduce the issue?

[storymapping.zip](https://github.com/codecentric/spring-boot-admin/files/3932058/storymapping.zip)

**Comment by ameyg7** [comment]
PFA

[storymapping.zip](https://github.com/codecentric/spring-boot-admin/files/3932122/storymapping.zip)

**Comment by joshiste** [comment]
You must not exclude the `spring-boot-starter-reactor-netty`
