### ISSUE TITLE
Allow removing/replacing ui views with custom extensions

### ISSUE THREAD

**Issue by michformanek** [codecentric/spring-boot-admin#1324]
We have custom actuator endpoints providing more information about caches, schedules,... Using UI extensions, we are able to add new views for these. 

However with custom extensions, we end up having them in the menu twice (original and custom one). Is there a way to remove or replace original one (during view installation), so that only one shows up?

**Comment by joshiste** [comment]
[Currently the view are only appended](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/viewRegistry.js#L64). It should be easy to replace views with the same name as the added one.

Would you like to submit a PR on this?
