### ISSUE TITLE
Explicitly call the InstanceDiscoveryListener's discovery function and re-register all the new instances

### ISSUE THREAD

**Issue by Ask149** [codecentric/spring-boot-admin#1328]
I am trying to use simple discovery client, as my environment does not support the Eureka cloud discovery. 

To make the discovery dynamic, i am getting the IP address of the client applications dynamically through API's in the Java Code and then setting the uri of the applications in the System Properties itself. But, after setting up, the server applications, does not pick up the new values/ updated values of the URI, as it runs the discovery service only at the start of the application. 

Is there any API, which can be overriden or called? So, that i can explicitly re-run the discovery function, which will update the values of the URI Properties and re-register all the services?

**Comment by joshiste** [comment]
You have several options:
1) Register the instances directly using the `InstanceRegistry`
2) The `InstanceDiscoveryListener` listens for the `ApplicationReadyEvent` you could make sure that doing your custom discovery happens before the event.
3) The `InstanceDiscoveryListener` listens for `HeartbeatEvent`/`ParentHeartbeatEvent`. You could publish a `HeartbeatEvent` after you did your work..

But Please keep in my that the `SimpleDiscoveryListener` may not take up the new SystemProperties once it is created during context initialization (which is the default in spring). So you need to make sure that the bean is somehow refreshed or the properties are set before context initialization.
