### ISSUE TITLE
In version 2.2, the admin alarm system often problem

### ISSUE THREAD

**Issue by yachi666** [codecentric/spring-boot-admin#1332]
In version 2.2, the admin alarm system often Misreports the status of the admin system itself, but it is always on. But in version 2.0.2, there is no problem ,The code is unchanged  
Thank you for your help. Please contact me. My email is lznpojo@163.com 
I'm sorry my English is a little poor  I'm from China think yo

**Comment by joshiste** [comment]
What kind of status is reported? Timeout? Error Status?

**Comment by yachi666** [comment]
offline and After a while  up

**Comment by joshiste** [comment]
Can you provide a project to reproduce the error?

**Comment by yachi666** [comment]
I seem to know the problem
The version number of my Eureka server is 1.5, but the clients use 2.2
The problem no longer appears after the same revision number
I want to know if anyone else has the same problem

**Comment by joshiste** [comment]
closing as non SBA issue.
