### ISSUE TITLE
Unable to find spring-boot-admin in applications page

### ISSUE THREAD

**Issue by zhanglei-1987** [codecentric/spring-boot-admin#1337]
in applications page, unable to find spring-boot-admin

**Comment by joshiste** [comment]
Sorry, but I don't understand what you problem is. Please give more details

**Comment by zhanglei-1987** [comment]
![image](https://user-images.githubusercontent.com/31624476/71656834-f3087f80-2d77-11ea-8bdf-c480645aaf8a.png)

I started spring-boot-admin  server  on eureka, but can't  find  spring-boot-admin in applications page

**Comment by joshiste** [comment]
Please make sure that the admin server registers itself (either using some kind of discovery or using the sba-client)

**Comment by zhanglei-1987** [comment]
I'm sure in eureka can found it

**Comment by joshiste** [comment]
Did you accidentally any value in `spring.boot.admin.discovery.ignored-services`? 

Imho this is most probably an error regarding your eureka configuration (and not SBA)

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by joshiste** [comment]
https://github.com/sildvauresberg/sba-eureka-sample
