### ISSUE TITLE
Download Logfile/Heapdump doesn't work in 2.x

### ISSUE THREAD

**Issue by Wang-Yumin** [codecentric/spring-boot-admin#1338]
I can download the logfile from Inslights-Logging-Logfile when the admin version was '2.1.5.RELEASE', when I update the admin version to '2.2.1.RELEASE', I can't download it, when I click the download button, It's just jump a new page with a html header but don't start a download process. What's worse, I can't download the dumpfile too. Why happened this, It's my security config error? Maybe not, because I try to set the anyRequest() is permitAll(), it seems to doesn't work too. Please. Thank you!

**Comment by joshiste** [comment]
Which Browser are you using?

**Comment by DhavalShewale** [comment]
I can confirm that this does not working in `SBA 2.2.x`.
For `SBA 2.1.6`, log file is displayed similar to that of actuator logfile output. It is never downloaded.

**Comment by DhavalShewale** [comment]
@joshiste Can you pls confirm whether the log file will be downloaded or just displayed in a new tab? In my case I can view it in a new tab. It is now downloaded.

**Comment by joshiste** [comment]
@DhavalShewale
I guess there are some other users that prefer the tab over the download - so I decided to leave that up to the browser to decide wether it is shown as new tab or downloaded. If you can display it as new tab you should also be able to right-click it and to choose "save as"

**Comment by DhavalShewale** [comment]
@joshiste ok so its intended to work that way. So its basically the same view without the SBA menu and header.

**Comment by Wang-Yumin** [comment]
I'm so sorry for not responding to this question for so long but this question still exist. I'm using Chrome browser, When I click the download button, it will open a new tab without any content, it seem like a empty white page.

**Comment by DhavalShewale** [comment]
Download logfile and heapdump works fine for me with `SBA 2.2.2`. However, download thread dump still fails.

**Comment by Wang-Yumin** [comment]
Like this. 
[download heapdump failed](https://files.minbb.cn/data/20200209115416.png)
[download logfile failed](https://files.minbb.cn/data/20200209115427.png)

**Comment by Wang-Yumin** [comment]
Oh! Great! When I update the Admin version to 2.2.2, this problem has been resolved. When I click the logfile download button, it will open a new tab with log content, I can preview or download it with  'save as', when I click the heapdump button, it will call the 'save as' explorer window then start the download progress. Thank you very much. @joshiste

**Comment by asamonov** [comment]
Does not work in 2.2.2 When I click "Download" a new empty tab opens.

**Comment by gbtec-ext-fernandoquiroga** [comment]
Checked with 2.2.2 as @asamonov says I click "Download" a new tab opens but nothing happens

**Comment by ankitbanka17** [comment]
@joshiste i am also facing the heap dump issue. Opens in new tab with empty screen(only  header part is displayed)
UI request:(not working)

```
url : admin/instances/{instanceId}/actuator/heapdump 
 header -> Accept : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8


```
```

Postman request: Working fine

```
url : admin/instances/{instanceId}/actuator/heapdump 
 header -> Accept : application/octet-stream


```

**Comment by joshiste** [comment]
which browser are you using?

**Comment by ankitbanka17** [comment]
@joshiste  I have resolved this issue by removing admin.context-path. There is some issue with using admin.context-path. 
spring:
 boot:
  admin:
   context-path: /admin

**Comment by asibross** [comment]
Hey @joshiste, I am seeing that same issue on 2.2.2.
I think it is related to this line:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/services/instance.js#L184

Where it uses the imported axios module instead of the pre-configured axios object.
Changing it to `this.axios.get` instead of `axios.get` would probably do the trick.

**Comment by AnthonyNTK** [comment]
@joshiste using spring-boot-admin 2.3.0 with `spring.boot.admin.context-path=/admin`
browser tested:
1. Firefox 83.0 (64-bit)
2. Chrome (87.0.4280.66)

Both opened a new tab with no content inside.
