### ISSUE TITLE
Spring boot 2.2 issue with lazy-initialization

### ISSUE THREAD

**Issue by stephanecot** [codecentric/spring-boot-admin#1340]
If I am using Spring Boot 2.2 with **lazy-initialization=true**, I am getting an error with:
**couldn't determine local port. Please set spring.boot.admin.client.instance.service-base-url**

I think it's because the method
`	@EventListener
	public void onWebServerInitialized(WebServerInitializedEvent event) {`

of the class **de.codecentric.boot.admin.client.registration.DefaultApplicationFactory** is not excecuted.

I don't know if it can be fixed or not...
Maybe it's must be indicated in the documentation.

Notes:
I am not using Discovery, juste simple spring boot application (docker in production)
I don't want to set **spring.boot.admin.client.instance.service-base-url** (all dynamic).

**Comment by joshiste** [comment]
I guess the DefaultApplicationFactory is instantiated after the event, so it's currently not working with the lazy initialization
