### ISSUE TITLE
Failure in Thread Dump and Heap Dump Download (SBA 2.2.x)

### ISSUE THREAD

**Issue by DhavalShewale** [codecentric/spring-boot-admin#1341]
1. Download Thread Dump Request fails with status code 406
<code>Downloading thread dump failed. Request failed with status code 406</code>

2. Download Heap Dump opens a new tab with below url and then performs no other action
<code>http://<server_path>/instances/<instance_id>/actuator/heapdump</code>

**Comment by joshiste** [comment]
Which version of SBA and which Browser version are you using?

**Comment by DhavalShewale** [comment]
I have tried on both SBA 2.2.0 and 2.2.1
Heap dump works fine with SBA 2.1.6
My bad to not include these details in original bug report.

I have tried it on IE, Chrome and Frontmotion Firefox. Imho browser version should not be an issue as it works for a lower SBA version. Anyways, will share the details later if required.

**Comment by DhavalShewale** [comment]
I am using Chrome 79

**Comment by kamaydeo** [comment]
I am facing the same issue (406). I'm using SBA 2.2.1 on Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by joshiste** [comment]
duplicate of #1338 which I've fixed some minutes ago.

**Comment by DhavalShewale** [comment]
When can we expect this to be released?

**Comment by joshiste** [comment]
@DhavalShewale I wanted to upgrade to Spring Boot 2.2.3 before, but having trouble due to a bug in spring 5.2.3

**Comment by DhavalShewale** [comment]
Download of Thread Dump still does not work. I have upgraded to `SBA 2.2.2`.

**Comment by joshiste** [comment]
@DhavalShewale 
Is there any error in the network or console tab?

**Comment by DhavalShewale** [comment]
On clicking of download button it tries to hit `<server>:<port>/<context-root>/actuator/threaddump` which return `406`
