### ISSUE TITLE
custom view js/css are not loaded because of wrong mime-type

### ISSUE THREAD

**Issue by ahoehma** [codecentric/spring-boot-admin#1342]
spring-boot: 2.2.2.RELEASE
spring-boot-admin: 2.2.0-SNAPSHOT

I try to add my own custom-view ("cc")
I followed https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui

Loading seems to work
2020-01-06 14:37:02.072  INFO 6588 --- [           main] b.a.s.u.c.AdminServerUiAutoConfiguration : Loaded Spring Boot Admin UI Extension: UiExtension(resourcePath=cc/js/cc.ca1ba42b.js, resourceLocation=file:target/vue-dist/cc/js/cc.ca1ba42b.js)
2020-01-06 14:37:02.073  INFO 6588 --- [           main] b.a.s.u.c.AdminServerUiAutoConfiguration : Loaded Spring Boot Admin UI Extension: UiExtension(resourcePath=cc/css/cc.4992ea56.css, resourceLocation=file:target/vue-dist/cc/css/cc.4992ea56.css)

But then the real ui is not showing the new views

I see only 2 errors in chrome

Refused to apply style from 'http://localhost:8080/cc/css/cc.4992ea56.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
details:1 Refused to execute script from 'http://localhost:8080/cc/js/cc.ca1ba42b.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
A bad HTTP response code (404) was received when fetching the script.

![image](https://user-images.githubusercontent.com/548214/71821711-20646e80-3093-11ea-936b-59ea91e1961c.png)

**Comment by ahoehma** [comment]
I found an ugly workaround :)
I defined the target-directory for the vue-compiling like that:
const targetDir = 'target/vue-dist/assets/cc/';
And now sba picks up the extension "cc" correctly.

**Comment by joshiste** [comment]
can you provide a project to reproduce this issue?

**Comment by marbon87** [comment]
Same problem here.

@ahoehma can you be more precise about your workaround?

**Comment by joshiste** [comment]
closed to missing feedback

**Comment by marbon87** [comment]
@joshiste i created a sample project based on spring boot and your spring-boot-admin-sample-custom-ui.
It does not show exactly the same error, but the custom ui is not shown and i get the following log in the browser console:
```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8080/custom/css/custom.41bd3967.css".
```

If you switch back to spring boot version to 2.1.12.RELEASE and spring boot admin version to 2.1.5 the custom entry is show on the applications view. 


[custom-ui.tar.gz](https://github.com/codecentric/spring-boot-admin/files/4140190/custom-ui.tar.gz)

**Comment by marbon87** [comment]
Hi @joshiste , do you need any more feedback? Because the issue is still tagged with 'watiing-for-feedback`

**Comment by joshiste** [comment]
currently not, but I didn't found the time to look at it.

**Comment by calaveraInfo** [comment]
I have the same problem. One additional important information that's not in the original description is that I use standard Tomcat war deployment, not embedded standalone process. Maybe it's important. I'm trying to find where in the code of admin are the mime types set up but I can't find anything (except for notifications), which is puzzling. How can standard admin javascript have correct mime type and custom javascripts not when they have the same file extension??

**Comment by calaveraInfo** [comment]
Oh, now I noticed that those JS and CSS are not served on their URLs at all. Only a blank page with standard menu header sits on their URLs, so the mime type is actually correct with respect to such content. The problem is more profound than just mime types.

**Comment by BeneStem** [comment]
Have the same issue. Not sure if its related to Accept header.
If I curl with specific Accept header it works...

**Comment by mbwhelan** [comment]
The browser console errors link to this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
I believe this has been caused by Spring Security enabling default security headers [1] with the version pulled in by Spring Boot 2.2.  
[1] https://docs.spring.io/spring-security/site/docs/5.1.0.RELEASE/reference/htmlsingle/#default-security-headers

Need to get the request to send the correct headers...

**Comment by bratwurzt** [comment]
> 
> 
> I found an ugly workaround :)
> I defined the target-directory for the vue-compiling like that:
> const targetDir = 'target/vue-dist/assets/cc/';
> And now sba picks up the extension "cc" correctly.

I expanded your workaround into a #1410 :)

**Comment by joshiste** [comment]
there shoud be soon a 2.2.3-SNAPSHOT available with this fix and I'll also try to push out a new release in the next days.

**Comment by wangChengChao** [comment]
> I found an ugly workaround :)
> I defined the target-directory for the vue-compiling like that:
> const targetDir = 'target/vue-dist/assets/cc/';
> And now sba picks up the extension "cc" correctly.
hi,can you tell me how to do it?
