### ISSUE TITLE
Issues with (lots of) caches

### ISSUE THREAD

**Issue by retevastum** [codecentric/spring-boot-admin#1345]
Hi all,

though one of my issues might not be a bug i am hoping to find a solution here.
I am on SBA 2.2.1, non-reactive server.
I have ~40 caches in my spring boot app.
I have two issues:

1) When on page insights>details where all the nice graphs are drawn there are also ~40 graphs for my caches. Because of that the app gets literally overwhelmed with requests for current hit/miss numbers. I see a huge cpu usage when on that details page. Otherwise not. Can i increase the interval those request are done ?
2) All requests for cache size (.../instances/.../actuator/metrics/cache.size?tag=name:...) get a 404 from SBA server as i can see in browser console.

Thanx alot, Cheers, JJ

**Comment by joshiste** [comment]
> 1. When on page insights>details where all the nice graphs are drawn there are also ~40 graphs for my caches. Because of that the app gets literally overwhelmed with requests for current hit/miss numbers. I see a huge cpu usage when on that details page. Otherwise not.

Are you speaking of the cpu the browser is running on or the server?
I think it would be useful to not display the caches by default if they exceed a certain limit (e.g. 5)

> Can i increase the interval those request are done ?

[The caches are refreshed every 2.5s](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-cache.vue#L146
). Currently there is no option to pause or customize this. But if you want to work on a PR for this, it would be great.


> 2. All requests for cache size (.../instances/.../actuator/metrics/cache.size?tag=name:...) get a 404 from SBA server as i can see in browser console.

IIRC this is because not every cache implementation provides this metric.

**Comment by retevastum** [comment]
> 
> 
> > 1. When on page insights>details where all the nice graphs are drawn there are also ~40 graphs for my caches. Because of that the app gets literally overwhelmed with requests for current hit/miss numbers. I see a huge cpu usage when on that details page. Otherwise not.
> 
> Are you speaking of the cpu the browser is running on or the server?
> I think it would be useful to not display the caches by default if they exceed a certain limit (e.g. 5)
The app which is monitored. Struggles with all those requests to actuator for hits/misses.
> 
> > Can i increase the interval those request are done ?
> 
> [The caches are refreshed every 2.5s](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-cache.vue#L146). Currently there is no option to pause or customize this. But if you want to work on a PR for this, it would be great.
Will do so, if i find time. 
> 
> > 1. All requests for cache size (.../instances/.../actuator/metrics/cache.size?tag=name:...) get a 404 from SBA server as i can see in browser console.
> 
> IIRC this is because not every cache implementation provides this metric.
Makes sense

Thanx, JJ
