### ISSUE TITLE
Improve Deserialization of InstanceEvents

### ISSUE THREAD

**Issue by ChunMengLu** [codecentric/spring-boot-admin#1348]
**Bug report**
I customized eventstore and found that it is not good enough for deserialization.
I use jackson and need to customize a Deserializer like RegistrationDeserializer.

**Comment by joshiste** [comment]
Could you please elaborate a bit on your customizing and why you need to deserialize the InstanceEvents using jackson?
What changes to the InstanceEvents would you apply to improve it?

**Comment by ChunMengLu** [comment]
Because the memory currently used for InstanceEvents storage, spring boot admin will be lost after restart, so I use rocksdb to store. Use jackson for serialization.

**Comment by ChunMengLu** [comment]
Currently I use custom deserialization:

```java
/**
 * InstanceEvent Deserializer
 *
 * @author L.cm
 */
public class InstanceEventDeserializer extends StdDeserializer<InstanceEvent> {

	public InstanceEventDeserializer() {
		super(InstanceEvent.class);
	}

	@Override
	public InstanceEvent deserialize(JsonParser jsonParser, DeserializationContext context) throws IOException {
		JsonNode node = jsonParser.readValueAsTree();
		String type = node.at("/type").asText();
		InstanceId instance = InstanceId.of(node.at("/instance").asText());
		long version = node.at("/version").asLong();
		Instant timestamp = Instant.parse(node.at("/timestamp").asText());

		if ("DEREGISTERED".equals(type)) {
			return new InstanceDeregisteredEvent(instance, version, timestamp);
		} else if ("ENDPOINTS_DETECTED".equals(type)) {
			List<Endpoint> endpoints = JsonUtil.convertValue(node.at("/endpoints"), JsonUtil.getListType(Endpoint.class));
			return new InstanceEndpointsDetectedEvent(instance, version, timestamp, Endpoints.of(endpoints));
		} else if ("INFO_CHANGED".equals(type)) {
			Map<String, Object> value = JsonUtil.convertValue(node.at("/info"), Map.class);
			return new InstanceInfoChangedEvent(instance, version, timestamp, Info.from(value));
		} else if ("REGISTERED".equals(type)) {
			Registration registration = JsonUtil.convertValue(node.at("/registration"), Registration.class);
			return new InstanceRegisteredEvent(instance, version, timestamp, registration);
		} else if ("REGISTRATION_UPDATED".equals(type)) {
			Registration registration = JsonUtil.convertValue(node.at("/registration"), Registration.class);
			return new InstanceRegistrationUpdatedEvent(instance, version, timestamp, registration);
		} else if ("STATUS_CHANGED".equals(type)) {
			Map<String, Object> value = JsonUtil.convertValue(node.at("/statusInfo"), Map.class);
			return new InstanceStatusChangedEvent(instance, version, timestamp, StatusInfo.from(value));
		}
		return null;
	}
}
```

**Comment by joshiste** [comment]
@ChunMengLu Currently I think the best is to provide a jackson module with your deserializer by SBA as I'm currently refusing to taint the code with the jackson polymorphic deserialization stuff. 
Do you want to work on a PR for this?

**Comment by srempfer** [comment]
I just referenced working state to the issue. 

@joshiste: Is that what you had in mind? Do you prefer...
* ...the Mixin variant like I did it for InstanceEndpointsDetectedEventMixin
* ...the @JsonXYZ annotations direct in the domain classes like I did for InstanceRegistrationUpdatedEvent

**Comment by joshiste** [comment]
My would by to pollute the core domain as little as possible with Jackson annotations. So either a custom deserializer or a mixin would be fine.
