### ISSUE TITLE
Admin Starter Client ignoring Service/Management-Url from SystemProperties with Boot 1.3

### ISSUE THREAD

**Issue by jenslofgren** [codecentric/spring-boot-admin#135]
When running Spring Boot with:
* Spring Boot 1.3.0
* Spring Boot Admin 1.3.0

And setting System Properties:
* SPRING_BOOT_ADMIN_URL = https://172.23.0.178:8443/
* SPRING_BOOT_ADMIN_CLIENT_HEALTH-URL = http://localhost:8053/health
* SPRING_BOOT_ADMIN_CLIENT_MANAGEMENT-URL = http://localhost:8053
* SPRING_BOOT_ADMIN_CLIENT_SERVICE-URL = http://localhost:8053

.. Boot Admin Starter Client **ignores** MANAGEMENT & SERVICE-URL and tries to register application with 

> Application registered itself as {managementUrl=http://172.23.0.178:8053, healthUrl=http://localhost:8053/health, serviceUrl=http://172.23.0.178:8053, name=spring-boot-application, id=0466f858, statusInfo={status=UNKNOWN, timestamp=1450112345224}}

When running the exact same setup with Boot 1.2 and Boot Admin 1.2 i get:
> Application registered itself as {managementUrl=http://localhost:8053, healthUrl=http://localhost:8053/health, serviceUrl=http://localhost:8053, name=spring-boot-application, id=0466f858, statusInfo={status=OFFLINE, timestamp=1450113000415}}

When running 1.3/1.3:
![image](https://cloud.githubusercontent.com/assets/11096579/11787569/a15d2c64-a28c-11e5-8405-8165e30c2a94.png)
![image](https://cloud.githubusercontent.com/assets/11096579/11787852/3194abbc-a28e-11e5-8b46-96ea9cb09c8d.png)

This becomes troublesome when running the same setup from within a Docker container and setting environment variables with -v

**Comment by jenslofgren** [comment]
I found a solution to my problem. It seems that when using Spring Boot 1.3 everything works as expected **if** I place "dummy"-properties in my Spring Boot application.yml file.
![image](https://cloud.githubusercontent.com/assets/11096579/11789609/a5a42998-a297-11e5-9fdc-124ac487e450.png)
Only **then** does Boot Admin Client pick up the values from System Properties. This problem only seems to affect properties with dash'es (-) in them.

**Comment by joshiste** [comment]
Crazy. but I think it's a bug in boot.

**Comment by joshiste** [comment]
I've submitted https://github.com/spring-projects/spring-boot/issues/4775 and will do a workaround by setting `ignoreUnknownFields=true` for AdminClientProperties.

**Comment by jenslofgren** [comment]
Sweet! Keep up the good work!
