### ISSUE TITLE
status updater doesn't set JSESSIONID cookie and thus creates new sessions on client

### ISSUE THREAD

**Issue by lambliesdown** [codecentric/spring-boot-admin#1350]
I'm registering an app with the admin server where the actuator endpoints are protected by basic authentication. By setting the spring.boot.admin.client.instance.metadata.user.name/password the health/info calls to the client are authenticated and work properly. However, the calls from the server (e.g. StatusUpdater) don't handle the session cookies. Thus every health/info request creates a new HTTP session on the client.

**Comment by lambliesdown** [comment]
My fault - the client authentication needs to be configured to be stateless.

**Comment by joshiste** [comment]
@lambliesdown may be this is interesting for others too, could you tell us what changes you did to your configuration?
Maybe it's worth to enhance the examples in the documentation?

**Comment by lambliesdown** [comment]
Attached is a simple example how I configured the authentication on my actuator endpoints such that they can be accessed by Spring Boot Admin without session overhead
[ActuatorBasicAuthenticationConfigurer.txt](https://github.com/codecentric/spring-boot-admin/files/4142570/ActuatorBasicAuthenticationConfigurer.txt)

**Comment by joshiste** [comment]
@lambliesdown when I get it right it will disable the session management for the entire application and not just for the actuator endpoint, right?

**Comment by lambliesdown** [comment]
No, that would be devastating. This is only applies to the endpoints selected by the AntMatcher.

 

Von: Johannes Edmeier <notifications@github.com> 
Gesendet: Sonntag, 2. Februar 2020 12:23
An: codecentric/spring-boot-admin <spring-boot-admin@noreply.github.com>
Cc: lambliesdown <karsten_opitz@arcor.de>; Mention <mention@noreply.github.com>
Betreff: Re: [codecentric/spring-boot-admin] status updater doesn't set JSESSIONID cookie and thus creates new sessions on client (#1350)

 

@lambliesdown <https://github.com/lambliesdown>  when I get it right it will disable the session management for the entire application and not just for the actuator endpoint, right?
