### ISSUE TITLE
SBA and Consul Service Discovery 

### ISSUE THREAD

**Issue by GiTweeker** [codecentric/spring-boot-admin#1351]
Unable to view instances  with context path  discovered on consul . Spring boot admin UI does not use the context path when getting actuator data. Instance information are shown as down because the servlet path from service discovery is not being used. 

Please assist

**Comment by GiTweeker** [comment]
had to override the Bean DefaultServiceInstanceConverter and method  getManagementPath

   protected String getManagementPath(ServiceInstance instance) {
       // String managementPath = (String)instance.getMetadata().get("management.context-path");
        String managementPath = (String)instance.getMetadata().get("contextPath");

        return !StringUtils.isEmpty(managementPath) ? managementPath+ managementContextPath : this.managementContextPath;
    }

**Comment by GiTweeker** [comment]
alternatively 

`spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: management.context-path=${management.server.servlet.context-path}, baz`


https://cloud.spring.io/spring-cloud-consul/2.1.x/multi/multi_spring-cloud-consul-discovery.html

**Comment by joshiste** [comment]
closing this issue, as it looks to me that you could solve your problem, right?
