### ISSUE TITLE
Multiple instances and alerting within Spring Boot Admin

### ISSUE THREAD

**Issue by andyd2002** [codecentric/spring-boot-admin#1354]
Hi,

I have multiple instances of Spring boot admin running on cloudfoundry, as i have email notifications enabled this results in multiple emails being sent when a registered services’ state changes.

What I would like is to only get an alert from any one instance of spring boot admin.  I already use the Shedlock library for similar purposes within other projects.

https://github.com/lukas-krecan/ShedLock

Is there a way to easily integrate something like shedlock into spring boot admin email notifications?

Thanks

**Comment by joshiste** [comment]
If you use multiple instances you can already use hazelcast to dedupe the notifications. This was added in 2.2.0 with https://github.com/codecentric/spring-boot-admin/issues/1122

If you don't want to use hazelcast, you can implement the Notifier interface with the locking mechanisms of SchedLock, but I currently refuse to add this to SBA.
