### ISSUE TITLE
can't change environment

### ISSUE THREAD

**Issue by zzlxf** [codecentric/spring-boot-admin#1360]
When an application uses the configuration center to pull the configuration file from the server, can't the logging.file parameter be modified by modifying the environment variable

**Comment by joshiste** [comment]
That doesn't looks like a SBA problem to me. But more a problem between spring-cloud-config and spring boot. please file an issue for spring cloud.

**Comment by zzlxf** [comment]
no,i think is SBA's problem.
Because SBA does not have an environment modification box when using the configuration center client, but it does when the configuration file is in the resource folder of the project.This is caused by the condition judgment of SBA
using spring cloud config client
![image](https://user-images.githubusercontent.com/36030142/75008930-49f71f00-54b4-11ea-8f3f-789878abd1eb.png)
using local cofiguration
![image](https://user-images.githubusercontent.com/36030142/75009177-f933f600-54b4-11ea-8d8b-a25402a869af.png)
pls check it,thanks

**Comment by joshiste** [comment]
@zzlxf sba is doing a options request to the env endpoint of the underlying application  to figure out wether it supports POST requests or not and showing the environment manager depending on that.

So you need to check if your endpoint supports POST requests when using the config client. If not it is a spring cloud issue

**Comment by zzlxf** [comment]
Where is this judgment realized？

**Comment by joshiste** [comment]
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/services/instance.js#L94

**Comment by zzlxf** [comment]
thanks
