### ISSUE TITLE
Dependencies for Jolokia can be optional?

### ISSUE THREAD

**Issue by tokuhirom** [codecentric/spring-boot-admin#1363]
Currently, spring-boot-admin-client depends on the `jolokia-core`.
But I guess it can be an optional dependency.

https://github.com/codecentric/spring-boot-admin/blob/ce0698f25662623d623ba314ef1545e560353219/spring-boot-admin-client/pom.xml#L63-L66

ref. https://github.com/codecentric/spring-boot-admin/blob/9b4a92982cdafe77c97cb7d47860e0a1f7c49b04/spring-boot-admin-docs/src/main/asciidoc/client.adoc#jmx-bean-management

**Comment by joshiste** [comment]
@tokuhirom I guess we can remove it completely and change the docs for it. Do you want to do a PR on this?

**Comment by tokuhirom** [comment]
yep. i'll send you a PR soon~
