### ISSUE TITLE
SCA itself is down, others are up

### ISSUE THREAD

**Issue by aeasylife** [codecentric/spring-boot-admin#1371]
Hello!

I ran into a problem using SCA version 2.2.2.

My SC version is hoxton.sr1.

My configuration refers to the configuration of "spring boot admin sample using Eureka" project.

But the result is:
![image](https://user-images.githubusercontent.com/20423987/75948071-698f3e00-5edd-11ea-91aa-5963e9f9c575.png)
The reason I saw it: there was a request that returned 401。
![image](https://user-images.githubusercontent.com/20423987/75948161-a9eebc00-5edd-11ea-9c2d-06da456eb699.png)
![image](https://user-images.githubusercontent.com/20423987/75948180-b70bab00-5edd-11ea-82ab-1bc9af5469e2.png)
I went to check the "/actuator/health" interface of the admin project, and his return was OK。
**{"status":"UP","components":{"discoveryComposite":{"status":"UP","components":{"discoveryClient":{"status":"UP","details":{"services":["api-gateway","admin","server-process"]}},"eureka":{"description":"Remote status from Eureka server","status":"UP","details":{"applications":{"API-GATEWAY":1,"ADMIN":1,"SERVER-PROCESS":1}}}}},"diskSpace":{"status":"UP","details":{"total":371056439296,"free":356923584512,"threshold":10485760}},"hystrix":{"status":"UP"},"ping":{"status":"UP"},"reactiveDiscoveryClients":{"status":"UP","components":{"Simple Reactive Discovery Client":{"status":"UP","details":{"services":[]}},"Spring Cloud Eureka Reactive Discovery Client":{"status":"UP","details":{"services":["api-gateway","admin","server-process"]}}}},"refreshScope":{"status":"UP"}}}**

I want to know what the problem is！

**Comment by aeasylife** [comment]
This is my permission configuration
` @Configuration
    public static class SecuritySecureConfig extends WebSecurityConfigurerAdapter {
        private final String adminContextPath;

        public SecuritySecureConfig(AdminServerProperties adminServerProperties) {
            this.adminContextPath = adminServerProperties.getContextPath();
        }

        @Override
        protected void configure(HttpSecurity http) throws Exception {
            // @formatter:off
            SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
            successHandler.setTargetUrlParameter("redirectTo");
            successHandler.setDefaultTargetUrl(adminContextPath + "/");

            http.authorizeRequests()
                    .antMatchers(adminContextPath + "/assets/**").permitAll()
                    .antMatchers(adminContextPath + "/login").permitAll()
                    .anyRequest().authenticated()
                    .and()
                    .formLogin().loginPage(adminContextPath + "/login").successHandler(successHandler).and()
                    .logout().logoutUrl(adminContextPath + "/logout").and()
                    .httpBasic().and()
                    .csrf()
                    .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                    .ignoringRequestMatchers(
                            new AntPathRequestMatcher(adminContextPath + "/instances", HttpMethod.POST.toString()),
                            new AntPathRequestMatcher(adminContextPath + "/instances/*", HttpMethod.DELETE.toString()),
                            new AntPathRequestMatcher(adminContextPath + "/actuator/**")
                    );
            // @formatter:on
        }
    }`

**Comment by joshiste** [comment]
The 401 is returned by the monitored application. You need to make those endpoints accessible for the SBA server. For [example by using basic auth](https://codecentric.github.io/spring-boot-admin/current/#_securing_client_actuator_endpoints)...

**Comment by zhangran2616** [comment]
> The 401 is returned by the monitored application. You need to make those endpoints accessible for the SBA server. For [example by using basic auth](https://codecentric.github.io/spring-boot-admin/current/#_securing_client_actuator_endpoints)...

I refer to the documentation, but there is no solution, please help。SCA itself is down, others are up

![image](https://user-images.githubusercontent.com/6472032/103113640-a27be780-4696-11eb-9038-4e917ecf5dda.png)

![image](https://user-images.githubusercontent.com/6472032/103113651-b0ca0380-4696-11eb-8083-973aba0c7174.png)

![image](https://user-images.githubusercontent.com/6472032/103113661-baec0200-4696-11eb-8a65-ccca62ce9aca.png)

![image](https://user-images.githubusercontent.com/6472032/103113678-d35c1c80-4696-11eb-9956-25c193954ef9.png)
