### ISSUE TITLE
Cant override `spring.boot.admin.client.url` with a ConfigurationProperties Bean

### ISSUE THREAD

**Issue by fionera** [codecentric/spring-boot-admin#1372]
I currently try to set the `spring.boot.admin.client.url` with a Bean, but the Condition gets evalued before the Bean is created. Any idea how I could circumvent this? 

Also the Binder in the condition only requests any sub-property from the enviroment, when the `spring.boot.admin.client` isnt null. This is bad since I need to setup the application.yaml now.

**Comment by joshiste** [comment]
This is not an SBA issue. 

But I thinks the solution is fairly simple: 
You need to make sure to add the properties before the application context is refreshed. To do that you need to use a [EnvironmentPostProcessor](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/env/EnvironmentPostProcessor.html)
