### ISSUE TITLE
i18n of custom views

### ISSUE THREAD

**Issue by mariobruck** [codecentric/spring-boot-admin#1373]
Hi,
I have been adding a "custom view" to spring-boot-admin. But I can not add internationalization. When using my own VueI18n object, the language does not change on the webpage when I select a different one from the drop-down menu. When using a label which is already defined (like: 'about.label' it works). So, it would be nice to have the possibility to add my own translation messages.

**Comment by joshiste** [comment]
i've added the vuei18n instance to the install() parameter object which is passed to the custom extension this should allow you to add/remove/replace messages.

**Comment by bratwurzt** [comment]
Could one of you provide an example for this?

**Comment by joshiste** [comment]
@bratwurzt unfortunately the changes hasn't been released yet.

**Comment by bratwurzt** [comment]
> 
> 
> @bratwurzt unfortunately the changes hasn't been released yet.

I've done it like this (am not a frontend developer, this might be super clunky):
```
const context = require.context('.', true, /^\.\/*\/.*i18n\.?([^/]*)\.json$/);

SBA.use({
  install({viewRegistry, applicationStore, vue, vueI18n, axios}) {
    context.keys().forEach(function (key) {
      const localeFromFile = /^\.\/*\/.*i18n\.?([^/]*)\.json$/.exec(key);
      const messages = context(key);
      vueI18n.mergeLocaleMessage(localeFromFile[1], messages);
    });
    viewRegistry.addView({
      name: 'custom',  //<1>
      path: '/custom', //<2>
      component: custom, //<3>
      label: 'Custom', //<4>
      order: 1000, //<5>
    });
  }
});
```
