### ISSUE TITLE
I have a Spring Boot application which listens for messages from an kafka MQ input queue, does some processing of the messages

### ISSUE THREAD

**Issue by LoveMyPyj** [codecentric/spring-boot-admin#1374]
This application is a non-web application. How do I use spring-boot-admin-client?

**Comment by LoveMyPyj** [comment]
Any documentation on non-web applications?

**Comment by joshiste** [comment]
@LoveMyPyj SBA relies on the actuator endpoints being available with http so you need to include netty or a servlet container just for this purpose.
