### ISSUE TITLE
Program that implements FactoryBean gives an error when getting configuration properties

### ISSUE THREAD

**Issue by jiangzeyin** [codecentric/spring-boot-admin#1375]
![image](https://user-images.githubusercontent.com/16408873/76486986-eb421700-645b-11ea-9447-4c025a1199e0.png)

![image](https://user-images.githubusercontent.com/16408873/76486998-f72dd900-645b-11ea-87d0-73db2fb9beb7.png)

![image](https://user-images.githubusercontent.com/16408873/76487101-41af5580-645c-11ea-9d46-b71e0bbb25b4.png)

**Comment by joshiste** [comment]
The stacktrace contains not a single class of Spring Boot Admin. It looks not like a Spring Boot Admin issue. I guess you have to open a issue for [spring boot](https://github.com/spring-projects/spring-boot)
