### ISSUE TITLE
Publish an Docker image 

### ISSUE THREAD

**Issue by robert2411** [codecentric/spring-boot-admin#1376]
It would be nice if there would be an 'official' spring boot admin image on docker hub
It should not be hard to add it as there are already builds that build a docker image. they are just not published

I don't mind helping if needed but I cannot do the push to dockerhub as I don't have access to the codecentric account

**Comment by joshiste** [comment]
We could publish the sample projects as docker images, but the downside would be that you have to use the security config from the sample - which is not customizable and probably not what you want for your production system.
Also as there are many options to register the clients (sba-client, eureka, zookeeper, kubernetes, ....) we don't want to provide an image for every use case.

These are the reasons, we currently don't publish any docker image.

**Comment by joshiste** [comment]
We can discuss these points, but in addition I don't have the time to do it and test the images.
