### ISSUE TITLE
logfile error 416

### ISSUE THREAD

**Issue by sky266** [codecentric/spring-boot-admin#1377]
when i click menu logfile then get a error msg 
--------
Fetching logfile failed.
Request failed with status code 416
--------
server log file was truncated 
how to fix this problem?

The http request head content an item    Range: bytes=-307200

**Comment by sky266** [comment]
I know why . because of i use alibaba.fastjson . idon't know how to resolve this problem.

**Comment by joshiste** [comment]
> I know why . because of i use alibaba.fastjson . idon't know how to resolve this problem.

You could try using Jackson in your actuator endpoints - see https://github.com/codecentric/spring-boot-admin/issues/751#issuecomment-575999785

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by HusseinElMotayam** [comment]
I faced the same issue, I had `logging.level.root=ERROR` and there were zero errors, so the log file was really empty.
When testing `actuator/logfile`, it returned 200 with an empty response.

**Comment by rexlin600** [comment]
so i thinl this is a bug,i meet this too

when log file is empty, 416 error
