### ISSUE TITLE
did you guys found oom in spring-boot-admin-starter-server 2.1.6 version

### ISSUE THREAD

**Issue by john1337** [codecentric/spring-boot-admin#1381]
![78C2E52E-D37D-4634-9F47-F415821F0E61](https://user-images.githubusercontent.com/11956341/76840395-14a2de80-6872-11ea-9b54-cae2f0943b24.png)

i found a oom problem in chrome when i open httptrace page in spring-boot-admin-starter-server,chrome shows the heap size is increasing all the time up to 2g bytes,until stopped by chrome's protection,
finally it will cause the chrome crash

**Comment by john1337** [comment]
i found the where the problem occurs is chartData func in traces-chart.vue

**Comment by joshiste** [comment]
please update to a recent 2.2.x version and see if the problem still persists.

**Comment by joshiste** [comment]
closed du to missing feedback

**Comment by john1337** [comment]
yes,2.2.x version has the problem also

**Comment by john1337** [comment]
> please update to a recent 2.2.x version and see if the problem still persists.

yes,2.2.x version has the problem also

**Comment by joshiste** [comment]
So does it work or do you still experience an oom?
