### ISSUE TITLE
Unable to add images to mail template

### ISSUE THREAD

**Issue by AravindPalani95** [codecentric/spring-boot-admin#1382]
Is there is any option to add inline images to custom mail template SBA?

Tried, Placing images inside static folder ( th:src="/images/someimg.png" ) but image got broken.

Do I have any alternate option to bring images into SBA mail.

**Comment by joshiste** [comment]
The template processor doesn't embed the image nor does it resolve the src attribute to an absolute url.

You either should use absolute urls or data-urls. It would be possible to add the images as a mime-part in the mail but that would require you to customize the `MailNotifier`

If the image is served on the admin server you can use the `${baseUrl}` (which resolves to the value you set in `spring.boot.admin.ui.public-url`) in the tyhemleaf template to render an absolute url.
