### ISSUE TITLE
Add support for registering Spring Boot Admin Client manually with config file or code on Server side.

### ISSUE THREAD

**Issue by xiaoxipangren** [codecentric/spring-boot-admin#1383]
Hi,
I'm looking for a lightweight visualization solution for Spring Boot application and SBA is perfect for me. But I want to deploy SBA server on intranet, thus SBA client couldn't register to server by HTTP request. Is there a way to do registration with client configuration info on server side? After all, server can pull data from client, so that we can make sure there is just one data flow direction.

**Comment by joshiste** [comment]
see https://codecentric.github.io/spring-boot-admin/current/#spring-cloud-discovery-static-config
