### ISSUE TITLE
context-path does not working

### ISSUE THREAD

**Issue by MasterLi** [codecentric/spring-boot-admin#1386]
**On page http://localhost:10030/registry-service/admin/applications - shows admin page, but error:**
Server connection failed.
Cannot read property 'map' of undefined

![image](https://user-images.githubusercontent.com/2511354/77536104-d4b0ac80-6eac-11ea-9cbd-257ea6020891.png)

**Browser console has error:**
index.js:55 The routes ["/about","/applications/:selected?","/instances/:instanceId","/journal","/wallboard"] aren't known to the backend and may be not properly routed!
e906 @ index.js:55 o @ bootstrap:840 @ sba-core.fc88cc06.js:1o @ bootstrap:84n @ bootstrap:45(anonymous) @ bootstrap:221(anonymous) @ sba-core.fc88cc06.js:1
index.js:84 Connection to server failed: TypeError: Cannot read property 'map' of undefined

**Also endpoints return 405 http error code:**
http://localhost:10030/registry-service/admin/instances

HTTP/1.1 405 
Allow: GET
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 25 Mar 2020 12:21:55 GMT
Keep-Alive: timeout=60
Connection: keep-alive

{
  "timestamp": "2020-03-25T12:21:56.362+0000",
  "status": 405,
  "error": "Method Not Allowed",
  "message": "Request method 'POST' not supported",
  "path": "/registry-service/admin/instances"
}

Response code: 405; Time: 16ms; Content length: 177 bytes

![image](https://user-images.githubusercontent.com/2511354/77535994-a763fe80-6eac-11ea-9ced-e5c9cefa9c80.png)

**application.yml :**
  boot:
    admin:
      context-path: /admin
      url: http://${spring.cloud.client.hostname}:${server.port}
      client:
        enabled: false
    ui:
      public-url: http://${spring.cloud.client.hostname}:${server.port}${server.servlet.context-path}/admin/

build.gradle:
    implementation "de.codecentric:spring-boot-admin-server-ui:2.2.2"
    implementation "de.codecentric:spring-boot-admin-server:2.2.2"

Result: context-path does not working.

**Comment by joshiste** [comment]
please provide a project to reproduce the issue.

**Comment by MasterLi** [comment]
Problem was resolved. Was conflict with @EnableConfigServer. Sorry for the inconvenience
