### ISSUE TITLE
The path from the service discovery uri is ignored.

### ISSUE THREAD

**Issue by andresoviedo** [codecentric/spring-boot-admin#1388]
**Bug report**

The ServiceInstanceConverter feature is broken in spring-boot-admin v.2.2.2
The service url is not taken into account when generating the /health and /info endpoint. 
They don't contain the /context-path of the application.

For instance, with this service url  "http://example.com/myapp", having the conversion feature enabled, the /info and /health endpoint get converted to http://example.com/info and http://example.com/health that is incorrect.  It should be http://example.com/myapp/info and http://example.com/myapp/health respectively.

**Workaround**

I had to overwrite the Converter implementation using the version 2.1.6 that is working fine.

**Comment by joshiste** [comment]
Could you please provide some more details?
1. What kind of discovery are you using.
2. What is the registered Url and metadata of the service from the discovery?

**Comment by andresoviedo** [comment]
Hello @joshiste 

Thank you. I am using SimpleDiscoveryClient.  i.e.

    spring.boot.admin.discovery.converter.management-context-path=/manage
    spring.cloud.discovery.client.simple.instances.cloud-admin- UAT[0].uri=http://example.com:8080/myapp
    spring.cloud.discovery.client.simple.instances.cloud-admin-UAT[0].metadata.user.name=usr
spring.cloud.discovery.client.simple.instances.cloud-admin-UAT[0].metadata.user.password=pwd

The registered URL is OK, but not the /info or /health endpoints

**Comment by joshiste** [comment]
We don't use the path part from `ServiceInstance#getUri()` (only the scheme, host and port).
As the most s-c-discovery implementations doesn't provide it, the bug slipped through.

**Comment by lburja** [comment]
In latest Spring Boot Admin (v2.4.1) using spring-cloud-starter v3.0.2, this is still broken.

The following from `DefaultServiceInstanceConverter` 

```
protected URI getServiceUrl(ServiceInstance instance) {
     return instance.getUri();
}
```
does not produce the expected result because `instance.getUri()` doesn't actually return the configured uri value, but builds it and strips the path (at least using the `DefaultServiceInstance` implementation, see `DefaultServiceInstance::getUri`)
