### ISSUE TITLE
Include Liveness and Readness Probes states

### ISSUE THREAD

**Issue by membersound** [codecentric/spring-boot-admin#1389]
As of spring-boot-2.3.0, there will be an interesting feature providing states for *readyness* and *liveness*:
https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot

Are you planning to integrate them in your evaluation in admin-server?

**Comment by joshiste** [comment]
As the liveness and readiness probes are a details of the health end they appear in the ui - so basic support is given.

What features do you want to see over that?
