### ISSUE TITLE
Optional Integration of hystrix Server together with admin server

### ISSUE THREAD

**Issue by cforce** [codecentric/spring-boot-admin#139]
Embedd hystrix server as part of the admin server. Care for the path problems - publish apps on different context .

**Comment by joshiste** [comment]
Can you be please a bit precise? At best provide an sample.

**Comment by cforce** [comment]
yes auto-correction is sometimes a  hazzle

**Comment by joshiste** [comment]
Did you configure the `spring.boot.admin.context-path` on your app?

**Comment by cforce** [comment]
Works
