### ISSUE TITLE
HELP ME: The following method did not exist: RequestMappingHandlerMapping.registerHandlerMethod

### ISSUE THREAD

**Issue by heykb** [codecentric/spring-boot-admin#1390]
**spring boot** :2.1.7
**jdk**: 1.8
**spring boot admin server**: 2.2.0
**spring boot cloud** : Greenwich.SR2

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    de.codecentric.boot.admin.server.web.servlet.AdminControllerHandlerMapping.registerHandlerMethod(AdminControllerHandlerMapping.java:46)

The following method did not exist:

    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.registerHandlerMethod(Ljava/lang/Object;Ljava/lang/reflect/Method;Lorg/springframework/web/servlet/mvc/method/RequestMappingInfo;)V

The method's class, org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping, is available from the following locations:

    jar:file:/E:/%e7%ac%94%e8%ae%b0/%e7%ac%94%e8%ae%b0/%e8%bd%af%e4%bb%b6/apache-maven-3.6.0-bin/rep/org/springframework/spring-webmvc/5.1.9.RELEASE/spring-webmvc-5.1.9.RELEASE.jar!/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.class

It was loaded from the following location:

    file:/E:/%e7%ac%94%e8%ae%b0/%e7%ac%94%e8%ae%b0/%e8%bd%af%e4%bb%b6/apache-maven-3.6.0-bin/rep/org/springframework/spring-webmvc/5.1.9.RELEASE/spring-webmvc-5.1.9.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping

Process finished with exit code 1

**Comment by joshiste** [comment]
You need to use spring boot 2.2.x for SBA 2.2.x
