### ISSUE TITLE
disabled basic authentication in 2.2.x ?

### ISSUE THREAD

**Issue by kpouer** [codecentric/spring-boot-admin#1391]
Hello,
migrating from version 2.1.6 to 2.2.2 it seems basic authentication is not working anymore.
The reason was the removal of the basicAuthHttpHeadersProvider bean from AdminServerAutoConfiguration in that commit.

https://github.com/codecentric/spring-boot-admin/commit/9833fd66c4e9394d9dc863b3fb1319ba4fa79cf7

Maybe I missed something in the doc bug I did not see anything about it.
Of course it is easy to fix, I can add the bean back and it works, but I was not sure if it was wanted or not.

**Comment by joshiste** [comment]
The bean is still there:
https://github.com/codecentric/spring-boot-admin/blob/535489797b55a0f0afb52250787b68127b40aa3e/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerInstanceWebClientConfiguration.java#L138
