### ISSUE TITLE
Fetching logfile failed

### ISSUE THREAD

**Issue by ElarbiMohamedAymen** [codecentric/spring-boot-admin#1393]
Hi guys, I'm facing this error when I open "Logging" -> "Logfile" menu:

Fetching logfile failed
Cannot read property 'split' of undefined

![image](https://user-images.githubusercontent.com/22550761/78928364-c2d02b80-7aa0-11ea-8ed1-b5ede516d942.png)

Browser : Chrome
Version : 80.0.3987.163

Respone :

![image](https://user-images.githubusercontent.com/22550761/78928605-307c5780-7aa1-11ea-8a9b-2b7ed4eeb39b.png)

Header Response :

![image](https://user-images.githubusercontent.com/22550761/78928687-59045180-7aa1-11ea-8b9d-61cf81c38ea2.png)

**Comment by joshiste** [comment]
@ElarbiMohamedAymen The logfile endpoint must return the plain logfile and not a json.

**Comment by ElarbiMohamedAymen** [comment]
@joshiste when I access my logfile endpoint on browser it prints a partial content of the log file.
I've changed my apiWebConfig file to this :

    private MappingJackson2HttpMessageConverter jacksonMessageConverter() {

        Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder()
                .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                .featuresToDisable(SerializationFeature.FAIL_ON_EMPTY_BEANS)
                .modulesToInstall(hibernate5Module().configure(Feature.FORCE_LAZY_LOADING, false));

        MappingJackson2HttpMessageConverter mc = new MappingJackson2HttpMessageConverter(builder.build());
        List<MediaType> supportedMediaTypes =
                new ArrayList<>(mc.getSupportedMediaTypes());
        supportedMediaTypes
                .add(MediaType.valueOf(MediaType.ALL_VALUE));
        mc.setSupportedMediaTypes(supportedMediaTypes);

        return mc;
    }

If I remove the part of adding `MediaType.valueOf(MediaType.ALL_VALUE)` it will prints the whole file content (even server startup banner) **but it displays 406 with json response content type.**

Is there a way to change or force /actuator/logfile endpoint to return text content ?

**Comment by joshiste** [comment]
@ElarbiMohamedAymen something like this may work https://github.com/codecentric/spring-boot-admin/issues/751#issuecomment-575999785
