### ISSUE TITLE
Fetching logfile failed: Request failed with status code 404

### ISSUE THREAD

**Issue by kqkdChen** [codecentric/spring-boot-admin#1394]
** Question **
 Fetching logfile failed.
Request failed with status code 404
![image](https://user-images.githubusercontent.com/41674301/78967197-5999f800-7b34-11ea-96f1-da3fb8baa633.png)
![image](https://user-images.githubusercontent.com/41674301/78967407-f65c9580-7b34-11ea-827f-3f095493bc3f.png)

The strange thing is that some services will have **logfile 404**. I use **Docker Swarm** for deployment.This did not happen in the past when registering with **Eureka**, but now it happens when registering with **Nacos**.

For each service, I have set logging.file = $ {HOME} /logs/console.log in yml, and I can find these logs file in the container.

Admin Version : 2.1.6
Spring Cloud Version : Greenwich.RELEASE
Spring Cloud Alibaba Version :  2.1.1.RELEASE

What information do I need to provide?

**Comment by joshiste** [comment]
Can you check that if you hit the `/actuator/logfile` endpoint directly the response is 200 OK?

**Comment by kqkdChen** [comment]
> Can you check that if you hit the `/actuator/logfile` endpoint directly the response is 200 OK?
> 
> 您能否检查一下，如果直接命中 / actuator / logfile 端点，响应是否为200 OK？

Thank you, I have found the problem, because I configured the **logging.file** in Nacos, it does not seem to be loaded correctly, I put it in bootstrap.yml in project and it can be displayed correctly, this is my solution

**Comment by rexlin600** [comment]
i meet this problem too, and i put logging.file.path config in bootstrap.yml,it works!
