### ISSUE TITLE
Add filters to Wallboard

### ISSUE THREAD

**Issue by benmlahzied** [codecentric/spring-boot-admin#1396]
We have 6 monitored services installed on 10 environnements.  So our wallboard became unreadable.
I suggest, to enhance the UI in order to permit to the users to filter by environnment, service and status.

**Comment by Glosur** [comment]
I'd like to contribute to that, however, I have no idea how this could look like from a design point of view

**Comment by joshiste** [comment]
may be [filter icon](https://fontawesome.com/icons/filter?style=solid) in the top right which opens a popup where you have an input field which filters the applications.

The filter expression should be reflected in a query param.
