### ISSUE TITLE
Description of service status

### ISSUE THREAD

**Issue by feiquan666** [codecentric/spring-boot-admin#1397]
You can tell me about UNKNOWN, OUT_OF_SERVICE,
Do you have specific description and starting conditions of DOWN, OFFLINE, RESTRICTEDand other states? I need to use this to identify the real situation of my service

**Comment by joshiste** [comment]
UNKNOWN = we haven't checked the health yet.
RESTRICTED = You have multiple applications with some of them bein UP or NOT

... all other values (UP, DOWN, OUT_OF_SERVICE) are the same as in spring boot.
