### ISSUE TITLE
Health check passed, but application status acquisition failed

### ISSUE THREAD

**Issue by feiquan666** [codecentric/spring-boot-admin#1399]
![image](https://user-images.githubusercontent.com/42441073/79427016-919eb080-7ff6-11ea-8539-4bbaaf7932e4.png)
The information I got through the health examination is as follows:
{"status":"UP","components":{"discoveryComposite":{"status":"UP","components":{"discoveryClient":{"status":"UP","details":{"services":[]}},"eureka":{"description":"Eureka discovery client has not yet successfully connected to a Eureka server","status":"UP","details":{"applications":{}}}}},"diskSpace":{"status":"UP","details":{"total":865441484800,"free":691815559168,"threshold":10485760}},"hystrix":{"status":"UP"},"ping":{"status":"UP"},"refreshScope":{"status":"UP"}}}

sba -version: 2.2.1
jdk-version: 1.8
i confirm chrome cache is closed。

**Comment by feiquan666** [comment]
![image](https://user-images.githubusercontent.com/42441073/79431556-315f3d00-7ffd-11ea-8f6c-759f25acad99.png)

**Comment by joshiste** [comment]
can you provide a sample project to reproduce the issue?

**Comment by feiquan666** [comment]
yes i can，project download address is：
[microservice-monitor.zip](https://github.com/codecentric/spring-boot-admin/files/4486030/microservice-monitor.zip)

**Comment by feiquan666** [comment]
another problem is ： when i stop one client , my doNotify(InstanceEvent event, Instance instance) method can work, but when i start it again，that can‘t get into doNotify(InstanceEvent event, Instance instance)

**Comment by feiquan666** [comment]
the project code by idea，maven version is 3.6,
modules description:  eureka-server is my register center，eureka-admin is Spring-boot-admin server,other both eureka client, find by @EnabledDiscoverClient

**Comment by feiquan666** [comment]
can you tell me yours WeChat or QQ or Dingding account？
