### ISSUE TITLE
eureka is a server need to start in a instance?

### ISSUE THREAD

**Issue by lmx1989219** [codecentric/spring-boot-admin#140]
![image](https://cloud.githubusercontent.com/assets/9464485/12032929/abafc9a6-ae58-11e5-9599-0e98379de7d2.png)

how can i do to resolved this problem

**Comment by joshiste** [comment]
Setup Eureka property...see
http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html

**Comment by lmx1989219** [comment]
thanks,but where is spring-boot-admin 1.3.3 snapshot？i found that 1.3.1 not support Eureka  server.

**Comment by joshiste** [comment]
1.3.2 should do it!

2015-12-29 13:06 GMT+01:00 lucas <notifications@github.com>:
