### ISSUE TITLE
Spring Boot Admin Certificate error in the logs

### ISSUE THREAD

**Issue by mciumac** [codecentric/spring-boot-admin#1400]
I am using Spring Boot Admin 2.2.2 . I configure it to use SSL. I register SSL applications with it.
Everything works good as suppose to. Able to access Spring Boot Admin through https and its applications info from it. But when I look in the logs I see this (see below).  I get this error because at some point it uses underneath the ip address. But all my urls for spring boot admin and registered applications are using dns names and certificate are also for dns name.  It does not affect functionality  of the app. So the question is why ip address  is used at some point and what should I do to fix this.

2020-04-16 12:52:33.535 [a2-admin-server,,,] [reactor-http-nio-2] ERROR reactor.netty.tcp.TcpServer - [id: 0x058d8c1f, L:0.0.0.0/0.0.0.0:8760 ! R:/10.1.42.56:57868] onUncaughtException(SimpleConnection{channel=[id: 0x058d8c1f, L:0.0.0.0/0.0.0.0:8760 ! R:/10.1.42.56:57868]})
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

**Comment by joshiste** [comment]
I guess you are using some kind of self-signed certificate. You need to import into your trustkeystore. 
This is not an SBA issue.

**Comment by joshiste** [comment]
SBA uses the URLs provided by the discovery or submitted by the sba-clients as is.

**Comment by mciumac** [comment]
I do have a certificate that is for dns name otherwise I wouldn't be able to successfully call the SBA url.  The port 57868 from the error it is not even the port that the SBA is running on. This error I see in the logs while navigating through SBA. All the urls configured in application.properties files are using dns name. 
I would expect this error will go away  if I add the certificate for ip address also. But why do I have to do it , if I use DNS name and again the call with error above is happening behind the scenes that I don't have control of.  So how do you label this issue as "invalid" when it is happening?
