### ISSUE TITLE
Loggers view doesn't work with multiple instances

### ISSUE THREAD

**Issue by lambliesdown** [codecentric/spring-boot-admin#1402]
I'm running version 2.2.2 and register several applications. When there's a single instance of an application, the Loggers view is perfectly fine. When I have multiple instances of an application, open the view for one of them and then try to go to the loggers, I'm immediately kicked out to 
http://localhost:9300/login?redirectTo=http%3A%2F%2Flocalhost%3A9300%2Finstances%2Ff28da854c543%2Floggers

I'm using the security configuration as suggested in https://codecentric.github.io/spring-boot-admin/current/#securing-spring-boot-admin.

Happens both for latest Chrome and Firefox

**Comment by joshiste** [comment]
hmm I'd guess one of the instances is responding with a 401. Can you try to test it for each instance?

**Comment by lambliesdown** [comment]
It happens for all instances. When I shut down one of the instances, it works fine for the remaining one. As soon as I launch a second one, the problem shows up again. The actuator endpoints on all my apps are configured with basic auth and the same credentials.

**Comment by joshiste** [comment]
May be there is an error picking up the credentials when dealing with multiple instances

**Comment by lambliesdown** [comment]
I did some more debugging and logged the requests. In the case of multiple instances, the culprit seems to be an additional call '/applications/<app name>/actuator/loggers' which causes a 401. If there's only a single instance, I don't see this call. See the attached header logs for the two different case.

[http_log.txt](https://github.com/codecentric/spring-boot-admin/files/4521640/http_log.txt)

**Comment by joshiste** [comment]
the sba server should make a request to each individual instance if `/applications/{application}/actuator/loggers` is hit. I guess some how it fails to add the authorization for the individual instances...

**Comment by lambliesdown** [comment]
Turns out it was my fault. I configured the security on the actuator endpoints of the SBA server incorrectly. I activated basic auth on the endpoints by specifying the ant pattern /**/actuator/**. This included and rejected the /applications/{application}/actuator/loggers call. Using 
http.requestMatcher(EndpointRequest.toAnyEndpoint()) as described in the [Spring Boot Actuator Doc](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-security) fixed the issue.
Sorry for raising this as an issue.
