### ISSUE TITLE
java.lang.NoSuchMethodError - PathMappedEndpoints

### ISSUE THREAD

**Issue by Angahran** [codecentric/spring-boot-admin#1403]
Seeing the following error in spring Boot v2.1.5.RELEASE.

2020-04-21 08:59:53.352 ERROR 13578 --- [gistrationTask1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
java.lang.NoSuchMethodError: org.springframework.boot.actuate.endpoint.web.PathMappedEndpoints.getPath(Ljava/lang/String;)Ljava/lang/String

**Comment by joshiste** [comment]
From your current description I don't see how this relates to spring boot admin.

**Comment by Angahran** [comment]
Apologies if this is in the wrong place.
I found what appeared to be a similar issue and thought my problem could be something related.
[](https://github.com/codecentric/spring-boot-admin/issues/953)
