### ISSUE TITLE
SBA doesn't see new service instances

### ISSUE THREAD

**Issue by Birthright50** [codecentric/spring-boot-admin#1405]
I use SBA 2.2.2, spring boot 2.2.6, spring cloud Hoxton SR4.

I made a test project to reproduce the problem  [https://github.com/Birthright50/admin-fail-instances](url).

We we have 4 services: `discovery-server`, `config-server`, `admin-server` and `cart-service`.
if you run them in this order:
* discovery
* config
* admin
* cart

SBA does not display in UI `admin-server` and `cart-service`, only `config-server`.
But in logs we see  that discovery client sees the `cart-service`.

`2020-04-25 18:57:53.814 DEBUG 31506 --- [freshExecutor-0] c.n.d.DiscoveryClient                    : Added instance 192.168.0.103:cart-service:8082 to the existing apps in region null`

![actual](https://user-images.githubusercontent.com/8762658/80285114-5bb2a800-872b-11ea-89fd-5d77206002d4.jpg)

if you restart SBA (but other services still alive), it will start showing `cart-service`, but it still doesn’t see itself.

![afterReboot](https://user-images.githubusercontent.com/8762658/80285118-68cf9700-872b-11ea-8530-7197eeff09af.jpg)

I see this issue https://github.com/codecentric/spring-boot-admin/issues/1327
Is this bug related to it? I noticed that this problem with updating instances occurred precisely with updating from spring boot 2.1 to 2.2 and cloud Greenwich to Hoxton.
From now on, it is not possible to use SBA to monitor applications.

**Comment by joshiste** [comment]
Which kind of discovery are you using? Eureka? Kubernetes? ...

**Comment by Birthright50** [comment]
> Which kind of discovery are you using? Eureka? Kubernetes? ...

netflix eureka

**Comment by joshiste** [comment]
@Birthright50 looks like the same problem as in https://github.com/codecentric/spring-boot-admin/issues/1327 which was reported to not be a SBA problem ...
Please have a look at the issue history...

**Comment by joshiste** [comment]
closed due to missing feedback
