### ISSUE TITLE
???

### ISSUE THREAD

**Issue by jotsinghdhillon** [codecentric/spring-boot-admin#1409]
Trying to get List of images or List<Resource> from the folder using ResponseEntity<List<Resource>> but it is giving me Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class java.nio.channels.Channels$1]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class java.nio.channels.Channels$1 and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0]->org.springframework.core.io.FileUrlResource["outputStream"])] 

```
// have a file path that has all the images in it. 
//NOTE: if i try to get one image using ResposeEntity<Resource> as return type. things work. But in 
//the use case i need more than one images to be coming from the folder path. 

@GetMapping("/Email/{spEmail}/{issuer}/{token}")
public ResponseEntity<List<Resource>> getUserCategoryImages( @PathVariable String spEmail,
													 @PathVariable String issuer,
													@PathVariable String token
												) throws NoSuchAlgorithmException {
	List<Resource> images= new ArrayList<Resource>();
		images.add(resourceLoader.getResource("file:"+ UPLOAD_ROOT + "/" +"GuestEmailJPEG_20200418_162752_2781835255317487645.jpg"));
	   images.add(resourceLoader.getResource("file:"+ UPLOAD_ROOT + "/" +"GuestEmailJPEG_20200418_162744_872144252722166725.jpg"));
		
		
return new ResponseEntity<List<Resource>>( images, HttpStatus.OK);
```

**Comment by joshiste** [comment]
1) I don't get what your problem is
2) I don't get how it relates to Spring Boot Admin

**Comment by joshiste** [comment]
closed due to missing feedback
