### ISSUE TITLE
Limit languages to a subset of existing ones

### ISSUE THREAD

**Issue by bratwurzt** [codecentric/spring-boot-admin#1417]
When developing a custom extension with a subset of languages, I'd like to limit other screens to that subset as well. 

I have a few options I could PR:
1. ui properties - this one is the fastest and easiest: add a comma-separated array od languages that are checked and filtered in `AVAILABLE_LANGUAGES` of `'@/i18n'`
2. automatically limit languages to common denominator subset: e.g. if an extension supports only en, the whole of spring-bootadmin-ui should do the same. Could be controlled by a property.

I am leaning to option 1 just because I am a backend developer and I could implement that. The second option would be more difficult (for me).

There are other reasons why you'd like to limit languages (clarity, customer wishes, ...). @joshiste, what's your opinion?

**Comment by joshiste** [comment]
I don't like the idea of removing a language if a single extensions doesn't support it.
It should then just fallback to the default ('en') translation for the missing texts.

What I think is valuable would be a property to restrict available languages in general.
E.g. For a german user it isn't very worthy to have chinese chosable.
So we could add a property that you can use to restrict the list 'de' and 'en'.

This way we don't need any complex magical thing to read all available translations from the extensions.

**Comment by bratwurzt** [comment]
> 
> 
> I don't like the idea of removing a language if a single extensions doesn't support it.
> It should then just fallback to the default ('en') translation for the missing texts.
> 
> What I think is valuable would be a property to restrict available languages in general.
> E.g. For a german user it isn't very worthy to have chinese choosable.
> So we could add a property that you can use to restrict the list 'de' and 'en'.
> 
> This way we don't need any complex magical thing to read all available translations from the extensions.

Yes, that's what I was thinking, too. Will prepare a PR in the next few days.

**Comment by joshiste** [comment]
> Yes, that's what I was thinking, too. Will prepare a PR in the next few days.

👍 👏

**Comment by bratwurzt** [comment]
> 
> 
> > Yes, that's what I was thinking, too. Will prepare a PR in the next few days.
> 
> 👍 👏

PR #1418 is ready.
