### ISSUE TITLE
Unable to remove the applications from boot admin UI

### ISSUE THREAD

**Issue by aayushgupta** [codecentric/spring-boot-admin#142]
I have changed the context name for the management endpoints in my application.
management.context-path=/admin

Now the spring boot admin UI is showing two applications, one as UP and running pointing to 
http://<hostname>:8080/myapp/admin/health (as expected)

and other as DOWN , trying to connect to   
http://<hostname>:8080/myapp/health 

I am trying to remove the DOWN application but its added back again to UI. Is there a way to remove it from boot admin server.

Shouldn't there be some mechanism to automcatically remove the DOWN application, just for such scenarios not for everything.

**Comment by joshiste** [comment]
Your urls look a bit weird to me, with the missing host...

If the applications is added over and over again, it is most likely being registered in the background...
Did you check that this isn't the case?

There is a feature to deregister applications when they are shut down, but it is disabled by default. [Look in the docs](http://codecentric.github.io/spring-boot-admin/1.3.2/#spring-boot-admin-client) for `spring.boot.admin.auto-deregistration`

**Comment by aayushgupta** [comment]
I am using a hostname in the actual configuration URL, I am surprised how it just disappeared while posting here... 
Yes I have a setup where multiple admin clients are connected to a single admin server. I have been redeploying the application again and again, but I have restared the server as well.

**Comment by joshiste** [comment]
> I am using a hostname in the actual configuration URL, I am surprised how it just disappeared while posting here... 

So is this issue resolved?

**Comment by aayushgupta** [comment]
My bad... its was the another instance of same application (with old configuration) running on different node, and had the wrong configuration (specifying the hostname name for other node).
Used tcpdump to get the IP of registeration request, cleanedup configuration and it worked. 
thanks a lot for your help!!!!

I know its bad at my part, but won't it be useful to show the IP address of the application on details page along with version and other details...
