### ISSUE TITLE
Error creating bean with name 'adminHandlerMapping'

### ISSUE THREAD

**Issue by aeron1sh** [codecentric/spring-boot-admin#1420]
I am trying to set up spring boot admin server, and when I started the app it failed with error shown below: 

`2020-05-07 22:03:55.248  WARN 1564 --- [  restartedMain] ConfigServletWebServerApplicationContext : {} Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'adminHandlerMapping' defined in class path resource [de/codecentric/boot/admin/server/config/AdminServerWebConfiguration$ServletRestApiConfirguation.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.registerHandlerMethod(Ljava/lang/Object;Ljava/lang/reflect/Method;Lorg/springframework/web/servlet/mvc/method/RequestMappingInfo;)V`

Additional log: 
`APPLICATION FAILED TO START
An attempt was made to call a method that does not exist. The attempt was made from the followinglocation:de.codecentric.boot.admin.server.web.servlet.AdminControllerHandlerMapping.registerHandlerMethod(AdminControllerHandlerMapping.java:46) The following method did not exist:
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.registerHandlerMethod(Ljava/lang/Object;Ljava/lang/reflect/Method;Lorg/springframework/web/servlet/mvc/method/RequestMappingInfo;)V
The method's class, org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping, is available from the following locations:

    jar:file:/C:/Users/.m2/repository/org/springframework/spring-webmvc/5.1.14.RELEASE/spring-webmvc-5.1.14.RELEASE.jar!/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.class

It was loaded from the following location:

    file:/C:/Users/.m2/repository/org/springframework/spring-webmvc/5.1.14.RELEASE/spring-webmvc-5.1.14.RELEASE.jar`

what I added in the pom.xml is:
`<dependency><groupId>de.codecentric</groupId><artifactId>spring-boot-admin-starter-server</artifactId><version>2.2.3-SNAPSHOT</version></dependency>
`
spring boot  2.1.13
spring-webmvc 5.1.14

Any idea please?

**Comment by joshiste** [comment]
for spring boot 2.1.x you have to use sba 2.1.x
