### ISSUE TITLE
Add SB 1.x LegacyConverters for beans, configprops and mapping endpoints

### ISSUE THREAD

**Issue by mehiel** [codecentric/spring-boot-admin#1421]
In order to support a transition phase from boot 1.x to 2.x I found out that support for boot 1.x apps in SBA 2.x is pretty much in place but with some extra legacy converters it could be easily improved.

Is there any interest for Beans, Configprops and Mappings LegacyConverters? I have a (wip) branch [1] that I could tide up and create a PR out of it. Beans and configprops are almost in place and I'm currently working on Mappings.

@joshiste feel free to close the issue if not interested.

[1] https://github.com/mehiel/spring-boot-admin/commit/8aa1e90a5084b9219005928864a26a6cb82ce61f

**Comment by joshiste** [comment]
@mehiel If you add some tests to the converters I'm happy to accept a PR for them.

**Comment by mehiel** [comment]
Sure thing. I'll make the PR as soon as I have all the pieces in place and we can continue the discussion there.

**Comment by mehiel** [comment]
> @mehiel If you add some tests to the converters I'm happy to accept a PR for them.

@joshiste FYI PR and tests are in place. Feel free to review and let me know your thoughts.
