### ISSUE TITLE
Update to Spring Boot 2.2.7 and Spring Cloud Hoxton.SR4

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#1422]

**Comment by zhangdberic** [comment]
When the browser is open and is in the monitoring interface, the Linux system will generate a large number of closed tcp connections.

[root@middleware ~]# ss -s
Total: 48484 (kernel 48504)
TCP:   48284 (estab 59, closed 48193, orphaned 0, synrecv 0, timewait 1/0), ports 0

Transport Total     IP        IPv6
*	  48504     -         -        
RAW	  0         0         0        
UDP	  1         1         0        
TCP	  91        91        0        
INET	  92        92        0        
FRAG	  0         0         0
