### ISSUE TITLE
why no `http trace` and `logging` in version`2.2.1` and `2.2.2`?

### ISSUE THREAD

**Issue by FutaoSmile** [codecentric/spring-boot-admin#1423]
### # why no `http trace` and `logging` in version`2.2.1` and `2.2.2`?

* now:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/17999702/81471980-b538cd80-9227-11ea-8115-8c5c6d7d4a29.png">

* before: 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/17999702/81471990-c1bd2600-9227-11ea-926f-46fc11b31e12.png">

**Comment by Glosur** [comment]
The actuator endpoint is now disabled by default on your monitored applciations

Cf. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#actuator-http-trace-and-auditing-are-disabled-by-default

For the logging part, it might have something to do with https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#deprecations-in-spring-boot-22 and the renaming of logging properties.

**Comment by FutaoSmile** [comment]
> The actuator endpoint is now disabled by default on your monitored applciations
> 
> Cf. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#actuator-http-trace-and-auditing-are-disabled-by-default
> 
> For the logging part, it might have something to do with https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#deprecations-in-spring-boot-22 and the renaming of logging properties.

thank you so much.
