### ISSUE TITLE
DefaultServiceInstanceConverter: management.context-path should support pathing

### ISSUE THREAD

**Issue by brianrodecap** [codecentric/spring-boot-admin#1425]
Please consider an enhancement to translate management.context-path to include delimited paths.

Consider that the following service YAML is illegal...

`management.context-path: v1/my-web-services/actuator`

> Error "Invalid value: "v1/my-web-services/actuator": a valid label must be an empty string or consist of alphanumeric characters, '-', '\_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" for field "metadata.labels".

As a temporary workaround, we specify the path using underscores...

`management.context-path: v1_my-web-services_actuator`

...and have hacked DefaultServiceInstanceConverter.getManagementPath()...

```
protected String getManagementPath(ServiceInstance instance) {
	String managementPath = instance.getMetadata().get(DefaultServiceInstanceConverter.KEY_MANAGEMENT_PATH);
	if (!isEmpty(managementPath)) {
		// custom translation hack
		return managementPath.replace("_", "/");
	}
	return this.managementContextPath;
}
```

Realizing that this is a Kubernetes limitation, please consider introducing a "management path separator" ( '-', '_' or '.') to optionally support non-trivial pathing.

**Comment by joshiste** [comment]
Adding this might break existing configurations using an underscore and we would also need someway to escape the underscore, so I'm not willing to add this to the SBA client.

It's missing in the Spring Cloud Kubernetes docs, but looking at the [Spring Cloud Kubernetes source code](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java#L177) you can also configure the metadata using k8s annotations.

IIRC the restrictions doesn't apply here, so please try configuring your path using annotations.

**Comment by brianrodecap** [comment]
Great advice on using annotations.  Worked like a charm!
