### ISSUE TITLE
Custom Extension Resources not found when using a custom context-path 

### ISSUE THREAD

**Issue by codingDriver** [codecentric/spring-boot-admin#1426]
After upgrading to SBA 2.2.3 from 2.2.2 our custom extensions not found anymore. The URLs to load the extension resources starts with "/extensions/" and ignores our defined context-path. The default SBA resources use the our context-path.
e.g.
https://mega.app-hamburg.de/foo/assets/js/sba-core.86dd6e42.js -> OK

https://mega.app-hamburg.de/extensions/info/js/custom.5af550b0.js -> NOT FOUND

-> the context path "foo" is missing. 

If we change the URL to 

https://mega.app-hamburg.de/foo/extensions/info/js/custom.5af550b0.js -> OK

**Comment by scramboy** [comment]
Hi there, may I know when this will be released? I see it is in 2.2.4, but cannot see a due date of 2.2.4. We've recently upgraded to 2.2.3 and experienced this custom extension missing issue. Thanks a lot.

**Comment by joshiste** [comment]
@scramboy I'll try to publish the release tomorrow

**Comment by scramboy** [comment]
@joshiste sounds great, much appreciated!
