### ISSUE TITLE
Missing either interface contract or Delegate implementation of ApplicationRegistrator

### ISSUE THREAD

**Issue by bratwurzt** [codecentric/spring-boot-admin#1428]
Since all fields in ApplicationRegistrator are private, inheritance duplicates all code. I'd like to implement my own (where there's no discovery service) but am forced to duplicate *and* extend the class. I'd much rather use one of two patterns mentioned in the title.

**Comment by joshiste** [comment]
Sounds reasonable. I'd favor an interface - do you want to work on a PR for this?

**Comment by bratwurzt** [comment]
> 
> 
> Sounds reasonable. I'd favor an interface - do you want to work on a PR for this?

I'll make a PR, just wanted your feedback first. Will get to it around tomorrow, I hope.

**Comment by bratwurzt** [comment]
PR #1431
