### ISSUE TITLE
support custom?

### ISSUE THREAD

**Issue by lmx1989219** [codecentric/spring-boot-admin#143]
enterprise custom edition can be supported?
i according to my biz for write some chinese words via admin-ui.

**Comment by joshiste** [comment]
> enterprise custom edition can be supported?

I don't understand the question. What is "enterprise custom edition" and what exactly do you mean with "supported"?

**Comment by lmx1989219** [comment]
sorry,
eh... my english is not good.
actually i want to know how can i set some i want on admin-ui's page.
e.g:i want write some chinese words on web page,like enterprise's name,contact info and so on,.

**Comment by joshiste** [comment]
As said in the [FAQs](http://codecentric.github.io/spring-boot-admin/1.3.2/#faqs) customizing the UI is currently only possible via copying the spring-boot-admin-server-ui project and modifiying the files.

**Comment by lmx1989219** [comment]
thanks
