### ISSUE TITLE
Couldn't retrieve status for Instance

### ISSUE THREAD

**Issue by SingularityZed** [codecentric/spring-boot-admin#1436]
Hello, in the process of running sba,some monitored programs are offline, others are not.
Then these went online immediately.
## sba Event Journal message:
{
    "statusInfo": {
        "status": "OFFLINE",
        "details": {
            "exception": "java.io.IOException",
            "message": "Connection closed prematurely"
        }
    }
}

## Console log report:
Couldn't retrieve status for Instance  (id=f2831db9d766, version=38, ...

## then stacktrace is:
java.io.IOException: Connection closed prematurely

## info:
SpringBootAdmin: version 2.0.6
spring-cloud-alibaba:version: 2.0.0.RELEASE
Deployed on Alibaba Cloud

**Comment by joshiste** [comment]
1) There was no need to create a new issue - as you can continue the conversation regardless of the issue's status.
2) The error is still the same: The SBA server doesn't get a response from the service it wants to monitor. You need to check your network setup that the SBA server can reach the application which should be monitored.

**Comment by SingularityZed** [comment]
Thanks for the answer
