### ISSUE TITLE
Application Status DOWN when health check is up

### ISSUE THREAD

**Issue by AaronAWatters** [codecentric/spring-boot-admin#144]
I have an application whose /health endpoint is behind basic auth, after entering the correct credentials in the popup window I can now view the applications Health Check info in the Spring Boot Admin window however the applications status remains as DOWN.
![screen shot 2016-01-14 at 13 50 29](https://cloud.githubusercontent.com/assets/15693179/12325984/d94ec776-bac5-11e5-9536-fec02430c7fc.png)

**Comment by joshiste** [comment]
The health status is determined on the server-side, wich doesn't have the credentials. Therefore at least the status (without the details) must be available for unauthenticated access....
