### ISSUE TITLE
SBA Server doesn't work correctly with lazy-initialization enabled

### ISSUE THREAD

**Issue by Mr-LiuDC** [codecentric/spring-boot-admin#1444]
I plan to integrate eureka and Spring Boot Admin in the same project.

When I use `spring boot` version `2.1.14.RELEASE`, `spring boot admin` version `2.1.6` and `spring cloud` version `Greenwich.SR5` it works fine.

[![enter image description here][1]][1]

But when I use `spring boot` version `2.3.0.RELEASE`, `spring boot admin` version `2.2.3` and `spring cloud` version `Hoxton.SR4` the browser console got some error.

[![enter image description here][2]][2]

[![enter image description here][3]][3]

Here is the demo code.
[demo.zip](https://github.com/codecentric/spring-boot-admin/files/4705368/demo.zip)

  [1]: https://i.stack.imgur.com/lDmAr.png
  [2]: https://i.stack.imgur.com/JgJ13.png
  [3]: https://i.stack.imgur.com/pOGW3.png

**Comment by joshiste** [comment]
It looks like that not all beans are properly instantiated when using spring boots lazy initialization. For example the statusUpdateTrigger bean is missing. As a workaround please set `spring.main.lazy-initialization=false`
