### ISSUE TITLE
Timeout for defaulting log levels for services

### ISSUE THREAD

**Issue by halatas** [codecentric/spring-boot-admin#1449]
Would it be possible to have a setting to define a timeout, that when a log level is changed from default level, it will automatically send a request to service to change the changed setting back to default?

If not would it be possible for you to share some clues on how we can programatically extend the functionality to provide such a feature?

**Comment by joshiste** [comment]
Interesting idea.
Imho it would be better to have such a log level-timeout implemented in the spring boot actuator itself. 

We could implement it in SBA but that would need solutions to following problems:
1) If SBA is restarted when an timeout is outstanding it would need some kind of persistence
2) We'd need a retry mechanism in case the request to reset the loglevel fails.

I do think that this is a valuable feature. Imho you should open a feature request for spring boot. If they refuse to implement this, you could write a `@EndpointExtension` for the logging endpoint, which we could support from SBA.

**Comment by halatas** [comment]
You are absolutely right about state management and implementing it in actuator makes much more sense. I opened the issue https://github.com/spring-projects/spring-boot/issues/21740, and will try to implement an @EndpointExtension if evaluation is not positive.

**Comment by halatas** [comment]
@encircled created a merge request for springboot issue, could you check it out? It creates an endpoint to specify the timeout from API which İ think is excellent.

**Comment by SteKoe** [comment]
Closed due to inactivity. Feel free to reopen if issue still exists.
