### ISSUE TITLE
incorrect redirect using L4 loadbalancer + L7 Reverse Proxy

### ISSUE THREAD

**Issue by tuxknight** [codecentric/spring-boot-admin#1452]
When using a L4 loadbalancer before a L7 Reverse Proxy(Ingress) which listen to a different port ,  SpringBootAdmin always redirect request to http://sba.example.com:12900 .

After inspect network traffice to SpringBootAdmin, I noticed that there a HTTP Header called  X-Forwarded-Port in every request. So does SpringBootAdmin using X-Forwarded-Port in baseUrl and redirections ?

```
http://sba.example.com:80 ----> L4 LoadLalancer port:80 -----> Nginx Ingress port: 12900 ----> SpringBootAdmin port:9090
```

**Comment by joshiste** [comment]
please see https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server

**Comment by tuxknight** [comment]
thanks for you reply. I sovled this problem by add spring.boot.admin.ui.public-url. 
but it may be not a solution if there are  two or more domains  for diffenrent end users.

**Comment by joshiste** [comment]
the docs also say to set `server.forward-headers-strategy=native` which is disabled in spring boot by default (I guess due to security reasons)

**Comment by tuxknight** [comment]
thank you for your patient.
