### ISSUE TITLE
Custom views loss when context path setup

### ISSUE THREAD

**Issue by tooms4444** [codecentric/spring-boot-admin#1454]
I've been working on a custom view, based upon instances actuator's endpoints analysis, but I lost it when upgrading from 2.2.2 to 2.2.3 and deployed the application as a WAR into Tomcat.
Here is the case study: https://stackoverflow.com/questions/62331226/war-spring-boot-admin-custom-view-not-found/

To summarize, it turned out that spring-boot-admin-server-ui/src/main/frontend/index.html is reaching out view scripts through **absolute URLs**, without caring of context path (nor servlet, neither UI) which I changed to isolate the dashboard from other hosted functionalities. I thought you might want to consolidate my fix.

**Comment by joshiste** [comment]
looks like a duplicate to https://github.com/codecentric/spring-boot-admin/issues/1426 which is already fixed. Can you confirm this?

**Comment by tooms4444** [comment]
I couldn't find the 2.2.4-SNAPSHOT branch, but index.html has accordingly changed into 2.3.0-SNAPSHOT (master branch) and my test upon it succeeded indeed. So I guess that's fixed :-)
So thx
