### ISSUE TITLE
Differentiate for liveness/readiness with Spring Boot 2.3.x

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#1457]

**Comment by stevengibbszions** [comment]
@joshiste - interested in this for sure.  I can see how this would work when individual instances are registering back to SBAdmin.  However, when using k8s service discovery, we don't get to see the "not ready" endpoints, so we lose visibility altogether.

I commented on this [issue](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/584) over at spring-cloud-kubernetes to see if we could allow for seeing "bad" endpoints for a particular service.

Any other thoughts on how to solve the problem of not seeing "not ready" endpoints in SBAdmin?

**Comment by stevengibbszions** [comment]
@joshiste - I did PR over at spring-cloud-kubernetes to add not-ready endpoints and there's a discussion of whether it belongs in that library.  Would appreciate your thoughts if you have any. https://github.com/spring-cloud/spring-cloud-kubernetes/pull/673

**Comment by filpano** [comment]
Just a note: https://github.com/spring-cloud/spring-cloud-kubernetes/pull/673 was merged 12 days ago (21.01.2021).

**Comment by andreasfritz** [comment]
fixed with https://github.com/codecentric/spring-boot-admin/pull/2765
