### ISSUE TITLE
Python integration with Spring Boot Admin

### ISSUE THREAD

**Issue by MatanRubin** [codecentric/spring-boot-admin#1460]
Hi,
We've implemented the Spring Actuator API for various Python web frameworks (currently Flask and FastAPI), and we've integrated it with Spring Boot Admin (which is awesome, BTW). 

[Pyctuator](https://github.com/SolarEdgeTech/pyctuator) allows monitoring Python web applications using Spring Boot Admin, side by side with Java applications.

I wanted to share the project here in case you or other Spring Boot Admin users will find it interesting. 

We'd be happy to get some feedback on our project and collaborate on future enhancements to it.

P.S. If this is not the appropriate place to share this project with you, feel free to let me know where I should put it and close this issue.

**Comment by joshiste** [comment]
Do you want to make a PR and add it in the README.md in the root and also in the docs?

**Comment by MatanRubin** [comment]
Sure, will push something later today or tomorrow
