### ISSUE TITLE
Disk Space health indicator does not show up for SB 2.3.x applications 

### ISSUE THREAD

**Issue by sraveh** [codecentric/spring-boot-admin#1461]
when Using the latest release of spring-boot-admin (2.2.3)  server & client with spring-boot 2.3.1.RELEASE, the disk space health indicator no longer shows up under the Health section.
Spring boot actuator does return it as part of the health endpoint.
When using older version of spring boot on the client like 2.2.7.RELEASE,  does show the diskSpace section

**Comment by joshiste** [comment]
can you provide the json output from the health endpoint?

**Comment by sraveh** [comment]
{"status":"UP","components":{"db":{"status":"UP","details":{"database":"MariaDB","validationQuery":"isValid()"}},"discovery
Composite":{"description":"Discovery Client not initialized","status":"UNKNOWN","components":{"discoveryClient":{"descripti
on":"Discovery Client not initialized","status":"UNKNOWN"}}},"diskSpace":{"status":"UP","details":{"total":10726932480,"free":9564057600,"threshold":10485760,"exists":true}},"hystrix":{"status":"UP"},"livenessState":{"status":"UP"},"mongo":{"stat
us":"UP","details":{"version":"4.2.7"}},"ping":{"status":"UP"},"readinessState":{"status":"UP"},"refreshScope":{"status":"UP"}},"groups":["liveness","readiness"]}

**Comment by melkhazen** [comment]
any solution to this issue?

**Comment by erikpetzold** [comment]
Hi @melkhazen, 
from the ticket history it seems thet the bug was fixed in 2.2.4

if you still have issues, please provide more details (SBA client version, SBA server version, Spring Boot Version in your monitored app)
