### ISSUE TITLE
Client specific alert notification  

### ISSUE THREAD

**Issue by rvp-cpu** [codecentric/spring-boot-admin#1463]
SBA supports the multiple notification services and mail is one of the core services to notify the alerts. According to documentation we can enable and send emails using the following

```
spring.boot.admin.notify.mail.enabled = true
spring.boot.admin.notify.mail.to = example@example.com
```   
Now consider a use case where we have multiple client applications connected to SBA for application monitoring. Is it possible to configure application-specific mail alerts as following

```
spring.boot.admin.notify.mail.enabled.client1: true
spring.boot.admin.notify.mail.to.client1: client1@client1.com
spring.boot.admin.notify.mail.enabled.client2: true
spring.boot.admin.notify.mail.to.client2: client2@client2.com 
```

**Comment by joshiste** [comment]
@rvp-cpu as thy can get complex and everyone wants different rules, I'd suggest that you Subclass the `MailNotifier` and implement the routing you want.
