### ISSUE TITLE
integrate module for turbine/hystrix widget

### ISSUE THREAD

**Issue by cforce** [codecentric/spring-boot-admin#147]
It would be nice to have a "visual" integration of the turbine steam UI (if active).
How this could be achived : https://github.com/VanRoy/spring-cloud-dashboard
Howver i would like to see it as part of the spring boot admin app, just another feature.

**Comment by mrumpf** [comment]
There is a section in the Hystrix Wiki about embedding the dashboard functionaility into another dashboard:
https://github.com/Netflix/Hystrix/wiki/Dashboard#customizing-and-embedding
