### ISSUE TITLE
Can a release be made for Spring Boot 2.3.1?

### ISSUE THREAD

**Issue by ddcruver** [codecentric/spring-boot-admin#1470]
I see all the tickets for Spring Boot Admin have been closed for Spring Boot 2.3.0, including one that said it added Spring Boot 2.3.1 support.  Can a release be made?

If no yet fully tested could a milestone or alpha or something be released in the meantime?

**Comment by joshiste** [comment]
Did you find any incompatibility when using SBA 2.2.x with Spring Boot 2.3.1? If yes I'm glad to do a release - if not I'd like to postpone it a bit.

**Comment by ddcruver** [comment]
Actually I have not tried it yet. I know we had issues with the Spring Boot 2.2 update and we were required to wait for Spring Boot Admin to make a 2.2.x release until we could use it again. I just assumed it would be the same again.

**Comment by ambethell** [comment]
I experienced this issue with spring boot 2.3.1 - https://stackoverflow.com/questions/62655110/spring-boot-admin-too-many-open-files-in-system-error

**Comment by joshiste** [comment]
@ambethell this is a problem of Spring Boot and not Spring Boot Admin, see #1459

**Comment by joshiste** [comment]
SBA 2.3.0 is released.
