### ISSUE TITLE
Support Spring Cloud Gateways verbose actuator format

### ISSUE THREAD

**Issue by GianniGiglio** [codecentric/spring-boot-admin#1473]
** Bug report **
Using version 2.2.3 of spring-boot-admin.

When using spring-cloud-gateway the route definitions are not found.
The routes are detected but the definitions remain empty. 
-->
![Screen Shot 2020-07-06 at 16 38 56](https://user-images.githubusercontent.com/4160696/86605812-7913b600-bfa7-11ea-8fb6-4702aa304cec.png)

**Comment by joshiste** [comment]
could you provide the json response from the `gateway` endpoint?

**Comment by GianniGiglio** [comment]
> could you provide the json response from the `gateway` endpoint?

Sure see https://cloud.spring.io/spring-cloud-gateway/reference/html/#actuator-api where you see an example of the json returned
