### ISSUE TITLE
no response after login on openshift.

### ISSUE THREAD

**Issue by ggree1** [codecentric/spring-boot-admin#1474]
I'm not sure this is bug or not, but I need some help.

I'm using Spring boot admin server 2.2.3 with spring boot 2.2.5 and Eureka as service-discovery.

In local environment, boot-admin works fine as expected.

I published application to Openshift and

When accessing to boot-admin via openshift router which has public domain,

The login page shows OK.

The problem comes after logged-in.

The application is not going to the next page (/applications page.)

The browser is just white and looping again.

After long long looping, chrome console says,

...assets/js/sba-core.86dd6e42.js net::ERR_CONNECTION_RESET 200
I tried 'spring.boot.admin.ui.public-url' but symptom is the same.

after login success, AdminControllerHandlerMapping debug logs in local,
```
Mapped to de.codecentric.boot.admin.server.ui.web.UiController#index()
Mapped to de.codecentric.boot.admin.server.ui.web.UiController#sbaSettings()
Mapped to de.codecentric.boot.admin.server.web.ApplicationsController#applications()
Mapped to de.codecentric.boot.admin.server.web.ApplicationsController#applicationsStream()
```

but in Openshift,
```
Mapped to de.codecentric.boot.admin.server.ui.web.UiController#index()
Mapped to de.codecentric.boot.admin.server.ui.web.UiController#sbaSettings()
```
and no response. (/wallboard, /about ... all mappings are the same.)

How can I deal with this problem?
Is this could be Eureka related problem?

Any help would be greatly appreciated!

**Comment by ggree1** [comment]
Should the docker image used in Openshift have npm installed?  
Any idea?

**Comment by joshiste** [comment]
did you take the steps for [running behind a rev. proxy?](https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server)

> Should the docker image used in Openshift have npm installed?
no npm at runtime needed

**Comment by ggree1** [comment]
Thanks for reply.
Yes I already followed 'spring.boot.admin.ui.public-url' property and 'server.forward-headers-strategy' also.
In my case in Openshift,
(boot-admin openshift router > like k8s ingress :: http://boot-admin.example.com) -> (boot-admin k8s service) -> (boot-admin k8s pod)
I gave to 'spring.boot.admin.ui.public-url=http://boot-admin.example.com'
But result has been the same. (After login, the /applications page is not shown.)
It's very frustrating because I really want to use boot-admin ui.

**Comment by joshiste** [comment]
does your proxy set the `X-Forwarded-*` headers? Can you look into the dev tools network tab, which requests are made and why they fail?

**Comment by ggree1** [comment]
Thanks for the feedback.
There is no X-Forwarded-* header attached and no fails just not reach to /applications request, only end at /sba-settings.js request.
Here is request sources of /sbs-settings.js of my local env, and openshift and.

- Local
```
GET /sba-settings.js HTTP/1.1
Host: localhost:8700
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: script
Referer: http://localhost:8700/
Accept-Encoding: gzip, deflate, br
Accept-Language: ko,ko-KR;q=0.9,en-US;q=0.8,en;q=0.7,und;q=0.6
Cookie: XSRF-TOKEN=cb4a6afe-c5f3-4212-8b3d-873c3c1eef7b; JSESSIONID=F0E5BFB80A992B8737F1C1A6B17F50CD
```


- Openshift
```
GET /sba-settings.js HTTP/1.1
Host: dev-server-boot-admin-ptl-dev.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Accept: */*
Referer: http://dev-server-boot-admin-ptl-dev.com/
Accept-Encoding: gzip, deflate
Accept-Language: ko,ko-KR;q=0.9,en-US;q=0.8,en;q=0.7,und;q=0.6
Cookie: f23104c733d96169488e6aa6b9e47825=760ebc9b4676a0a03069d23486df4895; JSESSIONID=DB9788B1BFF2EB55818BC28D2D523D65
```


I guess the only difference is the Cookie part that shows XSRF-TOKEN which is encrypted in request toOpenshift..
Could that be a problem..?

Anyway I'll upgrade Openshift and look into our firewall policy.
After that I'll leave a comment.
Thanks!

**Comment by joshiste** [comment]
what does the responses look like?

**Comment by joshiste** [comment]
closed due to missing feedback
