### ISSUE TITLE
t.$ is not a function

### ISSUE THREAD

**Issue by missfmaster** [codecentric/spring-boot-admin#1479]
I don't know why...
It's just a test to be used for the first time...
![image](https://user-images.githubusercontent.com/13460299/88062825-e7f23100-cb9b-11ea-9f87-1280eda5169b.png)
spring-boot-admin-starter-server  2.2.3
spring boot 2.2.5.RELEASE

**Comment by missfmaster** [comment]
`
             <dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-server</artifactId>
			<version>2.2.3</version>
		</dependency>
`
spring boot 2.2.5.RELEASE

**Comment by joshiste** [comment]
which browser version? can you provide a sample project to reproduce the error?

**Comment by missfmaster** [comment]
@joshiste how do you do.
The browser is Chrome version 84.0.4147.89 (official version) (64-bit).
This does not seem to affect the work...
![image](https://user-images.githubusercontent.com/13460299/88071661-b16de380-cba6-11ea-9630-d9ebaa76d008.png)

**Comment by joshiste** [comment]
can't reproduce this using our sample (https://repo1.maven.org/maven2/de/codecentric/spring-boot-admin-sample-servlet/2.2.3/spring-boot-admin-sample-servlet-2.2.3.jar).

Please retry using a cleared browser cache. Do you use any custom UI view?

**Comment by missfmaster** [comment]
yes. the spring-boot-admin-sample-servlet-2.2.3.jar is ok.
I have cleaned up the browser cache, no any custom UI.
maybe it's no big deal...
