### ISSUE TITLE
Add proxy authentication support for notifications

### ISSUE THREAD

**Issue by karsunke** [codecentric/spring-boot-admin#1480]
There is no way to add credentials (user/password) for the notification proxy settings. If spring boot admin runs in a environment which only can access the internet via authenticated proxy, the notifications are not working.

Resttemplate is created here (no way to inject or overwrite it): https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerNotifierAutoConfiguration.java
and here:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/NotifierProxyProperties.java

Also this documentation has to be updated, when the feature is implemented:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-docs/src/main/asciidoc/server-notifications.adoc

As long as there are no objections, I would try to implement it myself (by adding 2 properties for user and password) and create a pull request tomorrow.

**Comment by joshiste** [comment]
closed in favor of PR #1482
