### ISSUE TITLE
Add mechanism to control word wrap on log viewer

### ISSUE THREAD

**Issue by SledgeHammer01** [codecentric/spring-boot-admin#1481]
Can you add some config property to control whether the log viewer wraps the text or not? Right now it doesn't even wrap on a word-break, it just wraps at a char position. Makes it kind of hard to read. No wrapper + horizontal scroll bar would be nicer imo.

**Comment by joshiste** [comment]
wanna go for a PR?

**Comment by SledgeHammer01** [comment]
> wanna go for a PR?

Unfortunately not familiar with web ui. I'm a back end guy.
