### ISSUE TITLE
`spring.boot.admin.client.instance.name` in nacos. Not applied

### ISSUE THREAD

**Issue by lshz0088** [codecentric/spring-boot-admin#1484]
I used the Nacos registry and configured it on the client side `spring.boot.admin.client.instance.name`

However, the instance name is not applied

![image](https://user-images.githubusercontent.com/27722002/89013859-385d5180-d347-11ea-8c19-95dc0aeea47d.png)
![image](https://user-images.githubusercontent.com/27722002/89013918-51fe9900-d347-11ea-93e9-467ddd767412.png)

**Comment by lshz0088** [comment]
I wonder if it is not used when fetching configuration information

**Comment by joshiste** [comment]
The property only has an effect when you are using the sba-client to register the applications. As you are using nacos, you have to configure the instance name in nacos.
