### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by wanghwtaiji** [codecentric/spring-boot-admin#1497]
2.2.2admin and 2.3.1 spring boot + consult error couldn't retrieve status for instance io.netty.channel . unix.Errors $NativeIoException: newSocketStream(..) failed: Too many open files

**Comment by wanghwtaiji** [comment]
After running for a period of time, the above error will appear in admin, and couldn't retrieve status for instance will appear

**Comment by SteKoe** [comment]
Sounds like a duplicate of this one https://github.com/spring-projects/spring-boot/issues/21923. Could you please verify reactor-netty version is >= 0.9.9.RELEASE and also consider upgrading to Spring Boot 2.3.2 since they seem to have included a fix for this issue.

**Comment by joshiste** [comment]
duplicate of #1459
