### ISSUE TITLE
Feature: Add support for Spring Boot Chaos Monkey endpoints

### ISSUE THREAD

**Issue by rkettelerij** [codecentric/spring-boot-admin#1499]
You are probably aware of the [Chaos Monkey for Spring Boot](https://github.com/codecentric/chaos-monkey-spring-boot) project 😉. As far as I know the latter doesn't have a user interface but it does provide [actuator endpoints](https://codecentric.github.io/chaos-monkey-spring-boot/2.2.0/#_http_endpoint). Wouldn't it make sense to provide a UI on top of these endpoints in Spring Boot Admin? Seems like a nice integration between both projects.

**Comment by joshiste** [comment]
> Wouldn't it make sense to provide a UI on top of these endpoints in Spring Boot Admin? Seems like a nice integration between both projects.

yep. But from my perspective the UI should be provided by an SBA UI extension residing in the CM4SB repository as it is tied to their endpoints - also I'm laking the time to work on it.
