### ISSUE TITLE
Spring Boot Admin： Socket accept failed java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by messiGao** [codecentric/spring-boot-admin#1503]
<!--
Thanks for raising a Spring Boot Admin issue. Please take the time to review the following
categories as some of them do not apply here.

** Question **
When I upgrade springboot version and spring-boot-admin-starter-server version,I found that  springboot admin application socket connection can not release。

** Bug report **
old version：springboot_version=2.1.13.RELEASE     new version： springboot_version=2.2.8.RELEASE
old version：de.codecentric:spring-boot-admin-starter-server:2.1.1      new version： 2.2.3

2020-09-02 10:13:33,345 ERROR http-nio2-0.0.0.0-8788-exec-700 Nio2Endpoint.log(DirectJDKLog.java:175) - Socket accept failed
java.io.IOException: Too many open files
        at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_152]
        at sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.accept(UnixAsynchronousServerSocketChannelImpl.java:344) ~

**Comment by messiGao** [comment]
** Question **
When I upgrade springboot version and spring-boot-admin-starter-server version,I found that  springboot admin application socket connection can not release。

** Bug report **
old version：springboot_version=2.1.13.RELEASE     new version： springboot_version=2.2.8.RELEASE
old version：de.codecentric:spring-boot-admin-starter-server:2.1.1      new version： 2.2.3

**Comment by joshiste** [comment]
duplicate of #1459
