### ISSUE TITLE
Guide kubernetes users to use @EnableScheduling to the main application class in Spring Boot Admin documentation.

### ISSUE THREAD

**Issue by Ayden-Franklin** [codecentric/spring-boot-admin#1506]
**Enhancement**
I found when the admin server starts up it finds the list of running applications and monitors their health status, but it does not know of any new instances that are started. Described by #643
I suggest to guide kubernetes users to use `@EnableScheduling` on the main application class in `Spring Boot Admin` documentation in [**Spring Cloud Discovery** Section](https://codecentric.github.io/spring-boot-admin/current/#discover-clients-via-spring-cloud-discovery).

**Comment by joshiste** [comment]
Do you want to do a PR on our docs?

**Comment by Macrame** [comment]
I'd like to do that. I plan to commit in the next week as I'm quite busy these days.

**Comment by patpatpat123** [comment]
Many thanks @Ayden-Franklin

**Comment by davidkarlsen** [comment]
Should this be closed?
