### ISSUE TITLE
Spring boot actuator doesn't set default port 8080 for endpoints with "preferIp:true"

### ISSUE THREAD

**Issue by IliaEre** [codecentric/spring-boot-admin#1507]
Hi!

I have some problems with spring boot application and actuator.
I decided to use IP addresses for boot-services and SBA. (for me it's good point and so comfortable).
Main task is giving endpoints IP:port.

So, my yml properties here:
```
management:
  port: 8080
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      client:
        url: http://spring-admin:8080/
        auto-deregistration: true
        instance:
          preferIp: true
`

I used the base starter:

`implementation("org.springframework.boot:spring-boot-starter-actuator")`

Base endpoints for SBA have IP:port and it's ok.

But actuator endpoints don't have port.
request:
`curl http://0.0.0.1:8080/actuator`
response:
`
{"_links":{"self":{"href":"http://0.0.0.1/actuator","templated":false},"beans":{"href":"http://0.0.0.1/actuator/beans","templated":false},"caches-cache":{"href":"http://0.0.0.1/actuator/caches/{cache}","templated":true},"caches":{"href":"http://0.0.0.1/actuator/caches","templated":false},"health":{"href":"http://0.0.0.1/actuator/health","templated":false},"health-path":{"href":"http://0.0.0.1/actuator/health/{*path}","templated":true},
"info":{"href":"http://0.0.0.1/actuator/info","templated":false},
…
```
It works if I use different port - 8081 and etc, but I must use only 8080.

Versions:
spring boot: 2.3.3
build: Gradle KTS
dependency-manager: 1.0.10
Kotlin version: 1.4.0
Java project version: 11
Spring cloud version: Hoxton.SR8

How I can solve this case? How I can set 8080 port for actuator endpoints?
I would appreciate your immediate attention to this matter.
Have a nice day!

(Spring boot issue: https://github.com/spring-projects/spring-boot/issues/23220)

**Comment by joshiste** [comment]
if you omit the `management.port` from your config the actuator should automatically use the  `server.port`

**Comment by IliaEre** [comment]
@joshiste I tried, but it didn't work for me.

my properties now:
`management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
`

**Comment by IliaEre** [comment]
And I tried to add server.port properties....
