### ISSUE TITLE
2.3.0 ignoring external view's configured URLs

### ISSUE THREAD

**Issue by gigermocas** [codecentric/spring-boot-admin#1508]
After [#1469](https://github.com/codecentric/spring-boot-admin/issues/1469) was fixed, indeed all the external views are showing, but the actual configured URLs are being ignored, the actual links in the UI are the boot admin's own context path.

Versions 2.2.4 and 2.3.0 display the same behavior, version 2.2.2 is latest that works as intended.

Application properties used:

```
spring.boot.admin.ui.external-views[0].label=Eureka
spring.boot.admin.ui.external-views[0].url=http://${server.address:localhost}:${server.port}
spring.boot.admin.ui.external-views[0].order=2000

spring.boot.admin.ui.external-views[1].label=RabbitMQ
spring.boot.admin.ui.external-views[1].url=http://${server.address:localhost}:15672
spring.boot.admin.ui.external-views[1].order=3000

spring.boot.admin.ui.external-views[2].label=Zipkin
spring.boot.admin.ui.external-views[2].url=http://${server.address:localhost}:9411
spring.boot.admin.ui.external-views[2].order=4000

spring.boot.admin.ui.external-views[3].label=Prometheus
spring.boot.admin.ui.external-views[3].url=http://${server.address:localhost}:9090
spring.boot.admin.ui.external-views[3].order=5000

spring.boot.admin.ui.external-views[4].label=Grafana
spring.boot.admin.ui.external-views[4].url=http://${server.address:localhost}:3000
spring.boot.admin.ui.external-views[4].order=6000
```

Sample application is the same as the previous issue's, but updated to latest spring boot admin (2.3.0) and spring boot (2.3.3) versions.
[demo.zip](https://github.com/codecentric/spring-boot-admin/files/5187668/demo.zip)

**Comment by michael-wirth** [comment]
I'm having the same issue

**Comment by darrell-rg** [comment]
I am seeing the same issue here
