### ISSUE TITLE
CSRF support

### ISSUE THREAD

**Issue by SledgeHammer01** [codecentric/spring-boot-admin#1511]
Hi, regarding issue #1509 that you closed this morning, in reviewing, sorry I wasn't clear, the "csrf token has been associated to this client" error is occurring when I try to logon through the UI with:

```
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-server</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-server-ui-login</artifactId>
			<version>1.5.7</version>
		</dependency>
```

The csrf check is actually failing on the root /, /favicon.ico paths. Doesn't appear to be hitting the instances/actuator, etc. paths yet before rejecting as those didn't come into the matcher.

The UI does of course work if I disable csrf entirely and it worked in webmvc with the configuration I mentioned in #1509.

**Comment by joshiste** [comment]
> regarding issue #1509 that you closed this morning

no need to open a new issue. Next time please continue the discussion in the original issue (also possible for closed issues)


since SBA 2.x there is no need for the extra `spring-boot-admin-server-ui-login` module.

**Comment by SledgeHammer01** [comment]
Ok, no problem...

I removed the server-ui-login as recommended. My security config looks like:

	@Bean
	public SecurityWebFilterChain securityWebFilterChainSecure(ServerHttpSecurity http) {
		return http
			.authorizeExchange(authorizeExchange -> authorizeExchange
				.pathMatchers(this.adminServerProperties.path("/assets/**")).permitAll()
				.pathMatchers(this.adminServerProperties.path("/login")).permitAll()
				.anyExchange().authenticated())
			.formLogin(formLogin -> formLogin.loginPage(this.adminServerProperties.path("/login")))
			.logout(logout -> logout.logoutUrl(this.adminServerProperties.path("/logout")))
			.httpBasic(Customizer.withDefaults())
			.csrf()
				.csrfTokenRepository(CookieServerCsrfTokenRepository.withHttpOnlyFalse())
				.requireCsrfProtectionMatcher(x -> {
					System.out.println(x.getRequest().getPath());
					return MatchResult.match();
				})
				.and()
			.build();
	}

Haven't really been able to find an example of the correct way to ignore multiple paths in webflux for csrf, but the above was just dumping out the paths for testing. It's failing in the UI on the login dialog and giving me the "csrf token has been associated to this client" for / and /favicon.ico so it doesn't seem to be getting to the other paths before giving me the error.

**Comment by joshiste** [comment]
You forgot to specify the http verbs in your matcher. By default only PUT, POST and DELETE are considered - see javadoc of requireCsrfProtectionMatcher

**Comment by SledgeHammer01** [comment]
> You forgot to specify the http verbs in your matcher. By only PUT, POST and DELETE should be considered - see javadoc of requireCsrfProtectionMatcher

As its a NegatedServerWebExchangeMatcher, adding specific verbs would make csrf stricter, not looser. Also, as mentioned, it never even gets to those paths. "/instances", "instances/*", "/actuator/**" is never even hit, the csrf protection immediately rejects the request at the root /.

**Comment by joshiste** [comment]
If i get your configuration right. You request the CSRF protection for all requests except to "/instances", "instances/*", "/actuator/**". This means you request it for any other request which includes GET requests!

**Comment by joshiste** [comment]
you should do something like 
```

.requireCsrfProtectionMatcher(
  new AndServerWebExchangeMatcher(
    CsrfWebFilter.DEFAULT_CSRF_MATCHER,
    new NegatedServerWebExchangeMatcher(ServerWebExchangeMatchers.pathMatchers("/instances", "instances/*", "/actuator/**"))));
```

(just scratched - not tested)

**Comment by SledgeHammer01** [comment]
> If i get your configuration right. You request the CSRF protection for all requests except to "/instances", "instances/*", "/actuator/**". This means you request it for any other request, which includes GET requests! (including root)

@joshiste Correct. I want the tightest / strongest possible protection & security due to corp requirements.

**Comment by SledgeHammer01** [comment]
> you should do something like
> 
> ```
> 
> .requireCsrfProtectionMatcher(
>   new AndServerWebExchangeMatcher(
>     CsrfWebFilter.DEFAULT_CSRF_MATCHER,
>     new NegatedServerWebExchangeMatcher(ServerWebExchangeMatchers.pathMatchers("/instances", "instances/*", "/actuator/**"))
>     )
>   );
> ```
> 
> (just scratched - not tested)

I have updated to:

	@Bean
	public SecurityWebFilterChain securityWebFilterChainSecure(ServerHttpSecurity http) {
		return http
			.authorizeExchange(authorizeExchange -> authorizeExchange
				.pathMatchers(this.adminServerProperties.path("/assets/**")).permitAll()
				.pathMatchers(this.adminServerProperties.path("/login")).permitAll()
				.anyExchange().authenticated())
			.formLogin(formLogin -> formLogin.loginPage(this.adminServerProperties.path("/login")))
			.logout(logout -> logout.logoutUrl(this.adminServerProperties.path("/logout")))
			.httpBasic(Customizer.withDefaults())
			.csrf().requireCsrfProtectionMatcher(
					  new AndServerWebExchangeMatcher(
					    CsrfWebFilter.DEFAULT_CSRF_MATCHER,
					    new NegatedServerWebExchangeMatcher(ServerWebExchangeMatchers.pathMatchers("/instances", "instances/*", "/actuator/**"))))
			.and()
			.build();
	}

Still see the same issue during the login: "CSRF Token has been associated to this client". The browser is showing the error on: https://xxx.xxx.com:6413/login

Not sure if this has anything to do with it, but another corp security requirement is https (self signed cert) + TLSv1.2. Was all working with WebMvc with the CSRF configured how you described, but Webflux is giving the CSRF issue.

**Comment by joshiste** [comment]
May be there is a problem with the token not being included. Does the form in the login page have a hidden input field with the csrf token set? If not I guess the token is not included see https://docs.spring.io/spring-security/site/docs/5.4.0/reference/html5/#webflux-csrf-include

**Comment by SledgeHammer01** [comment]
> May be there is a problem with the token not being included. Does the form in the login page have a hidden input field with the csrf token set? If not I guess the token is not included see https://docs.spring.io/spring-security/site/docs/5.4.0/reference/html5/#webflux-csrf-include

When I remove the thymeleaf patch dependency, the html for the logon page looks like:

Spring Boot Admin</h1><form method=post><div class=field></div>

If I have the thymeleaf patch:

Spring Boot Admin</h1><form method=post><input type=hidden name=_csrf value=59356817-9076-4051-9cae-42e7bf447b88><div class=field></div>

So it seems to be missing on the Webflux page at least. I don't have my WebMvc version to test against anymore.

If I manually add that SecurityControllerAdvice, it puts the csrf token in there too without the Thymeleaf patch.

Might be good to add that to Admin so it works out of the box :).
