### ISSUE TITLE
Metadata will lost

### ISSUE THREAD

**Issue by HaojunRen** [codecentric/spring-boot-admin#1512]
** Bug report **
Metadata will lost, but after some time, it will be back. Then lost, and back. Refer to following pictures
![图片](https://user-images.githubusercontent.com/42354711/92933342-bf3e3780-f478-11ea-8ca1-8a4c29196feb.png)
![图片](https://user-images.githubusercontent.com/42354711/92933479-e09f2380-f478-11ea-8ea9-480d2ff81c72.png)

Spring Boot 2.3.3 with Spring Boot Admin 2.3.0

**Comment by joshiste** [comment]
looks to me that you are using SBA client and nacos service discovery. You must only use one of them. You must not use both of them.
