### ISSUE TITLE
Title for custom tab with multiple views is not displayed correctly

### ISSUE THREAD

**Issue by pgouri017** [codecentric/spring-boot-admin#1514]
Hi,

I’m having issue with custom tab title display after upgrading my application to spring boot admin version 2.2.4.

I have added a custom tab in sidebar with multiple views. 
```
SBA.use({
  install({viewRegistry}) {
    viewRegistry.addView({
      name: "instances/sd/account",
      parent: "instances",
      path: "sd/account",
      component: account,
      label: "Account",
      group: 'Solutions DevOps',
      order: 1000,
      isEnabled: ({instance}) => instance.hasEndpoint('sd')
    }),
    viewRegistry.addView({
      name: "instances/sd/test”,
      parent: "instances",
      path: "sd/test”,
      component: test,
      label: “Test”,
      group: 'Solutions DevOps',
      isEnabled: ({instance}) => instance.hasEndpoint('sd')
     }),
     viewRegistry.addView({
       name: "instances/sd/operation,
       parent: "instances",
       path: "sd/operation,
       component: operation,
       label: “Operation",
       group: 'Solutions DevOps',
       isEnabled: ({instance}) => instance.hasEndpoint('sd')
     });
  }
});
```

Prior to spring boot admin version update it was correctly displaying the title “**Solutions DevOps**” in sidebar. After version upgrade, title is displayed as "**sidebar.Solutions DevOps.title**"

<img width="160" alt="image" src="https://user-images.githubusercontent.com/8127574/93256866-045cb500-f76a-11ea-870e-367e05249d36.png">

In the spring boot admin ui source code, I have noticed a change in sidebar.vue for groups with multiple views

v-text="hasMultipleViews(group) ? **$t('sidebar.' + group.id + '.title')** : ($t(group.views[0].label))"

Could you please help to fix the title display issue?

 Thanks

**Comment by joshiste** [comment]
the install method get's the `vueI18n` passed in. You have to register a translation there under the key `sidebar.<groupId>.title`. We use `vue-i18n`  in case you need to lookup the api. Currently our samples are lacking this, but it would be good if we'd add this.
