### ISSUE TITLE
SBA can't discover other services

### ISSUE THREAD

**Issue by zhangbin1010** [codecentric/spring-boot-admin#1515]
Environment:
Spring Boot 2.3.3.RELEASE
Spring Cloud Hoxton.SR8
Spring Cloud Alibaba 2.2.2.RELEASE
Nacos 1.3.2

Spring Boot Admin 2.3.0

Start SBA first, and then start other services, but the web page always shows a service (SBA)
![image](https://user-images.githubusercontent.com/32190984/93295840-8c9d9180-f820-11ea-9f53-f028c99e3405.png)

**Comment by joshiste** [comment]
I guess the discovery is not setup properly but this is hard to tell from just having a bunch of versions and a screenshot. Could you provide a complete sample project to reproduce the issue?

**Comment by zhangbin1010** [comment]
It has been solved. This is the problem of Spring Cloud Alibaba.
Thank you for your attention.
https://github.com/alibaba/spring-cloud-alibaba/issues/1731
