### ISSUE TITLE
How to import Vuex or eventBus.js file in index.js file?

### ISSUE THREAD

**Issue by kormosp** [codecentric/spring-boot-admin#1516]
I have to develop the communication  between my Vue components, either with Vuex state management or with eventBus, but I cannot import the proper *.js file in my index.js. 
Vuex has already been installed with npm.

I tried something like this:
//**********************************************************************
**store.js:**
```
import Vue from 'vue';
import Vuex from 'vuex';
Vue.use(Vuex);
export const store = new Vuex.Store({
    state: {
        status: []
    }
});
```
//**********************************************************************
**index.js:**

```
import Vuex from 'vuex';
import store from './store/store'


SBA.use({
  install({vue}) {
    vue.use(Vuex)
  }
})

SBA.use({
  install({Vuex}) {
    Vuex.use(store)
  }
})

```
//**********************************************************************
I get the following error:
```
store.js: Uncaught TypeError: Cannot read property 'use' of undefined
    at eval (store.js:8)
    at Module../src/store/store.js (custom.js:1811)
```

OR after some modification:
**Uncaught Error: [vuex] must call Vue.use(Vuex) before creating a store instance**

I also tried to this, but nothing worked nothing worked:
```
import Vuex from 'vuex';
import store from './store/store'

SBA.use({
  install({viewRegistry,vue}) {
    vue.use(Vuex);
    vue.use(store);
    viewRegistry.addView({
      name:   'instances/custom',
      parent: 'instances',
      path:   'custom',
      component: customEndpoint,
      label: 'something',
      group: 'Group',
      order: -10,                   // Orig: 1000
      isEnabled: ({instance}) => instance.hasEndpoint('custom')
    });
  }
});
```

How shall I import *.js files properly?
Thank you for the help!

**Comment by joshiste** [comment]
the `Vue.use` in the store.js is the problem you should remove this and you also need to move the creation of the store into the `install` callback.

**Comment by kormosp** [comment]
> the `Vue.use` in the store.js is the problem you should remove this and you also need to move the creation of the store into the `install` callback.

Thanks 
I tried it, but I get the following error on console:
"Uncaught Error: [vuex] must call Vue.use(Vuex) before creating a store instance.
    at assert (vuex.esm.js:144)
    at new Store (vuex.esm.js:385)
    at eval (index.js:52)
   ..."

I tried this:

```
import Vuex from 'vuex';

export const store = new Vuex.Store({
  state: {
    status: [{streamName: '', streamState: []}]
  }
});

SBA.use({
  install({viewRegistry,vue}) {
    vue.use(Vuex);
    vue.use(store);
    viewRegistry.addView({
      name:   'instances/custom',
      parent: 'instances',
      path:   'custom',
      component: customEndpoint,
      label: 'GSLA-Cloud Streams',
      group: 'Group',
      order: -10,                   // Orig: 1000
      isEnabled: ({instance}) => instance.hasEndpoint('custom')
    });
  }
});
```

I do not undserstand, what is missing?

**Comment by joshiste** [comment]
you need to instantiate the store in the install method.
You could turn the store into a promise and resolve it in the install method:

(UNTESTED)

```
export const store = new Promise(resolve => {
    SBA.use({
        install({viewRegistry, vue}) {
            vue.use(Vuex);

            const store = new Vuex.Store({
                state: {
                    status: [{streamName: '', streamState: []}]
                }
            });

            vue.use(store);
            viewRegistry.addView({
                name: 'instances/custom',
                parent: 'instances',
                path: 'custom',
                component: customEndpoint,
                label: 'GSLA-Cloud Streams',
                group: 'Group',
                order: -10,                   // Orig: 1000
                isEnabled: ({instance}) => instance.hasEndpoint('custom')
            });

            resolve(store)
        }
    });
});
```

**Comment by kormosp** [comment]
> export const store = new Promise(resolve => {
>     SBA.use({
>         install({viewRegistry, vue}) {
>           vue.use(Vuex);
>
>           const store = new Vuex.Store({
>                state: {
>                    status: [{streamName: '', streamState: []}]
>                }
>            });
>          vue.use(store);
> ...
>             resolve(store)
>         }
>     });
> });


Thanks for the quick response. Unfortunately 
when I try to read the value from store (or write ) 

```
computed: {
       statusStore() {
                return this.$store.state.status;
            }
        },
```

I get the error of:
```
 TypeError: Cannot read property 'state' of undefined
    at a.counter (...)
```

**Comment by kormosp** [comment]
Hi Johannes,
I could not solve this problem. 
I have to use either the VUEX or an EventBus in my project, but none of them seems to work.
Can you please give some hint what could be the error here?
With Eventbus I get the error: 
_`Uncaught TypeError: vue__WEBPACK_IMPORTED_MODULE_10___default.a is not a constructor`_

```
import VueRx from 'vue-rx'
**import Vue from 'vue';** // The same error without this import

SBA.use({
  install({viewRegistry,vue}) {
    **const eventBus = new Vue();
    vue.use(eventBus);**

    vue.use(VueRx);
    vue.config.devtools = true;
    viewRegistry.addView({
      name:   'instances/custom',
      parent: 'instances',
      path:   'custom',
      component: customEndpoint,
      label: 'GSLA-Cloud Streams',
      group: 'Group',
      order: -10,                   
      isEnabled: ({instance}) => instance.hasEndpoint('custom')
    });
  }
});
```
 
With VUEX I get the error when accessing the vuex store:
`vue.runtime.esm.js:1888 TypeError: Cannot read property 'state' of undefined`
    
I tried to access it with:
```
computed: {
       statusStore() {
                return this.$store.state.status;
               // and also with
              //  return mystore2.store.state.status;
            }
        },
```

```
**import Vuex from 'vuex';**

export const myStore = new Promise(resolve => {
  SBA.use({
    install({viewRegistry, vue}) {
      **vue.use(Vuex);
      const store = new Vuex.Store({
        state: {
          status: [{streamName: '', streamState: []}]
        }
      });
      vue.use(store);**

      viewRegistry.addView({
        name: 'instances/custom',
        parent: 'instances',
        path: 'custom',
        component: customEndpoint,
        label: 'GSLA-Cloud Streams',
        group: 'Group',
        order: -10,                  
        isEnabled: ({instance}) => instance.hasEndpoint('custom')
      });

      **resolve(store);**
    }
  });
});
```

**Comment by joshiste** [comment]
do you have a sample project for me to play around with?

**Comment by SteKoe** [comment]
Closed due to inacivity.
