### ISSUE TITLE
Mixed Content: The page at ‘https://XXX’ was loaded over HTTPS

### ISSUE THREAD

**Issue by silenyc** [codecentric/spring-boot-admin#1518]
Mixed Content: The page at 'https://xx/' was loaded over HTTPS, but requested an insecure stylesheet 'http://xx/assets/css/sba-core.80e2ff1d.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by joshiste** [comment]
Sorry but this is too limited information to reproduce? Which version are you using? Is it running behind some proxy or does the SBA server itself do the TLS encryption? 

At best you provide a sample project to reproduce the issue.

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by zxiaozhou** [comment]
@silenyc 
1. nginx add :proxy_set_header  X-Forwarded-Proto $scheme;
2. application.yml: server.forward-headers-strategy:framework or server.use-forward-headers=true(The latest edition is out of date)
