### ISSUE TITLE
Http traces not working when it contains ongoing request without response

### ISSUE THREAD

**Issue by arbing** [codecentric/spring-boot-admin#1519]
browser console output:
> vue.runtime.esm.js:1888 TypeError: Cannot read property 'status' of null
>     at traces-list.vue?2892:1
>     at o.Pe [as _l] (vue.runtime.esm.js:2630)
>     at o.L (traces-list.vue?2892:1)
>     at o.t._render (vue.runtime.esm.js:3548)
>     at o.r (vue.runtime.esm.js:4066)
>     at nr.get (vue.runtime.esm.js:4479)
>     at nr.run (vue.runtime.esm.js:4554)
>     at Xn (vue.runtime.esm.js:4310)
>     at Array.<anonymous> (vue.runtime.esm.js:1980)
>     at ce (vue.runtime.esm.js:1906)

source code:
![image](https://user-images.githubusercontent.com/687757/95653941-fd3d8280-0b2e-11eb-81d6-61197d21fc7e.png)

> https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/httptrace/traces-list.vue#L49

Spring Boot Admin: 2.3.0
Spring Boot: 2.3.4.RELEASE

**Comment by joshiste** [comment]
can you show me the output from the traces endpoint for this single request?

**Comment by arbing** [comment]
```json
{
  "traces": [
    {
      "timestamp": "2020-10-19T14:43:30.374Z",
      "principal": null,
      "session": null,
      "request": {
        "method": "POST",
        "uri": "http://10.2.253.215/receive_ticket",
        "headers": {
          "x-real-ip": ["127.0.0.1"],
          "x-forward-for": ["127.0.0.1"],
          "remote-host": ["127.0.0.1"],
          "content-length": ["571"],
          "host": ["10.2.253.215"],
          "connection": ["close"],
          "content-type": ["text/xml"],
          "pragma": ["no-cache"],
          "accept": ["*/*"],
          "user-agent": ["Mozilla/4.0"]
        },
        "remoteAddress": null
      },
      "response": null,
      "timeTaken": null
    }
  ]
}
```
