### ISSUE TITLE
FilteringNotifier is calling its filter method twice every time

### ISSUE THREAD

**Issue by karsunke** [codecentric/spring-boot-admin#1523]
AbstractEventNotifier calls `shouldNotify` method before notifying. 
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/AbstractEventNotifier.java#L51

This `shouldNotify` calls the filter method of FilterNotifier.
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/filter/FilteringNotifier.java#L66

After that AbstractEventNotifier calls `doNotify`
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/AbstractEventNotifier.java#L52

Which also calls the filter method:
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/filter/FilteringNotifier.java#L71

Is this behaviour wanted or should we remove the filter check in `doNotify` of FilteringNotifier? At least I stumbled accross this and was wondering why the filter was called twice everytime.

**Comment by joshiste** [comment]
.. yeah I guess it's not necessary to call it twice ... do you want to submit a PR to fix this?

**Comment by karsunke** [comment]
I created the PR :+1:
