### ISSUE TITLE
401 Unauthorized when using instance-auth.default-user-name 

### ISSUE THREAD

**Issue by membersound** [codecentric/spring-boot-admin#1525]
I tried removing `spring.boot.admin.client.instance.metadata.*` in favor or `spring.boot.admin.instance-auth.default-user-name` (same for the password property).

But what happens is that when a client registers at SBA, it still sends `metadata` automatically generated like the `startup` datetime:
```
{"name":"my webservice","managementUrl":"http://localhost:8081/actuator","healthUrl":"http://localhost:8081/actuator/health","serviceUrl":"http://localhost:8081/","metadata":{"startup":"2020-10-27T15:46:55.677337+01:00"}}]
```
As the `BasicAuthHttpHeaderProvider` reads directly from the metadata, it does not find username/password, and thus prepared `HttpHeaders` are empty. Resulting in `401` for protected admin-clients.

I noticed the following difference:

 `spring-boot-admin-server2.3.0-sources.jar`:
```
public class BasicAuthHttpHeaderProvider {
	@Override
	public HttpHeaders getHeaders(Instance instance) {
		String username = getMetadataValue(instance, USERNAME_KEYS);
		String password = getMetadataValue(instance, PASSWORD_KEYS);

		HttpHeaders headers = new HttpHeaders();
		if (StringUtils.hasText(username) && StringUtils.hasText(password)) {
			headers.set(HttpHeaders.AUTHORIZATION, encode(username, password));
		}
		return headers;
	}
}
```

Compare this to:
https://github.com/codecentric/spring-boot-admin/blob/40eeb164b293d71827142ba480ce2ba1af8bc00c/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/BasicAuthHttpHeaderProvider.java

```
...
                       if(credentials != null) {
				username = credentials.getUserName();
				password = credentials.getUserPassword();
			}
			else {
				username = this.defaultUserName;
				password = this.defaultPassword;
			}
...
```

So probably this is a feature mismatch: the online docs state the property could already be used, but the change was introduced on 13. Aug, while the 2.3.0 release is from 09. Aug.

I think the docs should always reflect the release-state feature, not the trunk-state.

**Comment by joshiste** [comment]
which docs are you referring to??

SNAPSHOT:   https://codecentric.github.io/spring-boot-admin/current/
2.3.0:   https://codecentric.github.io/spring-boot-admin/2.3.0/

**Comment by membersound** [comment]
Ok then it was my understanding. I thought the github link to the docs would always reflect the state of the latest release, not of the current trunk.

**Comment by joshiste** [comment]
the releases have a link to the milestones with the issues/PRs
https://github.com/codecentric/spring-boot-admin/releases
