### ISSUE TITLE
Enhancement :  Can you add a function to automatically delete offline instances

### ISSUE THREAD

**Issue by lingting-gzm** [codecentric/spring-boot-admin#1535]
Now use docker for service deployment online, the deployment method is as follows:
 1. Start the new service 
2. After the new service is successfully started, stop and remove the old service.

 This will cause an offline instance to be added under the update module on the admin page after each update. , But due to the deployment method, I cannot specify the same hostname for each module container, so I want the admin to automatically delete the offline instance

**Comment by joshiste** [comment]
You can implement an `AbstractEventHandler` and add it as bean to your SBA Server.
It should listen to any `InstanceRegisteredEvent` and use the `InstanceRegistry#deregister()` to remove the unwanted instance.
