### ISSUE TITLE
Applications/Wallboard shows OUT_OF_SERVICE when service is UP

### ISSUE THREAD

**Issue by ronnberg** [codecentric/spring-boot-admin#1536]
We have a setup where we use hazelcast to persist event journal in SBA. We also use eureka as service discovery. Sometimes services are listed as OUT_OF_SERVICE in the Application view and Wallboard view when they are actually UP. This seems to happen when SBA misses the event when a service goes from OUT_OF_SERVICE to UP.

To replicate, this is what I did:

1. Start eureka, SBA and "myService" (all statuses are UP)
2. Make myService change status to OUT_OF_SERVICE
3. Kill SBA
4. Make myService change status to UP
5. After a few moments start SBA

When checking the event journal the last event of myService is "STATUS_CHANGED(OUT_OF_SERVICE)", both Applications and Wallboard view is flagging the service red and listing the service as OUT_OF_SERVICE. But when clicking into the service it has status UP (for all health indicators, Instance, discoveryComposite, eureka etc.) which is inconsistent with the other views.

I am not sure if there is something wrong with my configuration or if SBA cannot handle missed status changed events. It feels like the status state is a function of all the events, or is just simply the last event which will not work in the scenario I created. One thing to note in the example is that the STATUS_CHANGED event was never persisted by any instance. In my mind it is reasonable to assume that this could happen (DB is down, network issues or no instance of SBA was running during the time the status changed).

This was tested with SBA Version 2.2.2.

**Is there something I am missing here or is this a bug?**

Unfortunately I cannot share the actual code. To test this locally with hazelcast I added a simple storage using mapDB:

```java
import com.hazelcast.config.Config;
import com.hazelcast.config.EvictionPolicy;
import com.hazelcast.config.InMemoryFormat;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.MapStoreConfig;
import com.hazelcast.config.MergePolicyConfig;
import com.hazelcast.core.MapStore;
import com.hazelcast.map.merge.PutIfAbsentMapMergePolicy;
import de.codecentric.boot.admin.server.domain.values.InstanceId;
import org.mapdb.DB;
import org.mapdb.DBMaker;
import org.mapdb.Serializer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Collection;
import java.util.Map;

@Configuration
public class MyConfig {

    @Bean
    public Config config() {
        MapConfig eventStoreMap = new MapConfig("spring-boot-admin-event-store")
                .setInMemoryFormat(InMemoryFormat.OBJECT)
                .setBackupCount(1)
                .setEvictionPolicy(EvictionPolicy.NONE)
                .setMergePolicyConfig(new MergePolicyConfig(PutIfAbsentMapMergePolicy.class.getName(), 100))
                .setMapStoreConfig(new MapStoreConfig().setImplementation(new MyMapStore()));

        Config config = new Config();
        config.addMapConfig(eventStoreMap);
        config.setProperty("hazelcast.jmx", "true");


        return config;
    }

    private class MyMapStore implements MapStore<InstanceId, Object> {

        private DB db;
        private Map<InstanceId, Object> map;

        MyMapStore() {
            db = DBMaker.fileDB("testfile.db").checksumHeaderBypass().make();
            map = db.hashMap("test", Serializer.JAVA, Serializer.JAVA).createOrOpen();
        }

        @Override
        public void storeAll(Map<InstanceId, Object> map) {
            map.putAll(map);
            db.commit();
        }

        @Override
        public void deleteAll(Collection collection) {
            map.clear();
            db.commit();
        }

        @Override
        public Map loadAll(Collection collection) {
            return map;
        }

        @Override
        public Object load(InstanceId key) {
            return map.get(key);
        }

        @Override
        public Iterable loadAllKeys() {
            return map.keySet();
        }

        @Override
        public void store(InstanceId key, Object value) {
            map.put(key, value);
            db.commit();
        }

        @Override
        public void delete(InstanceId key) {
            map.remove(key);
            db.commit();
        }
    }
}
```

**Comment by joshiste** [comment]
Did you check the serverlogs for any errors? also can you reproduce the behavior in a recent 2.3.1 version?
?

**Comment by ronnberg** [comment]
I replicated the same behavior with version 2.3.1. No errors found in server log.
[spring.log](https://github.com/codecentric/spring-boot-admin/files/5606417/spring.log)

**Comment by ronnberg** [comment]
@joshiste Is anyone looking at this issue? Any more logs needed?

**Comment by SteKoe** [comment]
Closed due to inactivity. Feel free to reopen if issue still exists.
