### ISSUE TITLE
spring boot admin with SSO SAML authentication not working 

### ISSUE THREAD

**Issue by mangal07** [codecentric/spring-boot-admin#1541]
spring boot admin with service application SSO SAML authentication not working

**Comment by joshiste** [comment]
We don't provide any spring security config. You need to add your own.

If you have a specific problem to integrate your spring security config with SBA I may have a look at it. But we can't provide a fully fledged SAML config.

**Comment by Halayem** [comment]
In the perspective to go in production with SBA, our security auhority team require that every user accessing to SBA server must be authenticated and identified using our SSO authentication system,
so each http request sent by the browser to the server must provide the 'access_token' of the connected user that will be verified by the SBA Server to wether to authorize or not the request

I didn't find documentation on how to implement this, can you point me in the right direction ?

**Comment by erikpetzold** [comment]
Hi @Halayem 

closed issues are not visible in the list of open issues, so don't expect answers there ;)

for securing SBA there is a section in the docs: https://codecentric.github.io/spring-boot-admin/current/#securing-spring-boot-admin
just use standard spring security
