### ISSUE TITLE
ENV/ConfigProps Header is overlapping first entry in each category.

### ISSUE THREAD

**Issue by Xyaren** [codecentric/spring-boot-admin#1543]
Since updating to 2.3.1 we are experiencing issues with the env and config props view:
![image](https://user-images.githubusercontent.com/5864045/100458168-9ca8db80-30c3-11eb-8036-7aa7b3ee08ed.png)

![image](https://user-images.githubusercontent.com/5864045/100458247-ba764080-30c3-11eb-9b5e-bcd3dd82b000.png)

The `top 54px` results in the header overlapping the text.

Thanks for the help 👍

**Comment by SteKoe** [comment]
Hi @Xyaren, can you please share which browser and OS you are using? TIA!

**Comment by Xyaren** [comment]
Sure:

Windows 10 (latest version)
And current Chrome version.

I can post details when you need them. (Currently on mobile)
