### ISSUE TITLE
Monitoring status errors

### ISSUE THREAD

**Issue by 18670032796** [codecentric/spring-boot-admin#1544]
version:
Spring Cloud Alibaba 2.2.3+ druid-spring-boot-starter 1.2.3+ spring-boot-admin 2.3.1
question:
In the case of multiple data sources, clicking the configuration property will report a 504 error.

**Comment by andreashouben** [comment]
Can you provide more details or maybe even a demo project?

**Comment by joshiste** [comment]
closed due to missing feedback
