### ISSUE TITLE
There was an unexpected error (type=Internal Server Error, status=500). Exception evaluating SpringEL expression: "uiSettings.favicon"

### ISSUE THREAD

**Issue by mrdapotts** [codecentric/spring-boot-admin#1545]
Hi 
I was attempt to write a front end for a spring boot admin application, I have my own login page called login.html,  as soon as I added spring boot admin ar files, it reported error SpringEL expression: "uiSettings.favicon"

After doing a bit of digging around, I discovered that my version of login.html was not being loaded, instead a version had been taken from a spring boot admin jar file was loaded.  Even thought some sort of minification process has been run on index.html, I could see that no definition of uiSettings was provided.  I also discovered that its provided in index.html.

I don't know enough to tell spring to use my personnel version of login.html, so I renamed it and resolved my issue that way.

But since login.html is an entry point, I think you should be able to login in SBA without having to access index.html first.

**Comment by joshiste** [comment]
I'd suggest not to include the SBA into your business application. You'd better deploy it as separate applications, to avoid those cross-impacts.

**Comment by goldenxinxing** [comment]
The solution: Publish a bean of org.thymeleaf.spring5.templateresolver.SpringResourceTemplateResolver, make it's order larger than admin(10) and set a templateAlias
