### ISSUE TITLE
 health checks BUG

### ISSUE THREAD

**Issue by asdxiaoqex** [codecentric/spring-boot-admin#1548]
If you add this configuration, you will not be able to perform health checks

 server.servlet.context-path
![image](https://user-images.githubusercontent.com/50010140/101759131-2caf4200-3b14-11eb-85fb-fa03ecf6a559.png)

**Comment by joshiste** [comment]
can you provide a project to reproduce the issue?

**Comment by joshiste** [comment]
closed due to missing feedback
