### ISSUE TITLE
Update to Maven 3.6.3

### ISSUE THREAD

**Issue by Riggs333** [codecentric/spring-boot-admin#1550]

**Comment by erikpetzold** [comment]
are you referring to the maven wrapper here?

**Comment by jonashackt** [comment]
We should to dependency upgrades either with dependabot (I think this is currently configured) - or (I would prefer it) via https://github.com/renovatebot/renovate . But maybe this is also another issue?

**Comment by Riggs333** [comment]
I have no experience which of renovate and dependabot works better for SBA. 👍🏻 for using any of them. :-)

Anyway, I could not yet find out, if one of those tools also checks for updates for Maven itself.
While Maven did not have short release cycles in the past, we could still update it manually, in my opinion.

So updating the version in the properties of the maven wrapper here would be sufficient, I guess.

**Comment by joshiste** [comment]
the out of the box dependabot from github is currently active - afaik it just updates for security issues.

**Comment by jonashackt** [comment]
Ok then maybe we should solve this current issue manually - but create a new one to switch to renovate? I would also propose to combine the configuration of renovate with the introduction of GitHub actions (which would be another issue :) )...
