### ISSUE TITLE
Use frontend-maven-plugin to invoke frontend build

### ISSUE THREAD

**Issue by erikpetzold** [codecentric/spring-boot-admin#1553]
currently the maven build requires npm to be installed on the system in the correct version (invoking it via exec-maven-plugin)

with the frontend-maven-plugin (https://github.com/eirslett/frontend-maven-plugin) the correct npm version would we downloaded and used automatically, making the build more independent of the system configuration

**Comment by jonashackt** [comment]
An alternative would be https://www.webjars.org/ which is kind of a more fresh approach (didn't use it myself though).

**Comment by joshiste** [comment]
@jonashackt IIRC webjars is not feasible since we need to transpile the vue and javascript files.

**Comment by joshiste** [comment]
in the past (1.x) SBA used the frontend-maven-plugin. IIRC I removed it so it doesn't installs node in the CI during the build and use the preinstalled one to reduce build times

**Comment by jonashackt** [comment]
I have a working frontend-maven-plugin configuration in https://github.com/jonashackt/spring-boot-vuejs/blob/master/frontend/pom.xml if needed @ccoltx ✌️
