### ISSUE TITLE
SBA suport nacos but instance is DOWN 

### ISSUE THREAD

**Issue by zhousheng2** [codecentric/spring-boot-admin#1554]
Environment:
Spring Boot 2.2.0.RELEASE
Spring Cloud Alibaba 2.2.3.RELEASE
Spring boot Admin 2.2.4
Nacos 1.3.2

![image](https://user-images.githubusercontent.com/35722213/101881111-ea970680-3bce-11eb-9167-88fb91031a64.png)

![image](https://user-images.githubusercontent.com/35722213/101881070-dce18100-3bce-11eb-955d-90a28900af29.png)

**Comment by zhousheng2** [comment]
nacos is OK
![Uploading image.png…]()

**Comment by joshiste** [comment]
in your screenshot we can see that some of the health indicators return up, but not all are shown. Maybe one of the indicators just reports down?

**Comment by zhousheng2** [comment]
![image](https://user-images.githubusercontent.com/35722213/101906776-7cfdd100-3bf4-11eb-8d04-2a5586b9d75e.png)

**Comment by zhousheng2** [comment]
I have tried several versions of SBA to integrate Nacos, and all of them are the results

**Comment by zhousheng2** [comment]
`@Configuration
public class SecuritySecureConfig extends WebSecurityConfigurerAdapter {

    private final String adminContextPath;

    public SecuritySecureConfig(AdminServerProperties adminServerProperties) {
        this.adminContextPath = adminServerProperties.getContextPath();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");
        successHandler.setDefaultTargetUrl(this.adminContextPath + "/");

        http.authorizeRequests((authorizeRequests) -> authorizeRequests
                .antMatchers(this.adminContextPath + "/assets/**").permitAll()
                .antMatchers(this.adminContextPath + "/login").permitAll().anyRequest().authenticated())
                .formLogin((formLogin) -> formLogin.loginPage(this.adminContextPath + "/login")
                        .successHandler(successHandler))
                .logout((logout) -> logout.logoutUrl(this.adminContextPath + "/logout"))
                .httpBasic(Customizer.withDefaults())
                .csrf((csrf) -> csrf.csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                        .ignoringRequestMatchers(
                                new AntPathRequestMatcher(this.adminContextPath + "/instances",
                                        HttpMethod.POST.toString()),
                                new AntPathRequestMatcher(this.adminContextPath + "/instances/*",
                                        HttpMethod.DELETE.toString()),
                                new AntPathRequestMatcher(this.adminContextPath + "/actuator/**")));
    }

}`

![image](https://user-images.githubusercontent.com/35722213/101907927-37420800-3bf6-11eb-93a9-e03711b00445.png)

**Comment by lltx** [comment]
used sentinel ? You can refer to this article to troubleshoot

https://juejin.cn/post/6844904101034065927

**Comment by lltx** [comment]
Please expose the monitoring and inspection endpoint, from your screenshot, it is blocked by permission

**Comment by zhousheng2** [comment]
This is how I configure it

`management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always`

**Comment by lltx** [comment]
Not this, your spring security excludes `/actuator/**`

**Comment by zhousheng2** [comment]
I'm configured according to this：

https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-eureka/src/main/java/de/codecentric/boot/admin/SpringBootAdminEurekaApplication.java

**Comment by zhousheng2** [comment]
I've solved this problem.SecuritySecureConfig.java  It's not configured like the example，It should be configured like this：
` 
    private final String adminContextPath;

    public SecuritySecureConfig(AdminServerProperties adminServerProperties) {
        this.adminContextPath = adminServerProperties.getContextPath();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");

        http.authorizeRequests()
                .antMatchers(adminContextPath + "/assets/**").permitAll()
                .antMatchers(adminContextPath + "/login").permitAll()
                .antMatchers("/actuator/**").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin().loginPage(adminContextPath + "/login").successHandler(successHandler)
                .and().logout().logoutUrl(adminContextPath + "/logout")
                .and().httpBasic().and().csrf().disable();
    }
`
in addition，This is a bug in Nacos:
https://github.com/alibaba/nacos/issues/3005  
https://github.com/alibaba/nacos/issues/2820
![image](https://user-images.githubusercontent.com/35722213/102188933-e4679980-3ef0-11eb-8a1b-d78c8c637d16.png)

**Comment by joshiste** [comment]
Thanks for reporting back your findings. I'm closing this issue as we don't need to do anything here.
