### ISSUE TITLE
Enforcing LF in spring-javaformat prevents windows build

### ISSUE THREAD

**Issue by andreashouben** [codecentric/spring-boot-admin#1555]
Currently, the spring-javaformat settings in src/checkstyle/checkstyle.xml enforces an LF ending.

This causes an error when running the build on Windows where the default line ending is CRLF.

I get that CRLF line endings are unwanted in the project, but usually running git with `core.autocrlf=true` should solve that problem.

There is a similar bug in the spring-javaformat project where it's recommended to simply remove that setting so that it defaults to `LF_CR_CRLF`:

https://github.com/spring-io/spring-javaformat/issues/202

I propose removing it, too.

**Comment by andreashouben** [comment]
Seems it was just an issue with my local config.

**Comment by ccoltx** [comment]
Hi Andreas, you closed this issue too soon.
