### ISSUE TITLE
Add support for css customization

### ISSUE THREAD

**Issue by niriak** [codecentric/spring-boot-admin#1558]
I would like to change the look and feel of the UI in terms of colours (e.g. navigation-bar background colour) and some sort of layout (e.g. image size in login screen). Please add some css extension points (e.g. place a css file in some predefined folder like there is for extensions) to be used for all web pages incl. login screen.

**Comment by erikpetzold** [comment]
With Spring Boot Admin 3 there are some possibilities for customization. If more is needed please provide a pull request.

**Comment by SteKoe** [comment]
See: https://docs.spring-boot-admin.com/current/customize_ui.html#customizing-colors
