### ISSUE TITLE
SBA properties are not present in AdminServerProperties.instanceAuth.serviceMap

### ISSUE THREAD

**Issue by mikhalchenko-alexander** [codecentric/spring-boot-admin#1559]
Here is my configuration properties
```
server.port=8888
spring.security.user.name=admin
spring.security.user.password=admin

spring.boot.admin.instance-auth.service-map.api-service.user-name=client
spring.boot.admin.instance-auth.service-map.api-service.user-password=client
```

And my application is set up like this (it is in Kotlin, but I don't think it is important here)

```
@SpringBootApplication
@EnableAdminServer
class AdminApplication {
	@Autowired
	lateinit var adminServerProperties: AdminServerProperties

	@PostConstruct
	fun init() {
		println(adminServerProperties.instanceAuth.serviceMap)
	}
}

fun main(args: Array<String>) {
	runApplication<AdminApplication>(*args)
}
```

When I run SBA application the `AdminServerProperties.instanceAuth.serviceMap` is empty.

**Comment by soe78** [comment]
Hi,
I´ve  tried it and ran into the same problem. 
Only default-user-name and default-password properties seem to work.

**Comment by soe78** [comment]
InstanceCredentials has no DefaultConstructor, so Spring cannot load it as a @ConfigurationProperties - I will make a PullRequest

**Comment by soe78** [comment]
I could verify it´s working now with 2.4.0.
@ccoltx you can close this bug.
Thx!
