### ISSUE TITLE
Add a spring.boot.admin.client.enabled property to control if the client is enabled or disabled

### ISSUE THREAD

**Issue by RobWin** [codecentric/spring-boot-admin#156]
A `spring.boot.admin.client.enabled` property would still be nice and more intuitive than leaving spring.boot.admin.url empty.

Change 
`@ConditionalOnProperty("spring.boot.admin.url")` to
```
@ConditionalOnProperty(
        prefix = "spring.boot.admin.client",
        name = {"enabled"},
        matchIfMissing = true
)
```
The client would be enabled by default. But it would break backward compability. 
Or do you want me to write a more complex SpringBootClientEnablerCondition which extends SpringBootCondition and checks both properties?

**Comment by joshiste** [comment]
When possible the old behavior should be kept. So this would be this matrix:

   | enabled = false | enabled = true (default) |
--- | --- | ---
url empty (default)| inactive | inactive
url set | inactive | active

your change would activate the config although the url is unset..
Please also think of the docs & config-metadata....

**Comment by RobWin** [comment]
Ok. I change the PR

**Comment by RobWin** [comment]
The config-metadata is only used in the spring-boot-admin-server. Shall I still create a config-metadata file in spring-boot-admin-starter-client?
