### ISSUE TITLE
Provide option to prevent DNS canonical address resolution

### ISSUE THREAD

**Issue by shollander** [codecentric/spring-boot-admin#1574]
The current behavior of spring boot admin is to always resolve addresses given to some type of canonical address. This can cause issues (especially when using https) when the resolution comes up with an address that is not included in the server's certificate. There should be an option to prevent this behavior and just use the exact address as configured.
I know there is an option to prefer ip, but that is not always a good option. DNS is preferable to IP, and not all certificates contain the IP as a SAN.

**Comment by joshiste** [comment]
I don't know if I got it right. So basically you want an option to disable the Hostname verification on TLS connections?

**Comment by shollander** [comment]
No, although that would also fix my issue.
What I am suggesting is to provide an option to prevent resolving addresses. For example, if I have a server 10.0.0.1 that has a certificate with the name coolapp.mycompany.com. But there may be multiple DNS entries for that IP. The canonical hostname may resolve to abcd-ca-test.mycompany.com. What currently happens is that when I put `https://coolapp.mycompany.com` in the properties file as the value of `spring.boot.admin.client.url`, it ends up resolving to `https://abcd-ca-test.mycompany.com` which doesn't match the server's certificate. You can argue that the DNS entries should be fixed, but we don't always have the luxury of that option. I think that it's reasonable to expect that it use the exact property value that I configure and not try to be smart and resolve it to a canonical value.

**Comment by joshiste** [comment]
Sorry for the late response. We don't do any special name resolution. We "just" use the RestTemplate/Webclient.
So I'm not very keen on doing some extra work here.
But you can configure the RestTemplate in a custom way so that it fit's your needs.
See [SpringBootAdminClientAutoConfiguration](https://github.com/codecentric/spring-boot-admin/blob/c317e76c9d5e70f2b8041f67759186326baf5cbc/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/SpringBootAdminClientAutoConfiguration.java#L140)

**Comment by shollander** [comment]
@joshiste I don't think this has anything to do with the client used. I believe the cause of the issue is the call to `address.getCanonicalHostname()` in `DefaultApplicationFactory.getHost()`: https://github.com/codecentric/spring-boot-admin/blob/80dbc609eb999935fd6dbe55c80064e6f4fccf6d/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/DefaultApplicationFactory.java#L222
The canonical hostname is not always desired. I think a better option would be to use `address.getHostName()` instead, which will return the original host name as configured. If you don't want to modify the current default deault behavior, at least there should be an option similar to `spring.boot.admin.client.instance.prefer-ip` to prevent the undesirable DNS lookup. Perhaps something called `spring.boot.admin.client.instance.use-given-hostname`?

**Comment by joshiste** [comment]
ah ok now I've got it. sounds plausible

**Comment by nzuwera** [comment]
Setting spring.boot.admin.client.instance.service-host-type=host_name fix the issue I was having.
I allowed SBA to resolve client by hostname configured in server.address (also configured as certificate CN in keystores)
