### ISSUE TITLE
SBA with Eureka not showing instances from scaled app from Cloud Foundry

### ISSUE THREAD

**Issue by zorlac** [codecentric/spring-boot-admin#1577]
It seems like SBA is not capturing all the instances from eureka from an app deployed in cloud foundry. Basically the app is deployed and scaled to 3 instances, meaning all 3 instances shared same url but with different instance id from cloud foundry. Eureka is able to capture all instances SBA connected to eureka only displaying once instance. 

Spring boot version: 2.3.5
SBA version: 2.3.1

**Comment by joshiste** [comment]
Did you read https://codecentric.github.io/spring-boot-admin/current/#_cloudfoundry ?
