### ISSUE TITLE
spring-boot-admin-server-ui META-INF/resources moved to META-INF/spring-boot-admin-server-ui

### ISSUE THREAD

**Issue by oxygensar** [codecentric/spring-boot-admin#158]
I was using spring-boot-admin 1.2.3 in a war module with dependency on spring-boot-admin-server-ui jar that had static web content packed into META-INF/resources.
After move to 1.3.2 version i found that resources for spring-boot-admin-server-ui.jar are now packaged to META-INF/spring-boot-admin-server-ui (git commit e50ad9de42e522fecb9e1dcb692aae26538c167a) and thus are not accessible anymore by the application. Is it something intentional? Is there a recommended way of dealing with this change?

**Comment by joshiste** [comment]
The change was intentional, to allow custom context-paths. With the change also a resourcehandler is registered for the new location in spring-boot-admin-server. I wonder why it is not working for you.

**Comment by joshiste** [comment]
The [sample-war-file from maven-central](http://central.maven.org/maven2/de/codecentric/spring-boot-admin-sample-war/1.3.2/spring-boot-admin-sample-war-1.3.2.war) deployed to a tomcat is working for me.
