### ISSUE TITLE
Configure Renovate to automate dependency updates

### ISSUE THREAD

**Issue by jonashackt** [codecentric/spring-boot-admin#1580]
With https://github.com/renovatebot/renovate we can automate the dependency upgrade process better. This will also take care of things like https://github.com/codecentric/spring-boot-admin/pull/1549

**Comment by jonashackt** [comment]
See https://github.com/codecentric/spring-boot-admin/pull/1592

**Comment by Riggs333** [comment]
#1592 is merged and therefore **renovate** is activated.
We will see how it will work out and tweak it if necessary.
