### ISSUE TITLE
> The 401 is returned by the monitored application. You need to make those endpoints accessible for the SBA server. For [example by using basic auth](https://codecentric.github.io/spring-boot-admin/current/#_securing_client_actuator_endpoints)...

### ISSUE THREAD

**Issue by zhangran2616** [codecentric/spring-boot-admin#1584]
> The 401 is returned by the monitored application. You need to make those endpoints accessible for the SBA server. For [example by using basic auth](https://codecentric.github.io/spring-boot-admin/current/#_securing_client_actuator_endpoints)...

I refer to the documentation, but there is no solution, please help。SCA itself is down, others are up

![image](https://user-images.githubusercontent.com/6472032/103113640-a27be780-4696-11eb-9038-4e917ecf5dda.png)

![image](https://user-images.githubusercontent.com/6472032/103113651-b0ca0380-4696-11eb-8083-973aba0c7174.png)

![image](https://user-images.githubusercontent.com/6472032/103113661-baec0200-4696-11eb-8a65-ccca62ce9aca.png)

![image](https://user-images.githubusercontent.com/6472032/103113678-d35c1c80-4696-11eb-9956-25c193954ef9.png)

_Originally posted by @zhangran2616 in https://github.com/codecentric/spring-boot-admin/issues/1371#issuecomment-751145086_

**Comment by joshiste** [comment]
the spring boot admin talks to itself using http so you also need to include the username / password for the admin server in it's metadata-
