### ISSUE TITLE
How to make specific endpoint checks less strict?

### ISSUE THREAD

**Issue by membersound** [codecentric/spring-boot-admin#1585]
I have an application to monitor that exposes `db` status. It is totally fine for the db connection being offline several times a day for a few minutes.

Question: how can I tell spring-admin to be less strict on the `UP/DOWN` checks?
Like adding a wider timeout or more retries only for this specific application?

Would this usecase have to be configured on the admin server side, or on the client side?

**Comment by SteKoe** [comment]
Since we just display the actual value reported by the actuator endpoints, this feature request is related to Spring Boot directly and not part of SBA.

**Comment by membersound** [comment]
So you probably don't have any advise how this could be achieved in spring boot?
