### ISSUE TITLE
Unable to override spring.security.user.name and spring.security.user.password credentials in spring-boot-admin-sample-servlet sample

### ISSUE THREAD

**Issue by persapiens** [codecentric/spring-boot-admin#1586]
I was unable to override `spring.security.user.name` and `spring.security.user.password` credentials in spring-boot-admin-sample-servlet sample when I migrate from 2.1.6 to 2.3.1.

I think the problem may be related to this code [here](https://github.com/codecentric/spring-boot-admin/blob/10022c67a0fcbd6d6dadaf969a423824cc68ce5b/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SecuritySecureConfig.java#L71). It forces fixed credentials.

I look forward to your answer.

**Comment by joshiste** [comment]
The sample doesn't pick up those properties (since 2.x). 
I'd really suggest that you don't deploy the sample but build your own security config. 

But if you want to do a PR that the sample picks up the values from the `SecurityProperties` go for it.

**Comment by persapiens** [comment]
I've just done PR. I'm open to improve it.
Thanks for your time.

**Comment by SteKoe** [comment]
Closed by merging PR.
