### ISSUE TITLE
The style of the insights/environment panel seems in a mess

### ISSUE THREAD

**Issue by gongshw** [codecentric/spring-boot-admin#1588]
|||
| --- | --- |
| Version of Spring Boot Admin | 2.3.1 |
| Version of Spring Boot | 2.4.x/2.3.x |
| Which page the problem found | the insights/environment panel (/instances/{instantId}/env) |

![image](https://user-images.githubusercontent.com/2306755/104578697-fece9780-5695-11eb-8c4f-7a64fa1ec636.png)

The environment data is invisible because of this problem.

![image](https://user-images.githubusercontent.com/2306755/104578904-405f4280-5696-11eb-9caf-5713081396f4.png)

It seems that something wrong with the css style `top: 54px;`. but I'm not a fullstack developer, so I can't figure out how to solve this problem.

![image](https://user-images.githubusercontent.com/2306755/104579186-9df38f00-5696-11eb-8fcb-0845506c2c60.png)

**Comment by joshiste** [comment]
which browser are you using?

**Comment by gongshw** [comment]
@joshiste 
I'm using Chrome 87.0.4280.141 and Safari 14.0.2 (16610.3.7.1.9) on MacOs 11.1 (20C69).
This problem raises at both Chrome and Safari.

Here is a minimal demo project to reproduce this issue: https://github.com/gongshw/sba-issue-1588/

**Comment by ParkerM** [comment]
I also see this behavior in the current stable version. Looks like the issue was reported and fixed in #1546, so now just waiting for a new release.

**Comment by djgeary** [comment]
I'm seeing this too in Firefox 85.0 on Linux. Works fine in Spring Boot Admin 2.3.0, broken in 2.3.1. Its the first entry in each section isn't displayed - see attached screenshots:

![Spring Boot Admin 2 3 0](https://user-images.githubusercontent.com/12694487/106903670-2f807a80-66f2-11eb-82d1-3b49520ce3c9.jpeg)

![Spring Boot Admin 2 3 1](https://user-images.githubusercontent.com/12694487/106903688-35765b80-66f2-11eb-97d7-7b2bc3550470.jpeg)

**Comment by SteKoe** [comment]
Fixed by #1546
