### ISSUE TITLE
Multiple instances of SpringBoot admin

### ISSUE THREAD

**Issue by patpatpat123** [codecentric/spring-boot-admin#1595]
Small issue regarding the SpringBoot admin project please.

I was wondering how if this is a bug in a multi instance environment.

Case 1: ONE instance of SpringBoot Admin and ONE instance of MySpringBootApp.

Result1: Very happy, we are able to see MySpringBootApp properly registered in the one instance of SpringBoot Admin. We are seeing metrics etc, super.

However, both are single points of failures.

Case 2: ONE instance of SpringBoot Admin and THREE instances of MySpringBootApp. (three to put a concrete number, concrete example, please read "many")

Result2: Still very happy, we are able to see ALL THREE MySpringBootApp properly registered in the one instance of SpringBoot Admin. We are seeing metrics etc, super.

However, SpringBoot Admin is still single points of failure.

Case 3: THREE instances of SpringBoot Admin and N(1 to X) instances of MySpringBootApp.

Result3: A bit surprised. The instances of MySpringBootApp are registered to only ONE out of many instances of SpringBoot Admin. So, its kinda still single point of failure even though there are many SpringBoot Admin.

is it a bug apps can only be registered to one instance please? I tried putting a load balancer, an array of URLs, still registered to one instance only

**Comment by erikpetzold** [comment]
Hi @patpatpat123 ,

I did not have a deeper look at this feature yet, but I guess that's what the clustering option is made for: https://codecentric.github.io/spring-boot-admin/current/#clustering-support

So your backend instances communicate via hazelcast. I must admin I don't know if you can passa list of servers to register with to your client applications. But maybe this helps as a starting point.

**Comment by patpatpat123** [comment]
Thank you!
