### ISSUE TITLE
Ability to sanitize environment variables

### ISSUE THREAD

**Issue by batousik** [codecentric/spring-boot-admin#1596]
Would be nice to create a yaml parameter  environment-keys-to-sanitize that acts in the same ways as metadata-keys-to-sanitize, but for the environment variables

**Comment by joshiste** [comment]
Spring boot has it: `management.endpoint.env.keys-to-sanitize`

**Comment by blacksab** [comment]
I still do think this could be a great feature for spring-boot-admin.

spring-boot has started to mask all values in /env. If values are unmasked, none of the default sanitize rules are applied by default.
