### ISSUE TITLE
spring cloud Brixton.M5: migrate X-Trace-Id from UUID IDs to long based IDs

### ISSUE THREAD

**Issue by cforce** [codecentric/spring-boot-admin#160]
https://github.com/spring-cloud/spring-cloud-sleuth/issues/179

**Comment by joshiste** [comment]
Thank you for notifying.
I will not make a release of spring boot admin based on a Brixton milestone. So this should be no problem for us.

**Comment by cforce** [comment]
It is a problem..as this bug occurs on the services administration server
queries. So this would prevent all of us to use my or newer releases.
Please fix this

Johannes Edmeier <notifications@github.com> schrieb am Mo., 22. Feb. 2016
12:59 PM:

**Comment by joshiste** [comment]
The `X-Trace-Id` isn't added by our code so there isn't nothing to fix for us.

**Comment by cforce** [comment]
Yes, its not ur code fault. The problem is that M4 ist not compatible with M5 in spring for sleuth incompatible change. And because of a bug in M5 (you shall now which i mean) which raised espcially in admin server we can't switch admin server to M5. Therefore we must use admin server on spring cloud M4 togehter with all other services on M5 (for other reasons).
