### ISSUE TITLE
'Download Heap Dump' not working

### ISSUE THREAD

**Issue by joeshadbolt** [codecentric/spring-boot-admin#1611]
We appear unable to use the 'Download Heap Dump' feature in SBA. We are getting redirected to a page with no content.

The URL of which we are redirected to:
`/spring-boot-admin/instances/6fd9f5d8e308/actuator/heapdump`

There is nothing in the logs, network tab, all successful.

![image](https://user-images.githubusercontent.com/4125403/105842278-d7e55f00-5fcd-11eb-8647-1e2902314b61.png)

Version of SBA: 2.3.1
Version of Spring Boot in use: 2.2.1.RELEASE
Chrome: Version 88.0.4324.96 

We are running in a k8s cluster and using the k8s discovery client.

Verified the targeted application's `/actuator/heapdump` is working correctly.

**Comment by AnthonyNTK** [comment]
@joeshadbolt does the download function work for logfile and threaddump in your application?
All download will redirect me to a new page as you described using Firefox 84.0.2 (64-bit)

**Comment by djeanprost** [comment]
hello,

I have to say /logfile does not work for me neither on FF 78.5.0esr

**Comment by joeshadbolt** [comment]
@AnthonyNTK thread dump works, however the logfile does not.

**Comment by huan415** [comment]
I have the same problem.   How to solve this problem

**Comment by MorganArthur** [comment]
I have the same problem. 
![image](https://user-images.githubusercontent.com/24489342/126100249-8673bf33-a1d8-4472-bc2d-9c9035f72cda.png)

![image](https://user-images.githubusercontent.com/24489342/126100311-21005d7a-8ddb-4fac-9f14-2d15b3300f8c.png)

![image](https://user-images.githubusercontent.com/24489342/126100510-2c38f6e1-a414-44c6-bf4d-667b82421316.png)

![image](https://user-images.githubusercontent.com/24489342/126100527-d933d83e-ba2b-4929-be9d-f463920c45a4.png)

/logfile and /heapdump are redirected to a blank page.

Is this where the configuration information is missing？

sba version：2.4.2
springboot version：2.5.2
Chrome version：91.0.4472.124

**Comment by SteKoe** [comment]
I have just merged the PR by @huan415. Can you please recheck if the problem remains using the current 2.5.1-SNAPSHOT version? 

https://github.com/codecentric/spring-boot-admin/packages/575123

**Comment by ulischulte** [comment]
Due to the lack of feedback, we're closing the issue. Please reopen if this is still aproblem.
