### ISSUE TITLE
302 redirect without location after login success in webflux when I access http://localhost:port/context (no suffix '/')

### ISSUE THREAD

**Issue by zxdposter** [codecentric/spring-boot-admin#1613]
no suffix '/' :
http://localhost:port/context
![image](https://user-images.githubusercontent.com/13846260/106087205-7bfe1000-615e-11eb-8fea-a4d4589d2a62.png)

suffix '/' :
http://localhost:port/context/
![image](https://user-images.githubusercontent.com/13846260/106087251-96d08480-615e-11eb-86ab-ede9d5378dfb.png)

version:
spring boot : 2.4.2
spring boot admin : 2.3.1

**Comment by joshiste** [comment]
do you have a project to reproduce the issue?

**Comment by zxdposter** [comment]
I change back mvc already, sorry for bother you.
