### ISSUE TITLE
Foster beeing OS agnostic by introducing other environments (like Windows) to GitHub Actions builds

### ISSUE THREAD

**Issue by jonashackt** [codecentric/spring-boot-admin#1622]
As we have issues like https://github.com/codecentric/spring-boot-admin/pull/1617, we should be able to check, if SBA is not also working on the default GitHub Actions Ubuntu, but also on Windows (and maybe Mac - but I think that might be overengineered?).

**Comment by jonashackt** [comment]
Facing the build error

```
Error:  Unknown lifecycle phase ".javadoc.skip=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```

which seems to be Windows Powershell related, where the Powershell tries to interpret `.` inside the JavaDoc skip command `-D maven.javadoc.skip=true` as described in https://stackoverflow.com/questions/38051787/maven-javadoc-skip-true-throws-an-error.

**Comment by ccoltx** [comment]
Remove it, it's not needed

**Comment by jonashackt** [comment]
No problem @ccoltx 🤪  works with the space between `-D and the maven.javadoc` parameter. 

But now we have [the next problem]() with the [spring-javaformat-maven-plugin](https://github.com/spring-io/spring-javaformat):

```
Error:  Failed to execute goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.27:validate (default) on project spring-boot-admin-server: Formatting violations found in the following files:
Error:   * D:\a\spring-boot-admin\spring-boot-admin\spring-boot-admin-server\src\main\java\de\codecentric\boot\admin\server\config\AdminServerAutoConfiguration.java
```

**Comment by jonashackt** [comment]
Hmm, now the `maven-checkstyle-plugin` [runs amock](https://github.com/codecentric/spring-boot-admin/runs/1834019652?check_suite_focus=true): 

```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (checkstyle-validation) @ spring-boot-admin-server ---
[INFO] Starting audit...
Error:  D:\a\spring-boot-admin\spring-boot-admin\spring-boot-admin-server\src\main\java\de\codecentric\boot\admin\server\config\AdminServerAutoConfiguration.java:1: Expected line ending for file is LF(\n), but CRLF(\r\n) is detected. [NewlineAtEndOfFile]
```

**Comment by jonashackt** [comment]
Ok, seems that the GitHub Actions `windows-latest` environment has an issue with Docker:

```
Could not find a valid Docker environment. Please see logs and check configuration
```

**Comment by jonashackt** [comment]
Ah, this is [a known Testcontainers limitation right now with Windows Server 2019 and Docker](https://www.testcontainers.org/supported_docker_environment/windows/):

> Docker on Windows Server 2019 is currently not supported (also note this issue https://github.com/testcontainers/testcontainers-java/issues/2960).

**Comment by jonashackt** [comment]
Hmm, sadly also not working with `windows-server2016` [GitHub Actions environment](https://github.com/actions/virtual-environments).

**Comment by jonashackt** [comment]
Seems that the problem is, that in Windows Server there are only Windows containers activated per default (no Linux containers): https://stackoverflow.com/questions/66077884/testcontainers-in-windows-environment-on-github-actions-could-not-find-a-valid As Sergei Egorov stated:

> The problem with windows-latest is that it uses Windows containers, not Linux containers. It means that Testcontainers itself works, but all the images that it starts are Linux-based and, in Windows containers mode, they obviously fail to start :)

So a "fix" for that would be to have a GitHub Action environment with Linux containers enabled! But after some googeling this doesn't seem to be that easy. First I though LCOW (Linux Containers on Windows) would simply need to be enabled. But as [this great elaboration](https://github.com/src-d/metadata-retrieval/issues/53#issuecomment-545353264) states, it's not easy (or even possible) to activate LCOW on the GitHub Actions Windows env.

I digged deeper into the issue and found [that LCOW was officially deprecated in `20.10`](https://github.com/docker/cli/blob/master/docs/deprecated.md#linux-containers-on-windows-lcow-experimental) 😢 in favour of WSL2, that brings in native Linux runtime and also [Docker for Desktop on Windows 10 already favours this approach](https://docs.docker.com/docker-for-windows/wsl/).

**BUT: We are on Windows Server 2019**, which is not Windows 10 Desktop. And on GitHub Actions we only have the server version in it's nano flavor. There's sadly [an open issue for the WSL2 support in Windows Server 2019](https://github.com/MicrosoftDocs/WSL/issues/678). And scanning the GitHub Actions [Windows Server 2019 docs](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) I found out that there's only WSLv1 installed right now.

**Comment by jonashackt** [comment]
If we don't want to create a private GitHub Actions runner this seems to be a dead end.

The testcontainers team [uses Azure Pipelines](https://github.com/testcontainers/testcontainers-java/issues/2960#issuecomment-774487244) to run the tests on Windows - maybe we should also switch to this approach. See the testcontainers pipeline at https://github.com/testcontainers/testcontainers-java/blob/master/azure-pipelines.yml

**Comment by ccoltx** [comment]
@jonashackt - how would you like to proceed? We could tag the testcases using docker and exclude them from the command line here.

**Comment by jonashackt** [comment]
@ccoltx oh yeah, that would be an approach. I don't see any benefit from also using Azure Pipelines...
