### ISSUE TITLE
Speed up build time (local and GH actions)

### ISSUE THREAD

**Issue by Riggs333** [codecentric/spring-boot-admin#1623]
We (SBA team) want to investigate options to speed up the build time of SBA.

Brainstormed options for now:
* Maven build configuration using [parallel builds](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3)
* Split into more Maven modules
* Migrate to Gradle (considering using Gradle Enterprise, ...), also see #1438 
* Using [mavend](https://github.com/mvndaemon/mvnd)

**Comment by jonashackt** [comment]
We also talked about fastening the frontend build:
* caching `node_mudules` directory
* therefore we should pin the `node` version, which could be done with the frontend-maven-plugin

**Comment by ccoltx** [comment]
Cache the mvn dependencies between builds (see #1677)

**Comment by SteKoe** [comment]
Closed by #1677
