### ISSUE TITLE
Top custom view how use element ui.

### ISSUE THREAD

**Issue by zxdposter** [codecentric/spring-boot-admin#1628]
When I import element ui.
```
import ElementUI from 'element-ui'
```

Browser console error:
```
Uncaught TypeError: Cannot read property 'prototype' of undefined                      dom.js:19 
```

Seems element ui cannot found vue object, in dom.js, source code like this, I found _vue is **undefined**
```
var _vue = __webpack_require__(/*! vue */ "vue");
```

If I import Vue in my custom view, remove externals in vue.config.js, the error is gone, but element component not take effect.
```
        config.externals({
            vue: {
                commonjs: 'vue',
                commonjs2: 'vue',
                root: 'Vue'
            }
        });
```

Please help me!

**Comment by jonashackt** [comment]
@zxdposter could you try to use the fix from https://github.com/codecentric/spring-boot-admin/issues/1249#issuecomment-757853004 ?

**Comment by zxdposter** [comment]
@joshlong already try this, but element-ui still not workingm, I try "antd" today, it's working.
