### ISSUE TITLE
Only one connection receive subscriber allowed

### ISSUE THREAD

**Issue by coryroloff** [codecentric/spring-boot-admin#1631]
Hello,

Following the quick start guide I get this error from spring boot admin:

```
java.lang.IllegalStateException: Only one connection receive subscriber allowed.
	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:180) ~[reactor-netty-core-1.0.3.jar!/:1.0.3]
	Suppressed: reactor.core.publisher.FluxOnAssembly
```

The client seems to be calling the server fine with all the correct information.

Admin Version: 2.4.0-SNAPSHOT
App Spring Version: 2.4.1

**Comment by jonashackt** [comment]
Hey @coryroloff thanks for the report. Could you please provide us with a bit more context - ideally with a example repo on GitHub where we could comprehend the issue?!

**Comment by coryroloff** [comment]
Hi @jonashackt,

I followed the quick start guide to spin up the server and add the client to my existing spring app, which is when I started getting that error. I just tried generating a new spring boot app and it looks like that works fine, so it must be something in my project. However, I'm not sure where to start and I'm not sure I can put together an example repo as the code belongs to the company.

I tried disabling security and made sure all of the actuator endpoints are exposed, but still receive that error. Based on that message, are there any suggestions you have as to where to look?

The app itself doesn't do anything too crazy with Spring. Mostly just a standard setup. Here are the dependencies we're using:

```
implementation "com.googlecode.libphonenumber:libphonenumber:8.12.15"
implementation "org.projectlombok:lombok:1.18.16"
annotationProcessor "org.projectlombok:lombok:1.18.16"
testImplementation "org.projectlombok:lombok:1.18.16"
testAnnotationProcessor "org.projectlombok:lombok:1.18.16"
implementation "org.springframework.boot:spring-boot-starter-actuator:2.4.1"
implementation "org.springframework.boot:spring-boot-starter-web:2.4.1"
implementation "org.springframework.boot:spring-boot-starter-validation:2.4.1"
implementation "org.springframework.boot:spring-boot-starter-data-jpa:2.4.1"
implementation "org.springframework.session:spring-session-jdbc:2.4.1"
implementation "org.springframework.boot:spring-boot-starter-security:2.4.1"
implementation "com.auth0:java-jwt:3.12.0"
implementation "org.springdoc:springdoc-openapi-ui:1.5.2"
implementation "org.flywaydb:flyway-core:6.5.5"
implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.8"
implementation "org.apache.httpcomponents:httpclient:4.5.13"
implementation "org.apache.commons:commons-collections4:4.4"
implementation "net.logstash.logback:logstash-logback-encoder:5.2"
implementation "de.codecentric:spring-boot-admin-starter-client:2.4.0-SNAPSHOT"
developmentOnly "org.springframework.boot:spring-boot-devtools:2.4.1"
runtimeOnly "org.postgresql:postgresql:42.2.18"
testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.1")
testImplementation "org.springframework.security:spring-security-test:5.4.2"
```

**Comment by joshiste** [comment]
I'm closing this issue. Looks like you solved it on your own.
