### ISSUE TITLE
Possibility to disable SBA server side on property

### ISSUE THREAD

**Issue by djeanprost** [codecentric/spring-boot-admin#1633]
Hello,

Actually, it's only possible to disable SBA Server side by removing the annotation @EnableAdminServer.
I would like to be able to disable the server by using something that could look like the enabled toggle on client side, which is actually ``spring.boot.admin.client.enabled``. This could be for instance ``spring.boot.admin.server.enabled``

Thank you

**Comment by joshiste** [comment]
@djeanprost sounds plausibel. do you wanna go for a PR?

**Comment by djeanprost** [comment]
Hello,
I'm not sure about the release process of this issue. Can I expect it to be included in the next release (2.4.2 or other) ?
thank you
