### ISSUE TITLE
Show refresh trigger in UI without having the updatable env endpoint

### ISSUE THREAD

**Issue by patpatpat123** [codecentric/spring-boot-admin#1636]
Hello SBA Team,

I just wanted to start an enhancement request regarding the /refresh endpoint please.

Currently, on server side, I do have:
```
spring.boot.admin.probed-endpoints=beans,caches,conditions,configprops,env,health,heapdump,info,loggers,mappings,metrics,scheduledtasks,threaddump,refresh

```
(note the last one on the list, refresh)

On app start up, after registration, I do see on client side (the service that is going to be registered to SBA server) log:
```
[or-http-epoll-4] reactor.netty.http.server.AccessLog      : 1x.1xx.1xx.1xx:45504 - - [18/Feb/2021:00:25:14 +0000] "OPTIONS /refresh HTTP/2.0" 200 - 13 ms
```

But that is all. No further call to refresh endpoint by SBA server.

It will be interesting on the SBA Serverside, maybe through the UI, to have a way to "trigger" those refresh (without making it a periodic poll like /health).

Many clients that expose the @refreshScope can benefits from this feature, making SBA server even more useful for dynamic content.

Thank you

**Comment by joshiste** [comment]
There is already an option on the enviroment page of an instance to trigger the refresh endpoint.

**Comment by patpatpat123** [comment]
Thank you for the answer. However, I am not seeing anything similar.

Are you referring to the [Insights tab] -> Details, Metrics, [Environment] ?
If it is, I am only seeing server port, system properties, system environment, Spring cloud Client Host Info, configserver:vault:refundservice, configClient and Config resource 'class path resource [application.properties]' via location 'optional:classpath:/'

I am not seeing anything related to a /refresh trigger.

Can you please detail a bit more?

**Comment by joshiste** [comment]
when then POST on then /env actuator is available (from spring cloud) then there is an "Environment Manager" on the page which has a refresh button.

**Comment by patpatpat123** [comment]
Thanks for the follow up.

I am trying to understand the issue, definitely something I did wrong!

So, you said: "when then POST on then /env actuator is available (from spring cloud) "
I see in my app, the client, that SBA Server is doing: 

```
[or-http-epoll-4] reactor.netty.http.server.AccessLog      : 1x:45504 - - [18/Feb/2021:00:25:14 +0000] "OPTIONS /env HTTP/2.0" 200 - 21 ms
[or-http-epoll-4] reactor.netty.http.server.AccessLog      : 1x:45504 - - [18/Feb/2021:00:26:00 +0000] "GET /env/PID HTTP/2.0" 200 574 12 ms
[or-http-epoll-4] reactor.netty.http.server.AccessLog      : 1x:45504 - - [18/Feb/2021:00:26:08 +0000] "GET /env HTTP/2.0" 200 23919 19 ms
```

Like in the example, I see OPTION and GET, but no POST.

But I went to perform a curl on the POST /env endpoint, and I am getting this:

```
{"timestamp":"2021-02-18T19:45:09.731+00:00","path":"/env","status":405,"error":"Method Not Allowed","message":"","requestId":"6e3c404e/1-6951"}%
```

And you are saying: "then there is an "Environment Manager" on the page which has a refresh button."

I undertand I do not have a POST /env endpoint, hence, it is normal I am not seeing en Environment manager page which has a refresh button. Am I correct please?

And if this is the issue. May I ask what is SBA Server trying to do with this /env endpoint? Because from the Spring Cloud documentation, I am not seeing a POST on /env neither.

Also, I do have this on SBA Server:

```
spring.boot.admin.probed-endpoints=beans,caches,conditions,configprops,env,health,heapdump,info,loggers,mappings,metrics,refresh,scheduledtasks,threaddump
```
Note the 5th element, env.

Would it be possible to all SBA Server to display the page based on the GET/OPTION please?

**Comment by joshiste** [comment]
The UI does a [OPTION request to /env ](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/services/instance.js#L94)to look if the POST method is allowed (and the env can be updated).

But as you got a 405 on testing it yourself, this seems not to be the case.

So you currently need to activate the env endpoint extension from spring cloud.

But I've also accept a PR that a refresh button is shown depending on whether `/refresh` is present or not.

**Comment by patpatpat123** [comment]
Hello @joshiste,

So you are correct, I went to activate the /POST to /env, and was able to see the difference.

As expected, very well designed.

But the UI expect some kind of input, on the left and right side (two text boxes to fill)

I was more suggesting a simple refresh button, that will trigger the /refresh endpoint of the registered app, no matter the registered app has /env ready or not.

This way, the Admin will have the possibility to trigger the dynamic hot reload of properties of registered apps, which can be a very strong feature.

I believe it is what you said here:

"accept a PR that a refresh button is shown depending on whether /refresh is present or not (and don't depend on the POST-ability of /env"

**Comment by AnakinPt** [comment]
I think this feature would be useful just with the /actuator/refresh. Could you make it work, please? I would not like to expose the /actuator/env push just for this.

**Comment by patpatpat123** [comment]
Hello SBA Team, 

I think this might be a good idea for enhancement, especially combined with the @refreshScope of Spring framework.

I was going through the code, and I am interested in a contribution.

Unfortunately, I am not sure where to start.

The idea should be straightforward, some kind of
```
for (Client client : registeredClientList) {
    use the rest template / web client to send a request to the /actuator/refresh (or /refresh depending on configuration)
}
```

And on the front end side, just a button to trigger above method.

Is this design correct? If yes, is it possible to point me where to start on the back end java side please?

Thank you

**Comment by patpatpat123** [comment]
@joshiste @AnakinPt

**Comment by patpatpat123** [comment]
Many thanks guys. Cannot wait to give it a go. Thanks a lot!
