### ISSUE TITLE
Implement push client mode

### ISSUE THREAD

**Issue by morrica** [codecentric/spring-boot-admin#1643]
Hi and thanks for all the great work on Spring Boot Admin.

I'd like to propose a big feature request, namely a push client mode that would not require the client to have any web application running on the client. I.e. `SpringApplication.setWebApplicationType(WebApplicationType.NONE)`.

My reasons for this request are threefold:
1) I would like to monitor an application that doesn't naturally have an HTTP server running. 
2) My current testing process for my application involves spinning up many instances simultaneously in a BASH for loop. Setting up the Actuator endpoint and spring-boot-admin-client in a "testing" profile is possible but involves setting a different port for each instance and passing that port through the for loop ends up being fairly hacky for my setup.
3) I understand that leveraging the functionality of actuator is very attractive, but from a greenfield design standpoint allowing the client to be monitored without running a HTTP server seems attractive.

My proposed solution would involve adding a "push" mode to the client that would cause it to push the actuator data to the admin server on a regular basis. No request from the admin server to the client would be required. If the admin server did not hear from the client for a specified period of time the admin server would consider the client to be down.

I am not familiar with the APIs provided by Actuator internally but I imagine that the data that would be published at the endpoint is either already available to other classes in the application or making it so would not be impossible for the actuator team to implement. 

Anyway... I realize this is a big change to the current architecture and may involve coordinating work on actuator as well, but I think it would improve the usability of Spring Boot Admin in a variety of situations. I don't expect to see this implemented immediately, but keeping it on the possible things to do list might be a good idea. 

Thanks for your consideration!

**Comment by joshiste** [comment]
@morrica Thanks for your suggestion. 

We've shortly discussed this. For now we see some Problems:

1) If you have a lot of those services, the data for all endpoints needs either to be kept in memory (big heap) or be persisted somewhere (and we tried to avoid persistence so far). And some of them have quite a lot of data (e.g. loggers, metrics, http traces)

2) There are currently interactive features (setting log levels, updating environment, interacting with jmx) which are very hard to be adapted for this pattern.

3) AFAIK prometheus also spins up a sidecar with a http server for doing the scraping. And imho including the http server for getting the SBA part is a tradeoff which little pain but huge benefits. (We actually did that in projects using spring-batch)

**Comment by morrica** [comment]
@joshiste Thanks for your response.

If I understand the issues you raise correctly, solving 1 and 2 would probably require the client to setup and maintain a persistent TCP connection to the server for bi-directional communication rather than using a periodic push model. That way the server would only receive the data when an end user requested it through the web interface.

Your comment in 3 I'm not sure about. Sounds like you are commenting on the cost benefit of setting up an HTTP server on the client? Totally reasonable position. Like I said originally: Probably a lot of work. Probably would have limited benefit for most current users. Might improve things for some use cases like mine. 

I understand if this is something that never happens. Maybe better as a model for a separate project. :-)

**Comment by SteKoe** [comment]
Closed due to inacivity.
