### ISSUE TITLE
Disable IP Display on Admin 

### ISSUE THREAD

**Issue by winterpa** [codecentric/spring-boot-admin#1647]
We currently have our services register through Eureka and they register using internal Docker IPs. We would like the ability to not display the IPs as they won't be useful to anyone looking at the dashboard. Would like an ability to turn off showing the IPs if possible.

**Comment by SteKoe** [comment]
As SBA is an expert tool, we will not provide this feature. Anyway, you can change the shown IP / hostname by setting `server.address` or `management.address`. Their respective value will be used when `spring.boot.admin.client.instance.prefer-ip` is set to `true`. 

See: https://codecentric.github.io/spring-boot-admin/2.4.1/#spring-boot-admin-client
