### ISSUE TITLE
Logfile-Download-Link absent when management.port and server.port differ 

### ISSUE THREAD

**Issue by tobiasflohre** [codecentric/spring-boot-admin#165]
It seems like the download option for the log file on the overview page is only there when I don't set the management.port. When management.port and server.port differ, it's not there.
Can you confirm that or am I missing something?

**Comment by joshiste** [comment]
The ui queries the `/configprops` endpoint to look whether the `/logfile` endpoint is enabled.
The `/logfile`-endpoint is only enabled when your client hast the `logging.file` property set. So in case you are using boot's `launch.script` or some other `init.d` script, which just redirects the output, the `/logfile` endpoint is disabled.

**Comment by tobiasflohre** [comment]
I have logging.path in my application.properties, and I only run the applications from my IDE. And when I use a different management port, the logfile endpoint doesn't appear in /configprops though it's there and working.

**Comment by joshiste** [comment]
Indeed. That's bad. I'll have a look into this if it's a bug in Spring Boot or if we have to adapt the detection of the endpoint.

**Comment by joshiste** [comment]
Ok. The logfile endpoint is mvc only so the bean (and the associated configprops) is only created in the managment application context. So the detection of the endpoint needs a fix.
