### ISSUE TITLE
Forced logout without manualy logout while i clicked Spring boot admin node page

### ISSUE THREAD

**Issue by laskdjlaskdj12** [codecentric/spring-boot-admin#1651]
Cause case

1. clone this repository https://github.com/horyu1234/spring-boot-admin
2. change spring boot admin dependencies to 2.4.0 version (all of it server, server-ui, client)
3. run spring boot admin and login to main page
4. when you see image that i pase in, click client entity (any of client entity is okay)
![image](https://user-images.githubusercontent.com/16471540/109894191-61283980-7cd0-11eb-95b5-089852a37252.png)
5. you can see login page (Yeah that's it!)
6. goto "http://localhost:8080" you can see session is expire immediately.

**Comment by eavendano** [comment]
I found a way to replicate it constantly as well.
https://github.com/codecentric/spring-boot-admin/issues/1658#issuecomment-800744719

**Comment by Bad-Pop** [comment]
Hi, I have already posted an issue on this subject: #1649.
I think it would be more productive to all come together on one issue. What do you think  @eavendano and @laskdjlaskdj12 ?

**Comment by laskdjlaskdj12** [comment]
> Hi, I have already posted an issue on this subject: #1649.
> 
> I think it would be more productive to all come together on one issue. What do you think  @eavendano and @laskdjlaskdj12 ?

Yeah then i'll close this and rediect to that

**Comment by laskdjlaskdj12** [comment]
> > Hi, I have already posted an issue on this subject: #1649.
> > 
> > I think it would be more productive to all come together on one issue. What do you think  @eavendano and @laskdjlaskdj12 ?
> 
> Yeah then i'll close this and rediect to that

Oh you're tag to me. Then i'll leave thi.

**Comment by SteKoe** [comment]
We are dealing with this issue in #1649 and hence close this one.
