### ISSUE TITLE
Netty PrematureCloseException occuring in SpringWebClient

### ISSUE THREAD

**Issue by cjmarling** [codecentric/spring-boot-admin#1662]
At random times I'm seeing services being updated as OFFLINE due to netty PrematureCloseException across several of my services.  There appears to be an issue in either Spring WebFlux or in Netty itself that is causing this as I have seen other posts for this exception in those libraries

{
    "statusInfo": {
        "status": "OFFLINE",
        "details": {
            "exception": "reactor.netty.http.client.PrematureCloseException",
            "message": "Connection prematurely closed BEFORE response"
        }
    }
}

**Comment by SteKoe** [comment]
Superseded by #1711.
