### ISSUE TITLE
Scheduled fixedDelay & fixedRate not shown

### ISSUE THREAD

**Issue by timpamungkas** [codecentric/spring-boot-admin#1664]
On Boot 2.4.3 : `id 'org.springframework.boot' version '2.4.3'`  

Using spring boot admin client does not show `fixedRate` and `fixedDelay` scheduler on admin UI.  
This is the sample scheduler on client.

```java
@Service
public class SampleScheduler {

	@Scheduled(fixedDelay = 2000)
	public void runOne() {
		System.out.println("One");
	}

	@Scheduled(cron = "0 * * * * *")
	public void runTwo() {
		System.out.println("Two");
	}

	@Scheduled(fixedRate = 5000)
	public void runThree() {
		System.out.println("Three");
	}

}
``` 

But on admin UI, only `runTwo` (cron) that shown

![image](https://user-images.githubusercontent.com/17508786/111426117-baf41f00-8726-11eb-86cb-64341f0b175f.png)

Actuator endpoint from client returns all scheduler.

```json
{"cron":[{"runnable":{"target":"com.sample.scheduler.SampleScheduler.runTwo"},"expression":"0 * * * * *"}],"fixed_delay":[{"runnable":{"target":"com.sample.scheduler.SampleScheduler.runOne"},"initial_delay":0,"interval":2000}],"fixed_rate":[{"runnable":{"target":"com.sample.scheduler.SampleScheduler.runThree"},"initial_delay":0,"interval":5000}],"custom":[]}
```

**Comment by ahoehma** [comment]
`
class SchedulingHousekeeper implements SessionHouseKeeper {
    @Override
    @Scheduled(
      fixedRateString = "${spice.configcluster.session.housekeeper.interval:5000}", // default to 5 seconds
      initialDelay = 5000)
    public void cleanupConfigurations() {
...
`

And I can see the fixed rate:
![image](https://user-images.githubusercontent.com/548214/123772876-7dc62e00-d8cc-11eb-9a5a-5c3a94a367a7.png)

I'm using springboot 2.5.2, springbootadmin 2.4.2

**Comment by SteKoe** [comment]
Hi @timpamungkas,

you have to configure your service actuator endpoints to return camel case fields. See this issue as well: https://github.com/codecentric/spring-boot-admin/issues/1863#issuecomment-986070284

Since this is no bug, I will close this issue.
