### ISSUE TITLE
Spring Boot Admin Server unable to connect to clients with hostname

### ISSUE THREAD

**Issue by daanishsarguru** [codecentric/spring-boot-admin#1665]
On upgrading to Spring Boot Admin 2.4.0, our SBA Server is unable to reach client apps that have
`spring.boot.admin.client.instance.prefer-ip=false`
whereas it's able to connect to clients via IP which have
`spring.boot.admin.client.instance.prefer-ip=true`

The clients are able to register themselves to the server, but the server is not able to poll them back

I'm using Spring Boot Admin 2.4.0 for both the server and the clients
Also I'm using Spring Boot 2.4.3 with Spring Cloud Dependencies 2020.0.1

**Comment by SteKoe** [comment]
Hi @daanishsarguru,

can you please update SBA to 2.4.1 and check if the issue still remains? Did you ever get SBA working using `spring.boot.admin.client.instance.prefer-ip=false` (e.g. using SBA in version 2.3.X)?

**Comment by JimmyWe11s** [comment]
> Did you ever get SBA working using spring.boot.admin.client.instance.prefer-ip=false (e.g. using SBA in version 2.3.X)?

Yes it used to work earlier, tested with SBA 2.3.0

> can you please update SBA to 2.4.1 and check if the issue still remains?

Tested with SBA 2.4.1, got the same issue

**Comment by ulischulte** [comment]
Due to no further activity we close this issue.
