### ISSUE TITLE
The function of instance filtering and grouping

### ISSUE THREAD

**Issue by Kyrie-yx-Irving** [codecentric/spring-boot-admin#1680]
Dear Spring boot admin developer! 
Recently, our team wants to introduce spring boot admin as a global monitor service of all applications. However,  We found that we can't implement some functions without further development of the developer. We need two extra functions:
- **filter function**  : We need some filter function for authentication. for example, if person PA has the permission of service A and service B, he will see service A and Service B, while Person PB will only see service A if he has only the permission of service A
- **grouping function** :  we want to have a grouping function, for example, we need to know what services does A group contains and what services does B group contains because our team has too many services.

I think this two function is really important in daily usage for many people, I strongly recommended to add this two function,  so many people can use this two function.

**Comment by SteKoe** [comment]
This is some kind of special requirement addressing your use case. Feel free to fork this repo (as you have already done) and implement a custom SBA. Anyway, thanks for the work and PR, but we are not going to merge this feature request.
