### ISSUE TITLE
Read-only mode for sb-admin?

### ISSUE THREAD

**Issue by stevengibbszions** [codecentric/spring-boot-admin#1692]
@joshiste Any ideas how I might create a "READ ONLY" mode for SB Admin?  I am looking to grant access to a larger user-base within my organization, but I don't want them to make changes to running components, env variables, log levels, etc.  Any hints at how I might do that?

Any way to do that within WebSecurityConfig based on roles?

I'd be happy to do a PR or work on customizing my own instance depending on ideas/suggestions.

**Comment by SteKoe** [comment]
Hi @stevengibbszions,

did you try to add a Spring security matcher in SBA that prevents accessing `/instances/*/actuator/**` via POST (based on your logic) as shown in the docs? https://codecentric.github.io/spring-boot-admin/2.4.1/#_securing_spring_boot_admin_server

Please find attached the added line in the sample security configuration:

```
http.authorizeRequests(
  (authorizeRequests) -> authorizeRequests.antMatchers(this.adminServer.path("/assets/**")).permitAll() // <1>
      .antMatchers(this.adminServer.path("/actuator/info")).permitAll()
      .antMatchers(this.adminServer.path("/actuator/health")).permitAll()
      .antMatchers(this.adminServer.path("/login")).permitAll()
      .antMatchers(HttpMethod.POST, this.adminServer.path("/instances/*/actuator/**")).hasRole("ALLOW_WRITE") // CHANGED
      .anyRequest().authenticated()
```

**Comment by stevengibbszions** [comment]
> did you try to add a Spring security matcher in SBA that prevents accessing `/instances/*/actuator/**` via POST (based on your logic) as shown in the docs? https://codecentric.github.io/spring-boot-admin/2.4.1/#_securing_spring_boot_admin_server

yes!  @SteKoe thanks for the tip. Here is what I came up with.  it definitely gets the job done, but error messaging is not ideal.  But we can definitely live with it, as now this enables many more users to benefit from SBA in our PROD environments.

```java
    http.authorizeRequests(
        (authorizeRequests) -> authorizeRequests
            // ANONYMOUS
            .antMatchers(this.adminServer.path("/actuator/health")).permitAll()
            .antMatchers(this.adminServer.path("/assets/**")).permitAll()
            .antMatchers(this.adminServer.path("/login")).permitAll()
            // ADMIN ONLY FUNCTIONS
            .antMatchers(HttpMethod.POST, this.adminServer.path("/instances/**")).hasRole(adminRole)
            .antMatchers(HttpMethod.PUT, this.adminServer.path("/instances/**")).hasRole(adminRole)
            .antMatchers(HttpMethod.DELETE, this.adminServer.path("/instances/**")).hasRole(adminRole)
            .antMatchers(HttpMethod.POST, this.adminServer.path("/applications/**")).hasRole(adminRole)
            .antMatchers(HttpMethod.PUT, this.adminServer.path("/applications/**")).hasRole(adminRole)
            .antMatchers(HttpMethod.DELETE, this.adminServer.path("/applications/**")).hasRole(adminRole)
            .antMatchers(this.adminServer.path("/instances/**/actuator/heapdump")).hasRole(adminRole)
            // DEFAULT FOR ALL OTHER REQUESTS
            .anyRequest().hasAnyRole(adminRole, readOnlyRole))
```

**Comment by SteKoe** [comment]
I am glad that it works for you :)
