### ISSUE TITLE
SBA On-Startup Not Updating Status of All Instances of an Application - Zookeeper

### ISSUE THREAD

**Issue by odexue** [codecentric/spring-boot-admin#1694]
Service Discovery for finding clients - Spring Cloud Zookeeper
SBA version - 2.4.0
Spring Boot - 2.4.3

Scenario:
1) Application X has 3 instances published/registered in Zookeeper
2) SBA starts up and I can see in SBA Journal section that 3 instances were 'REGISTERED' for Application X
3) In Journal section still, only 1 instance has event logged as 'STATUS_CHANGED (UP)'
4) Subsequently, an event 'ENDPOINTS_DETECTED' is logged for the same instance in no. 3
5) No other events are logged at this point.

The above produces a state where 2 instances are 'down' in SBA UI, where in fact they aren't really (all 3 instances of Application X returns status UP when directly querying their actuator endpoints). I can also see in SBA logs that only 1 instance is being continually polled for /actuator/health, but not the other instances.

If I were to start up a 4th instance of Application X (while SBA is still running), this 4th instance will then be detected by SBA and will be continually polled as well (SBA UI will now show 2 instances UP and 2 instances down for Application X).

If I shutdown SBA and start it up again, only 1 instance of Application X is polled for health status. The other 3, at this point, do not seem be updated.

**Comment by odexue** [comment]
I have downgraded the SBA version to 2.3.1 and I don't encounter this issue anymore.

**Comment by jeffbswope** [comment]
I have a similar problem using manual/static service registration that I keep trying to find time to look into more.

When SBA is started, for some number of already-running services, seemingly at random, they will not fully show online in the admin UI.

Some will show gray/offline/unknown:
- If you drill in to the service detail you see the health result is UP.  
- Info and all other details are missing.
- journal shows `REGISTERED`, `STATUS_CHANGED (UP)` and nothing else.

Some will show green/up but the version information will not show on the wallboard:
- If you drill in to the service detail all seems fine.
- journal shows `REGISTERED`, `STATUS_CHANGED (UP)`, `ENDPOINTS_DETECTED` and `INFO_CHANGED` -- same as with services that are all good in the UI.

These are all generally services that are registered in the exact same way -- often with only a port difference from others exhibiting no bad behavior or a different flavor of bad behavior.

I have not observed either behavior in services that come online after SBA and bouncing the services seems to correct their representation in SBA after they come back up.

There's nothing notable in the logs, although I haven't had a chance to turn the log level up and see if I can follow what's going on...

We necessarily made some changes adapting to SBA 2.4.0 / SB 2.4.x / cloud 2020 so it's hard to compare apples-to-apples but all was fine in SBA 2.3.x.

**Comment by nickcaballero** [comment]
I'm seeing this same issue with instances registered in Eureka registry after upgrading to SBA 2.4.0.

**Comment by nickcaballero** [comment]
Reverting the changes to `InstanceEventPublisher.java` seems to fix it. UnicastProcessor is deprecated but it seems like the suggested fix has a different behavior.

https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Sinks.UnicastSpec.html#onBackpressureBuffer--

https://github.com/codecentric/spring-boot-admin/commit/9fa2dfd8b22041407a5eebb02d96bf8a0270acfa#diff-ee05cf1fb20e714260076705ee7640b619c15a1c515384e08bfd75ce685850e9

**Comment by jeffbswope** [comment]
Nice find.  I can confirm shading `InstanceEventPublisher` with an older version (https://github.com/codecentric/spring-boot-admin/blob/ee2d4b1f51f578202a90cf2117e6283fc69a6045/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/eventstore/InstanceEventPublisher.java) seems to resolve the issues I described above.

**Comment by SteKoe** [comment]
Hi guys,

try updating to SBA 2.4.1 and report back whether the issue still remains. 

TIA!

**Comment by jeffbswope** [comment]
Yes thanks and sorry I should have commented earlier.  I was able to revert the workaround after moving to 2.4.1 and all seems well.

**Comment by SteKoe** [comment]
I am glad that it helped. Thanks for reporting back!
