### ISSUE TITLE
when i upgrade 2.4.0  version SBA is bad

### ISSUE THREAD

**Issue by zhangran2616** [codecentric/spring-boot-admin#1695]
when i use 2.3.0  version . SBA is very good。

when i upgrade 2.4.0  version SBA is bad。
gateway service：
![image](https://user-images.githubusercontent.com/6472032/114294432-25ec0800-9ad1-11eb-99f5-851d8d154ad4.png)
Some of the menus on the left have disappeared

permission service:
![image](https://user-images.githubusercontent.com/6472032/114294467-72374800-9ad1-11eb-891e-4ff4c94c0ee3.png)
but after 1 second, the page is pushed out and logged in

Why some service points into the left menu is not, some service points into the direct exit login. The previous version worked as usual without any adjustments

my SBA  config：
![image](https://user-images.githubusercontent.com/6472032/114294534-f689cb00-9ad1-11eb-8bab-c84b2969e4ac.png)

**Comment by SteKoe** [comment]
Hi @zhangran2616,

could you please try out the release version 2.4.1 of SBA and report back if the problem still remains? 

TIA!

**Comment by zhangran2616** [comment]
> Hi @zhangran2616,
> 
> could you please try out the release version 2.4.1 of SBA and report back if the problem still remains?
> 
> TIA!

hi @SteKoe 
upgrade 2.4.1 version .The service is normal. thank you
why 2.4.0 version Can't use 。。
Version 2.4.1 has just been released

**Comment by SteKoe** [comment]
We have just released 2.4.1 which fixes an issue in version 2.4.0 that addresses service discovery and actuator handling. SBA 2.4.X is now built on top of Spring Boot 2.4 and migration from Spring Boot 2.3 to 2.4 was necessary which lead to errors in service handling. 

Anyways: Glad that 2.4.1 works for you!
