### ISSUE TITLE
Register spring mvc actuator

### ISSUE THREAD

**Issue by rasi-natbuild** [codecentric/spring-boot-admin#1698]
Can we register spring mvc actuator?

I manage to get below json from my exsisting MVC project but now I need to register it 

// 20210413154959
// http://localhost:8081/actuator

{
  "_links": {
    "self": {
      "href": "http://localhost:8081/actuator",
      "templated": false
    },
    "info": {
      "href": "http://localhost:8081/actuator/info",
      "templated": false
    },
    "health-component-instance": {
      "href": "http://localhost:8081/actuator/health/{component}/{instance}",
      "templated": true
    },
    "health-component": {
      "href": "http://localhost:8081/actuator/health/{component}",
      "templated": true
    },
    "health": {
      "href": "http://localhost:8081/actuator/health",
      "templated": false
    },
    "logfile": {
      "href": "http://localhost:8081/actuator/logfile",
      "templated": false
    }
  }
}

**Comment by SteKoe** [comment]
Hi @rasi-natbuild,

you need to set up a Spring Boot Admin server where applications are able to be listed. The basic usage is documented here: https://codecentric.github.io/spring-boot-admin/2.4.0/#getting-started

Since your requests seems to be "just" a question, we have removed the bug-flag.

**Comment by SteKoe** [comment]
Closed due to no response.
