### ISSUE TITLE
ApplicationRegistrator : Application registered itself as not happening when spring.boot.admin.client.auto-registration": false and "spring.boot.admin.client.register-once": false

### ISSUE THREAD

**Issue by patpatpat123** [codecentric/spring-boot-admin#1702]
Hello Spring Boot Admin Team,

Just wanted to raise an issue / observation.

We have multiple instances of SBA Server across different datacenter / regions. We then have business apps we want to report to all of them:

```
  "spring.boot.admin.client.url": "https://sba.us-east-1a.com,https://sba.us.us-west-3a.com:, etc... ",
```

Only when those two properties are false
```
  "spring.boot.admin.client.auto-registration": false,
  "spring.boot.admin.client.register-once": false,
```

We do not see the usual ```ApplicationRegistrator : Application registered itself as``` on startup

Putting back   "spring.boot.admin.client.auto-registration": to true will come back to the original expected bahaviour, the message is seen.

Thank you

**Comment by SteKoe** [comment]
Hi @patpatpat123, according to our documentation, `auto-registration` has to be set to `true` in your case since you are not using auto-discovery:

 > If [auto-registration is] set to true the periodic task to register the application is automatically scheduled after the application is ready.

**Comment by patpatpat123** [comment]
Got it, thanks
