### ISSUE TITLE
Public URL is resolves to wrong base url

### ISSUE THREAD

**Issue by michael-wirth** [codecentric/spring-boot-admin#1717]
Spring Boot Admin 2.4.1

The Spring Boot Admin is accessible through a WAF with public URL: **https://myhost:443/app/admin**
The application itself is using a context-path: **/admin** because it is deployed to a web application server as web archive.

The public URL is configured via spring configuration:
`spring.boot.admin.ui.public-url=https://myhost:443/app/admin`

The combination of the public URL and the context path resolve to: `https://myhost:443/admin/app/admin`. -> `<context-path>/<public-path>`, which is wrong

If I define a public URL why is it merged in the `UiController.getBaseUrl()` method? 
I'd like to use the public URL as IS and not have it modified for unknown reasons.

There is a workaround by defining the public URL as `https://myhost:443/../app/admin` which will resolve to:
`<base href="https://myhost:443/admin/../app/admin/">`

That is working but an ugly solution.

**Comment by SteKoe** [comment]
Closed due to inactivity. Feel free to reopen if issue still exists.

**Comment by scott-avery** [comment]
the problem still exists.
