### ISSUE TITLE
Microsoft Teams notifications are missing options for quick visual identification of status changes

### ISSUE THREAD

**Issue by olithissen** [codecentric/spring-boot-admin#1718]
The class [`MicrosoftTeamsNotifier.java`](https://github.com/codecentric/spring-boot-admin/blob/875cc286a4be089aa5f39c8b54a99405beba2f92/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/notify/MicrosoftTeamsNotifier.java) allows for some customization via its respective configuration properties (`spring.boot.admin.notify.ms-teams.*`).

None of them allows me to control the look of the notification message depending on its status: The theme color applies to all status changes (e.g. green for UP and green for DOWN) and the string templates are processed with `String.format()`. So there is no easy way to tell good status changes from bad ones at a glance. Other notifiers, like the `TelegramNotifier`, use SpEL instead and thus offer a wider variety of theming options.

![image](https://user-images.githubusercontent.com/13063051/116875443-3cdad180-ac1b-11eb-8744-d0294eeffb9f.png)

A possible solution might involve migrating from `String.format()` to `SpelExpressionParser` for properties like `themeColor`, `statusActivitySubtitlePattern`, etc. allowing the use of SpEL conditionals. (-> Colors or emojis depending on status change)

Thanks and keep up the good work!
Oli

**Comment by SteKoe** [comment]
Has been released as part of 2.4.2. See changenotes.
