### ISSUE TITLE
版本依赖

### ISSUE THREAD

**Issue by BayMax619** [codecentric/spring-boot-admin#1725]
使用springboot2.3.5-release 应该使用哪个版本?

**Comment by SteKoe** [comment]
Use Spring Boot Admin > 2.3.0. The first two numbers in SBA version refer to the minimum supported spring-boot version. Please ask this kind of question in our Gitter chat next time. https://gitter.im/codecentric/spring-boot-admin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
