### ISSUE TITLE
JMX operation timeout

### ISSUE THREAD

**Issue by lightoze** [codecentric/spring-boot-admin#173]
I have some longer (10s of seconds) application maintenance operations exposed over JMX, but Spring Boot Admin gives up on waiting for response too soon. It would be nice to have a longer timeout and/or have a documented way to change it. `zuul.host.socket-timeout-millis` seems to be the way, but it only works if I supply a system property and does not work in `application.yml`.

**Comment by joshiste** [comment]
After realizing that eclipse somehow added an ignore for `application.properties/.yml` to the build path, I found out that the property already gets propagated to the `SimpleHostRoutingFilter` and a correct configured `httpClient` gets instatiated in `SimpleHostRoutingFilter.newClient()`

**Comment by lightoze** [comment]
I found a reason for that - Zuul will only load Spring Boot configuration when `spring-cloud-netflix-core` is in dependencies, thanks to ArchaiusAutoConfiguration. Having only `spring-boot-admin-server` dependency is not enough.

**Comment by joshiste** [comment]
`spring-cloud-netflix-core` is a dependency of `spring-boot-admin-server` and so is atransitive dependency of your project and be on your classpath

**Comment by lightoze** [comment]
Indeed... seems to be an IDEA/Maven issue, I cannot reproduce the problem anymore.
