### ISSUE TITLE
Http trace and browser crashes. UP. Cause its real problem.

### ISSUE THREAD

**Issue by aam1go** [codecentric/spring-boot-admin#1733]
I see this problem here from 2018. Too many ISSUES. Every Issue answers something like this: Disable from serializer options: WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS, WRITE_DATES_AS_TIMESTAMPS  For example codes: 
```
public void extendMessageConverters(List<HttpMessageConverter> converters) {
        for (HttpMessageConverter converter : converters) {
            if (converter instanceof MappingJackson2HttpMessageConverter) {
                MappingJackson2HttpMessageConverter jsonMessageConverter = (MappingJackson2HttpMessageConverter) converter;
                ObjectMapper objectMapper = jsonMessageConverter.getObjectMapper();
                objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
                break;
            }
        }
}
```

But okay. This impacts on every message converts. Not only Actuator. This is not problem if it can solve this problem, But not: (

---THIS is cant help me... I Saw issues 18,19,20 year. And there some changes. But i use different versions of Spring boot and *Admin too. 

THEN: i found some code, that can fix this issue on actuator level type of media: 
```
@Bean
    public MappingJackson2HttpMessageConverter actuatorHttpMessageConverter() {
        MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter(Jackson2ObjectMapperBuilder.json().featuresToDisable(WRITE_DATES_AS_TIMESTAMPS).build());
        converter.setSupportedMediaTypes(Collections.singletonList(MediaType.parseMediaType(ActuatorMediaType.V2_JSON)));
        return converter;
    }
```

But and this code too cant help me. I Tried to use it in Spring Boot Admin Client at first. After i tried to use and in Admin server too. So why if works). Then Combine WRITE_DATES_AS_TIMESTAMPS with 
WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS. When combine it for: ActuatorMediaType.V2_JSON, ActuatorMediaType.V3_JSON - cause this is exist.

So i could find decision for this problem... I need help :)

**Comment by SteKoe** [comment]
Hi @aam1go, 

we do not quite get your problem and what you want to achieve. What is the actual error you are facing? To what other issues from 2018/2019 are you referring and what do you mean by "browser crashes"?

What versions of Spring Boot, Spring Boot Admin/Client, and Jackson are you using? Would it be possible for you to provide an example project that illustrates your issue?

**Comment by aam1go** [comment]
Hi, @SteKoe. 

Version Spring Boot was 2.3.7.RELEASE. And SBA 2.3.1 And then i update for 2.4.5 ,and SBA 2.4.1 Spring boot. But still same)
I tried with jdk 11,15. No resolution. When i read all same problems in ISSUES. There was info about http trace **timestamp** with nano "1622206219.333" - for example. So i do many shaman magic. But no. Jackson - fasterxml 2.11.4. ))).

So my problem possible to from **timestamps with nano**. I watch it when i go to */actuator/httptrace

**Comment by netbuffer** [comment]
Try it the way I did under this answer #1053

**Comment by ulischulte** [comment]
Due to no further activity we close this issue.
