### ISSUE TITLE
Mime types are not loaded

### ISSUE THREAD

**Issue by garunc** [codecentric/spring-boot-admin#1734]
Springbootadmin  2.4.1 version :
'org.springframework.boot' version '2.4.2'

application.properties
######################################
spring.boot.admin.ui.title=Admin
spring.boot.admin.ui.brand=<img src="assets/img/custom-logo-favicon.ico"><span>Aps Admin</span>
spring.boot.admin.ui.favicon=assets/img/custom-logo-favicon.ico
spring.boot.admin.context-path=/sba
spring.boot.admin.ui.public-url=http://adminapp:8080/sba
server.forward-headers-strategy=native
##############################
nginx configurations
################
server {
    listen 8080;

   
     location /sba {
      proxy_pass http://app.com:8080/sba;

      proxy_set_header X-Forwarded-Port $server_port;
      include /etc/nginx/mime.types;
      location ~ \.css{
      add_header Content-Type text/css;
      }
    }
  }

Error:
Refused to apply style from 'http://mydomain.com:8080/sba/assets/css/sba-core.e8cbb3e1.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled

Please let me know where am i doing wrong.

**Comment by erikpetzold** [comment]
Hi @garunc,

I'm no nginx expert, but I think the mime type config belongs to some "higher" level, it should be placed under "http" in your config, not within the location. 

See the full config example here: https://www.nginx.com/resources/wiki/start/topics/examples/full/

**Comment by garunc** [comment]
Hi @erikpetzold thank you ,the issue is resolved now thank you.
what i have done is below nginx configurations .
http{
// mimetypes.
server{
location /sba {
  proxy_pass http://app.com:8080;
}
}
}
