### ISSUE TITLE
About listening to useless services can filter out the problem

### ISSUE THREAD

**Issue by HaoLi-Rainbow** [codecentric/spring-boot-admin#1736]
Spring Boot Admin Versions：2.3.1
Spring Boot Versions：2.3.2.RELEASE
Hello, I springboot admin and nacos (registry) integration, as springboot admin will get nacos service list, resulting in him listening to a lot of rpc services, but these rpc services specific confidence but can not get, there is no version that allows him to filter out these rpc services listening, otherwise it will lead to my services here is very messy, as shown in the figure, (the gray is the rpc services)

![image](https://user-images.githubusercontent.com/49888630/120879509-6742f480-c5f6-11eb-94e8-7a661893479d.png)
![image](https://user-images.githubusercontent.com/49888630/120879541-a7a27280-c5f6-11eb-97e0-6cd438afe33e.png)

**Comment by andreasfritz** [comment]
Have you tried to filter services via these properties:
- spring.boot.admin.discovery.ignored-services
- spring.boot.admin.discovery.services
- spring.boot.admin.discovery.ignored-instances-metadata
- spring.boot.admin.discovery.instances-metadata

see [Discovery configuration options](https://codecentric.github.io/spring-boot-admin/current/#spring-cloud-discovery-support)

I am using spring.boot.admin.discovery.instances-metadata to filter Spring Boot Apps in a Kubernetes Cluster.
spring.boot.admin.discovery.instances-metadata.spring-boot-admin=true
Only the Kubernetes pods that are tagged with spring-boot-admin=true are monitored by Spring Boot Admin.

**Comment by HaoLi-Rainbow** [comment]
> Have you tried to filter services via these properties:
> 
> * spring.boot.admin.discovery.ignored-services
> * spring.boot.admin.discovery.services
> * spring.boot.admin.discovery.ignored-instances-metadata
> * spring.boot.admin.discovery.instances-metadata
> 
> see [Discovery configuration options](https://codecentric.github.io/spring-boot-admin/current/#spring-cloud-discovery-support)
> 
> I am using spring.boot.admin.discovery.instances-metadata to filter Spring Boot Apps in a Kubernetes Cluster.
> spring.boot.admin.discovery.instances-metadata.spring-boot-admin=true
> Only the Kubernetes pods that are tagged with spring-boot-admin=true are monitored by Spring Boot Admin.
thank
