### ISSUE TITLE
Active profiles on application view list items

### ISSUE THREAD

**Issue by selimok** [codecentric/spring-boot-admin#1740]
Hi, 

On the application view the instances are listed by their names and version. If I expand any application item, I can see additionally their IP addresses and applicationIds. But sometimes it would be helpful to get more detail about the instance such as active profiles for easy differentiation.  

I think there is enough space on the item bar for displaying active profiles and such an improvement can help to increase general usability. 

Thanks

**Comment by Glosur** [comment]
If you want to use an already existing feature, you can show tags per instance https://codecentric.github.io/spring-boot-admin/2.4.3/#show-instance-tags

Depending on how you register your clients, you could then map the property to the active profiles
```yaml
info:
  tags:
    profiles: ${spring.profiles.active}
```

This then looks like the attached screenshot


![image](https://user-images.githubusercontent.com/14371287/127771698-2da9f710-7e24-4b41-8c48-e9ab934709c7.png)

**Comment by ilyastuit** [comment]
> If you want to use an already existing feature, you can show tags per instance https://codecentric.github.io/spring-boot-admin/2.4.3/#show-instance-tags
> 
> Depending on how you register your clients, you could then map the property to the active profiles
> 
> ```yaml
> info:
>   tags:
>     profiles: ${spring.profiles.active}
> ```
> 
> This then looks like the attached screenshot
> 
> ![image](https://user-images.githubusercontent.com/14371287/127771698-2da9f710-7e24-4b41-8c48-e9ab934709c7.png)

Does this mean that this feature already exists and the issue is not actual now?

**Comment by selimok** [comment]
Hi @LaSylv, 
Thank you for your answer. This is exactly what I'm looking for. 
This means we can close this issue, since the feature already exists (but a little bit hidden :)
