### ISSUE TITLE
Environment information 'line.separator' is not visible

### ISSUE THREAD

**Issue by plumstone** [codecentric/spring-boot-admin#1744]
The property is not displayed probably because it is not escaped.

![grafik](https://user-images.githubusercontent.com/37106962/122365313-d9063100-cf5a-11eb-995b-3395150fd327.png)

From the actuator it is delivered as follows.

![grafik](https://user-images.githubusercontent.com/37106962/122366028-7cefdc80-cf5b-11eb-99c4-4962bded9b39.png)

Tested with Spring Boot 2.5.1 and Spring Boot Actuator 2.4.1.

**Comment by SteKoe** [comment]
Fix will be included in next release.
