### ISSUE TITLE
bad uri of endpoints

### ISSUE THREAD

**Issue by miqi770** [codecentric/spring-boot-admin#1745]
Dear all 

here is one of my instance from wallboard, when I click the instance just goes to below url
"http://192.168.30.3:8080/instances/%5Bobject%20Object%5D/details"

so I got the "503" http status code;

and one more scenario : goes to Heap Dump and F12 to look up html as below :

[a href="instances/[object Object]/actuator/heapdump" target="_blank"]

so my question , is it a bug or someting othes ?

spring-boot version   2.3.4.RELEASE
spring-boot-admin version 2.3.1

**Comment by SteKoe** [comment]
Hi,

please have a look at issue #1446 and check if the provided solutions and hints help you. If not, post the content of `/applications` call in wallboard here, and we check further steps.
