### ISSUE TITLE
Two different instances of one same app are not registering with the same ID

### ISSUE THREAD

**Issue by patpatpat123** [codecentric/spring-boot-admin#1746]
Hello Spring Boot Admin Team,

I wanted to raise an issue, where two different instances of one same app, but deployed in different regions, are now registered with the same ID, when it was not the case before.

To put a concrete example, I have one booking service deployed in Africa, another instance of booking service deployed in Europe, they are the same booking service.

Both booking services wants to be registered with Spring Boot Admin.

On application start up of booking service, I am seeing this: Note one is for the instance in Africa, one from Europe.

```
[gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Application registered itself as 4a42bbde48e4

[gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Application registered itself as 1a34ccde18c3
```

Unfortunately, it is now registered with the same ID for both apps. We are sure, because we dumped the log of the instance from Africa, and the log of the instance from Europe.

Both have this same line: ```[gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Application registered itself as 4a42bbde48e4```

May I ask, how is this ID computed in the first place?

May I ask, how if it is possible to override the ID, with some property like: ```spring.boot.admin.registered.id=my_service_in_europe```?

What would make both apps have same ID, root cause of this issue please?

Thank you

**Comment by erikpetzold** [comment]
Hi @patpatpat123 ,

the instance id is generated from health url of the registered app. So you should make sure your instances have different health urls (which is required for proper monitoring anyways).

Please also note, that this is not true for a Cloud Foundry setup, so if you are using Cloud Foundry make sure your metadata there is correct.

**Comment by patpatpat123** [comment]
Understood @erikpetzold, Thank you
