### ISSUE TITLE
How does spring boot admin monitor the service of HTTPS

### ISSUE THREAD

**Issue by xiaqinghh** [codecentric/spring-boot-admin#1747]
When I test locally, I prompt "unable to find valid certification path to requested target"。How can I monitor the service of HTTPS?

**Comment by xiaqinghh** [comment]
It's the Java language

**Comment by xiaqinghh** [comment]
spring-boot-admin-starter-server 2.2.4

**Comment by SteKoe** [comment]
Hi @xiaqinghh ,

this seems to be a general issue with Java and the truststore. I assume you are using SSL Certificates that are self-signed or not included in the truststore of your locally installed Java. So please check the web on how to add the certificate of the server you are trying to connect to.
