### ISSUE TITLE
Refreshing the trace items causes duplicate entries

### ISSUE THREAD

**Issue by chrisschauer** [codecentric/spring-boot-admin#175]
On the trace page the refresh button does not work correctly!

**Process:**
* Request an endpoint
* Go to trace page on spring boot admin ui
* Hit the refresh button

**Observation**
* Old items were duplicated

The /trace endpoint works correct. 

**Assumption**
The item list isn't cleared on hitting the refresh button.
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/app/js/controller/apps/traceCtrl.js#L29

![trace_error](https://cloud.githubusercontent.com/assets/5363619/14167707/66b0324c-f71d-11e5-9bf2-c33c27a3cbbf.JPG)

**Comment by joshiste** [comment]
I've already observerd this problem. I have a fix in my https://github.com/joshiste/spring-boot-admin/tree/pluggable-ui for that problem, which I'll merge
