### ISSUE TITLE
Support Cache Actuator on Application Level too

### ISSUE THREAD

**Issue by ahoehma** [codecentric/spring-boot-admin#1752]
If one runs multiple instances for an application it would be nice to clear a cache for ALL instances at "once".
Like the functionality for the logger. One  can switch between Instance and Application.

**Comment by erikpetzold** [comment]
Hi @ahoehma, 
thanks for your suggestion - sounds like a good idea, but we don't know when we will have time for this.

We are open for contributions, so you could also provide a Pull Request. All the basic building blocks should already be there (clearing the cache, doing action for all instances).
