### ISSUE TITLE
Requests should use session cookie

### ISSUE THREAD

**Issue by fiveOO** [codecentric/spring-boot-admin#1768]
I noticed that SBA is creating a new session at the monitored application for every request as SBA is not using the cookie retrieved with the previous response but sending the authentication with every request again and again (=pre-emptive authentication).

This leads in (my case) to some 1000 open sessions at the monitored application just waiting for their timeout.

SBA should remember the cookies received from the monitored application and send them in the next requests.

**Comment by fiveOO** [comment]
I have a solution that is working for me based on an InstanceExchangeFilterFunction. Please let me know if you want to add that feature to SBA in principle. Then I will "polish" it and create a PR.

**Comment by ulischulte** [comment]
@fiveOO,
please feel free to contribute :)

**Comment by ulischulte** [comment]
related to #1786
