### ISSUE TITLE
Make Environment accessible in mail SpEL-expressions

### ISSUE THREAD

**Issue by oxygensar** [codecentric/spring-boot-admin#177]
I'm trying to add additional information (like link to spring boot admin's url) to the mail body but it seems that only ClientApplicationStatusChangedEvent properties are available to SpeL parser.

Is it possible to add the Environment object to the parser's evaluation context?

**Comment by joshiste** [comment]
Sure I think it would be a good enhancement.

**Comment by joshiste** [comment]
Hmm are you configuring your subject / text from an `application.properties` or `.yml` ? In case yes you can already use property placeholders `${...}` which get resolved against the environment so I have to revert my opinion and there is no need to make the `Environment` accessbile...

**Comment by joshiste** [comment]
Closed due to missing response.

**Comment by oxygensar** [comment]
Sorry for late response. You're right. When configuring message text via application properties they first get resolved by Spring and only later by Spring Boot Admin when actually sending the message. Probably it's worth mentioning this explicitly in the docs. Thank you!
