### ISSUE TITLE
SBA use nginx configured HTTPS proxy forward to HTTP error

### ISSUE THREAD

**Issue by MorganArthur** [codecentric/spring-boot-admin#1770]
![image](https://user-images.githubusercontent.com/24489342/125903832-d50d856e-9f4f-44c3-b5e3-e371215d205a.png)

![image](https://user-images.githubusercontent.com/24489342/125904542-0882a350-b833-445c-90ef-c6fc507af1be.png)

I used nginx to proxy my SBA, and the configured HTTPS changed to HTTP when forwarding. I did not find a suitable configuration in the documentation to fix this problem.

Is there something wrong with my configuration？

version: 2.4.2

![image](https://user-images.githubusercontent.com/24489342/125904286-b05e45c9-f999-4d78-8cfa-7ede0aa526e1.png)
![image](https://user-images.githubusercontent.com/24489342/125904318-e92c1e55-83aa-4dca-916d-4f0ae88a254a.png)

**Comment by ulischulte** [comment]
Hi @MorganArthur,
please try to set ```server.forward-headers-strategy``` to ```NATIVE```
(https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.use-behind-a-proxy-server)

**Comment by MorganArthur** [comment]
> 嗨@MorganArthur，
> 请尝试设置`server.forward-headers-strategy`为`NATIVE`
> （https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.use-behind-a-proxy-server）

I've tried. problem has been solved. Thank you very much.
