### ISSUE TITLE
Spring Boot Admin Deprecated now?

### ISSUE THREAD

**Issue by kapilsoni2013** [codecentric/spring-boot-admin#1773]
Please check below snapshot from Spring Initializer. It is showing Admin dashboard deprecated? 
If its deprecated then what is alrernative?
![image](https://user-images.githubusercontent.com/29603970/126899386-09006fe0-82fd-4f40-b54a-9a871ecafb06.png)

**Comment by SteKoe** [comment]
hi @kapilsoni2013,

Spring Boot Admin is not deprecated. We have not updated start.spring.io, yet but will do so. You can still use and rely on SBA.

**Comment by kapilsoni2013** [comment]
Thanks @SteKoe for the giving quick update.

**Comment by SteKoe** [comment]
https://github.com/spring-io/start.spring.io/pull/743
