### ISSUE TITLE
Spring Boot Admin Not Show Login

### ISSUE THREAD

**Issue by hendisantika** [codecentric/spring-boot-admin#1776]
Nice article,
I want to ask why my Spring Boot Admin Not Show Login Page?

https://github.com/hendisantika/SpringBootAdminDemo

![image](https://user-images.githubusercontent.com/3713580/127725272-6636b422-c7b4-44dc-ab59-e934175894d4.png)

Thanks

**Comment by SteKoe** [comment]
Hi @hendisantika,

the example project you provided works like a charm on my machine. I have checked it out and started Eureka, SBA and the customer service. Login and detection of applications work as expected.

![Screenshot from 2021-07-31 20-39-20](https://user-images.githubusercontent.com/1809221/127749550-a1007a68-f935-4a27-8424-27300718dcc5.png)

![Screenshot from 2021-07-31 20-38-56](https://user-images.githubusercontent.com/1809221/127749541-e1fd9e00-da29-4d6e-9156-753e1d81e2da.png)

**Comment by hendisantika** [comment]
Hmmm... But, I try on my local machine it didn't work.

**Comment by hendisantika** [comment]
OK. I don't now it's working.
