### ISSUE TITLE
What is this url http://localhost:8001/.metrics 

### ISSUE THREAD

**Issue by Arpanparikh** [codecentric/spring-boot-admin#1796]
http://localhost:8001/.metrics
What is this url and why is it called? Correct metrics url is http://localhost:8001/abc/actuator/metrics

I have prefixed all actuator endpoints with /abc. So my new endpoints are like http://localhost:8001/abc/instance
http://localhost:8001/abc/actuator/health. This is working fine.

I have used below properties for this :
management.endpoints.web.base-path=/abc/actuator
spring.boot.admin.client.url=http://localhost:8001/abc
spring.boot.admin.client.instance.health-url=http://localhost:8001/abc/actuator/health
spring.boot.admin.context-path=config

But the problem is , http://localhost:8001/.metrics is not moved under abc. 
1. What is this url and why is it called?
2. How can I move this url to /abc. http://localhost:8001/abc/.metrics

**Comment by erikpetzold** [comment]
Hi @Arpanparikh,

we're missing some context here, can you please provide some more details:
- who is calling /.metrics? You ask why it is called, what do you mean with that? Is it called by SBA Server? Where do you see it is called?
- Are we talking about SBA Server monitoring itself? (SBA Server is monitoring some client applications, including itself)
- Does http://localhost:8001/.metrics return some useful response?

**Comment by Arpanparikh** [comment]
- That is my question as well. I am not calling this URL, but I see a call to this URL every minute in my logs. I suspect it must be SBA server
- SBA server and client are in the same application. I have registered the client and I can see all the details without any problem in SBA UI
- No, just 404
The problem is I don't know who is calling this URL and why, but it is being called every minute and that is flooding my logs.
So, I want to stop this from being called or move this under /abc.

**Comment by erikpetzold** [comment]
If you say the SBA UI is working fine then I guess the wrong calls are not coming from SBA. If it would call wrong endpoint, it would not be working.

Is the page under insights -> metrics fine? 
http://localhost:8001/instances/<instance-id-here>/metrics
That would be the page displaying data from the metrics endpoint (if enbaled).

To be sure you could check the network tab of your Browser Dev Tools if there are any requests to the /.metrics from the SBA page.

Maybe there is some other tool scraping metrics? Something configured on cluster level?

**Comment by erikpetzold** [comment]
closing old ticket, if there are still problems feel free to reopen or create a new ticket
