### ISSUE TITLE
Logging Loggers/filters do not validate the package existence, allowing to create a logger for non-existing packages

### ISSUE THREAD

**Issue by pgouri017** [codecentric/spring-boot-admin#1809]
Logging->Loggers/filters do not validate the package existence, allowing to create logger for non-existing packages

I tried creating a new logger for a non-existing package "my.test.logger.package"

<img width="572" alt="image" src="https://user-images.githubusercontent.com/71350567/133100636-6d6c1f91-6e7e-40b2-b268-457282626820.png">

This is not a blocker, but sometimes people create random loggers in the test environments, making the logger view messy and confusing.

**Comment by erikpetzold** [comment]
Hi @pgouri017 

the Logger name is just a name and can be any String. Often the package+classname is used (by convention)... but you could pass any String when creating the logger. This is a Feature of the logging libraries and has nothing to to with SBA.
So of course you can override any logger name and there is no validation for packages.
