### ISSUE TITLE
Springbootadmin error

### ISSUE THREAD

**Issue by ssumathy** [codecentric/spring-boot-admin#182]
I have springboot admin server application running on Jboss and I get the following error while trying to register a client: 

2016-04-15 09:44:57 WARN  ApplicationRegistrator:96 - Failed to register application as Application [id=null, name=dlod, managementUrl=http://localhost:8080/xxx/actuator, healthUrl=http://localhost:8080/xxx/actuator/health, serviceUrl=http://localhost:8080/xxx] at spring-boot-admin (http://localhost:8080/monitoringadmin/api/applications): 404 Not Found

I am able to bring up the springbootadmin server, however I also see an error on the Journal link:

![image](https://cloud.githubusercontent.com/assets/18488844/14570577/0c5226a0-0313-11e6-94c8-00665f3e0316.png)

Can you please suggest if I am missing something. The spring boot admin server has the following dependencies on pom:
                   <dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-server</artifactId>
			<version>1.3.2</version>
		</dependency>
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-server-ui</artifactId>
			<version>1.3.2</version>
		</dependency>

**Comment by joshiste** [comment]
Hi, looks like your `http://localhost:8080/monitoringadmin/api/applications` isn't started correctly. Did you check your logs for errors during startup? Do you have a small sample for me to reproduce the problem?

**Comment by ssumathy** [comment]
Thank you for getting back to me. I am attaching the admin project. Please let me know if I am missing something.


Thank you
Sandhya
[monitoringadmin.zip](https://github.com/codecentric/spring-boot-admin/files/223605/monitoringadmin.zip)

**Comment by joshiste** [comment]
Your `MonitoringadminApplication` class only works for fat-jars not for war deployment.
Have a look at our [war-sample](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-war/src/main/java/de/codecentric/boot/admin/SpringBootAdminApplication.java) to see how to run a spring-boot-application inside a servlet-container.

**Comment by joshiste** [comment]
I've added a note in the docs for this.
You also could just deploy our [sample war-file from maven-central](http://repo1.maven.org/maven2/de/codecentric/spring-boot-admin-sample-war/1.3.2/spring-boot-admin-sample-war-1.3.2.war) right away.

**Comment by ssumathy** [comment]
Thank you Johnannes for getting back to me. I followed your sample-war and
converted my monitoringapplication class to work for war deployment.

I believe the monitoring admin is coming up ok now per the below log. But,
still my client is not able to register and gives me this exception:

08:52:25,739 INFO [stdout] (pool-16-thread-1) 2016-04-18 08:52:25 WARN
ApplicationRegistrator:95 - Failed to register application as Application
[id=null, name=dlod, managementUrl=http://localhost:8080/dlod/actuator,
healthUrl=http://localhost:8080/dlod/actuator/health, serviceUrl=
http://localhost:8080/dlod] at spring-boot-admin (
http://localhost:8080/monitoringadmin/api/applications): 404 Not Found

*******************Log
Details*********************************************************

08:49:18,273 INFO
[org.springframework.jmx.export.annotation.AnnotationMBeanExporter]
(ServerService Thread Pool -- 113) Registering beans for JMX exposure on
startup

08:49:18,283 INFO
[org.springframework.jmx.export.annotation.AnnotationMBeanExporter]
(ServerService Thread Pool -- 113) Bean with name 'zuulEndpoint' has been
autodetected for JMX exposure

08:49:18,300 INFO
[org.springframework.jmx.export.annotation.AnnotationMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'zuulEndpoint':
registering with JMX server as MBean
[org.springframework.cloud.netflix.zuul:name=zuulEndpoint,type=RoutesEndpoint]

08:49:18,312 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Registering beans for JMX exposure on
startup

08:49:18,318 INFO
[org.springframework.context.support.DefaultLifecycleProcessor]
(ServerService Thread Pool -- 113) Starting beans in phase 0

08:49:18,320 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean
'requestMappingEndpoint': registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=requestMappingEndpoint]

08:49:18,332 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean
'environmentEndpoint': registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=environmentEndpoint]

08:49:18,337 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'healthEndpoint':
registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=healthEndpoint]

08:49:18,344 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'beansEndpoint':
registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=beansEndpoint]

08:49:18,350 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'infoEndpoint':
registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=infoEndpoint]

08:49:18,355 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'metricsEndpoint':
registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=metricsEndpoint]

08:49:18,366 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'traceEndpoint':
registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=traceEndpoint]

08:49:18,373 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'dumpEndpoint':
registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=dumpEndpoint]

08:49:18,380 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean
'autoConfigurationReportEndpoint': registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=autoConfigurationReportEndpoint]

08:49:18,386 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean
'configurationPropertiesReportEndpoint': registering with JMX server as
MBean
[org.springframework.boot:type=Endpoint,name=configurationPropertiesReportEndpoint]

08:49:18,391 INFO
[org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter]
(ServerService Thread Pool -- 113) Located managed bean 'archaiusEndpoint':
registering with JMX server as MBean
[org.springframework.boot:type=Endpoint,name=archaiusEndpoint]

08:49:18,408 INFO [com.fhlbatl.MonitoringadminApplication] (ServerService
Thread Pool -- 113) Started MonitoringadminApplication in 12.789 seconds
(JVM running for 593.711)

08:49:18,413 INFO
[org.springframework.cloud.netflix.zuul.ZuulFilterInitializer]
(ServerService Thread Pool -- 113) Starting filter initializer context
listener

08:49:20,764 INFO
[org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/dlod]]
(ServerService Thread Pool -- 148) jolokia: jolokia:type=Config is already
registered. Adding it with
jolokia:type=Config,uuid=c42ecd15-91cd-4954-8a1e-942d8b11f617, but you
should revise your setup in order to either use a qualifier or ensure, that
only a single agent gets registered (otherwise history functionality might
not work)

08:49:20,764 INFO
[org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/dlod]]
(ServerService Thread Pool -- 148) jolokia: Cannot register (legacy) MBean
handler for config store with name jmx4perl:type=Config since it already
exists. This is the case if another agent has been already started within
the same JVM. The registration is skipped.

08:49:20,764 INFO
[org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/dlod]]
(ServerService Thread Pool -- 148) jolokia: Jolokia Discovery MBean
registration is skipped because there is already one registered.

**Comment by joshiste** [comment]
Did you check the path `http://localhost:8080/monitoringadmin/api/applications` is correct?

**Comment by joshiste** [comment]
You also have duplicat MBean names have a look at the spring boot reference guide to make them unique.

http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-custom-mbean-names

**Comment by ssumathy** [comment]
Johannes,

Thank you very much for your help. I finally got it working. I had to
define my the following setting in my application.properties to make it
work in Jboss:

server.servlet-path=/*

Also, I set the setting to make the MBean unique.

One more question. Do you have any samples to show you can configure
security if the client application endpoints have been secured?

Thank you
Sandhya

**Comment by joshiste** [comment]
Either you use the same password in all your apps for the management endpoints or you can try the session / oauth2 examples from https://github.com/joshiste/spring-boot-admin-samples

**Comment by ssumathy** [comment]
Thank you Johannes.

On Mon, Apr 18, 2016 at 11:07 AM, Johannes Edmeier <notifications@github.com

**Comment by joshiste** [comment]
>One more question. Do you have any samples to show you can configure
security if the client application endpoints have been secured?

I've put up a simple example. Have a look.
https://twitter.com/joshiste/status/722888734878748676

**Comment by ssumathy** [comment]
Johannes

Can you please sent me the link one more time? 
Thank you again

Sandhya

**Comment by ssumathy** [comment]
Got it. Please ignore the previous message.

Thank you for your help!

**Comment by ssumathy** [comment]
Johannes,

I have a follow-up question on the security configuration. Should the admin
server and resource server be deployed on two different ports ? Can the
Spring boot admin and the registering application be deployed on to the
same port ?

Thank you
Sandhya

**Comment by ssumathy** [comment]
Johannes,

I have configured my admin server and resource server based on the 'basic
auth' example you provided and was successfully able to register my app to
the admin server. But, I am still facing an issue. I have spring security
wrapped around my application and use LDAP for authentication. So when the
admin server tries to hit the application to retrieve status, it gets
redirected to our Login page. Below I have provided the code for my spring
security configuration.

Have you encountered something similar and have a workaround to bypass this
?   Please let me know if I should open a new help ticket.

@Override

*protected* *void* configure(HttpSecurity http) *throws* Exception {

http.authorizeRequests().antMatchers("/login*").anonymous()

.antMatchers("/**").authenticated().and().formLogin()

.loginPage("/login").defaultSuccessUrl("/home", *true*)

.failureUrl("/login?error=true").and().logout()

.logoutUrl("/j_spring_security_logout")

.logoutSuccessUrl("/login").permitAll().and().csrf().disable();

}
Thank you again for all your help. Very much appreciated.

Sandhya

On Mon, Apr 18, 2016 at 11:07 AM, Johannes Edmeier <notifications@github.com

**Comment by joshiste** [comment]
you need to enable the basic auth mechanism (at least for the actuator
endpoints), your config doesn't do that. Also the "/health" has to be
accessible without any authentication.
