### ISSUE TITLE
More leniently handle metrics with no tags defined

### ISSUE THREAD

**Issue by deadpassive** [codecentric/spring-boot-admin#1821]
My service has Jackson configuration which means that my metrics are serialized with no `availableTags` field. For example, the serialized metrics looks like the following:

```
{
    "name": "my_metric",
    "description": "A custom metric",
    "measurements": [
        {
            "statistic": "COUNT",
            "value": 0.0
        }
    ]
}
```

This currently breaks the Spring Boot Admin UI with the following error being shown in the browser console:

```
Fetching metric tags failed: TypeError: Cannot read properties of undefined (reading 'forEach')
    at index.vue:196
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

My guess is that it's trying to loop over the tags which are undefined.

Unfortunately the Jackson config responsible for serialising the metrics is not something I can easily change. Is it possible to more leniently handle the missing field and treat it as an empty list of tags?

I am currently using:

Spring Boot Admin version: 2.4.3
Spring Boot version: 2.4.3

**Comment by erikpetzold** [comment]
I ported the small fix to 2.4.x and released 2.4.4
however, we recommend updating SBA to 2.5.x to have the newest features and fixes (no need to update your monitored applications)
