### ISSUE TITLE
How to show all log files?

### ISSUE THREAD

**Issue by jameswuwu** [codecentric/spring-boot-admin#1844]
** Question **
I want Springboot Admin to show all log files, not just one

** Enhancement **
My Logback generates multiple history log files, as shown in the figure below

![image](https://user-images.githubusercontent.com/52489194/137246433-f41c72fe-da55-424c-87f1-6b0daa4c6067.png)

I can only access the log files of that day through springboot Admin，The YML configuration is as follows

![image](https://user-images.githubusercontent.com/52489194/137246645-3aaffbf5-7753-4e80-9bc6-935f3bfa1dfe.png)

Springboot admin screenshots is as follows

![image](https://user-images.githubusercontent.com/52489194/137246883-44ebe5a3-4f1c-44a4-bd1c-87acea255903.png)

I don't know how to view other log files via springboot admin

thanks!

**Comment by erikpetzold** [comment]
Hi @jameswuwu ,

the data that Spring Boot Admin is showing here is coming from Spring Boot Actuator in your application, in this case from the "logfile" actuator. 

From the docs and code it seems this actuator can only return logs from one file, so nothing we ca do here.
