### ISSUE TITLE
Refresh page error "Whitelabel Error Page"

### ISSUE THREAD

**Issue by zxiaozhou** [codecentric/spring-boot-admin#1849]
## Implementation steps
1. Normal page opening
![image](https://user-images.githubusercontent.com/62740686/139533117-86e7f059-b4f9-42ac-beec-555bbbde329d.png)
2. Refresh page
![image](https://user-images.githubusercontent.com/62740686/139533126-167e602d-fd87-461a-9d02-fd8304b3b101.png)

## problem  version:
2.4--->now version

## Attention
I set up webflux base-path. It is normal not to set webFlux base-path, but I need a prefix, not being able to set it is not ideal
```
spring:
  webflux:
    base-path: /monitor
```

**Comment by erikpetzold** [comment]
Hi @zxiaozhou ,
this is still the same problem as in #1772, right? (you commented the problem still happens, but did not reopen the ticket, so it was closed and did not appear in our list)
We will have a look again.

**Comment by ulischulte** [comment]
I was able to reproduce the issue with this sba-example: https://github.com/ulischulte/spring-boot-admin-examples/tree/main/spring-boot-admin-webflux

The pull request above should fix the problem.

**Comment by antechrestos** [comment]
Same here; before webflux, by only setting `server.servlet.context-path` to, let's say `/admin` and reverse-proxifying using spring cloud gateway (for example) did the trick without having to set the `spring.boot.admin.ui.public-url`.

However, now it does not; indeed, without setting `spring.boot.admin.ui.public-url`, `spring.boot.admin.context-path` to `/admin` and `forward-headers-strategy`to `native`, the html attempt to load from internal address (https://<eureka registered address>:<eureka registered port>/admin/assets/css/chunk-common.a3a93490.css)

**Comment by antechrestos** [comment]
@ulischulte I've tested locally your fix and it works like a charm :ok_hand:

**Comment by antechrestos** [comment]
Thanks @ulischulte.

Do you know if there will be an official release?

Thanks and have a nice weekend

CC @erikpetzold

**Comment by ulischulte** [comment]
Version 2.5.4 has just been released (https://github.com/codecentric/spring-boot-admin/releases). It may take some time until it's available in maven-central.

**Comment by antechrestos** [comment]
@ulischulte thanks! I was only looking at the badge on readme 🤭
Great. 👌
