### ISSUE TITLE
How to persist monitoring data to MySQL

### ISSUE THREAD

**Issue by feixiaoduo** [codecentric/spring-boot-admin#1851]
I want to persist the interface monitoring information to MySQL for subsequent statistical analysis. How can I persist it? Is there such an interface

**Comment by erikpetzold** [comment]
Hi @feixiaoduo 
there is no default way to store monitoring information to mysql. To persist the data you can use hazelcast and configure it to be persistent. 
To have the data in a relational database for analytics or search you would have to implement something into SBA on your own.
See https://codecentric.github.io/spring-boot-admin/current/#clustering-support 
and #1134, #541
