### ISSUE TITLE
How to hide tab

### ISSUE THREAD

**Issue by bootstrap2025** [codecentric/spring-boot-admin#1854]
I want to consult if there is a configuration to hide the red box tab in the picture?
![微信截图_20211112165231](https://user-images.githubusercontent.com/9637974/141438802-71adc9a0-32e8-47f7-9841-0eb752c521d0.png)

**Comment by erikpetzold** [comment]
Hi @bootstrap2025 

for language there ist the option to set `availableLanguages` only to 1 value, then the selection is hidden. See #1799

**Comment by erikpetzold** [comment]
for journal there is no such option and we are not planning to implement this at the moment

**Comment by bootstrap2025** [comment]
Great, thanks！

**Comment by bootstrap2025** [comment]
![微信图片_20211112155947](https://user-images.githubusercontent.com/9637974/141715103-9511ed81-d2a4-4fb2-988f-6cb0f73d3128.png)
