### ISSUE TITLE
client application status changes to Offline immediately after registration

### ISSUE THREAD

**Issue by immanishbainsla** [codecentric/spring-boot-admin#1855]
Hi there,
I have following properties set in my SBA-server
```
server.port=9090
server.host=custom-url
spring.security.user.name=user
spring.security.user.password=password

server.ssl.enabled=true
server.ssl.key-store=ServerKeystore.jks
server.ssl.trust-store=truststore.jks
server.ssl.key-store-password=test
server.ssl.key-password=test
server.ssl.keyStoreType=JKS

spring.boot.admin.routes.endpoints=env, metrics, trace, jolokia, info, configprops
```

and following properties set in my SBA Client
```
spring.boot.admin.client.url=https://custom-url:9090
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.boot.admin.client.username=user
spring.boot.admin.client.password=password
spring.security.user.name=clientuser
spring.security.user.password=clientpassword
spring.boot.admin.client.auto-registration=true
spring.boot.admin.client.instance.name=${module.name}
spring.boot.admin.client.instance.metadata.user.name=${spring.security.user.name}
spring.boot.admin.client.instance.metadata.user.password=${spring.security.user.password}
server.port=8484
spring.boot.admin.client.period=10000
spring.boot.admin.client.register-once=false
```

but every time client registers itself, status is shown as offline but client is up and running 
Is there any property that allows to ping client health API to know current client status by SBA server

![Screenshot 2021-11-17 at 15-42-24 Spring Boot Admin](https://user-images.githubusercontent.com/36675831/142183940-f442b7d5-e63c-46e7-b111-3e64275c9bd2.png)

**Comment by ulischulte** [comment]
Hi @immanishbainsla ,

a few questions to understand the situation in more detail:
    * which version of SBA client and server are you using currently?
    * does the issue still occur after moving to the actual versions (2.5.4)?
    * to reproduce the problem you're facing, it would be nice to have a sample project under github etc..

**Comment by immanishbainsla** [comment]
Hi @ulischulte 
* I am using 2.3.0 version of SBA both client and server
* I can't use version >= 2.4 because then I see `getBasePath()` function missing error
* It started happening after I added below properties in my project
```
server.ssl.enabled=true
server.ssl.key-store=ServerKeystore.jks
server.ssl.trust-store=truststore.jks
server.ssl.key-store-password=test
server.ssl.key-password=test
server.ssl.keyStoreType=JKS
```

the other `mysqldemo` project doesn't have ssl enabled and it works fine.
So is there any property for SBA server which checks health of client by pinging client health API or something for health check so that at least server can confirm whether my client is up and running or not because even though client is up and running as I can access client server's health API but still it shows client status offline?

I will try to recreate this error in sample project and then share later today.
Thanks

**Comment by immanishbainsla** [comment]
apart from all this I see this error in my logs
```
JMS health check failed
javax.jms.IllegalStateException: Connection closed
	at org.apache.activemq.jms.pool.PooledConnection.assertNotClosed(PooledConnection.java:206) 
```
	not sure whether this is related to this or not

	
	but SBA server shows
```
	 {
    "statusInfo": {
        "status": "OFFLINE",
        "details": {
            "exception": "java.util.concurrent.TimeoutException",
            "message": "Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)"
        }
    }
}
```

**Comment by immanishbainsla** [comment]
closing this as this error was because somehow my app's health endpoint was not reachable to the SBA server because ssl was enabled.
Thanks @ulischulte for your time
