### ISSUE TITLE
When will spa upgrade to spring boot 2.6.x?

### ISSUE THREAD

**Issue by zhangbinhub** [codecentric/spring-boot-admin#1858]
When will spa upgrade to spring boot 2.6.x?

**Comment by JCSCatena** [comment]
waiting too.

**Comment by baobeidaodao** [comment]
> waiting too.

waiting too too.

**Comment by antechrestos** [comment]
@ulischulte when will it be available? I saw that your pull request fell into conflict with the bots :disappointed:

**Comment by linghengqian** [comment]
Hi, I would like to ask if this issue is related to the hint at https://start.spring.io/ ?
![image](https://user-images.githubusercontent.com/20187731/148420985-b747e8c7-3f8d-4f58-b4a4-7a1dfd8174ff.png)
