### ISSUE TITLE
client application status is offline because client health endpoint returns string instead of pojo

### ISSUE THREAD

**Issue by immanishbainsla** [codecentric/spring-boot-admin#1860]
when my client returns response as
```
{
"health":"ok"
}
```
it works fine but
when my client app health endpoint just returns 
```
"ok"
```
with error
```
{
    "statusInfo": {
        "status": "OFFLINE",
        "details": {
            "exception": "org.springframework.core.codec.DecodingException",
            "message": "JSON decoding error: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('ok'); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('ok')\n at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1]"
        }
    }
}
``` 

is there any way to configure SBA server to ping health status and checks health based on *response status code* or *string* instead of pojo/LinkedHashmap ?

Thanks in advance.

**Comment by immanishbainsla** [comment]
on [stackoverflow](https://stackoverflow.com/questions/70065175/client-application-status-is-offline-because-client-health-endpoint-returns-stri)

**Comment by SteKoe** [comment]
Hi @immanishbainsla!

Checking health based on response status code string instead of POJO is and will not be supported since we heavily rely on the response data and format exposed and defined by Spring Boot Actuator endpoints which produce JSON by default. 

Best,
SteKoe

**Comment by immanishbainsla** [comment]
thanks, @SteKoe for your response.
