### ISSUE TITLE
After the SBA goes online in the k8s cluster, it affects the monitoring of other stations by the k8s survival probe

### ISSUE THREAD

**Issue by ITGcx** [codecentric/spring-boot-admin#1864]
SBA registers with Nacos, obtains site information from Nacos and monitors it. After the k8s cluster goes online, it affects the monitoring of other sites by the k8s survival probe, resulting in the restart of other sites. Have you ever encountered this problem, version springbootadminversion: 2.2.4, org. Springframework. Boot: 2.2.8. Release

**Comment by erikpetzold** [comment]
Closing this old ticket. If you encounter new problems please feel free to open a new ticket, we will try to analyze and respond quicker.
