### ISSUE TITLE
integrate microservices-dashboard

### ISSUE THREAD

**Issue by imod** [codecentric/spring-boot-admin#187]
This would be a nice addition: https://github.com/ordina-jworks/microservices-dashboard/blob/master/README.md

**Comment by andreasevers** [comment]
We're willing to help integrating from our end, where we already have an issue to integrate the other way around: https://github.com/ordina-jworks/microservices-dashboard-server/issues/41

**Comment by cforce** [comment]
Really looking forward, any news here?

**Comment by joshiste** [comment]
I guess currently nobody is working on this...

**Comment by joshiste** [comment]
the microservices-dashboard looks quite abandoned to me, therefore I'm closing this issue.
