### ISSUE TITLE
Audit Log screen mssing records

### ISSUE THREAD

**Issue by zackfei** [codecentric/spring-boot-admin#1870]
## SBA 2.5.4

![Screenshot_1](https://user-images.githubusercontent.com/30618665/144007004-cf27dcb4-3895-47aa-8c12-23ba29027cdf.png)

- audit log not populate full event after retrieve from actuator/auditevents endpoint. I got 16 audit event from the endpoint, but the UI only populate 8 records.
- Based on my observation, if the returned records having the "timestamp" close to the miliseconds from previous record, that particular record will skip

**Comment by SteKoe** [comment]
Hi @zackfei,

thanks for posting this issue. Would you mind sharing the JSON data that is sent from the server? We'd like to investigate the issue further.

**Comment by zackfei** [comment]
> Hi @zackfei,
> 
> thanks for posting this issue. Would you mind sharing the JSON data that is sent from the server? We'd like to investigate the issue further.

here is the new screen and json result from `actuator/auditevents`

[auditevents.txt](https://github.com/codecentric/spring-boot-admin/files/7648274/auditevents.txt)

![image](https://user-images.githubusercontent.com/30618665/144578992-0fa30d8b-2dc5-4e44-bd04-ee41a71af2f2.png)
