### ISSUE TITLE
SpringBoot Admin的Server模块生成的可视化界面将X-Frame-Options设置为了DENY，导致无法嵌入到iframe中

### ISSUE THREAD

**Issue by XieRW** [codecentric/spring-boot-admin#1871]
依赖版本：
de.codecentric:spring-boot-admin-starter-server:2.2.4
org.springframework.boot:spring-boot-starter:2.2.8.RELEASE
![image](https://user-images.githubusercontent.com/37648592/144184302-8e5f8209-e021-474e-b508-8c90ebf3feb8.png)

**Comment by XieRW** [comment]
我用nginx解决了这个问题，但是SpringBoot Admin本身有没有这个问题的解决方案呢？

**Comment by ulischulte** [comment]
Hi @XieRW,

we're not quite sure if we understood your problem. Are you trying to embed the spring-boot-admin-server-ui itself within an iframe or are you trying to embed an external page? For the latter, there's an option to do so (@see https://codecentric.github.io/spring-boot-admin/current/#customizing-external-views).

**Comment by XieRW** [comment]
I tried to embed the spring-boot-admin-server-ui itself within an iframe
![image](https://user-images.githubusercontent.com/37648592/145545238-b10f7d85-6349-488d-bb3c-66374fdd4f7b.png)

**Comment by ulischulte** [comment]
Hi @XieRW,

the X-Frame-Options response header instructs the browser to prevent any site with this header in the response from being rendered within a frame. By default, Spring Security disables rendering within an iframe.

You can customize frame options to use the same origin your security config using the following:

http.headers().frameOptions().sameOrigin();

Regards,
Uli
