### ISSUE TITLE
When creating a custom view the components cannot be imported

### ISSUE THREAD

**Issue by kevinspelt** [codecentric/spring-boot-admin#1877]
** Why is the extension not marked as type module**

** I have to import the components made in vue.js, but this is not possible because the script for the extensions is not marked as module. Is it me not doing this correctly or is there no way to do this**

**Comment by eliblurr** [comment]
Hi @kevinspelt, I have been having the same issue and I want to know if you solved it, if so how did you do it.

**Comment by SteKoe** [comment]
Hi @kevinspelt,

I don’t get your questions: 

 1. Which extension is not marked as type module?
 2. What kind of components do you want to import?

Please find here a detached, from scratch example showing how to build a custom ui: https://github.com/SteKoe/spring-boot-admin-example-custom-ui

**Comment by shotmk** [comment]
@SteKoe i believe i understand the issue, and i believe i am having the same issue.
I am building the custom UI extension for the spring-boot-admin.
You guys have created many components inside spring-boot-admin-server-ui. I mean Vue.js components. 
Some of them may be very useful for custom screens (like Instance/Application switch button that changes the scope of action between affecting single instance, or all instances of same application) 
It would be great if this components were published to npm, to make them re-usable inside custom extensions.
Or maybe u have another idea on how can i re-use the component in my custom UI extension project? 
I can copy the component from your code-base to mine, but it does not feel right. 
WDYT?
