### ISSUE TITLE
No Response from endpoints with "/api/applications/*" 

### ISSUE THREAD

**Issue by aroradeepak001** [codecentric/spring-boot-admin#188]
I am trying out spring boot admin application, I have two servers and trying to register one App into another, Everything is working fine, But the UI gives a strange message of just  "Error{}", And when I look at the individual jsons I get no response, The app just doesn't give any response(Not even 404) for those endpoints.

**Comment by joshiste** [comment]
Please provide a sample project to reproduce the error.

**Comment by joshiste** [comment]
Did you check the admin server logs? I guess it can't reach the endpoints of the registered client. Please make sure that the client server is reachable via network from the admin server

**Comment by aroradeepak001** [comment]
Thanks for replying :) , Its code from my organization so I can't share any code snippet, But I think that it is not able to go past the ZuulController, Because I ran it remotely in debug mode, It is going to the client server..

**Comment by joshiste** [comment]
I can't help you wihtout any logs or seeing some code. Did you have a look at the logs of the spring boot admin server? I guess it can't reach the client.

**Comment by aroradeepak001** [comment]
Thanks Josh , it got resolved, Maybe some dependency was missing , I put that in and it started working, I can't share anything form code , So i am sorry for that ...
