### ISSUE TITLE
Spring boot version 2.6.0 and spring boot admin version 2.2.2 compatibility issue

### ISSUE THREAD

**Issue by akshmendhe** [codecentric/spring-boot-admin#1882]
I have a Spring boot admin server with spring-boot-admin version 2.2.2.

I am trying to register spring boot client over mentioned spring boot server with client project having below configurations:
Spring boot version: 2.6.0
Spring boot cloud version: 2021.0.0
Spring boot actuator version: 2.6.0
Spring boot admin starter client version: 2.2.2

I am getting the below error in the client startup:

{"instant":{"epochSecond":1639544707,"nanoOfSecond":994993000},"thread":"registrationTask1","level":"ERROR","loggerName":"org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler","message":"Unexpected error occurred in scheduled task","thrown":{"commonElementCount":0,"localizedMessage":"'org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties$Servlet org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getServlet()'","message":"'org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties$Servlet org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getServlet()'","name":"java.lang.NoSuchMethodError","extendedStackTrace":"java.lang.NoSuchMethodError: 'org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties$Servlet org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getServlet()'\n\tat de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementContextPath(ServletApplicationFactory.java:86) ~[spring-boot-admin-client-2.2.2.jar:2.2.2]\n\tat de.codecentric.boot.admin.client.registration.ServletApplicationFactory.getManagementBaseUrl(ServletApplicationFactory.java:77) ~[spring-boot-admin-client-2.2.2.jar:2.2.2]\n\tat de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getHealthUrl(DefaultApplicationFactory.java:154) ~[spring-boot-admin-client-2.2.2.jar:2.2.2]\n\tat de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:80) ~[spring-boot-admin-client-2.2.2.jar:2.2.2]\n\tat de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:58) ~[spring-boot-admin-client-2.2.2.jar:2.2.2]\n\tat org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.13.jar:5.3.13]\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]\n\tat java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]\n\tat java.lang.Thread.run(Thread.java:833) [?:?]\n"},"endOfBatch":false,"loggerFqcn":"org.apache.commons.logging.LogAdapter$Log4jLog","threadId":147,"threadPriority":5,"timestamp":"2021-12-15T10:35:07.994+0530","serviceName":"spring-boot-project","serviceId":"spring-boot-project"}

I have tried to register another spring boot client project over the same server with the below configurations and it is working fine as expected:
Spring boot version: 2.5.2
Spring boot cloud version: 2020.0.3
Spring boot actuator version: 2.5.2
Spring boot admin starter client version: 2.2.2

Are there any compatibility issues between Spring boot version 2.6.0 and spring boot admin version 2.2.2? Please let me know if there are any workarounds for this situation?

**Comment by SteKoe** [comment]
Hi @akshmendhe,

we strongly recommend using the version of Spring Boot admin starter client that corresponds to your Spring Boot version. Hence, please upgrade from 2.2.2 to 2.5.5 and check if the problem remains and report back.

Best,
Stephan

**Comment by ulischulte** [comment]
We're closing the issue due to missing feedback.
