### ISSUE TITLE
Delay before notification

### ISSUE THREAD

**Issue by playaz87** [codecentric/spring-boot-admin#1885]
I have a Spring Admin monitoring a server on a different continent that sends a Slack notification when the server goes offline. The issue I'm having is that I will get a notification that the server is down (when it isn't) and then another notification shortly after that it's back up. I presume this down to packet loss. It'd be great to be able to set the number of failed attempts to reach a server before the notification gets set. Currently I'm receiveing about 20 notifications a day that the server is down when it isn't.

**Comment by ulischulte** [comment]
Superseded by #1711
