### ISSUE TITLE
Startup consumed a lot of memory with the external tomcat

### ISSUE THREAD

**Issue by zondacker** [codecentric/spring-boot-admin#1887]
** Bug report **
When I started a spring boot project with SBA client or server using the external tomcat, it consumed a lot of memory, but it returned to normal when I removed the SBA.

spring boot: 2.3.12.RELEASE
spring boot admin: 2.3.1

**Comment by ulischulte** [comment]
Hi @zondacker,

we're not quite sure wether we understood your problem.
We assume you're building a spring boot application war with version 2.3.12.RELEASE and deploy this on a dedicated tomcat  server instead of starting the application with an embedded server. 
Furthermore, we assume, that memory consumption increases, when adding Spring Boot Admin Client dependencies to said project.
Is this right?
If so, could you add some more details for us to understand your issue:
* How much memory does the application consume with/without SBA?
* On which tomcat version is the application running?
* Are you facing the same problem when using the embedded tomcat?

Regards,
Uli

**Comment by zondacker** [comment]
Hi @ulischulte,

Yes, you are right.

- see the picture below, the details of memory consumption with/without SBA
- apache tomcat 9.0.46
- no

![image](https://user-images.githubusercontent.com/6701230/149092194-52239d97-28d6-443d-acbe-bcee683e20fa.png)

![image](https://user-images.githubusercontent.com/6701230/149091302-5c024cfd-b36d-4eee-be57-cef7ed302761.png)

**Comment by ulischulte** [comment]
Hi @zondacker ,

we were not facing unexpected high memory consumption while trying to reproduce your setup. We deployed a Spring Boot application (v 2.3.12.RELEASE) and the Spring Boot Admin Server (2.3.1) afterwards on a tomcat (v 9.0.56).

![image](https://user-images.githubusercontent.com/16336547/149491386-ff17d1c2-0265-480b-abd2-c014467910ea.png)

As you can see, the memory consumption is not higher than expected.
Can you please provide some deeper insights on your configuration of Spring Boot Admin?

Regards,
Uli

**Comment by zondacker** [comment]
Hi @ulischulte,

My Spring Boot application using the Spring Cloud components, such as spring-cloud-starter-openfeign, spring-cloud-starter-netflix-ribbon. The pom.xml dependencies as below:

`<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>${spring.boot.admin.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>`
    
And the configuration of Spring Boot Admin as below:
`@Configuration
public class SecuritySecureConfig extends WebSecurityConfigurerAdapter {
    private final String adminContextPath;

    public SecuritySecureConfig(AdminServerProperties adminServerProperties) {
        this.adminContextPath = adminServerProperties.getContextPath();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");
        successHandler.setDefaultTargetUrl(adminContextPath + "/");

        http.authorizeRequests()
                .antMatchers(adminContextPath + "/assets/**").permitAll()
                .antMatchers(adminContextPath + "/login").permitAll()

                .antMatchers(adminContextPath + "/api/**").permitAll()
                .antMatchers(adminContextPath + "/instances").permitAll()
                .antMatchers(adminContextPath + "/actuator/**").permitAll()
                .antMatchers(adminContextPath + "/v3/api-docs").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin().loginPage(adminContextPath + "/login").successHandler(successHandler).and()
                .logout().logoutUrl(adminContextPath + "/logout").and()
                .httpBasic().and()
                .csrf()
                .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                .ignoringAntMatchers(
                        adminContextPath + "/api/**",
                        adminContextPath + "/instances",
                        adminContextPath + "/actuator/**"
                );
        // @formatter:on
    }
}`

**Comment by erikpetzold** [comment]
@ulischulte in the screenshot from @zondacker the heap is much higher when including the client into an spring boot application. In your screenshot you show the non-heap memory.

@zondacker you provided your config of the admin **server**, right? As you said the **client** uses too much memory, I think we should have a look at the client config.
If you include the client in your application, then it will register with SBA Server. Then the server starts to monitor the application by invoking the actuator endpoints. When using the war sample from SBA, we cannot see such a memory increase.
Maybe some actuator in your application is using so much memory. So would be good to know which actuators you have enabled etc. Best would be to share a sample project that we can simply run, maybe put some project on github?

**Comment by ulischulte** [comment]
We're closing the issue due to missing feedback.
