### ISSUE TITLE
Server Poll URL's vs Registering with Admin Server

### ISSUE THREAD

**Issue by dmarley** [codecentric/spring-boot-admin#189]
Is there a way to not have your application have knowledge of the admin server, but instead just have the admin server poll URL's on a scheduler?

I can see the benefits in a micro service environment to have them register them selves, but in a environment where we have a couple of web apps and don't want to couple the web app with the administration app.

Thoughts?

**Comment by joshiste** [comment]
There is support for spring cloud discovery. The admin server fetches the
URLs from an service registry.
So every service registry mechanism supported by spring cloud should work
with boot admin. (I only tested eureka so far).

It should be no problem to implement something similar and query mesos or
some other scheduler.
In fact you just need to write the polling code for the admin server an
store the results in the applicationRegistry.
