### ISSUE TITLE
cannot build spring-boot-admin-server-ui

### ISSUE THREAD

**Issue by jakabgergely** [codecentric/spring-boot-admin#193]
Hi, I am getting this npm error on mvn clean install:

> spring-boot-admin-server-ui@1.3.3 postinstall C:\dev\workspace3\spring-boot-admin\spring-boot-admin-server-ui
> ./node_modules/protractor/bin/webdriver-manager update

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\dev\\tools\\nodejs\\node.exe" "C:\\dev\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! spring-boot-admin-server-ui@1.3.3 postinstall: `./node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spring-boot-admin-server-ui@1.3.3 postinstall script './node_modules/protractor/bin/webdriver-manager update'.
npm ERR! This is most likely a problem with the spring-boot-admin-server-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-boot-admin-server-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls spring-boot-admin-server-ui
npm ERR! There is likely additional logging output above.

**Comment by joshiste** [comment]
I'm developing on Linux and the CI runs Linux. You have to do some small changes to run on Windows: Please see the [README.md of spring-boot-admin-server-ui](
https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-server-ui#building-on-windows)
