### ISSUE TITLE
Please update the Reference Guide (2.2.1 Springboot Admin Client)

### ISSUE THREAD

**Issue by Springjunky** [codecentric/spring-boot-admin#1931]
Since Spring-Boot 2.6 an extra property is need to display all the
`info.* `
properties with the `actuator/info` Endpoint

**`management.info.env.enabled=true`**

Please give a hint for that in Part 2.2.1 - 2 application.properties  sample
(See https://medium.com/@TimvanBaarsen/help-my-spring-boot-info-actuator-endpoint-is-enabled-but-i-dont-see-any-environment-details-c2d41a7b24d7)

Thanks in advance

**Comment by SteKoe** [comment]
Hi @Springjunky,

thank you for the hint. We have added the required property to the documentation which will be shipped with a release for Spring Boot 2.6. soon.

Best,
Stephan

**Comment by Springjunky** [comment]
:+1:
