### ISSUE TITLE
After upgrading to springboot 2.4 and spring-boot admin 2.4.1, none of the instances show up in SBA dashboard

### ISSUE THREAD

**Issue by pgouri017** [codecentric/spring-boot-admin#1932]
My current project contains many microservices discovered through consul and managed/monitored by SBA. 
After upgrading my applications to springboot 2.4 and spring-boot admin 2.4.1, none of the instances show up in SBA dashboard, but all instances are up in consul UI.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/71350567/148267535-345c89c8-21f5-443b-b3da-18fa48aa725e.png">

**Comment by SteKoe** [comment]
duplicate of #1737
