### ISSUE TITLE
`actuator/auditevents` no longer trigger for 2.6.0

### ISSUE THREAD

**Issue by zackfei** [codecentric/spring-boot-admin#1935]
springboot version: 2.6.2
SBA version: 2.6.0

after upgrading springboot version to 2.6.2 and SBA version to 2.6.0, the audit log screen no longer trigger `actuator/auditevents` endpoint

![image](https://user-images.githubusercontent.com/30618665/148927706-39bb9a6d-ba89-4b86-bd52-ea357cbb92f8.png)

**Comment by SteKoe** [comment]
Hi @zackfei,

we have just merged a fix. If possible, please check if the fix is working for you. It will be included in the next release :)
