### ISSUE TITLE
Use liveness instead of /actuator/health

### ISSUE THREAD

**Issue by vgropp** [codecentric/spring-boot-admin#1937]
We are using /actuator/health/liveness in our kubernetes. We have services who include more/other Probes in /actuator/health so Spring Boot Admin does not show the actual up-state compared to kubernetes. I have found #1389 but it seems there was no progess. What about not only adding those endpoints in UI but using it for the status in https://github.com/codecentric/spring-boot-admin/blob/dfe2a4b493bb4670eec7b6bfd684787e2e208038/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/services/StatusUpdater.java#L75 or is this the wrong place? 

I guess this should be some sort of config, do you have any advice where/how to configure this behavior? I would use liveness only for status up/down

**Comment by SteKoe** [comment]
Hi @vgropp,

we do not support configuring the Status URL of services, yet. We are checking how to implement this feature.

**Comment by andreasfritz** [comment]
fixed with https://github.com/codecentric/spring-boot-admin/pull/2765
