### ISSUE TITLE
SBA shows 2 instances of application where there should be only one

### ISSUE THREAD

**Issue by charlesb-yesmail** [codecentric/spring-boot-admin#1943]
I am setting up SBA to monitor three different applications.  Two of the applications are deployed in the same Tomcat server and the third runs as a service.

What I am seeing with the applications deployed in Tomcat is that SBA shows two instances of either or both of them (I'm seeing slightly different behaviour in different environments).  Here's what I see on my laptop, with the Microservices API running as a service and the Custom Hosted Pages and Barcode Generator applications running in Tomcat 9:

![image](https://user-images.githubusercontent.com/2489428/149504148-13d19c1e-2204-4613-b210-89be813fb538.png)

Tomcat is configured with the ```spring.boot.admin.client.instance.service-base-url=http://localhost:8081```

Questions:

Why do I see two instances of the Custom Hosted pages application?

What does Restricted mean?

**Comment by SteKoe** [comment]
Hi @charlesb-yesmail,

"Restricted" means that at least one instance of an application is up but other instances have a different state. 

We have some questions regarding your issue:

 * Is Spring Boot Admin running as a Tomcat application as well?
 * Do the services register themself at SBA?
 * We assume that you have deployed some Spring Boot applications which you have configured to have `service-base-url` set up as shown in your post and not Tomcat itself.

We guess, that SBA is monitoring itself and hence shown as "down" in the list. Please check if `spring.boot.admin.client.url` is set for SBA to the correct URL, if you want to monitor SBA. Otherwise, please remove the property from SBA configuration.

Best,
SteKoe

**Comment by charlesb-yesmail** [comment]
Hi SteKoe,

Thanks for responding.

> * Is Spring Boot Admin running as a Tomcat application as well?

SpringBoot Admin is deployed as a fat Jar and run from the command line using its embedded webserver.  It is not deployed to the same Tomcat container as the monitored applications.

> * Do the services register themself at SBA?

Yes.  The services include the Spring Boot Admin Starter Client dependency which I understand enables them to register themselves with the SBA server.

> * We assume that you have deployed some Spring Boot applications which you have configured to have `service-base-url` set up as shown in your post and not Tomcat itself.

```service-base-url``` is set in the Tomcat server's ```setenv.sh``` script and passed via the command line as shown below (have wrapped the lines to make it easier to read):

```
export CATALINA_OPTS="$CATALINA_OPTS -Dspring.boot.admin.client.username=$SPRING_SECURITY_USER_NAME 
-Dspring.boot.admin.client.password=$SPRING_SECURITY_USER_PASSWORD 
-Dspring.boot.admin.client.instance.metadata.user.name=$SPRING_SECURITY_USER_NAME 
-Dspring.boot.admin.client.instance.metadata.user.password=$SPRING_SECURITY_USER_PASSWORD 
-Dspring.boot.admin.username=$SB_ADMIN_USER -Dspring.boot.admin.password=$SB_ADMIN_PASSWORD 
-Dmanagement.endpoint.health.roles=ACTUATOR -Dspring.boot.admin.client.url=http://localhost:9060 
-Dspring.boot.admin.client.instance.service-base-url=http://localhost:8081"
```

I wasn't sure if it should have a different value for each application or not.

> 
> We guess, that SBA is monitoring itself and hence shown as "down" in the list. Please check if `spring.boot.admin.client.url` is set for SBA to the correct URL, if you want to monitor SBA. Otherwise, please remove the property from SBA configuration.

I'm not trying to monitor SBA as well.  As mentioned above it is running in a separate container from the monitored applications.

Thanks,

Charles.

**Comment by ulischulte** [comment]
Hi @charlesb-yesmail,

thanks for your information. For further investigation - could you provide the whole configuration of your Spring Boot Admin application (application. properties / application.yml).

Regards,
Uli

**Comment by charlesb-yesmail** [comment]
Hi Uli,

> thanks for your information. For further investigation - could you provide the whole configuration of your Spring Boot Admin application (application. properties / application.yml).

Here you go

Environment setup script
```
#!/usr/bin/env bash

export SPRINGBOOT_ADMIN_LOG_LOCATION=/tmp/ptsacs/springbootadmin/log

export SPRING_SECURITY_USER_NAME="{removed for security}"
export SPRING_SECURITY_USER_PASSWORD='{removed for security}'
export SPRING_BOOT_ADMIN_CLIENT_INSTANCE_METADATA_USER_NAME=${SPRING_SECURITY_USER_NAME}
export SPRING_BOOT_ADMIN_CLIENT_INSTANCE_METADATA_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}
```
SBA startup script:
```
#!/bin/sh
FULL_PATH=$(cd $(dirname $0) && pwd -P)

heap_dump_dir="."

if [ ! -d "$heap_dump_dir" ]; then
   echo "WARN  Heap Dump directory $heap_dump_dir doesn't exist. If server crashes with OutOfMemory error, heap dump will not be collected"
fi

JAVA_OPTS="-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$heap_dump_dir"
JAVA_OPTS+=" -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5011"

PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Get standard environment variables
PRGDIR=`dirname "$PRG"`

source "$PRGDIR"/set_env.sh

java $JAVA_OPTS \
  -Dlog.file.location="$SPRINGBOOT_ADMIN_LOG_LOCATION" \
  -Dlogging.config="$PRGDIR"/conf/logback-spring.xml \
  -jar $PRGDIR/target/SpringbootAdmin.jar
```
SBA application.yml:
```
#Springboot specific configs

management:
  port: 9065
server:
  port: 9060
  session-timeout: 3000

spring:
  application:
    name: PTS Spring Boot Admin
```
Hope this helps.

Thanks,

Charles.

**Comment by charlesb-yesmail** [comment]
I've created a demo project which is similar to the set up we are using for our applications, which is available here:

https://github.com/charlesb-yesmail/sba-issue-1943

At first I wasn't able to reproduce the problem.  As I looked for differences between the demo project and our application configuration I realised that I had not configured my local Tomcat in the same way as the environment where I am seeing the issue.  When I updated Tomcat's configuration to include a similar vhost setup then I was able to reproduce the issue.

I've attached a log file from SBA when the issue was occurring.

[issue-1943-log.txt](https://github.com/codecentric/spring-boot-admin/files/8134225/issue-1943-log.txt)

**Comment by SteKoe** [comment]
Hi @charlesb-yesmail,

we were able to reproduce the issue and found a solution by setting the property `spring.boot.admin.client.instance.service-url` for the different services to a fixed, service specific value: 

* `spring.boot.admin.client.instance.service-url=http://localhost:8081/webapp1`
* `spring.boot.admin.client.instance.service-url=http://localhost:8081/webapp2`

After setting the properties, just one instance registers with SBA. Hope this will solve the problems in your setup as well. If not, feel free to reopen the issue :)

Regards,
SteKoe

**Comment by charlesb-yesmail** [comment]
Confirming that the suggested solution works.  Thanks for your help with this.
