### ISSUE TITLE
EurekaServiceInstanceConverter.convert() uses metadataMap.management.context-path. There is no information about that in docs.

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#195]
To propagate to admin-server management context-path form the client (I use Spring Cloud Discovery) I have to set this property on client side.

I'm using 1.3.3-SNAPSHOT.

**Comment by joshiste** [comment]
It is mentioned in the docs: http://codecentric.github.io/spring-boot-admin/1.3.2/#spring-cloud-discovery-support (see the information-note)

**Comment by tjuchniewicz** [comment]
I've been searching 1.3.2 docs... Sorry.
