### ISSUE TITLE
SBA UI Journal view - displaying same event multiple times

### ISSUE THREAD

**Issue by ztomic** [codecentric/spring-boot-admin#1958]
Since Spring Boot Admin 2.5.5, event journal is displaying same event multiple (9) times.

It can be seen in original pull request screen capture also (https://github.com/codecentric/spring-boot-admin/pull/1862)

Screenshot from 2.5.4:
![image](https://user-images.githubusercontent.com/1428972/149954082-d9cc8dec-89ec-40bf-9d82-0f0babc44d8a.png)

Screenshot from 2.6.1 (same isssue is at 2.5.5 and 2.6.0 versions)
![image](https://user-images.githubusercontent.com/1428972/149954340-5c003f58-2fd1-49c4-b4fe-f636901864d6.png)

**Comment by SteKoe** [comment]
Hi @ztomic,

thanks for reporting this bug, we have fixed this [here](https://github.com/codecentric/spring-boot-admin/commit/ecdd09177ae8d19bcfb7591dd3a4f56428b16177) and will ship it with the next release. 

Best,
SteKoe

**Comment by ztomic** [comment]
Nice, thanks!
