### ISSUE TITLE
service-url 配置无效？为什么呢？

### ISSUE THREAD

**Issue by 350078238** [codecentric/spring-boot-admin#1971]
![image](https://user-images.githubusercontent.com/17629739/150663257-d43d3112-b41e-4f61-8fe3-6a92476061a5.png)
![image](https://user-images.githubusercontent.com/17629739/150663263-76af5134-8f21-4598-8bd8-f7004ae3cc1e.png)

**Comment by ulischulte** [comment]
Hi @350078238 

Sorry for the late reply. 
This is too little information to help you. What exactly is your problem?

Regards,
Uli

**Comment by ulischulte** [comment]
We're closing this issue due to missing feedback.
