### ISSUE TITLE
项目第一次启动，查看日志一直显示加载中

### ISSUE THREAD

**Issue by 350078238** [codecentric/spring-boot-admin#1972]
![image](https://user-images.githubusercontent.com/17629739/150669174-c37a577e-fa5a-4640-bfcb-cce94492618e.png)
被监控项目没有日志文件的时候 ，启动被监控的项目，生成日志文件后，admin 查看日志，就一直 加载中，admin项目后台没有任何报错，只要把被监控的项目重启一下之后  ，在 admin 上在查看日志 才是可以正常看到。

**Comment by SteKoe** [comment]
> The first time the project is started, the viewing log always shows loading

> When the monitored project has no log file, start the monitored project. After generating the log file, the admin checks the log, and it is always loaded. There is no error in the background of the admin project. Just restart the monitored project. It is normal to see the log.

Hallo @350078238,

can you please update Spring Boot Admin and check if the error still occurs? If so, please check the browser's network tab and post the result of `/actuator/logfile` call, especially the status code (404? 200?). TIA!

Best,
SteKoe

**Comment by ulischulte** [comment]
We're closing the issue due to missing feedback.
