### ISSUE TITLE
Filtering/Sorting functionality in Events Journal

### ISSUE THREAD

**Issue by pasolid** [codecentric/spring-boot-admin#1977]
Currently an events journal is very basic view and simply a list of events w/o any possibility to filter or sort the results. This makes it very frustrating searching for all recent events of specific service, especially in large system.

Another thing, but related to filtering functionality is when user clicks on `journal` button on the service tab or in the service page (print screen attached) then it would open events journal for this specific service (filtered results)
<img width="495" alt="Screen Shot 2022-01-30 at 11 33 18" src="https://user-images.githubusercontent.com/76808982/151694330-3efa7845-cadd-48d3-96cc-ec1a2b097043.png">

**Comment by claitonp** [comment]
Hi,

78 / 5.000
Resultados de tradução
Filtering functionality is not working for a specific service in the current version.

![event journal](https://user-images.githubusercontent.com/11926060/152401816-20c7b326-bd91-45c5-bb4b-6cede9ee37ff.PNG)
