### ISSUE TITLE
Spring boot admin showing only Details tab

### ISSUE THREAD

**Issue by rHilkner** [codecentric/spring-boot-admin#1980]
Hello guys,

I've just setup Spring Boot Admin Server in which server and client are in Kotlin. I've seen many tutorials in which they show a screen with many tabs details, metrics, logging, etc (see first image attached). But in my case for some reason only the Details tab show up (see second image attached). 

This is the github of the project I'm woring on [https://github.com/rHilkner/kotlin-boilerplate], in which I have a project for the main api and another for the admin server (api-monitor). I've followed every rule from the videos/tutorials I've seen/read, but nothing seems to work. I really think this is a bug since everyone just imports and starts the admin server and already have all tabs displayed. 

Maybe this bug is happening only because I'm using Kotlin? Shouldn't be the case, since no warnings or exceptions are showing up in any of the projects. Also I'm seeing no errors in HTTP requests. My client yml already have `endpoints.web.exposure.include: "*"`. Any ideas on how to debug this? I'm kind of lost in what appeared to be a simple issue.

Useful links
Github project: https://github.com/rHilkner/kotlin-boilerplate
Client project: https://github.com/rHilkner/kotlin-boilerplate/tree/master/api-boilerplate
Client yml: https://github.com/rHilkner/kotlin-boilerplate/blob/master/api-boilerplate/src/main/resources/application.yml
Client gradle: https://github.com/rHilkner/kotlin-boilerplate/blob/master/api-boilerplate/build.gradle.kts
Admin project: https://github.com/rHilkner/kotlin-boilerplate/tree/master/api-monitor
Admin yml: https://github.com/rHilkner/kotlin-boilerplate/blob/master/api-monitor/src/main/resources/application.yml
Admin gradle: https://github.com/rHilkner/kotlin-boilerplate/blob/master/api-monitor/build.gradle.kts
Admin security config: https://github.com/rHilkner/kotlin-boilerplate/blob/master/api-monitor/src/main/kotlin/com/example/adminserver/WebSecurityConfig.kt

Images:
Expected admin server (many tabs - details, metrics, logging, etc) - Link for the video: https://youtu.be/ERzE_5OT9C4
![image](https://user-images.githubusercontent.com/11353796/151723542-0cd935f5-a1e5-4a13-83b8-ca1667ed65b6.png)
My admin server (only Details tab) - no errors in HTTP requests
![image](https://user-images.githubusercontent.com/11353796/151723920-75d534a3-014c-40cc-8dbc-19fa382e4bdd.png)

**Comment by erikpetzold** [comment]
hi @rHilkner 

the SBA web frontend shows only the menu entries for active actuators. So if the endpoints are not available then they are hidden, this is fine.

Now the question ist why the actuators are not available. There are 2 things to check: they need to be **enabled** and **exposed**. From your config it seems you are exposing everything and most of them should be enabled by default.
Can you please check the output of `/actuator` on your client? just open it in the browser, like `http://localhost:8080/actuator`.
This should list all endpoints. If there is only health, then SBA shows only the details page. Then this is a Spring Boot problem and not related to Spring Boot Admin.

If there are more endpoints listed please provide the json here, so we can check what causes issues in SBA.

**Comment by ulischulte** [comment]
We're closing the issue due to missing feedback.
