### ISSUE TITLE
Support user SSO authentication

### ISSUE THREAD

**Issue by Halayem** [codecentric/spring-boot-admin#1985]
In the perspective to go in production with SBA, our security auhority team require that every user accessing to SBA server must be authenticated and identified using our SSO authentication system,
so each http request sent by the browser to the server must provide the 'access_token' of the connected user that will be verified by the SBA Server to wether to authorize or not the request

I didn't find documentation on how to implement this, can you point me in the right direction ?

**Comment by erikpetzold** [comment]
Hi @Halayem 

Spring Boot Admin is a normal Spring Boot applcation, so you can secure it with spring security. See also the docs: https://codecentric.github.io/spring-boot-admin/current/#securing-spring-boot-admin

Keep in mind that there are 2 possible kinds of authentication: 
- user using the (secured) webfrontend of Spring Boot Admin
- Spring Boot Admin invoking the (secured) actuator endpoints of your applications

I will close the issue, if you have more specific questions feel free to reopen or create a new issue.
