### ISSUE TITLE
Improve UX of the JMX Mbeans View

### ISSUE THREAD

**Issue by pobodysnerfect** [codecentric/spring-boot-admin#1986]
I recently upgraded SBAC to the latest 2.6.2 from 1.5.X, we utilize JMX operations quite a lot and i noticed the JMX view doesn't handle long package names/methods very well. I'll attach 2 screenshots to show what i mean:

First issue: our "Domain" is the package name: "com.constantcontact.tokensvc.service", about 36 characters, it gets chopped off and appears off screen on the right:

<img width="1532" alt="Screen Shot 2022-02-08 at 12 00 00 PM" src="https://user-images.githubusercontent.com/11590081/153037955-464f4d74-a001-4231-b136-ebf0b870190b.png">

Second issue: We use some operations with lots of parameters, the method/parameter list also blows out beyond the button:

<img width="1530" alt="Screen Shot 2022-02-08 at 12 00 25 PM" src="https://user-images.githubusercontent.com/11590081/153038544-213181b9-97b8-42e5-b54e-75bedb51b669.png">

I was hoping the UX could be improved to handle both of these cases so its easier to read/interact with.

**Comment by SteKoe** [comment]
Hi, @pobodysnerfect,

thanks for opening the issue. We are currently focussing on supporting Spring Boot Version 3 and have no capacity to work on your issue right now, sorry. But anyway, we'd be happy to see your input either as a suggestion on how to rearrange the UI to support better readability or–of course–as a PR.

**Comment by SteKoe** [comment]
We have included an improved UI in 2.6.6. :)
