### ISSUE TITLE
unregistering servers using trash icon button not working

### ISSUE THREAD

**Issue by pobodysnerfect** [codecentric/spring-boot-admin#1987]
I'm currently running spring boot 2.6.2, and spring boot admin 2.6.2, and all the clients that are registering with the server are using spring boot admin client 1.5.2. I realize this isn't the recommended setup (we will be updating our services to the latest spring boot in time), but its unclear to me if this bug is related to that or not.

to reproduce, open up the instances and click on the trash icon:

 
<img width="1157" alt="Screen Shot 2022-02-08 at 12 16 32 PM" src="https://user-images.githubusercontent.com/11590081/153040548-69b2da1c-03cf-4a27-b372-b47d8edbe29f.png">

Nothing happens, and I get this stack trace in the console:

Axios.js:40 Uncaught (in promise) Error: Provided config url is not valid
    at l.request (Axios.js:40:11)
    at l.r.forEach.l.<computed> [as delete] (Axios.js:136:17)
    at Function.delete (bind.js:9:15)
    at t.<anonymous> (instance.js:55:23)
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7

It seems like its trying to call this:

https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/services/instance.js#L55

but its failing because axios isn't configured. I also noticed that the registration source is "http-api", which seems to suggest unregistering isn't possible:

https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/services/instance.js#L51

but that would definitely be useful for us. 

Expected: the trash icon should work and it should unregister the server
Actual: nothing happens and i get an exception in the console.

**Comment by chrisdev0** [comment]
Perhaps related to https://github.com/axios/axios/issues/4407?

**Comment by erikpetzold** [comment]
Should be fixed with new axios version, we just merged #1994
