### ISSUE TITLE
Unable to login after upgrade to 1.3.3

### ISSUE THREAD

**Issue by dmwb** [codecentric/spring-boot-admin#199]
I'm have basic security for my spring boot application and it was working fine with Spring Boot Admin 1.3.2. After upgrade to 1.3.3 version I kept seen authentication popup when try to access admin page and I couldn't get to the front page. It seems like every request SBA made to my application is not passing basic authentication credentials..

```
security.basic.enabled=true
security.basic.path=/**
security.user.name=foo
security.user.password=bar
```

Please advise.

**Comment by dmwb** [comment]
It might be that configprops and logfile are not passing authentication headers ?...

![image](https://cloud.githubusercontent.com/assets/17462277/15412339/8f809fc4-1ddb-11e6-8d78-81847e82a58a.png)

**Comment by dmwb** [comment]
it could be related after this fix #165 was introduced in 1.3.3 release.

**Comment by WillBDaniels** [comment]
Confirmed, just reproduced this issue, and verified that it is not present in 1.3.2, but is in 1.3.3. same scenario as @dmwb

**Comment by joshiste** [comment]
duplicate of #192
