### ISSUE TITLE
Please Update Reference-Guide Chapter 3.3 Logfile Viewer (colored output without console)

### ISSUE THREAD

**Issue by Springjunky** [codecentric/spring-boot-admin#1993]
**Enhancement**

Please give a hint In Chapter 3.3. Logfile Viewer.

The colored output is only working if Spring / Java runs with an active console.
If you start a SpringBoot without any console (System-D Unit or redirection of output 2>&1>log.txt) the internal detection for ANSI-Color detects "NO CONSOLE" (System.console() == null) and the output in SBA is not colored.

**Solution:**
If you set 
```
spring.output.ansi.enabled=ALWAYS
#Default is DETECT
```
in your SBA-Client the colored output is _always_ working

**Comment by ulischulte** [comment]
Hi @Springjunky,

would you like to contribute with a pullrequest including the hint in the docs and a reference to the according spring docs?

Regards
Uli
