### ISSUE TITLE
ManagementServerProperties.getBasePath()Ljava/lang/String

### ISSUE THREAD

**Issue by Cocowwy** [codecentric/spring-boot-admin#1999]
java.lang.NoSuchMethodError: org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getBasePath()Ljava/lang/String;

SpringBoot version is : 2.3.9-RELEASE   
Which spring-boot-admin-starter-client‘s versuion should i choose ?

**Comment by erikpetzold** [comment]
Hi @Cocowwy , please make sure the client version matches the spring boot version in your monited applications in major and minor.
So for Spring Boot 2.3.9 you would need sba client 2.3.x (latest one would be 2.3.1)

**Comment by Cocowwy** [comment]
> Hi @Cocowwy , please make sure the client version matches the spring boot version in your monited applications in major and minor. So for Spring Boot 2.3.9 you would need sba client 2.3.x (latest one would be 2.3.1)

tks~
