### ISSUE TITLE
Unable to get client to register with correct URL

### ISSUE THREAD

**Issue by WillBDaniels** [codecentric/spring-boot-admin#200]
I've got a unique configuration which I don't think can be handled by the current configuration options, and I was hoping you could either point me in the right configuration direction, or perhaps there is an enhancement for a future release that could be done. 

I'm deploying a single instance of a spring boot application to multiple cloud servers, where the applications all run behind an apache proxy redirect in order to make all requests filter through port 80 > internal spring boot port. the crux of the problem, however, is that when the applications register themselves with my central spring-boot-admin server, they try to guess the url they're on and fail (since they know nothing of the DNS, and it's named differently than the hosts, etc), and they try to register using the spring boot port (which is firewalled from anything but localhost). this means that the client can reach the admin, but not vice-versa. 

I also tried using the 'prefer IP' option, but since each cloud machine has both a public and a private IP address, it only picked up the private ip address (which is the expected behaviour based on your documentation of using the `InetAddress().getLocalHost()`.

I realize I could set the various URL's with the `spring.boot.admin.client.service-url` etc. options, but since I'm deploying the same app over and over again to different servers, they all have different urls. This means that the automatic deployment script would have to go in and modify the resource file on the fly before creating the jar, and then re-creating the jar before every deployment (which for larger deployments, is a bit cumbersome). 

We don't currently use spring cloud or docker, so I can't speak as to whether or not either of those two situations alleviate this issue. 

**Possible Solution**
Simply having the admin view be able to modify configuration information for entities once they were registered would solve all the weird url/firewall problems completely. Just add an option to 'specify base URL' or some such after the clients register themselves, and then have all of the various /health and management endpoints, etc, referenced from that base URL. This also makes it so that the applications themselves (the clients) don't have to know about the URL that leads to them, they can be totally agnostic, which in my opinion, is a nice separation of concerns.

**Comment by joshiste** [comment]
>This means that the automatic deployment script would have to go in and modify the resource file on the fly before creating the jar, and then re-creating the jar before every deployment (which for larger deployments, is a bit cumbersome).

Mofifying the deployment unit is not needed. The deployment script could write an external property file or even just some environment variables, which you could refer in your `application.properties`.
You should read spring boot's chapter on [Externalized Configuration](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config).
