### ISSUE TITLE
False alarm of application restart via Slack

### ISSUE THREAD

**Issue by patpatpat123** [codecentric/spring-boot-admin#2000]
Hello Spring Boot Admin Team,

Sometimes, via our Slack (and other channel) we get this kind of message, which seems to be an application restart.

```
[SlackBot](https://app.slack.com/services/XXX)APP  
[06:44](https://a1.slack.com/archives/BBB/CCC)
myservice (5a52bbde18e3) is OFFLINE
[06:45](https://a1.slack.com/archives/BBB/CCC)
myservice (5a52bbde18e3) is UP
[06:46](https://a1.slack.com/archives/BBB/CCC)
myservice (5a52bbde18e3) is OFFLINE
[06:47](https://a1.slack.com/archives/BBB/CCC)
myservice (5a52bbde18e3) is UP
```

Because an application restart means a lot to us (downtime, outage), we have alert on this, etc.
Once we receive those kind of alert, we immediately verify if:
- the kubernetes pod was indeed restarted
- the application dashboard, prometheus, kibana and co shows sign of application restart / down
- we even verify with clients they were able to request / response without problem.

And upon verification, we are sure the application did not restart at that time, and not even close.

Therefore, we believe (please correct if wrong) it might just be Spring Boot Admin thinking the service application restarted, while not actually. 

While we are not seeing logs neither from admin, neither from client, hinting what could happen, I would like to ask, what is the correct way to troubleshoot those false alarm?

Should we look for some kind of log "checking client app, seems client app is restarting" or maybe some kind of "seeing health ok, seeing health not ok, seeing health ok again, therefore, I think it is a restart"

Overall, is there a way to prevent those false alarm?

Thank you!

**Comment by erikpetzold** [comment]
Hi @patpatpat123 

can you please check the logs for 'Connection prematurely closed BEFORE response' as seen in #1711 ?

This may be the cause for the behaviour you see.

**Comment by patpatpat123** [comment]
Hello @erikpetzold,

Thank you for taking a look at this.
I had a chance to look at related issue 1711, and it is indeed similar, but not totally the same.

I do not see any logs for 'Connection prematurely closed BEFORE response' at all.

However, I do see:

```
2022-03-03 08:49:16.302  INFO [adminserver,,] 10 --- [     parallel-1] d.c.b.a.server.services.StatusUpdater    : Couldn't retrieve status for Instance(id=123 ...
```

and

```
java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'map' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.4.14.jar!/:3.4.14]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to GET health [DefaultWebClient]
```

I hope this helps! 

Again, thank you

**Comment by erikpetzold** [comment]
Hi @patpatpat123 , we had this error message already in many issues, see for example #1774, #1566 or #1855

Like the message says, there was no response within the expected timeout. So either the service is not reachable or it responds very slow. You can increase the timeout with the sba properties to check whether this removes the error.
Then you have to find out why it is so slow.

**Comment by erikpetzold** [comment]
You could also check f retry helps, see #1711 again

**Comment by patpatpat123** [comment]
Understood, closing this, following up on related threads. Thanks a lot for looking into this
