### ISSUE TITLE
Jackson serialization broken for SpringBootAdmin custom types (i.e. InstanceId, Tags)

### ISSUE THREAD

**Issue by azi03** [codecentric/spring-boot-admin#2003]
the version of Spring Boot Admin: 2.6.2
the version of Spring Boot: 2.6.3
the version of explorer: Chrom 版本 99.0.4844.51（正式版本） （64 位）

the uri of service detail page will include id of service instance, but it's "**%5Bobject%20Object%5D**".
for example:    http://adminserver/instances/%5Bobject%20Object%5D/details
the page show the id is : Id: **{ "value": "3f3e7ac94568" }**
may be, resolve id is error, should show Id: "3f3e7ac94568" is OK.
![image](https://user-images.githubusercontent.com/51783122/156923415-d4b604b2-ab9c-4e7c-93cd-cd1ace217950.png)

**Comment by SteKoe** [comment]
Hi @azi03,

can you please check if your acuator endpoints use `camelCase` instead of `snake_case`. Also, check #751 for additional information. If you are already using `snake_case`, please provide the result of `/actuator/health` endpoint for further investigation.

TIA!

**Comment by azi03** [comment]
It means that the attribute name of the message returned by each service endpoint needs to be snake_case ready?
It was always in camelCase format. My health message is as follows：

`{
  "status" : "UP",
  "components" : {
    "db" : {
      "status" : "UP",
      "details" : {
        "database" : "MySQL",
        "validationQuery" : "isValid()"
      }
    },
    "discoveryComposite" : {
      "status" : "UP",
      "components" : {
        "discoveryClient" : {
          "status" : "UP",
          "details" : {
            "services" : [
              "schedule-web",
              "dc-search",
              "dc-metadata-gather",
              "dmc-expression-server",
              "dataapi-client",
              "data-center-station-server",
              "app-act",
              "app-atd",
              "dc-datastandard-server",
              "app-portal",
              "dataapi-core",
              "app-admin",
              "bdap-gateway",
              "app-sys",
              "schedule-server",
              "app-realtime",
              "auth-service",
              "dc-dataasset-server",
              "dc-quartz-server",
              "dc-dataquality-server",
              "app-dataExchange",
              "dc-datamodel-core",
              "app-adms",
              "app-mock",
              "bdap-demo22",
              "bdap-demo1",
              "dc-datamodel-server",
              "bdap-demo3",
              "dc-metadata-server"
            ]
          }
        }
      }
    },
    "diskSpace" : {
      "status" : "UP",
      "details" : {
        "total" : 53171187712,
        "free" : 11690278912,
        "threshold" : 10485760,
        "exists" : true
      }
    },
    "nacosConfig" : {
      "status" : "UP"
    },
    "nacosDiscovery" : {
      "status" : "UP"
    },
    "ping" : {
      "status" : "UP"
    },
    "redis" : {
      "status" : "UP",
      "details" : {
        "version" : "6.2.1"
      }
    },
    "refreshScope" : {
      "status" : "UP"
    },
    "sentinel" : {
      "status" : "UNKNOWN",
      "details" : {
        "dataSource" : { },
        "enabled" : true,
        "dashboard" : {
          "description" : "the dashboard servers [[Endpoint{protocol=HTTP, host='10.114.10.121, port=30080}]] one of them can't be connected",
          "status" : "UNKNOWN"
        }
      }
    }
  }
}`

**Comment by azi03** [comment]
> Hi @azi03,
> 
> can you please check if your acuator endpoints use `camelCase` instead of `snake_case`. Also, check #751 for additional information. If you are already using `snake_case`, please provide the result of `/actuator/health` endpoint for further investigation.
> 
> TIA!

I don't think this is the problem of attribute name format. I compared the old version of admin with the new version of admin. The message obtained by the applications interface is different in the ID field. The new version of ID value is an object and the old version is a string. The problem should be this value

![image](https://user-images.githubusercontent.com/51783122/157148089-22cdea63-5e5f-4af7-b742-f1a777b7845c.png)

**Comment by SteKoe** [comment]
Hi @azi03,

we have checked your screenshots and found out that the Jackson configuration you are using is off the one SBA requires. For example the field `statusTimestamp` needs to be in ISO 8601 format, some values like `id` or `info` are serialized as `{ value: '<actual value>'}`. We assume that you override the `ObjectMapper` configuration somewhere in a way that `AdminServerModule` and `JavaTimeModule` are not used by Jackson anymore. Please see the comment in the following file and recheck your Jackson configuration.

https://github.com/codecentric/spring-boot-admin/blob/ed0b42d8fab6b9a8a40ae7d2adbbffc3ae2a215a/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/utils/jackson/AdminServerModule.java#L48

Regards,
SteKoe

**Comment by azi03** [comment]
Hi @SteKoe ,
I debugged Jackson's automatic configuration code and found that adminservermodule had been added to Jackson 2objectmapperbuilder, but when legacyendpointconverters initialized the codec, there was no adminservermodule in the objectmapper built by admin through Jackson 2objectmapperbuilder. The tracking code found that during this construction, Jackson2objectmapperbuilder did not inject any ApplicationContext or adminservermodule. I don't know why.
![image](https://user-images.githubusercontent.com/51783122/158055761-c2767ffc-70d0-4567-aa0f-aa0287ebe06d.png)
![image](https://user-images.githubusercontent.com/51783122/158055771-42a655e5-8c9c-42d3-ae92-567251eba2cd.png)

**Comment by SteKoe** [comment]
Hi @azi03,

the use of a different Jackson configuration in `LegacyEndpointConverter` is fine since this affects Spring Boot 1.X apps only and is triggered on `GET /instances` endpoint. Despite that, the configuration of Jackson which includes AdminServerModule looks good, but we assume that another loaded module like Swagger might change the Jackson configuration in a way, that the serialization of Spring Boot Admin classes is affected.
If you need further help, we need to have access to the project (or a comparable example) to check what's going wrong there.

Regards,
SteKoe

**Comment by azi03** [comment]
Yes, I used swagger in my project, which caused me to rewrite `WebMvcConfigurationSupport`. I didn't rewrite the `extendMessageConverters` method before. Debugging found that the `Jackson2ObjectMapperBuilder` builder used in the `addDefaultHttpMessageConverters` method didn't have the module and mixin of admin, but the `Jackson2ObjectMapperBuilder` in the ApplicationContext was complete, so I rewritten the `extendMessageConverters` method like this to solve the previous problem. But what puzzles me is why the `addDefaultHttpMessageConverters` method does not use the `Jackson2ObjectMapperBuilder` in ApplicationContext, but creates a new `Jackson2ObjectMapperBuilder`?

```
    @Override
    protected void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
        converters.parallelStream().forEach(c -> {
            if (c instanceof MappingJackson2HttpMessageConverter) {
                ((MappingJackson2HttpMessageConverter) c).setObjectMapper(jacksonObjectMapperBuilder.build());
            }
        });
    }

```

**Comment by erikpetzold** [comment]
Hi @azi03 

I don't know what exactly you had before the change, so I don't know what exactly failed. But seems you created your own ObjectMapper or Builder whixh has then overridden the default one.

> But what puzzles me is why the addDefaultHttpMessageConverters method does not use the Jackson2ObjectMapperBuilder in ApplicationContext, but creates a new Jackson2ObjectMapperBuilder?
I think it should be the other way around: this creates the default instance and you can customize it. `addDefaultHttpMessageConverters` uses the `Jackson2ObjectMapperBuilder` which uses the modules, customizers etc from your context. So you should not create your own ObjectMapper or Builder, but just provide input to the existing builder. Like Spring Boot Admin does when registering the Modules in the Application Context.

The above is vald for the standard/default ObjectMapper. Only when you want to have a specialized ObjectMapper for specific cases, then you should create your own, like we do for LegacyEndpointConverter.

**Comment by azi03** [comment]
I didn't create my own `ObjectMapper `or builder. I just took out the built bean from `ApplicationContext `and gave it to `MappingJackson2HttpMessageConverter`. This should be caused by the lack of adaptation between swagger and webmvc, not the problem of admin itself. Thank you for @SteKoe and @erikpetzold help and discussion. I'll close this problem first
