### ISSUE TITLE
[springboot2.6.6]Unable to download package

### ISSUE THREAD

**Issue by mdddj** [codecentric/spring-boot-admin#2022]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/29020213/163504378-f2b7cf59-0519-444c-a1ab-6b90092cc450.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29020213/163504421-54cffd4e-5a4e-4c43-9007-0e2c69031f5f.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/29020213/163504455-11073c5a-8ee4-4016-8dd0-c8380d3c7341.png">
I try to add package in springboot2.6.6 project, but can't download, I don't know what happened

```bash
无法解析 Failure to transfer de.codecentric:spring-boot-admin-starter-server:pom:2.4.0-SNAPSHOT from http://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshot has elapsed or updates are forced. Original error: Could not transfer artifact de.codecentric:spring-boot-admin-starter-server:pom:2.4.0-SNAPSHOT from/to spring-snapshot (http://repo.spring.io/snapshot): Transfer failed for http://repo.spring.io/snapshot/de/codecentric/spring-boot-admin-starter-server/2.4.0-SNAPSHOT/spring-boot-admin-starter-server-2.4.0-SNAPSHOT.pom 308 Permanent Redirect
```

**Comment by SteKoe** [comment]
Hi @mdddj,

as you are using Spring Boot 2.6.6 please use the release version 2.6.6 of SBA, as well. 

```
<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>spring-boot-admin-starter-server</artifactId>
  <version>2.6.6</version>
</dependency>
```

If you want to use snapshot versions, you have to configure GitHub to be a maven repository as shown here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry. We do not push snapshot versions to maven central. 

Anyways, we do not recommend using snapshot versions anyway.
