### ISSUE TITLE
Is it possible to add Chinese support to the document?

### ISSUE THREAD

**Issue by qq253498229** [codecentric/spring-boot-admin#2023]
I translated the document into Chinese. Here is the address of GitHub:

https://github.com/qq253498229/docs-spring-boot-admin-docs-chinese

**Comment by SteKoe** [comment]
Hi @qq253498229,

thanks for your afford to translate the reference guide. We have added a link to your translation in our README.md (https://github.com/codecentric/spring-boot-admin#reference-guide).
