### ISSUE TITLE
No error message when a Jolokia call fails

### ISSUE THREAD

**Issue by lleder** [codecentric/spring-boot-admin#2024]
Hi all,

I've noticed a recent change in the handling of failed JMX invocations. Up until version 2.6.5, the Spring Boot Admin UI shows an error message if a Jolokia call returns a response with an HTTP status >= 400.
![image](https://user-images.githubusercontent.com/40660132/164720973-5168c28f-fe89-4ddf-bc27-3bbf9183b73e.png)

With version 2.6.6, this is no longer the case. The operation is shown as successful and no further output is displayed.
![image](https://user-images.githubusercontent.com/40660132/164720628-b3e190d4-722a-495f-9507-2e9c551f4361.png)

This is very likely a consequence of the pull request https://github.com/codecentric/spring-boot-admin/pull/2014, so I would like to ask whether this change was actually intended or happened by accident.

**Comment by SteKoe** [comment]
Hi @lleder, that is definitely a bug. I have created a PR that fixes this issue and adds some tests. It will be part of our next release.
