### ISSUE TITLE
Support tab menu expand list view for external menus 

### ISSUE THREAD

**Issue by hwy425** [codecentric/spring-boot-admin#2031]
Hi SBA team,

Could you please to support the external menu list view?  Like that language menu. So that we can customized some category menus. and there should be no limitation for users.

**Comment by erikpetzold** [comment]
Hi @hwy425 ,

sorry but I have absolutely no idea what you want. Can you please add some more description and maybe some screenshots/examples?

And is this the same like #2032?

**Comment by erikpetzold** [comment]
We assume you mean the same like #2032, so I will close this issue now. If you mean sth else please reopen with more details.
