### ISSUE TITLE
Support dropdown menu for the top level custom views

### ISSUE THREAD

**Issue by Kieun** [codecentric/spring-boot-admin#2032]
We have multiple top-level custom views to manage our applications.
Since the room for the top-level menu to add number of custom features is quite small, it is hard for us to locate our menu in the top level menu.

**Comment by Kieun** [comment]
@SteKoe First of all, thanks for the great products and concerning this issue. It seems that the feature might be added to 3.0.0. Can I get ETA for the version?
If it takes quite long time, could you prioritize this feature up?

**Comment by SteKoe** [comment]
Hi @Kieun,

we have just merged https://github.com/codecentric/spring-boot-admin/pull/2033 which allows you to add submenu items to *any* top menu. It will be part of the next release of SBA 2.6. 

Regards,
SteKoe
