### ISSUE TITLE
Provide account creation and reset/change password menu

### ISSUE THREAD

**Issue by Kieun** [codecentric/spring-boot-admin#2034]
This issue is related to the  #2032.
In our case, rather than register default user account into properties, we leverage the database for identity, authentication management.
To create the accounts, we create our own custom view to register username and account.
It is good to have account creation page and reset/change password page so that we can use it.

Especially, for account management (reset, change password), it would be great to locate under the **user** menu.

Thanks.

**Comment by SteKoe** [comment]
Hi @Kieun,

We have just merged https://github.com/codecentric/spring-boot-admin/pull/2033 which allows you to add submenu items to the user menu by setting `parent: 'user'`. 

Regards,
SteKoe
