### ISSUE TITLE
Not rediscovering instances after a deregistration

### ISSUE THREAD

**Issue by jaschenk** [codecentric/spring-boot-admin#2035]
Using 2.6.5 of SBA, Spring Boot 2.6.6, JDK 17, Consul Discovery.
Having issue when an instance deregisters, it may or may not get rediscovered.

Upon trapping a De-Registration Event, Is there a way to notify that Consul Discovery should be re-checked?  As I see instances gets de-registered in Journal and the instance has restarted, registered to Consul, however SBA, seldom triggers to check Consul again. Sometimes works sometimes it does not. Thoughts?

**Comment by ulischulte** [comment]
Hi @jaschenk,

there might be a problem with your spring cloud discovery config. Could you please check your configuration (for instance Consul Catalog watch -> see https://cloud.spring.io/spring-cloud-consul/reference/html/#consul-catalog-watch).

If you still encounter any problems, please provide your server config for further investigations.

**Comment by jaschenk** [comment]
Hello @ulischulte I added the following to SBA's Configuration:
spring:
  cloud:
    config:
      ...
      discovery:
        ...
      name: ${spring.application.name}
    consul:
      discovery:
        # watch Delay In Milliseconds ... (default is 1000)
        catalog-services-watch-delay: 10000
        # watch Timeout In Seconds ... (default is 2)
        catalog-services-watch-timeout: 5
#

Then on the Service/App Side I added:
spring:
  cloud:
    config:
      ...
      discovery:
        ...
    consul:
      discovery:
        heartbeat:
          enabled: true
          reregister-service-on-failure: true
          ttl: 120

#####

That appeared to work and was very robust, however, consul kept failing/flapping the interface due to TTL Timeout and had to back out.  Almost there but no cigar.

Any additional thoughts would be appreciated.

Thanks,
Jeff

**Comment by jaschenk** [comment]
Just wanted to post the differences in discovery times.  When a service with 2 instances behind it and we start a deployment cycle, where one instance will be redeployed and the next, the first new instance is discovered relatively quickly.  However, the 2nd instance takes in this screen capture at least 55 minutes to be re-discovered.

![image](https://user-images.githubusercontent.com/440314/169069035-1d3db0ef-46e9-413f-8a27-60f7e1276a4d.png)

Please advise.

Thanks,
Jeff

**Comment by jaschenk** [comment]
I have confirmed that this is not the Discovery Client, after turning on TRACE logging for Discovery Client I am seeing data presented to SBA from Consul with the previously DEREGISTERED app/instance information present indicating a new instance or recovery.  

However, SBA is not acting fast enough.  It would be nice if a DEREGISTER occurs, queue to peek for newly discovered instance and reregister. 

Please advise.

Thanks,
Jeff

**Comment by jaschenk** [comment]
The closed issue appears to be the scenario: [1092](https://github.com/codecentric/spring-boot-admin/issues/1092).

**Comment by jaschenk** [comment]
Closing as this is just a waste of time.  Bottom line after a service/instance goes away a long time period when it is eventually re-discover if at all.
