### ISSUE TITLE
Developer can enable spring-boot-admin optional

### ISSUE THREAD

**Issue by MonkeyYeah** [codecentric/spring-boot-admin#2037]
Now I can realize it only comment with @EnableAdminServer，Can you enhance @EnableAdminServer to choose either enable it.

**Comment by SteKoe** [comment]
Hi @MonkeyYeah,

I am not pretty sure wether I get you right, but I assume that you want to disable the AdminServer even if the @EnableAdminServer annotation is present. If so, you can disable it by setting `spring.boot.admin.server.enabled` to `false` (c.f. https://codecentric.github.io/spring-boot-admin/2.6.6/#_configuration_options).
