### ISSUE TITLE
logging out from UI breaks custom SBA context-path configuration

### ISSUE THREAD

**Issue by ViliusS** [codecentric/spring-boot-admin#2040]
I have spring.boot.admin.context-path set to /admin
I have also configured Spring Boot Admin security using reactive sample.

Everything in UI works fine under that path. I can login, browse, services can authenticate, etc. However if I click Logout it first goes into /login?logout which then forwards it to /admin/logout link. This is fine if running SBA standalone, however if running in Kubernetes and / is routing to some other service you get redirected out of SBA.

This is not critical issue, but still would be nice to have it fixed.

**Comment by erikpetzold** [comment]
Hi @ViliusS 

did you configure the context path in your security config?
In `SpringBootAdminConsulApplication` you can find an example with context paths.

If there are still problems, please provide more detaills (version, security config, relevant properties) or an example app.

Regards, Erik

**Comment by ViliusS** [comment]
I was using this.adminServer.path("/logout"), but just tried with this.adminServerContext + "/logout" which I assume is the same. Still on logout it redirects to /logout?login.

I initialize path the same way for "login" and other URLs, and /admin/login works fine. It's only /logout which doesn't work.

I'm using latest SBA version 2.6.7 with Spring Boot 2.6.7. I believe it includes Spring Security 5.6.3 
My app is essentially the same as in Reactive example with minor changes:
```
package lt.sample.admin;

import de.codecentric.boot.admin.server.config.AdminServerProperties;
import de.codecentric.boot.admin.server.config.EnableAdminServer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.AutoConfigurationPackage;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.security.config.Customizer;
import org.springframework.security.config.web.server.ServerHttpSecurity;
import org.springframework.security.web.server.SecurityWebFilterChain;

@SpringBootApplication
@Configuration(proxyBeanMethods = false)
@AutoConfigurationPackage
@EnableAdminServer
public class AdminApplication {

	private AdminServerProperties adminServer;

	public AdminApplication(AdminServerProperties adminServer) {
		this.adminServer = adminServer;
	}

	public static void main(String[] args) {
		SpringApplication.run(AdminApplication.class, args);
	}

	@Bean
	@Profile("insecure")
	public SecurityWebFilterChain securityWebFilterChainPermitAll(ServerHttpSecurity http) {
		return http.authorizeExchange((authorizeExchange) -> authorizeExchange.anyExchange().permitAll())
				.csrf(ServerHttpSecurity.CsrfSpec::disable).build();
	}

	@Bean
	@Profile("secure")
	public SecurityWebFilterChain securityWebFilterChainSecure(ServerHttpSecurity http) {
		return http
				.authorizeExchange((authorizeExchange) -> authorizeExchange
						.pathMatchers(this.adminServer.path("/assets/**")).permitAll()
						.pathMatchers("/actuator/health/**").permitAll()
						.pathMatchers(this.adminServer.path("/login")).permitAll().anyExchange().authenticated())
				.formLogin((formLogin) -> formLogin.loginPage(this.adminServer.path("/login")))
				.logout((logout) -> logout.logoutUrl(this.adminServer.path("/logout")))
				.httpBasic(Customizer.withDefaults()).csrf(ServerHttpSecurity.CsrfSpec::disable).build();
	}
}
```

application.properties
```
server.port=8887
spring.boot.admin.context-path=/admin/
# active profile
spring.profiles.active=${ENVIRONMENT:dev,secure}
logging.level.root=INFO

spring.security.user.name=${SBA_HTTP_USERNAME:admin}
spring.security.user.password=${SBA_HTTP_PASSWORD:admin}

```

**Comment by ulischulte** [comment]
Hi @ViliusS,

If you don't configure a SimpleUrlLogoutSuccessHandler, Spring Boot will redirect to the default which is `/login?logout`. You can simply configure a different behaviour by adding a handler with `logoutSuccessUrl`.
You can find the documentation here: https://docs.spring.io/spring-security/reference/servlet/authentication/logout.html

Regards
Uli

**Comment by ViliusS** [comment]
Hi @ulischulte,

thank you for your answer. I looked at it but unfortunately logoutSuccessUrl only available for Servlet applications. It doesn't work in my case for Reactive app.

However, given your guidance I found a way to set logoutSuccessUrl via different way and made a PR for Reactive sample https://github.com/codecentric/spring-boot-admin/pull/2064
