### ISSUE TITLE
spring-boot-admin-starter-client not working with springboot 2.6.6

### ISSUE THREAD

**Issue by naughtyFingers031** [codecentric/spring-boot-admin#2043]
**Greetings, I recently upgraded my springboot version from 2.5.4 to 2.6.6. My spring-boot-admin-starter-client 2.4.1 used to work with springboot 2.5.4. I tried using  spring-boot-admin-starter-client 2.4.1, 2.6.6 and 2.6.7 with springboot 2.6.6, all versions give the same runtime error below:**

> ***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.opentracing.contrib.spring.web.starter.SkipPatternAutoConfiguration$ManagementSkipPatternProviderConfig.getPatternForManagementServerProperties(SkipPatternAutoConfiguration.java:68)

The following method did not exist:

    org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getServlet()Lorg/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties$Servlet;

The calling method's class, io.opentracing.contrib.spring.web.starter.SkipPatternAutoConfiguration$ManagementSkipPatternProviderConfig, was loaded from the following location:

    jar:file:/C:/Users/Admin/.m2/repository/io/opentracing/contrib/opentracing-spring-web-starter/4.0.0/opentracing-spring-web-starter-4.0.0.jar!/io/opentracing/contrib/spring/web/starter/SkipPatternAutoConfiguration$ManagementSkipPatternProviderConfig.class

The called method's class, org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties, is available from the following locations:

    jar:file:/C:/Users/Admin/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.6.6/spring-boot-actuator-autoconfigure-2.6.6.jar!/org/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties.class

The called method's class hierarchy was loaded from the following locations:

    org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties: file:/C:/Users/Admin/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.6.6/spring-boot-actuator-autoconfigure-2.6.6.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.opentracing.contrib.spring.web.starter.SkipPatternAutoConfiguration$ManagementSkipPatternProviderConfig and org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties

**My YML configs:**

>    spring.boot.admin.client.password: admin
            spring.boot.admin.client.url: http://localhost:8080/
            spring.boot.admin.client.username: admin
               spring.boot.admin.client.instance.name: ${spring.application.name}
                  spring.boot.admin.client.instance.metadata.user.name: admin
                  spring.boot.admin.client.instance.metadata.user.password: admin

your feedback will be highly appreciated

**Comment by SteKoe** [comment]
Hi @naughtyFingers031,

as @chris-adfenix has stated, this is not related to SBA. Please file an issue at opentracing.
