### ISSUE TITLE
After upgrading to Spring boot 2.6.7, statusInfo.details missing in the response of https://xxx.com/boot-admin/applications

### ISSUE THREAD

**Issue by vellingirim** [codecentric/spring-boot-admin#2044]
After upgrading the spring boot-admin to 2.6.7, statusInfo.details missing in the response of /applications

Refer below attachment: 
![details_missing](https://user-images.githubusercontent.com/56846819/172211677-e9eabefe-d775-4686-a975-09c81526b3e7.JPG)

**Comment by andreasfritz** [comment]
Have you set following property?
management.endpoint.health.show-details=always

**Comment by SteKoe** [comment]
Hi @vellingirim,

Thanks for opening this issue. Spring Boot Admin is built as an event-based system and therefore may be in an inconsistent state on startup. The highlighted values are just initial values that are transient and used for the first render of the web user interface. Spring Boot Admin Server is polling the health-Endpoint periodically to update the status of each instance and publishes these statuses via an Event Stream to the front end. In other words, a GET-Request on `/applications` just returns a snapshot of the current state of an application. 

Kind regards,
Stephan
