### ISSUE TITLE
The applicaton view broken because of css import

### ISSUE THREAD

**Issue by michael-wirth** [codecentric/spring-boot-admin#2056]
The application list view is broken because of duplicated CSS rules.

The Bulma CSS is loaded by the `chunk-common.css` AND the `sba-core.css`. The order of loading the CSS rules is critical.
Some rules defined in the `sba-core.css` are now overridden by the default Bulma CSS, which is also imported in the `sba-core.css`.
The Bulma CSS are now loaded twice!

The bug is caused with the statement `@import "~@/assets/css/base";` in commit https://github.com/codecentric/spring-boot-admin/commit/586bf657fe7041724fe0e04d363a9db1c2ff4277#diff-a7d03e630ffebf56030fcfcf11744ca3449f6fdb04f115afdeb0934c9ed47cf0R104

![image](https://user-images.githubusercontent.com/3389626/175813578-05585f2b-3459-4961-bc70-b214dbca441f.png)

Compare the generated CSS files before and after:

### Before
```txt
  target/dist/assets/css/chunk-common.1c6e97d8.css           237.73 KiB
  target/dist/assets/css/sba-core.e2779621.css               41.84 KiB 
```

### After
```txt
  target/dist/assets/css/chunk-common.1c6e97d8.css           237.73 KiB 
  target/dist/assets/css/sba-core.01dd3b14.css               279.57 KiB   <-- includes the Bulma CSS

```

**Comment by Peksa** [comment]
We also noticed this - any chance for a patch release for this, or will this be released with a new Spring version?
