### ISSUE TITLE
/applications/xxx cannot display the instance list normally

### ISSUE THREAD

**Issue by kuengroc** [codecentric/spring-boot-admin#2061]
` springBootAdminVersion = "2.6.6"`

`/applications/xxx` cannot display the instance list normally
![image](https://user-images.githubusercontent.com/102577917/176112834-c855b4a0-4aab-4ecc-99f1-c537095b8d89.png)

**Comment by erikpetzold** [comment]
Hi @kuengroc 

does this happen for all your services or just one specific?

Can you provide the responses of the network calls? Should be `/applications` 

We also noticed there is "APPLICATIONS.DOWN" in your frontend, but there should be at least an english fallback, so seems something is broken in general.

**Comment by ulischulte** [comment]
We're closing this issue due to missing feedback.
