### ISSUE TITLE
springbootadmin2.7.2的版本前端页面无法显示

### ISSUE THREAD

**Issue by zhanghengdashuaibi** [codecentric/spring-boot-admin#2066]
启动2.7.2版本的项目访问home报错没有找到

**Comment by SteKoe** [comment]
> The version front-end page of springbootadmin2.7.2 cannot be displayed
> Start the 2.7.2 version of the project to access the home error report not found

A little bit more information is required to check your issue. 
Could you please elaborate which problem you actually face (add error messages or screenshots).
Please provide a test case or sample application that reproduces the problem if possible.

**Comment by lhchong** [comment]
我刚刚也碰到了类似的情况，希望对你有所帮助，建议确认下springboot的版本是否有关
从 spring-boot-admin 发布的版本日志可以得知 spring-boot-admin 2.7.2依赖于 spring-boot 2.7.0

**Comment by lhchong** [comment]
> 启动2.7.2版本的项目访问首页报错没有找到

我刚刚的日志也确认了下类似spring-boot的情况，希望能从
spring-boot-admin的发布版本中得知spring-boot-admin的版本是否适用于spring-boot-admin的7.2版本。 2.7.0

**Comment by lhchong** [comment]
> 启动2.7.2版本的项目访问home报错没有找到

从spring-boot-admin的版本发布日志得知 spring-boot-admin 2.7.2依赖于spring-boot 2.7.0 
我也遇到了类似的情况，我的是因为版本问题导致的，希望能对你有些帮助
