### ISSUE TITLE
Is fetchRegistry: true always required for SBA running inside Eureka?

### ISSUE THREAD

**Issue by filpano** [codecentric/spring-boot-admin#2067]
SBA version: `2.5.5`
Eureka Server version: `3.0.5`
Spring Boot version: `2.5.13`

We have a `dev` profile for our Eureka so that it runs in standalone mode for development purposes. The [recommended configuration](https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-eureka-server.html#spring-cloud-eureka-server-standalone-mode) for this is to set:

```yaml
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
```

However, it seems that SBA defers to `eureka.client.fetchRegistry` being true to actually retrieve the running applications when ran inside of Eureka (i.e. not as a standalone SBA server application).

The [SBA reference docs](https://codecentric.github.io/spring-boot-admin/current/#discover-clients-via-spring-cloud-discovery) as well as the accompanying [running-inside-eureka configuration example](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-eureka/src/main/resources/application.yml) seem to imply a replicated Eureka registry at all times.

Is there any way around this behaviour for standalone Eureka registries?

**Comment by erikpetzold** [comment]
Hi @filpano 

we understood, that you have combined Eureka Server and Spring Boot Admin Server in a single application, is this correct?

And then the config required for a single-instance Eureka is conflicting with the config required for SBA using Eureka, right?

Spring Boot Admin is using the Eureka client provided by Eureka (through spring-cloud), so both parts of your application use the same client. We do not see a simple way to have 2 clients with different configs.

The simplest solution would be to separate both into own applications I think.

**Comment by filpano** [comment]
Hi @erikpetzold , thanks for the reply.

>we understood, that you have combined Eureka Server and Spring Boot Admin Server in a single application, is this correct?
>And then the config required for a single-instance Eureka is conflicting with the config required for SBA using Eureka, right?

Correct.

>Spring Boot Admin is using the Eureka client provided by Eureka (through spring-cloud), so both parts of your application use the same client.

Ah, I see. I was under the impresison that SBA initializes its own Eureka Client. That explains the behaviour. 

>We do not see a simple way to have 2 clients with different configs.

You're right. I initially thought that we might teach SBA to first look for its own qualified Eureka Client bean, but AFAIK, `@ConditionalOnBean` cannot match that directly and so this would not work.

Thanks for the response.
