### ISSUE TITLE
Zuul problems in api-gateway with spring-boot-admin enabled

### ISSUE THREAD

**Issue by magaton** [codecentric/spring-boot-admin#208]
Hi, we hit the strange problem that our zuul routes defined in api-gateway are completely ignored when:
Here is the main class:
`@EnableAdminServer
@ComponentScan("com.acme.app")
@SpringBootApplication
@EnableEurekaClient
@EnableZuulProxy
public class GatewayAPIApplication extends SpringApplication`

And we have zuul routes defined in application.yml which work ok if we don't include spring-boot-admin-server.

When we enable logging in org.springframework.cloud: DEBUG
We can see that all spring-boot-admin routes are initialised, but not ours.
Any idea? 
Thank you

**Comment by joshiste** [comment]
Spring Boot Admin Server itself uses a modified zuul proxy. Adding your own routes is not supported. 

I guess you need the additional routes for business and not monitoring purposes. I strongly advise you not to include your monitoring application with your business application.
