### ISSUE TITLE
Deregister apps which have been removed from Eureka

### ISSUE THREAD

**Issue by herder** [codecentric/spring-boot-admin#211]
We're using the DiscoveryClient approach to registering apps in Boot Admin, but this makes instances linger on in the UI, causing dramatic slowdowns after a few deploys of our services.

I guess the fix for this would be that apps which are gone from Eureka are deregistered by the server when updating the app registry from Eureka?

**Comment by joshiste** [comment]
Sounds reasonable.

**Comment by herder** [comment]
Great, I'll try and whip up a PR for this.

**Comment by joshiste** [comment]
Your code on gitter is pointing in the right direction. But remember we need to be compatible with Java 7.

**Comment by joshiste** [comment]
Fixed with #215
