### ISSUE TITLE
Ability to start API (not restart

### ISSUE THREAD

**Issue by dbnex14** [codecentric/spring-boot-admin#2112]
I would be nice we can use code admin to stop, start, or restart the application.
Stopping and restarting is probably already supported as actuators support them.  However, it would be nice to also be able to start an API that was down for some time.
For example, testers would like to stop API, do some testing, then 2 hours later start it up again.  This is different from restart.

**Comment by SteKoe** [comment]
Hi @dbnex14,

thank you for your message but the requested feature is out of scope. Spring Boot Admin supports actions offered by actuators of registered clients only and is not able to start JVM processes in general. It sounds like you need to have some pipeline triggering the deployment of service whenever necessary.
