### ISSUE TITLE
Status of Shutdown button in Spring Boot Admin UI

### ISSUE THREAD

**Issue by saikrishnasaski** [codecentric/spring-boot-admin#2116]

**Comment by erikpetzold** [comment]
hi @saikrishnasaski, have you also exposed the shutdown endpoints? You need to enable and expose via web.

You can list all active actuators by invoking https://yourApp:managementport/actuator

You can also try to invoke the endpoint directly to test if it is available (use a POST request!)

**Comment by saikrishnasaski** [comment]
I have integrated spring boot admin with OAuth2.0. For Admin users I am able to shut down the clients. For normal users spring boot admin throws 403 from application, but in UI I am not seeing any 403 like forbidden. Is there a way to add this?

**Comment by erikpetzold** [comment]
Probably it is not possible at the moment.
We will discuss on Friday if we add something like this. If I remember correctly we recently added showing the result of an actuator call for some other endpoint.

**Comment by saikrishnasaski** [comment]
Thanks @erikpetzold for the information. Sure we will discuss on Friday.

**Comment by SteKoe** [comment]
We have implemented a notification that will be shipped in 2.9.10.

**Comment by saikrishnasaski** [comment]
Thanks @SteKoe :)
