### ISSUE TITLE
Allow the navbar logo and/or title to be customized

### ISSUE THREAD

**Issue by mrumpf** [codecentric/spring-boot-admin#212]
When there are many environments where the Spring Boot Admin server will be deployed to, it would be helpful to see the environment name as part of the UI. One idea would be to allow a custom logo.
The logo filename could be configurable as an application parameter so that different logos could be set per spring profile.
The logo should be read from the classpath so that it can be packaged with the application.

**Comment by joshiste** [comment]
Have you tried what happens if you place a custom logo at the same place in the classpath? it should take precedence. Sadly it wouldn't be configurable for each environment.

**Comment by chrisdimitr** [comment]
I tried this. I have placed a custom logo (logo.png) at src/resources/img but I always get 404 error. I tried several other locations (src/resources/static/img, src/resources/static/images, src/public/img ...) but I always get 404 error. Can we do something about that. I just want to change the logo and the navigation color (so I want to add a custom css also).

**Comment by joshiste** [comment]
Since SBA registers custom resource handlers, the right place for the custom edited assets would be these:

```shell
META-INF/spring-boot-admin-server-ui/img/spring-logo.png
META-INF/spring-boot-admin-server-ui/img/favicon.png
META-INF/spring-boot-admin-server-ui/css/main.css
```

but exchanging them is more a hack. And with 1.4.x these paths changes slightly.

**Comment by szisti** [comment]
placing a file called "spring-logo.png" into the `resources/META-INF/spring-boot-admin-server-ui/img/` works perfectly and overwrites the original logo with v1.5.2

**Comment by sddakoty** [comment]
How did you find that out? This seems not being documented. It works.

But I'd love being able to replace the `spring-boot-logo` image. But adding a `spring-boot-logo.png` in the same path did not work.

**Comment by szisti** [comment]
@sddakoty that file is called `platform-spring-boot.png`
and the favicon is `favicon.png` in the same folder

**Comment by sddakoty** [comment]
Ok great.

Is it also possible to override the css somehow? I tried adding a `main.css` as follows, but that did not work (my logo is too large and exceeds the default 160px width):
```
.spring-logo {
    width: 300px !important;
}
```

**Comment by szisti** [comment]
@sddakoty if you check the content of the spring-boot-admin-server-ui jar 
you can see that the css is called core.css and is in `META-INF/spring-boot-admin-server-ui/`

**Comment by sddakoty** [comment]
Well, I also tried renaming the file to `core.css`, but still nothing is overridden. The logo `width` attribute remains the same.

**Comment by shakuzen** [comment]
> When there are many environments where the Spring Boot Admin server will be deployed to, it would be helpful to see the environment name as part of the UI.

This seems like a great idea, given that Spring Boot Admin makes it easier to use actuator endpoints that can affect the behavior of applications. It is important to make users aware of which environment they are interacting, and just having different URLs is often overlooked.
Changing the background color is another way to help distinguish between environments.

**Comment by anandvarkeyphilips** [comment]
This is still not working for me.. Is it working??

**Comment by tenglongwentian** [comment]
@monsif success，good，thinks。
