### ISSUE TITLE
Maybe the error alert popups could be a little more obvious. Version: 3.0.0-M4

### ISSUE THREAD

**Issue by OnlyEatCairoubao** [codecentric/spring-boot-admin#2130]
Hi. The 401 error code is prompted when login fails. But the error code is not displayed long enough, only for a moment, and the alert box is displayed on the admin page after login. Maybe the error alert box could pop up on the login page, so that the user experience will be better. Although there are logs in the backend of the program, I hope there will be feedback from the frontend page, thanks.
![Spring-Boot-Admin-Error-Message](https://cdn.staticaly.com/gh/OnlyEatCairoubao/image-hosting@master/杂七杂八/Spring-Boot-Admin-Error-Message.6uidooonxoo0.webp)

**Comment by SteKoe** [comment]
Error message will be more informative when redirected to login screen (includes error code). Hope that hits your expectations.

<img width="531" alt="Bildschirmfoto 2022-09-30 um 10 44 00" src="https://user-images.githubusercontent.com/1809221/193230938-26c6116a-d5ba-4ae2-bf71-0a36ee698805.png">

**Comment by OnlyEatCairoubao** [comment]
> 

Thanks, that's much better.

**Comment by OnlyEatCairoubao** [comment]
> Error message will be more informative when redirected to login screen (includes error code). Hope that hits your expectations.
> 
> <img alt="Bildschirmfoto 2022-09-30 um 10 44 00" width="531" src="https://user-images.githubusercontent.com/1809221/193230938-26c6116a-d5ba-4ae2-bf71-0a36ee698805.png">

Thanks, that's much better.
