### ISSUE TITLE
Configuring ip in spring boot admin client

### ISSUE THREAD

**Issue by deveshprobus** [codecentric/spring-boot-admin#2132]
I am using spring boot admin version 2.6.9 and using

spring.boot.admin.client.instance.prefer-ip=true

to register to admin server via ip. Now since I am running my apps inside docker containers the admin server receives docker ips and not the public ips of the applications. I have tried changing management.address but that does not work. I can not use docker network to connect to these machines and I can not change server.address property. I have tried below properties as well but they dont show anything on admin server apart from online status.

spring.boot.admin.client.instance.service-url=http://11.0.134.202:9999
spring.boot.admin.client.instance.management-url=http://11.212.134.202:9999

**Comment by ulischulte** [comment]
Hi @deveshprobus,

the problem you describe does not seem to be a bug, but rather a configuration problem. To solve this, we need more information about your configuration - especially your client's configuration (application.properties/yaml + docker config).

Regards,
Uli

**Comment by deveshprobus** [comment]
I got it working using below

spring.boot.admin.client.instance.prefer-ip=true
spring.boot.admin.client.instance.service-url=http://127.0.0.1:9999
spring.boot.admin.client.instance.management-url=http://127.0.0.1:9999/actuator

But if I run my client application on port 443 I am still facing issues because I think spring boot admin starts to try connecting with port 80


io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:80
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET info [DefaultWebClient]
Stack trace:
Caused by: java.net.ConnectException: Connection refused: no further information

**Comment by ulischulte** [comment]
Hi @deveshprobus,

this still seems to be a configuration problem. For instance - is your application running behind a frontend-proxy which terminates the http connection? In that case, it may be necessary to configure ´server.forward-headers-strategy=native´ (also see Spring Boot Reference Guide https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server).

Regards,
Uli

**Comment by erikpetzold** [comment]
Closing this issue, as there was no more response. If you still have problems, feel free to reopen or create a new issue.

In general, more information helps to understand and solve the problem. (like already asked: is there a proxy, who is terminating the ssl connection, which discovery mechanism is used, which properties are configured, is the problem occuring during registration or when invoking the actuator, is exception from client or server log, ...)
