### ISSUE TITLE
Support reactive HttpHeaderProvider's

### ISSUE THREAD

**Issue by braunsonm** [codecentric/spring-boot-admin#2137]
Currently the `HttpHeaderProvider` does not run in a reactive pipeline even when you are running the spring boot admin server in webflux mode. This hampers the use case for providing headers when making requests to downstream instances.

The implementation that needs to change is here: https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/config/AdminServerInstanceWebClientConfiguration.java#L84

Specifically, a new interface should be created that accepts Mono's which are resolved as part of the request. See the composite here: https://github.com/codecentric/spring-boot-admin/blob/f865a094cea04c5ba0a5ba4ef5f6a66132cb1079/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/web/client/CompositeHttpHeadersProvider.java#L25

This is required for use cases where you want to access the currently authenticated user when writing your `getHeaders` method as you need to use the `ReactiveSecurityContextHolder` and not the `SecurityContextHolder`

**Comment by erikpetzold** [comment]
Hi @braunsonm , thanks for your detailed request. We had a look and it will be fixed with #2142. (Some stuff like tests still missing)

**Comment by braunsonm** [comment]
Awesome thank you @erikpetzold it looks great.

**Comment by SteKoe** [comment]
We have implemented this in #2142. :)
