### ISSUE TITLE
springboot 整合 spring-boot-admin出现静态资源无法访问?

### ISSUE THREAD

**Issue by Zhangjian195** [codecentric/spring-boot-admin#2149]
springboot2.3.2/admin2.3.0
maven方式引入
spring-boot-admin-starter-server
后出现静态资源无法访问，同时也引入了spring-boot-security（重写WebSecurityConfigurerAdapter对所有请求放行）。

有没有大佬知道这是怎么回事吗🧐

**Comment by qqhai007** [comment]
用英文提问，回答的人会多一些，你这个是配置问题  或者兼容问题，你给的信息太少  很难直接看出问题
