### ISSUE TITLE
IP selectivity problem of multiple network adapters

### ISSUE THREAD

**Issue by tonycody** [codecentric/spring-boot-admin#2159]
e.g.
eth0(The internet network)
129.227.8.189
eth1(The  internal network)
172.16.1.231

When Spring boot admin client instance get ip,Internet IP addresses may be obtained, and Intranet IP addresses are expected to be registered.
You are advised to specify a parameter for filtering only Intranet IP addresses

**Comment by ulischulte** [comment]
Hi @tonycody,

We are not 100% sure we understand your problem. Generally, it is helpful if you use our template when recording a bug. I.e. ideally you should give us the following information: 

- config properties (server and client)
- Discovery mechanism used
- Spring Boot Admin version (server and client)
- Configured security
- Webflux or servlet variant
- deployment infrastructure (docker, kubernetes, onPrem ...)

etc...

In the following image we have tried to capture our interpretation of your problem:

![image](https://user-images.githubusercontent.com/16336547/201299251-9ee79354-cbde-4183-ac8f-b83b21ab90b0.png)

We assume your client registered itself without any service discovery mechanism.
Do we understand your problem correctly? 

Furthermore have a look at https://codecentric.github.io/spring-boot-admin/current/#spring-boot-admin-client and the properties concerning registration via ip. Did you configure the property ```spring.boot.admin.client.instance.prefer-ip```? Then please have a look at the description within the table and set the according properties to the correct ip address.

Regards
Uli

**Comment by ulischulte** [comment]
Closed due to missing feedback. If your problem still occurs, please open a new issue.
