### ISSUE TITLE
Add ability to configure custom application links

### ISSUE THREAD

**Issue by aantono** [codecentric/spring-boot-admin#216]
Similar to "capabilities" that are hard-coded for Spring Boot endpoints like "LogFile", etc. allow for configuring custom URLs for applications that might lead to internal tools, or things like Jenkins build job, Git repo, etc.

**Comment by joshiste** [comment]
I would suggest you to include these informations in your info-endpoint.

**Comment by aantono** [comment]
Those links are not rendered as href clickable, and they present unnecessary burden on every application developer having to explicitly include them in the configuration.

Can you elaborate as to why you are reluctant to consider this feature, or at least to discuss it?

**Comment by aantono** [comment]
Would you be willing to accept a PR if I submit one for this functionality?

**Comment by joshiste** [comment]
> Those links are not rendered as href clickable, and they present unnecessary burden on every application developer having to explicitly include them in the configuration.
 
I'd suggest one of the following ways around this:
1) you add these information during your (standardised?) build process (for example with maven filtering) - i guess the information are in your `pom.xml` or your build environment.
2) you write a custom InfoEndpoint which contains the information
3) you implement a `InfoContributor` (spring boot 1.4.x) adding the information

>Can you elaborate as to why you are reluctant to consider this feature, or at least to discuss it?

1) You could already show the desired information right now without any change to SBA
2) I don't think its a heavy burden to add the informations to the /info endpoint. If you don't want to do it for every app over and over again manually - automate it! (solutions given above)
3) Imho the info endpoint is the right place where your application should show additional information.
4) SBA uses  the info endpoint to show additional infos for you app. If you would only submit them to SBA the information is not available to others.
5) SBA doesn't need any metadata to do it's work and therefore doesn't accept such. Your proposal needs extensions of the rest api.

>Would you be willing to accept a PR if I submit one for this functionality?

I would accept a PR that would enhance the info section and render things that looks like urls as links.
