### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by zgqq** [codecentric/spring-boot-admin#2161]
## Spring Boot Admin Server information

- **Version**:
2.7.7

- **Spring Boot version**:
2.7.5

- **Configured Security**:
  
```
            // @formatter:off
            SavedRequestAwareAuthenticationSuccessHandler successHandler =
                    new SavedRequestAwareAuthenticationSuccessHandler();
            successHandler.setTargetUrlParameter("redirectTo");
            successHandler.setDefaultTargetUrl(adminContextPath + "/");

            http.authorizeRequests()
                    .antMatchers(adminContextPath + "/assets/**").permitAll()
                    .antMatchers(adminContextPath + "/login").permitAll()
                    .anyRequest().authenticated()
                    .and()
                    .formLogin().loginPage(adminContextPath + "/login").successHandler(successHandler).and()
                    .logout().logoutUrl(adminContextPath + "/logout").and()
                    .httpBasic().and()
                    .csrf()
                    .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                    .ignoringAntMatchers(
                            adminContextPath + "/instances",
                            adminContextPath + "/actuator/**"
                    );
            // @formatter:on
```
- **Webflux or Servlet application**:
  
Servlet
## Client information

- **Spring Boot versions**:
  
  2.7.5

- **Used discovery mechanism**:
  
self registration
- **Webflux or Servlet application**:
  
servlet
## Description
`
spring.boot.admin.context-path=/sba-admin
`

Access via http returns a 404
```
113.116.142.93 - - [10/Nov/2022:11:26:25 +0000] "GET /sba-admin/login HTTP/1.1" 404 19 "-" "-" 3706 "-" "-" 0ms
```

Return 200 via https access
```
113.116.142.93 - - [10/Nov/2022:11:24:17 +0000] "GET /sba-admin/login HTTP/2.0" 200 1924 "-" "-" 3702 "flycat-sba0@docker" "http://172.18.0.4:8081" 12ms
```

**Comment by andreasfritz** [comment]
The configured spring security looks fine.
We assume that the problem is not related to Spring Boot Admin.
Please provide more information to your infrastructure, if you need more help.

**Comment by SteKoe** [comment]
Just a guess: Is the `loadbalancer.server.port` missing for `ROUTER_SBA**1**`? E.g.

`traefik.http.services.ROUTER_SBA1-service.loadbalancer.server.port=8080`

**Comment by zgqq** [comment]
@SteKoe The problem has been resolved. ROUTER_SBA1 is a variable with the value flycat-sba1 and ROUTER_SBA0 has the value flycat-sba0 because the traefik router cannot use hypen(-), causing problems with http entry access.
