### ISSUE TITLE
How can I set up remote client application?

### ISSUE THREAD

**Issue by edgaryeghiazarian** [codecentric/spring-boot-admin#2162]
I want to monitor spring boot applications running on remote server with docker compose.
How can I configure the client to listen the spring boot admin application on my local machine (or another remote server)?

**Comment by erikpetzold** [comment]
Hi @edgaryeghiazarian ,
there are 3 ways to tell the SBA server where the applications are running:

1) use a static list in the SBA server: https://codecentric.github.io/spring-boot-admin/current/#spring-cloud-discovery-static-config

2) let the applications register themselfes on the SBA server using the SBA client: https://codecentric.github.io/spring-boot-admin/current/#register-clients-via-spring-boot-admin

3) Use some discovery/registry mechnism supported by spring cloud (Kubernetes, Eureka, Zookeeper, Consul, …​): https://codecentric.github.io/spring-boot-admin/current/#discover-clients-via-spring-cloud-discovery

In all cases it does not matter on which machine the applications are running, as long as they are rechable via the network.
