### ISSUE TITLE
Frontend: Disable error toasts for axios responses

### ISSUE THREAD

**Issue by MichaelZett** [codecentric/spring-boot-admin#2165]
Since version 2.7.5 of Spring Boot Admin, we are getting a lot of 404 error toasts in our custom views because we are executing axios requests against our applications to see if an endpoint is available or not. We would rather avoid getting an error toast in the case of a 404 response because we also use that for optional endpoints and we don't want to maintain a list of apps that provide these endpoints but discover it.

Here is the axios interceptor responsible for the error toast: https://github.com/codecentric/spring-boot-admin/blob/2.7.7/spring-boot-admin-server-ui/src/main/frontend/utils/axios.js#L37

Would it be possible to add a configuration option to disable this toast in the custom views?

**Comment by SteKoe** [comment]
Hi @MichaelZett,

thanks for suggesting this enhancement. We are planning to implement a configuration option for this in the future. If you need this asap, feel free to provide a PR. FYI: In Spring Boot Admin 3, we have introduced grouped by HTTP-Status code toast messages to reduce pollution.

Regards
SteKoe

**Comment by mdzunic** [comment]
Hi, do you have any example of setting the configuration in frontend? I wasn't able to find anything like that in docs (https://codecentric.github.io/spring-boot-admin/)

Thanks,
Miroslav

**Comment by SteKoe** [comment]
Hi,

we have just released version 2.7.9 of SBA that includes a property to enable toasts `spring.boot.admin.ui.enable-toasts`. They are disabled by default, now.

Sorry for the inconvenience.
