### ISSUE TITLE
Frontend: Prevent JMX endpoints without parameter from accidental execution

### ISSUE THREAD

**Issue by EyedPeas** [codecentric/spring-boot-admin#2167]
Hey team, 

We're using SBA to manage our ~50 microservices and make extensive use of JMX Endpoints to execute important tasks (e.g. batch delete deactivated accounts). 
The problem: Some of them have no parameter and therefore can be accidentally activated with one wrong click. 
Would it be possible to integrate a 'security mode' where the execution of parameterless endpoints has to be confirmed? 

Thanks in advance!

**Comment by SteKoe** [comment]
Hi @EyedPeas,

thanks for suggesting this enhancement. We do not have plans to implement a feature like this, hence feel free to create a PR.

Regards
SteKoe
