### ISSUE TITLE
allow configuration of additional columns for instance list 

### ISSUE THREAD

**Issue by cforce** [codecentric/spring-boot-admin#217]
Allow to configure which metadataMap keys are shows as additional column's in listing.
Allow to set filter on this metadata list value value's

**Comment by joshiste** [comment]
The ui is currently not configurable and also doesn't show any metadata. In my opinion you should include the information you want to see in your info endpoints. For the most part it's are similar reasons like in #216

**Comment by joshiste** [comment]
@cforce do you have any comment on this or can i close this issue?

**Comment by cforce** [comment]
Can you give a hint to an example how to include that as an info point extesion?
The problem is that i need a filter (sort on a a table) to only show micro services having some attribute value.
Your solution enforces me to click on every single instance and search for this property value.
So your solution doesn't solve my request.

**Comment by joshiste** [comment]
> The problem is that i need a filter (sort on a a table) to only show micro services having some attribute value.
Your solution enforces me to click on every single instance and search for this property value.
So your solution doesn't solve my request.

the search box in the application list should also consider the values in the info coloum.
For adding things to the InfoEndpoint please refer to the [spring-boot-reference guide](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-application-info).
FYI: With spring boot 1.4 you have a more options
