### ISSUE TITLE
spring boot server Jump to error page when logging in

### ISSUE THREAD

**Issue by 96XL** [codecentric/spring-boot-admin#2171]
## Spring Boot Admin Server information

- **Version**:
  3.0.0-M5

- **Spring Boot version**:
  3.0.0-SNAPSHOT

## Description
application.yml add `context-path: /admin`

![image](https://user-images.githubusercontent.com/41610506/204774595-118f8140-81a6-4765-9d53-18012561aa70.png)

login 

![image](https://user-images.githubusercontent.com/41610506/204775422-ee5d78e7-2637-4498-baf7-1abe8fa5260a.png)

 Jump to error page

![image](https://user-images.githubusercontent.com/41610506/204775485-b0b3cafe-3914-4f1f-85a1-8ef525698e6b.png)

**Comment by erikpetzold** [comment]
Hi @96XL , can you please check if this still happens with 3.0.0-M6, which was released today? There were changes made to context path handling.
Thank you

**Comment by 96XL** [comment]
> 嗨@96XL，您能否检查一下今天发布的 3.0.0-M6 是否仍然发生这种情况？对上下文路径处理进行了更改。 谢谢

I have checked with 3.0.0-M6, login is successful, but if you click refresh in browser 404 is returned.

**Comment by 96XL** [comment]
> Hi @96XL , can you please check if this still happens with 3.0.0-M6, which was released today? There were changes made to context path handling. Thank you

I have checked with 3.0.0-M6, login is successful, but if you click refresh in browser 404 is returned.

**Comment by ulischulte** [comment]
This could be the same issue as #2175 which has been fixed in 3.0.0-M8. Please try again with the mentioned version.

**Comment by 96XL** [comment]
> This could be the same issue as #2175 which has been fixed in 3.0.0-M8. Please try again with the mentioned version.

I have no more questions, if there is a problem, i will check other issues.
Thank you
