### ISSUE TITLE
Supporting various naming convention

### ISSUE THREAD

**Issue by SeongEon-Jo** [codecentric/spring-boot-admin#2172]
I got some problem when trying to get spring actuator's metics data in spring admin server page.

While checking the problem, I found a warning like this.

![스크린샷 2022-12-01 오전 10 45 40](https://user-images.githubusercontent.com/62459414/204946214-a2250f0c-364c-48a7-a6be-b346981765c6.png)

The problematic spot was below.

![스크린샷 2022-12-01 오전 10 47 09](https://user-images.githubusercontent.com/62459414/204946341-0fe7bbd6-b2a0-4ba1-adda-456d96f0060d.png)

```response.data.availableTags``` was not getting the data successfully.

And my actuator's data was like this.
```
{"name":"hikaricp.connections","description":"Total connections","base_unit":null,"measurements":[{"statistic":"VALUE","value":11.0}],"available_tags":[{"tag":"pool","values":["HikariPool-1","HikariPool-2"]}]}
```

I guess this problem was because spring admin server is only handling the data of **lowerCamelCase** convention.

I will appreciate it if spring admin could support more various naming convention.

If you already have some answers to this, please let me know about it. Thank you

**Comment by erikpetzold** [comment]
Hi @SeongEon-Jo 

the frontend relies on the default json output of the actuators. Please do not change this format (via jackson config). There are already many issues for this topic, maybe have a look there.

In Spring Boot 3 this will also be enforced as Spring Boot itself uses a separate ObjectMapper for the actuator endpoints.
