### ISSUE TITLE
continuous 'Request failed: 404 - 404' shown in UI

### ISSUE THREAD

**Issue by robtha** [codecentric/spring-boot-admin#2174]
## Spring Boot Admin Server information

- **Version**:
2.7.8

- **Spring Boot version**:
2.7.6, 2.7.5

- **Configured Security**:
basic auth

- **Webflux or Servlet application**:
servlet

## Client information

- **Spring Boot versions**:
2.7.8

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
webflux or servlet

## Description
Admin Server UI repeatedly shows error message 'Request failed: 404 - 404' (see attached screenshot).
It seems, that admin server tries to query for system metrics, even if the are disabled on registered client app.

If first discovered this behaviour in spring-boot-admin version 2.7.5 - it did not appear in older versions.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/15860148/205322172-26aef16d-244e-4c0b-9f2d-6bda4aeb5227.png">

**Comment by SteKoe** [comment]
Hi,

we have just released version 2.7.9 of SBA that includes a property to enable toasts `spring.boot.admin.ui.enable-toasts`. They are disabled by default, now.

Sorry for the inconvenience.

**Comment by pgehl** [comment]
Awesome !!
Thanks a lot for the quick fix!!!
