### ISSUE TITLE
Spring Admin UI is flooded with "Request failed" error toasts when EVCache size is null

### ISSUE THREAD

**Issue by iuliiasobolevska** [codecentric/spring-boot-admin#2178]
## Spring Boot Admin Server information

- **Version**:
2.7.7

- **Spring Boot version**:
2.7.5

- **Webflux or Servlet application**:
Webflux

## Description
Spring Boot Admin shows an increased number of error toasts when `cache.size` metric is absent after updating to version 2.7.7. 
This is a result of the change made in https://github.com/codecentric/spring-boot-admin/commit/330252c385d93a1902dbcb131b848b81623086a5 that surfaces errors that were previously swallowed.

### Root cause
Micrometer doesn't emit `cache.size` metric when EVCache `size()` method returns `null`: 
* https://github.com/micrometer-metrics/micrometer/blob/e4e9ec9f120bdefdf72b166562138d229197b008/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CacheMeterBinder.java#L47-L58
* https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CacheMeterBinder.java#L95-L97

but Spring Admin expects metric to be present: 
* https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-cache.vue#L130-L131

showing a "Request failed" toast with the following error in the console when [response](https://github.com/codecentric/spring-boot-admin/blob/4b72b427b077ad24bdda56033b9c8fd597e633c1/spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-cache.vue#L131) is `undefined`:
```
Fetching cache EVCACHE_TEST size failed - error is ignored TypeError: Cannot read properties of undefined (reading 'data')
    at details-cache.vue:131:1
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```

Unfortunately, I don't have a screenshot right now but the first time the issue was observed the whole screen was flooded with error toasts which is surprising given that `shouldFetchCacheSize` should get set to `false` when the 1st issue is observed:
* https://github.com/codecentric/spring-boot-admin/blob/4b72b427b077ad24bdda56033b9c8fd597e633c1/spring-boot-admin-server-ui/src/main/frontend/views/instances/details/details-cache.vue#L133

### Potential solutions
I'm happy to submit a PR if you support the suggestion to handle response being `undefined` in a way that would disable further cache.size retrieval and do not show error toast at all (even for the 1st error) to not confuse customers.

**Comment by SteKoe** [comment]
Hi,

we have just released version 2.7.9 of SBA that includes a property to enable toasts `spring.boot.admin.ui.enable-toasts`. They are disabled by default, now. 
We hope that this reduces the confusion.

**Comment by iuliiasobolevska** [comment]
Appreciate the prompt response. What I was trying to point out is that it's totally valid for cache.size metric to not be emitted and Spring Admin doesn't respect that and as a result breaks contract. Disabling error toasts would hide the issue and as you pointed out would confuse customers less but it doesn't feel like the right fix. Apologies for not clearly explaining what I think the issue is about.

**Comment by SteKoe** [comment]
Hi @iuliiasobolevska,

sorry for closing the issue, we would love to see a PR fixing the issue in the frontend! :) 

Kind regards
SteKoe
