### ISSUE TITLE
Confusing Clear cache functionality for multiple instances

### ISSUE THREAD

**Issue by azemliankin** [codecentric/spring-boot-admin#2181]
**Enhancement**

https://github.com/codecentric/spring-boot-admin/pull/1785 adds a new toggle button for choosing to clear the cache on all instances or selected instance **(1)**. 

However, this functionality is applied only for the "Clear" button on top of the page, which clears all caches **(2)**. And not applied to particular caches "Clear" buttons in the list of all caches **(3)**.  

It seems confusing for us from the UX perspective. This toggle should be applied to all "Clear" buttons on the page
<img width="1765" alt="Screenshot 2022-12-16 at 14 53 40" src="https://user-images.githubusercontent.com/56021980/208103061-fa057609-825e-486a-a4d3-45298af00c60.png">

**Comment by psemeniuk** [comment]
Is anyone actively working on this? If not - i think i can allocate some time to solve this. 

But first i want to make sure that solution proposed by @azemliankin will not be considered as breaking change which will eventually block my contribution. Can you confirm @erikpetzold / @SteKoe ?

**Comment by erikpetzold** [comment]
I would say it can be changed like proposed - otherwise we would have closed/comment on the issue. It is open as enhancement, so just waiting for implementation.

Thanks for taking care of that issue!
