### ISSUE TITLE
3.0.0-M8 About page anchor links

### ISSUE THREAD

**Issue by dbarnhoorn** [codecentric/spring-boot-admin#2183]
## Spring Boot Admin Server information

- **Version**:
3.0.0-M8

- **Spring Boot version**:
3.0.1

- **Configured Security**:
basic auth

- **Webflux or Servlet application**:
servlet

## Client information

- **Spring Boot versions**:
3.0.0, 3.0.1

- **Used discovery mechanism**:
kubernetes discovery client

- **Webflux or Servlet application**:
servlet

## Description
The first two documentation links on the about page of the spring boot admin server application
- Spring Boot Admin Client : https://codecentric.github.io/spring-boot-admin/3.0.0-M8/#register-clients-via-spring-boot-admin
- Spring Cloud Discovery Client : https://codecentric.github.io/spring-boot-admin/3.0.0-M8/#discover-clients-via-spring-cloud-discovery
point at a non-existing anchor in the index.html, they should be pointing at https://codecentric.github.io/spring-boot-admin/3.0.0-M8/getting-started.html with the same two anchors.

**Comment by ulischulte** [comment]
Hi @dbarnhoorn!
Thanks for the tip. The links should be corrected in the next milestone version.
Regards,
Uli

**Comment by dbarnhoorn** [comment]
Just wanted to mention it, easily solved when you know it's there :) Thanks for the fix!
