### ISSUE TITLE
Spring

### ISSUE THREAD

**Issue by 1Ghub** [codecentric/spring-boot-admin#2184]
## Spring Boot Admin Server information

- **Version**:
  

- **Spring Boot version**:
  

- **Configured Security**:
  

- **Webflux or Servlet application**:
  

## Client information

- **Spring Boot versions**:
  

- **Used discovery mechanism**:
  

- **Webflux or Servlet application**:

**Comment by ulischulte** [comment]
We close this issue because it does not contain any description. If there is still a problem, feel free to open a new one with a filled template including a detailed description.

Regards,
Uli
