### ISSUE TITLE
How to show HttpExchange(http-traces) in v3.0.0

### ISSUE THREAD

**Issue by yellowms** [codecentric/spring-boot-admin#2185]
## Spring Boot Admin Server information

- **Version**: 3.0.0-M8
  

- **Spring Boot version**: 3.0.1
  

- **Webflux or Servlet application**: Servlet application
  

## Client information

- **Spring Boot versions**: 3.0.0-M8
  

- **Webflux or Servlet application**: Servlet application
  

## Description

In Spring Boot v3.x.x, The http-traces is change to HttpExchange!!!!
So,how to show the View  http-traces in new version???
I see the datas in client Actuator.But can't see the datas view/menu in Spring Boot Admin view!

**Comment by erikpetzold** [comment]
will be included in the next release
