### ISSUE TITLE
@project.version@ not evaluated anymore

### ISSUE THREAD

**Issue by jarmoni** [codecentric/spring-boot-admin#220]
I recently updated from 1.3.2 to 1.3.3 and neither @project.version@ nor @pom.version@ are evaluated. They are displayed as plain String in the UI. (Same with @project.artifactId@/@pom.artifactId@)

**Comment by joshiste** [comment]
This is not a feature of spring boot admin.
I guess there is something wrong with your maven filtering options. The spring boot parent has this configured, but afaik the didn't change ther config.
The maven integration in Eclipse sometimes messes this up.
