### ISSUE TITLE
how to config to send mail when server is down?

### ISSUE THREAD

**Issue by dragontree101** [codecentric/spring-boot-admin#221]
First, in admin server, i add dependency in pom
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-mail</artifactId>
</dependency>
```
and add properties
```
spring.mail.host=smtp.example.com
spring.boot.admin.notify.mail.to=me@example.com
```
but no mail to send to me, can i debug the code, i found in ```NotifierConfiguration``` class 
```
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(
      prefix = "spring.boot.admin.notify.mail",
      name = {"enabled"},
      matchIfMissing = true
    )
    @ConfigurationProperties("spring.boot.admin.notify.mail")
    public MailNotifier mailNotifier() {
      return new MailNotifier(this.mailSender);
    }
``` 
code have not run, any other configure i need to set or my configure is wrong?

**Comment by joshiste** [comment]
1. Which version are you using?
2. Please heck spring boot's autoconfiguration report and beans endpoint for a MailSender and MailNotifier bean. The latter requires the former to send mails
3. If both beans from 2 are present please check your mail server log.

Just to clarify: If the admin server itself goes down, it might not be able to send the notifications.

**Comment by joshiste** [comment]
P.s. I guess you have configured your own mail server and just copied the settings from the guide in your post...

**Comment by dragontree101** [comment]
spring-boot-start-admin version is 1.3.3 
i need to create MailSender bean by myself?

**Comment by dragontree101** [comment]
i debug sendmail, found  to is ```root@localhost``` and from is ```null```

but i have set 
```
spring:
  boot:
    admin:
      auto-deregistration: true
      notify:
        mail:
          from: xxxx@qq.com
          to: yyyy@qqq.com
```

**Comment by dragontree101** [comment]
i know ,  i use bootstart-xxx.yaml, i change to application-xxx.yaml is ok!

**Comment by joshiste** [comment]
> i debug spring boot's autoconfiguration, i found org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
not create JavaMailSenderImpl Bean, 

Then this is your problem and you need to fix it. When autoconfiguration doesn't work, you could instantiate the JavaMailSender yourself.
