### ISSUE TITLE
how can i config mail to send different people?

### ISSUE THREAD

**Issue by dragontree101** [codecentric/spring-boot-admin#222]
i hope admin server can send mail to different people record some config, 

i have two project App1 and App2, and i want to send mail to P1 when App1 is down and send mail to P2 when App2 is down, how can i config admin server?

i have read admin server code, ```MailNotifier``` object only can set one ```to``` var, so i am not sure can i solve this problem?

**Comment by joshiste** [comment]
`MailNotifier.setTo()` and `setCc()` both accepts a List of Strings. So you just need to write them comma separated, Spring should do the rest.

**Comment by dragontree101** [comment]
but i would send mail to different people when different project status to down.

i have two project App1 and App2, and i want to send mail to P1 when App1 is down and send mail to P2 when App2 is down, how can i config admin server? not both to send mail to P1 and P2

likes

                       admin-server
                        /               \
           admin-client-1       admin-client-2
                       |                         |
               people 1                  people 2

**Comment by joshiste** [comment]
Via configuration this is currently not possible. You need to implement your own Notifier.

**Comment by dragontree101** [comment]
ok, i see, thanks ,  i must implement my ```Notifier```  :(
