### ISSUE TITLE
how can i custom my notify？

### ISSUE THREAD

**Issue by dragontree101** [codecentric/spring-boot-admin#223]
spring-boot-admin will request admin-client by ```RegistryController```

i think admin can request admin-cilent's path like this ```/health```、```/metrics```、```/traces```

if request ```/metrics``` path, and response is
```
xxx_metrics: 200
yyy_metrics: 300
```

if ```xxx_metrics``` is more than i set threshold value ```150``` . i want to send mail to mysql, how can i custom myself notify event?

**Comment by joshiste** [comment]
SBA doesn't support notification for metric thresholds and I don't intend to implement this. But you can easily add your own code which polls the metric-endpoints and sends notifications.
