### ISSUE TITLE
On reset logging level send empty string instead of null

### ISSUE THREAD

**Issue by martintimko** [codecentric/spring-boot-admin#2236]
## Spring Boot Admin Server information

- **Version**:
1.5.7

- **Spring Boot version**:
2.7.8

## Description
Hi, I observed following problem: 
When my client's application(s) are using default Spring serializer (Jackson), resetting logging level in Spring Boot Admin UI works fine. However, in our project we are using `kotlinx.serialization`, which throws following exception when receiving reset logger request:
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 19: Expected string literal but 'null' literal was found at path: $['configuredLevel']
Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
JSON input: {"configuredLevel":null}
```
Suggested `coerceInputValues = true` config doesn't work, as there is no default value set for that field in related Spring Actuator class and I'm not able to find any workaround.

After manual test, I found that sending POST

```
{
  "configuredLevel": ""
}
```

to `/actuator/loggers/{LOGGER_NAME}` instead of 

```
{
  "configuredLevel": null
}
```
works perfectly fine, so I think it could be used instead, for better compatibility with various serialization libraries.

## Steps to reproduce:
Just add

`implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")` 

to the client application, spring automatically uses it to deserialize incoming web requests.

**Comment by erikpetzold** [comment]
Hi @martintimko, 
thanks for your suggestion, we will check it.

The official docs recommend sending an empty object: https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#loggers.clearing-level
