### ISSUE TITLE
Failed to startup admin server if Application.Builder does not contains healthURL

### ISSUE THREAD

**Issue by ouaibsky** [codecentric/spring-boot-admin#224]
Admin server stop if an application instance is missing some details:
Root cause is Assert.*
```java
    protected Application(Application.Builder builder) {
        Assert.hasText(builder.name, "name must not be empty!");
        Assert.hasText(builder.healthUrl, "healthUrl must not be empty!");
        Assert.notNull(builder.statusInfo, "statusInfo must not be null!");
        this.healthUrl = builder.healthUrl;
        this.managementUrl = builder.managementUrl;
        this.serviceUrl = builder.serviceUrl;
        this.name = builder.name;
        this.id = builder.id;
        this.statusInfo = builder.statusInfo;
    }
```

For some unknown cause (likely due to ongoing migration of spring-cloud (Angel -> Brixton) some of our microservice do not register anymore healthURL in eureka, but only securedHealthUrl is there.

Anyway, admin server should not stop if this data is missing, at worst just putting information saying this microservice will not be monitored by admin.

Christophe.

**Comment by joshiste** [comment]
Hey Christophe, which version are you using and can you please provide the stacktrace from the crash?

**Comment by joshiste** [comment]
Could you try the 1.3.4 version? The Exception should be caught - but the application is probably still missing so we have to fix this nonetheless.

**Comment by ouaibsky** [comment]
Hi
I tested with 1.3.3 and .4, same issue
Unfortunately I do no have a stacktrace 'cause I fixed my eureka clients to set both URLs as a quick workaround but remains sensible to new clients who do not do the same. 
I looked over commit f95f7a5 and it sounds good. Thx for that.
I'll test when new version will be available.

Christophe
