### ISSUE TITLE
Custom Ui is broken

### ISSUE THREAD

**Issue by georgerocha** [codecentric/spring-boot-admin#2255]
Hello! 

After testing on my application **extensively**, I decided to clone the project and try to test the custom ui provided in the samples module. It also **doesn´t** work. 

The provided sample doesn´t work, nothing I try with vue or simple html tags works. If I click any other link after clicking the 'Custom' tab nothing is working either, seems like opening it breaks the application.

As such, it looks like the ui extension feature is broken.
Tested for version 3.0.0

**Comment by ahoehma** [comment]
Any news here?

**Comment by Petlyuk-Vladimir** [comment]
I am interested too.

**Comment by SteKoe** [comment]
Hi, we are currently investigating why data binding is not working. We managed to fix the examples, showing the current registered applications.

**Comment by georgerocha** [comment]
Thank you. I really need this.

Em dom., 26 de fev. de 2023 16:08, Stephan Köninger <
***@***.***> escreveu:

**Comment by subhojit777** [comment]
I am interested in customizing the UI. I tried with the latest code and it is not working. I copied the sample-ui code and I am getting errors:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'addView')
Uncaught TypeError: Cannot read properties of undefined (reading 'mergeLocaleMessage')
```

and the wallboard, etc. is completely blank. Am I missing something?

**Comment by subhojit777** [comment]
Also the `npm run watch` command isn't working. Looks like the script is missing.

**Comment by subhojit777** [comment]
I was able to get the UI working by disabling the custom-ui changes as mentioned in the PR https://github.com/codecentric/spring-boot-admin/pull/2311
Now when I open the `custom` path, it is blank, but the top menu is appearing. I see console logs:

```
TypeError: SBA.useApplicationStore is not a function
```

I think the custom UI is missing some dependencies. JFYI I want to do the customizations on top of starter-server.

**Comment by SteKoe** [comment]
`SBA.useApplicationStore` is exposed since 3.0.2 (released yesterday). Please upgrade and retry using the latest version. Please find an example repo here: https://github.com/SteKoe/spring-boot-admin-example-custom-ui
