### ISSUE TITLE
E-mail to alert warning in VM

### ISSUE THREAD

**Issue by ofbizbrazil** [codecentric/spring-boot-admin#228]
It would be nice to have a feature to alert users via user e-mail about unwanted behaviors of Spring Boot app, VM, Heap, etc, etc...

**Comment by joshiste** [comment]
You could write a `HealthIndicator` for your application watching the heap usage or certain metrics. This has the advantage that you could define the thresholds individual for every application and works with the current spring boot admin, when the status goes down or the jvm becomes unresponsive.

**Comment by ofbizbrazil** [comment]
I guess if we had via screen user an option to set up this behavior, it would much easier than programming and having hard-coded.

**Comment by joshiste** [comment]
This is not an easy task and at the moment out of scope. But you could add such functionality in 1.4.0 as module...
