### ISSUE TITLE
SpringBootAdmin V 2.3.0 Rendering CSS on HTML So Behind Proxy Page is not loaded

### ISSUE THREAD

**Issue by sitamadhavi** [codecentric/spring-boot-admin#2287]
## Spring Boot Admin Server information

- **Version**:
 2.3.0

- **Spring Boot version**:
 2.3.9.RELEASE

- **Configured Security**:
None

- **Webflux or Servlet application**:
 Servlet

## Client information

- **Spring Boot versions**:
 2.1.4.RELEASE

- **Used discovery mechanism**:
Kubernetes

- **Webflux or Servlet application**:
 servlet

## Description
SpringBootAdmin UI from Browser making calls to CSS using Http.. so being blocked by Ingress which is only allowing https traffic. Please let us know the workaround.

**Comment by SteKoe** [comment]
Hi @sitamadhavi,

CSS and JS resources are loaded relative to the `baseUrl` which can be defined using the property `spring.boot.admin.ui.public-url`. You can see the current value in `<base>` tag of the HTML-Page. Please set the property (including https) to a value matching your environment.

![Bildschirm­foto 2023-02-18 um 10 58 07](https://user-images.githubusercontent.com/1809221/219854185-1953a9a5-913a-41a1-b731-b915a76706a5.png)

Regards
SteKoe

**Comment by sitamadhavi** [comment]
Thank you it worked. Appreciate for the response
