### ISSUE TITLE
Static content not found after enabling the admin server

### ISSUE THREAD

**Issue by pihlajus** [codecentric/spring-boot-admin#229]
For some reason my static content (js, css) is not found after I enable admin server. The same content is found if I don't enable admin server. Static content is located in resources -> static -> js/css folder. I'm using admin server version 1.3.3 and Spring Boot 1.3.3.RELEASE.

**Comment by joshiste** [comment]
This only works when you set `spring.boot.admin.context-path` to some value other than `/`. Otherwise Spring Boot Admins resource handler will be registered for `/**` and it's resources must reside in `META-INF/spring-boot-admin-server-ui`.

**Comment by pihlajus** [comment]
That was it, thanks.
