### ISSUE TITLE
Error to build url with a different management.port

### ISSUE THREAD

**Issue by ofbizbrazil** [codecentric/spring-boot-admin#230]
If we have a custom **management.port**, Spring Boot Admin should not append **server.context-path** to the that url.

For Example:
```
server.port=9151
server.context-path=/mailsender
management.port=9152

```
It should be only http://hostname:9152/ and not http://hostname:9152/mailsender as it is doing at the moment.

At the same time if I set management.context-path=/mailsender I am getting http://hostname:9152/mailsender/mailsender where in this case it should be only http://hostname:9152/mailsender

Spring Boot Admin Client is not leading fine when we have a management context in a different port of application.

See logs:

`2016-07-14 18:01:15,356 INFO  de.codecentric.boot.admin.services.ApplicationRegistrator - Application registered itself as {managementUrl=http://hostname:9152/mailsender, healthUrl=http://hostname:9152/mailsender/health, serviceUrl=http://hostname:9151/mailsender, name=mail-sender, id=23bb5e95, statusInfo={status=UNKNOWN, timestamp=1468530075227}}`

**Comment by ofbizbrazil** [comment]
In my case I will have a server.context-path but if I do not want to have it for management.port Spring Boot Admin should see it. The same was Spring Boot does, Spring Boot Admin should obey too. In my opinion this a several error.

**Comment by joshiste** [comment]
@ofbizbrazil in deed and it's fixed in the next version with ed00440 :grinning:

**Comment by ofbizbrazil** [comment]
Great, I saw the code fixing it.

Do you have any idea when the version **1.3.5** will be available to download?
Tks.

**Comment by joshiste** [comment]
@ofbizbrazil 1.3.5 is now available
