### ISSUE TITLE
v-for not working in custom ui

### ISSUE THREAD

**Issue by Tobisaninfo** [codecentric/spring-boot-admin#2304]
## Spring Boot Admin Server information

- **Version**:
3.0.0

- **Spring Boot version**:
3.0.3

- **Configured Security**:
basic auth

- **Webflux or Servlet application**:
sevlet

## Client information

- **Spring Boot versions**:
3.0.3

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
sevlet

## Description

I'm trying to use a custom ui for my own spring scheduling system. Therefor a create a custom ui node project and fetch the content from my custom actuator endpoint. After that, the scheduled jobs should be displayed in a table. Here is the problem, I could find any way to get a v-for to work with the current spring boot admin version. I'm using this custom ui for many years with spring boot admin 2.x.y without any problems. Now I have migrated all stuff to current dependency versions and Vue 3.

Below is a simple v-for construct, that doesn't work in the custom ui extension. I also tried the same snipped in a fresh standalone Vue 3 project and it worked just fine. (Tested on https://codesandbox.io/s/vue)

The snippet (for simplification, :key is missing, but should work anyway):

```vue
<template>
  <div v-for="i in [1, 2, 3, 4]">
    {{ i }}
  </div>
</template>

<script>

export default {
  props: {
    instance: {
      type: Object,
      required: true
    }
  }
}
</script>

<style>
</style>
```

The complete custom view is:
```vue
<template>
  <section class="section" :class="{ 'is-loading' : !hasLoaded }">
    <div v-if="error" class="message is-danger">
      <div class="message-body">
        <strong>
          <span v-text="$t('instances.scheduling.fetch_failed')"/>
        </strong>
        <p v-text="error.message"/>
      </div>
    </div>
    <div v-else-if="!hasData" class="message is-warning">
      <div class="message-body" v-text="$t('instances.scheduling.no_scheduledtasks')"/>
    </div>

    <div v-else>
      <h3 class="title" v-text="$t('instances.scheduling.data.title')"/>
      <table class="metrics table is-fullwidth">
        <thead>
          <tr>
            <th v-text="$t('instances.scheduling.data.name')"/>
            <th v-text="$t('instances.scheduling.data.cron')"/>
            <th v-text="$t('instances.scheduling.data.last_run')"/>
            <th v-text="$t('instances.scheduling.data.state')"/>
            <th v-text="$t('instances.scheduling.data.next')"/>
          </tr>
        </thead>
        <tbody>
          <tr v-for="task in items" :key="task.name">
            <td v-text="task.name"/>
            <td v-text="task.cron"/>
            <td v-text="task.lastRun"/>
            <td v-text="task.state"/>
            <td v-text="task.nextRun"/>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</template>

<script>

export default {
  props: {
    instance: {
      type: Object,
      required: true
    }
  },
  data: () => ({
    hasLoaded: false,
    error: '',
    items: []
  }),
  computed: {
    hasData: function () {
      return this.items;
    }
  },
  async created() {
    try {
      const response = await this.instance.axios.get('actuator/scheduling');
      this.items = response.data;
    } catch (error) {
      console.warn('Fetching scheduled tasks failed:', error);
      this.error = error;
    }
    this.hasLoaded = true;
  }
}
</script>

<style>
</style>
```

And the response from the actuator endpoint:
```json
[
  {
    "name": "AppUserResetTokenCleanupTask",
    "cron": "0 0 * * * *",
    "lastRun": null,
    "nextRun": "2023-02-26T21:00:00",
    "state": "NOT_EXECUTED"
  }
]
```

The custom endpoint is registered as following:

```js
import schedulingEndpoint from './scheduling-endpoint';

SBA.use({
    install({viewRegistry}) {
        viewRegistry.addView({
            name: 'instances/scheduling',
            parent: 'instances',
            path: 'scheduling',
            component: schedulingEndpoint,
            label: 'Scheduling',
            group: 'scheduling',
            order: 1000,
            isEnabled: ({instance}) => instance.hasEndpoint('scheduling')
        });
    },
});
```

I have no console output in the browser that shows any hint for an error. I hope I have given enough information to reproduced this behaviour.

**Comment by Petlyuk-Vladimir** [comment]
I experience same issue too.

**Comment by pierrepinon** [comment]
Same issue for me

**Comment by Tobisaninfo** [comment]
Unfortunately this error occurs still in SBA 3.0.1 (with spring boot 3.0.3), even after spending a lot of time to migrate my custom ui to the new vite setup. With this setup, the errors even get worse, now in the built application, the global vue not exists anymore (`TypeError: undefined is not an object (evaluating 'vue.openBlock')`). 

I also try to copy your [samples](https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui) to get these to work in my setup and got also a bunch of errors like: `TypeError: SBA.useApplicationStore is not a function. (In 'SBA.useApplicationStore()', 'SBA.useApplicationStore' is undefined)`from the custom sub view or som registration issues from the `index.js`. It seems like something general is wrong. 

I used the given package.json and vite.config.js from your samples in combination with your chosen node and npm version from the pom.xml.
