### ISSUE TITLE
HttpExchanges not available in 3.0.0

### ISSUE THREAD

**Issue by tskramp** [codecentric/spring-boot-admin#2307]
## Spring Boot Admin Server information

- **Version**:
 3.0.0

- **Spring Boot version**:
3.0.2

- **Configured Security**:
n/a

- **Webflux or Servlet application**:
 webflux

## Client information

- **Spring Boot versions**:
3.0.2

- **Used discovery mechanism**:
  

- **Webflux or Servlet application**:
  

## Description

** Bug report **
HttpExchanges are not showing up in spring boot admin. I can manually get the exchanges endpoint, but cannot view it through the app.

![sba-httpexchange](https://user-images.githubusercontent.com/112283261/221859914-abf0a675-f8ff-4bd9-9e3f-aa002d8358b2.png)

**Comment by erikpetzold** [comment]
Hi, @tskramp,
this should have been added, see #2185
we will have a look

**Comment by tskramp** [comment]
Hey @erikpetzold  I think I figured out the reason this is happening, no idea how to fix it. But I recently switched my management port to `8081` rather than `8080`, I had one service that I hadn't done that to, and it displayed the `Web` tab, but as soon as I switched it over to port `8081` it went away

**Comment by SteKoe** [comment]
I close this issue as it seems to be resolved.

**Comment by tskramp** [comment]
@SteKoe this is actually not resolved. It still does not work when using port 8081. Everything else in SBA works normally on 8081 except for the HttpExchanges
