### ISSUE TITLE
client main actuator does not get picked up in custom path, health does

### ISSUE THREAD

**Issue by andmer** [codecentric/spring-boot-admin#2308]
## Spring Boot Admin Server information

- **Version**:
2.7.10

- **Spring Boot version**:
2.7.9

- **Configured Security**:
none

- **Webflux or Servlet application**:
servlet

## Client information

- **Spring Boot versions**:
2.7.9

- **Used discovery mechanism**:
eureka

- **Webflux or Servlet application**:
servlet

## Description

client is not fully registering correctly
```
management:
  info:
    git:
      mode: "full"
  server:
    base-path: /symbol
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always

server:
  port: 0
  error:
    include-stacktrace: never
  servlet:
    context-path: /symbol
```

health actuator picks up custom path, but main actuator does not:

![image](https://user-images.githubusercontent.com/74022244/222459374-3fe04d3e-a18b-4bf3-a993-07cd906576e1.png)

**Comment by erikpetzold** [comment]
hi @andmer ,

when using `management.server.base-path` you also have define a separate port for actuator, see the docs of this property:

> Management endpoint base path (for instance, '/management'). **Requires a custom management.server.port.**
