### ISSUE TITLE
Spring boot admin 3.0.2 Start sequence

### ISSUE THREAD

**Issue by MorganArthur** [codecentric/spring-boot-admin#2329]
** Question **
Spring boot admin 3.0.2 integrates the nacos. Start the spring boot admin first. When starting the application service, the spring boot admin cannot find the service. Start the application service first and then start the spring boot admin can only.
Configuration is the simplest configuration. There are no additional configuration parameters. Whether the configuration is missing or the operation is incorrect.

** version **
spring boot : 3.0.4
spring boot admin : 3.0.1
spring cloud : 2022.0.1
spring cloud alibaba : 2022.0.0.0-RC1

 
![image](https://user-images.githubusercontent.com/24489342/225175209-a208e540-e1d4-44e8-93c7-c3b2be75033d.png)

**Comment by erikpetzold** [comment]
closing duplicate, will be analyzed in existing issue

**Comment by ulischulte** [comment]
@MorganArthur ,

have you tried setting `spring.cloud.nacos.discovery.watch.enabled` to `true`? The default used to be true, but now it's false.

Have you added `@EnableScheduling` to the main Application class of your Spring Boot Admin implementation?

Regards
Uli

**Comment by karl-chanel** [comment]
@ulischulte   I tried what you said,It's still not working.
