### ISSUE TITLE
Instance id in spring boot admin is same for 2 services

### ISSUE THREAD

**Issue by adsinghnet** [codecentric/spring-boot-admin#2345]
## Spring Boot Admin Server information

- **Version**: 2.2.4
  

- **Spring Boot version**: 2.3.1
  

- **Configured Security**:
  

- **Webflux or Servlet application**:
  

## Client information

- **Spring Boot versions**: 2.3.1
  

- **Used discovery mechanism**: self registration
  

- **Webflux or Servlet application**:
  

## Description

I have 2 replica of a single spring boot services with same service url and context path and they are running on 2 different pods and i have registered both the services to spring boot admin ui but there instance id is same, due to this I am not able to change logs as it is causing issues with communication between the Spring Boot Admin Server and the instances.

**Comment by erikpetzold** [comment]
Hi @adsinghnet 

the instanceId is generated as a hash of the healthUrl (which is provided with the registration)

If you have 2 instances, of course they need a different url, so both can be monitored independently. If you provide the correct url to Spring Boot Admin, then both instances get a different ID and can be managed independently.

**Comment by adsinghnet** [comment]
Thanks @erikpetzold  for looking into this, 
I cant change the url as other services are also using that, So I created a customImpl of InstanceIdGenerator --> generateId:

```
public class CustomHashingInstanceUrlIdGenerator implements InstanceIdGenerator {

public InstanceId generateId(Registration registration) {
        try {

            MessageDigest digest = MessageDigest.getInstance("SHA-1");
            byte[] bytes;
            if (registration.getMetadata().get("instance-id") == null || registration.getMetadata().get("instance-id").isBlank()) {
               
                bytes = digest.digest(registration.getName().getBytes(StandardCharsets.UTF_8));
            } else {
                
                bytes = digest.digest(registration.getMetadata().get("instance-id").getBytes(StandardCharsets.UTF_8));
            }

            return InstanceId.of(new String(encodeHex(bytes, 0, 12)));
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException(ex);
        }
    }

   }
```

**Comment by erikpetzold** [comment]
But if you have 2 instances, how should Spring Boot admin check the health of each instance if both share the same url? What if one of them goes down and the other one is still running? This would not be visible I guess.

You need to do the monitoring on pod level, not on service level.

**Comment by adsinghnet** [comment]
@erikpetzold  So, can you suggest me something how can I do that,
I was thinking I might use spring-boot-admin-server-cloud 
can you suggest me...

**Comment by adsinghnet** [comment]
Will look into this a bit more,
Thanks for the suggestions @erikpetzold

**Comment by erikpetzold** [comment]
The best solution would be to use the discovery mechanism for kubernetes instead of self registration
