### ISSUE TITLE
HttpExchanges does not display when management server running on port 8081

### ISSUE THREAD

**Issue by tskramp** [codecentric/spring-boot-admin#2350]
## Spring Boot Admin Server information

- **Version**:
 3.0.1

- **Spring Boot version**:
3.0.2

- **Configured Security**:
n/a

- **Webflux or Servlet application**:
 webflux

## Client information

- **Spring Boot versions**:
3.0.2

- **Used discovery mechanism**:
  self-registration

## Description

** Bug report **
HttpExchanges are not showing up in spring boot admin. I can manually get the exchanges endpoint, but cannot view it through the app. This happens when the management server is set to run on port 8081, rather than the default port 8080. Every other actuator endpoint works as expected with SBA when running on 8081 except the exchanges.
```
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8081
```
![sba-httpexchange](https://user-images.githubusercontent.com/112283261/221859914-abf0a675-f8ff-4bd9-9e3f-aa002d8358b2.png)

**Comment by ulischulte** [comment]
Hi @tskramp,

I wasn't able to reproduce your bug. I made a sample application with your configuration (management server port 8081, server port 8080 + given versions above) and everything looks fine. You will find it here: https://github.com/ulischulte/spring-boot-admin-examples/tree/main/hello-spring-boot-admin-3-httpexchange

![image](https://user-images.githubusercontent.com/16336547/227167489-f4e83a8b-48c0-4ef5-98e0-b1272c6c72af.png)


Does the example solve your problem?

Regards
Uli

**Comment by ulischulte** [comment]
Closed due to missing feedback
