### ISSUE TITLE
Log button should open a tail-ed log and refresh a configurable amount of time

### ISSUE THREAD

**Issue by Antauri** [codecentric/spring-boot-admin#237]
The UI is awesome. We use it to monitor all our micro-service instances. However, sometimes we want to look at individual logs of individual instances. Clickin on the log button, outputs a new tab which requires us to scroll-down to the end of the page. And if we need to refresh, we hit refresh and scroll-down again. And so on and so forth.

A (modal) log viewer that tails the URL of the log should be very simple to make. Upon clicking the Log button it pops-up the log and tails the last N lines and refresh every R seconds. A "view full log" options should also be allowed that keeps the current functionality to view the entire log.

Could it be done for 1.3.5?

**Comment by tjuchniewicz** [comment]
Tail would be great. We don't use Log at all because we have very large log files difficult to view through the browser.

**Comment by joshiste** [comment]
ui enhancements will be only implemented in 1.4.x

**Comment by Antauri** [comment]
Scheduled for 1.4.1? :D

**Comment by joshiste** [comment]
@Antauri currently not. But a PR is always welcome.
I don't use the logfile endpoint in our production env anymore, so for myself this isn't at the top of the wishlist....
