### ISSUE TITLE
Spring Boot Admin Inability to perceive service online and offline

### ISSUE THREAD

**Issue by zhangbinhub** [codecentric/spring-boot-admin#2390]
Environment:
Spring Boot 3.0.5
Spring Cloud 2022.0.2
Spring Cloud Alibaba 2022.0.0.0-RC1
Nacos 2.2.1

Spring Boot Admin 3.0.2

1.Start SBA first, then start other services, but the webpage always shows only SBA itself
![image](https://user-images.githubusercontent.com/32190984/231212116-da5a1740-11b1-4ec5-b332-9ea8f8799aca.png)
![image](https://user-images.githubusercontent.com/32190984/231212271-107bca74-2710-418c-8170-a19f26ccbcda.png)

2.Start other services first, then start SBA, and the registered services will be displayed correctly on the webpage
![image](https://user-images.githubusercontent.com/32190984/231213309-63ae6055-6727-4046-ac62-abe0e465a523.png)

3.Stop other services based on the second step, and the webpage will only display offline and will not remove the service from the list
![image](https://user-images.githubusercontent.com/32190984/231213794-1c36637e-fa0c-47e0-814d-ef24a8db0b90.png)

**Comment by zhangbinhub** [comment]
Occasionally, the following warning logs may appear in SBA
`2023-04-11T23:29:55.422+08:00  WARN 20832 --- [  XNIO-1 task-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: No acceptable representation]`

**Comment by karl-chanel** [comment]
is there any update on this ,i trie sba 3.0.3 ,problem still exists

**Comment by zhangbinhub** [comment]
Environment:
Spring Boot 3.0.6
Spring Cloud 2022.0.2
Spring Cloud Alibaba 2022.0.0.0-RC2

Spring Boot Admin 3.0.3

After upgrading the sba and dependency version, this problem still exists.

**Comment by karl-chanel** [comment]
i did a test,sba only works fine with spring cloud alibaba 2021.04  ,2021.05 and 2022 above have the same problem,and from 2021.04 to 2021.05 they refactored the nacos watch (i think thats the cause),but when i set nacos watch to true ,it doesnt fix the problem

**Comment by karl-chanel** [comment]
solved it https://github.com/alibaba/spring-cloud-alibaba/issues/3258#issue-1659872701

**Comment by zhangbinhub** [comment]
this problem is nacos
see https://github.com/alibaba/spring-cloud-alibaba/issues/3258
