### ISSUE TITLE
How to add tags when deploying SBA with K8 discovery client 

### ISSUE THREAD

**Issue by scipionyx** [codecentric/spring-boot-admin#2395]
Hey All

Love SBA! Great job and thanks!

How to add tags when deploying SBA with K8 discovery client (I'm not using SBA client)

**Comment by andreasfritz** [comment]
Do you mean tags, that show up in Spring Boot Admin?
Or tags to filter the service discovery?

These two are part of an unfinished K8 SBA example:
https://github.com/andreasfritz/spring-boot-admin-kubernetes-example

1. https://github.com/andreasfritz/spring-boot-admin-kubernetes-example/blob/main/hello-world/src/main/resources/application.yml
  tags:
    spring-boot: "@pom.parent.version@"
2. https://github.com/andreasfritz/spring-boot-admin-kubernetes-example/blob/main/hello-world/deployment/templates/service.yaml
  annotations:
    spring-boot-admin: "true"
