### ISSUE TITLE
Integrate Hystrix Dashboard into the Spring Boot Admin Server

### ISSUE THREAD

**Issue by mrumpf** [codecentric/spring-boot-admin#241]
The following page contains some info about how to integrate the Hystrix Dashboard view into existing applications:
https://github.com/Netflix/Hystrix/wiki/Dashboard#customizing-and-embedding

It would be great if Spring Boot Admin would automatically show a tab for Hystrix, when the endpoint /hystrix.stream is available for a Spring Boot application.
See https://github.com/VanRoy/spring-cloud-dashboard#circuit-breaker

**Comment by cforce** [comment]
duplicate of https://github.com/codecentric/spring-boot-admin/issues/147 ?

**Comment by joshiste** [comment]
you're right. Didn't spot it.
closing due to duplication of #147
