### ISSUE TITLE
GUI Authentication

### ISSUE THREAD

**Issue by berinle** [codecentric/spring-boot-admin#242]
It would be nice if there was a way to turn on authentication for the spring admin server GUI out of the box.

BTW, Nice work!

**Comment by joshiste** [comment]
Authentication is a broad field and everyone is approaching differently, so I don't tend to include it in the admin server itself.
Setting up authentication isn't that hard. I've setup some samples for that: https://github.com/joshiste/spring-boot-admin-samples

**Comment by berinle** [comment]
Cool! You are right. I missed that in the samples. Thanks for the prompt response!
