### ISSUE TITLE
Misleading docs about background image

### ISSUE THREAD

**Issue by genuss** [codecentric/spring-boot-admin#2428]
## Spring Boot Admin Server information

- **Version**: 3.0.x

- **Spring Boot version**: 3.0x

## Description

I looked for a property to disable background image appeared in 3.0 and found documentation about [spring.boot.admin.ui.theme.background.enable](https://github.com/codecentric/spring-boot-admin/blob/0e97cb3ca353f5506f07e1e97759c6c14e78336b/spring-boot-admin-docs/src/site/asciidoc/customize_ui.adoc#customizing-colors), but it doesn't work and I couldn't find anything related to it in code.
Was it ever implemented? And if not, what's the intended behaviour: add property, or fix documentation?

**Comment by SteKoe** [comment]
Hi @genuss,

thanks for pointing this out! I have just pushed a change that fixes this behavior. The property is renamed to `spring.boot.admin.ui.theme.background-enabled` and will be respected in an upcoming release. 

Regards,
Stephan

**Comment by genuss** [comment]
Than you, @SteKoe ! I've checked your branch and it works like a charm. Looking forward for the new release 👍
