### ISSUE TITLE
instance IP error

### ISSUE THREAD

**Issue by HuMan008** [codecentric/spring-boot-admin#2439]
你好，我遇到了一个问题；
SBA_Server 版本为2.6.11 
SBA_CLIENT使用了NACOS的服务发现
部署在K8S环境中；
启动SBA_SERVICE 一切正常，启动某个服务A，在SBA里能正常的看到服务A是正常的；
重启服务A后，发现ip地址还是以前的IP
![image](https://user-images.githubusercontent.com/41569330/236420176-885f5eb0-b01e-4847-aef5-6fce03ad2f3c.png)
然后我通过curl 127.0.0.1:9107/actuator/nacosdiscovery   （在服务A的容器中）
{"subscribe":[{"name":"paas-rnc","groupName":"DEFAULT_GROUP","clusters":"DEFAULT","cacheMillis":1000,"hosts":[{"ip":"10.100.1.11","port":9107,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@paas-rnc","metadata":{"preserved.register.source":"SPRING_CLOUD"},"ipDeleteTimeout":30000,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000}],"lastRefTime":0,"checksum":"","allIPs":false,"reachProtectionThreshold":false,"valid":true}],"NacosDiscoveryProperties":{"serverAddr":"AOS-NACOS:8848","username":"","password":"","endpoint":"","namespace":"","watchDelay":30000,"logName":"","service":"paas-rnc","weight":1.0,"clusterName":"DEFAULT","group":"DEFAULT_GROUP","namingLoadCacheAtStart":"false","metadata":{"IPv6":null,"preserved.register.source":"SPRING_CLOUD"},"registerEnabled":true,"ip":"10.100.1.11","networkInterface":"","ipType":null,"port":9107,"secure":false,"accessKey":"","secretKey":"","heartBeatInterval":null,"heartBeatTimeout":null,"ipDeleteTimeout":null,"instanceEnabled":true,"ephemeral":true,"failureToleranceEnabled":false,"failFast":true,"nacosProperties":{"secretKey":"","com.alibaba.nacos.naming.log.filename":"","enabled":"true","watch.enabled":"true","password":"","endpoint":"","serverAddr":"AOS-NACOS:8848","accessKey":"","clusterName":"DEFAULT","namespace":"","namingLoadCacheAtStart":"false","username":""}}}
在SBA_SERVER的容器中，我请求 curl  curl 10.100.1.11:9107/actuator/health 可以得到UP的状态
请问，如何才能使SBA_SERVER的状态变成正常状态；

**Comment by erikpetzold** [comment]
@HuMan008 can you please translate your request to english (or german :D ).
Also the title says "error", but the label says "enahncement". For bugs please use the provided issue template.
