### ISSUE TITLE
Discovery client deregisters HTTP registered applications

### ISSUE THREAD

**Issue by urgelacko** [codecentric/spring-boot-admin#244]
I have an admin application which uses Eureka for some services and some services are not in Eureka so those are registering with spring-boot-admin-client.
After upgrading 1.3.4 I have realized a thing when the discovery client refresh removes the http registered ones because they are missing from Eureka. Just after this the application re-registers itself with HTTP and it is visible in the dashboard again.
This is quite annoying because generates a lot of noise in the logs and if admin is opened from chrome 2 notifications are popping up immediately, one for de-registration and one for re-registration 

I have attached a screenshot of the log messages here: ![admin.log](https://cloud.githubusercontent.com/assets/2915827/17409328/20f2a3ba-5a6f-11e6-8219-b8256c94a70a.PNG)

Do you have any idea how to resolve this?

**Comment by joshiste** [comment]
As a workaround you should bring your own implementation of the `ApplicationDiscoveryListener` which doesn't  remove the stale applications.
I didn't expected to see people using  two different registration mechanisms at the same time.
As a long term fix we can modifiy the stale detection to also respect the ignoredServices. This would you allow to add those services which registers via http to the ignored services and they won't get removed.

**Comment by urgelacko** [comment]
That was quick :smile: 
Your app is awesome it helps me a lot. So thank you for your great work and keep up the good spirit :wink:
