### ISSUE TITLE
CSRF exclude missing for /applications/** in Docs

### ISSUE THREAD

**Issue by MahatmaFatalError** [codecentric/spring-boot-admin#2441]
## Spring Boot Admin Server information

- **Version**:
  3.0.3

- **Spring Boot version**:
  3.0.6

- **Configured Security**:
  based on example on http://docs.spring-boot-admin.com/current/security.html

- **Webflux or Servlet application**:
  Servlet

## Client information

- **Spring Boot versions**:
  2.7

- **Used discovery mechanism**:
  Kubernetes

- **Webflux or Servlet application**:
  Servlet

## Description

I think there is a "bug" or at least something missing in the docs of http://docs.spring-boot-admin.com/current/security.html.
In order to get switching log levels to work, I needed to change
```
new AntPathRequestMatcher(this.adminServer.getContextPath() + "/instances/**", HttpMethod.POST.toString()),
new AntPathRequestMatcher(this.adminServer.getContextPath() + "/applications/**", HttpMethod.POST.toString()),
```
otherwise the browser received a 403 from the server.

Especially `applications` is not mentioned at all, but is required for switching log levels on application level for multiple pod instances.

**Comment by SteKoe** [comment]
Hi @MahatmaFatalError,

we have rechecked the CSRF behavior in our Servlet example you are referring to and don’t see any problem here. The XSRF token is read from the Cookie as shown in the screenshot below. 

Hence, an example project that reproduces your issue would be helpful to see why the CSRF protection breaks in your setup.

TIA,
SteKoe

![xsrf-token-in-cookie](https://github.com/codecentric/spring-boot-admin/assets/1809221/14bfcf8b-686e-4927-8c11-b2984dfbef0c)

**Comment by MahatmaFatalError** [comment]
Hi @SteKoe Thanks for the response. I don't have a public example at hand, but I can say that there is no XSRF-TOKEN sent in the request header. Checked with Chrome and Firefox.

**Comment by ulischulte** [comment]
Hi @MahatmaFatalError,
could you please at least show us your security filter chain configuration, so that we can check wether there's something wrong regarding CSRF token request handling? As mentioned above - there's a running sample within Spring Boot Admin's codebase (https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet) which uses the exact same configuration you mentioned from the docs.
Regards,
Uli

**Comment by cachescrubber** [comment]
I had the exact same issue. Double checking my config after reading this issue, I think I was missing the `CsrfTokenRequestAttributeHandler`:

`            .csrfTokenRequestHandler(new CsrfTokenRequestAttributeHandler())
`

**Comment by ulischulte** [comment]
We're closing this issue due to missing feedback.

Regards,
Uli
