### ISSUE TITLE
When viewing log files scroll to the very bottom, the down button does not gray out

### ISSUE THREAD

**Issue by chenzl123** [codecentric/spring-boot-admin#2465]
When viewing log files scroll to the very bottom, the down button does not gray out
![image](https://github.com/codecentric/spring-boot-admin/assets/28611508/b84d719f-c9f6-49c6-a4ad-4477265d4060)
![image](https://github.com/codecentric/spring-boot-admin/assets/28611508/73aae72f-69e0-4e46-a4fa-2c855cfa784c)
Their difference is less than 1

**Comment by ulischulte** [comment]
Hi @chenzl123,

I'm not able to reproduce the bug in the current version. I'm pretty sure this has already been fixed within the last version (#2436). Can you please recheck with SBA version 3.0.4?

Regards,
Uli

**Comment by chenzl123** [comment]
yes 3.0.4

**Comment by chenzl123** [comment]
https://github.com/codecentric/spring-boot-admin/assets/28611508/0aed7f9b-7696-4c4d-bee0-fa0699766304

**Comment by chenzl123** [comment]
The scroll bar is at the bottom, change the window to hit, that button is going to change

**Comment by SteKoe** [comment]
Hi @chenzl123,

thanks for providing the video. Even though we were able to reproduce the issue, we think that this is a edge case and hence won’t fix it. Anyways, feel free to provide a PR anytime.

Regards
SteKoe
