### ISSUE TITLE
Which version use

### ISSUE THREAD

**Issue by lduparc** [codecentric/spring-boot-admin#249]
I'm currently using Spring Boot 1.3.5 with Spring Cloud Brixton.RELEASE.

Which version of spring boot admin is compatible with this version of Spring Boot and Spring Cloud ?

Where find version compatibilities ?

**Comment by tjuchniewicz** [comment]
I use SBA 1.3.6 with Brixton.SR4. 
For Brixton.RELEASE use SBA 1.3.3.

**Comment by lduparc** [comment]
Is SBA 1.4.1 support spring boot 1.3.5 with Brixton.SR4 or is only for Spring boot 1.4.X ?

**Comment by tjuchniewicz** [comment]
I can't make SBA 1.4.0 work with Brixton.SR4. I'm experiencing class not
found issues. But I use non default pom hierarchy.

**Comment by lduparc** [comment]
It's working using SBA 1.4.1 and Brixton.SR4/Springboot 1.4.0.

What is the new column use for on the left ?

<img width="60" alt="capture d ecran 2016-08-17 a 9 54 53 pm" src="https://cloud.githubusercontent.com/assets/790935/17751057/aad0ba76-64c5-11e6-9f70-e0e4796df789.png">

**Comment by lduparc** [comment]
OK it's for multiple instances !

**Comment by joshiste** [comment]
SBA 1.3.x. is for spring boot 1.3.x  and 1.4.x for spring boot 1.4.x. Currently there is no compatibility matrix. Please use the pom.xml or release notes to figure out which version to use.
I've to little time to test for multiple supported boot or cloud versions.
