### ISSUE TITLE
Actuator endpoints secured by oAuth

### ISSUE THREAD

**Issue by narup** [codecentric/spring-boot-admin#250]
Hello Team, I am trying to use spring-boot-admin for our API server but all my actuator endpoints are secured by oAuth with management-path /management/**. Is there a plan to support this use case? There's some complications mixing oAuth and http basic auth for API endpoints vs actuator endpoints with spring boot, so for simplicity I am securing all types of endpoint with oAuth.
Let me know if this is something that should be supported in this project.

Thanks

**Comment by joshiste** [comment]
Please see the samples here for OAuth authentication: https://github.com/joshiste/spring-boot-admin-samples
