### ISSUE TITLE
logfile 

### ISSUE THREAD

**Issue by doubleDimple** [codecentric/spring-boot-admin#2513]
When I use springboot admin to view the log of the client service, I found that the request will be executed once per second. Is there any configuration to modify the request time? For example, I want to refresh the client log every 10 seconds.
![image](https://github.com/codecentric/spring-boot-admin/assets/96671314/512d539d-b977-4625-bed5-1d0ac0c399a1)
springboot admin version: 2.3.1
springboot version:2.3.12.RELEASE

**Comment by doubleDimple** [comment]
When I use springboot admin to view the log of the client service, I found that the request will be executed once per second. Is there any configuration to modify the request time? For example, I want to refresh the client log every 10 seconds.
![image](https://github.com/codecentric/spring-boot-admin/assets/96671314/512d539d-b977-4625-bed5-1d0ac0c399a1)
springboot admin version: 2.3.1
springboot version:2.3.12.RELEASE
![image](https://github.com/codecentric/spring-boot-admin/assets/96671314/26db2314-a63a-41cb-8de5-3674fbc4ffb3)

**Comment by erikpetzold** [comment]
Hi @doubleDimple, this is currently not configurable. 

We think about introducing a new property, but has no high priority.

Currently this is hard coded in spring-boot-admin-server-ui/src/main/frontend/views/instances/logfile/index.vue
`.streamLogfile(1000)`

**Comment by hzpz** [comment]
Use `spring.boot.admin.ui.poll-timer.logfile` to configure the polling duration in ms to fetch new logfile data.
