### ISSUE TITLE
Register instance programmatically

### ISSUE THREAD

**Issue by FabioAng71** [codecentric/spring-boot-admin#2514]
I embedded spring-boot-admin into my application and it works fine but I cannot register an instance programmatically.

```
@Component
public class MyCommandLineRunner implements CommandLineRunner {

    @Autowired
    private InstanceRegistry instanceRegistry;

    @Override
    public void run(String... args) throws Exception {

        Registration registration = Registration.builder()
                .name("test")
                .serviceUrl("http://localhost:4092")
                .healthUrl("http://localhost/actuator/health")
                .managementUrl("localhost:4092/actuator")
                .build();

        instanceRegistry.register(registration);
    }
}
```
no errors, but I dont see the instance in the web console and if I follow the code with the debugger it is not registered.

**Comment by erikpetzold** [comment]
Hi @FabioAng71 

you say you tried to debug the registrtion, but it is not registered.

Does that mean your `run()` method in the CommandlineRunner is not executed? Or is it executed but `instanceRegistry.register(registration);` does not do what you expect?

**Comment by erikpetzold** [comment]
closed due to inactivity
