### ISSUE TITLE
management.context-path with management.port

### ISSUE THREAD

**Issue by rhosman** [codecentric/spring-boot-admin#252]
When Spring Boot has a management.context-path and a management.port set it ignores the server.context-path property and makes the management endpoint  available at a URL using the following pattern http://${hostname}:${management.port}/${management.context-path}.  When the management.port is not set it uses http://${hostname}:${server.port}/${server.context-path}/${management.context-path}

Spring Boot Admin uses the second format in boot cases.  You can override this and get it to work by setting spring.boot.admin.management-url property but it seems like something that could easily just work by following the same behavior that Spring Boot already uses.

See this Spring Boot issue for more details on it's behavior in this situation [https://github.com/spring-projects/spring-boot/issues/4401](https://github.com/spring-projects/spring-boot/issues/4401)

**Comment by joshiste** [comment]
What version are you using? This should have been fixed with #230. I guess this is a duplicate of it or a regression?

**Comment by rhosman** [comment]
You are exactly right.  I was on 1.3.4 and when I upgraded to the current version (1.4.1) it worked as expected.  Sorry about the duplication.
