### ISSUE TITLE
Admin UI -> Web -> Mappings - not support  RouterFunction  router

### ISSUE THREAD

**Issue by fobgochod** [codecentric/spring-boot-admin#2525]
## Spring Boot Admin Server information

- **Version**: 
3.0.4

- **Spring Boot version**:
3.1.0

- **Configured Security**:
insecure

- **Webflux or Servlet application**:
Servlet

## Client information

- **Spring Boot versions**:
3.1.0

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
Webflux

## Description

write a api by RouterFunctionDsl
```
    @Bean
    fun routeDsl() = router {
        GET("/") {
            accept(MediaType.APPLICATION_JSON)
            ServerResponse.ok().bodyValue(buildProperties)
        }
    }
```

Spring Boot Admin UI -> Web -> Mappings :  page blank
![image](https://github.com/codecentric/spring-boot-admin/assets/13817644/6d70f1af-7f62-4e06-98ee-8057e6523364)

Client Actuator: /actuator/mappings  : may caused by different `details` property

![image](https://github.com/codecentric/spring-boot-admin/assets/13817644/e170f493-3176-42fd-93c9-60c6e80fa006)

**Comment by SteKoe** [comment]
Fix will be included in upcoming version :)
