### ISSUE TITLE
Spring Admin Server behind VPC

### ISSUE THREAD

**Issue by berinle** [codecentric/spring-boot-admin#258]
Hi, 
I'm attempting to setup the admin server within a VPC. I have the admin server and a sample app which attempts to connect to it launched in the same VPC and private subnet. However, the status of the app according to admin server is always "offline", despite the fact the app is up and running. If I launch the app in a public subnet in the same VPC, admin server has no issues and the app status is reported correctly.

Can you please advice? Is this an expected behavior? Why would it not connect to an app launched in the same VPC and private subnet?

I've gone through the docs, but nothing mentions this type of typology.

Cheers

**Comment by joshiste** [comment]
The client application tells the admin server it's health url during registration. Afterwards the admin server polls this endpoint to determine liveness. So the registered health-url needs to be reachable from the admin server.
The admin client tries to guess the url where it is reachable. I guess in your case the url is wrong and the server can't access the client's health endpoint. 
Either you have to set the client's url correclty via properties or ensure that the url is reachable from the admin server.
