### ISSUE TITLE
Ability to configure a menu label icon for SBA UI extension

### ISSUE THREAD

**Issue by konstantinMinkov** [codecentric/spring-boot-admin#2589]
I've been working on a UI extension and didn't find any way to configure an icon for it. It's not a big problem, but label looks a little bit out of place in the side menu (see `Extension 1` on the screenshot):

![image](https://github.com/codecentric/spring-boot-admin/assets/13005664/9e816163-2e17-4c88-b715-de8adff1b398)

After some source code investigation, I discovered that menu icons are configured via static map: https://github.com/codecentric/spring-boot-admin/blob/e4d7cc830a5c6ac80170669f2ad4600cac6d92f3/spring-boot-admin-server-ui/src/main/frontend/views/index.ts#L39-L53

So it doesn't look like there is a way to extend it.

It would be nice to have an ability to provide an icon in SBA extension config.

My suggestion is to be able able to either provide it as a full html string:

```javascript
SBA.use({
  install({viewRegistry}) {
    viewRegistry.addView({
      ...
      icon: '<svg xmlns="http://www.w3.org/2000/svg" class="h-5  mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path></svg>'
    });
  }
});
```

Or just an svg path for more safety and control on the SBA side:

```javascript
SBA.use({
  install({viewRegistry}) {
    viewRegistry.addView({
      ...
      icon: 'M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z'
    });
  }
});
```

Please let me know if you need more details.

**Comment by SteKoe** [comment]
Hi @konstantinMinkov,

we have implemented the feature you requested. Beginning from next release it will be possible to set or override group icons by using the new function `SBA.viewRegistry.setGroupIcon(name: string, icon: string)` as shown [here](https://github.com/codecentric/spring-boot-admin/blob/51aa1071cf78c58244f37b5ddf1d2920c865722a/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui/src/index.js#L84).

We decided to not add an `icon` property to a view, but groups in general. Hence, you have to set the `group` property of your views and then set an icon for the group using the function mentioned above.
If you do not want to set a specific group name, you can also override the icon for the default group called `none`. 

Regards
SteKoe
