### ISSUE TITLE
Publish storybook

### ISSUE THREAD

**Issue by LaSylv** [codecentric/spring-boot-admin#2591]
I saw that there is a storybook job to get information about vue components available. It's super nice when developing custom ui, however, could it be possible to publish it ?

It would be nice to have access to it without having to run the project locally

**Comment by ulischulte** [comment]
Hi @LaSylv,

storybook is used internally to help us develop UI components.
We won't provide a UI library for Spring Boot Admin, thus we won't publish storybook. Still, you can easily just use the npm script `npm run storybook` to use storybook locally if it helps you to develop your custom UI.

Regards,
Uli
