### ISSUE TITLE
[SBA3 UI] Spinner is not shown on page loading

### ISSUE THREAD

**Issue by iuliiasobolevska** [codecentric/spring-boot-admin#2595]
## Spring Boot Admin Server information

- **Version**:
`3.0.4`

- **Spring Boot version**:
`3.0.6`

## Description
`sba-instance-section` is supposed to show a spinner when a page hasn't loaded yet. That doesn't seem to be the case. Example: beans page.

**Comment by SteKoe** [comment]
Hi @iuliiasobolevska,

thanks for reporting this bug. A fix has just been pushed and will be included in the next release. 

Regards
SteKoe
