### ISSUE TITLE
How to add Authorization request header

### ISSUE THREAD

**Issue by cn-src** [codecentric/spring-boot-admin#2607]
My security framework requires storing the token in the header. How should I do this? I cannot access the global axios object to add interceptors.

**Comment by ulischulte** [comment]
Hi @cn-src,

we're not 100 percent sure if we understand your issue correctly. Do you want to intercept the communication from SBA to instances/applications or to SBA itself?
Bearer Tokens etc. should be sent by default. 

Can you provide a demo application which reproduces your problem?

Regards,
Uli

**Comment by cn-src** [comment]
I want to intercept all AJAX requests and add my token to the header. My token is stored in localStorage.
But I don't know how to retrieve the existing global axios instance.

<img width="578" alt="image" src="https://github.com/codecentric/spring-boot-admin/assets/8263180/3b3ef7d0-569b-475e-8cc9-b09c23872b88">

```js
window.onload = function() {
    axios.interceptors.request.use(function (config) {
        const token = window.localStorage.getItem('DW_TOKEN')
        config.headers['Authorization'] = 'Bearer ' + token;
        return config;
    }, function (error) {
        return Promise.reject(error);
    });
}
```

**Comment by marbon87** [comment]
Hi @cn-src ,
we had the same requirement and solved it  by using an rev-proxy (like oauth2-proxy), that does the oauth2-communication with the identity provider, holds the Bearer-Token and sends it with each request to the SBA-server (in Authorization-Header).

**Comment by ulischulte** [comment]
Hi @cn-src
 
You may need to configure and implement an `HttpHeadersProvider` in order to use a custom header containing the token for requests towards actuator endpoints of monitored applications (https://docs.spring-boot-admin.com/current/customize_http-headers.html).
The Provider will then be recognized automatically via `AdminServerAutoConfiguration`.

For instance, if your actuator endpoints are behind OAuth2 security, this might look something like this:
```
@Bean
public HttpHeadersProvider bearerAuthHeaderProvider(OAuth2AuthorizedClient oAuth2AuthorizedClient) {
    OAuth2AccessToken oAuth2AccessToken = oAuth2AuthorizedClient.getAccessToken();
    final HttpHeaders httpHeaders = new HttpHeaders();
    httpHeaders.add(HttpHeaders.AUTHORIZATION, "Bearer " + oAuth2AccessToken.getTokenValue());
    return (app) -> httpHeaders;
}
```
Does this help you?

Regards,
Uli

**Comment by ulischulte** [comment]
Closed due to inactivity. Please feel free to open a new issue if this is still not fixing your problem.
