### ISSUE TITLE
metrics section blank , found undefied error in index.vue

### ISSUE THREAD

**Issue by billyshen26** [codecentric/spring-boot-admin#2618]
## Spring Boot Admin Server information

- **Version**:
  2.7.10

- **Spring Boot version**:
  2.7.2

- **Configured Security**:
  basic auth

- **Webflux or Servlet application**:
 servlet application 

## Client information

- **Spring Boot versions**:
  2.7.2

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
servlet application 

## Description
i have Insights menu ,howerver, most sections are blank. when i open Devtools in chrome use F12 ,i found en error in console.
`vue.runtime.esm.js:3019 TypeError: Cannot read properties of undefined (reading 'length')
    at o.a (index.vue:1:444)
    at t._render (vue.runtime.esm.js:2654:28)
    at o.r (vue.runtime.esm.js:3844:27)
    at t.get (vue.runtime.esm.js:3415:33)
    at t.run (vue.runtime.esm.js:3491:30)
    at Kr (vue.runtime.esm.js:4090:17)
    at Array.<anonymous> (vue.runtime.esm.js:3113:20)
    at $n (vue.runtime.esm.js:3035:16)`
![image](https://github.com/codecentric/spring-boot-admin/assets/5089845/fd47fb28-da6b-4ab4-bb48-694aadd003c9)

you can check the error here: [http://47.99.145.44:8000/instances/5bd10f62ff01/metrics](http://47.99.145.44:8000/instances/5bd10f62ff01/metrics)  
username: server
password: server

error can be found in adminserver , please have a look.  another client mailserver is ok.

i can share the codes, if necessary. but the code for adminserver is a little complex. so i just want to know why line 444 in index.vue have undefined error. how can i fix it ? thanks

Billy

**Comment by hzpz** [comment]
Hi @billyshen26,

you seem to have modified your Actuator endpoints somehow. They all return the correct data but wrapped in something like this:

```
{
    "code": 0,
    "message": "ok",
    "result": {
      // actual data here
    }
}
```

Spring Boot Admin expects the data without the result wrapper.

**Comment by billyshen26** [comment]
thanks , seems that caused by CustomResponseBodyAdvice in adminserver ,let me try to fix

**Comment by billyshen26** [comment]
fixed.
`    public Object beforeBodyWrite(Object o, MethodParameter methodParameter, MediaType mediaType, Class<? extends HttpMessageConverter<?>> aClass, ServerHttpRequest serverHttpRequest, ServerHttpResponse serverHttpResponse) {

        String url = ((ServletServerHttpRequest) serverHttpRequest).getServletRequest().getRequestURI();
        if ( antPathMatcher.match("/actuator/**",url)){ // spring boot admin actuator do not wrapper
            return o;
        }
...
}`
