### ISSUE TITLE
Why a custom tab not support the html

### ISSUE THREAD

**Issue by proton5000** [codecentric/spring-boot-admin#2620]
I have created the custom tab, it's works. But, when I started to show something data on it I have see that I cant create a new line or something else, only the one line of text. Maybe it would be better that the SBA can render the simple html tags? Why do I need a new tab if I can not read the information on it, since there is one continuous, unbreakable line of text. How can this be used?
![image](https://github.com/codecentric/spring-boot-admin/assets/11408913/d1ae8172-2795-4a69-b6e4-01c7eb18a707)

**Comment by MaxProk** [comment]
have the same issue

**Comment by Gomenyuk-Gleb** [comment]
It's about time. Anyway, it doesn't look good in the span tag

**Comment by SteKoe** [comment]
Hi all,

I have checked the custom ui example in our sources and achieve the following results:

<img width="359" alt="Bildschirmfoto 2023-07-21 um 07 03 54" src="https://github.com/codecentric/spring-boot-admin/assets/1809221/bb5ae8dc-5dbf-4910-85e7-5e1d2a0c3116">
    

The first "output" line, printing escaped HTML tags, looks like the one you have shown in your screenshot. The second one is rendering the HTML tags as expected. Hence, I assume that you are using the `v-text` directive to let Vue.js print the response of your service. To allow rendering of HTML, you have to switch to `v-html` which allows you to render arbitrary HTML code on your page. Please check the [documentation](https://vuejs.org/api/built-in-directives.html#v-html) of Vue.js at this point, as `v-html` might be a security risk.

Also, please find the corresponding code of the screenshot, below:

```html
<template>
  <div class="custom">
    <p>Instance: <span v-text="instance.id" /></p>
    <p>Output: <span v-text="text" /></p>
    <p>Output: <span v-html="text" /></p>
  </div>
</template>
```

Regards,
SteKoe

**Comment by proton5000** [comment]
@SteKoe thanks for Your answer
But, maybe, You are use the newest version? I'm using the 2.7.10 version of SBA due to my spring boot version
I have generate the custom tab by maven dependency:
```
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-sample-custom-ui</artifactId>
			<version>2.7.10</version>
		</dependency>
```
in this version of spring-boot-admin-sample-custom-ui the Vue.js generate only one output like this
![image](https://github.com/codecentric/spring-boot-admin/assets/11408913/7c0c3b56-db01-4d18-a7a7-4478ba7a4178)

**Comment by SteKoe** [comment]
This won’t work as you are using the sample custom ui which does not allow to render HTML directly (it uses `v-text`). You will have to implement _your very own_ custom UI including a Vue.js component that allows you to render HTML provided by your backend. 

I have posted a Vue.js snippet above which can be used to render HTML. I suggest to adapt the `spring-boot-admin-sample-custom-ui` sample. Please also consult the documentation on how to create a custom view [here](https://docs.spring-boot-admin.com/current/customize_ui.html#customizing-custom-views).

**Comment by proton5000** [comment]
@SteKoe Ok, I understud You. I need a build the spring-boot-admin-sample-custom-ui himself with my cusom options and instal it to local maven repository. And then use it in my project as the local maven dependency. This is very inconvenient to maintain. With any changes I need rebuild / install the new version of spring-boot-admin-sample-custom-ui and then rebuild my main application. I need to update my CI for create the new step with rebuild first of all the spring-boot-admin-sample-custom-ui if I need some updates for it. And then rebuild the main application. This complicates the support of such an application and increases the deployment time. Why not implement some options for the spring-boot-admin-sample-custom-ui and update this options from application properties such as output format text / html and etc?

**Comment by SteKoe** [comment]
> I need a build the spring-boot-admin-sample-custom-ui himself with my cusom options and instal it to local maven repository. And then use it in my project as the local maven dependency.

Correct, this is the way to go if you plan to implement your very own, custom UI which serves your special needs.

> With any changes I need rebuild / install the new version of spring-boot-admin-sample-custom-ui and then rebuild my main application. [...]This complicates the support of such an application and increases the deployment time.

A **custom** UI is an extension to Spring Boot Admin. Extensions are highly individual as they serve a very special need. Within a custom UI you can do whatever you want, as there are no restrictions in doing so. Its main purpose is to give some kind of flexibility to our users to add features to SBA that are not be provided by SBA itself.

Anyways, I have switched the `v-text` component to `v-html` in our example as it does not affect the result of the sample project. The changed artifact will be available as [SNAPSHOT version](https://github.com/codecentric/spring-boot-admin/packages/575590) right now (check [README](https://github.com/codecentric/spring-boot-admin#snapshot-builds) how to pull snapshot versions). 

But **please** keep in mind that all projects in `spring-boot-admin-sample` are just examples, that can be used as basis or starter. They are **NOT** intended to be used as dependency nor production ready.
