### ISSUE TITLE
config prop and environment values not being sanitized

### ISSUE THREAD

**Issue by erbrecht** [codecentric/spring-boot-admin#2622]
## Spring Boot Admin Server information

- **Version**:
  3.1.3

- **Spring Boot version**:
  3.1.2

- **Configured Security**:
  none

- **Webflux or Servlet application**:
  servlet

## Client information

- **Spring Boot versions**:
  3.1.2

- **Used discovery mechanism**:
  self registration

- **Webflux or Servlet application**:
  servlet

## Description

Since the upgrade to Spring Boot 3, and the corresponding updates to Spring Boot Admin, sanitizing values has not worked the same. It appears that the values for config properties and environment variables are not being sanitized at all. These 2 repos are a simple server/client setup to show the behavior.

https://github.com/erbrecht/sba-server-sanitize
https://github.com/erbrecht/sba-client-sanitize

I would expect the admin server to sanitize the value for `spring.security.user.password`. I also added an environment variable with a name that should be sanitized (`special.token`) but is not.

Hopefully the 2 sample applications are helpful. Please let me know if I'm misunderstanding how this should be working, or if I've configured something incorrectly. I tried to keep the config as minimal as possible.

**Comment by ulischulte** [comment]
Hi @erbrecht ,
This is rather a basic spring boot functionality than SBA-related. You can still use `management.endpoint.additionalKeysToSanitize` and `management.endpoint.env.keys-to-sanitize` to configure specific sanitization or implement a Component using the `SanitizingFunction` interface.

By the way, those properties will only work for the [auto-configuration from Spring Boot](https://github.com/spring-projects/spring-boot/blob/5b107141fdb2db652419365e6184f12d25519b7f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/servlet/UserDetailsServiceAutoConfiguration.java#LL85C2-L85C2). If you provide an UserDetailsService bean, the UserDetailsServiceAutoConfiguration will back off and won't initialize a default user for you.

Did this help you?
Cheers 
Uli

**Comment by erbrecht** [comment]
You're totally right. This behavior changed in actuator. I should have looked more closely, I'll need to implement my own sanitizing function. Thanks for getting back to me, you can close this out.
