### ISSUE TITLE
How to customize charts based on Metrics?

### ISSUE THREAD

**Issue by asasas234** [codecentric/spring-boot-admin#2623]
In the /instances/xxx/details page there will be several charts related to JVM memory, I think it's great, but the number of charts is too small, for example, I would also like to define charts based on Metrics such as number of requests, request time, etc., is there any way to do this?

I know I can add custom Metrics monitoring in the /instances/5ec31768c422/metrics page, but that's just in table form, I'd like it to be in chart form

**Comment by SteKoe** [comment]
It is not possible to customize/extend the default pages of SBA, but you can implement your very own view as shown in the [documentation](https://docs.spring-boot-admin.com/current/customize_ui.html#customizing-custom-views).

**Comment by asasas234** [comment]
@SteKoe I see. Thank you very much.
