### ISSUE TITLE
I'm using it to keep track of my 53 small(isch) apps - mostly deployed on tomcat in 3 environments - more to come.

### ISSUE THREAD

**Issue by ValentineMWAY** [codecentric/spring-boot-admin#2625]
I'm using it to keep track of my 53 small(isch) apps - mostly deployed on tomcat in 3 environments - more to come.

_Originally posted by @rittermit in https://github.com/codecentric/spring-boot-admin/issues/1304#issuecomment-557119821_

**Comment by ValentineMWAY** [comment]
hi, how you configure it, tell pls

**Comment by SteKoe** [comment]
Hi @ValentineMWAY,

please check the docs at https://docs.spring-boot-admin.com/current/getting-started.html on how to get started. You have several ways on how to configure SBA.

If you have *specific* questions or issues, feel free to reopen this issue.

Regards,
SteKoe
