### ISSUE TITLE
PropertySources content not wrapping correctly in Details View

### ISSUE THREAD

**Issue by briansjavablog** [codecentric/spring-boot-admin#2628]
## Spring Boot Admin Server information

- **Version**:
3.1.3

- **Spring Boot version**:
3.1.2

- **Configured Security**:
basic auth

- **Webflux or Servlet application**:
Servlet 

## Client information

- **Spring Boot versions**:
2.7.0

- **Used discovery mechanism**:
kubernetes

- **Webflux or Servlet application**:
Servlet

## Description
After a recent upgrade from Boot Admin 2.6.0 to 3.1.3 I noticed an issue in the way the Insights/Details view is rendered. 
The propertySources config value no longer wraps correctly and results in a horizontal scrollbar.

In version 2.6.0 the view looks like this

![image](https://github.com/codecentric/spring-boot-admin/assets/2404172/5220187e-0e4d-4139-b300-69eb290a4053)

In version 3.1.1 the view looks like this

![image](https://github.com/codecentric/spring-boot-admin/assets/2404172/6c802593-961b-4e04-bb27-74cbd820d120)

**Comment by SteKoe** [comment]
![Bildschirmfoto 2023-08-04 um 09 55 30](https://github.com/codecentric/spring-boot-admin/assets/1809221/d1196808-efc0-4504-a954-546d82a1cf3a)

**Comment by briansjavablog** [comment]
@SteKoe - thanks for the quick turnaround, much appreciated
