### ISSUE TITLE
Getting error while browsing through apps

### ISSUE THREAD

**Issue by pradeepkusingh** [codecentric/spring-boot-admin#266]
Getting this error in console UI , any idea why ?

Error: {"timestamp":1473537927823,"status":404,"error":"Not Found","message":"No message available","path":"/metrics"}

**Comment by joshiste** [comment]
Did you check that the /metrics endpoint of your client application is active? Or did you change the path of it?

**Comment by pradeepkusingh** [comment]
i checked http://hostname:port/activation(context-management)/mertics is
showing all data. Not sure why this is failing.

Thanks,
Pradeep Singh
Please excuse typos.

**Comment by joshiste** [comment]
If you changed your management.context-path and use eureka read this section carefully http://codecentric.github.io/spring-boot-admin/1.4.1/#_serviceinstanceconverter
