### ISSUE TITLE
Instances remain in status DOWN though health check returns overall status UP

### ISSUE THREAD

**Issue by ydubrouka** [codecentric/spring-boot-admin#2672]
## Spring Boot Admin server 

- **Version**: 3.1.3

- **Spring Boot version**: 3.1.0

- **Configured Security**: ldap for SBA, health endpoints -- basic

- **Webflux application**.

## Client information

- **Spring Boot versions**: 2.7 and 3.1

- **Used discovery mechanism**: consul

- **Servlet applications**

## Description

SBA shows that some apps are down on applications page: red icon. This is also shown in a dropdown on instance details page. But if we look to health panel on instance details page then we see all green and UP.

Issue was resolved after restart of SBA. All apps are shown as UP.

## Analysis if the issue

Event Journal for apps that are shown in DOWN state showed one event where we actually got DOWN from a health check for that app. One of the apps services was not fully up. There are no other events in the log that say that app is UP and running normally.

Subsequent SBA calls to health check of that app returns UP but status of the app is never updated to UP and remains DOWN.

## Bug (?)

From our perspective this looks like a bug since actual status of the app is never updated of there are no other events.

At the moment no more info is available or how to reproduce the issue.

**Comment by ouaibsky** [comment]
Same issue on our side, I thought it was only with kubernetez discovery client, but same issue with service declared in config file.

Anyway it could be nice to add somewhere in the application page a button to manually ask again an health status

Thx
Christophe

**Comment by ahoehma** [comment]
I have the same effect.

Dashboard shows 1 instance red
![image](https://github.com/codecentric/spring-boot-admin/assets/548214/7205457c-7d77-4fbe-88aa-6a0d47a834e9)

But if I click into this instance its green
![image](https://github.com/codecentric/spring-boot-admin/assets/548214/c492448f-1a83-431e-9f39-69af1d9a9949)

**Comment by SteKoe** [comment]
Hi, we have made some changes in 3.1.6 regarding the mechanism of detecting status changes of instances. Could you please update your server to 3.1.6 and check if the issues still occur? TIA!

**Comment by ydubrouka** [comment]
We will probably update our instances next week. So far we have never seen the problem again.

**Comment by ahoehma** [comment]
Hi, I updated yesterday and watched the new app since then and now it seems to work much better! :-) Mercí

**Comment by janar-rahumeel** [comment]
Hi @SteKoe can you also fix 2.7.x version?

**Comment by SteKoe** [comment]
> Hi @SteKoe can you also fix 2.7.x version?

We have just released version 2.7.11 including the fix. :)

**Comment by ouaibsky** [comment]
Hi, also updated and works like a charm now.
Thanks a lot

**Comment by ydubrouka** [comment]
We have rolled out new version on premises. So far we have not experienced the issue on live. I'd say we can close the ticket.
