### ISSUE TITLE
SpringbootAdmin Kubernetes AutoDiscovery Pointing to Internal POD IP and not LoadBalancer IP 

### ISSUE THREAD

**Issue by sitamadhavi** [codecentric/spring-boot-admin#2673]
SpringbootAdmin Using Kubernetes AutoDiscovery.. It is picking the Pods with internal POD IP which are not accessible when executed remotely . How can we change pod lookup to use external ip / loadbalancer ip.

**Comment by ulischulte** [comment]
Hi @sitamadhavi 

you will have to forward those ports. Have a look at [Spring Boot Admin Kubernetes discovery example](https://github.com/codecentric/spring-boot-admin-discovery-playground/tree/main/kubernetes/apps/spring-boot-admin-kubernetes). It contains a running example on how to run SBA with Kubernetes Discovery.

Does this help you?

Regards 
Uli

**Comment by sitamadhavi** [comment]
Yes.. thank you ; It worked for me.
***
Sri Sri Ravi Shankar (AOL) -
Purity in heart, clarity in mind, sincerity in action and contentment is
the formula for happiness.
Our Worth is always determined by our deeds, not by our good intentions,
however noble.
***
