### ISSUE TITLE
Values in Environment view obscured with ***** 

### ISSUE THREAD

**Issue by briansjavablog** [codecentric/spring-boot-admin#2677]
## Spring Boot Admin Server information

- **Version**:
3.1.3

- **Spring Boot version**:
3.1.2

- **Configured Security**:
basic auth

- **Webflux or Servlet application**:
Servlet 

## Client information

- **Spring Boot versions**:
2.7.0

- **Used discovery mechanism**:
kubernetes

- **Webflux or Servlet application**:
Servlet

## Description
After a recent upgrade from Boot Admin 2.6.0 to 3.1.3 the values displayed in the Environment view are obscured with ****. In version 2.6.0 values regarded as sensitive were obscured such as passwords but this now appears to be happening for all values.

In version 2.6.0 the view looks like this

![image](https://github.com/codecentric/spring-boot-admin/assets/2404172/2e0ad19c-7ab3-4877-a4bd-259424c129da)

In version 3.1.1 the view looks like this

![image](https://github.com/codecentric/spring-boot-admin/assets/2404172/971d327c-7911-438e-a154-e58c700f910f)

**Comment by ulischulte** [comment]
Hi @briansjavablog 

Starting from Spring Boot 3, all actuator values are always masked by default. To get the same result as before you could consider the following configuration.
`management.endpoint.env.show-values=ALWAYS`

Have a look at the Spring Boot documentation on how to manage sanitization of actuator endpoint values starting from Spring Boot 3 ([Actuator Endpoints Sanitization](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.actuator.sanitize-sensitive-values)). 

I just opened up a pull request with enhanced documentation on how to configure sanitizing values in Spring Boot 3.

Regards 
Uli
