### ISSUE TITLE
Wallboard Customize Font Size

### ISSUE THREAD

**Issue by Ephenodrom** [codecentric/spring-boot-admin#2687]
![grafik](https://github.com/codecentric/spring-boot-admin/assets/30625794/4e385284-5fc4-4fcf-9550-641f5c922403)

The font size for the service names and running version are too big, for example if your service does not contain a "-". So there is no linebreak and the name is bigger than the hexagon width.
I would like to configure the font sizes via the application properties or have the functionality to add some custom css to the ui.

**Comment by ulischulte** [comment]
Hi @Ephenodrom,
the wallboard now has set the word-break class property by default. Servicenames should fit into the hexagons. Additionally, there's also the possibility of adding custom CSS.
Regards,
Uli
