### ISSUE TITLE
No notifications when service removed

### ISSUE THREAD

**Issue by rnbWarden** [codecentric/spring-boot-admin#270]
It looks like we have a race condition when services are removed. Sometimes we see the Down notification and others we don't... which I believe is a result of eureka /polling intervals/ etc. 

After walking through the source I see that these are two distinct events and the AbstractStatusChangeNotifier ignores ClientApplicationDeregisteredEvent. I can work around this by supplying our own concrete bean (SlackNotifier) which handles the DeregisteredEvent, but wondering if this wouldn't be a feature worth adding to the abstract class for everyone to leverage? Or if there's a better way to handle this, please let me know.

**Comment by aantono** [comment]
I've noticed the same behavior.  The browser/chrome notifications do the same thing also. Would you mind Shari f your implementation of SlackNotifier?

**Comment by joshiste** [comment]
@aantono the browser notifications listen to all events and work a bit differently..

@rnbWarden So do you expect a Slack notification when a service deregisters? Isn't it on purpose when a services deregisters so an extra notification isn't needed?

**Comment by rnbWarden** [comment]
The issue is that down/deregister happen all at once when the app drops out of eureka... and if deregister happens first, we never get a down status change notification.

**Comment by joshiste** [comment]
I got the race condition, but what behaviour do you expect?

In my opinion when the service shuts down on purpose and there is a cancel send to the Eureka server there should be no down event just the deregistration event. (which is currently flawed because of the race condition)

But when the service crashes and doesn't deregister from Eureka there should be an down event and no deregister event (which should already apply)

**Comment by rnbWarden** [comment]
Using the graceful shutdown use-case, I'd like to see a channel notification for deregister since we won't get a down status change. 

What is your preferred design for handling this? Another EventListener devoted to deregister events or handling deregister along with Status Change in the existing Notifier? Based on what I've seen I'd think handling in the existing notifier.

**Comment by rnbWarden** [comment]
@aantono - Since you asked, here's the simplest SlackNotifier I put together that converts a regsitration/deregistration events into Status change events. I also elected to override notify() in my testing but that may or may not be useful to you.

I wound up not using this exact implementation after all and wrote something more complex to handling throttling/batching notifications.

HTH

`
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(prefix = "spring.boot.admin.notify.slack", name = "enabled", matchIfMissing = true)
    @ConfigurationProperties("spring.boot.admin.notify.slack")
    public SlackNotifier slackNotifier() {

        return new SlackNotifier() {

            @Override
            public void notify(ClientApplicationEvent event) {

                super.notify(event);

                Application application = event.getApplication();
                if (event instanceof ClientApplicationDeregisteredEvent) {
                    super.notify(new ClientApplicationStatusChangedEvent(application, StatusInfo.ofDown(), StatusInfo.ofOffline()));
                } else if (event instanceof ClientApplicationRegisteredEvent) {
                    super.notify(new ClientApplicationStatusChangedEvent(application, StatusInfo.ofOffline(), application.getStatusInfo()));
                }
            }
        };
    }
`
