### ISSUE TITLE
Status of Application is not updated when application is deployed as traditional war file

### ISSUE THREAD

**Issue by jbhardwaj12** [codecentric/spring-boot-admin#274]
Status of Application is not updated when application is deployed as traditional war file. Following behavior is observed on Spring Boot Admin 1.4.1 and Springboot 1.4.0-RELEASE:
1. Spring boot admin is started as traditional war on Tomcat 8 (instance 1) deployed as windows service
2. Client application is started as traditional war on Tomcat 8 instance 2) deployed as windows service
3. Client registers itself with current status (UP) with Sptring Boot Admin on Tomcat 8 (instance 1)
4. Tomcat (instance 2) Service is stopped, status is not updated on Spring Boot Admin 

Status is correctly updated when Client application is running with embedded tomcat.

**Comment by joshiste** [comment]
By default the status update is triggered every 10s and the status is updated if the old status is 10s old. So in the worst case the status recieves an update after 20s. Did you wait that amount of time?

**Comment by joshiste** [comment]
The status check is a http get on the health endpoint. Did you check that the endpoint was really unaccessible (and no zombie process did answer)?

**Comment by jbhardwaj12** [comment]
Application or Tomcat both were not accessible and nor was the <app-path>/health. Tomcat process as well as corresponding Java process was ensured is terminated.  Waited more than a minute to get status reflected.
This was repeated 3 times before raising with with your team. I tried it with and without apache proxy (everything is on same machine) but behavior seems to be consistent.
This behavior was not observed when client was running with embedded tomcat.

I am new to Spring Boot Admin, I would assume that as client registered successfully the configurations is complete and additional configuration is required for traditional deployment.

**Comment by joshiste** [comment]
I couldn't reproduce the issue using both applications running on tomcat 7 on linux

**Comment by joshiste** [comment]
Did you check the admins log after stopping the client application? There should be an exception logged if the other instance gets inaccessible.
