### ISSUE TITLE
Project Version & Build Info is not reflecting then client is deployed as Traditional war

### ISSUE THREAD

**Issue by jbhardwaj12** [codecentric/spring-boot-admin#275]
When client is deployed as traditional war with external configuration, with following properties not included in external configuration file. It is expected to be picked from resolved/filtering resources from maven build from with in the classpath. (Embedded tomcat works fine)

1. spring.boot.admin.client.name=${project.artifactId} ${project.version}
2. info.version=${project.version}
3. info.artifactId=${project.artifactId}

- spring.boot.admin.client.name : resolves correctly
- info.version=do not resolve 
- info.artifactId=do not resolve 

![image](https://cloud.githubusercontent.com/assets/11051205/18639342/2ae1e95e-7e59-11e6-8ac1-fba358339147.png)

Is that expectation correct or how to achieve this with external configuration and traditional war ?

**Comment by joshiste** [comment]
You need to check if you have your maven resource filtering setup properly. The information are taken from the `/info` endpoint from spring boot actuator and it's configuration has nothing to do with SBA.

For more information have a look at https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html

**Comment by joshiste** [comment]
Also have a look at the [spring boot reference guide section](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-application-info-env)
