### ISSUE TITLE
“Configuration Properties”issues by com.baomidou.dynamic.datasource.ds.ItemDataSource、com.alibaba.druid.pool.DruidPooledConnection

### ISSUE THREAD

**Issue by dengchufeng** [codecentric/spring-boot-admin#2756]
【Version】
1、SpringBoot：3.0.9
2、SpringBoot Admin：3.1.6
3、SpringCloud：2022.0.4
4、SpringCloud Alibaba：2022.0.0.0
5、druid-spring-boot-3-starter（com.alibaba）：1.2.18
6、dynamic-datasource-spring-boot3-starte（com.baomidou）：4.1.3

【Question】
Hello, timeout accessing monitored projects using spring boot admin： Did not observe any item or terminal signal within 9000ms in 'log' (and no fallback has been configured)

【Question  Recurrence】
1、Click on the "Configuration Properties" of the monitoring project
![1](https://github.com/codecentric/spring-boot-admin/assets/142789289/4012e724-9697-4481-a42d-88f74c81e53c)
![2](https://github.com/codecentric/spring-boot-admin/assets/142789289/97cc5e0a-4221-41ac-9591-7830adedae22)
2、SpringBoot Admin project（zy-monitor） error
![3](https://github.com/codecentric/spring-boot-admin/assets/142789289/30fe09e7-fe29-43c0-a5a3-8d2c49432570)
3、Monitored project（zy-base） warn
![4](https://github.com/codecentric/spring-boot-admin/assets/142789289/0aa139dd-5e07-4d7b-8175-ebb6d4eb9131)

【Summarize】
1、Is it incompatible with druid、dynamic-datasource version
2、Do you have any good suggestions to address this issue

**Comment by erikpetzold** [comment]
Hi @dengchufeng 

we have tried to analyze your issue, but cannot help you at the moment.

1. Can you please provide an runnable example project on github?
2. We don't know dynamic-datasource-spring-boot3-starte and the documentation is completely in chinese, so we cannot understand.
3. dynamic-datasource-spring-boot3-starte has a github issue for druid, maybe there is something missing? https://github.com/baomidou/dynamic-datasource/issues/558
4. **From the error messages it seems more like a connection issue**. Seems the monitored aplication is registering on SBA server, but the server cannot reach the application. That would explain the error in the frontend and also the error in the log (coming from status updater (scheduled task), not related to the frontend error)
5. The warning in the application should have nothing to do with SBA.

Regards

**Comment by dengchufeng** [comment]
@erikpetzold  Thank you for your reply

【project address】
1、https://github.com/dengchufeng/zy-cloud
2、There are three projects involved，zy-business inside "zy-base"
![image](https://github.com/codecentric/spring-boot-admin/assets/142789289/d81c3c20-cf77-4cba-ad50-cb0f1d5fa868)
3、need to build a nacos service
![image](https://github.com/codecentric/spring-boot-admin/assets/142789289/2ab7ca22-55ad-4058-9fc2-d2f97aaeea79)

【other issue】
1、issue：Cross domain issues occur when accessing the springboot admin through the gateway
2、Same as the above project, involving 2 projects, The gateway configuration can be found in the nacos.sql configuration file
![image](https://github.com/codecentric/spring-boot-admin/assets/142789289/f6747e8e-2566-4cd0-a719-4f4bc089c878)
3、Cross domain issues occur when accessing admin using the gateway, As shown in the following figure, 20238 port is the gateway port
![image](https://github.com/codecentric/spring-boot-admin/assets/142789289/c7e5c0c2-00d6-4a67-8d7c-5ddadfdbf1c6)
4、Attempted to add cross domain configuration in admin, but still had this issue.
5、It would be possible to specify public-url and context-path in admin, but this is not what I want, Is there a better way
![image](https://github.com/codecentric/spring-boot-admin/assets/142789289/7083bde0-023e-42e6-a270-46a4bd33f36d)
6、Thank you again for your reply

**Comment by ulischulte** [comment]
Hi @dengchufeng,

It looks like your problem is very specific and is driven more by your setup than by spring boot admin itself. 
Since this is an open source project and we're all putting our effort into it in our free time, I cannot reproduce your issue with the information at hand with a minimum of expense.
Starting from your last response, I tried to start zy-monitor first, which didn't work out-of-the-box. In addition to that, I wasn't able to start any of the other clients provided. Analyzing complex and individual setups is very time-consuming and will not be our prior objective. A failing test, for instance, provided by you, would be much more purposeful.

Keep in mind that we're always open for new contributers. Most likely, you are the person with the expertise to address this problem. So, if you have a suitable solution in mind, don't hesitate to open up a merge request.

Regards 
Uli

**Comment by dengchufeng** [comment]
Hi @ulischulte 

Thank you for looking into my issue. I understand that you tried to analyze the problem but couldn’t assist me at the moment.
I apologize for the inconvenience caused. Unfortunately, I cannot provide a runnable example project on GitHub at the moment. I will try to find a solution with the resources available to me.

I appreciate your suggestions regarding the dynamic-datasource-spring-boot3-starte documentation and the GitHub issue for Druid. I will review them and see if they can provide any help in resolving my issue.
Thank you for clarifying that the warning in the application is unrelated to SBA. I will investigate further to identify the cause of the connection issue between the monitored application and the SBA server.

Once again, thank you for your attention to my problem and your willingness to assist.
