### ISSUE TITLE
1.4.2 breaks client registration

### ISSUE THREAD

**Issue by mweirauch** [codecentric/spring-boot-admin#277]
It occurs to me as if the changes from #260 breaks client registration in a non-hystrix environment.

Setup: Simple boot app (cloud-config,eureka-client, sba-client)
```
		<spring-boot.version>1.4.1.RELEASE</spring-boot.version>
		<spring-cloud.version>Brixton.SR6</spring-cloud.version>
		<spring-boot-admin.version>1.4.2</spring-boot-admin.version>
```

With `1.4.1` it works fine. Note, that `event.getApplicationContext().getParent()` is not `null` here.

**Comment by joshiste** [comment]
Got a stacktrace? Or sth. Else?

**Comment by joshiste** [comment]
Why are you using the sba client in addition to eureka?
OK I guess the bootstrap context from cloud config is the parent context... So we need to get rid of the null check and solve #260 different.

**Comment by mweirauch** [comment]
Thanks for the quick fix! I'll give it a try tomorrow.

Regarding eureka and sba-client: There might be apps which are not providing any services discoverable via eureka. But from your question it sounds as if it's best practice to register anything with eureka no matter if there are consumers of the service and having sba query eureka for the available apps/services?

**Comment by joshiste** [comment]
>  But from your question it sounds as if it's best practice to register anything with eureka no matter if there are consumers of the service and having sba query eureka for the available apps/services?

Why not. I think it would be better just to use a single way of registering your applications and getting rid of the extra dependency.
Imho having a extra sba client is just needed if you have a good reason to keep the services out of eureka.

**Comment by jervi** [comment]
If the property `spring.application.name` is defined in `bootstrap.yml`, it seems like it is ignored by Spring Boot Admin > 1.4.1, including 1.4.3-SNAPSHOT. 
![spring boot admin](https://cloud.githubusercontent.com/assets/155558/19432715/18de0b14-945e-11e6-8c89-971086f86085.png)

**Comment by joshiste** [comment]
@jervi  please submit a new issue.

**Comment by jervi** [comment]
@joshiste Sorry. I've made a new issue: #303
