### ISSUE TITLE
Support for client-side security

### ISSUE THREAD

**Issue by sjnorman** [codecentric/spring-boot-admin#279]
It doesn't appear that the admin app can communicate with a client that has its management resource secured  via the setting:

`management.security.enabled=true`

Although it's not an optimal solution, it would be useful to be able to pass in the http basic auth credentials used for each client's management resource during the registration process (perhaps configured via property) so that the management endpoints can be secured on the spring-boot application side of things.

**Comment by joshiste** [comment]
For examples on how to integrate security please have a look at these samples here: https://github.com/joshiste/spring-boot-admin-samples

Currently submitting credentials during the registration process isn't supported because the sensitive information could leak easily via the rest api.
