### ISSUE TITLE
Is mixing client and server possible ?

### ISSUE THREAD

**Issue by mar1ged** [codecentric/spring-boot-admin#284]
I have seen the nice new features that Spring Boot Admin provides. Unfortunately some of the applications we use are still on Spring Boot 1.3.8 (updated recently) and are not yet fit for Spring Boot 1.4.x

Is it possible to have a Spring Boot 1.3.8 application use Spring Boot Admin Client 1.3.6 and have it connected to a Spring Boot Admin Server 1.4.2 ?
`Spring Boot 1.3.8 + Spring Boot Admin Client 1.3.6 -> Spring Boot Admin Server 1.4.2`

Or could I even stick with Spring Boot 1.3.8 and put Spring Boot Admin Client 1.4.2 into it and let it connect to Spring Boot Admin Server 1.4.2 ?
`Spring Boot 1.3.8 + Spring Boot Admin Client 1.4.2 -> Spring oOot Admin Server 1.4.2`

**Comment by joshiste** [comment]
> Is it possible to have a Spring Boot 1.3.8 application use Spring Boot Admin Client 1.3.6 and have it connected to a Spring Boot Admin Server 1.4.2

It is. The protocol for registration hasn't changed.

> Or could I even stick with Spring Boot 1.3.8 and put Spring Boot Admin Client 1.4.2 into it and let it connect to Spring Boot Admin Server 1.4.2 ?

That's not intended and very probably won't work,
