### ISSUE TITLE
Trouble accessing jmx 

### ISSUE THREAD

**Issue by mar1ged** [codecentric/spring-boot-admin#285]
I use Spring Boot 1.3.8 with Spring Boot Admin Client 1.3.6, jolokia-core 1.3.4 is on the classpath and I even forced the proper logback.xml with `-Dlogback.configurationFile=...` and checked if it is used with `-Dlogback.debug=true`

Unfortunately Spring Boot Admin Server still tells me 
![jmx](https://cloud.githubusercontent.com/assets/16045549/18971985/95d49842-8697-11e6-8cb7-4b496b55dca8.png)
("To make the JMX section work you need to make the /jolokia-endpoint accessible" and "Expected CSRF token not found. Has your session expired?")

`/jolokia` is shown when I run Spring Boot Actuator `/mappings´ and when I open the URL in my browser I see proper JSON. 

Perhaps it is just too late for my brain, but I don't see the reason why this doesn't work.

**Comment by joshiste** [comment]
You need to disable the CSRF-protection for the `/jolokia` endpoint in your spring security in your client application.

**Comment by mar1ged** [comment]
I followed your advice and set `spring.enable-csrf=false` in my application.yml (and checked if this is effective using the `/env` endpoint: it is)

Do you happen to know a known working approach to this ?

**Comment by joshiste** [comment]
I guess you have a custom `WebSecurityConfigurerAdapter`? Then setting this property has no effect.

**Comment by mar1ged** [comment]
It is not really my own code, but I checked it: I am sory but I have to say there is no  `WebSecurityConfigurerAdapter`

**Comment by joshiste** [comment]
did you check server and client for not having csrf active? Since the sba server just forwards the request via zuul to the client endpoint both apps need to have csrf disabled...
