### ISSUE TITLE
defined the self url for admin-client application

### ISSUE THREAD

**Issue by aohanhongzhi** [codecentric/spring-boot-admin#2893]
<img width="1728" alt="image" src="https://github.com/codecentric/spring-boot-admin/assets/37319319/416b6517-92cd-4789-b247-3bc6bdf5af7d">

sometimes,  the client app maybe proxy by nginx . so the `request.getRequestURL()` can not get the path in nginx.

so I need config the currect path by yaml config file.

<img width="754" alt="image" src="https://github.com/codecentric/spring-boot-admin/assets/37319319/fcb70a00-9475-4f3b-8e9f-42e33649dcbb">

actually, springboot admin server can not get the information from the self url  restful api by nginx

**Comment by ulischulte** [comment]
Hi @aohanhongzhi 
have you tried to set `server.forward-headers-strategy` to `NATIVE`?
(https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.use-behind-a-proxy-server)

**Comment by ulischulte** [comment]
We're closing this issue due to missing feedback. If you're still facing problems, please open up a new issue and fill out the bug template.

Regards,
Uli
