### ISSUE TITLE
Why is environmental information hidden?

### ISSUE THREAD

**Issue by doveylovey** [codecentric/spring-boot-admin#2928]
Why is environmental information hidden? How should I configure to see them?
![image](https://github.com/codecentric/spring-boot-admin/assets/28882195/27525471-0570-4190-a74e-1d516a539c4b)

**Comment by ulischulte** [comment]
Hi @doveylovey

Starting from Spring Boot 3, all env and configprops actuator values are masked by default. To get the same result as before you could consider the following configuration.
management.endpoint.env.show-values=ALWAYS

Have a look at the Spring Boot documentation on how to manage sanitization of actuator endpoint values starting from Spring Boot 3 [Actuator Endpoints Sanitization](https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/howto-actuator.html#howto-sanitize-sensible-values).

Does this help you?

Regards
Uli

**Comment by doveylovey** [comment]
Ok, thank you very much.  @ulischulte 
By the way, why can't you take a service offline?
![image](https://github.com/codecentric/spring-boot-admin/assets/28882195/cdf7a973-6cee-4c96-ba06-a45b878c7de5)

**Comment by erikpetzold** [comment]
Probably there is an error message being logged by Spring Boot Admin Server. There could be many reasons, like errors from the instance that should be stopped or permission problems.

**Comment by erikpetzold** [comment]
If the problem with the shutdown persists, please open a new issue. Use the bug issue template and if possible provide an example that can be used to preproduce the issue.

**Comment by SylvainAssemat** [comment]
Hi all.

I m still confused about this issue.

When i set : 

`
management:
  security:
    enabled: false
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: ALWAYS
    env:
      # Hide properties that end with password and username:
      # keys-to-sanitize: password,username
      show-values: ALWAYS
    configprops:
      # Also hide port and key values from the output:
      # keys-to-sanitize: port,key
      show-values: ALWAYS
`

i am still seeing those hidden properties everywhere (*****)

Is there another security that i am missing ?
