### ISSUE TITLE
Clients register themselves as "OFFLINE" (since 1.4.2, no problems in 1.4.1)

### ISSUE THREAD

**Issue by rfelgent** [codecentric/spring-boot-admin#293]
When migrating SBAP from version 1.4.1 to 1.4.2, the clients register themselves as offline.

Log example:
2016-10-05 17:47:29.969  INFO 23343 --- [registrationTask1] d.c.b.a.services.ApplicationRegistrator  : Application registered itself as {managementUrl=http://XXXXX:9999/actuator, healthUrl=http://YYYY:9999/actuator/health, serviceUrl=http://YYYY, name=XXX, id=323e9a24, statusInfo={status=OFFLINE, timestamp=1475682434470}}

The SBAP server shows the instances as offline, but the "detail" button is active and you can hit the tabs "log", "metrics", "trace" and so on.

More information:

- SBAP sits behind a web server
- SBAP is protected (based on spring security config from the example)
- actuator endpoints of clients are protected (based on spring security config from the example)
- SBAP knows credentials to connect to clients (Zuulfilter configured according to example)

**Comment by joshiste** [comment]
Please look into the SBA server. If your application is listed as offline there should be an exception. I guess the server can't reach the client...

**Comment by rfelgent** [comment]
Hi @joshiste,

I neither see errors nor warning in the SBAP log.

I do see an info in the client who registers to SBAP (see my first comment!). As far as i understand the log message, the client registers with status "statusInfo={status=OFFLINE, timestamp=1475682434470}}". That sounds strange...

Furthermore, I can access the endpoint information though SBAP without problems. It just the offline status SBAP's gui and the the detail view at the same time that irritates me.

**Comment by joshiste** [comment]
> I do see an info in the client who registers at SBAP (see my first comment!). As far as I understand the log message, the client registers with status "statusInfo={status=OFFLINE, timestamp=1475682434470}}". That sounds strange...

In deed registering normally has status UNKNOWN and triggers a status update.
Do you use any "special" config for the sba server additional to spring security (e.g. spring cloud config)?

You could set the loggerlevel for the StatusUpdater to DEBUG and see what happens...

**Comment by rfelgent** [comment]
I do not use spring cloud. Is the StatusUpdater running on SBAP or the client?

**Comment by joshiste** [comment]
On the Server.

**Comment by joshiste** [comment]
@rfelgent I could not reproduce the error. Can you provide a sample project to reproduce it?

**Comment by rfelgent** [comment]
Hi @joshiste ,

the error still exists. I attached the SBAP sample project
[sbap.zip](https://github.com/codecentric/spring-boot-admin/files/527441/sbap.zip)

**Comment by joshiste** [comment]
1) In your local profile you disable the SlackNotifier, when you do this, the delegate for the FilteringNotifier will be null - resulting in an NPE. I'd recommend to configure a LoggingNotifier in this case.

2) The StatusUpdater recieves a 401 from the client (itself in this case) you either need to add `/actuator/health` to the security ignores for the clients or you need to instantiate the StatusUpdater yourself with a RestTemplate which knows the credentials

btw, the client registers as "DOWN" not as "OFFLINE" - a slight difference OFFLINE = no tcp connect - DOWN = not HTTP-OK (200)

**Comment by joshiste** [comment]
Also note that SBA 1.4.2 is built against Spring Boot 1.4.1 (your build gradle had a 1.4.0)

**Comment by rfelgent** [comment]
Hi @joshiste 

thx for your fast responses! 
The troubles the last days I had with SBAP was due to protected actuator endpoints. My team decided to protect all actuator endpoints except /actuator/info because of the loadbalancer.

Looking back, I had to make following steps to make the things work again:

1) SBAP/SERVER: Extending the com.netflix.zuul.Zuulfilter like described in https://raw.githubusercontent.com/joshiste/spring-boot-admin-samples/master/basic-auth/admin-server/src/main/java/com/github/joshiste/spring/boot/admin/samples/admin/BasicAuthFilter.java

2) CLIENTS: a required Update from 1.4.1 to 1.4.2, so the client registration uses http auth (_buggy_ RestTemplateBuilder-pattern in Spring)

3) SPAB/SERVER: creating the Bean StatusUpdater with required http basic auth credentials


I think it would be nice to add a chapter in the _reference documentation_ like "how to configure SBAP & Clients with protected actuator endpoints". This could save the time for other developers.

Furthermore, I was not aware the existence of the LoggingNotifier. Thx for the tip (or update the reference documentation ;-) )

**Comment by joshiste** [comment]
> My team decided to protect all actuator endpoints except /actuator/info because of the loadbalancer.

Why are you using `/info` for the loadbalancing. `/health` would be more reasonable cause it checks resources you depend on...

Also you can configure the health endpoint to expose only the status and no further details...

There are plans for Boot 1.5 to protect the endpoints as default. Making the out-of-the-box experience for protected endpoints is on my todo list.

**Comment by openjack** [comment]
Using eureka, spring boot 1.4.2 with Camden.SR3 and spring boot admin 1.4.4.

My eureka servers register as OFFLINE (not down).

From the logs:

Couldn't retrieve status for Application [id=5ce33f52, name=DISCOVERY-SERVICE, managementUrl=http://mydomain.com:80, healthUrl=http://mydomain.com:80/health, serviceUrl=http://mydomain.com:80]

I am deploying with docker.  I had to configure these properties in order to get my peer replication working properly:

eureka:
  instance:
    hostname: mydomain.com
    nonSecurePort: 80
    non-secure-port: 80
    preferIpAddress: false

Replication is working
The /health endpoint is returning successfully, properly
There is no security enabled on the actuator endpoints

**Comment by joshiste** [comment]
I guess the url http://mydomain.com:80/health is not reachable from within your admin container...
Most likely the hostname can't be resolved....

**Comment by openjack** [comment]
I was sleepy.  Thanks for the direction!

The way we have haproxy/marathon-lb setup to route vhosts (mydomain.com) doesn't work when there is a :PORT on the url.

So http://mydomian.com/health works, but http://mydomain.com:80/health does not.
