### ISSUE TITLE
AdminClientProperties.getServiceUrl() ignores server.address if preferIp=false

### ISSUE THREAD

**Issue by weeniearms** [codecentric/spring-boot-admin#295]
When binding to a specific address (i.e. server.address set to something other than null/empty) urls are using the machine hostname, unless you set preferIp=true. Therefore, the generated urls will not be reachable by the admin server if the hostname does not map to the address provided as server.address.

Although, setting preferIp=true resolves this, it also makes it impossible to use an alternative hostname (which you can set as server.address, e.g. server.address=customhostname) instead of an IP address.

**Comment by joshiste** [comment]
Do I understand you right:
If server.address is set the url should determine the hostname for server.adress and not localhost.
right?

**Comment by weeniearms** [comment]
Exactly. I already have a fix for that, so I could submit a PR if you'd like.

**Comment by joshiste** [comment]
>  so I could submit a PR if you'd like.

The enhancement sounds reasonable, so go for it!

**Comment by weeniearms** [comment]
Would it be possible to also include this in the 1.3.x branch?

**Comment by joshiste** [comment]
closed in favour of #296
