### ISSUE TITLE
External Views Dropdown not working without Top Level Link

### ISSUE THREAD

**Issue by https429** [codecentric/spring-boot-admin#2968]
## Spring Boot Admin Server information

- **Version**:
  3.1.8

- **Spring Boot version**:
  3.0.5

## Description

On your documentation Page, there is a [section](https://docs.spring-boot-admin.com/current/customize_ui.html#dropdown-with-links) for embedding external Webpages in the Navbar.

You provide two examples, one with an Top Level Link and one without.
Since Commit [d6d79d0](https://github.com/codecentric/spring-boot-admin/commit/d6d79d09a281baf2c5f600d390539d9feb708b00) or Version 3.1.8 the example without the Top Level Link is no longer working.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.boot.admin.ui.external-views[0]' to de.codecentric.boot.admin.server.ui.web.UiController$ExternalView:

    Reason: java.lang.IllegalArgumentException: 'url' must not be empty

Action:

Update your application's configuration
```

Thanks for coding the Admin Service and good luck fixing :)

**Comment by ulischulte** [comment]
Hi @https429 

I wasn't able to reproduce your problem. There is a running sample here: [spring-boot-admin-servlet-sample](spring-boot-admin-samples/spring-boot-admin-sample-servlet)
It provides external views with and without children.
Could you provide a sample configuration to reproduce the problem?

Regards,
Uli
