### ISSUE TITLE
Toggle for enable/disable ApplicationStatusHero in Applications view

### ISSUE THREAD

**Issue by Hildebrand-Ritense** [codecentric/spring-boot-admin#2983]
Hi there, I love Spring Boot Admin and how it really puts the Spring framework in its strenght.
At my company we currently have 25 applications registered. Some of these are rightly so in the _unknown_ health state.

The status hero (first thing on the Applications list view) however tells me _Some instances are down_. This is incorrect.
Also, I think the visual summary of the Wallboard view already works for us. As such I'm looking for a toggle to disable this hero.

I've shortly looked at adding a custom view, but I feel that is a bit overkill for the thing I'm trying to achieve.

All in all, would that be something that can be implemented?

**Comment by erikpetzold** [comment]
Hi @Hildebrand-Ritense,

we discussed this and will not make this configurable, so there will be no toggle to disable the hero.

But we agree that the current visualization is not optimal and will work on a solution.

**Comment by ulischulte** [comment]
Just so we're all talking about the same thing... It's about the portrayal of this 'hero'

![image](https://github.com/codecentric/spring-boot-admin/assets/16336547/e0d85e67-0597-4d1e-bb89-1dcabe3f287f)

**Comment by Hildebrand-Ritense** [comment]
Yes, that's right.

**Comment by ulischulte** [comment]
Hi @Hildebrand-Ritense,

We have recently created a PR that deals with the different status combinations and their corresponding representation in the ApplicationHero (#3000). It has been released with version 3.2.1.

Does the solution meet your requirements so that we can close this issue?

**Comment by ulischulte** [comment]
Hi @Hildebrand-Ritense,

We're closing this issue. If the 'new' hero implementation is still missing something for you, feel free to open up a new issue.

Regards,
Uli

**Comment by Hildebrand-Ritense** [comment]
Hi Uli,

Thank you for the release, I was planning on deploying and testing it this week but have been busy with other matters unfortunately. From the PR it's looking good though, will let you know later on.

Thank you, much appreciated,
Hildebrand
