### ISSUE TITLE
Status changed event does not include health details

### ISSUE THREAD

**Issue by jgraglia** [codecentric/spring-boot-admin#2997]
## Spring Boot Admin Server information

- **Version**:
2.7.11

- **Spring Boot version**:
2.7.18

- **Configured Security**:
none

- **Webflux or Servlet application**:
servlet

## Client information

- **Spring Boot versions**:
2.7.11 or 2.7.10

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
Servlet

## Description

When upgrading from Spring Boot Admin server 2.7.10 to 2.7.11 I have found that the status changed event no longer include the additionnal details.

I have build a demo system  reproducing the issue : see [https://github.com/jgraglia/spring-boot-admin-registration-issue](https://github.com/jgraglia/spring-boot-admin-registration-issue)

I have a client spring boot defining some custom components for the health status  : 
```java
@Component
public class CustomHealthComponent implements HealthIndicator {
    @Override
    public Health health() {
        return Health.up().withDetail("foo10", "bar").withDetail("tags", Set.of("A10", "B10")).build();
    }
}
```

Those details are still visible in the healh page of Spring Boot Admin Server
![image](https://github.com/codecentric/spring-boot-admin/assets/754914/8cba036d-c94f-4f1a-8734-4fee2c6d84a7)

but there are missing from the "Status Update" event in the journal.

With Spring Boot 2.7.10, the details were included in the event

![image](https://github.com/codecentric/spring-boot-admin/assets/754914/3b90ed18-de56-49d6-8198-f394207b2166)

Version [2.7.11](https://github.com/codecentric/spring-boot-admin/releases/tag/2.7.11) does include a commit on the status event but I can't see the change 

[https://github.com/codecentric/spring-boot-admin/compare/2.7.10...2.7.11](https://github.com/codecentric/spring-boot-admin/compare/2.7.10...2.7.11)

**Comment by SteKoe** [comment]
Hi @jgraglia,

thanks for opening the issue and providing a demo repository! We found some regression issues in the 2.7-branch and included a fix for your issue as well. Please try using our newest release 2.7.15. It should include the desired details / custom components now.

Regards,
SteKoe

**Comment by jgraglia** [comment]
I can confirm that 2.7.15 fix the regression.

Thank you for this quick fix & release !
