### ISSUE TITLE
Run Spring Boot Admin with Gradle

### ISSUE THREAD

**Issue by izeye** [codecentric/spring-boot-admin#30]
Is there any support for Gradle?

Due to the Maven parent POM, I can't run it.

JS files' version problems occur.

https://github.com/izeye/samples-spring-boot-admin

**Comment by n0mer** [comment]
add this to you build.gradle

```groovy
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.webjars' && details.requested.name == 'angularjs') {
            details.useVersion '1.2.12'
        }
    }
}
```

**Comment by izeye** [comment]
@n0mer Thanks but I did already a similar thing like this:

    compile("org.webjars:jquery:1.11.0")
    compile("org.webjars:angularjs:1.2.12")

It works fine but I think it would be nice if the users don't have to care about the versions.

**Comment by n0mer** [comment]
that's why i asked them in #25 to modify their POM by including explicit versions of transitive dependencies

**Comment by joshiste** [comment]
The UI has been separated from the server and the webjars are gone. There shouldn't be no problems with the transitive dependencies any more.

**Comment by joshiste** [comment]
It's not published yet. To test it you have to build from scratch
Am 06.01.2015 05:48 schrieb "izeye" <notifications@github.com>:
