### ISSUE TITLE
BeanCurrentlyInCreationException with empty server project

### ISSUE THREAD

**Issue by andreasevers** [codecentric/spring-boot-admin#300]
Just created a new SBA server application:
- Downloaded maven project with Spring Boot 1.4.1 without extra dependencies from http://start.spring.io
- Added the following two dependencies:
```xml
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-server</artifactId>
	<version>1.4.2</version>
</dependency>
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-server-ui</artifactId>
	<version>1.4.2</version>
</dependency>
```
- Add SBA annotation to Application class:
```java
@SpringBootApplication
@EnableAdminServer
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}
```

This throws the following exception:

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> There is a circular dependency between 5 beans in the application context:
> 	- endpointHandlerMapping defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointWebMvcManagementContextConfiguration.class]
> 	- mvcEndpoints defined in class path resource [org/springframework/boot/actuate/autoconfigure/EndpointWebMvcManagementContextConfiguration.class]
> 	- zuulEndpoint defined in class path resource [de/codecentric/boot/admin/config/RevereseZuulProxyConfiguration$RoutesEndpointConfiguration.class]
> 	- de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration (field private org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping de.codecentric.boot.admin.config.RevereseZuulProxyConfiguration.zuulHandlerMapping)
> 	- zuulHandlerMapping defined in class path resource [de/codecentric/boot/admin/config/RevereseZuulProxyConfiguration.class]
> 	- routeLocator
> 
> 
> 2016-10-12 19:29:56.190 ERROR 76199 --- [           main] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener@7995092a] to prepare test instance [com.example.DemoApplicationTests@6a87026]
> 
> java.lang.IllegalStateException: Failed to load ApplicationContext
> ...
> Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'routeLocator': Requested bean is currently in creation: Is there an unresolvable circular reference?

**Comment by joshiste** [comment]
Hmm... the error is from a testcase or not?

**Comment by andreasevers** [comment]
Yep from the maven clean install.
The testcase basically just loads the applicationContext, but perhaps it's the new `@SpringBootTest` annotation that has an impact?

```java
@RunWith(SpringRunner.class)
@SpringBootTest
public class DemoApplicationTests {

	@Test
	public void contextLoads() {
	}

}
```

**Comment by joshiste** [comment]
Switch it to `@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)` and you're done :smile:

**Comment by andreasevers** [comment]
Couldn't be easier :D

Cheers!

**Comment by MHarris021** [comment]
I had the same issue, and this solution worked just fine. Maybe add it to the getting started guide?

**Comment by dartains** [comment]
Not working for me, Gradle-4.8
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
public class WebiReportSchedulerApplicationTests {

	@Test
	public void contextLoads() {
	}

}

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :processResources
> Task :classes
> Task :bootJar
> Task :jar SKIPPED
> Task :assemble
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test

com.ericsson.csdp.bm.webireportscheduler.WebiReportSchedulerApplicationTests > contextLoads FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.service.spi.ServiceException
                Caused by: org.hibernate.HibernateException

1 test completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

**Comment by joshiste** [comment]
your root cause is a a HibernateException. SBA uses no Hibernate.
