### ISSUE TITLE
JMX Non-Primitive Parameters are not Passed

### ISSUE THREAD

**Issue by StasKolodyuk** [codecentric/spring-boot-admin#301]
When passing a non-primitive `jmx` method parameters in `JSON` format they are sent as `null` to `/jolokia` endpoint. However, `/jolokia` itself supports passing non-primitive method parameters in `JSON` format.

**Comment by StasKolodyuk** [comment]
Hey, @joshite, you've closed the issue. Will it be fixed?

**Comment by joshiste** [comment]
It was closed from a commit and the commit message says 'fixed' ...

So you can try a 1.4.3-SNAPSHOT build and test the fix if you want to.

**Comment by StasKolodyuk** [comment]
Thank you very much!
