### ISSUE TITLE
Properties defined in bootstrap.yml are ignored by client

### ISSUE THREAD

**Issue by jervi** [codecentric/spring-boot-admin#303]
When using Spring Cloud Config, if you define the property `spring.application.name` in `bootstrap.yml`, it seems like it is ignored by clients > 1.4.1 (?), including 1.4.3-SNAPSHOT. It worked in earlier versions.

![spring boot admin](https://cloud.githubusercontent.com/assets/155558/19435814/037629fa-946d-11e6-83db-c1261bc28242.png)

**Comment by joshiste** [comment]
With 1.4.3-SNAPSHOT I couldn't reproduce the error (when spring-cloud-starter-config is active).
Could you try the current snapshot? And when you can reproduce the error please provide the sample project..

![image](https://cloud.githubusercontent.com/assets/8779225/19445803/1ef7d3e4-9496-11e6-8f05-78d635e82a20.png)

**Comment by jervi** [comment]
Sorry. I'm unable to reproduce it in a new project as well. On further investigation, the project in question actually refuse to read the `spring.application.name` property no matter where it is defined. I'll have to investigate further. Sorry for wasting your time!

**Comment by jervi** [comment]
For anyone interested: It was Swagger that caused the problem, more specifically the annotation `@EnableSwagger2` from SpringFox. When I remove the annotation, the client registers using the correct name. I'm not sure what the actual culprit was, but it does register a `PropertyPlaceholderConfigurer` bean, which I suspect might be a possible cause.

**Comment by jervi** [comment]
https://github.com/springfox/springfox/issues/1514
