### ISSUE TITLE
Secured management port

### ISSUE THREAD

**Issue by HobbesFNM** [codecentric/spring-boot-admin#304]
Hi, apologies if this is somewhere else in the docs, but I really can't find it.  Can this admin UI work with TLS secured Actuator services?  I am uneasy about exposing any unsecured paths into my application in production environments and whilst obviously the actuator management points can be secured, would this then preclude this utility from working with them?

Many thanks.

**Comment by joshiste** [comment]
> Can this admin UI work with TLS secured Actuator services?

Do you mean to use client certificates to identify the SBA against the monitored applications? It's possible, it would require that you modify the used http clients for the zuul proxy filter and the `StatusUpdater`'s restTemplate.
If you just mean that the SBA should accept self-signed certificates from your applications you just need to use a reqular java trustKeystore containing the certificates.

In the docs for the just released 1.4.3 there is a [note on security](http://codecentric.github.io/spring-boot-admin/1.4.3/#securing-spring-boot-admin) and a reference to some examples to secure your endpoints.

**Comment by joshiste** [comment]
P.s. I currently plan to improve the out-of-the-box experience with basic-auth secured endpoints for the next version (not scheduled yet; but not before boot 1.5.0)
