### ISSUE TITLE
Problems still exist

### ISSUE THREAD

**Issue by aohanhongzhi** [codecentric/spring-boot-admin#3056]
https://github.com/codecentric/spring-boot-admin/issues/2893

https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.use-behind-a-proxy-server

**Comment by erikpetzold** [comment]
Hi @aohanhongzhi ,

as written in #2893 , it would be really helpful if you would use the **template** we're providing for bugs. In the edit mode it contains also hints what to fill in there.

Please also provide some **description** of the problem. What have you already tried? have you set `spring.boot.admin.ui.public-url` and `erver.forward-headers-strategy=native`?

**Comment by aohanhongzhi** [comment]
> Hi @aohanhongzhi ,
> 
> as written(书面) in #2893 , it would(会) be really helpful(乐于助人) if you would(会) use the **template** we're providing(提供) for bugs. In the edit(编辑) mode(模式) it contains also hints what to fill in there.
> 
> Please also provide(提供) some **description(描述)** of the problem. What have you already tried? have you set `spring.boot.admin.ui.public-url` and `erver.forward-headers-strategy=native`?

of course , I have set `spring.boot.admin.ui.public-url and erver.forward-headers-strategy=native`, but it not helpful

**Comment by aohanhongzhi** [comment]
> Hi @aohanhongzhi
> 
> I added a sample with nginx proxy here: https://github.com/codecentric/spring-boot-admin-discovery-playground/tree/main/nginx
> 
> Maybe now I start understanding your problem (you still did not really describe your setup). From the screenshots in #2893 I guess, that you are talking about the connection between admin server and monitored app. So only your monitored app lives behind the proxy and the url it returns is pointing to the wrong url (private url, not public url of the proxy). So I guess you want to modify the values in the /actuator endpoint? Like in the example from above http://localhost:8888/hello/actuator returns <img alt="grafik" width="634" src="https://private-user-images.githubusercontent.com/16555444/297073900-4f5c1f5c-e477-421b-b2d5-af2cfb035429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTQ2MjAsIm5iZiI6MTcwNTQ5NDMyMCwicGF0aCI6Ii8xNjU1NTQ0NC8yOTcwNzM5MDAtNGY1YzFmNWMtZTQ3Ny00MjFiLWIyZDUtYWYyY2ZiMDM1NDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyMjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNDgxMzFlNGY0OWYyNzNiY2E3YWE5MTkwNzkwZGUxMDJhYzg0ZDU3ZjY0MjA0YjViYjVmMzgxZDE2ZmZkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tC0Jc2swwOUT5Arb7AcYumLcXRRBqbx40exj6uCrmbE"> which contains http://hello-world-nginx:8081/ that would not be reachable from the outside. So Admin Server could not access this, right?
> 
> Hint: Actuator is provided by Spring Boot itself, not by Admin. The class in your screenshot is not even from Spring Boot Admin.
> 
> Questions:
> 
> * Is the setup and problem I assumed correct?
> * Which discovery/registration mechanism do you use?

bingo , you are right! I didn't use any `discovery/registration mechanism`

so as you mean , I should solve the problem by modify Actuator to use `public url of the proxy`?

**Comment by erikpetzold** [comment]
I mean, there must be some kind of discovery or registration, the admin server must know the spring apps somehow.

E.g. with self registration you can provide the url (`spring.boot.admin.client.instance.health-url`) that the adminserver should use, so it would not use the url that is returned by the actuator anyways, so no need to fix this.

**Comment by aohanhongzhi** [comment]
> I mean, there must be some kind of discovery or registration, the admin server must know the spring apps somehow.
> 
> E.g. with self registration you can provide the url (`spring.boot.admin.client.instance.health-url`) that the adminserver should use, so it would not use the url that is returned by the actuator anyways, so no need to fix this.


I configed `spring.boot.admin.client.instance.health-url` , but it is not working.

![image](https://github.com/codecentric/spring-boot-admin/assets/37319319/3b19f1ed-6524-4260-851c-44279810262b)

**Comment by erikpetzold** [comment]
As I said before, the properties will not change the output of the actuator endpoint. Actuator is provided by Spring Boot and is not influenced by the `spring.boot.admin` properties.
So the url in your screenshot is completely out of our control. This is part of Spring Boot itself.

However, the Spring Boot Admin does not use these urls in href. So even if they are wrong, you can get Spring Boot Admin to call the correct urls. Therefore, the client which is used to register can be configured with some different properties, see https://docs.spring-boot-admin.com/current/client.html#spring-boot-admin-client
You would need to set `health-url`/`management-url`/`service-url` depending on your setup. Probably `management-url` should be your url with the `prod-api` path. Then SBA Server will call the actuator endpoints with this path.

Here as graphical overview:
<img width="673" alt="grafik" src="https://github.com/codecentric/spring-boot-admin/assets/16555444/1b9494e6-64d7-428e-9f07-17a67f3a575f">


In the example in the playground (see above) you can simulate that situation by setting 
`spring.boot.admin.client.instance.service-url: "http://host.docker.internal:8888/hello"`
then the admin client would register with that url and admin server would call client through proxy

**Comment by aohanhongzhi** [comment]
> As I said before, the properties will not change the output of the actuator endpoint. Actuator is provided by Spring Boot and is not influenced by the `spring.boot.admin` properties. So the url in your screenshot is completely out of our control. This is part of Spring Boot itself.
> 
> However, the Spring Boot Admin does not use these urls in href. So even if they are wrong, you can get Spring Boot Admin to call the correct urls. Therefore, the client which is used to register can be configured with some different properties, see https://docs.spring-boot-admin.com/current/client.html#spring-boot-admin-client You would need to set `health-url`/`management-url`/`service-url` depending on your setup. Probably `management-url` should be your url with the `prod-api` path. Then SBA Server will call the actuator endpoints with this path.
> 
> Here as graphical overview: <img alt="grafik" width="673" src="https://private-user-images.githubusercontent.com/16555444/297999343-1b9494e6-64d7-428e-9f07-17a67f3a575f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Njk0MjksIm5iZiI6MTcwNTY2OTEyOSwicGF0aCI6Ii8xNjU1NTQ0NC8yOTc5OTkzNDMtMWI5NDk0ZTYtNjRkNy00MjhlLTlmMDctMTdhNjdmM2E1NzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEyNTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMWI0ZTE1Zjc0M2I0NmFkOWMxM2U1YjU3MTc0ZmM0NDQ5ZDc3NDVlNDNkYWNlMzllYjBlM2YyYjg3MjJlZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1GsxMh1E2NgZLZxBAznpqtS5yX9AxmJSPFlRDACAD4">
> 
> In the example in the playground (see above) you can simulate that situation by setting `spring.boot.admin.client.instance.service-url: "http://host.docker.internal:8888/hello"` then the admin client would register with that url and admin server would call client through proxy

unfortunately, it is not  working too.

![image](https://github.com/codecentric/spring-boot-admin/assets/37319319/d9ca62f5-8da0-4390-bb06-33c7a23cfc07)

**Comment by erikpetzold** [comment]
What exactly is "not working"? Do you have any error message?

**Comment by aohanhongzhi** [comment]
> What exactly is "not working"? Do you have any error message?

I mean this spring.boot.admin.client.instance.service-url still doesn't have a way to configure the post-proxy address

Looking at the Springboot Actuator source code, there's really no way to configure this

Maybe I should go to the Springboot Actuator github and make my request.

thank you very much!
