### ISSUE TITLE
Specify the ip of springadminserver to restrict ip access to actuator endpoints.

### ISSUE THREAD

**Issue by aohanhongzhi** [codecentric/spring-boot-admin#3057]
The security department often scans springadmin endpoints for exposure to various issues

Specify the ip of springadminserver to restrict ip access to actuator endpoints.

**Comment by erikpetzold** [comment]
Hi @aohanhongzhi 

it is very hard to understand what you want to achieve. Can you please provide some more details?

Where do you want wo specify the ip address?
Which Setup are you using? Versions? Discovery mechanism? Environment?
Reactive or Servlet?

You can already add your own security config. Your apps and the Spring Boot Admin Server can all be secured with Spring Security, so you can already add your own rules. 
The different security configuration requirements are one reason why Spring Boot Admin is provided as a library and not as a just-run-it application. But as mentioned you can use Spring Security https://spring.io/projects/spring-security/

**Comment by aohanhongzhi** [comment]
> Hi @aohanhongzhi
> 
> it is very hard to understand what you want to achieve(实现). Can you please provide(提供) some more details?
> 
> Where do you want wo specify(指定) the ip address? Which Setup are you using? Versions? Discovery mechanism(机制)? Environment? Reactive or Servlet?
> 
> You can already add your own security(安全) config. Your apps and the Spring Boot Admin Server can all be secured with Spring Security(安全), so you can already add your own rules. The different security(安全) configuration requirements are one reason why Spring Boot Admin is provided(提供) as a library and not as a just-run-it application(应用). But as mentioned you can use Spring Security(安全) https://spring.io/projects/spring-security/

as you said, I should setup by Spring Security.

**Comment by erikpetzold** [comment]
Ok, we will close this issue as there is nothing we can do in spring boot admin at the moment
