### ISSUE TITLE
Can spring mvc project register to spring boot admin server?

### ISSUE THREAD

**Issue by XiaokunHou** [codecentric/spring-boot-admin#307]
Is there any example to register spring mvc to admin server?

**Comment by joshiste** [comment]
For registering client applications please read the [Docs](http://codecentric.github.io/spring-boot-admin/1.4.3/#register-client-applications)

**Comment by Miltonjacomini** [comment]
The Docs don't say exely what do for register mvc applications. The answer don't helped on this problem.
I think that the correct answer would be to looking for 'SpringBootAdminClientAutoConfiguration' and find a way that is not talked in anywhere how register that. 

I'm looking for this, if i find do that. i will post here.

[]'s

**Comment by Miltonjacomini** [comment]
That project helped me find the solution...

https://github.com/Azilen/Spring-Actuator

He implement some classes that are used for register the application on Spring Boot Admin.

:+1:
