### ISSUE TITLE
springbootadmin-client， Start using external tomcat，Failed to register with the admin server 

### ISSUE THREAD

**Issue by 1198735966** [codecentric/spring-boot-admin#3077]
springbootadmin-client， Start using external tomcat，Failed to register with the admin server

**Comment by SteKoe** [comment]
Hi @1198735966,

first of all thank you for ignoring our bug issue template. Despite that, we really need the information asked in there: What version (of spring boot admin as well as tomcat) are you using and, most importantly, how to reproduce the issue? 

The only things we can derive from your exhaustive bug report are: You are using Spring Boot Admin, running an external (so you seem to have a WAR-package, deployed to Tomcat?) Tomcat and then a SBA-Client fails to register with a SBA-Server that runs somewhere (hopefully).

So, please, as we would like to understand the issue and help you, provide more information.

Thank you very much.

**Comment by 1198735966** [comment]
springboot version :2.0.3
spring-boot-admin-starter-server :2.0.3,
The configuration is normal.Start using external tomcat. The client is not injected into the server，

**Comment by erikpetzold** [comment]
Closing this issue as it is completely unclear.
If you still have problems please open abug ticket and
- fill the template
- provide error message
- describe your setup
