### ISSUE TITLE
gradle support, repositories mavenCentral?

### ISSUE THREAD

**Issue by kamilwlf** [codecentric/spring-boot-admin#310]
How to add it to gradle project:
I tried:

> compile('org.springframework.boot:spring-boot-admin-starter-client')

but it does not work
Should I add something extra? It is in mavenCentral?

**Comment by kamilwlf** [comment]
Ok, I got it from here:
https://mvnrepository.com/artifact/de.codecentric/spring-boot-admin-starter-client/1.2.3

It should be 

> compile('de.codecentric:spring-boot-admin-starter-client')

**Comment by joshiste** [comment]
Yes we publish our artifacts to Maven Central.
