### ISSUE TITLE
Configuration for spring.boot.admin.routes.endpoints is missing, cannot add @EnableAdminServer

### ISSUE THREAD

**Issue by kamilwlf** [codecentric/spring-boot-admin#311]
spring-boot-admin-starter-client-1.2.3.jar
does not include:
 spring-boot-admin/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/config/EnableAdminServer.java

then I can not enable:
@EnableAdminServer

![screenshot - 2016-10-28 11_45_24](https://cloud.githubusercontent.com/assets/7765963/19802459/1da5a428-9d04-11e6-8e7c-08719f676903.jpg)

**Comment by joshiste** [comment]
The `@EnableAdminServer` is part of the `spring-boot-admin-server` artifact. Also I'd advise you to switch to the latest version (1.4.1)
Please read the [Getting started guide](http://codecentric.github.io/spring-boot-admin/1.4.3/#getting-started) on how to get started.

**Comment by kamilwlf** [comment]
yup, I was using old docs,  I added extra dependencies
'de.codecentric:spring-boot-admin-server:
de.codecentric:spring-boot-admin-server-ui:
