### ISSUE TITLE
Display version(s) for groups in application list

### ISSUE THREAD

**Issue by anderius** [codecentric/spring-boot-admin#312]
Right now, in spring-boot-admin-server-ui/modules/applications/views/applications-list.html, only name and status is displayed for each grouped application. For us, it would be very useful to also have the version there. My suggestion:

If all instances have the same version, display that version. If not, display some text, for example: "Versions differ", or something like that.

The objective is to get a quick overview of what is deployed.

What do you think?

**Comment by joshiste** [comment]
Yeah why not. PRs are alway welcome :)

**Comment by anderius** [comment]
I might have some time this week to make a PR, but will only be happy if anyone beats me to it! :-)
