### ISSUE TITLE
Missing applicationversion in applicationlist 

### ISSUE THREAD

**Issue by NF10** [codecentric/spring-boot-admin#3126]
## Spring Boot Admin Server information

- **Version**:
3.2.1

- **Spring Boot version**:
3.2.1

- **Configured Security**:
Basic Auth with ldap

- **Webflux or Servlet application**:
Servlet

## Client information

- **Spring Boot versions**:
3.2.2 and 3.1.1

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
servlet

## Description
I miss the applicationversion in the applicationlist. I have to unfold to see the version.

spring boot admin server 3.1.0
![image](https://github.com/codecentric/spring-boot-admin/assets/63918287/d0a190f9-b918-413d-9861-acf7ea665a1a)

spring boot admin server 3.2.1
![image](https://github.com/codecentric/spring-boot-admin/assets/63918287/9826dfba-782a-4dcb-8832-458fee4e114c)

**Comment by vanicekv** [comment]
It also made my job a lot more complicated, before you could see at a glance who has which version in the list, currently you have to unpack everything first... It's annoying and impractical.

**Comment by NFehringVHV** [comment]
@ulischulte Thanks for your work :) Is it possible to get a 3.2.3 version with this Commit? :)
