### ISSUE TITLE
Filter-Input is lost after selecting an application

### ISSUE THREAD

**Issue by marbon87** [codecentric/spring-boot-admin#3138]
## Spring Boot Admin Server information

- **Version**:
3.2.1

- **Spring Boot version**:
3.1.7

- **Configured Security**:
OAuth2

- **Webflux or Servlet application**:
Servlet

## Client information

- **Spring Boot versions**:
2.x-3.x

- **Used discovery mechanism**:
Consul

- **Webflux or Servlet application**:
Servlet

## Description

The content of the filter-input element is dynamically added to the uri in the browser and get's added to the history.
But when i select an instance of an application in the search result, the filter-parameter in the browser is removed.
If i now navigate to the instance and then go back in  the browser, the content of the filter is lost.

Example:
1. Open springbootadmin
2. Type a word in the filter, e.g. test and notice that the uri parameter q=test is added to the uri in the browser uri bar:
<img width="1772" alt="image" src="https://github.com/codecentric/spring-boot-admin/assets/2949525/cd303096-0bc6-456c-b87c-082c1d19a2d4">
3.  Click on the first element in the result and noticat that the uri parameter q=test is lost:
<img width="1748" alt="image" src="https://github.com/codecentric/spring-boot-admin/assets/2949525/3459c3a3-5b45-4bae-a2e2-92bda5a31936">

**Comment by erikpetzold** [comment]
will be included in next release
