### ISSUE TITLE
Add option to disable core ui-modules

### ISSUE THREAD

**Issue by ahmednasir91** [codecentric/spring-boot-admin#314]
Two questions

- The active connections are showing as 0 (screenshot attached), any idea what needs to be configured for this to work?
- Also, we don't need liquibase, flyway, is there a way we can disable some checks?

![capture](https://cloud.githubusercontent.com/assets/1519532/19882270/353413cc-a02e-11e6-9689-a953b6aec8c0.PNG)

**Comment by joshiste** [comment]
> The active connections are showing as 0 (screenshot attached), any idea what needs to be configured for this to work?

I guess you need "just" to set you system under pressure. The data is taken from the `/metrics` endpoint.

> Also, we don't need liquibase, flyway, is there a way we can disable some checks?

As of now it's not possible to disable some of the "core" ui-modules (which would remove the checks)..
But we could add that feature.

**Comment by ahmednasir91** [comment]
@joshiste cool thanks.

What do you suggest, this should be done via configuration  for eg. `spring.boot.admin.module.liquibase.enabled`? 

I'll try to work on it and contribute.

**Comment by joshiste** [comment]
@ahmednasir91 with 32e1d9ba25635940cf4c333a26cf6b56686b6952 the checks for flyway/liquibase are made lazily and should hit your endpoints way less often.
Imho this reduces the need to disable core modules to almost zero. Can I close this issue, what do you think?

**Comment by ahmednasir91** [comment]
Sure thanks for the update.
