### ISSUE TITLE
Session-list detail page 'Created At' and 'Last Accessed At' show incorrectly with spring 2.24

### ISSUE THREAD

**Issue by matejbludsky** [codecentric/spring-boot-admin#3165]
## Spring Boot Admin Server information

- **Version**:
  3.2.1

- **Spring Boot version**:
  3.2.1

- **Configured Security**:
basic auth

- **Webflux or Servlet application**:
servlet
## Client information
2.2.4
- **Spring Boot versions**:
2.2.4

- **Used discovery mechanism**:
self registration

- **Webflux or Servlet application**:
servlet application 

## Description
When using spring version 2.24 with spring boot admin client 2.24 the sessions page list is displaying session details incorrectly, this is due to the actuator endpoint providing the Created At and Last Accessed At fields in seconds and not in millis.
This can be corrected by editing the class of index.vue in the server-ui component with 

```vue
class Session {
  constructor({ creationTime, lastAccessedTime, ...session }) {
    Object.assign(this, session);
    this.creationTime = moment(creationTime * 1000);
    this.lastAccessedTime = moment(lastAccessedTime * 1000);
  }
}
``` 
The 
    this.creationTime = moment(creationTime * 1000);
    this.lastAccessedTime = moment(lastAccessedTime * 1000);
does correct the issue and then it will display correctly. 

Actuator response 
```json
  "sessions": [
    {
      "id": "185cbd24-65de-489e-993e-55502bdab683",
      "attributeNames": [
        "__mock_SSO_header_value",
        "org.grails.FLASH_SCOPE",
        "javamelody.userAgent",
        "javamelody.remoteAddr",
        "javamelody.country",
        "SPRING_SECURITY_CONTEXT",
        "javamelody.remoteUser"
      ],
      "creationTime": 1707945854.340000000,
      "lastAccessedTime": 1707945913.122000000,
      "maxInactiveInterval": 1800,
      "expired": false
    }
  ]
}
``` 

This seems to be an incompatibility issue, attached is screenshot also. 

<img width="534" alt="Screenshot 2024-02-14 at 3 20 59 PM" src="https://github.com/codecentric/spring-boot-admin/assets/24680409/be668b19-e75b-4aaf-abcf-021f6fb59c9e">

**Comment by erikpetzold** [comment]
Hi @matejbludsky 

probably you changed your jackson config how to write dates in json.

I created a new app with spring boot 2.2.4 and no other config, so just using the default and the response of the actuator looks like this:

<img width="759" alt="grafik" src="https://github.com/codecentric/spring-boot-admin/assets/16555444/59e82891-3ea9-4b6e-a52c-45e5e187b70c">

so the date is in ISO Format by default.

If you wish to adjust the date format for your own rest endpoints, please use a separate jackson config and do not override the behaviour of the actuator endpoints. Spring Boot Admin relies on the default format.
In Spring Boot 3 this is supported by the framework as Spring Boot 3 explicitly creates an own jackson config for actuators, in Spring Boot 2 you have to keep an eye on that.

**Comment by erikpetzold** [comment]
Closing this issue, if you have more problems feel free to open a new issue.
