### ISSUE TITLE
not work with HTTPS

### ISSUE THREAD

**Issue by liangchouzhou** [codecentric/spring-boot-admin#318]
API gateway (spring cloud zuul) use HTTPS, other service uses HTTP.

spring boot admin communicates with HTTP correctly, but it tries to access API gateway via HTTP.

how to let spring boot admin communicate with API gateway via HTTPS?

thanks.

**Comment by joshiste** [comment]
The ui uses relative URLs.
So you need to serve the ui via HTTPS to make HTTPS zuul requests.

**Comment by liangchouzhou** [comment]
@joshiste
can you help me how to config to serve the ui via HTTPS?

**Comment by joshiste** [comment]
Since it's an ordinary spring boot application, have a look at the spring boot reference guide.

**Comment by liangchouzhou** [comment]
@joshiste 
my case is that only API gateway is HTTPS, other services are HTTP.
can sprint boot admin support this?

**Comment by jakobjoachim** [comment]
I'm having a similar issue, we are hosting our spring applications in containers but are not in charge of the "gateway service" that uses SSL to communicate to the world. As such we have no good way of managing SSL certificates required for using SBA with https. All our other applications communicate with each other over HTTP and we would have hoped to do the same with SBA. Is there any way to get SBA to act like its using https in the hrefs we have configured via "admin.ui.public-url".
