### ISSUE TITLE
How to config admin server if Spring boot client application enabled basic authentication?

### ISSUE THREAD

**Issue by grissomsh** [codecentric/spring-boot-admin#319]
If Spring boot client enabled basic authentication via:

security.basic.enabled=true
management.security.enabled=true
security.user.name=admin
security.user.password=****

So how could spring boot admin to pull infor from client management port? Thanks.

**Comment by joshiste** [comment]
Please see http://codecentric.github.io/spring-boot-admin/1.4.3/#securing-spring-boot-admin
