### ISSUE TITLE
Make the StatusUpdater easier to extend

### ISSUE THREAD

**Issue by dilbertside** [codecentric/spring-boot-admin#321]
Hi,

It is related to SO question [Redefining Mail notifications template for Spring Boot Admin](http://stackoverflow.com/questions/40463789/redefining-mail-notifications-template-for-spring-boot-admin)

Before proposing a PR, I would like to investigate its relevance, in that effect I tried to extend StatusUpdater to modify the `restTemplate.getForEntity(application.getHealthUrl())`

I find difficult to extend it without copying the whole code as 

- `queryStatus` method is private and _maybe_ only that method would need to be modified (anyway `updateStatus` is public)
- `ApplicationStore store` is private and no getter, why not protected?
- `RestTemplate restTemplate` is private and no getter, why not protected?
- `ApplicationEventPublisher publisher` is private and no getter, why not protected?
- `long statusLifetime` is private and no getter, why not protected?

AdminServerWebConfiguration let us redefine StatusUpdater bean by using @ConditionalOnMissingBean but the class is difficult to extend.
Could we modify its signature?

**Comment by joshiste** [comment]
I made `queryStatus()` protected and added a public getter for `statusLifetime`.
Since I consider field names a implementation detail I left them private. But it should be no problem to intercept the values for  `publisher`, `store` and `restTemplate` in the constructor / setter.

**Comment by dilbertside** [comment]
I did manage to get something like (after redefining bean):
```
spring.boot.admin.notify.mail.subject="#{application.name} #{indicator[0]?:''} (#{application.id}) is #{to.status}"
spring.boot.admin.notify.mail.text="#{application.name} (#{application.id})\nstatus changed from #{from.status} to #{to.status}#{health[0] != null ? ('\n\n'+ indicator[0] + ' health indicator is ' + health[0] ) : ''}\n\n#{application.healthUrl}"
```
Interested by a PR?

**Comment by joshiste** [comment]
Do you have sample output?
Having more information in the notifications looks like a good thing. PRs are always welcome.

**Comment by dilbertside** [comment]
Yes I do. 

For above SPEL and an IvmsHealthIndicator which role is just pinging a remote machine.

####  UP to DOWN email
```
Date: Wed, 9 Nov 2016 10:22:34 +0700 (WIB)
From: IT@acme.com
To: dbs@acme.com
Message-ID: <1964353434.2.1478661754045@inno.acme.com>
Subject: "admin-console ivms (ac97ae34) is DOWN";
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

"admin-console (ac97ae34)
status changed from UP to DOWN

ivms health indicator is DOWN {output=PING 192.168.23.140 (192.168.23.140) 56(84) bytes of data.

--- 192.168.23.140 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

}

http://inno.acme.com:7979/mgmt/health";
```

#### DOWN to UP email

```
Date: Wed, 9 Nov 2016 10:23:24 +0700 (WIB)
From: IT@acme.com
To: dbs@acme.com
Message-ID: <1837897579.3.1478661804043@inno.acme.com>
Subject: "admin-console ivms (ac97ae34) is UP";
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

"admin-console (ac97ae34)
status changed from DOWN to UP

ivms health indicator is UP {output=PING 192.168.24.140 (192.168.24.140) 56(84) bytes of data.
64 bytes from 192.168.24.140: icmp_seq=1 ttl=60 time=1.68 ms

--- 192.168.24.140 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.688/1.688/1.688/0.000 ms
}

http://inno.acme.com:7979/mgmt/health";

```

It may not work in all scenario specifically the secured one
If health endpoint is accessed in a non authenticated way, it returns simple status message UP or DOWN. If accessed through authenticated way, there will be indicators data available.

Currently in SBA 2 ways are used to access /mgmt/health

- http://localhost:7979/api/applications/ac97ae34/health (zuul)
- http://localhost:7979/mgmt/health

In the second bullet the basic authentication is not currently applied if security is set.

Will need to make some test with following settings such as
```
management.security.enabled=true
security.basic.enabled=true
security.user.name=admin
security.user.password=admin
```

**Comment by dilbertside** [comment]
Guess need to open a new ticket?

**Comment by joshiste** [comment]
> Guess need to open a new ticket?

would be better
