### ISSUE TITLE
Based on nacos monitoring, the service has a content-path path, resulting in the failure to access the correct address.

### ISSUE THREAD

**Issue by JavaLionLi** [codecentric/spring-boot-admin#3220]
## Spring Boot Admin Server information

- **Version**:
  
3.2.2
- **Spring Boot version**:
  
3.2.3
- **Configured Security**:
  

- **Webflux or Servlet application**:
  

## Client information

- **Spring Boot versions**:
  
3.2.3
- **Used discovery mechanism**:
  

- **Webflux or Servlet application**:
  

## Description

The spring-boot-admin-server discovers and monitors the service based on nacos. nacos can only obtain the ip and port of the service. In fact, the service also has the corresponding path content-path, which leads to the 404 of the monitoring service. No way has been found to solve this problem. I hope the author can help me think of some way.

Client yml
![image](https://github.com/codecentric/spring-boot-admin/assets/31852897/03b8b28c-c1e5-4586-a8b3-706cc4263159)

Path should be accessed
http://localhost:8800/easy-retry/actuator

Actual Access Path
http://localhost:8800/actuator

**Comment by hzpz** [comment]
As you already figured out: If you set the servlet context-path you will also implicitly change the management context-path (unless you have a separate management port configured).

Spring Boot Admin uses instance metadata to discover things like the management port and context-path (see section "Converting ServiceInstances" in [our documentation](https://docs.spring-boot-admin.com/current/server.html)). To make your setup work, you need to set `management.context-path` in your service's metadata:

```
spring:
  cloud:
    nacos:
      discovery:
        metadata:
          management.context-path: /easy-entry/actuator
```

Please let me know if that helps.

**Comment by JavaLionLi** [comment]
thinks
