### ISSUE TITLE
Documentation 404.

### ISSUE THREAD

**Issue by VladislavBakshanskij** [codecentric/spring-boot-admin#3253]
## Spring Boot Admin Server information

- **Version**: 3.2.2

## Description
Current documentation link return 404 https://docs.spring-boot-admin.com/current/

**Comment by erikpetzold** [comment]
seems there was an issue when publihing the docs for 3.2.3, we will have a look

here are the docs for the previous version: http://docs.spring-boot-admin.com/3.2.2/

**Comment by SteKoe** [comment]
We have just fixed uploaded the current docs for 3.2.3.
