### ISSUE TITLE
Application shows as DOWN because of different context-path

### ISSUE THREAD

**Issue by triberraar** [codecentric/spring-boot-admin#327]
Hej,
I am running the admin ui and several other spring clouds servers (all running as seperate instances):
Discovery through Eureka
Config server
Gateway through Zuul
But my config server shows up as down even though i know it is up. I think it is because its context path is set up to point to /admin so the health endpoint is under /admin/health. Is there some way to get the admin console to know this?
Thanks

**Comment by joshiste** [comment]
1) Did you check that the health endpoint responds with `UP`?

2) When using eureka the health checks are made using the healthCheckUrl from the eureka. So please make sure you configured your eurka client correctly. 
In the Spring Cloud Netflix documentation there is a note that you need to configure the healthCheckUrl when you have a custom `management.context-path` .
See http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_status_page_and_health_indicator
