### ISSUE TITLE
New UI in 3.x??

### ISSUE THREAD

**Issue by Subrhamanya** [codecentric/spring-boot-admin#3302]
Recently I uplifted my code base from spring 2.7.x to 3.2.x and so spring boot admin. But it seems I am completly getting new UI in spring boot admin 3.x. Is there any way I can still use 2.7.x UI along with 3.2.x spring boot admin??

3.x UI
![image](https://github.com/codecentric/spring-boot-admin/assets/36793516/b1a69563-05f4-4131-bb5f-9d63fcbc483a)

2.7.x UI
![image](https://github.com/codecentric/spring-boot-admin/assets/36793516/0e4aef8f-77c3-4c67-9d90-01993211d982)

**Comment by SteKoe** [comment]
Hi @Subrhamanya,

that is totally right: when we switched to Spring Boot 3 in early 2023 we also update the frontend to Vue 3 :) 
So no, there is no option to switch back to the previous UI. Is there something you miss in the new UI that lets you wish to go back?

Regards,
SteKoe

**Comment by Subrhamanya** [comment]
Yeah the color scheme (green), the UI of how table and it's data is shown, filter UI almost everything was superb in sprint boot 2.7.x when compared to 3.x...

**Comment by SteKoe** [comment]
Hey @Subrhamanya,

we switched to TailwindCSS in Spring Boot Admin 3 and removed all dependencies to Bootstrap. To customize the colors of the UI, we provide some configuration properties (see https://docs.spring-boot-admin.com/current/customize_ui.html#customizing-colors). 

If you have particular features that you miss or bugs you find, feel free to open a specific issue / detailed feature request.

Regards!

**Comment by Subrhamanya** [comment]
@SteKoe the above url throws 404 error.
