### ISSUE TITLE
"spring.boot.admin.ui.poll-timer.logfile" is broken in version 3.2.3 

### ISSUE THREAD

**Issue by p4pramod** [codecentric/spring-boot-admin#3306]
## Spring Boot Admin Server information

- **Version**:
3.2.3  

- **Spring Boot version**:
3.1.9

- **Configured Security**:
NA

- **Webflux or Servlet application**:
NA

## Client information

- **Spring Boot versions**:
NA

- **Used discovery mechanism**:
  Eureka

- **Webflux or Servlet application**:
na

## Description
The configuration "spring.boot.admin.ui.poll-timer.logfile" is not honoured in 3.2.3 version. However version 3.2.2 is working correctly

**Comment by SteKoe** [comment]
Hi @p4pramod,

I have just tested 3.2.2 and 3.2.3 which both work as expected. Are you sure that the configuration is correctly set and available in the frontend? Can you please check in your browser, what value in `sba-settings.js` is listed? The file is generated and then served by Spring Boot Admin Server. 

Regards
SteKoe

**Comment by p4pramod** [comment]
Hi .. 
Seems after going back to 3.2.3 from 3.2.2 things are working. 
Don't know how it did not work in the first place?
Thanks,
Pramod

**Comment by SteKoe** [comment]
Good question, but I’m glad it works now :)
