### ISSUE TITLE
Allow easier customization of the registration info

### ISSUE THREAD

**Issue by rfelgent** [codecentric/spring-boot-admin#331]
Hello folks,

I need to customize the client's register logic against SBAP. My machines are reachable by a "public" and "private" IP address. The private IP has no restrictions considering ports whereas the public IP has only port 80&443 for connection establishment.

Unfortunately, clients find the public IP/hostname and not the private one. 
Furthermore, the current implementation of client's hostname calculation used by SBAP for connecting to the client's actuator endpoints is not easy customizable.
Currently, my workaround is to manipulate instance de.codecentric.boot.admin.model.Application before it is handed to the RegistryController in SBAP server.

I was thinking of a "OnMissingBean" conditional for making the customization configurable at the SPAB client side (the moment clients register to SBAP server). But this is not possible with the current implementation.

If this feature request is useful, I would do a merge request for it.

**Comment by joshiste** [comment]
Currently you can override the `createApplication()` method in `ApplicationRegistrator`.
But adding an `ApplicationFactory` class for extracting this logic into a seperate class sounds reasonable. When doing this we should consider to remove the event listener and some noise from `AdminClientProperties`

PRs are always appreciated :smile:

**Comment by rfelgent** [comment]
Hi @joshiste ,

I tried to register my bean of ApplicationRegistrator in an earlier attempt.
When I looked into the code, I found it not the right way to go, as there is too much config logic and dependencies to other beans. That in turn would force me to duplicate (internal) code.

`      /**
	 * Task that registers the application at the spring-boot-admin application.
	 */
	@Bean
	@ConditionalOnMissingBean
	public ApplicationRegistrator registrator() {
		RestTemplateBuilder builder = restTemplBuilder
				.messageConverters(new MappingJackson2HttpMessageConverter())
				.requestFactory(SimpleClientHttpRequestFactory.class);
		if (admin.getUsername() != null) {
			builder = builder.basicAuthorization(admin.getUsername(), admin.getPassword());
		}
		return new ApplicationRegistrator(builder.build(), admin, client);
	}`

What exactly do you mean by: "...to remove the event listener and some noise from AdminClientProperties..."

I will try to make a PR :)
