### ISSUE TITLE
SpringBootAdminClientAutoConfiguration required a single bean, but 2 were found

### ISSUE THREAD

**Issue by ffroliva** [codecentric/spring-boot-admin#3312]
## Spring Boot Admin Server information

- **Version**:
  3.1.0

- **Spring Boot version**:
3.1.0

- **Configured Security**:
basic auth

- **Webflux or Servlet application**:
servlet applicatoin

## Client information

- **Spring Boot versions**:
3.1.0

- **Used discovery mechanism**:
self-registration

- **Webflux or Servlet application**:
servlet

## Description

I need to customize `RegistrationClient` and for that, I have created a Configuration classes as follows:

```java
import de.codecentric.boot.admin.client.config.ClientProperties;
import de.codecentric.boot.admin.client.registration.BlockingRegistrationClient;
import de.codecentric.boot.admin.client.registration.RegistrationClient;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.ssl.NoSuchSslBundleException;
import org.springframework.boot.ssl.SslBundle;
import org.springframework.boot.ssl.SslBundles;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.boot.web.client.RestTemplateCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Primary;
import org.springframework.web.client.RestTemplate;

@Slf4j
@Configuration
@Import({ClientProperties.class})
public class RestTemplateConfiguration {

    public static final String MY_SSL_BUNDLE = "my_ssl_bundle";


    RestTemplateBuilder customRestTemplateBuilder(RestTemplateBuilder restTemplateBuilder, SslBundles sslBundles) {
        if (sslBundles != null) {
            try {
                SslBundle sslBundle = sslBundles.getBundle(MY_SSL_BUNDLE);
                restTemplateBuilder.setSslBundle(sslBundle);
                log.info("Found 'spring.ssl.bundle.jks.my_ssl_bundle.*' bundle, setting it to RestTemplateBuilder");
            } catch (NoSuchSslBundleException ex) {
                log.info("SSL not enabled. 'spring.ssl.bundle.jks.my_ssl_bundle.*' not provided on the configurations.");
                log.info("Creating RestTemplate with no SSL configurations.");
            }
        }
        return restTemplateBuilder;
    }

    @Bean
    @Primary
    public RegistrationClient registrationClient(@Qualifier("de.codecentric.boot.admin.client.config.ClientProperties") ClientProperties client, SslBundles sslBundles) {
        RestTemplateBuilder builder = (new RestTemplateBuilder(new RestTemplateCustomizer[0])).setConnectTimeout(client.getConnectTimeout());
        builder.setReadTimeout(client.getReadTimeout());
        if (client.getUsername() != null && client.getPassword() != null) {
            builder = builder.basicAuthentication(client.getUsername(), client.getPassword());
        }

        RestTemplate build = customRestTemplateBuilder(builder, sslBundles).build();
        return new BlockingRegistrationClient(build);
    }


    /**
     * @return a new customized ResTemplate instance
     */
    @Bean
    public RestTemplate restTemplate(RestTemplateBuilder restTemplateBuilder, SslBundles sslBundles) {
        return customRestTemplateBuilder(restTemplateBuilder, sslBundles).build();
    }
}
```

When I start the application I get the following error:

Parameter 1 of method registrator in de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfiguration required a single bean, but 2 were found:
	- de.codecentric.boot.admin.client.config.ClientProperties: defined in unknown location
	- spring.boot.admin.client-de.codecentric.boot.admin.client.config.ClientProperties: defined in unknown location

**Comment by hzpz** [comment]
Hey @ffroliva,
this is a Spring related issue (not Spring Boot Admin). Spring Boot Admin already provides an instance of `ClientProperties` (see `@EnableConfigurationProperties` in `SpringBootAdminClientAutoConfiguration`). If you `@Import` `ClientProperties` again, there will be another instance of this class and this is what the error message is about.

Just remove the line `@Import({ClientProperties.class})` and it should work. Please let us know if that helps.

**Comment by hzpz** [comment]
Hey @ffroliva,
right now it seems that this is the only way to customize the `RegistrationClient`. We are considering changing our auto-configuration so that it'll be easier to customize and/or implement a property to customize the SSL bundle.

**Comment by ffroliva** [comment]
Thank you @Timo

Looking forward to this enhancement.

BTW, spring boot admin is a great project. Well done!

You may close this thread if you understand so.

Regards,

Flavio



Em sex., 19 de abr. de 2024 às 12:51, Timo ***@***.***>
escreveu:

**Comment by hzpz** [comment]
Thanks! We will mention this issue if we implement any of the enhancements.
