### ISSUE TITLE
Unable to access logging and JMX endpoints

### ISSUE THREAD

**Issue by bmw1800cc** [codecentric/spring-boot-admin#337]
I am trying to use spring boot admin and I am able to access all other modules but logging and JMX. I have included jolokia as a dependency in my microservices and I am able to reach the jolokia endpoint directly from my browser. Also, I have included the logback.xml as mentioned in the reference documentation.

**Comment by joshiste** [comment]
Is there any error shown?

**Comment by bmw1800cc** [comment]
Yes, here is what i see. 

Error:
{
  "timestamp": 1479413360400,
  "status": 404,
  "error": "Not Found",
  "message": "No message available",
  "path": "/api/applications/18963283/jolokia/"
}

And this is from the jolokia endpoint on my microservice

{"request":{"type":"version"},"value":{"agent":"1.2.3","protocol":"7.2","config":{"agentId":"10.7.152.40-42211-38b0e2a7-servlet","agentType":"servlet"},"info":{"product":"tomcat","vendor":"Apache","version":"8.0.23"}},"timestamp":1479413247,"status":200}

**Comment by joshiste** [comment]
Is the endpoint `/api/applications/18963283/jolokia/` listed in the `/mapping` endpoint of your spring boot admin server? Is any error in sba server log?

**Comment by joshiste** [comment]
Can you post the response of the `/routes` endpoint from your sba server?

**Comment by bmw1800cc** [comment]
`
<Map></api/applications/18963283/health/**>http://acbc32d3a33d:8085/health<//api/applications/18963283/health/**></api/applications/18963283/env/**>http://acbc32d3a33d:8085/env<//api/applications/18963283/env/**></api/applications/18963283/metrics/**>http://acbc32d3a33d:8085/metrics<//api/applications/18963283/metrics/**></api/applications/18963283/trace/**>http://acbc32d3a33d:8085/trace<//api/applications/18963283/trace/**></api/applications/18963283/dump/**>http://acbc32d3a33d:8085/dump<//api/applications/18963283/dump/**></api/applications/18963283/info/**>http://acbc32d3a33d:8085/info<//api/applications/18963283/info/**></api/applications/18963283/configprops/**>http://acbc32d3a33d:8085/configprops<//api/applications/18963283/configprops/**></api/applications/18963283/logfile/**>http://acbc32d3a33d:8085/logfile<//api/applications/18963283/logfile/**></api/applications/18963283/logging/**>http://acbc32d3a33d:8085/logging<//api/applications/18963283/logging/**></api/applications/18963283/refresh/**>http://acbc32d3a33d:8085/refresh<//api/applications/18963283/refresh/**></api/applications/18963283/heapdump/**>http://acbc32d3a33d:8085/heapdump<//api/applications/18963283/heapdump/**></api/applications/18963283/hystrix.stream/**>http://acbc32d3a33d:8085/hystrix.stream<//api/applications/18963283/hystrix.stream/**></api/applications/18963283/turbine.stream/**>http://acbc32d3a33d:8085/turbine.stream<//api/applications/18963283/turbine.stream/**></api/applications/cb88b2ed/health/**>http://acbc32d3a33d:8761/health<//api/applications/cb88b2ed/health/**></api/applications/cb88b2ed/env/**>http://acbc32d3a33d:8761/env<//api/applications/cb88b2ed/env/**></api/applications/cb88b2ed/metrics/**>http://acbc32d3a33d:8761/metrics<//api/applications/cb88b2ed/metrics/**></api/applications/cb88b2ed/trace/**>http://acbc32d3a33d:8761/trace<//api/applications/cb88b2ed/trace/**></api/applications/cb88b2ed/dump/**>http://acbc32d3a33d:8761/dump<//api/applications/cb88b2ed/dump/**></api/applications/cb88b2ed/info/**>http://acbc32d3a33d:8761/info<//api/applications/cb88b2ed/info/**></api/applications/cb88b2ed/configprops/**>http://acbc32d3a33d:8761/configprops<//api/applications/cb88b2ed/configprops/**></api/applications/cb88b2ed/logfile/**>http://acbc32d3a33d:8761/logfile<//api/applications/cb88b2ed/logfile/**></api/applications/cb88b2ed/logging/**>http://acbc32d3a33d:8761/logging<//api/applications/cb88b2ed/logging/**></api/applications/cb88b2ed/refresh/**>http://acbc32d3a33d:8761/refresh<//api/applications/cb88b2ed/refresh/**></api/applications/cb88b2ed/heapdump/**>http://acbc32d3a33d:8761/heapdump<//api/applications/cb88b2ed/heapdump/**></api/applications/cb88b2ed/hystrix.stream/**>http://acbc32d3a33d:8761/hystrix.stream<//api/applications/cb88b2ed/hystrix.stream/**></api/applications/cb88b2ed/turbine.stream/**>http://acbc32d3a33d:8761/turbine.stream<//api/applications/cb88b2ed/turbine.stream/**></api/applications/4a9bd912/health/**>http://acbc32d3a33d:8888/health<//api/applications/4a9bd912/health/**></api/applications/4a9bd912/env/**>http://acbc32d3a33d:8888/env<//api/applications/4a9bd912/env/**></api/applications/4a9bd912/metrics/**>http://acbc32d3a33d:8888/metrics<//api/applications/4a9bd912/metrics/**></api/applications/4a9bd912/trace/**>http://acbc32d3a33d:8888/trace<//api/applications/4a9bd912/trace/**></api/applications/4a9bd912/dump/**>http://acbc32d3a33d:8888/dump<//api/applications/4a9bd912/dump/**></api/applications/4a9bd912/info/**>http://acbc32d3a33d:8888/info<//api/applications/4a9bd912/info/**></api/applications/4a9bd912/configprops/**>http://acbc32d3a33d:8888/configprops<//api/applications/4a9bd912/configprops/**></api/applications/4a9bd912/logfile/**>http://acbc32d3a33d:8888/logfile<//api/applications/4a9bd912/logfile/**></api/applications/4a9bd912/logging/**>http://acbc32d3a33d:8888/logging<//api/applications/4a9bd912/logging/**></api/applications/4a9bd912/refresh/**>http://acbc32d3a33d:8888/refresh<//api/applications/4a9bd912/refresh/**></api/applications/4a9bd912/heapdump/**>http://acbc32d3a33d:8888/heapdump<//api/applications/4a9bd912/heapdump/**></api/applications/4a9bd912/hystrix.stream/**>http://acbc32d3a33d:8888/hystrix.stream<//api/applications/4a9bd912/hystrix.stream/**></api/applications/4a9bd912/turbine.stream/**>http://acbc32d3a33d:8888/turbine.stream<//api/applications/4a9bd912/turbine.stream/**></Map>`

**Comment by bmw1800cc** [comment]
i see this at startup

`Mapped "{[/jolokia/**],methods=[],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.actuate.endpoint.mvc.JolokiaMvcEndpoint.handle(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception`

**Comment by joshiste** [comment]
The logstatement is from the sba's own jolokia endpoint.

But looking at your routes (weird malformed xml :astonished:) I guess you have set the `spring.boot.admin.routes.endpoints` property. Please look through the list carefully I guess you accidentally removed jolokia from it.
