### ISSUE TITLE
Ask for Java 21 support for de.codecentric : spring-boot-admin-dependencies

### ISSUE THREAD

**Issue by Swarn10** [codecentric/spring-boot-admin#3415]
### If there are plans already to support Java 21, is there an ETA for the same?

**Comment by erikpetzold** [comment]
Hi @Swarn10 

the baseline for Spring Boot Admin 3 is java 17, like for Spring Boot 3 itself. Nevertheless it should be possible to use the Spring Boot Admin dependencies in a java 21 project (same as Spring Boot).
We are currently not actively testing the compatability in a pipeline or something like this.

**Comment by StefanHufschmidt** [comment]
Our Spring Boot Admin as well as the client dependencies of our other Spring Boot services are running with Java 21 for a while now. Seems to work like a charm so far.
