### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR during SSE/EventSource communication

### ISSUE THREAD

**Issue by frgaume** [codecentric/spring-boot-admin#3426]
## Spring Boot Admin Server information

- **Version**:
3.2.3

- **Spring Boot version**:
3.2.6

- **Configured Security**:
none

- **Webflux or Servlet application**:
N/A

## Client information
N/A (UI console)

## Description

The /applications event source can't push data from the server to the browser's event source : 
GET https://<sba_public-url>/admin/applications net::ERR_HTTP2_PROTOCOL_ERROR 200 (OK)
(we see à 200 here but it failed actually)

My Spring Boot Admin (SBA) Server is behind an AWS ALB which acts as a reverse proxy.
The SBA is running inside a AWS Fargate Container, with AWS Service Connect enabled (meaning there is also an Envoy proxy intercepting the flow between the ALB and the SBA.

I enabled the http2 protocol everywhere I could, i.e. in the ALB and the SBA's Target Group.

But it still does not work (the UI pops up an error message "connection to server failed")

Extract from the browser's chrome tools: 

Request URL:
https://<sba_public-url>/admin/applications
Request Method:
GET
Status Code:
200 OK
Remote Address:
1xxx:443
Referrer Policy:
strict-origin-when-cross-origin

Response Headers:

Content-Type:
text/event-stream;charset=UTF-8
Date:
Tue, 04 Jun 2024 09:25:30 GMT
Server:
envoy

X-Envoy-Upstream-Service-Time:
1

Request Headers:
:authority:
<sba_public-url>
:method:
GET
:path:
/admin/applications
:scheme:
https
Accept:
text/event-stream
Accept-Encoding:
gzip, deflate, br, zstd
Accept-Language:
fr-FR,fr;q=0.9
Cache-Control:
no-cache
Referer:
https://<sba_public-url>/admin/applications
Sec-Ch-Ua:
"Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-origin
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by erikpetzold** [comment]
Hi @frgaume 

seems like this is a problem with the webserver running in front of your application. Just searching the error message in the internet I found a lot of possible issues (wrong content length header, incomplete response because of timeout or full disk, ...). But nothing that may be related to Spring Boot Admin itself.

As the call is made with https and you say you have configured the server to use https, the SBA config seems correct. Must be something with your ALB/envoy config. I would recomment to ask for help somewhere else, e.g. aws forums.

**Comment by frgaume** [comment]
Thank you Erik for your time. I'll look into the AWS components indeed, especially the envoy between the SBA and the ALB. I think the issue is not far from there.
