### ISSUE TITLE
Multiple applications running on one tomcat instance, change spring.boot.admin.client.service-url programatically

### ISSUE THREAD

**Issue by Creedzy** [codecentric/spring-boot-admin#344]
At the moment I am running 3 applications on one tomcat instance in docker and they share external configuration settings. Thanks to Spring Boot's resource handling any variable is overwritten by the last file with the highest precedence. As all applications have different endpoints lets say 192.168.99.100/Home ,192.168.99.100/Mobile and 192.168.99.100/Jumbotronics the spring.boot.admin.client.service-url is being overwritten by the last value(192.168.99.100/Jumbotronics) so the previous apps will get registered with the same url as the last app (or overwritten, dont know what happens if multiple apps post the same settings). Do you know of a way to plug into the AdminClientProperties in runtime and add different urls for each app.

**Comment by joshiste** [comment]
I guess each application runs it's own applicationContext ? Each applicationContext  should run an independent spring boot admin client.
**Each context must not see the configuration of the others**. One way to achieve this would be using a different spring profile for each app and using `application-<profile>.properties`. Or right away independent config files.

I don't think this is a sba issue - how do you deal with other application specific settings? Don't you have the same problem there?

**Comment by joshiste** [comment]
With the upcoming 1.4.5 you can provide your own `ApplicationFactory` to change the way the serviceUrl is constructed.
