### ISSUE TITLE
Application status would not refresh.

### ISSUE THREAD

**Issue by heymysweetheart** [codecentric/spring-boot-admin#345]
Hi sba team,

During the start process of spring boot admin, the clients form eureka tried to register to the admin, and before the admin started, status of these clients remained `UNKNOW` or `DOWN`, after the admin started I think this status in the admin index page would be refreshed. But it was not. Unless I removed the registered application, the right status could not be refreshed. I am using 
**`sba: 1.4.2, spring boot: 1.4.1.RELEASE.`**

Also I am confused about these configs:
```
spring:
  boot:
    admin:
      monitor:
        period: 10000
        status-lifetime: 10000
```
The office docs:
![image](https://cloud.githubusercontent.com/assets/9413173/20659832/082022e6-b581-11e6-85fd-97dadc7c6d2a.png)

My understanding of the default config `spring.boot.admin.monitor.period` (whose default value is 10ms, 10.000ms, not 10000ms?) is the application's status will be refreshed every 10 milliseconds. Am I right or is there something wrong? Thanks.

**Question:**
- If what I think above is right, the fact is the application status was not refreshed. This might be a bug.
- If this was not a bug, I really want to know how to modify the configuration to refresh the status instead of unregistering web application first.

![image](https://cloud.githubusercontent.com/assets/9413173/20659736/7feb6e12-b580-11e6-89b6-170ed395ca81.png)

Best regards,
yuliang

**Comment by joshiste** [comment]
>... is the application's status will be refreshed every 10 milliseconds. Am I right or is there something wrong?

The default value is 10000ms. The point is not a decimal point but a thousand sepearator. Sorry for the misunderstanding. I'll fix the docs on this.

>... I really want to know how to modify the configuration to refresh the status instead of unregistering web application first.

I guess you are using Eureka or another DiscoveryClient implementation? Spring Boot Admin removes all applications which aren't listed in the service registry anymore automatically (see [ApplicationDiscoveryListener](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/discovery/ApplicationDiscoveryListener.java#L80))
Refreshing the status and syncing applications with the service registry is independent from each other. You could ship your own `ApplicationDiscoveryListener` implementation and prohibit the removal of the stale applications or use the `StatusUpdater` to do a status check before removal.
