### ISSUE TITLE
Use all available space for Hystrix view

### ISSUE THREAD

**Issue by steve-oakey** [codecentric/spring-boot-admin#348]
The root container is using class `container`. Using `container-fluid` would provide a much better view since a large number of services wouldn't be confined to the 1024px in the middle of the screen.

**Comment by joshiste** [comment]
If there are too many graphs for one row the wrap around, don't they?

**Comment by steve-oakey** [comment]
They do, but if you compare it to the stock Hystrix Dashboard, it is easier
(maybe just in my opinon) to see a large number of graphs if they are
spread out horizontally rather than vertically. I just think it's better to
use the whole space rather than just a percentage of it in this case.

-Steve
