### ISSUE TITLE
Aggregate info on the server side

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#349]
Aggregating infos on the server side has following benefits:
 * we don't need to make 1 XHR per application from the UI resulting in bad performance when dealing with many applications. (Currently we have n+1 requests for the application list).
 * infos for the applications can be used in the notifications

**Comment by steve-oakey** [comment]
I assume you would you fetch the periodically like the health checks?
Fetching all info on demand would likely be quite slow.

**Comment by joshiste** [comment]
> Fetching all info on demand would likely be quite slow.

Yes. I guess that wouldn't solve the problem.

> I assume you would you fetch the periodically like the health checks?

I thought about fetching the infos when the status changes and not periodically. I guess most people have static infos that don't change over time without redeploying?
