### ISSUE TITLE
Help Wanted : Unable to view log file and heap dump

### ISSUE THREAD

**Issue by bmw1800cc** [codecentric/spring-boot-admin#350]
We are running the admin console and all other features work except logfile and heapdump. 

Here is the configuration which shows that all endpoints are included. 

Is there anything else that needs to be done to enable these options?

`
server:
  port: 8761
spring:
  boot:
    admin:
      api-path: api/applications
      hazelcast:
        enabled: false
      routes:
        endpoints:
          env,metrics,trace,dump,info,configprops,trace,logfile,logging,refresh,heapdump,hystrix.stream,turbine.stream,jolokia
  application:
    name: eurekaserver1
eureka:
  instance:
    prefer-ip-address: false
  dashboard:
    path: /dashboard
  client:
     serviceUrl:
       defaultZone: ${EUREKA_SERVERS}
  server:
     waitTimeInMsWhenSyncEmpty: 0
`

**Comment by joshiste** [comment]
For the heapdump your client applications must be at least spring boot 1.4 and serve the `/heapdump` endpoint which should be enabled by default.

For the logfile view the client must have the `/logfile` endpoint enabled. Which is disabled by default. Either you set `logging.file` or `endpoints.logfile.external-file` on your client. For more details please have a look in the spring boot reference guide.
