### ISSUE TITLE
How to extend the "scheduled tasks" view to execute a task if this is "possible"

### ISSUE THREAD

**Issue by ahoehma** [codecentric/spring-boot-admin#3518]
Hello,

In https://github.com/spring-projects/spring-boot/issues/17585#issuecomment-2236447954 we will find a prototype to enabled "POST" requests to the springboot actuator for scheduled tasks. If the extension is enabled each configured task could be startet from "outside".

I would be pretty cool to have a "run-now" button per task in the "scheduled tasks" view.

May this is nothing for the general version of sba ... if so then please share some ideas how to hook into the view, maybe here the sba framework can provide some extensions for thirdparty users of sba.

Thanks.
Andreas

**Comment by erikpetzold** [comment]
Hi @ahoehma ,

we aim to provide a useful UI for the actuator Endpoints, so if the actuator Endpoints support this then it would also fit into Spring Boot Admin.

But if I understand the last comments in the linked issue correctly, the triggering will bot be added to the actuator. So if ou add this feature manually, then you would also have to add tis feature to Spring Boot Admin yourself. If this is not standardized we cannot implement this as it may be different in every implementation.
Extending Spring Boot Admin is already possible, but you cannot hook into existing pges as far as I know. So you would have to create your own view where you could trigger this.

**Comment by ahoehma** [comment]
@erikpetzold  I got you and I agree.

This possibility to "POST" to a task-actutator-endpoint will not be part of springboot core ... it's just an extension (a nice one).

Can you please give me a little bit more hints about "how to extend such a view"?

Kind regards
Andreas

**Comment by erikpetzold** [comment]
As I said, you cannot extend existing views, but create a new one.

See the docs here: docs.spring-boot-admin.com/current/customize_ui.html
Or the sample here: https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-custom-ui

You will find the code of the existing page for scheduled tasks here: https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/scheduledtasks/index.vue

**Comment by SteKoe** [comment]
We're closing this issue. If you're still encountering problems, feel free to file a new one.
