### ISSUE TITLE
Health actuator Read timed out

### ISSUE THREAD

**Issue by dilbertside** [codecentric/spring-boot-admin#353]
Hi,

I'm facing a problem when an actuator is longer to query heath data as following

![health-sockettimeoutexception](https://cloud.githubusercontent.com/assets/2637724/20959170/1d2a1234-bc8c-11e6-96e5-d8bfbf0094f3.png)

There is no issues with SBA so far.

I was wondering how to increase the timeout so status will no show DOWN when it is expected to be a slow query.
My query time is above 30sec (NFT purposes) and I see in `de.codecentric.boot.admin.zuul.filters.route.SimpleHostRoutingFilter` `ZuulConstants.ZUUL_HOST_SOCKET_TIMEOUT_MILLIS` and `ZuulConstants.ZUUL_HOST_CONNECT_TIMEOUT_MILLIS`.

question is: 
are the timeout values configurable? 
if yes how?
If No will it be possible to externalize their values?

**Comment by joshiste** [comment]
IIRC you can set these with `zuul.host.connect-timeout-millis` or `zuul.host.socket-timeout-millis`.

But I don't think this long running health check is not very desirable.
Did you thought of doing the check itself periodically in a different thread and the indicator just returns the result form the last finished check? This way you get fast http responses and have a solution to throttle the checks in case the endpoint is hit very often.
