### ISSUE TITLE
Integrate feature-toggles

### ISSUE THREAD

**Issue by buzdin** [codecentric/spring-boot-admin#354]
Is feature toggle dashboard something you would consider as a plugin?

Some implementations
* http://ff4j.org/
* https://www.togglz.org/

You would need to see a list of toggles change its status and settings.

Just to start a discussion, not sure if there is a Spring Boot "native" way at the moment besides profiles and conditional beans, which is not possible to override in runtime (correct me if I am wrong). You have to select a feature toggling framework and integrate.

Thought that it might be a great addition to the tool.

**Comment by joshiste** [comment]
togglz as well as ff4j have their own administration consoles. So I refuse to implement that in SBA.

Showing informations from spring-cloud-commons `/features` can be integrated, but they are for informational purposes only.

**Comment by joshiste** [comment]
We can discuss adding arbitrary links to the top navbar of Spring Boot Admin by configuration.
