### ISSUE TITLE
How to ignore slack notifications from certain service instances

### ISSUE THREAD

**Issue by hotterd** [codecentric/spring-boot-admin#356]
According to docs, we can use `spring.boot.admin.notify.slack.ignore-changes` to specify which status transitions to ignore. This is great. However, sometimes while developing, we do not want to receive status from local service instances at all, i.e. status from services IP as 127.0.0.1 or localhost. Do we have a way to turn it off?

**Comment by joshiste** [comment]
Implement a [Notifier](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/notify/Notifier.java) wich delegates to the SlackNotifier bean and just throw away the unwanted status changes.

**Comment by hotterd** [comment]
@joshiste Thanks for the quick response.  I'm trying with following code:

```
public class FilteredNotifier implements Notifier {

  private final Notifier notifier;

  public FilteredNotifier(Notifier delegate) {
    this.notifier = delegate;
  }

  @Override
  public void notify(ClientApplicationEvent event) {
    String serviceUrl = event.getApplication().getServiceUrl();
    if (!serviceUrl.contains("127.0.0.1") && !serviceUrl.contains("localhost")) {
      notifier.notify(event);
    }
  }
}
```

```
@Configuration
public class SlackNotifierConfiguration {

  @Autowired
  private SlackNotifier notifier;

  @Bean
  public FilteredNotifier filteredNotifier() {
    return new FilteredNotifier(notifier);
  }
}
```

However, it leads to duplicate notifications. I assume the SlackNotifier was fired in addition to my custom delegation. How do I disable the original SlackNotifier? I tried to turn it off with `spring.boot.admin.notify.slack.enabled=false`, but it caused bean injection failure, since my custom implementation requires SlackNotifier Bean.  Or am I on the right direction?

**Comment by joshiste** [comment]
Annotating your `filteredNotifier` bean with `@Primary` should do it.
