### ISSUE TITLE
Add feature to manage multiple environments

### ISSUE THREAD

**Issue by dessens** [codecentric/spring-boot-admin#358]
Add a feature to manage multiple environments ie test, dev, prod

Url examples:

* hostname/test
* hostname/dev
* hostname/prod

**Comment by joshiste** [comment]
Do you mean to have separate application list views for each stage? 
Simply run a SBA server instance per stage. This way your SBA server gets staged and the same QA process as your other applications.

**Comment by dessens** [comment]
We're currently doing that, but when there are many environments it becomes rather costly to maintain a large amount of instances.

**Comment by joshiste** [comment]
What's costly about it? 

Memorizing the urls? Put a reverse proxy (with url rewriting) in front!
Deploying the applications? Automate it!

**Comment by dessens** [comment]
Ram, cpu etc. I know in most cases it's trivial, but starting a jvm for each instance can add up.

**Comment by joshiste** [comment]
Or run a single SBA server for multiple environments. Include a `info.env` property in the client applications so that the environment shows up in the application list and you can use the env as search string to filter the list.

**Comment by joshiste** [comment]
> Ram, cpu etc. I know in most cases it's trivial, but starting a jvm for each instance can add up.
Hardware is cheap today. Also we run our SBA server with `-Xmx256m` which is really not much in my opinion.
