### ISSUE TITLE
Export an aggregate service status for display elsewhere

### ISSUE THREAD

**Issue by lhanson** [codecentric/spring-boot-admin#360]
I'd like to be able to display an aggregate status on another site; for example, all services UP would be green, some services up YELLOW, no services up RED.

Is there a way to do this now, or would that be a new feature?

**Comment by joshiste** [comment]
Should be no problem to add your own controller and some template rendering stuff to achieve that.
You can use the `ApplicationRegistry` to obtain a `Application` instance and it's status.

**Comment by lhanson** [comment]
Great, thanks!
