### ISSUE TITLE
How to Exclude Dubbo Monitoring in Spring Boot Admin

### ISSUE THREAD

**Issue by stoneLee81** [codecentric/spring-boot-admin#3631]
I am using Dubbo in my Spring Boot web project and monitoring some parameters of the project through Spring Boot Admin. I would like to exclude Dubbo monitoring from boot admin. How can this be achieved?

**Comment by erikpetzold** [comment]
Hi @stoneLee81 ,
some more details on what you are seeing and what you want to achieve would be nice.

- What do you mean with monitoring some parameters? Are you referring to metrics here?
- What do you mean with exlcuding Dubbo? Do you want to exclude an application from being visible in Spring Boot Admin?

**Comment by erikpetzold** [comment]
If you want to disable specific metrics you can do that in your Spring Boot Application, see here: https://bootcamptoprod.com/spring-boot-3-disable-metrics/

**Comment by stoneLee81** [comment]
> https://bootcamptoprod.com/spring-boot-3-disable-metrics/



> Hi @stoneLee81 , some more details on what you are seeing and what you want to achieve would be nice.
> 
> * What do you mean with monitoring some parameters? Are you referring to metrics here?
> * What do you mean with exlcuding Dubbo? Do you want to exclude an application from being visible in Spring Boot Admin?

Spring Boot Admin is currently monitoring two ports in my project: 8030 is the web startup port for the project, and 30880 is for Dubbo. I want to remove the Dubbo port monitor from Admin monitoring.

<img width="495" alt="image" src="https://github.com/user-attachments/assets/e679bcd6-8ee4-4796-82f4-b396a5b99ac4">

**Comment by a386572631** [comment]
> Ok then how does spring boot admin know about these services? Do they register themselfes, do you use any discovery mechanism?

I also want to remove the Dubbo port monitor from Admin monitoring. And I don't want to see many offline service.
For example
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/33f24239-9aaa-4213-98e2-800af3adc9c0">

**Comment by erikpetzold** [comment]
@a386572631 as you did not provide any context and no answers to he questions we are not able to help you.

Maybe @stoneLee81 can share his solution as he closed the ticket.
