### ISSUE TITLE
is the name correct for property spring.boot.admin.client.url?

### ISSUE THREAD

**Issue by michaelisvy** [codecentric/spring-boot-admin#3639]
Hi,
when I am inside a Spring Boot Admin client and I want to specify the server url, I use this property inside application.properties:

`spring.boot.admin.client.url=http://localhost:8085`

Shouldn't this property be called `spring.boot.admin.server.url` instead? If I'm correct, it refers to the server url, not the client url.

Great thanks, and kudos for the great work on Spring Boot admin!

**Comment by erikpetzold** [comment]
Hi @michaelisvy 

this dependens on how you interpret the properties. Your way is comprehensible, but not the only one.
You can also think of the third segment as category, so these are all the properties that belong to the Spring Boot Admin Client configuration.
So either SpringBootAdmin - ClientUrl or SpringBootAdminClient - Url.

As there are already many existing installations and documentations, I think we are not going to change the name.

**Comment by michaelisvy** [comment]
sure, totally understood. Thanks for the clarification!
