### ISSUE TITLE
codecentric/spring-boot-admin docker issue mounting application.(properties|yml)

### ISSUE THREAD

**Issue by kevin-agysoft** [codecentric/spring-boot-admin#3648]
Good afternoon,

I am aware the following docker images do not include support and are not production ready.
https://hub.docker.com/r/codecentric/spring-boot-admin

I would like nonetheless report a bug.

The above link states:
> Configuration
> You can modify application properties by mounting custom properties or YAML file to /application.{yml,properties}.

This does not seem to be the case. Starting the application using docker will fail. It will complain either application.properties or application.yml is missing, even though they are properly mounted.

I have resolved this issue by mounting both files: application.properties and it's equivalent application.yml files.
Only then does the Spring boot admin application start properly in the docker container.

Cheers,

**Comment by SteKoe** [comment]
Hi @kevin-agysoft,

thanks for reporting the bug anyway! 

we have just pushed two images `3.2.3` and `3.3.3` to Docker hub. We changed the `spring.config.additional-location` property to `/usr/share/codecentric/conf/`. A default `application.yml` is shipped having set `server.port=8080`.

So when you run a container, you can now just use ```docker run -v .:/usr/share/codecentric/conf/ -p8080:8080 --rm codecentric/spring-boot-admin:3.3.3```.

Hope that fixes the general issue.

Regards,
SteKoe
