### ISSUE TITLE
Eureka discovered clients asking for passwords on certain ui pages.

### ISSUE THREAD

**Issue by yeta-io** [codecentric/spring-boot-admin#365]
Hi,

I have a eureka server and few clients registered with it. Each client has security starter + configuration in order to protect its endpoints.

```
security.user.name: user
security.user.password: pass
management.security.enabled: true
```

Clients are discovered successfully and displayed in admin ui, but when I enter into logs/metrics page it constantly asking me for password. It looks like admin can't forward credentials to protected endpoint.

Same client with the same configuration but registered to admin directly (using admin-client registration) has no such issue.

**Comment by joshiste** [comment]
By default the zuul proxy inside SBA removes sensitive headers and don't passes 'em along. Setting `zuul.sensitiveHeaders=` to empty should help.
