### ISSUE TITLE
(question) What does the /api/journal?stream Warning mean?

### ISSUE THREAD

**Issue by jhelbling** [codecentric/spring-boot-admin#372]
It seems that we successfuly configured _spring-boot-admin_ application. It's running within a Docker Container and can correctly communicate with a _spring-cloud-netflix_ server (also itself installed in a Docker Container).

However, we do see the following WARNING in the logs:

`2016-12-28 08:46:27.954  WARN 7 --- [qtp66231846-19] org.eclipse.jetty.server.HttpChannel     : //serviceName:portNumber/api/journal?stream

java.lang.IllegalStateException: cannot reset buffer on committed response
	at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1245)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:371)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:266)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Unknown Source)`

We see this warning every ~30sec ...

What does it mean? Something to be worried about? 

I'm not 100% which configuration information is relevant for this question, please just ask for any parameter you need to know.

**Comment by joshiste** [comment]
The ui does some long polling on this endpoint. The default timeout is 30s for the async request. After the timeout the ui does a reconnect. So you don't need to worry about this. You can try to set `spring.mvc.async.request-timeout=-1` and see if the message disappears.

**Comment by jhelbling** [comment]
Thanks for the quick answer. I added this parameter, seem to do the trick. cheers!
