### ISSUE TITLE
spring boot admin 对 docker 中 cloud 服务 支持吗 

### ISSUE THREAD

**Issue by atliwen** [codecentric/spring-boot-admin#376]
请问一下   spring boot admin 对 docker 中 cloud 服务 支持吗 

docker 容器中的 cloud 服务  有通讯的问题       除非指定 cloud hostname 地址 
但是 指定地址后   spring admin   获取的只有一个服务  不管该服务有几个。

**Comment by joshiste** [comment]
I can't understand Chinese. Please use English or I can't help you.

**Comment by joshiste** [comment]
Closed due to missing feedback.
