### ISSUE TITLE
support regular expression in spring.boot.admin.discovery.ignored-services

### ISSUE THREAD

**Issue by ezraroi** [codecentric/spring-boot-admin#377]
Hi,
my consul has rabbit mq clusters that register in it. They register with service id like: rabbitmq-{cluster_name}.

If the ignored-services property will support regular expression i will be able to exclude all those rabbitmq clusters from the admin view

**Comment by joshiste** [comment]
PRs are always welcome😉

**Comment by ezraroi** [comment]
Will do so, thanks

**Comment by ezraroi** [comment]
I cloned the repo but looks like the maven build is failing on `RegistryControllerTest` as `JSONObject().put` can throw exception... any idea?

**Comment by joshiste** [comment]
Please try using java8 and the mavenwrapper from the repo...

**Comment by ezraroi** [comment]
Tired.. the pom.xml sis saying java 7...

**Comment by joshiste** [comment]
I use jdk8 with a source and target for 7...

**Comment by ezraroi** [comment]
strange.. me too

**Comment by joshiste** [comment]
OK I've got the same error. I since master is built agains boot 1.5.0.BUILD-SNAPSHOT it's most likely due to a dependency update.
I'll dig into this and will push an update.

**Comment by ezraroi** [comment]
Thanks :)
