### ISSUE TITLE
When will the spring-boot-admin-server-ui-login dependency be available in Maven Repository? 

### ISSUE THREAD

**Issue by mstommes** [codecentric/spring-boot-admin#378]
Hello,

I've been searching maven repository for the spring-boot-admin-server-ui-login dependency and cannot seem to find it anywhere.  Has it been added yet or is there a timeline for when it will be added? 

Thank you.

**Comment by joshiste** [comment]
The login module is part of the 1.5.0 Release which is scheduled end of January (after the Boot 1.5 release.)

**Comment by joshiste** [comment]
But there are snapshot builds available...

**Comment by mstommes** [comment]
Thank you for the quick response :)

**Comment by joshiste** [comment]
@mstommes we need to postpone the spring boot admin 1.5 release after Feb. 17, since we depend on the spring cloud dalston release.
