### ISSUE TITLE
/api/applications/23e21a69/logfile   404 Not Found

### ISSUE THREAD

**Issue by wzl1990** [codecentric/spring-boot-admin#381]
I use the 1.3.5 version of the following problems
http://localhost:8089/api/applications/23e21a69/logfile 404 Not Found

**Comment by steve-oakey** [comment]
Is the `/logfile` endpoint available on the application you are monitoring?

**Comment by wzl1990** [comment]
thanks  
I have a problem This interface /api/applications/23e21a69/health to return data, the number of pages are not shown, as shown
![3q68 b u18n5zzua8w8 j k](https://cloud.githubusercontent.com/assets/12508059/21836401/f46358a8-d7ff-11e6-94fc-c0efdc9c1391.png)
![5 tmflq435 lq __ks39 5](https://cloud.githubusercontent.com/assets/12508059/21836427/177d99fc-d800-11e6-81ab-5340b60eff0d.png)

**Comment by joshiste** [comment]
Did you try updating to a more recent version of spring boot admin? We won't do any updates on 1.3.x

**Comment by joshiste** [comment]
Which version of spring boot actuator are you using in your client application?

**Comment by joshiste** [comment]
Your `/health` endpiont renders the wrong format. It should look like this:

```json
{
"status": "UP",
"diskSpace": {
"status": "UP",
"total": 498971181056,
"free": 423447494656,
"threshold": 10485760
},
"hystrix": {
"status": "UP"
}
}```

**Comment by wzl1990** [comment]
I use the admin-ui version is 1.4.5
/ health The data returned is:
{"Details": {"diskSpace": {"details": {"total": 148474163200, "free": 55337496576, "threshold": 10485760}
: {"Code": "UP", "description": ""}}, "redis": {"details": {"version": "3.0.6" UP "," description "
: ""}, "Db": {"details": {"database": "MySQL", "hello": 1}, "status": {"code": "UP" }}}, "Status"
: {"Code": "UP", "description": ""}}

![f m9ipz _hn5eaa3h3kt3](https://cloud.githubusercontent.com/assets/12508059/21842423/a2b8bae4-d821-11e6-8d8a-d455a1e7cfae.png)
