### ISSUE TITLE
Loggers UI should set a color for FATAL

### ISSUE THREAD

**Issue by TimHess** [codecentric/spring-boot-admin#3837]
I have an app that uses log4j, which adds the level of FATAL, which all seems to function fine aside from not coloring the buttons in the UI on the loggers page:
![image](https://github.com/user-attachments/assets/f7b1f1e5-0b0e-4e3c-8667-466e81f714d0)

Can this be added?

A bit of an aside, but I find the [existing colors/class to level mappings](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/loggers/logger-control.vue#L88) to be a bit odd.

**Comment by bart-vmware** [comment]
Suggestion:
- off = black
- fatal = red
- error = orange
- warn = dark-yellow (yellow makes the text hard to read)
- debug = blue
- trace = green

**Comment by erikpetzold** [comment]
Hi @TimHess 

we can add a coloring for FATAL. As you already found the relevant code you could also open a Pull Request.

Regarding the color-to-level mappings: we understand, that the first idea is to have something like error = red.
But here we are not talking about error logs, but level configuration.
The "special case" is to have something on debug or trace. This can fill up your disk, this indicates you are researching some kind of bug etc. So these are the red/yellow cases.

Regarding color-blindness: even if people cannot distinguish the colors, they still see there is something (some kind of grey or whatever), right? So they already see it is selected.

**Comment by TimHess** [comment]
> Hi @TimHess 
> 
> we can add a coloring for FATAL. As you already found the relevant code you could also open a Pull Request.
> 
> Regarding the color-to-level mappings: we understand, that the first idea is to have something like error = red.
> But here we are not talking about error logs, but level configuration.
> The "special case" is to have something on debug or trace. This can fill up your disk, this indicates you are researching some kind of bug etc. So these are the red/yellow cases.
> 
> Regarding color-blindness: even if people cannot distinguish the colors, they still see there is something (some kind of grey or whatever), right? So they already see it is selected.

Thanks for sharing the reasoning, that now makes a lot more sense. The main thing to me was getting _some_ color for the category so it was more evident when it was selected - your change works for me!

**Comment by SteKoe** [comment]
Hi @TimHess,

we have release version 3.3.6 including a fix for the color.

Regards,
SteKoe
