### ISSUE TITLE
404s and broken JS

### ISSUE THREAD

**Issue by deanpullen** [codecentric/spring-boot-admin#385]
Hi I'm having trouble with several end points.

As you can see in the screenshot below I'm getting 404s for flyway/liquibase etc - how do I turn off these from being polled by SBA? It _seems_ to break the view - the JSON returned for the Memory looks absolutely fine but the screen shows it all as 0.

Many thanks.

![screen shot 2017-01-12 at 12 29 01](https://cloud.githubusercontent.com/assets/1701884/21889874/fc2f1af4-d8c2-11e6-8ba0-42bf3a5cd729.png)

**Comment by joshiste** [comment]
You currently can't turn of these requests... But this shouldn't affect the
ui.
Can you provide some sample json for /metrics from the network-tab in your
browsers dev-tools.
Sometime it happens that the json get rendered wrong from the acutator
endpoints depending on your Jackson config....

**Comment by deanpullen** [comment]
Thanks. Here's an example response:

{"LinkedHashMap":{"mem":667977,"mem.free":295763,"processors":4,"instance.uptime":320629,"uptime":509676,"systemload.average":1.13,"heap.committed":536624,"heap.init":524288,"heap.used":240860,"heap":1223936,"nonheap.committed":139328,"nonheap.init":2496,"nonheap.used":131353,"nonheap":1556480,"threads.peak":94,"threads.daemon":22,"threads.totalStarted":161,"threads":45,"classes":16653,"classes.loaded":16655,"classes.unloaded":2,"gc.parnew.count":13,"gc.parnew.time":4296,"gc.concurrentmarksweep.count":4,"gc.concurrentmarksweep.time":1640,"gauge.response.api.status":676.0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.median":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.min":0,"gauge.response.manage.health":13.0,"gauge.response.manage.info":56.0,"MyServerName.$(graphite.app.name}).someType.MT800.count":0,"MyServerName.$(graphite.app.name}).someType.MT800.oneMinuteRate":0.0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.max":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.99thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.fiveMinuteRate":0.0,"MyServerName.$(graphite.app.name}).someType.MT800.oneMinuteRate":0.0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.95thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.meanRate":0.0,"counter.status.200.manage.health":22,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.median":0,"MyServerName.$(graphite.app.name}).someType.MT800.count":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.75thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.mean":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.max":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.999thPercentile":0,"counter.status.200.manage.metrics":4,"counter.status.200.manage.heapdump":4,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.98thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.98thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.fiveMinuteRate":0.0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.min":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.stdDev":0,"counter.status.200.api.status":1,"MyServerName.$(graphite.app.name}).someType.MT800.fifteenMinuteRate":0.0,"counter.status.200.manage.info":5,"MyServerName.$(graphite.app.name}).someType.MT800.fifteenMinuteRate":0.0,"gauge.response.manage.heapdump":106.0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.stdDev":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.95thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.999thPercentile":0,"gauge.response.manage.metrics":199.0,"MyServerName.$(graphite.app.name}).someType.MT800.meanRate":0.0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.75thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.99thPercentile":0,"MyServerName.$(graphite.app.name}).someType.MT800.snapshot.mean":0}}

**Comment by joshiste** [comment]
Yep, your JSON has the wrong format. The `{"LinkedHashMap":` must not appear.
You can try setting the `management.port` different to the `server.port`. IIRC this should result in a nested ApplicationContext for the actuator endpoints using their own converters....

**Comment by deanpullen** [comment]
That makes sense - thanks for your help.

**Comment by deanpullen** [comment]
@joshiste if I'm unable to change the management.port (due to firewall issues) is there a way I can configure the actuator endpoints to use a specific mapper/converter?

**Comment by joshiste** [comment]
I think so. Please consult the spring boot reference guide on this.
