### ISSUE TITLE
integrate JavaMelody

### ISSUE THREAD

**Issue by wallishuang** [codecentric/spring-boot-admin#388]
Integration with javamelody will be great...
https://github.com/javamelody/javamelody/wiki

**Comment by Pughy12** [comment]
Is this still being looked into? I am really interested in this happening, just wondering how close (if at all) it is to becoming a reality.

**Comment by joshiste** [comment]
If you want to see this happen you need to do it yourself. Any help and PRs are appreciated. I have to limited time to dig into this.

**Comment by Pughy12** [comment]
Fair enough, thanks for the reply.

**Comment by dvtoever** [comment]
I have something which is kinda working, applications register itself using service discovery (eureka) to the javamelody collect server (which I added into my spring-boot-admin project). I also made a very basic spring-boot-admin-server-ui-javamelody module that embeds the specific javamelody page within an iframe (yes an iframe). 

Is there interest if I share this as a pull request? It would be nice if others could help give it further shape

**Comment by joshiste** [comment]
Showing code is always appreciated :)

I wonder if we can make the collect-server use the ApplicationRegistry as source for collecting, so that sba-client and discovery are both supported....

**Comment by dvtoever** [comment]
Ok, i created a PR that is not intented to be merged right now, but to provide a starting point from which can be worked. https://github.com/codecentric/spring-boot-admin/pull/450

For now the service discovery events are used to register applications, I guess we can easily fit ApplicationRegistry into this as well

**Comment by joshiste** [comment]
There is now a solution for writing 3rd party view modules and also the backend is extensible. Therefore this integration should be developed as a 3rd party module (if ever done)
