### ISSUE TITLE
Admin server not reading client applications via consul

### ISSUE THREAD

**Issue by get2parag** [codecentric/spring-boot-admin#389]
I'm trying to integrate spring boot admin server in one of my existing spring boot apps but it is not able to read client info and the admin page is coming empty. Configuration done -
pom 
```xml
<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-server</artifactId>
			<version>1.4.5</version>
		</dependency>
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-server-ui</artifactId>
			<version>1.4.5</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-discovery</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jolokia</groupId>
			<artifactId>jolokia-core</artifactId>
		</dependency>
```

Spring boot application has following annotations class-
```java
@EnableAdminServer
@EnableDiscoveryClient
@SpringBootApplication
````

The clients are being discovered using consul so i believe no further configuration is required at their end. Spring boot parent version is 1.4.2.RELEASE.

Please guide me what could be off here. Let me know if any further info is required.

**Comment by joshiste** [comment]
Looks good so far. Did you checked your application.prooerties is configured correctly for consul? Did you have a look at our consul-sample? Have you checked that the admin registers itself correctly at consul?

**Comment by get2parag** [comment]
Have you checked that the admin registers itself correctly at consul? -- Yes, admin application is visible and healthy on consul.
Did you check your application.prooerties is configured correctly for consul? -- I have explicitly enabled admin property like spring.boot.admin.* etc. and will check and get back to you.

**Comment by joshiste** [comment]
>  will check and get back to you.

So does everything work now? Can I close the issue?

**Comment by joshiste** [comment]
Closing after a week without feedback.
