### ISSUE TITLE
Long Application descriptions break layout

### ISSUE THREAD

**Issue by jenswl** [codecentric/spring-boot-admin#39]
In the "details" view longer descriptions (2nd column) are not breaking correctly. A CSS change (class ng-binding) with word-break:break-word can fix that.

best regards,
Jens

**Comment by joshiste** [comment]
Hi Jens,

which version? Witch FF an Chrome it looks good using the HEAD.
![bildschirmfoto vom 2015-02-02 19 52 02](https://cloud.githubusercontent.com/assets/8779225/6006910/b9e0b4f4-ab16-11e4-98be-df0cc264785e.jpg)
