### ISSUE TITLE
Styling issue with long application title and urls

### ISSUE THREAD

**Issue by Spewer92** [codecentric/spring-boot-admin#392]
A long application name leads to a linebreak and the applications urls are no longer fully visible.
Example:
![screenshot_edit](https://cloud.githubusercontent.com/assets/15867036/22139890/5bcdc0f6-dee9-11e6-92b7-56b0b5d3f119.png)

The following CSS would solve the problem (in most cases):
`.header--application .application--title .muted {
    display: block;
}`

**Comment by joshiste** [comment]
Are you using the latest 1.4.5? Should have been fixed with #347

**Comment by Spewer92** [comment]
Yes, I'm on 1.4.5.

**Comment by joshiste** [comment]
Works for me with 1.4.5.. May be you get an old version from your browser's cache?

![image](https://cloud.githubusercontent.com/assets/8779225/22181886/53edbca2-e096-11e6-95c3-39db5ddeab2b.png)
