### ISSUE TITLE
(Question) "Details" page customization

### ISSUE THREAD

**Issue by jhelbling** [codecentric/spring-boot-admin#393]
We're using version 1.4.1, and are looking to customize the "Details" page of a service.

For example, we would like to hide part of the entries pointed by the red arrows (attached screenshot).

Is it possible?

![applicationdetail](https://cloud.githubusercontent.com/assets/8075031/22248106/5b716958-e23d-11e6-953b-c5ddabe2a503.png)

**Comment by joshiste** [comment]
Currently you can only copy the sources from the spring-boot-admin-ui module, modify and build the module and use this to replace the original one.
