### ISSUE TITLE
Log follow doesn't work when zooming page in Chrome

### ISSUE THREAD

**Issue by jmisur** [codecentric/spring-boot-admin#396]
When I zoom the page in or out (Chrome) while following logfile, it doesn't follow.

**Comment by joshiste** [comment]
The following is active until you scroll. If you zoom in it might happen that a scroll event occurs.
You can see that the following is active when the "Follow" button is blue. You can just activate the follow after zooming in.

**Comment by jmisur** [comment]
Hi thanks for the answer. However did you try to reproduce it? For me zooming and clicking follow really doesn't work. Zoomed in/out page cannot follow log.

**Comment by joshiste** [comment]
I turned on follow hit `ctrl + '+'` multiple times. And hit follow again...

**Comment by jmisur** [comment]
hm that's weird. I'm using admin 1.4.4 and Chrome 55.0.2883.95 and when I zoom in let's say 150%, then hit follow again, it does move the log to the latest entry, but then doesn't follow. always overflows below the visible screen. I also have `... first 1.5M skipped ...` at the top, dunno if that matters.
