### ISSUE TITLE
Multiple log file download/viewing

### ISSUE THREAD

**Issue by paulnuk** [codecentric/spring-boot-admin#397]
It would be good to have a facility to not only have the ability to view and download the current log, but also  previous logs, as it is often a previous log that is needed to resolve application support issues.

**Comment by joshiste** [comment]
There is no spring boot actuator to provide that. So we can't implement that.

**Comment by kiransajja** [comment]
Can i add more than one log file to the below configuration, It would be good if we can display more than one log file. Can you please give any configuration logging.file=nohup.out, application.log ...

**Comment by joshiste** [comment]
@kiransajja the responsible logfile actuator endpoint is part of the spring boot project and not spring boot admin.
