### ISSUE TITLE
Improve Cloudfoundry support in client

### ISSUE THREAD

**Issue by ashwgupt** [codecentric/spring-boot-admin#399]
This is being re-reported after failure to get a help on Stackoverflow - http://stackoverflow.com/questions/41742918

There is an issue being faced when SBA client and server are running on Cloud Foundry.

We are developing a Boot-Admin dashboard using the codecentric provided library of `spring-boot-admin-server` version 1.4.5

The application are registering itself with the server as client using `spring-boot-admin-starter-client` version 1.4.5.

Both client and server are deployed on a PCF environment and are communication over HTTPS. 

The application though is able to register itself with the admin sever but is showing up as OFFLINE on dashboard. There are no errors reported in the logs for either the admin-server or the admin-client.

The application properties used for the spring-boot-admin-client app to run in PCF is:

    spring:
      application:
        name: bootadmin-ms-charlie
      boot:
        admin:
          url: https://bootadmin-dashboard.abc.intl.com
    
    ssl:
      trust_store:
        path: classpath:ssl/sslcacert.jks
        password: a-password

Here are the logs from SBA server showing that the communication between server and client is working okay. I don't see any logs giving any indication of an error, don't they?

    OUT 2017-01-23 05:15:15.139 DEBUG 10 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing POST request for [/api/applications]
    OUT 2017-01-23 05:15:15.151 DEBUG 10 --- [nio-8080-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Read [class de.codecentric.boot.admin.model.Application] as "application/json;charset=UTF-8" with [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@7df33a9f]
    OUT 2017-01-23 05:15:15.163 DEBUG 10 --- [nio-8080-exec-1] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Written [Application [id=3805ee6a, name=bootadmin-ms-charlie, managementUrl=http://23fcf304-82d6-44cd-7fce-2a5027de9f21:8080, healthUrl=http://23fcf304-82d6-44cd-7fce-2a5027de9f21:8080/health, serviceUrl=http://23fcf304-82d6-44cd-7fce-2a5027de9f21:8080]] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@7df33a9f]
    OUT 2017-01-23 05:15:15.166 DEBUG 10 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
    OUT 2017-01-23 05:15:15.166 DEBUG 10 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Successfully completed request
    OUT bootadmin-dashboard.abc-intl.com - [23/01/2017:05:15:15.140 +0000] "POST /api/applications HTTP/1.1" 201 302 308 "-" "Java/1.8.0_121" 60.16.25.20:43224 x_forwarded_for:"10.10.10.10" x_forwarded_proto:"https" vcap_request_id:a40159e4-543f-40e0-627e-e8f1e7688b99 response_time:0.034164523 app_id:adcc8a33-83f4-448d-9ae2-bf2a2b16ea72
    OUT 2017-01-23 05:15:18.719 DEBUG 10 --- [    updateTask1] o.s.web.client.RestTemplate              : Created GET request for "http://23fcf304-82d6-44cd-7fce-2a5027de9f21:8080/health"
    OUT 2017-01-23 05:15:18.722 DEBUG 10 --- [    updateTask1] o.s.web.client.RestTemplate              : Setting request Accept header to [application/json, application/*+json]

The logs from client are all clean. It throws warning of "Failed to register" only when the server is down.

The same apps are working perfectly fine **locally** where the admin dashboard shows all the applications as expected.

Is there any configuration that needs to be done in specific to Cloud Foundry?
Or any obvious mistake that I might have made?

Any suggestion is most welcome.

**Comment by abracadv8** [comment]
I ran into the same issue.  I forked an older version of the client/SBA because our teams are still on Spring Boot 1.2.x and made some custom changes.  Cloud Foundry 'hides' the true IP and port of the service.  You can see this is evident during the registration; the IP is some GUID value.

```serviceUrl=http://23fcf304-82d6-44cd-7fce-2a5027de9f21:8080```

I ended up autowiring the following properties and using them if those properties exist instead of InetAddress and building the URL using them.

Reference: https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#CF-INSTANCE-IP

```
  @Value("${CF_INSTANCE_ADDR:}")
  private String cfInstanceUrl;
  @Value("${CF_INSTANCE_IP:}")
  private String cfInstanceIp;
  @Value("${CF_INSTANCE_PORT:}")
  private String cfInstancePort;
```

The newer versions use the ApplicationFactory interface, so in the future it may make sense to make a custom CloudFoundryApplicationFactory to autowire those custom values.

**Comment by joshiste** [comment]
> The newer versions use the ApplicationFactory interface, so in the future it may make sense to make a custom CloudFoundryApplicationFactory to autowire those custom values.

PRs welcome!

@ashwgupt Does @abracadv8's comment help you solving the problem?

**Comment by ashwgupt** [comment]
@abracadv8 thanks for the tip. As am using the latest SBA version and spring-boot 1.4, let me try to use the ApplicationFactory to inject the a CF compatible bean.

Shall report back the results.

**Comment by ashwgupt** [comment]
Using the versions as mentioned above, we could overcome the erroneous status for the microservices showing on SBA.

Below is the code snippet used to achieve it:
```
@Configuration
@Conditional(SpringBootAdminClientEnabledCondition.class)
public class BootAdminClientConfig {

    @Autowired
    private ManagementServerProperties managementServerProperties;

    @Autowired
    private ServerProperties serverProperties;

    @Bean
    public AdminClientProperties adminClientProperties(){
        AdminClientProperties clientProperties = new AdminClientProperties();
        clientProperties.setHealthUrl("https://bootadmin-ms-charlie.abc.com/health");
        clientProperties.setManagementUrl("https://bootadmin-ms-charlie.abc.com/management");
        clientProperties.setServiceUrl("https://bootadmin-ms-charlie.abc.com/");
        return clientProperties;
    }

    @Bean
    public ApplicationFactory applicationFactory(ManagementServerProperties management,
            ServerProperties server,
            @Value("${endpoints.health.path:/${endpoints.health.id:health}}") String healthEndpointPath) {
        return new DefaultApplicationFactory(adminClientProperties(),
                management, server, healthEndpointPath);
    }
}
```

I will ultimately replace the URL values with those from CF env, as you suggested. 
If you see any other scope of improvement in it, please advise.

And I would request either of you @abracadv8 or @joshiste to reply back on my Stackoverflow post - http://stackoverflow.com/questions/41742918 as an answer so that I can accept it and make available for others to refer.

**Comment by joshiste** [comment]
Did someony try`spring.boot.admin.client.prefer-ip=true` without any other modifications as it is sugegsted for docker?

**Comment by ashwgupt** [comment]
I just tried it and found the status to be doubtful, as out of my apps 2 instances running on CF, any one is showed as Online while other showes as Offline.

IPs are not the preferred the way to work with on CF for the reason that, the IPs may change/masked/nat'ed when traffic passes through CF Router.

**Comment by ashwgupt** [comment]
On the other note, I'm seeing huge number Registration-Deregistration entries in the SBA Journal at very quick succession. 

Do an app need to de-register if it's already been running okay? Why is that happening?
And can its frequency be modified to be less frequent?

**Comment by ashwgupt** [comment]
I see `spring.boot.admin.period` solving it.

**Comment by ashwgupt** [comment]
I've noticed that the simple app properties can also help in achieving the same. So in my view that's the preferred choice than creating a new config class.
```
spring:
  boot:
    admin:
      client:
        management-url: 
        health-url: 
        service-url: 
```

**Comment by joshiste** [comment]
@ashwgupt so can you show up some sample config?

**Comment by ashwgupt** [comment]
Here is all that we had to configure in properties file for our client apps' run on Cloud Foundry:
```
spring:
  application:
    name: microservice-alpha
  boot:
    admin:
      register-once: false
      url: https://bootadmin-dashboard.az1.abc.com,https://bootadmin-dashboard.az2.abc.com
      client:
        service-url: https://microservice-alpha.az1.abc.com
```
>It is for an application - microservice-alpha running on AZ1 of our private Cloud Foundry setup. The `service-url` will change for instances running on AZ2

I hope it helps.

**Comment by joshiste** [comment]
Hmm I expected that you'd use the CloudFoundry Env-Variables...

**Comment by ashwgupt** [comment]
Yeah, I could have but after a debate and evaluation we wanted to keep it simple.

Using VCAP_APPLICATION_URIS[] could be a way out to achieve the same. But given in our topology we have multiple routes bound to an app on CF, varying from F5 GTM level to LTM level, using CF variable to find out the service DNS may not be very effective as we may not know their exact sequence in env.

We wanted an app to register itself with the server using the AZ specific route for sanity and ease of understand of correct status on dashboard, and hence the choice.

Let me try to showcase a case of using the CF Env to set it up for use in a simpler topology unlike ours.

**Comment by ashwgupt** [comment]
Below will be the code snippet if one wants to populate the application URI from the CF environment:

```
spring:
  application:
    name: microservice-alpha
  boot:
    admin:
      register-once: false
      url: https://bootadmin-dashboard.az1.abc.com,https://bootadmin-dashboard.az2.abc.com
      client:
        service-url: https://${vcap.application.application_uris[0]}
```

**Comment by joshiste** [comment]
Ok. That's really simple. I don't think I'll add myself a ApplicationFactory for this. But if someone wants to submit a PR its welcome.

**Comment by sruthi-kotla** [comment]
Hi All,

Even am facing the same issue. once I push my application to pcf(cloud foundry) I do see that the client application is showing OFFLINE. I tried the above option of adding configration properties in clients .yml file but didnt work out.

```
spring:
  application:
    name: Sample
  boot:
    admin:
      register-once: true
      url: https://admin-project.cfapps.io
      username: user
      password: user
      client:
        service-url: https://sample-hilarious-bonobo.cfapps.io        
management:
  security:
    enabled: false
```

This is my client configuration properties.

Can someone help me out with this?
Thanks in advance..

![image](https://user-images.githubusercontent.com/37380174/37421072-6406f32a-27de-11e8-8ce3-abc98aa5be14.png)

**Comment by sruthi-kotla** [comment]
Is SSL mandatory?
When I hover over OFFLINE I get the below error. It is trying to hit health of someother /health endpoint.
Am not sure why is thiis happening.

Could you suggest in this?

![image](https://user-images.githubusercontent.com/37380174/37425348-0b9f6298-27e9-11e8-99e7-e6274c6a6f8b.png)
