### ISSUE TITLE
de.codecentric:spring-boot-admin-server-ui:1.1.1 doesn't exist in Maven Central.

### ISSUE THREAD

**Issue by izeye** [codecentric/spring-boot-admin#40]
de.codecentric:spring-boot-admin-server-ui:1.1.1 doesn't exist in Maven Central.

Has it been released yet?

**Comment by joshiste** [comment]
We are working on it. We have some issues with the new gulp build on our ci server....

**Comment by izeye** [comment]
@joshiste Thank you for the feedback :-)

**Comment by joshiste** [comment]
You can find a snapshot here: https://oss.sonatype.org/content/repositories/snapshots
We hope to release in the next days

**Comment by joshiste** [comment]
1.2.2 has been released
