### ISSUE TITLE
Spring boot 1.5.1 env update mime error

### ISSUE THREAD

**Issue by JMesens** [codecentric/spring-boot-admin#403]
Environment manager doesn't seem to be compatible with spring boot 1.5.1

Error when setting a env var:

```json
{
  "data": {
    "timestamp": 1486550788785,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.IllegalArgumentException",
    "message": "MIME type may not contain reserved characters"
  },
  "status": 500,
  "config": {
    "method": "POST",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "params": {
      "logging.level.org.apache": "DEBUG"
    },
    "url": "api\/applications\/XXXXXXX\/env",
    "data": "",
    "headers": {
      "Accept": "application\/json, text\/plain, *\/*",
      "Content-Type": "application\/json;charset=utf-8"
    }
  },
  "statusText": ""
}
```

**Comment by joshiste** [comment]
Are you using Spring Cloud Camden.SR5?

**Comment by JMesens** [comment]
Yes

**Comment by Maraschin** [comment]
I'm not sure if it's related but I can't managed it to read environment variables.

- bootstrap.yml has
spring:
  profiles:
    active: ${environment:localhost}

Works on spring =< 1.4.4
But not on 1.5.1 with cloud Camden.SR5, it defaults to localhost - just changing back to 1.4.4 run again and it works.

**Comment by joshiste** [comment]
Your error is related to https://github.com/spring-cloud/spring-cloud-netflix/issues/1663

**Comment by joshiste** [comment]
At best you downgrade to Camden.SR4 and Boot 1.4.4 in your Spring Boot Admin Server. I don't recommend to run SBA Server on Boot 1.5.x, since we don't test and support that. The SBA 1.5.x release will be out end Feb, when Spring Cloud Dalston is released.

**Comment by joshiste** [comment]
Just realized that we ship our won version of the `SimpleHostRoutingFilter`...

**Comment by joshiste** [comment]
Could you try a 1.4.6-SNAPSHOT from

´´´xml
<snapshotRepository>
 <id>sonatype-nexus-snapshots</id>
 <name>Sonatype Nexus Snapshots</name>
 <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</snapshotRepository>
```

**Comment by JMesens** [comment]
Yes that works!
Thanks!
