### ISSUE TITLE
Expose the application id

### ISSUE THREAD

**Issue by mikexliu** [codecentric/spring-boot-admin#404]
Would it be possible to expose ApplicationRegistrator's registeredId?

For example, I could do:

```java
@Inject
ApplicationRegistrator applicationRegistrator;

{
    // returns registeredId.get()
    applicationRegistrator.getRegisteredId();
}
```

**Comment by joshiste** [comment]
It is. But for what purpose?

**Comment by mikexliu** [comment]
Basically, I'd like to be able to reference back to `/admin-ui/#/applications/<my_id>/details` in a different page that's also served by the same app. I could link it back to `/admin-ui/#/`, but if I have multiple spring-boot-admin-ui apps (for redundancy), then I'm not certain which is the current app.

Hopefully that makes sense..

**Comment by joshiste** [comment]
Ok. That's just what i imagined, you want to do. :)

**Comment by mikexliu** [comment]
Thanks @joshiste 

I've submitted a PR here: https://github.com/codecentric/spring-boot-admin/pull/405
