### ISSUE TITLE
Sample error

### ISSUE THREAD

**Issue by Applemann** [codecentric/spring-boot-admin#407]
Hello, I am trying build and run your spring-boot-admin-sample, but when I run command:
mvn package
so I get error: 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:14 min
[INFO] Finished at: 2017-02-10T14:24:26+01:00
[INFO] Final Memory: 24M/313M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-boot-admin-sample: Could not resolve dependencies for project de.codecentric:spring-boot-admin-sample:jar:1.5.0-SNAPSHOT: The following artifacts could not be resolved: de.codecentric:spring-boot-admin-server:jar:1.5.0-SNAPSHOT, de.codecentric:spring-boot-admin-server-ui:jar:1.5.0-SNAPSHOT, de.codecentric:spring-boot-admin-server-ui-login:jar:1.5.0-SNAPSHOT, de.codecentric:spring-boot-admin-starter-client:jar:1.5.0-SNAPSHOT: Could not find artifact de.codecentric:spring-boot-admin-server:jar:1.5.0-SNAPSHOT in spring-snapshot (http://repo.spring.io/snapshot) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by joshiste** [comment]
You either need to build the full project (including the npm builds) or configure the snapshot mirror:
```
<snapshotRepository>
 <id>sonatype-nexus-snapshots</id>
 <name>Sonatype Nexus Snapshots</name>
 <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</snapshotRepository>
```

Or just don't use the SNAPSHOT and use the latest release (1.4.5)
