### ISSUE TITLE
Timer metrics support

### ISSUE THREAD

**Issue by bsideup** [codecentric/spring-boot-admin#41]
Hi!

Could you please support timer metrics? i.e.:

``` javascript
"timer.someTimer" : 33,
"timer.someTimer.count" : 26,
"timer.someTimer.fifteenMinuteRate" : 0.20585190244272,
"timer.someTimer.fiveMinuteRate" : 0.213187349928478,
"timer.someTimer.meanRate" : 0.248698908802215,
"timer.someTimer.oneMinuteRate" : 0.187558528524916,
"timer.someTimer.snapshot.75thPercentile" : 45,
"timer.someTimer.snapshot.95thPercentile" : 60,
"timer.someTimer.snapshot.98thPercentile" : 61,
"timer.someTimer.snapshot.999thPercentile" : 61,
"timer.someTimer.snapshot.99thPercentile" : 61,
"timer.someTimer.snapshot.max" : 61,
"timer.someTimer.snapshot.mean" : 37,
"timer.someTimer.snapshot.median" : 34,
"timer.someTimer.snapshot.min" : 25,
"timer.someTimer.snapshot.stdDev" : 10,
```

**Comment by kiview** [comment]
When implementing Timer support, adding Histogram support as well would be great.

**Comment by RobWin** [comment]
+1

**Comment by joshiste** [comment]
I think i will try to tackle this next, since we are now using timers too. What type of diagram would be suitable for displaying timers?

**Comment by mar1ged** [comment]
I too am fascinated by the great insight Spring Boot Admin gives for my applications and miss the timers. But I think it is difficult to decide which values to display and with which type of diagram. Perhaps it is easiest to display three charts for the rates, the percentiles and the snapshot values which compare the 4 / 5 values. This could be bar charts which makes it easy to compare for example max, mid and mean value. Combining multiple timers into one diagram could be difficult to handle when one time is in the low milliseconds while the other is in the higher seconds range.

**Comment by joshiste** [comment]
As the new metrics endpoint in 2.0.0 has a totally different layout (due to micrometer), I'm closing this issue.
