### ISSUE TITLE
CompositeRouteLocator changes behaviour of RouteLocators significantly

### ISSUE THREAD

**Issue by JWThewes** [codecentric/spring-boot-admin#412]
Since yesterday we had no problems using Spring Boot Admin on our Zuul server.
Yesterday we introduced Spring Cloud Config and Spring Cloud Bus.

What I've noticed is the following:
The CompositeRouteLocator get's a Collection of RouteLocator injected in the constructor.
And here's the main problem:
Normally a Zuul only has one RouteLocator. Per Default the DiscoveryClientRouteLocator is used in our case. When enabling the AdminServer the SimpleRouteLocator is used.

This changes the behaviour of Zuul.

If you need any further information feel free to ask anytime.

**Comment by joshiste** [comment]
First, i strongly recommend not to include the admin into your business stuff. It can lead to unwanted side effects)

Second Spring Boot Admin doesn't needs a DiscoveryClientRouteLocator and hence doesn't instantiates it (and never did). There are two flavors of Zuul, a simple (see `ZuulConfiguration`) and the discovery one (see `ZuulProxyConfiguration`). 
Spring Boot Admin only imports the former one.

If you need a discovery based Zuul you *really* should run it as separate application.

**Comment by JWThewes** [comment]
Yeah omk I'm fine with not running this in my business application. But wouldn't it be nice if SpringBootAdmin behaves correctly on Zuul including DiscoveryClient?

**Comment by joshiste** [comment]
I don't think so. I don't want to include stuff I don't need, since it has to be tested and increases the surface. Also the default setup of SBA has no DiscoveryClient included.

You can try and add the `@EnableZuulProxy` config. Could be working due to the CompositeRouteLocator. But I don't give you any guarantees 😄
