### ISSUE TITLE
The "heap" metric is not the same as "-Xmx"

### ISSUE THREAD

**Issue by DidierLoiseau** [codecentric/spring-boot-admin#413]
This seems to be a just a label issue, but Spring Boot Admin reports the "_Maximum Heap (-Xmx)_" in the interface while this does not actually match the value of the `-Xmx` parameter.

The value reported in Spring Boot's [metrics](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html) as `heap` is [`MemoryUsage#getMax()`](https://docs.oracle.com/javase/8/docs/api/java/lang/management/MemoryUsage.html#getMax--) (see [`SystemPublicMetrics`](https://github.com/spring-projects/spring-boot/blob/996a31f8e6f70626020742b34eaa7293d1359e0c/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/SystemPublicMetrics.java#L119)) which actually [differs from -Xmx](http://stackoverflow.com/questions/23701207/why-do-xmx-and-runtime-maxmemory-not-agree).

I noticed it because we have some microservices starting with `-Xmx` = `-Xms`, but Spring Boot Admin is reporting a lower value for `-Xmx` which is not possible (the JVM wouldn't start with such values).

I think the “_(-Xmx)_” should be removed from the label at least. Retrieving the actual `-Xmx` value would be interesting though.

**Comment by joshiste** [comment]
You're right it's the max heap not the max memory for the whole jvm. I'll remove the labels
