### ISSUE TITLE
 how could i see direclty the Hystrix dashboard in my application page in Spring Boot Admin Server?

### ISSUE THREAD

**Issue by Genitana** [codecentric/spring-boot-admin#414]
how could i see direclty the Hystrix dashboard in my application page in Spring Boot Admin Server ?
i can't find  a tab of Hystrix  and i  add the spring-boot-admin-server-ui-hystrix to my pom.xml

**Comment by joshiste** [comment]
You need to follow all steps from the guide http://codecentric.github.io/spring-boot-admin/1.4.5/#_hystrix_ui_module

**Comment by harishkadamudi** [comment]
I tried this today, should work.
