### ISSUE TITLE
When will the version 1.5 be available?

### ISSUE THREAD

**Issue by ashwgupt** [codecentric/spring-boot-admin#415]
First of all my sincere apologies for asking such a naive question here but it did not look appropriate to be asked on Stackoverflow either :-)

My only simple question is, given the project is already building its 1.5.0 version, can we assume it's generally available for use now? This version is not showing up on Mavencentral or Mavenrepository yet though.

And if it's available for general use, when can we expect the reference-doc for the latest version also being made available?

My apologies again but a tentative timelines will help.

**Comment by joshiste** [comment]
For the planned release date please look at the corresponding milestone (see https://github.com/codecentric/spring-boot-admin/milestones). But please mind that we depend on the Spring Cloud Dalston release - if it gets postponed, I have to adapt the schedule.

The Docs from the current 1.5.0-SNAPSHOT are here: http://codecentric.github.io/spring-boot-admin/1.5.0-SNAPSHOT/

The jars aren't available on maven central, but here:
```xml
<snapshotRepository>
 <id>sonatype-nexus-snapshots</id>
 <name>Sonatype Nexus Snapshots</name>
 <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</snapshotRepository>
```
