### ISSUE TITLE
can not send email notify white use spring cloud config with auto discovery

### ISSUE THREAD

**Issue by chinahappyking** [codecentric/spring-boot-admin#429]
hi, 

spring-boot-admin version: 1.5.0-SNAPSHOT
spring-cloud-config version: 1.3.0.BUILD-SNAPSHOT

I have a microservice with consul configuration, If i set spring.cloud.config.discovery.enable=false,  System send email notify but set to false was not send notify:

bootstrap.xml
``` javascript
spring:
    cloud:
        consul:
            discovery:
                instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
                prefer-ip-address: true
                tags: management.context-path=${management.context-path}, health.path=/health
                healthCheckPath: ${management.context-path}/health
        config:
            failFast: false
            discovery:
                enabled: true
```

**Comment by joshiste** [comment]
Are you sure a JavaMailSender Bean exists in your ApplicationContext?

**Comment by chinahappyking** [comment]
sure

**Comment by joshiste** [comment]
do you have a sample project to reproduce?

**Comment by chinahappyking** [comment]
hi, @joshiste 

i have uploaded to github, my url is https://github.com/chinahappyking/adminserver.git

**Comment by joshiste** [comment]
Thanks for providing the sample project.
When I run your project using the `Prod` profile the `doNotify()` for the `MailNotifier` is executed perfectly. I couldn't find any issue, therefore I close this issue. Did you check you mail config and the mail-servers logs?

**Comment by chinahappyking** [comment]
hi, @joshiste, 
when setting **spring.cloud.config.discovery.enabled=false**, I find the doNotify() for the MailNotifier is not executed. but set true it is executed.

**Comment by joshiste** [comment]
The project provided by you hasn't `spring.cloud.config.discovery.enabled=false` set, so it defaults to `true` and everything worked properly for me.

**Comment by chinahappyking** [comment]
@joshiste , please see file bootstrap-prod.yml and bootstrap-dev.yml,  have setted to **true** and i debug config discovery code find it default to **false**.

**Comment by joshiste** [comment]
When disabling discovery no application is registered... If no application is registered there is no application going down to notify about...

I'm very confused about your expectations....

**Comment by chinahappyking** [comment]
@joshiste , when i set to **true** the notify not work, so set to **false**, can you try again?

**Comment by joshiste** [comment]
If discovery is *disabled* there is *nothing* to notify about...

**Comment by chinahappyking** [comment]
I think to enable discovery ,but notify is not work
