### ISSUE TITLE
How to set managementUrl and serviceUrl for Spring Boot Application?

### ISSUE THREAD

**Issue by ashishpratapsingh14** [codecentric/spring-boot-admin#431]
I am running Spring Boot Application in tomcat with ContextPath say /application1.
And Dispatcher Servlet has path /test. so this means all actuator URLs will be accessible by
http:/localhost:8080/application1/test/info 
http:/localhost:8080/application1/test/health
http:/localhost:8080/application1/test/env etc.

Here each application is registering to **Eureka** server. Where **Spring Boot Admin** is also registered.
But when I open Spring Boot Admin UI in a browser it shows service down.
Because in Spring Boot Admin UI for particular application details page it shows
healthUrl = http:/localhost:8080/health
serviceUrl = http:/localhost:8080/
managementUrl = http:/localhost:8080/

**Comment by joshiste** [comment]
You need to make sure that your homePageUrl in Eureka is correct. Please have a look at the [spring cloud documentation ](http://cloud.spring.io/spring-cloud-static/Camden.SR6/#_service_discovery_eureka_clients) for that.
