### ISSUE TITLE
Overview of scheduled jobs

### ISSUE THREAD

**Issue by selimok** [codecentric/spring-boot-admin#432]
Hi, 

it would be very nice to have an overview of all scheduled jobs (@Scheduled annotated methods) and their cron values (may be the calculated next execution time). 

An indicator of whether scheduling enabled or not would be also very helpful.

Thanks.

**Comment by joshiste** [comment]
@selimok yeah would be really nice. But wee need first a spring boot actuator endpoint that provides the data. Have you filed an issue for Spring Boot?

**Comment by selimok** [comment]
I just created an issue :)

**Comment by selimok** [comment]
Actuator implementation is DONE :)  (See: https://github.com/spring-projects/spring-boot/issues/8831 )

**Comment by semeiser** [comment]
I took a first stab at this here https://github.com/semeiser/spring-boot-admin/tree/scheduled-tasks-overview , just displaying the data returned from the scheduledtasks endpoint. If that's enough for a first iteration i'll create a PR.

**Comment by joshiste** [comment]
do you have a screenshot?

**Comment by joshiste** [comment]
Looking better than I imagined from your description. PR welcome!
