### ISSUE TITLE
Admin UI Keeps popping Authentication

### ISSUE THREAD

**Issue by Fransferdy** [codecentric/spring-boot-admin#433]
Whenever using Admin UI and selecting an instance, the UI starts popping an "authenticate" pop-up. Using the login/password specified in the client application won't make it go away. 

Clicking cancel will stop them from showing up, however everything will still work. So it's only rather annoying.

Is this a known bug or rather a missusage case ?

Thanks

**Comment by joshiste** [comment]
Did you ensure that Zuul doesn't filter the authorized header? Have a look at http://codecentric.github.io/spring-boot-admin/1.4.6/#_securing_client_s_actuator_endpoints

**Comment by joshiste** [comment]
...oh there is a typo in the docs it must read `zuul.sensitiveHeaders`...
