### ISSUE TITLE
Accessing the dashboard on Jboss EAP7 gives an embedded 404 error.

### ISSUE THREAD

**Issue by sunilgovindankutty** [codecentric/spring-boot-admin#435]
I have deployed Spring boot admin as a WAR on JBoss EAP 7. We are using Eureka for service discovery. But while clicking on any of the registered services in the spring boot admin dashboard the resulting details page shows a 404 at the top, right after the navigation bar. I do not find any errors in the logs. 
![image](https://cloud.githubusercontent.com/assets/26659544/25184179/53874eda-24df-11e7-8e4c-176629034b84.png)

**Comment by joshiste** [comment]
Are you sure the correct management-url gets registered in spring boot admin? Looks like the admin get's a 404 from your application.

**Comment by sunilgovindankutty** [comment]
I can click on the management URL at the top right corner of the page and that works though.

**Comment by joshiste** [comment]
is that url also reachable for the admin server? did you append a `/info` to the url an can you see the json?

**Comment by sunilgovindankutty** [comment]
Yes, it is. The weird thing is that if I run app using the embedded Tomcat container the details get displayed correctly. What is that section with 404 looking for?

**Comment by joshiste** [comment]
I guess your JBoss is issueing the 404. Are you sure all paths are setup correctly?
