### ISSUE TITLE
Not getting Environment Manager option to update the properties from spring Admin -> Details -> Environment 

### ISSUE THREAD

**Issue by PBondugula** [codecentric/spring-boot-admin#436]
I have spring boot admin server and 2 client applications. With application-1 I am able to Update environment properties,  but with application-2 it shows all the property values but don’t have Update environment option.

Below is the spring boot admin server versions and dependencies.

dependencyManagement - imports:
org.springframework.boot:spring-boot-gradle-plugin:1.4.2.RELEASE
io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE

dependencies:
org.springframework.cloud:spring-cloud-dependencies:Brixton.SR4

group: 'de.codecentric', name: 'spring-boot-admin-server', version:'1.4.6'
group: 'de.codecentric', name: 'spring-boot-admin-server-ui', version:'1.4.6'

Application-1 with below spring versions:

dependencyManagement - imports:
org.springframework.cloud:spring-cloud-starter-parent:Brixton.RELEASE

dependencies:
org.springframework.boot:spring-boot-gradle-plugin:1.4.2.RELEASE

io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE
compile group: 'de.codecentric', name: 'spring-boot-admin-starter-client', version:'1.3.0'

properties:
endpoints.jmx.domain=com.app1
endpoints.jmx.uniqueNames=true
spring.jmx.default-domain=com.app1

Application-2:

dependencyManagement - imports:
org.springframework.cloud:spring-cloud-dependencies:Camden.SR5
org.springframework.cloud:spring-cloud-dependencies:Brixton.SR4

dependencies:
org.springframework.boot:spring-boot-gradle-plugin:1.5.2.RELEASE
io.spring.gradle:dependency-management-plugin:1.0.0.RELEASE

de.codecentric:spring-boot-admin-starter-client:1.3.5

properties in both applications:
endpoints.jmx.domain=com.app2
endpoints.jmx.uniqueNames=true
spring.jmx.default-domain=com.app2

Is there any issue with jar versions. Why I am not getting the Update environment  options for 2nd application in spring admin UI.

**Comment by joshiste** [comment]
you need to make sure that `spring-cloud-context` is on your classpath. The Environment Manager is shown when the `/env`-endpoint of the monitored application supports the `POST` verb, which is enabled via an actuator endpoint from spring cloud context...

**Comment by pitinga** [comment]
Hi @PBondugula ...

Did you change the management port of "application-2"? The port is not equal to server port?

I have the same "disappearance of Update environment option" problem. I realized that it happens when I change the management port.

![image](https://user-images.githubusercontent.com/7571851/44117453-af1d8a4e-9fe9-11e8-900e-19ff88e69d7b.png)

I put more details in issue #246.
