### ISSUE TITLE
Eureka Discovery with different management ports not working.

### ISSUE THREAD

**Issue by vixmemon** [codecentric/spring-boot-admin#437]
I have my services registered to Eureka Registry on same host with different management ports. i.e. I have 5 services, each of them registered to Eureka with different -Dserver.port and -Dmanagement.port . I have My admin server fetch clients using Discovery Client and it fetches the list correct. Even the health url is fetched correct with accurate ports, but nothing else works. 

**Note:** management port is different, management basic auth is enabled, management context-path is empty.

**Following is my Client Config for all clients**
```
security.user.name=username
security.user.password=secure
security.basic.enabled=false
management.security.roles=SUPERUSER
server.port=8080
management.port=8081

eureka.client.serviceUrl.defaultZone=${peerUrls}
eureka.client.registryFetchIntervalSeconds=2
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.availabilityZones.default=${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
eureka.instance.statusPageUrlPath=${management.contextPath}/info
eureka.instance.healthCheckUrlPath=${management.contextPath}/health
eureka.instance.preferIpAddress=true
eureka.instance.metadataMap.instanceId=${spring.application.name}:${spring.application.instance_id:${random.value}}
```

**Following is my Spring Boot Admin Server Config**
```
eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=${peerUrls}

spring.boot.admin.discovery.enabled=true
zuul.sensitiveHeaders=
spring.boot.admin.routes.endpoints=env, metrics, trace, dump, jolokia, info, configprops, trace, activiti, logfile, refresh, flyway, liquibase
endpoints.sensitive=true
```

When i run the Admin UI, i get status of all registered apps as UP. Health URL is working fine and proper management.port... but nothing else seems to work. they all give this error
Error: {"timestamp":1492633234425,"status":404,"error":"Not Found","message":"Not Found","path":"/metrics"}

**Comment by joshiste** [comment]
You should use SBA 1.5.0 and set `management.port`and `management.context-path` for the metadataMap of your instance... see http://codecentric.github.io/spring-boot-admin/1.5.0/#_serviceinstanceconverter Table 5 Instance metadata options
