### ISSUE TITLE
Filtering in the application list should not take the health-information into account

### ISSUE THREAD

**Issue by ronnberg** [codecentric/spring-boot-admin#438]
The filter bar does not work for application name since I lifted to new version 1.5.0. Filter works for version and url, but no hits when typing the application name.

I have tried this on Chrome and Firefox, clearing all caches with same result.

**Comment by joshiste** [comment]
Still works for me using the 1.5.0...

Are there any errors in the browser's console?

**Comment by joshiste** [comment]
closing due to missing feedback

**Comment by cabbonizio** [comment]
Hey we started seeing this bug also once we upgraded to 1.5.0

**Comment by joshiste** [comment]
@cabbonizio do yo have any further information?

**Comment by cabbonizio** [comment]
Sure will check it out in further detail tomorrow.   Thanks for reopening.  I checked the console and didn't see an errors if I remember correctly.  It seems like the search is taking more things into account but no longer matching on application name like it used to.   I believe we were on version 1.4.6 prior to upgrading to 1.5.0.

**Comment by cabbonizio** [comment]
hey @joshiste as promised I am back with hopefully more detail.  I added a screenshot of my Chrome browser (with console window opened) and I have typed some text into the filter textbox.  In this case I typed "authentication" and have an application with that name but it never filtered down the list.  One thing that is interesting is all of the applications registered in Eureka as their /health endpoint, which leads to my next question on how "deep" are you filtering?   Meaning....which data are you filtering upon?  Are you using the /health results by any chance to match on what is typed in the text box?   I was assuming the match was only on what was on the opening screen columns (application name, version, info, etc.).   It doesn't look like there's any errors in the console but more of the functionality with the filtering itself.

Many thanks!

![image](https://cloud.githubusercontent.com/assets/6088654/25708014/3d1069c2-30b3-11e7-8d7a-7cd639f92cb2.png)

**Comment by joshiste** [comment]
the filtering is a full-text search on each element of the json-array returned by the `/api/applications` endpoint...

**Comment by cabbonizio** [comment]
Thanks that is helpful and now I can see what is happened and I think it's related to what I was saying earlier.  It looks like each service that is registered in Eureka is reporting back ALL of the applications registered in Eureka in the /health endpoint.  Therefore, when I search for something like "authentication", every application is matching so your functionality is working as you specified.   I will have to get to know how to control what's produced in the automatic health check for the Eureka discovery client, looks like it reports back all of the services.   Have you seen this behavior with Eureka, curious?  If this is standard behavior with Eureka then I assume others would find the search not very useful.   I certainly don't want to address Eureka concerns here, but wondering if it would be better not to full-text search and maybe limit the search to what is exposed in the screen such as just the name, version, info columns.  Thoughts?   

Below is the output of a single application from the /api/applications endpoint.

```json
{
"id": "f327c8f3",
"name": "ZUUL-GATEWAY-SERVICE",
"managementUrl": "http://wchpplcon102.qvcdev.qvc.net:30781",
"healthUrl": "http://wchpplcon102.qvcdev.qvc.net:30781/health",
"serviceUrl": "http://wchpplcon102.qvcdev.qvc.net:30781",
"statusInfo": {
"status": "UP",
"timestamp": 1493941053238,
"details": {
"hystrix": {
"status": "UP"
},
"diskSpace": {
"status": "UP",
"total": 38979764224,
"free": 20714532864,
"threshold": 10485760
},
"configServer": {
"status": "UP",
"propertySources": [
"configClient",
"http://wchvplstash01.qvcdev.qvc.net:7990/scm/is/spring-config.git/zuul-gateway-service/application.yml",
"http://wchvplstash01.qvcdev.qvc.net:7990/scm/is/spring-config.git/application.yml"
]
},
"discoveryComposite": {
"description": "Spring Cloud Eureka Discovery Client",
"status": "UP",
"discoveryClient": {
"description": "Spring Cloud Eureka Discovery Client",
"status": "UP",
"services": [
"dcp-eureka-discovery-service",
"qards-bes",
"qvc-endeca-attribute-mapping",
"authentication-integration-service",
"qards-demo",
"zuul-gateway-service",
"dcp-spring-boot-admin-service"
]
},
"eureka": {
"description": "Remote status from Eureka server",
"status": "UP",
"applications": {
"ZUUL-GATEWAY-SERVICE": 1,
"DCP-EUREKA-DISCOVERY-SERVICE": 2,
"DCP-SPRING-BOOT-ADMIN-SERVICE": 1,
"QARDS-BES": 2,
"QVC-ENDECA-ATTRIBUTE-MAPPING": 1,
"AUTHENTICATION-INTEGRATION-SERVICE": 2,
"QARDS-DEMO": 1
}
}
},
"refreshScope": {
"status": "UP"
},
"description": "Spring Cloud Eureka Discovery Client",
"vault": {
"status": "UP"
},
"status": "UP"
}
},
"source": "discovery",
"metadata": {},
"info": {
"groupId": "com.qvc.dcp.integration.services",
"artifactId": "zuul-gateway-service",
"version": "0.0.1-SNAPSHOT"
}
}
```

**Comment by joshiste** [comment]
It's standard behaviour that all discovered services appear in the health endpoint from spring boot. I guess we need to restrict the search here a bit.

**Comment by cabbonizio** [comment]
Thanks for your response really appreciate it.  I did find also that is standard behavior as well.  Many thanks for offering to restrict the search I think it's a good idea given the nature of Spring Boot/Eureka health checks across registered services.   Will look out for future release with the new search.  Have a great weekend

**Comment by joshiste** [comment]
@cabbonizio could you try the `1.5.1-SNAPSHOT`?

**Comment by cabbonizio** [comment]
Will give it a try early this week.  Thx!

**Comment by oliviercoma** [comment]
I've tried 1.5.1-SNAPSHOT but I still have the issue. In the minified javascript, I didn't find the modifications of 98769ab though.

**Comment by joshiste** [comment]
The build wasn't triggered. I fixed this. the Snapshot should be available in about 1 hour.

**Comment by oliviercoma** [comment]
Thanks, it works.
When do you plan to release the 1.5.1 version? Possible to have the release soon? Thanks

**Comment by oliviercoma** [comment]
@joshiste Possible to release 1.5.1 for this issue?
Thanks
