### ISSUE TITLE
Display full MBean name in the list

### ISSUE THREAD

**Issue by lightoze** [codecentric/spring-boot-admin#439]
Sometypes MBean type and name is not enough to reliably distinguish MBeans:
![selection_006](https://cloud.githubusercontent.com/assets/534657/25237241/c3b6938c-25f2-11e7-8cf0-c7107e90fa54.png)

I know ActiveMQ may be to blame here, but can we at least have "title" attribute containing full MBean name (to display on mouse hover)? Ideally there could be some smarter logic deciding what to display to ensure situation like this does not happen.

**Comment by joshiste** [comment]
It's now rendered either with `name` or `title` and the `type`, also all attributes from the name are shown. Example:

![image](https://cloud.githubusercontent.com/assets/8779225/25437104/9dee6ea2-2a95-11e7-84f0-0a8dbfc8ec03.png)
