### ISSUE TITLE
why not use spring-cloud for client autodiscovery

### ISSUE THREAD

**Issue by Vad1mo** [codecentric/spring-boot-admin#44]
Why have an custom client if we can reuse the spring-cloud eureka client or event better connect directly to eureka server and get all the client list from there?

**Comment by RobWin** [comment]
You mean something like
https://github.com/VanRoy/spring-cloud-dashboard

**Comment by Vad1mo** [comment]
wow this could be it. Will give it a try. At the first glance it seems not using a custom client.

**Comment by denschu** [comment]
I'm disappointed :-( I don't understand why @VanRoy didn't get in contact with us to discuss this functionality.

**Comment by Vad1mo** [comment]
Yeah it seems to be a hidden fork. @VanRoy did a great job but I also think uniting the effort into one direction would be more effective in a long run. Do you think it would be possible to merge the projects? spring-boot-admin could rund as is and with spring-cloud if available.

**Comment by denschu** [comment]
Yes, we thought about to provide another implementation of the ApplicationRegistry which is backed by Eureka etc. Pull-Request and ideas are also always welcome...
