### ISSUE TITLE
datasource active connections

### ISSUE THREAD

**Issue by benson0217** [codecentric/spring-boot-admin#440]
when i use this yml setting
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
then  datasource active connections informataion will gone
is this normal??

**Comment by joshiste** [comment]
The datasource metrics are provided by the `DataSourcePublicMetrics` from the `PublicMetricsAutoConfiguration`. If your DataSource is still a bean, the information should still appear. The information is taken from the `/metrics`actuator endpoint. Make sure it's listed there. This is not a Spring Boot Admin issue. It's related to Spring Boot Actuator.

**Comment by benson0217** [comment]
Thank you for your reply
