### ISSUE TITLE
how to configure https between the spring boot admin and its client？

### ISSUE THREAD

**Issue by ExtremeYu** [codecentric/spring-boot-admin#448]
I hava a problem，could you please write a demo project to show how to configure https between the spring boot admin and its client. I hava read the issue [https://github.com/codecentric/spring-boot-admin/issues/399](url) but it is not useful. now the spring boot admin will reqest the client over https and http in both time.that lead to  a contrary result.
![image](https://cloud.githubusercontent.com/assets/16620268/25807551/ca8f8e3e-3439-11e7-883e-bf4485c0fa54.png)

!

**Comment by joshiste** [comment]
I guess you are using the latest 1.5.0?

Are you sure it's not just a leftover (in case your app was previously configured without https)?
The sba-client computes the url from your boot-config. The computation should always yield the same result and it, shouldn't register your application twice. Please remove the instance and watchout if it shows up again..

**Comment by ExtremeYu** [comment]
I solved it, the @EnableDiscoveryClient will let the spring boot admin send http request to client which configured with,I remove the  @EnableDiscoveryClient from all my client and now it become normal ,but can you tell me why? and what consequences will have if i remove all @EnableDiscoveryClient at Appmain from my client? i use 1.5.0 spring boot admin and 1.5.3 in spring boot, zookeeper 3.4.6 with spring-cloud-starter-zookeeper-all 1.1.0 release

**Comment by joshiste** [comment]
@ExtremeYu You must use either on of the DiscoveryClient implementations or the sba-client, but you must not use both. If you already use the DiscoveryClient for your applications, I'd suggest you just remove the sba-client from all your apps.
