### ISSUE TITLE
Configure build for coveralls.io

### ISSUE THREAD

**Issue by britter** [codecentric/spring-boot-admin#45]
I have activated coveralls.io for this repository: https://coveralls.io/r/codecentric/spring-boot-admin

Now the build needs to be configured, so that it reports coverage data to coveralls. More information can be found here: https://github.com/trautonen/coveralls-maven-plugin

An example configuration is here: https://github.com/trautonen/jersey-mustache

**Comment by dgomesbr** [comment]
According the documentation, since the project is building on travis-ci, we just need to edit the yml to get that integrated.

**Comment by britter** [comment]
Yes we have to add the coveralls-maven-plugin to pom.xml

**Comment by dgomesbr** [comment]
@britter Yeah, my mistake, gonna add it as well.

**Comment by dgomesbr** [comment]
uhhh... looks like I've open another pull request for the same branch, sorry, I'm getting used to it.

**Comment by britter** [comment]
No problem, you just have to reference #45 in your commits and the branch will automatically be attached to this issue.
