### ISSUE TITLE
The SBA had successfully setup,but some requst received  404

### ISSUE THREAD

**Issue by ExtremeYu** [codecentric/spring-boot-admin#451]
![image](https://cloud.githubusercontent.com/assets/16620268/25994340/1cc36b22-3740-11e7-8c21-583dc4aa27f3.png)

**Comment by joshiste** [comment]
Thats ok. This is how the UI checks for the available endpoints. If you get a 404 on these the according sections are hidden.

**Comment by ExtremeYu** [comment]
how to enable theme all and not to show 404？

**Comment by joshiste** [comment]
This only makes sense if you use the corresponding tools eg hystrix, flyway, liquibase... 
But this is described in our reference guide

**Comment by ExtremeYu** [comment]
thanks a lot！！
