### ISSUE TITLE
one project have tow clients and zuul exception?

### ISSUE THREAD

**Issue by SoberChina** [codecentric/spring-boot-admin#454]
Hello  everyone:
  I used spring boot admin  version:1.5.0 ;
 the first question  my server and my client is same project, why admin  have tow clients?  
the second question  I not used the zuul but the log exception is `
com.netflix.zuul.exception.ZuulException: Read timed out`

**Comment by joshiste** [comment]
SBA uses zuul internally. Also server and client is separated. If you also want to monitor the sba server itself, it needs either the sba client or a DiscoveryClient implementation.
