### ISSUE TITLE
Unable to run turbine-ui multiple beans

### ISSUE THREAD

**Issue by sba-123** [codecentric/spring-boot-admin#457]
Running the latest 1.5 and following the instructions the application fails to start with the error

RevereseZuulProxyConfiguration.preDecorationFilter() expected only one bean has two -:
TurbineAutoConfiguration.staticRouteLocator and RevereseZuulProxyConfiguration.applicationRouteLocator

Removing tubine-ui from the pom or excluding TurbineAutoConfiguration from the auto-configuration fixes this, although obviously turbine no longer functions.

Is there a work-around for this or is it a setup issue at my end?

**Comment by joshiste** [comment]
You're using the wrong version of spring-cloud. Please don't override the version sba depend on.
