### ISSUE TITLE
More than double the example？

### ISSUE THREAD

**Issue by SoberChina** [codecentric/spring-boot-admin#458]
Hello @joshiste Thank you for answering my question. my project tell me  instance REGISTRATION,
I know that my project is in error ,but why tell me instance registration？my 	Application list More than double the example。yesterday you tell me " must not use spring-boot-admin-starter-client and spring-cloud-discovery at the same time, just choose one of them!" I'm sure I just used one，
what does that mean  http://bogon:port？ Thank you again。
![image](https://cloud.githubusercontent.com/assets/10227558/26193124/ce75c57c-3be6-11e7-8449-757d02580441.png)

![image](https://cloud.githubusercontent.com/assets/10227558/26192938/177be7de-3be6-11e7-9747-53f46e501c6f.png)

**Comment by SoberChina** [comment]
admin_server  and goods-card  is my client

**Comment by joshiste** [comment]
Looks like one registration is with the hostname an one with the ip... 
can you show me the code of your `admin_server`?

**Comment by joshiste** [comment]
Your project works correctly on my machine. Maybe there is a second application from another machine registering at your admin?
Or the call to `InetAddress.getLocalHost(). getCanonicalHostName()` doesn't always return the same value... you could try to avoid that by setting `spring.boot.admin.client.prefer-ip=true`.
Or you tap the wire with tcpdump/wireshark and look where the requests come from...

**Comment by SoberChina** [comment]
@joshiste  ok Thanks!
