### ISSUE TITLE
Spring Boot Admin with Spring Batch integration

### ISSUE THREAD

**Issue by serhiikartashov** [codecentric/spring-boot-admin#461]
Hello everyone,

Do you have any plans for integration Spring Boot Admin with Spring Batch? Something similar with Spring Batch Admin. At least REST API monitoring, JMX, scheduling and running jobs, get status and progress, etc.

Thank you,
Serhii K.

**Comment by joshiste** [comment]
No we currently don't. But would indeed a nice feature. We're currently running Spring Boot Admin and Spring Batch Admin as separate apps.

**Comment by bhaskarmishra** [comment]
Any plans to implement this? It would be great and helpful to have this feature.

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.
