### ISSUE TITLE
Make timeouts for the status updater configurable

### ISSUE THREAD

**Issue by Japca** [codecentric/spring-boot-admin#462]
Hey folks,

We struggle little bit with apps which use admin. 
Problem occurs when:
1. server A running service dies (like totally crashes)
2. you try to restart application with admin included on server B (service from server A is still registred to this admin instance). The service on this server B takes long time to start -- **server/health** hanging over 3 minutes. 

We found out that there is no way to set connect/request timeout on RestTemplate that StatusUpdater uses. This is quite frustrating :)

**Comment by joshiste** [comment]
Sounds quite reasonable to add some properties to configure the timeouts. 
For now as a workaround you just need to instantiate the StatusUpdater with a properly configured RestTemplate yourself.

**Comment by Japca** [comment]
Thanks guys. This was really quick.
