### ISSUE TITLE
Spring Boot Admin Notifications

### ISSUE THREAD

**Issue by surajrrao** [codecentric/spring-boot-admin#463]
I am having issues with Spring Boot Admin in production sending notification that a particular microservice is offline/down though the service is up and running without any issues. Is this a known issue? Secondly, how can i have spring boot admin wait for 2 or more heartbeat interval before sending a offline/down status email.

Thanks in advance!

**Comment by joshiste** [comment]
Did you have a look at the admin server logs? It should give you some hints why they are classified as offline. You could write a delegating notifier which only tiggers the delegate when the offline status wasn't resolved after a period of time...
