### ISSUE TITLE
Hi bro please help me 

### ISSUE THREAD

**Issue by SoberChina** [codecentric/spring-boot-admin#464]
Hi @joshiste excuse me,
`spring.boot.admin.routes.endpoints` I use this configuration on my server side.monitor the sba server itself is valid ,but the client is in valid ,Why this configuration does not take effect for the client?
this is my client.
![image](https://cloud.githubusercontent.com/assets/10227558/26393863/b7b112ea-409d-11e7-9e88-93012a426928.png)
This is my server.
![image](https://cloud.githubusercontent.com/assets/10227558/26393962/0bc8beaa-409e-11e7-880f-ded53b6a6021.png)
server `Counter` is  ok  but `Gauges `
Thanks very much !
This is my project  [this](https://github.com/SoberChina/admin_server)

**Comment by joshiste** [comment]
The data is taken directly from the metrics endpoint. Your problem is related to the spring boot actuator. Not spring boot admin
