### ISSUE TITLE
Support for Spring Boot 2.0.0

### ISSUE THREAD

**Issue by micheljung** [codecentric/spring-boot-admin#465]
Spring Boot 2.0.0 is going to be released soon.

See PR #466

**Comment by anderius** [comment]
@joshiste: Is there any news about Spring Boot 2 support? Do you await the final release, or is there a snapshot somewhere? I would be happy to start testing if you have a branch somewhere! :-)

**Comment by wtatum** [comment]
I'd also be happy to do some testing against a snapshot release of 2.0.0. We're already using Boot 2.0.0 since we're not planning to go to production until well after the planned December 18 release of Boot 2.

**Comment by joshiste** [comment]
the master will switch to boot 2.0 when rc1 of it is published
.

**Comment by wtatum** [comment]
Thanks for the update @joshiste . I had that feeling from other threads but couldn't find anything official.

**Comment by n0mer** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes release notes for RC1 are available, although it is not yet relased (as per https://github.com/spring-projects/spring-boot/releases )

**Comment by joshiste** [comment]
Due date for the spring boot RC1 is January 25... s

**Comment by anderius** [comment]
https://spring.io/blog/2018/01/31/spring-boot-2-0-0-rc1-available-now

:-)

**Comment by perdonare** [comment]
2.0.0 RC1 available   Cann't wait for update

**Comment by HaVonTe1** [comment]
+1

**Comment by joshiste** [comment]
will merge joshiste/spring-boot-admin/2.x probably next week

**Comment by friddle** [comment]
great！

**Comment by perdonare** [comment]
ui related  module not in the snapshot repository

**Comment by joshiste** [comment]
`spring-boot-admin-server-ui` is in there. What are you missing?

**Comment by n0mer** [comment]
@joshiste Could not find `de.codecentric:spring-boot-admin-server-ui-activiti:2.0.0-SNAPSHOT`

https://oss.sonatype.org/content/repositories/snapshots/de/codecentric/spring-boot-admin-server-ui-activiti/ - latest is 1.5.8-SNAPSHOT

**Comment by n0mer** [comment]
@joshiste can you please elaborate how to use `spring-boot-admin-starter-client` for spring-boot 2.0? Client stopped working after updating to 2.0.0-SNAPSHOT

I'm using

```yaml
spring:
  boot.admin:
    discovery.enabled: false
    period: 30000
    url: "https://sba.domain.tld"
    username: "user"
    password: "password"
    autoDeregistration: true
    client:
      service-url: "http://${spring.application.name}.domain.tld:${management.port}"
      management-url: "${spring.boot.admin.client.service-url}${management.context-path}"
```

**Comment by firegnome** [comment]
@n0mer Try to use 2.0.0.RC1 instead of 2.0.0-SNAPSHOT for your spring-starter projects. I had trouble with this too.

**Comment by n0mer** [comment]
@firegnome

i have this

```
+--- de.codecentric:spring-boot-admin-starter-client: -> 2.0.0-SNAPSHOT
|    \--- de.codecentric:spring-boot-admin-client:2.0.0-SNAPSHOT
|         +--- org.springframework.boot:spring-boot-starter:2.0.0.BUILD-SNAPSHOT -> 2.0.0.RC1 (*)
|         +--- org.springframework.boot:spring-boot-starter-actuator:2.0.0.BUILD-SNAPSHOT -> 2.0.0.RC1 (*)
|    |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.0.0.RC1 (*)
|    |    +--- org.springframework.boot:spring-boot-starter:2.0.0.RC1 (*)
```

**Comment by firegnome** [comment]
@n0mer Is it working for you or not? You may also have to add the snapshot repository like i did for gradle:
`repositories {
	maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
	mavenCentral()
	jcenter()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}`

**Comment by n0mer** [comment]
@firegnome unfortunately, not - it is not even trying to register

**Comment by firegnome** [comment]
@n0mer ah I guess I see your problem, its in the yml configuration you need to do this:
`spring.boot.admin.client.url: http://localhost:8070`

The url configuration should be under client. Don't ask my why but i did debug it.

**Comment by n0mer** [comment]
https://github.com/codecentric/spring-boot-admin/commit/e0b60b5d36655ee2cd06adf39ad603a2a6c4b2c0 - this changeset introduced `ClientProperties`, that are referenced in `de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfiguration`

**Comment by n0mer** [comment]
boot-admin-server started working with this snippet in build.gradle:

```groovy

    ext {
        springbootVersion = '2.0.0.RC1'
    }

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group  == 'org.springframework.boot') {
            details.useVersion springbootVersion
        }
    }
}
```

@firegnome thanks for pointing to `spring.boot.admin.client.url`!

**Comment by n0mer** [comment]
JIC: has to add `    compile 'org.springframework.boot:spring-boot-starter-web'` , because spring-boot-admin-server 2.x uses spring-webflux (not using spring-web transitively), so my 

```yaml
management:
  server:
    servlet:
      context-path: "/management"
```

is taken into account on sba instance itself as well.

**Comment by joshiste** [comment]
> @joshiste can you please elaborate how to use spring-boot-admin-starter-client for spring-boot 2.0.RC1? Client stopped working after updating to 2.0.0-SNAPSHOT

All properties for the client were moved to `spring.boot.admin.client.*` so your properties need to be moved.

**Comment by joshiste** [comment]
> JIC: has to add compile 'org.springframework.boot:spring-boot-starter-web' , because spring-boot-admin-server 2.x uses spring-webflux (not using spring-web transitively), so my

Yes. We need the WebClient from webflux. So you know should explicitely choose the reactive or serlvet starter and choose. Currently both variants are supported on the admin server.

**Comment by joshiste** [comment]
p.s. sorry for the outdated docs. Any help appreciated :)

**Comment by firegnome** [comment]
Hi @joshiste you asked why 2.0.0-SNAPSHOT stopped working for us and why we are using 2.0.0.RC1. My problem was, that the method getWebserverId() was removed in the SNAPSHOT.

If you compare the javadoc you see that it was removed:
https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/api/org/springframework/boot/web/context/WebServerInitializedEvent.html

https://docs.spring.io/spring-boot/docs/2.0.0.RC1/api/org/springframework/boot/web/context/WebServerInitializedEvent.html

**Comment by joshiste** [comment]
@firegnome you have to use the SNAPSHOT afaik currently there is no cloud MS/RC based on boot.RC1 so we have to use the snapshot

**Comment by rahul-pharande** [comment]
@joshiste is there tentative date when RC will be available for spring-boot-admin

**Comment by joshiste** [comment]
no RCs just SNAPSHOTs. 
oss sonatype has no milestone repos.

**Comment by joshiste** [comment]
I'll investigate if a release without the spring-cloud part is viable

**Comment by Hronom** [comment]
June 13 is near is spring-boot will be released at the same time?

**Comment by joshiste** [comment]
@Hronom 
https://github.com/codecentric/spring-boot-admin/milestones

**Comment by n0mer** [comment]
@joshiste are you going to support flowable https://github.com/flowable/flowable-engine/issues/816 ?

**Comment by joshiste** [comment]
@n0mer No. But with 2.0.2 we have support for custom ui modules. So it would be possible to write a  community extension as standalone project.
