### ISSUE TITLE
Keycloak integration

### ISSUE THREAD

**Issue by radutoev** [codecentric/spring-boot-admin#469]
Hello,

If the spring rest endpoints are protected with keycloak and the keycloak spring boot adapter, is there a way to make the admin work with those endpoints? 

Thanks,
Radu

**Comment by joshiste** [comment]
Afaik the spring boot keycloak integration is using spring security - so this should be possible, but I can't give you any good examples. If you have concrete questions feel free to ask in out [gitter channel](https://gitter.im/codecentric/spring-boot-admin).

**Comment by leonardonunespuc** [comment]
Does anyone have any update on how to use Spring Boot Admin with an application that is secured with Keycloak using Spring Security?
