### ISSUE TITLE
Actuator login showing popup and not accepting yml configured password; compile group: 'de.codecentric', name: 'spring-boot-admin-server', version: '1.5.1' not working

### ISSUE THREAD

**Issue by mstommes** [codecentric/spring-boot-admin#472]
We are running into the actuator login window not accepting passwords.  This was working(we used the Basic Auth setup that you had posted) but since that that time the actuator auth seems to have broken.  In trying to resolve the issue I saw that there were quite a few updates made so I updated the dependencies. When I went to update the spring-boot-admin-server to verion 1.5.1  a compiler error showed up:   
------
These work but actuator does not with prod password:
#1
compile group: 'de.codecentric', name: 'spring-boot-admin-server', version: '1.4.6'
compile group: 'de.codecentric', name: 'spring-boot-admin-server-ui', version: '1.4.6'

#2 This works but no applications show up in the ui 
compile group: 'de.codecentric', name: 'spring-boot-admin-server', version: '1.4.6'
compile group: 'de.codecentric', name: 'spring-boot-admin-server-ui', version: '1.5.1'

#3 This breaks and results in a compiler error: 
compile group: 'de.codecentric', name: 'spring-boot-admin-server', version: '1.5.1'
compile group: 'de.codecentric', name: 'spring-boot-admin-server-ui', version: '1.5.1'

I think the error might be happening here but I'm not sure:

https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/config/RevereseZuulProxyConfiguration.java

------
I could keep the configuration for #2 and things all work except for the fact that the applications do not appear in the ui.  

At this point, any suggestions on how to resolve this would be great.  

Thank you,
Maria

**Comment by joshiste** [comment]
you should always align server-ui and server versions... 
Also you should really go for the 1.5.1
This also needs you to update to spring boot 1.5. and spring cloud dalston... 
For the compile error you are pointing, I guess you're using the wrong spring cloud version.

**Comment by mstommes** [comment]
You were right, this was the ticket:
"This also needs you to update to spring boot 1.5. and spring cloud dalston..."
Resolved the issue...really appreciate the quick reponse @joshiste.  Thank you!
