### ISSUE TITLE
Hystrix UI and Turbine UI  how to use ?

### ISSUE THREAD

**Issue by javanan** [codecentric/spring-boot-admin#473]
`
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-server-ui-hystrix</artifactId>
    <version>1.5.1</version>
</dependency>
`
Which service will you add?

> Add the /hystrix.stream to the proxified endpoints:

What do you mean?

How do I open the visual interface?

Is there an demo?

**Comment by suimi** [comment]
@javanan 
hi javanan,
 i used `spring.boot.admin 1.5.0`, get same error
`Unable to connect to Command Metric Stream 'api/turbine/stream?cluster=default'.
Error: {"isTrusted":true}`
do you have any solution?

**Comment by joshiste** [comment]
@bbaiggey see https://github.com/codecentric/spring-boot-admin/issues/657#issuecomment-396177252
