### ISSUE TITLE
logging managment feature not working with spring-boot-admin 1.5.1

### ISSUE THREAD

**Issue by EliaRohana** [codecentric/spring-boot-admin#477]
logging tab(logging managment) is not working with version of spring boot admin 1.5.1. with a spring boot client of 1.5.x

logging managment is not displayed because of wrong wrong endpoint status check. the application is trying to access
 http://localhost:8030/api/applications/80baae44/logging 
instead of 
http://localhost:8030/api/applications/80baae44/loggers
to check the state of the loggers.

when trying to access the spring-boot-admin loggers route directly using - http://localhost:8030/#/applications/80baae44/logging . works perfectly

## suggested fix:

[modules.js](https://github.com/codecentric/spring-boot-admin/blob/94aec760589f6c82d581909128c5935b1b16e80e/spring-boot-admin-server-ui/modules/applications-logging/module.js) need to fix the logging api path to loggers.

line 42 in the module.js mentioned above:
from:
`return $http.head('api/applications/' + application.id + '/logging')`
to:
`return $http.head('api/applications/' + application.id + '/loggers')`

**Comment by joshiste** [comment]
this bug is was introduced with #398 in 1.5.1...

**Comment by joshiste** [comment]
fixed with 1.5.2. I just hit the release button. Should be synced to maven central soon.

**Comment by joshiste** [comment]
Thanks for the report

**Comment by EliaRohana** [comment]
Thanks!
