### ISSUE TITLE
Metrics for servlet access @RequestMapping

### ISSUE THREAD

**Issue by sddakoty** [codecentric/spring-boot-admin#487]
It would be nice having a counter for all ```@RestController @RequestMapping``` servlets. They should be automatically detected without further configuration, and exposed as metrics.

For example the average time for response, number of invocations, and number of response codes.

Like:
```
    "GET /users":
   {
        "invocations": 7,
        "averageResponseTime": 1100,
        "200":6,
        "409":1
    },
    "GET /users/1":
    {
        "404":1
    }
```

**Comment by sddakoty** [comment]
Ok, this might come with developoment of spring-metrics?
https://github.com/spring-projects/spring-metrics

**Comment by joshiste** [comment]
spring boot already has this included: http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#production-ready-metrics
