### ISSUE TITLE
Retrieve contextPath from ServletContext instead of server.contextPath properties?

### ISSUE THREAD

**Issue by sddakoty** [codecentric/spring-boot-admin#488]
Would it be possible to change the ```DefaultApplicationFactory``` to retrieve the contextPath from ```ServletContext.getContextPath()``` instead of reading property ```.path(server.getContextPath())``` from ```server.contextPath```?

Or even better: just inject ```@Value("#{servletContext.contextPath}") String servletContextPath``` into the constructor.

Reason: when I deploy a *.war application to tomcat, I might create subcontext path like:
```
myapp#v1.war -> /webapps/myapp/v1
myapp#v2.war -> /webapps/myapp/v2
...
```

If always the ```server.contextPath``` property is read, I have to change that property in ```application.properties``` before redeployment.

But I would like to just rename the war file (eg myapp#v8.war), deploy and then spring-boot-admin should automatically register as a client using the .../v8 contextpath.

Currently the following is a workaround. It just overrides the contextpath dynamically retrieved from ServletContext.

```
@Configuration
public class AdminClientConfiguration extends SpringBootAdminClientAutoConfiguration {
	@Bean
	public ApplicationFactory applicationFactory(AdminClientProperties client,
	                                             ManagementServerProperties management, ServerProperties server,
	                                             @Value("${endpoints.health.path:/${endpoints.health.id:health}}") String healthEndpointPath,
	                                             @Value("#{servletContext.contextPath}") String servletContextPath) {
		server.setContextPath(servletContextPath); //<- this is the change
		return super.applicationFactory(client, management, server, healthEndpointPath);
	}
}
```

**Comment by joshiste** [comment]
You could just add your own implementation of the ApplicationFactory instead of this nasty hack. If you wan't to provide a PR to add this feature you're welcome.

**Comment by joshiste** [comment]
Hmm how do you know the port your tomcat ist listening on? Usually `server.port` isn't set for war-file deployments...

**Comment by sddakoty** [comment]
That's true, but it's the same with `server.contextPath`. This also has to be set even though not read by the tomcat server.
So currently I'm setting `server.port` in application.properties to the same port that tomcat is run in production. Even though the property is not read by the tomcat server, it can still be read by SBA.

But Maybe it would be even better to introduce a new property that only sets the host for SBA, like `spring.boot.admin.host=http://localhost:8080/`, and the context path is always derived dynamically from `ServletContext` bean. Instead of having to harccode the full url.

**Comment by joshiste** [comment]
With this commit two new properties were added to ease the client
configuration when used in servlet containers:
`spring.boot.admin.client.management-base-url` and
`spring.boot.admin.client.service-base-url`. Both properties can be used
to specify protocol, host and port for the urls. The paths will still be
guessed and appended to the base-urls. Additionally the servlet context
path is not read from the properties but from the ServletContext itself.

**Comment by sddakoty** [comment]
Great improvement, works as expected!
