### ISSUE TITLE
Admin UI not able to pick different application's context root

### ISSUE THREAD

**Issue by deepank-sharma** [codecentric/spring-boot-admin#496]
We have a set up of different microservices registered in Eureka server and all of them have a different context path set in their bootstrap.ymls.

Say Microservice 1:
Server.port: 8001
server.context-path: /v1/service1/

Say Microservice 2:
server.port: 8002
server.context-path: /v1/service2/

When I try to access these apps from Spring Boot admin dashboard I can only pull true details of only one of the applications as I can just set one management.context-path in the admin.

spring:
  application:
    name: solo-boot-dashboard
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /v1/service1 # OR /v1/service2/

Is there a way where I can see the details of all my services who each have a different context root.

**Comment by joshiste** [comment]
As described in http://codecentric.github.io/spring-boot-admin/1.5.2/#_serviceinstanceconverter this can be configured via the instance metadata. This way you get a per-instance config.
