### ISSUE TITLE
Timeout threshold for status change notification [Feature]?

### ISSUE THREAD

**Issue by sddakoty** [codecentric/spring-boot-admin#498]
Would it be possible to add a delay/timeout/threshold for status change notification?

Example: if I undeploy and redeploy an application at midnight, the status change should not send an OFFLINE notification to all team members listed in `spring.boot.admin.notify.mail.to`. 
Only if the application is not UP again within X seconds, the notifications are to be send.

As that possible as of now (I don't think so)? Or could be a feature for a future release?

**Comment by joshiste** [comment]
You can achieve that by a smart combination of the `RemindingNotifier` and `FilteringNotifier`
You need to build a notifier chain like that: `RemindingNotifier` --> `FilteringNotifier` --> 'MailNotifier`.

The `RemindingNotifier` will resend notifications as long as the application is not up again. The `FilteringNotifier`will throw them away while the filter is active. A filter can be set via the REST-api - which you need to do before the deployment and either you let the filter expire automatically or you need remove the filter after the deployment. If the application is back up before the filter expires you get no notification, but if the application doesn't come back online you will recieve notifications repeatedly until the application is back up again.

**Comment by sddakoty** [comment]
Thanks for the detailed insight. Maybe this should be added to the docs, as a showcase how to chain the `Notifier`?

**Comment by joshiste** [comment]
it is.. 
http://codecentric.github.io/spring-boot-admin/1.5.2/#filtering-notifications
>This examples combines the reminding and filtering notifiers. This allows you to get notifications after the deployed applications hasn’t restarted in a certain amount of time (until the filter expires).

 may be it should be more emphasized

**Comment by sddakoty** [comment]
Hm that's not quite what I was looking for. I don't want to call a Rest path explicit before deployment to add a temporary filter. I want to set a **global** period (eg 60s) in which status changes are ignored.

**Comment by joshiste** [comment]
Hmm that would lead to late notifications. At best you implement a `DelayingNotifier` which delegates to a real notifier which implements your desired behaviour. And if you're finished and would like to see this feature in SBA directly included - submit a PR ;)

**Comment by sddakoty** [comment]
Coming back to this, it would be sufficient if the /health polling interval could be configured. As a result any changes in the application state would automatically be delayed.

Or is there maybe already a property for it? At which time interval is the health point called by default, and where does this value come from?

**Comment by joshiste** [comment]
You can change the interval via `spring.boot.admin.monitor.period` (default: 10000ms). This would make it less likely but wouldn't totally prevent your application found offline - or you would need to sync your deployment with the health-checks.

**Comment by sddakoty** [comment]
What exactly is the difference to `spring.boot.admin.monitor.status-lifetime`? The docs state something about `/health` endpoint, so maybe those two properties could be combined?

**Comment by joshiste** [comment]
If the period is expired SBA is about to query all registered applications, except those whose status-lifetime hasn't expired. When an application registers in between a "full run", it's status is checked immediately and on the next run it's most likely to be ignored since the status-lifetime hasn't expired.

**Comment by sddakoty** [comment]
I see, so if I set period=60000, and status-lifetime=10000. If the app registers between 51-60sec of the period, then it will be ignored. Right?

**Comment by joshiste** [comment]
yes
