### ISSUE TITLE
Also showing the actuator trace..

### ISSUE THREAD

**Issue by enayet-repo** [codecentric/spring-boot-admin#500]
Hi,
Thanks…

I am having one issue with the following setup.

If I setup like –
My actual application – http://localhost:8080/example
My management url – http://localhost:8080/example/manage

Then in SBA UI If it try to access actuator’s trace/log, then it is also showing the actuator urls also, that means – /health, /info etc..
But, these info no need to show to the SBA user.

Please suggest me how can I omit them?

Thanks again…

**Comment by joshiste** [comment]
You can disable the endpoints in your client application if you don't want them to appear in the admin server.
