### ISSUE TITLE
how to use spring-boot-admin for non Spring Boot Project？

### ISSUE THREAD

**Issue by jeff-leo** [codecentric/spring-boot-admin#504]

**Comment by joshiste** [comment]
For non-boot applications you can only get health-monitoring. For this you need to do a `POST` request to `/api/applications` containing an json-object with the fields `name` and `healthIUrl`.

**Comment by omertopuz** [comment]
I have tried `/api/applications` endpoint but it fails. I think `/instances` endpoint should be used.
