### ISSUE TITLE
Could not create URI object: Expected scheme-specific part at index 5 : http

### ISSUE THREAD

**Issue by malijagadish** [codecentric/spring-boot-admin#506]
I get the "Could not create URI object: Expected scheme-specific part at index 5 : http" error repeatedly in the spring boot Admin console . Could someone please explain what is this error.
Also when i first time try to see the hystrix dash board through Spring Boot Admin server turbine options ,it does not load the dashboard .If i go to hystrix dashboard mannauly (http://servicehost:port/hystrix) then give the turbine url and clusters it works .After that only if i go to the Spring Boot Admin server it loads the hystrix dash.

**Comment by joshiste** [comment]
Could you post a stacktrace? Which version are you using?

**Comment by joshiste** [comment]
closing due to missing feedback

**Comment by jumkey** [comment]
may be the server hostname have a point like `server.1`
`UriComponentsBuilder.fromUri(URI.create("http://server.1:9090")).port(-1).pathSegment("").build().toUri()` throw error
@joshiste

**Comment by joshiste** [comment]
@jumkey A hostname component must not start with an digit!
Therefore `server.1` is not recognized as hostname but as authority.
See the BNF for URLs as defined by the W3C: https://www.w3.org/Addressing/URL/5_BNF.html

**Comment by shrikant606** [comment]
sorry this is late response but might save someones time in furture.
i was facing same issue. i was hitting "localhost:7089/api" was giving me same error, i changed it to "http://localhost:7089/api" and it worked.
give it a shot.

**Comment by huypham0427** [comment]
@shrikant606 I tried your way but it didn't work.
How can you test it? Did you test it on postman?

Thank you
