### ISSUE TITLE
client config for non boot app not working

### ISSUE THREAD

**Issue by abhaylangoti** [codecentric/spring-boot-admin#509]
Trying to configure a spring (non boot) app as client for admin server. This app has actuators enabled.
Added client dependency.
		<dependency> <groupId>de.codecentric</groupId><artifactId>spring-boot-admin-starter-client</artifactId><version>1.5.2</version></dependency>

No error, but app doesn't get registered with server

**Comment by joshiste** [comment]
If you are not using boot the autoconfig doesn't kick in automatically. You need to instantiate all facilities from `SpringBootAdminClientAutoConfiguration`

**Comment by abhaylangoti** [comment]
@joshiste thanks for quick solution. Only additional change that I had to make was to use ContextRefreshedEvent instead of ApplicationReadyEvent of boot in RegistrationApplicationListener class. Thanks, it is a wonderful project !!!!
