### ISSUE TITLE
Set Loglevel for all instances of an application

### ISSUE THREAD

**Issue by pirer** [codecentric/spring-boot-admin#510]
Hi everyone,
Do you have any plans for propagating setting through all nodes of registered applications? 

For example when you would like to change logging level on all nodes at once. 

Thanks 
Petr N

**Comment by mrumpf** [comment]
There must be a choice on whether an action should be executed on one or on multiple nodes.
When debugging a high traffic application it is probably wise to enable DEBUG level for one logger only for one node out of many nodes.
But when a service's log is too noisy, it would be cool to set the log to a silent level on all nodes at once. Especially if you have more than 2 nodes.

**Comment by maczikasz** [comment]
This would be a super awesome feature, it's marked as 2.0.0 are there any plans on when that will be implemented?

**Comment by adannunez** [comment]
Curious if there are any plans to support something like this through SBA in the near future? Or open to discussion on it leading to a contribution from someone?

**Comment by sdugan01** [comment]
Will this functionality be in 2.2.0 and when will it be released?

Thanks

**Comment by joshiste** [comment]
yes it is included in 2.2.0. Which will be release after Boot 2.2.0 and Cloud Hoxton

**Comment by sdugan01** [comment]
Do you have a estimate on the date for release?

**Comment by joshiste** [comment]
Hoxton is scheduled for November 07, 2019 so I guess we will release around November 15, 2019

**Comment by sdugan01** [comment]
thank you
