### ISSUE TITLE
used in docker,spring.boot.admin.client.prefer-ip=true but registration information is local ip

### ISSUE THREAD

**Issue by SoberChina** [codecentric/spring-boot-admin#511]
Hello everyone
   My admin server and  client deployed in docker, my client registration information log is 
```Application registered itself as {id=c398b0c3, name=goods_card, managementUrl=http://172.17.0.5:31944, healthUrl=http://172.17.0.5:31944/health, serviceUrl=http://172.17.0.5:8080, statusInfo={status=UNKNOWN, timestamp=1501497837450, details={}}, source=http-api, metadata={}, info={}}```
The information is local Ip,  My server and client are Different projects.
I set this configuration`spring.boot.admin.client.prefer-ip=true`, please help me. thanks very much!
SBA version is 1.5.0

**Comment by joshiste** [comment]
With `prefer-ip` you get the local ip. Your container doesn't know about your host-ip.
I'd suggest that you update to 1.5.3 and use the `spring.boot.admin.client.service-base-url` property and set it to your docker host address (via env-vars).

**Comment by SoberChina** [comment]
Just a minute, please.There are many servers,my clients are not in the same server.How can i do set it to my docker host address?I don't know how other people use it.thanks @joshiste

**Comment by joshiste** [comment]
you need to set the env var `SPRING_BOOT_ADMIN_CLIENT_SERVICE_BASE_URL=http://<yourdockerhost>:<mapped-port>`
on your docker container. I rarely can't provide you the values and please read the docker docs on how to obtain the values and set env-vars.

**Comment by SoberChina** [comment]
Thanks @joshiste ,But I don't know why I'm using the client registered IP, so why doesn't the server take the initiative to get the client's IP?
