### ISSUE TITLE
Enhancement to provide the health response body when it was in the DOWN state

### ISSUE THREAD

**Issue by vaisegid** [codecentric/spring-boot-admin#512]
It would be nice to store information about the DOWN state. We see temporal server status flip from the UP to DOWN and back but there are no way to check what part of the health check was temporally failing. This information could be provided in the journal page but even emitting to the logs with warning level would be sufficient.

**Comment by joshiste** [comment]
If you hover with the mouse over the statos on the jounrla page you should get some info.

**Comment by vaisegid** [comment]
Thanks, I found it. Good for now but it do not show nested statuses. Like there is "discoveryComposite" has "discoveryClient" and "eureka" nodes. .

**Comment by joshiste** [comment]
If you query the rest endpoint behind that view you should get them as well.
