### ISSUE TITLE
Version and build info not refreshed

### ISSUE THREAD

**Issue by melbichon** [codecentric/spring-boot-admin#514]
On application list page, version and build info are not refreshed when using Tomcat parallel deployment.
Details are well refreshed but not in the starting page.
Needs to restart webapp to refresh !
I'm using SimpleDiscoverClient.

**Comment by joshiste** [comment]
The info on the overview page is fetched by the backend and only updated when the status changes. So if your deployment doesn't trigger a status change the info isn't updated. There are two ways to circumvent this:
Either you deregister and register your application explicitly or you setup a scheduled task which invokes the `InfoUpdater`explictly.

**Comment by melbichon** [comment]
StatusUpdater only changes info if status has changed and I can't force queryInfo because method is protected.
Changing programmaticaly the status makes the work but notifications are triggered so it's not a good solution.
Any idea ?
