### ISSUE TITLE
(Question) Spring Boot Admin - info.version

### ISSUE THREAD

**Issue by jhelbling** [codecentric/spring-boot-admin#518]
We have a service which uses a custom context path. In order to correctly register our Service on Eureka Server, we've set the following:

```
eureka.instance.statusPageUrl=http://xxx/custom/info
eureka.instance.healthCheckUrl=http://xxx/custom/health
eureka.instance.homePageUrl=http://xxx/custom/
```

This is working well, our application gets registered. However, although we have set the info.version information, it doesn't get displayed on the Spring Boot Admin homepage. For our application where we don't have a custom context path, it's working:

![springbootadmin](https://user-images.githubusercontent.com/8075031/29154079-068c844a-7d92-11e7-9a57-e88dddf1e9c1.png)

Any idea which property(ies) is/are eventually missing?

**Comment by joshiste** [comment]
You need to specify the custom context path in the eureka instance metadata. All options are documented here http://codecentric.github.io/spring-boot-admin/1.5.3/#_converting_serviceinstances_into_monitored_applications (see Table 4.)

**Comment by jhelbling** [comment]
Thanks joshiste.

I added the following properties:

```
eureka.instance.statusPageUrl=http://myurl:8217/mycontext/info
eureka.instance.healthCheckUrl=http://myurl:8217/mycontext/health
spring.boot.admin.client.management-base-url=http://myurl:8217/mycontext
```

But it didn't help to get information like info.version beeing displayed. In the logs, I see the following:

`2017-08-11 10:42:54.619  INFO 7 --- [DiscoveryClient-CacheRefreshExecutor-0] d.c.b.a.registry.ApplicationRegistry     : New Application Application [id=7372c107, name=xxx, managementUrl=http://myurl:8217, healthUrl=http://myurl:8217/mycontext/health, serviceUrl=http://myurl:8217] registered `

I'm definitely missing something in order to correctly configure the context. Do you have any pointe?

**Comment by jhelbling** [comment]
Got it ... following was missing:

eureka.instance.metadata-map.management.context-path=/mycontext
