### ISSUE TITLE
 My client has a large number of /health checks

### ISSUE THREAD

**Issue by SoberChina** [codecentric/spring-boot-admin#519]
Hi everyone：
  My client has a large number of /health checks, through Trace, my server is also client, but my server does not have such a problem,please help me.
my sever config is 
`spring.boot.admin.monitor.period=1000
spring.boot.admin.monitor.status-lifetime=1000`
SBA version is 1.5.3
This is my admin server client 
![image](https://user-images.githubusercontent.com/10227558/29209872-5f266f76-7ec3-11e7-9171-c9e05c4f359c.png)
This is my other server client 
![image](https://user-images.githubusercontent.com/10227558/29209690-6fcdcc3a-7ec2-11e7-8177-a6991fba5d3e.png)
Thanks very much!

**Comment by joshiste** [comment]
did you check who is issuing the requests?

**Comment by SoberChina** [comment]
The host is my server

**Comment by SoberChina** [comment]
@joshiste   this is the trace info 
![image](https://user-images.githubusercontent.com/10227558/29255563-399ed0a4-80d5-11e7-8211-4d426bc8c780.png)
the host is my client server ip address.

**Comment by joshiste** [comment]
So apparently you solved your issue. Any findings you want to share?
