### ISSUE TITLE
Health-Check for non-Boot applications

### ISSUE THREAD

**Issue by jar349** [codecentric/spring-boot-admin#52]
Hello all, I really like this concept, and I've successfully registered my spring boot-based REST service.  Instead of using Spring MVC to serve views, I'm only providing a REST service and then I have an AngularJS web app (just static assets) using it.  Due to this, the service and the web app are deployed separately.

What I'd love to be able to do is have a simple health check on whether or not hitting the web app returns a 200 OK status, and to show the status on the admin console.  I can imagine a simple form that allows you to register a URL and an expected HTTP status code, along with how often to ping the URL.

I realize that this app is focused on monitoring spring-boot apps, but I don't think that what I'm doing is uncommon, and adding this health check would let me use the admin console to monitor my whole application until it grows to the point that I'd want to do something more heavy-weight.

**Comment by joshiste** [comment]
Do I get it rigth: you want to register some other health endpoint, than /health?
I don't know how big your static angular app is, but when their url is polled as endpoint everytime the whole app will be transmitted....

**Comment by jar349** [comment]
I wouldn't want to register '/' because it would transmit the whole app.  But in my static assets, I can create a /health.html page that returns a 200 or a /#/health Angular route that returns a 204.  This will be fast, and will show that my static assets are being served.

If I integrated a health indicator in my REST service, I don't know how I'd show the health information in spring-boot-admin.  Additionally, my REST service would become coupled to the web app.

**Comment by joshiste** [comment]
So can't you create a ``health`` file with content ```{ "status" : "UP"
}```.  This should work...
Though supporting non-boot apps is a feature we can discuss. But in my
opinion spring boot admin is not a 'enterprisey' monitoring solution,  it
merely helps to gather information about your applications.
Am 05.03.2015 19:26 schrieb "John Ruiz" <notifications@github.com>:

**Comment by joshiste** [comment]
So i'm currently working on seperating the health-url from the management-url, to support non-boot-actuator-apps. 
I'm just curious how you wan't to register your asset-server? Is there a need for specifying a 'static' application-list in sba?

**Comment by joshiste** [comment]
Closed with 742fa8a0d184ef0653bcc596a461e62dc700a48f.
Currently there is no "static" client configuration if realy needed open a second issue.
