### ISSUE TITLE
After adding Simple discovery client /env and /metrics stopped working

### ISSUE THREAD

**Issue by gunjank** [codecentric/spring-boot-admin#521]
After adding Simple discovery client - Below endpoints now called by using Request Method "HEAD" instead "GET" and calls are failing because client applications still have "GET" only support. 

Failed endpoint 
env, metrics. (Both are valid end points for client application and returning data with GET)

**Comment by joshiste** [comment]
SBA uses HEAD requests to determine the availability of the endpoints. If your application responses with a 200 for a GET and a 405 for a HEAD-request it doesn't comply to the HTTP-Spec.
So basically you should allow the HEAD requests for your client applications.

**Comment by gunjank** [comment]
It returns 400 . Also I don't think I could change my stable code. My app is spring boot app and it follows its rules. You are telling me to add support for head request manually.

**Comment by dmitrysenkovich** [comment]
Experiencing the same issue with Spring Boot 1.5.10 and Spring Adming 1.5.7

**Comment by pitinga** [comment]
I thing that the problem is related with this issue of Spring Actuator:
https://github.com/spring-projects/spring-boot/issues/10560
