### ISSUE TITLE
I have an idea about Automatically delete invalid application

### ISSUE THREAD

**Issue by SoberChina** [codecentric/spring-boot-admin#522]
Hi @joshiste 
   I have an idea,My clients often release versions,along with my hosts are changed, application  registered, the old application still exists ，Not automatically removed;
![image](https://user-images.githubusercontent.com/10227558/29267854-0eceeb3c-811d-11e7-876e-3510a95defb8.png)

I myself and realized this function，I hope the next version also has this function。

**Comment by joshiste** [comment]
Using the SBA client you can deregister the application on shutdown using `spring.boot.admin.auto-deregistration=true` and if you're using some kind of `DiscoveryClient` the stale applications should get removed automatically.
