### ISSUE TITLE
Follow of issue #521 - After adding Simple discovery client /env and /metrics stopped working #521

### ISSUE THREAD

**Issue by gunjank** [codecentric/spring-boot-admin#523]
Raising new issue for tracking because #521 closed 
Root Issue : 
After adding Simple discovery client - Below endpoints now called by using Request Method "HEAD" instead "GET" and calls are failing because client applications still have "GET" only support.
Failed endpoint
env, metrics. (Both are valid end points for client application and returning data with GET)

**As per #521 closed issue message these endpoints supposed to support GET and Head both** 
 
But this seems problem with Spring Actuator then, reason -- 
It returns 400 Bad Request. Both endpoints (env and metrics) are not something related to application code. These are Spring Actuator (internal) endpoints.
You are telling me to add support for head request manually (override it by custom code). Why should I change/override these endpoints (env/metrics).
Error details :: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'HEAD' not supported��

**Comment by joshiste** [comment]
Instead of opening a new issue you just could havre simply reopenend the last one.
Which version of Spring Boot are you using? Please provide a sample Project to reproduce the issue.

**Comment by gunjank** [comment]
Sorry, but don't see any option to reopen closed issue. 
1) My Spring Boot App is where Head call is failing - 1.4.2.RELEASE
2) For SBA APP I have used spring-boot-admin-server - 1.5.3 and spring-boot-starter-parent 1.5.6.RELEASE

**Comment by joshiste** [comment]
Generating a spring boot `1.4.x` application on http://start.spring.io with web+actuator and doing HEAD requests to `/env` and `/metrcis` totally works for me. The issue must be your configuration.

```
$ curl -I -vv http://localhost:8080/metrics
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> HEAD /metrics HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200
HTTP/1.1 200
< X-Application-Context: application
X-Application-Context: application
< Content-Type: application/json;charset=UTF-8
Content-Type: application/json;charset=UTF-8
< Content-Length: 623
Content-Length: 623
< Date: Fri, 18 Aug 2017 04:21:34 GMT
Date: Fri, 18 Aug 2017 04:21:34 GMT
```

So please provide a sample project (and with this I mean code) to reproduce the issue.

**Comment by joshiste** [comment]
Please give any feeback within 3 day or I'll close this issue.

**Comment by gunjank** [comment]
I have tested with a plain 1.4.2.RELEASE spring boot application and found both endpoint returning 200 -OK with Head method-Type . Still puzzled why my app which has no such configuration to disable HEAD or any type throwing 400 Bad Request. I will dig in and explore all used jars if something inside. For now good to close issue.
