### ISSUE TITLE
Notifications senMail(Do not need a password?) 

### ISSUE THREAD

**Issue by wzl1990** [codecentric/spring-boot-admin#524]
![image](https://user-images.githubusercontent.com/12508059/29411400-3b9ea730-8387-11e7-9834-c03c6eca8a6c.png)

spring.boot.admin.notify.mail.from MailSender 
Send mailer how to configure the password

**Comment by joshiste** [comment]
You need to configure the `JavaMailSender` using the `spring.mail.*` properties. See http://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/htmlsingle/#boot-features-email
