### ISSUE TITLE
spring.boot.admin.notify.mail.ignore-changes not work

### ISSUE THREAD

**Issue by lijie121210** [codecentric/spring-boot-admin#525]
I enabled <spring.boot.admin.notify.mail.enabled>, and set <spring.boot.admin.notify.mail.ignore-changes> a value, but still got notifications. I tried "UNKNOWN:UP" ; "OFFLINE:UP" ; "DOWN:UP".

**Comment by joshiste** [comment]
For having mail notifiactions you need to configure a `JavaMailSender`. See http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#boot-features-email
