### ISSUE TITLE
Spring boot admin displaying only details and trace tabs

### ISSUE THREAD

**Issue by venkattarigopula** [codecentric/spring-boot-admin#527]
Hello,

I am using spring boot admin (SBA) version 1.5.1 For my application which is running and registering in eureka. I am not using boot admin client or server libraries. SBA only showing two tabs ( trace and details )
Infact SBA showing all the tabs when i click the service and quickly  hiding rest of the tabs like ( metrics and environment etc.,) when i access the services actuator endpoints direcly like <appip:port>/context/metrics , it is displaying all metrics json. 

Please help me.
Regards,
Venkat

**Comment by joshiste** [comment]
SBA determines the availability of the endpoints by doing HEAD requests.
If these HEAD requests fail the corresponding tabs are hidden. So you need to figure out why these HEAD requests fail...

**Comment by venkattarigopula** [comment]
HEAD requests are fine. But my service is not on / context path. does it make any difference ? Thanks for the reply

**Comment by joshiste** [comment]
It shouldn't. Did you have a look in the browser's network console for errors?

**Comment by venkattarigopula** [comment]
Hi @joshiste  I have checked HEAD in postman , the response is 200 OK. all the actuator endpoints are accessible. By the way we have oauth in Zuul ( gateway )  no auth at service level. I have put spring security with all end points are accessible in  WebSecurityConfigurerAdapter

http.csrf().disable().authorizeRequests().antMatchers("/**").permitAll(); 

Thanks

**Comment by joshiste** [comment]
[There is a example security config in the reference guide](http://codecentric.github.io/spring-boot-admin/1.5.3/#_securing_spring_boot_admin_server)

**Comment by tjuchniewicz** [comment]
I have the same issue using 1.5.4. Security is disabled. Tabs are hided quickly. 
For example Details tab is visible under url: `/applications/6db88706/details`
Tab Metrics is not visible, but when I use this url manually: `/applications/6db88706/metrics` SBA shows valid content!

In browser console I see:
`HEAD .../api/applications/6db88706/metrics 405 (Method Not Allowed)`

For me issue appears only for Spring Boot 1.3.8 apps. When monitored application uses Spring Boot 1.5 it works fine.

**Comment by joshiste** [comment]
If Spring Boot Actuator 1.3.x doesn't support the HEAD request you could put a servlet filter in front... or update your application?

**Comment by tjuchniewicz** [comment]
This is not so easy in our environment to change microservice code. Too many services, too many teams. 
For me best solution would be to fix it in single place (SBA). Any tips where to change SBA source to show all tabs by default without changing availability?.  I will fork then.

**Comment by joshiste** [comment]
You could add a zuul filter to sba that handles theses HEAD requests...

**Comment by tjuchniewicz** [comment]
To SBA... Now I get it. I will try. Thanks!

**Comment by tjuchniewicz** [comment]
This custom filter works for me:
```java
/**
 * Fix for https://github.com/codecentric/spring-boot-admin/issues/527.
 * Based on {@link FormBodyWrapperFilter}.
 * 
 */
@Slf4j
public class SpringBoot13SupportFilter extends ZuulFilter {

    private Field requestField;
    private Field servletRequestField;

    public SpringBoot13SupportFilter() {
        this.requestField = ReflectionUtils.findField(HttpServletRequestWrapper.class, "req", HttpServletRequest.class);
        this.servletRequestField =
                ReflectionUtils.findField(ServletRequestWrapper.class, "request", ServletRequest.class);
        Assert.notNull(this.requestField, "HttpServletRequestWrapper.req field not found");
        Assert.notNull(this.servletRequestField, "ServletRequestWrapper.request field not found");
        this.requestField.setAccessible(true);
        this.servletRequestField.setAccessible(true);
    }

    @Override
    public String filterType() {
        return "pre";
    }

    @Override
    public int filterOrder() {
        return 1;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() {
        RequestContext ctx = RequestContext.getCurrentContext();
        HttpServletRequest request = ctx.getRequest();

        log.debug("Filtering {} request to {}", request.getMethod(), request.getRequestURL());

        if (request.getRequestURL().toString().contains("spring-boot-admin/api/applications")
                && request.getMethod().equals("HEAD")) {
            HeadToGetMethodRequestWrapper wrapper = null;
            if (request instanceof HttpServletRequestWrapper) {
                HttpServletRequest wrapped = (HttpServletRequest) ReflectionUtils.getField(this.requestField, request);
                wrapper = new HeadToGetMethodRequestWrapper(wrapped);
                ReflectionUtils.setField(this.requestField, request, wrapper);
                if (request instanceof ServletRequestWrapper) {
                    ReflectionUtils.setField(this.servletRequestField, request, wrapper);
                }
            } else {
                wrapper = new HeadToGetMethodRequestWrapper(request);
                ctx.setRequest(wrapper);
            }
        }

        return null;
    }

    private class HeadToGetMethodRequestWrapper extends HttpServletRequestWrapper {

        private HttpServletRequest request;

        HeadToGetMethodRequestWrapper(HttpServletRequest request) {
            super(request);
            this.request = request;
        }

        @Override
        public HttpServletRequest getRequest() {
            return this.request;
        }

        @Override
        public String getMethod() {
            return "GET";
        }
    }
}
```

**Comment by palamit21** [comment]
Hi ,
Both Admin and registered service 2.x version facing the below issue
in SBA expected registered service is 8 but in chrome 5 and firefox 8 missing the consistency of registered services.
Tried clearing the browser cache but the problem persist.

Please help!!

**Comment by brzler** [comment]
Having the exact same issue.

After upgrading to SBA 2 (from 1) only the "Details" tab is shown.
Old SBA 1 worked fine and displayed all tabs, new SBA 2 is missing all tabs except "Details".

What changed?

**Comment by joshiste** [comment]
@brzler with Spring Boot 2 by default most of the endpoints are not exposed via http. Check your config

**Comment by brzler** [comment]
No the problem was that the newest version of SBA Client and the Eureka Client don't report the right Endpoints to the Eureka Server/SPA Server:

SBA 2.0.2 UI shows:

http://domain.com:80080/myapp
http://domain.com:80080/myapp/actuator/
http://domain.com:80080/myapp/actuator/health

SBA 2.2.2 UI shows:

http://domain.com:80080/myapp
http://domain.com:80080/actuator/ <<< WTF is going on here???
http://domain.com:80080/myapp/actuator/health

To fix the issue I had to set:

eureka.instance.metadata-map.management.context-path=${server.servlet.context-path}/actuator

on **each** client ...

**Comment by joshiste** [comment]
there is also an option for the SBA server `spring.boot.admin.discovery.converter.management-context-path`

**Comment by brzler** [comment]
actually there are a lot of properties which result in the same outcome sooo ... which one is the most right one? xD

**Comment by joshiste** [comment]
for those parts which are the same for all clients use the server one for all parts inidividual to the client should be set in the client metadata.
