### ISSUE TITLE
How can we remove google analytics from the pages.

### ISSUE THREAD

**Issue by amitshukla30** [codecentric/spring-boot-admin#528]
I notices that Spring boot admin pages contains Google analytics and would like to remove it as I am not able to understand the purpose of adding analytics for such component.

Can you please let me know does removal removal of Google analytics violates your policy for the usage of this project? If no then, is there an easy way to remove it?

**Comment by joshiste** [comment]
There aren't any google analytics in Spring Boot Admin. So why do you think there are?

**Comment by joshiste** [comment]
Closing due to missing feedback.
