### ISSUE TITLE
Incompatible with Spring Cloud Dalston SR3

### ISSUE THREAD

**Issue by JWThewes** [codecentric/spring-boot-admin#529]
We updated to Spring Cloud Dalston SR3 and our application won't start anymore. Problem is a NoClassDefFound exception for org/springframework/cloud/netflix/zuul/ZuulConfiguration.
If I find some time I'll dig deeper. Just the issue first as a reminder.

**Comment by barrycommins** [comment]
The class has been renamed. See: https://github.com/spring-cloud/spring-cloud-netflix/pull/2170/files#diff-7d64ed23121818ae4be22e1acbcb8992
