### ISSUE TITLE
Integration in existing projects?

### ISSUE THREAD

**Issue by riy** [codecentric/spring-boot-admin#53]
I'm trying to integrate Spring Boot Admin, along with the Server UI and the Admin Client, in an *existing* Spring Boot project. After including the three dependencies I also added the appropriate application.properties settings (my main application runs under the root context):

    spring.boot.admin.url=http://localhost:8080

In the log files I see that the application does register itself but I still can't access the Admin UI using http://localhost:8080/admin, which returns a 404.
Could this be because my main application already has a controller matching against `api/**`, effectively intervening with internals of Spring Boot Admin?

Now if I read the docs again and understand them correctly then the Spring Boot Admin application needs to be deployed as its own application, with the Admin Client deployed in the main application. Is it correct that I can't run it along with my main application?

Sorry for brevity, I thought I'd keep things simple here instead of posting lots of code. Please let me know if you need me to post anything in addition.

Thanks
Rias

**Comment by joshiste** [comment]
Hey Rias,

If you remove @EnableAdminServer and import a subclassed admin WebappConfig
with a subclassed registry controller it should be possible to change the
mapping. You have to configure the context path in the client also,  via
property.

BUT,  i advise you to not include the admin in the main app...
Am 12.03.2015 09:34 schrieb "Rias A. Sherzad" <notifications@github.com>:

**Comment by riy** [comment]
Danke Dir für die schnelle Rückmeldung :-)

Awesome - alright, I think I'll be setting up a separate webapp for the Admin Server. I guess that makes very much sense, having a centralized Admin Server...

Thanks
Rias
