### ISSUE TITLE
Missing description of Parameters in JMX operations

### ISSUE THREAD

**Issue by frkautz** [codecentric/spring-boot-admin#531]
I upgraded the spring-boot-admin-server and spring-boot-admin-server-ui from 1.3.7 to 1.5.3. In our services (spring-boot-admin-starter-client) we use 1.3.x, 1.4.x. and 1.5.x. In the spring boot admin server UI we are missing the description of the parameters from all JMX operations. This happens with our JMX operations and also with the operations from java.lang and other domains. We have the issues with all services, so I think it is an issue in the spring-boot-admin-server or spring-boot-admin-server-ui. The two attached screenshots shows the JMX operations in the UI in the different UI versions.
![jmx_endpoint_sba_1 3 7](https://user-images.githubusercontent.com/29547723/29620531-782f7a9e-881e-11e7-87b4-c888005f3e2f.png)
![jmx_endpoint_sba_1 5 3](https://user-images.githubusercontent.com/29547723/29620533-7ab85286-881e-11e7-87dd-9ed0822b27c9.png)

The relevant code snippet:
```@ManagedOperation(description = "Sets legal terms lock on a given account")
@ManagedOperationParameters({
        @ManagedOperationParameter(name = "accountId", description = "The id of the accountuser aggregate"),
        @ManagedOperationParameter(name = "legalTermsLockReason", description = "Reason for legal terms lock (BOUNCE, CANCELLATION")
})
public void setLegalTermsLock(String accountId, String legalTermsLockReason) {
       …
}
```

**Comment by joshiste** [comment]
Yes indeed. The description is gone missing.

**Comment by joshiste** [comment]
I'll target that for the next release

**Comment by frkautz** [comment]
Hi joshiste,

I tested the version 1.5.4, but issue isn't gone. Can you reopen the ticket.

kind regards,
Frank

**Comment by joshiste** [comment]
@frkautz Did you have a look into the jolokia response if the description is provided by jolokia? (and made sure you didn't had an old version from browser cache)?

**Comment by frkautz** [comment]
@joshiste Yes, the jolokia request contains the description and I also deleted the browser cache and checked the version of the UI. The about section shows version 1.5.4.  
```
"accountuser":{
	"name=LegalTermsLock":{
		"op":{
			"setLegalTermsLock":{
				"args":[{
					"name":"accountId","type":"java.lang.String",
					"desc":"The id of the accountuser aggregate"
				},{
					"name":"legalTermsLockReason","type":"java.lang.String",
					"desc":"Reason for legal terms lock (BOUNCE, CANCELLATION"
				}],
				"ret":"void","desc":"Sets legal terms lock on a given account"
			}
		},
		"desc":"Allows to manually set legal terms lock for testing purposes"
	}
}
```

**Comment by frkautz** [comment]
@joshiste somehow a strange behavior after I deleted the  browser cache it didn't work, but during analyzing the jolokia request it shows the description. So ignore my request to reopen the ticket.
