### ISSUE TITLE
Causes logback to generate the LOG_PATH_IS_UNDEFINED folder

### ISSUE THREAD

**Issue by lijie121210** [codecentric/spring-boot-admin#532]
Using the spring-boot-admin in the project and config log with logback-spring.xml file, the app then generated LOG_PATH_IS_UNDEFINED folder;

I use the same configuration file, the same steps to create a new project that will not generate this folder before joining the framework;

Any idea ? Thanks.

**Comment by joshiste** [comment]
Spring Boot Admin should not influence your logback config.
Did you have a look at this Spring Boot Issue https://github.com/spring-projects/spring-boot/issues/1434 ?

**Comment by lijie121210** [comment]
Yes, I read and solved the problem. But the strange thing is: when I remove spring-boot-admin, keep spring-boot, the problem does not exist.
