### ISSUE TITLE
auto-deregistration seems not working in 1.5.3

### ISSUE THREAD

**Issue by hotstepper13** [codecentric/spring-boot-admin#533]
We have updated SBA to 1.5.3 and have 2 additional microservices connected (via spring boot admin client) along with SBA itself. Everything is running inside kubernetes.

spring.boot.admin.auto-deregistration is set to true (in the sba server)

OFFLINE applications are not removed automatically.

Even after several minutes the OFFLINE application is still shown.

Testcase:
run SBA
register application at SBA
kill application and ensure the same application register with different hostname/containerid

You should see now 1 up and 1 Offline application.

I am not sure if I am missing configuration or if this might be a bug.

**Comment by aantono** [comment]
Looking at the code I'm not even seeing where this property is being consumed or bounded to a Properties object...

**Comment by joshiste** [comment]
`spring.boot.admin.auto-deregistration` must be set on the client side and relies on proper shutdown of the application context.

**Comment by arahlf** [comment]
Did you ever figure out a solution to this? I'm facing the same issue (where old pods aren't deregistering themselves).

I'm not exactly sure how the old pods are being killed (SIGTERM, SIGKILL, something else, etc.)... Can you further explain what it means for the proper shutdown of the application context (like, does SIGTERM fit that bill)?

**Comment by arahlf** [comment]
What version of Spring Boot Admin are you using? I'm in the process of hooking up the k8s discovery client right now, and looking at the source of InstanceDiscoveryListener, there appears to be some code in that method that calls removeStaleInstances -- not sure if that's new or not.

**Comment by aantono** [comment]
Oh, nice, looks like it was added in 2.0.  We were migrating from 1.5 line, which didn’t have this feature.
