### ISSUE TITLE
How can I store traces of requests in SBA?

### ISSUE THREAD

**Issue by christianf2029** [codecentric/spring-boot-admin#534]
I am new to SBA, but I was wondering if there is a way to store all the requests of a certain registered application for future queries and filters. Has as?

I know this is not an issue but I did not find another place to report me quickly.

**Comment by joshiste** [comment]
The traces are just taken from the `/traces` endpoint of the application, so no persistence involved.

If you want to persist the traces i suppose you should implement you own `TracesRepository` for spring boot. But may be it's just easier to log each request into a logfile.
