### ISSUE TITLE
Unable to add apikey to header to call application's health point

### ISSUE THREAD

**Issue by anarwal27** [codecentric/spring-boot-admin#536]
I have been trying to resolve a problem with registering my application(REST APIs) with Spring-boot admin console. Application goes and registers itself with admin, following to that admin has to make calls to health end point of application, which fails as application has a API gateway in front of it and needs apikey added to all the calls being made to it . Now I have tried couple of different ways suggested by Spring-boot security (https://codecentric.github.io/spring-boot-admin/1.5.0/#securing-spring-boot-admin) to send apikey as a part of header but still every time call is going without key. Is this some functionality not supported yet?

**Comment by joshiste** [comment]
Headers provided by your custom `HttpHeadersProvider` implementation should be included in every request... So this should basically work. May be you can provide a sample project so i can figure it out?

**Comment by anarwal27** [comment]
Okay, looks like it is yet to be documented as mentioned here: https://github.com/codecentric/spring-boot-admin/issues/442 So did not try this, let me give it a shot and if it doesnt work, will put together an example for you.

**Comment by joshiste** [comment]
after 9 days without feedback I close the issue. I guess you could solve your problem.

**Comment by anarwal27** [comment]
The changes you suggested, got it to work. Due to long weekend in between it got missed.
