### ISSUE TITLE
How to use the spring-boot-admin on general spring framework project？

### ISSUE THREAD

**Issue by workcheng** [codecentric/spring-boot-admin#539]
I try to use  spring-boot-admin in my spring project，but it not work. And I use spring framework version is 4.2.4.RELEASE

**Comment by joshiste** [comment]
You can use it with spring only. But:
1) your monitored applications must provide the spring boot actuator endpoints (or at least a heatlth check endpoint)
2) If you want to use the SBA client you would need to apply the AutoConfiguration yourself
