### ISSUE TITLE
Time series for metrics-view

### ISSUE THREAD

**Issue by BERA** [codecentric/spring-boot-admin#54]
Hi 

Would be nice to have a feature to monitor in real time the number of requests received by a 
spring boot application over the time and a time series to show that.

What do you think guys about it?

**Comment by joshiste** [comment]
So you mean a view for watching the /metrics-endpoint change over time?
There will be no persistent history data and data will only be collected as
your browser stays open.

If you want to do this right i would suggest you to export  boot-actuators
metrics into graphite or influxDB. These are tools especially made for
that.
Am 13.03.2015 18:46 schrieb "Bera" <notifications@github.com>:

**Comment by Bera** [comment]
Perfectly Joshiste

I agree with you. I just need to export the metrics-endpoint periodically  to influxDB.

**Comment by RobWin** [comment]
Wow influxDB looks neat. Thx

**Comment by agrawalchetan** [comment]
HI, I am facing compilation error pom.xml for npm-install.

**Comment by joshiste** [comment]
@agrawalchetan can we discuss this in [gitter](https://gitter.im/codecentric/spring-boot-admin) for not polluting this issue?

**Comment by andreashouben** [comment]
As there has not been an update to this issue in a long time I'm closing it. Feel free to reopen it if you think there is still something to be done.
