### ISSUE TITLE
SBA Exception on Weblogic: Can NOT error at this state: AsyncCompleted.

### ISSUE THREAD

**Issue by danic21** [codecentric/spring-boot-admin#540]
Hello,

I have installed SBA (1.5.4) on Weblogic 12.2.1.0. Everything looks ok, except for the fact that every time the SBA application is loaded and running in the browser, I get the following exception every 10 seconds. Any idea why this happens?

Thanks in advance!

BR,
Daniel

> ####<Sep 6, 2017 2:43:21 PM CEST> <Error> <Kernel> <CIS1109685> <AdminServer> <[ACTIVE] ExecuteThread: '10' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <23725e89-13d2-41c3-a077-5fb3b94305d2-00000031> <1504701801246> <[severity-value: 8] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000802> <ExecuteRequest failed
>  java.lang.IllegalStateException: Can NOT error at this state: AsyncCompleted.
> java.lang.IllegalStateException: Can NOT error at this state: AsyncCompleted
> 	at weblogic.servlet.internal.async.DefaultState.notifyError(AsyncStates.java:62)
> 	at weblogic.servlet.internal.async.AsyncContextImpl.handleError(AsyncContextImpl.java:134)
> 	at weblogic.servlet.internal.async.DispatchHandler.run(DispatchHandler.java:38)
> 	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:643)
> 	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:348)
> 	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:333)
> 	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:54)
> 	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
> 	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:617)
> 	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:397)
> 	at weblogic.work.ExecuteThread.run(ExecuteThread.java:346)
> >

**Comment by joshiste** [comment]
SBA uses Server Sent Events for notifications and status updates. The error you are getting is related to Spring's SSE implementation and does occur when the request times out. You don't need to worry about it.

**Comment by danic21** [comment]
Thanks for your reply.

What causes this exception? Is there some configuration missing on WL?

Having an application that throws an exception every 10 seconds is not really reassuring. And, unfortunately, it's my job here to worry about things like this. :)

**Comment by joshiste** [comment]
The http request for just times out. There is nothing you can do about...

> Is there some configuration missing on WL?
I am not familiar with WL - so I cant tell...

There has been some similar issue #317  with running on tomcat. But adding a ExceptionHandler resolved that. If you really want to resolve this problem I guess there is no way around for you than to dig deeper into that. You should look into the Spring Framewor'ks issue tracker if someone else reported similar issues with timeouts on server sent events.
