### ISSUE TITLE
How can I store journals in SBA?

### ISSUE THREAD

**Issue by sunnykaka** [codecentric/spring-boot-admin#541]
If I restart SBA, the journals are gone.

How could I persist them?

**Comment by joshiste** [comment]
Either you implement the `JournaledEventStore` interface with your custom implementation. Or you tell your SBA Server to use Hazelcast and configure Hazelcast to persist the data on disk. How to use Hazelcast with SBA is described in the docs and for the Hazelcast configuration itself please have a look at the Hazelcast's documentation.

**Comment by sunnykaka** [comment]
@joshiste 

Thanks. I have checked Hazelcast's documentation.

Hazelcast was not adopt in my project, I wan't to persist journals in Redis or MySQL.
