### ISSUE TITLE
SBA is doubling services when there are multiple admins

### ISSUE THREAD

**Issue by christianf2029** [codecentric/spring-boot-admin#546]
I have two Eureka Server instances running locally (which are administrators). I also enabled Hazelcast (for example in the documentation). I bind this clients on an of the instances of the Eureka Server and I'm waiting for replication, but here's the problem.

**These clients are being registered twice**

When I disable the admin client in the services (via application.yml: `spring.boot.admin.client.enabled: false` ), the instance is registered regularly on one server and replicated to the others (but it is not what I want because it up unmonitored). Image below:

![image](https://user-images.githubusercontent.com/16386736/30224774-6e6a9c5c-94a6-11e7-9801-b8e6db04d9ae.png)

But when I enable and execute again, I have the following result:

![image](https://user-images.githubusercontent.com/16386736/30224959-15c170fc-94a7-11e7-8628-a21cdafca255.png)

The first instance showed of CloudConfig is monitored regularly, the second no.

Then I do not know if it's registering again or if it's some conflict in showing the clients or something related to my configuration here. What's happening?

**Comment by joshiste** [comment]
You should either register the services via eureka or via sba client. But you must not use both at the same time.

**Comment by christianf2029** [comment]
Dude, that's not what's happening. I removed the @eurekaclient the CloudConfig here and got the same problem with the two servers. When I have a single administration server I do not have this problem, even with @eurekaclient and SB client. It seems that there is some communication error of the SB between servers.

**Comment by joshiste** [comment]
Could you please provide a sample project for me to reproduce the issue?

**Comment by joshiste** [comment]
Closed due to missing feedback
