### ISSUE TITLE
List down/offline applications at the top of application list

### ISSUE THREAD

**Issue by ccit-spence** [codecentric/spring-boot-admin#55]
Fairly simple, If I get a chance may do it myself. The idea would be any Application that is not `UP` would go to the top of the list sorted by severity.

**Comment by joshiste** [comment]
In master branch the columns are already sortable.
Am 14.03.2015 10:00 schrieb "ccit-spence" <notifications@github.com>:

**Comment by ccit-spence** [comment]
Does the sorting change on refresh?  My thought is lets say you have 300 services it would be nice to see the problems dynamically on the top.

**Comment by joshiste** [comment]
Not tested but it should.
Am 14.03.2015 10:08 schrieb "ccit-spence" <notifications@github.com>:

**Comment by ccit-spence** [comment]
Ok, right now I am using the maven central build.
