### ISSUE TITLE
Add type that caused health status change in MailNotifier

### ISSUE THREAD

**Issue by sddakoty** [codecentric/spring-boot-admin#551]
`MailNotifier` sends notifications like `<appname> status changed from UP to DOWN`.

Problem: you never know if it was the entire application, the diskSpace, the database, whatsoever.

It would be great if the notifier could also report the root cause of the status change. The `/health` check at least supports specific status changes, eg:

`{"status":"UP","db":{"status":"UP","database":"MySQL","hello":1}}`

**Comment by joshiste** [comment]
You can customize the default the default text using `spring.boot.admin.notify.mail.text`.  You can access the status details via `#{to.details}`

**Comment by sddakoty** [comment]
Unfortunately this is not documented. Maybe the docs could be improved?

**Comment by joshiste** [comment]
the SpEL expression is correct. I just returns a `Map<String, Serializable>` and not a string as you expected... So you need to convert the map with the details to a`String`...

**Comment by sddakoty** [comment]
So and how could I achieve that in plain SpEL? As my goal was just include the health details plain in the mail...

**Comment by joshiste** [comment]
`toString()` ???

**Comment by sddakoty** [comment]
Adding `#{to.details.toString()}` to the mail text message leads to the following content when status:
From OFFLINE/DOWN to UP: the details are printed as expected.

But from UP to OFFLINE gives following error in notification:

```
status changed from UP to OFFLINE

{exception=org.springframework.web.client.RestClientException, message=Could not extract response: no suitable HttpMessageConverter found for response type [interface java.util.Map] and content type [text/html;charset=utf-8]}
```

Could this be prevented somehow to send an exception as notification?

**Comment by joshiste** [comment]
As you can see from your String the exception is inside the map ... you just need to transform it correctly to a String.

Maybe this is to complex for SpEL and you should override the `getText()` method in `MailNotifier`

**Comment by y-luis** [comment]
How to use only the override version of `MailNotifier` and "disconnect" the built-in?
