### ISSUE TITLE
Error loading JMX tab

### ISSUE THREAD

**Issue by jlsalmon** [codecentric/spring-boot-admin#554]
Hi,

First off, thanks for the awesome work on this dashboard! It's super useful.

I'm not able to see the JMX tab in any of my applications currently (1.5.2). I can see the following error in the console:

```json
POST http://pscom1201:8100/admin/api/applications/57bf084d/jolokia/
{
  "timestamp": "2017-09-13T11:28:10.889+1000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Duplicate key *",
  "path": "/admin/api/applications/57bf084d/jolokia/"
}
```

Happy to provide any more debugging info as required. Also willing to make a PR to fix if someone could point me in the right direction.

Any help would be very much appreciated!

Cheers,
Justin

**Comment by joshiste** [comment]
So when you have a `500` there should also be an exception either in the admin's or application's log (probably with a stacktrace...). Did you have a look in there?

**Comment by jlsalmon** [comment]
Thanks for your quick response @joshiste. I tracked down the error in the admin server log, and it was due to an issue in my own code that was throwing an exception inside an HTTP interceptor.
