### ISSUE TITLE
Cached Data Issue on Applications View

### ISSUE THREAD

**Issue by azizabah** [codecentric/spring-boot-admin#556]
We're seeing an issue where the main applications view is occasionally out of sync with the details view of an individual service. Mainly noticing it on the git commit that is deployed. 

So on the applications view we're seeing:
git:
  commit:
    time: 1504278558000
    id: xxxx
  branch: feature/integrateWithSBA

But when I click details for that service I immediately get:

git | commit:   time: 1505414187000   id: xxxx branch: story/rk-validation
-- | --

If I go back to applications view by clicking on the spring leaf, it still displays the old values. It doesn't seem to be a timing issue since the rk-validation branch has been deployed into our environment for over four days at this point. 

Is there a caching issue or config setting we can use to get it to refresh those values correctly?

Thanks!

**Comment by joshiste** [comment]
Same problem as in #514 for performance reasons the info is cached on the server side and currently only refreshed if the application status changes...

**Comment by azizabah** [comment]
@joshiste it would be nice to make it more configurable or do some kind of data "staleness" check when you go from applications view to a detail view and if they're out of sync, force a refresh.

**Comment by joshiste** [comment]
In case you use the sba client you can use the auto-deregistration feature as a workaround.

**Comment by azizabah** [comment]
We're using a service registry and having SBA discover all the services that way so I don't think that would work if I understand the behavior correctly.

**Comment by szisti** [comment]
@azizabah I'm using service discovery with zookeeper 
If I shut down an instance for a release it triggers a deregistration event and gets removed from the list 
Few seconds later the new instance pops up but gets all its details read again 
Only had issues with clients which used the client dependency and that got solved with the auto deregister configuration option
