### ISSUE TITLE
Support for multiple users in administration server

### ISSUE THREAD

**Issue by christianf2029** [codecentric/spring-boot-admin#557]
Imagine that I have a range of services and I have people and teams working on them. I did not want everyone to see and manage all the services, I wanted them to visualize and manage only theirs. Only one super user, or some, could manage the entire cloud, which I think is entirely valid. From the little I've seen, we still do not have this support, am I mistaken? If so, is there any hope?

**Comment by joshiste** [comment]
Currently there isn't and it's not on my todo list. Imho you better setup a admin server for each user group. An application is capable of registering at multiple admin servers (either with SBA client or using a discovery implementattion). Or you implement your own `ApplicationController` which takes account for the reduced visibility.
