### ISSUE TITLE
Register (and show) service- and management-url

### ISSUE THREAD

**Issue by ccit-spence** [codecentric/spring-boot-admin#56]
This would probably need another definition within the spring-boot-admin-client.  Maybe an `info` property.  Basic idea is that aside from the url that exist now `http://hostname/admin` be able to define an entry point that could open in another window to view the service.

**Comment by joshiste** [comment]
So splitting service and management url?
Am 14.03.2015 10:07 schrieb "ccit-spence" <notifications@github.com>:

**Comment by ccit-spence** [comment]
Yes, since an admin would be looking at the dashboard it could help to have a link to view the actual service.  Just a thought.

**Comment by joshiste** [comment]
Closed with 742fa8a0d184ef0653bcc596a461e62dc700a48f.
