### ISSUE TITLE
Metrics with ".min" or ".max" in their name not rendering correctly

### ISSUE THREAD

**Issue by talbert83** [codecentric/spring-boot-admin#561]
I have some custom metrics with keys containing ".min", like "rpm.last.5.minutes" and noticed that they are not displayed correctly in SBA Metrics tab. The key is truncated and displays only the part before ".min" and no value is shown. I performed some tests and found that both ".min" and ".max" behave in the same way and I'm guessing that they are interpreted by javascript in some way, so there may be other keywords that behave in the same way. Using upper-case solves the issue.

Here's an example (I changed the original keys for testing):
```
    {
        gauge.test1.min: 11,
        gauge.test2.minutes: 2.2,
        gauge.test3.max: 0.7333333333333333,
        gauge.test4.maximum: 0.18333333333333332,
        gauge.test5.MIN: 0.007638888888888889
    }
```
Will result in this in the UI:
![image](https://user-images.githubusercontent.com/32326871/30912063-d10d6988-a393-11e7-93af-00dea20143bc.png)
Only the last metric is displayed correctly.

I used SBA version 1.5.4.

**Comment by joshiste** [comment]
I guess the metric is incorrectly recognized as rich gauge. Since the metrics endpoint has totally changed with spring boot 2.x I don't want to put much effort in this issue, but if you want to submit a  PR fixing this issue, I'll have a look into it.

**Comment by talbert83** [comment]
Thanks for looking into this. I guess the fix would need to be done on the UI side, which I'm not familiar with, so I guess I'll stick to the workaround with uppercase keys. Looking forward to the new versions of spring boot and admin!
