### ISSUE TITLE
Turbine Stream Zuul path /api/turbine/stream?cluster= sends data intermittently

### ISSUE THREAD

**Issue by dbcall2** [codecentric/spring-boot-admin#563]
Hi,

I'm using the turbine-ui plugin and noticed that the turbine page loads but is stuck with the double "loading..." message for a very long time. When I hit the turbine.stream endpoint directly on the turbine server it streams the updates just fine. However, when I hit the /api/turbine/stream endpoint on the admin server it seems to hang with the pipe open, then bursts a bunch of updates, and then hangs again, and then bursts more updates. The time between bursts is upwards of five to ten minutes without any periods of continuous streaming. Any idea what might be causing this behavior? I'm not seeing any exceptions in the logs and the browser and zuul proxy appear to keep the connection open but the data is not flowing in real time. 

I'm using version 1.5.3 and the spring.boot.admin.turbine.location property set to a URL with basic auth embedded. Enabling and disabling security on the  turbine.stream server endpoint has no effect. Also, I'm not seeing any exceptions in the logs which might indicate a problem. 

I appear to have everything configured correctly and have used the debugger to ensure that that is the case. Hence why I'm raising the issue here instead of StackOverflow. 

Any help greatly appreciated. 

Blessings,
Brian

**Comment by herder** [comment]
Might your issue be related to this? https://github.com/codecentric/spring-boot-admin/issues/351#issuecomment-273288074
The embedded Zuul has issues with the Turbine stream, but the fix above makes the view work.
