### ISSUE TITLE
Disable password requesting in jmx environment

### ISSUE THREAD

**Issue by letientai299** [codecentric/spring-boot-admin#564]
I'd like to have a methods to remotely trigger `/refresh/` or `/restart/` on configuration change on spring config server. JMX tab offer that feature. But it's also offer the ability to query for sensitive environment data, which is hid when using Environment tab. 

### JMX query
![image](https://user-images.githubusercontent.com/8386780/30983299-9d2e8e1a-a4bc-11e7-8cd5-5a2311ffe33f.png)

### Environment query

![image](https://user-images.githubusercontent.com/8386780/30983446-12355e82-a4bd-11e7-8709-20f5ca0a30cb.png)

How could we to avoid this problem?

**Comment by joshiste** [comment]
This is not a SBA issue. The password is published by the underlying /jolokia endpoint.
IIRC jolokia itself has some configuration options to restrict the access.
