### ISSUE TITLE
ClassNotFoundException with Dalston.SR2

### ISSUE THREAD

**Issue by Pytry** [codecentric/spring-boot-admin#565]
This bug is similar to the classnotfound error with TraceProxyRequestHelper: https://stackoverflow.com/questions/39268604/could-not-start-springboot-admin-java-lang-noclassdeffounderror-org-springfram/46496944#46496944 

When using "org.springframework.cloud:spring-cloud-dependencies:Dalston.SR2" and version "1.5.4" of the admin server I was getting a ClassNotFoundException for "org.springframework.cloud.netflix.zuul.ZuulServerAutoConfiguration". I confirmed this behavior on maven 3.3.9 and 3.5.0, but not with gradle. 

Updating to the "Dalston.SR3" solves the problem.

I guess this is more of a "heads up" than a bug, since I already found a fix.

**Comment by joshiste** [comment]
SBA 1.5.4 is built against Dalston.SR3 ...
