### ISSUE TITLE
unable to connect to services via consul discovery while using TLS.

### ISSUE THREAD

**Issue by hamsaparam** [codecentric/spring-boot-admin#567]
Services are registered with consul and are enabled on https. Spring admin server discovers the services via consul. But it tries to perform the health check only via http .

**Comment by joshiste** [comment]
This is no SBA issue. You need to configure your discovery clients to register with the `https` scheme:

```
spring.cloud.consul.discovery.scheme=https
```

**Comment by hamsaparam** [comment]
Even after I configure discovery client (which is consul) to register with https scheme , spring admin server tries to do the health at http end point only by default, and gives Resource Access Exception

**Comment by hamsaparam** [comment]
opening a new issue for the same.
