### ISSUE TITLE
When using spring-boot-admin to monitor services on eureka, when the services on eureka are too many (for example, more than 50 on eureka) spring-boot-admin is slow or spring-boot-admin does not start Up, resulting in the spring-boot-admin application can not access

### ISSUE THREAD

**Issue by zhangjianbinJAVA** [codecentric/spring-boot-admin#568]
When using spring-boot-admin to monitor services on eureka, when the services on eureka are too many (for example, more than 50 on eureka), the boot process of spring-boot-admin is very slow, and sometimes there will be suspended animation Spring-boot-admin start process is very slow, there is no corresponding solution, I will not be able to visit the spring-boot-admin can not visit, Use <admin.version> 1.4.5 </admin.version>

**Comment by joshiste** [comment]
Please update to 1.5.x. With #349 there has been a improvement reducing the requests made by the UI, which should improve performance.
