### ISSUE TITLE
server-ui detail page some modules' ui disappear

### ISSUE THREAD

**Issue by 995270418L** [codecentric/spring-boot-admin#569]
Anyone can help me ? In the server-ui detail page, It contains 5 module (Application, Health, Memory, JVM, Garbage Collection). The Application and Health modules appear normal. others not. And I look through the 'row json' uri. it can response some json format data. and the client's /metrics endpoints request normal.

**Comment by joshiste** [comment]
The ui does some HEAD requests to figure out which endpoints are available and activates those. It appears that older Spring Boot 1.3.x applications are not responding correctly to those requests.

**Comment by joshiste** [comment]
I guess it's the same as in https://github.com/codecentric/spring-boot-admin/issues/527
