### ISSUE TITLE
Flyway Not Visible For Multiple Beans

### ISSUE THREAD

**Issue by mohita123** [codecentric/spring-boot-admin#575]
I have n number of beans which create n number of schemas in database.
I configured it with spring admin and all works fine except on UI only migrations for the last bean created is seen.
I am clueless what to do!!
Please Help!!

**Comment by joshiste** [comment]
did you check what the /flyway endpoint of your application gives you?

**Comment by mohita123** [comment]
```
@Configuration
public class DefaultDatasourceConfig {

    @Primary
    @Bean(name = "common")
    @ConfigurationProperties(prefix = "common.datasource")
    public DataSource getCommonDataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean(name = "xyz")
    @ConfigurationProperties(prefix = "public.datasource")
    public DataSource getxyzDataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean(name = "abc")
    @ConfigurationProperties(prefix = "adani.datasource")
    public DataSource getABCDataSource() {
        return DataSourceBuilder.create().build();
    }

}
```
I have this configuration 
In /flyway endpoint I see just for abc thing

**Comment by joshiste** [comment]
So when the endpoint just gives you a single datasource SBA can’t show you all....

**Comment by mohita123** [comment]
Yes it gives single datasource SBA.
Is there a way to view all?

**Comment by joshiste** [comment]
afaik there was an issue for that in boot 1.5.x
