### ISSUE TITLE
Application fails to launch running in non web environment.

### ISSUE THREAD

**Issue by shashidarp** [codecentric/spring-boot-admin#578]
When spring boot application is launched as a non web environment, it fails to launch with below error.

**************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method applicationFactory in de.codecentric.boot.admin.client.config.SpringBootAdminClientAutoConfiguration required a bean of type 'org.springframework.boot.autoconfigure.web.ServerProperties' that could not be found.
	- Bean method 'serverProperties' in 'ManagementServerPropertiesAutoConfiguration' not loaded because @ConditionalOnWebApplication (required) not a web application
	- Bean method 'serverProperties' not loaded because @ConditionalOnWebApplication (required) not a web application

Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.boot.autoconfigure.web.ServerProperties' in your configuration.

**Comment by joshiste** [comment]
Why you would even include the starter in non-web-applications???

**Comment by shashidarp** [comment]
@joshiste during our CICD process, we have a phase where we run the app as a non web app on a random port. This is causing failure due to above exception.

**Comment by joshiste** [comment]
>as non web app on a random port

isn't that contradictionary?

Ok. Got you point. As a workaround you can disable the client using a property.

**Comment by shashidarp** [comment]
Yes. Did the same as a work around. Felt it was a hack and thought it’s better to add to library.
