### ISSUE TITLE
Does Spring boot Admin Register Applications running over https?? , I tried it but it goes offline any help on this , or sample projects would be helpful??

### ISSUE THREAD

**Issue by Nivedan3112** [codecentric/spring-boot-admin#580]
![issue](https://user-images.githubusercontent.com/30735786/32476044-9efc3728-c33a-11e7-8a43-083aa9540e8b.PNG)

**Comment by Nivedan3112** [comment]
the above is a client application running on https , i do not have an sba in client side as i am using discovery using eureka, any help on this??

**Comment by joshiste** [comment]
Did you check the SBA servers log for exceptions? Offline means that no connection could be established... I guess you haven’t a valid certificate path. Next time please use StackOverflow for questions.

**Comment by Nivedan3112** [comment]
Hmm , i do have valid certificates , this is what i did , i have a sprint-boot-admin server running over https succesfully , now i have a spring client which is also running over https(Note both do not have discovery client yet). I would need some steps or any sample project to guide me through .

Step 1: I need a Spring boot admin to be able to register any applications running over https?
Step 2: If there is any way it is possible using eureka or Consul discovery clients , would be helpful.

Thanks Pls let me know if any

**Comment by joshiste** [comment]
Yes SBA is capable of handling https. Please refer to the corresponding manuals for eureka / consul on setting up https. The SBA client uses https if you configure via the spring boot options...
