### ISSUE TITLE
The thread dump should include the information whether a thread is a daemon thread or not

### ISSUE THREAD

**Issue by mrumpf** [codecentric/spring-boot-admin#581]
In the thread dump view the information is important whether a thread is a daemon or a non daemon thread.

For example: 

Non Daemon thread
````
"ActiveMQ Session: ID:d027paal-28160-1510134975512-1:1:2" #63 prio=7 os_prio=0 tid=0x00007fa6602af000 nid=0x6919 in Object.wait() [0x00007fa730179000]
````

Daemon thread
````
"ActiveMQ Session: ID:d027paal-28160-1510134975512-1:1:2" #63 daemon prio=7 os_prio=0 tid=0x00007fa6602af000 nid=0x6919 in Object.wait() [0x00007fa730179000]
````

When there are daemon threads the VM sometimes does not stop. In ActiveMQ clients you need to set daemon=true as part of the connection string to make the VM terminate correctly.

**Comment by joshiste** [comment]
As the `DumpEndpoint` (`ThreadDumpEndpoint` in boot 2.0) just spills out the `java.lang.management.ThreadInfo´ which doesn't contain any information about daemon/non-deamon we can't provide such info in the ui.
