### ISSUE TITLE
Spring boot Admin Fails to register application on client??

### ISSUE THREAD

**Issue by Nivedan3112** [codecentric/spring-boot-admin#582]
Hello , i have a spring boot adming running on https , i also have a spring boot normal client on https , on the logs i see it fails to register.Here i am not using any discovery client.

Secondly , if i make spring boot admin as http and any client on https , the SBA ui shows Offline , i really am looking for any help that i could get .

**Comment by joshiste** [comment]
Did you check the SBA server logs for exceptions?

**Comment by Nivedan3112** [comment]
Ok here is the thing , i tried generating a normal cert using keytool and putting it in admin server , so admin server runs on https,

I have the same in client , but the client runs separately but fails to register , i first though it was the self signed certificate issue, as the client was failing to register , but i am not too sure it works that way.


I am going to try now with discovery client (Eureka), having eureka and admin on server side , and a client and will let you know , any links related to https would be helpful
