### ISSUE TITLE
Add swagger ui module

### ISSUE THREAD

**Issue by ctoestreich** [codecentric/spring-boot-admin#584]
I spent a bunch of time adding this UI module https://github.com/Orange-OpenSource/angular-swagger-ui

I ran into a few issues namingly this one was the biggest in their package.json.

```
 "engines": {
        "node": ">=6 <7"
    },
```

I was looking for another option in angular to quickly add swagger ui, but this seemed like the only option.  I am open to alternatives or other ideas.

**Comment by joshiste** [comment]
hmm ... so how this relates to spring boot admin?

**Comment by slyoldfox** [comment]
@joshiste before I create an issue for my question, could I ask a question regarding "third party" modules (=user built modules).

We have some endpoints we would like to disclose in SBA. I've succesfully integrated SBA in our code platform, but I wonder if there is any way to easily add "our" SBA based angular modules into the UI.
I hacked my way around it by adding a "META-INF/spring-boot-admin-server-ui/applications-across" resource package and for sake of testing copied the webpacked version of applications-environment in it. I then proceeded to change the module name in module.js.
Everything seems to "work" (I realize I did some hacking there). But the main question is:

Is there any way that third party projects can add their own modules easily to SBA at this moment?
If yes please point me to the documentation or code-base.
If not, do you think I should create an issue so SBA can implement some extension points for this?

**Comment by slyoldfox** [comment]
To answer my own question, I stumbled upon

https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-server-ui-activiti/src/main/resources/META-INF/spring-boot-admin-server-ui/applications-activiti
which was eactly what I needed to include our own module in our code base.

Seems to work perfectly for showing additional items in SBA based on other endpoints.

**Comment by joshiste** [comment]
So can I close this issue?

**Comment by ctoestreich** [comment]
Up to you.  I was merely putting this here as a placeholder for a public and common record of request for feature.  I can create a new issue and submit code against it if I ever get the chance to add the swagger ui module.

**Comment by joshiste** [comment]
so @slyoldfox's comment didn't has something todo with your issue? So what's this issue is about? Adding a swagger ui for the sba server's endpoint?

**Comment by joshiste** [comment]
so @ctoestreich? did you read my last comment?

**Comment by archenroot** [comment]
@joshiste - I understand that this request was about adding swagger ui into spa. And I am also fun of it in general.

Maybe you can also shine light on my feature request related to swagger. I asked guys at Swagger already that the services I develop are purely event driven via message broker, very limited or none HTTP endpoints, I asked them if there is some kind of UI like manager as Swagger or if they implement this, but they see this as not right place as Swagger is bound to HTTP protocol. But in SPA there is Tracing capability which show you trace of HTTP calls, do you think if something like this can be supported for lets say **AMQP endpoints**? There is zipkin system which is able to trace this kind of async stuff, but question is if it would be something to integrate into spa admin or not. What do you think?

And sorry for mixing here now Swagger and async endpoints...

**Comment by ismarslomic** [comment]
I support this feature request. It would be lovely to be able to list all REST-apis that Spring Boot Application exposes. For instance by having one specific Swagger UI-tab. URL to the swagger.json file could be configured with specific property, and if it is not set, you dont show that tab.

**Comment by joshiste** [comment]
hmm is there a spring boot actuator endpoint for swagger? The url must live on the management port.

**Comment by ismarslomic** [comment]
No, not according to [Spring Boot Actuator Endpoint reference guide](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints). However, it is still possible to create custom on that is exposed on the management port.

Basically when requesting `/management/swagger` you will get JSON response with URL to the `swagger.json` file, which Spring Boot Admin application renders by embedding Swagger UI on some way. I have not thought much on the last part, but Swagger UI is HTML/CSS/JS (React).

**Comment by joshiste** [comment]
> However, it is still possible to create custom Actuator endpoint for Swagger, that is exposed on the management port.

Yeah but SBA shouldn't depend on everyone implementing it the same way...
And currently providing extra actuator endpoints is out of scope for SBA

**Comment by ismarslomic** [comment]
Yes, I see your point. What would be nice is an easy way to extend the core of SBA, such as new tab with custom content, but still be able to upgrade to latest version of SBA. The case is that SBA covers already many of the monitoring scenarios and it is nice way of getting the big picture into one place. So that is the reason why it would be nice to include swagger into the same portal.

Another input on the API-visibility would be to have an tab for Actuator endpoint `mappings`: Displays a collated list of all @RequestMapping paths. This endpoint is at least built in

**Comment by molexx** [comment]
AFAIK no, actuator's list of endpoints isn't enough to build a compete swagger spec. We include springfox in our app which generates internally and makes the json and a copy of swagger-ui available as a separate endpoint not a part of actuator.

Maybe actuator should get a swagger module first, then it might make sense to embed a copy of swagger-ui in SBA.

**Comment by joshiste** [comment]
>  Maybe actuator should get a swagger module first, then it might make sense to embed a copy of swagger-ui in SBA.

I totally agree

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.
