### ISSUE TITLE
Spring boot admin failing to register https application??

### ISSUE THREAD

**Issue by Nivedan3112** [codecentric/spring-boot-admin#585]
Hello , i have an issue in registering https clients on spring boot admin.

I have 2 applications ?
1. Admin Server (Running on http)
2.Client (Running on https).

upon starting the application i see the logs as below

> 2017-11-13 10:22:27.030  WARN 14680 --- [gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application [name=admin-server-client, managementUrl=https://IBMT460PC0K53NA.caremarkrx.net:5508, healthUrl=https://IBMT460PC0K53NA.caremarkrx.net:5508/health, serviceUrl=https://IBMT460PC0K53NA.caremarkrx.net:5008] at spring-boot-admin ([http://ibmt460pc0k53na/:8008/api/applications]): I/O error on POST request for "http://ibmt460pc0k53na/:8008/api/applications": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect<.

**Comment by Nivedan3112** [comment]
Tried adding this on client side properties but still it doesnt work

spring.boot.admin.client.managementUrl = https://IBMT460PC0K53NA.caremarkrx.net:5508
spring.boot.admin.client.healthUrl = https://IBMT460PC0K53NA.caremarkrx.net:5508/health
management.security.enabled=false

Note: I do not use any discovery client here

**Comment by joshiste** [comment]
I guess you are using the wrong port if the connection is refused

**Comment by Nivedan3112** [comment]
2017-11-13 10:34:32.513  WARN 17652 --- [gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application [name=admin-server-client, managementUrl=https://localhost:5008, healthUrl=https://localhost:5008/health, serviceUrl=https://IBMT460PC0K53NA.caremarkrx.net:5008] at spring-boot-admin ([http://ibmt460pc0k53na/:8008/api/applications]): I/O error on POST request for "http://ibmt460pc0k53na/:8008/api/applications": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect.

Nope this is the error to be precise

**Comment by joshiste** [comment]
you have a mistake in the URL:

`http://ibmt460pc0k53na/:8008/api/applications`

should read as

`http://ibmt460pc0k53na:8008/api/applications`

note the superfluous `/` before the port 8008

**Comment by Nivedan3112** [comment]
hmm , that is on the server side , that is the admin server url , which by default comes in like that do i have any property that i can do like how you specified??

**Comment by Nivedan3112** [comment]
OK thanks , actually i could see https now thank you
