### ISSUE TITLE
Spring boot admin unable to detect https when using eureka??

### ISSUE THREAD

**Issue by Nivedan3112** [codecentric/spring-boot-admin#586]
Hello , i have a client application on https and eureka server as discovery client(On http). I also have a Spring boot admin which needs to detect the https client application. Normally https without eureka and sba client works.  But i am unable to register https using eureka , i would like to know the approach

Error in consul log:
```
[2m2017-11-13 17:28:00.939[0;39m [31mERROR[0;39m [35m12224[0;39m [2m---[0;39m [2m[freshExecutor-0][0;39m [36md.c.b.a.d.ApplicationDiscoveryListener  [0;39m [2m:[0;39m Couldn't register application for service org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient$EurekaServiceInstance@5fd6f469
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

java.lang.IllegalArgumentException: healthUrl must not be empty!.
```

**Comment by Nivedan3112** [comment]
This is how my property in admin and client looks like

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
      instance:
      leaseRenewalIntervalInSeconds: 10
      securePortEnabled: true
      nonSecurePortEnabled: false
      statusPageUrl: https://localhost:8082/info
      healthCheckUrl: https://localhost:8082/health
      homePageUrl: https://localhost:8082/
      #statusPageUrl: http://${eureka.hostname}:${server.port}/info
      #healthCheckUrl: http://${eureka.hostname}:${server.port}/health
      #homePageUrl: http://${eureka.hostname}:${server.port}/

**Comment by Nivedan3112** [comment]
any help on this????

**Comment by joshiste** [comment]
your yaml to configure the eureka client is imho wrong indented. Did you check the registration information which comes from the eureka server?

**Comment by joshiste** [comment]
closing due to missing feedback
