### ISSUE TITLE
When maximum memory size is unbounded we should not use chart bar

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#587]
Non-Heap Memory bar in SBA is always red in our case. Maximum Non-Heap is unbounded so JVM will reserve and extend memory using memory blocks. For example if it needs 60MB it will reserve 64MB. For 64 -> 70, 70 -> 75. This will always be presented on red because memory utilization is always ~90%.
 
When non-heap memory max size is not set SBA should not use chart bar.

**Comment by joshiste** [comment]
SBA use the `heap` value as max from the `MemoryUsage`-MBean's `getMax()` method.
The MemoryUsage Mbean doesn't tell if it is unbounded or not.

From the Java doc:
>max | represents the maximum amount of memory (in bytes) that can be used for memory management. Its value may be undefined. The maximum amount of memory may change over time if defined. The amount of used and committed memory will always be less than or equal to max if max is defined. A memory allocation may fail if it attempts to increase the used memory such that used > committed even if used <= max would still be true (for example, when the system is low on virtual memory).

Unfortunately there is no info available if the maximum is unbounded or not. So we cant decide on that.
