### ISSUE TITLE
Update to Spring Cloud Edgware.RELEASE?

### ISSUE THREAD

**Issue by sdhery** [codecentric/spring-boot-admin#597]

**Comment by altitdb** [comment]
I would like to know when the version 1.5.6 will be released? I'm waiting for this fix. Tks.

**Comment by matt-shaw** [comment]
So would I.

**Comment by damifan** [comment]
thank you

**Comment by sincang** [comment]
thank you. please keep us posted.

**Comment by joshiste** [comment]
The release containing this fix was published.
