### ISSUE TITLE
Application not registering when scheduled annotation is used

### ISSUE THREAD

**Issue by yarinzimmerman** [codecentric/spring-boot-admin#598]
Hi,

I'm using SBA for some time now and recently came across a strange issue.
I have a class with a method that is annotated with `scheduled annotation` with a fixed delay of 1 second.

If the application is not registered in SBA then the `scheduled annotation` will prevent it from registering. When i remove the annotation and restart the application it will successfully register itself in SBA.

On the other hand, if the application is already registered then it will communicate properly with SBA regardless of the presence of the `scheduled annotation`.

I'm SBA 1.5.4 and my applications are using spring-boot-starter-actuator and admin-starter-client 1.5.4

Can you please advise?

Thanks, Yarin.

**Comment by joshiste** [comment]
I guess you are facing the same issue as in https://github.com/codecentric/spring-boot-admin/issues/478#issuecomment-311749930
