### ISSUE TITLE
Spring +vert.x+ spring admin does not work

### ISSUE THREAD

**Issue by armdev** [codecentric/spring-boot-admin#599]
Hello all,
If you exclude spring-boot-starter-tomcat from dependencies, Spring admin does not understand spring boot/vert.x as web application. If you keep tomcat dependency and run vert.x in different port, spring admin get information only from spring boot default port.:(

Simple project location is https://github.com/armdev/reactive-web , spring admin understand only tomcat or undertow port . Actually when you run app. , it is run in two ports , one vert.x http server, second spring tomcat/undertow server. If you exclude tomcat/undertow, spring boot admin does not receive any information.
 Finally if you run integrated vertx application Spring boot admin does not receive any request.

Is any simple solution?:)

Many thanks

**Comment by joshiste** [comment]
Spring boot Admin 1.5.x is only able to run with servlet web applications. With 2.x there will be support for reactive web applications.

**Comment by armdev** [comment]
Hi, many thanks
