### ISSUE TITLE
Remove button when using Discovery

### ISSUE THREAD

**Issue by ronnberg** [codecentric/spring-boot-admin#600]
Remove button was removed in version 1.5 (issue #328 ). Why?

We have auto de-registration off because we want to monitor if any application was de-registered by mistake. In this way we can act on offline status by either removing (de-registration was not done by mistake) or restart application/find out why it went down.

Now we are stuck with a bunch of old instances that has been decommissioned and the only way to remove them is to restart SBA. Is there any way to make the remove button for discovery applications  configurable via properties instead? At least the button should be available when the application has status offline.

**Comment by joshiste** [comment]
1. You should be able to remove the instance by issueing a `DELETE /api/applications/{id}`
2. When you are using discovery the `ApplicationDiscoveryListener` should keep the registered instances in sync with your service registry. So if you remove the application in the service registry it should disappear in spring boot admin.
