### ISSUE TITLE
Old spring boot verison in spring-boot-admin-client

### ISSUE THREAD

**Issue by ExtremeYu** [codecentric/spring-boot-admin#601]
spring-boot-admin-client has a old version of spring boot so that make all project to a old spring boot version,how to solve it?

**Comment by joshiste** [comment]
If you are using the `spring-boot-starter-parent` as parent or import `spring-boot-dependencies` as bom - the spring boot admin client should not influence the chosen spring boot version.
There is a whole chapter for this in the spring boot reference guide: https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-build-systems.html
