### ISSUE TITLE
sample-eureka can't work

### ISSUE THREAD

**Issue by caoyongviper** [codecentric/spring-boot-admin#602]
I run sample-eureka project. It seems that backend is ok,but ui can't display. 
Then I change version of spring-boot-admin-server and spring-boot-admin-server-ui from 1.5.6 to 1.5.5，every thing is ok.

**Comment by joshiste** [comment]
Did your sba successfully register with the eureka server? are there any errors in the logs?

**Comment by joshiste** [comment]
closed due to missing feedback
