### ISSUE TITLE
DateTimeFormat issue in Audit

### ISSUE THREAD

**Issue by dimazig** [codecentric/spring-boot-admin#605]
Hi there there is an issue with DateTime parsing here 

```java
        @ActuatorGetMapping
	@ResponseBody
	public ResponseEntity<?> findByPrincipalAndAfterAndType(
			@RequestParam(required = false) String principal,
			@RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssZ") Date after,
			@RequestParam(required = false) String type) {
		if (!isEnabled()) {
			return DISABLED_RESPONSE;
		}
		Map<Object, Object> result = new LinkedHashMap<Object, Object>();
		result.put("events", this.auditEventRepository.find(principal, after, type));
		return ResponseEntity.ok(result);
	}
```

Maybe it can be simplified somehow?

![image](https://user-images.githubusercontent.com/22467806/33537791-9fc8dee4-d911-11e7-8090-32d41bf896a5.png)

**Comment by joshiste** [comment]
Hmm looks like your browser serializes the date to `2017-12-13T14:01:00 0000` which should have been `2017-12-13T14:01:00+0000` (note the `+`).
For me this works on my machine. What browser are you using and what is your timezone?
Can you tell me what `new Date().toISOString()` evaluates to (in your browser's console?)

**Comment by dimazig** [comment]
My browser is Chrome 62 and new Date().toISOString() returns something like "2017-12-11T00:56:20.106Z"
My timezone is AEDT which is Sydney, Australia
new Date() produces something like "Mon Dec 11 2017 12:00:01 GMT+1100 (AUS Eastern Daylight Time)"

**Comment by joshiste** [comment]
Hmm I can't see why it shouldn't work - and it works on my machine. Do you have any custom settings in the admin regarding jackson's time deserialization? Could you provide a project to reproduce the issue`

**Comment by dimazig** [comment]
I debugged and found the problem. + symbol replaced with a space by tomcat. Tomcat version is 8.5.23.
Class org.apache.tomcat.util.buf.UDecoder
Line: 107 

` if( buff[ j ] == '+' && query) {
                buff[idx]= (byte)' ' ;`

**Comment by dimazig** [comment]
That quite strange cause a browser requests http://localhost:8080/admin/api/applications/bef38cd6/auditevents?after=2017-12-13T02:13:00%2B0000
so + is encoded %2B but Tomcat tries to decode it twice. Trying to find where is the first trasnformation from %2B to +

**Comment by dimazig** [comment]
There is definitely some s..t happening in Tomcat. http://tomcat.10.x6.nabble.com/character-is-always-encoded-in-url-path-after-request-dispatch-since-59317-td5062787.html
I would change the format of DateTime to something more reliable than ISO

**Comment by dimazig** [comment]
https://developer.ibm.com/answers/questions/249153/urls-with-or-2b-in-the-path-or-2b-in-the-query-are.html

**Comment by dimazig** [comment]
Or at least you could convert DateTime to UTCin JavaScript before sending so it would end up with Z rather than +<offset>

**Comment by joshiste** [comment]
The date conversion doesn't accept a `Z` for timezone only a `+0000`. And this is just what the current ui implementation uses. 
Additional to that for me it works using an embedded tomcat `8.5.23`. So maybe you've misconfigured some filters that the url is decoded twice. 
I currently don't consider this as a bug of spring boot admin.

**Comment by dimazig** [comment]
I've found what's causing an issue. This issues caused by ZuulFilter
I need to add zuul.forceOriginalQueryStringEncoding=true to fix it and disable double encoding.
