### ISSUE TITLE
Feature Request: Oauth2 Authentication With Actuator Endpoints

### ISSUE THREAD

**Issue by jmardis10** [codecentric/spring-boot-admin#607]
Would it be possible to add the ability to communicate with an applicaiton's health endpoints via Oauth2. Similarly to the way basic authentication was added. Spring Cloud handles this by allowing you to inject you're own Rest Template, maybe something similar can be done.

**Comment by viruscamp** [comment]
```java
public class OAuth2AuthorizationHttpHeadersProvider implements HttpHeadersProvider {

    public OAuth2AuthorizationHttpHeadersProvider(OAuth2RestOperations oAuth2RestOperations) {
        this.oAuth2RestOperations = oAuth2RestOperations;
    }

    private OAuth2RestOperations oAuth2RestOperations;

    @Override
    public HttpHeaders getHeaders(Application application) {
        HttpHeaders headers = new HttpHeaders();
        OAuth2AccessToken accessToken = oAuth2RestOperations.getAccessToken();
        if (accessToken != null) {
            String tokenType = accessToken.getTokenType();
            if (!StringUtils.hasText(tokenType)) {
                tokenType = OAuth2AccessToken.BEARER_TYPE; // we'll assume basic bearer token type if none is specified.
            }
            headers.set(HttpHeaders.AUTHORIZATION, String.format("%s %s", tokenType, accessToken.getValue()));
        }
        return headers;
    }
}
```

**Comment by joshiste** [comment]
@jmardis10 as @viruscamp has shown it's possible to inject your own headers into the requests made to the clients.
If it's about user authentication the `Authorization`-Header from the browser can be passed along to the clients, if you configure zuul to do so by `zuul.sensitiveHeaders=`. But keep in mind that the server itself is doing requests to `/health` and `/info` and needs also to authenticate somehow.
