### ISSUE TITLE
Problem with micro-services with custom oauth2

### ISSUE THREAD

**Issue by masoudsoha** [codecentric/spring-boot-admin#611]
hi.
I have several micro-services and a customized OAuth server that handle the security of services.
when I'm using spring-boot-admin, I can get resource server authorization from OAuth-server but I don't know how to add this to spring-boot-admin requests.

**Comment by joshiste** [comment]
For adding custom HTTP-Headers you just need to provide an implementation of the `HttpHeaderProvider` interface.

**Comment by masoudsoha** [comment]
thanks, I already did and works fine
