### ISSUE TITLE
problem with admin-server where about zuul

### ISSUE THREAD

**Issue by wangyuehaha** [codecentric/spring-boot-admin#612]
there is the case :
     java.lang.NoClassDefFoundError: com/netflix/servo/monitor/DynamicCounter

**Comment by joshiste** [comment]
The information you provided is not endough to reproduce the issue. At best you provide a sample project to reproduce the error, at least tell me which version of spring boot admin, spring boot and spring cloud you are using.

**Comment by joshiste** [comment]
closed due to missing feedback

**Comment by Dellaire** [comment]
I had this issue too, in my case, my server had the following dependencies:
```
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-server</artifactId>
	<version>1.5.7</version>
</dependency>
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-server-ui</artifactId>
	<version>1.5.7</version>
</dependency>
```
The problematic class resides within `servo-core-0.7.2.jar`. I fixed this by manually increasing the version of the related dependency within my server:
```
<dependency>
	<groupId>com.netflix.servo</groupId>
	<artifactId>servo-core</artifactId>
	<version>0.12.20</version>
</dependency>
```
