### ISSUE TITLE
AppliationFactory only mentioned in documentation?

### ISSUE THREAD

**Issue by yuniorb** [codecentric/spring-boot-admin#619]
In the documentation for 1.5.6 ([section 3.4](http://codecentric.github.io/spring-boot-admin/1.5.6/#spring-boot-admin-client)) the following paragraph describes an interface that can be implemented to customize application registration:

> There are plenty of properties to influence the way how the SBA Client registers your application. In case that doesn’t fit your needs, you can provide your own `AppliationFactory` implementation.

I can't seem to find this anywhere in this repo, the closest thing I saw to it was  the `ApplicationRegistry` class. Has this factory been renamed, moved, implemented? I would really appreciate some direction on this. Thanks!

**Comment by joshiste** [comment]
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-starter-client/src/main/java/de/codecentric/boot/admin/client/registration/ApplicationFactory.java
