### ISSUE TITLE
Listen for HTTPS services

### ISSUE THREAD

**Issue by waterlufei** [codecentric/spring-boot-admin#620]
I have a service that is HTTPS, and I have configured the domain name, I am a set of spring cloud project, and then I find that spring boot admin can't monitor the information of the HTTPS service. Is there any good way to do it?

**Comment by joshiste** [comment]
SBA is capable of monitoring via https. The urls wich are used to registrer at the sba server have to be set accordingly and the certificate must be valid. 
In case you are using SBA client, you can use `spring.boot.admin.client.*` properties to influence the url computation
