### ISSUE TITLE
Add a customizable warning page for new users

### ISSUE THREAD

**Issue by mrumpf** [codecentric/spring-boot-admin#621]
The SBA can cause serious harm to a production system. In a high traffic environment it is very easy to nuke a microservice by simply increasing the log level of the ROOT logger to DEBUG or TRACE. Or to override some config parameters which render the microservice unusable.
An idea would be to optionally show a warning page, before loading the SBA user interface, with a general explanation that a developer should be careful when using the tool and that all modifications are loggied in an audit log file (see #566 )

**Comment by joshiste** [comment]
With great power comes great responsibility....

You already could use a custom login page showing this warning...

**Comment by mrumpf** [comment]
Thanks for the hint. We will give that a try.

**Comment by tjuchniewicz** [comment]
This may be also fixed by https://github.com/codecentric/spring-boot-admin/issues/212 after we can customize navbar text.
