### ISSUE TITLE
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat

### ISSUE THREAD

**Issue by wangjia2016** [codecentric/spring-boot-admin#622]
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>1.2.7.RELEASE</version>
        </dependency>
<dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>1.2.4</version>
        </dependency>

SpringBoot version：1.2.7.RELEASE

Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat

Caused by: java.lang.NullPointerException

ServletContextInitializer
        characterFilter.setInitParameter("encoding", "UTF-8"); //this line cause null point

how to solve this problem?

ps:my project use shiro instead of spring security.

**Comment by joshiste** [comment]
doesn't look like an SBA bug to me, as the SBA doesn't contain a `ServletContextInitializer`.

Anyway I won't do fixes for a 1.2.x
