### ISSUE TITLE
springbootadmin application gets registered itself on common IP 169.254.0.2 with Eureka

### ISSUE THREAD

**Issue by kumarganesh2814** [codecentric/spring-boot-admin#626]
Hi Team,

We are trying to deploy springbootadmin on kubernetes 

Once Pod/container comes up application run fine and accessinble thorugh VM IP but when its registering itself on Eureka its showung up as -->169.254.0.2:springbootadmin:9300 

However my VM IP is diffrent and I have made hostentry too in /etc/hosts file 

Can you please help me how on kubernetes I can register springbootadmin with correct host IP.

``` 
worker/2689813a-bf7e-49e1-b2c5-6cb4662e949a:~$ cat /etc/hosts
127.0.0.1 localhost e2d994e1-2862-4e21-8fcb-5892f025975f

The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback e2d994e1-2862-4e21-8fcb-5892f025975f
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.180.xxx.xx e2d994e1-2862-4e21-8fcb-5892f025975f.myhost.com e2d994e1-2862-4e21-8fcb-5892f025975f
10.180.xxx.xx 772aee3f-c542-4c12-88ea-9a05404ad66a.myhost.com 772aee3f-c542-4c12-88ea-9a05404ad66a
10.180.xxx.xx b49f7988-9cd6-4745-ba9b-7dc5108b2247.myhost.com b49f7988-9cd6-4745-ba9b-7dc5108b2247
```

Please let us know if we need to change anything here on OS level or Yaml for deployment

Best Regards
Ganesh

**Comment by joshiste** [comment]
if you are using eureka you need to fix your eureka config... can't help you with that

**Comment by kumarganesh2814** [comment]
@joshiste Can you please suggest some contect for Eureka Issue
