### ISSUE TITLE
Spring Boot Admin does not show any tab other than 'Details' and 'Trace'

### ISSUE THREAD

**Issue by wavicle** [codecentric/spring-boot-admin#629]
I am able to run HEAD on all endpoints (such as JMX), and still the tabs don't show up after a certain application has been registered. The Spring Boot Application logs do not show any errors. In fact, even the 'Details' and 'Trace' tabs miss most information and appear incomplete. Other applications work well with the same SBA instance, so this is NOT a browser issue.

When the application registers, it does not show any version information, and almost all tabs are hidden.

Is there a troubleshooting guide that one can follow, when one cannot see tabs and other information?

I referred to issue #527 - it asks me to check for HEAD response and they all say 200 OK. I did not find any further 'how to' documentation.

**Comment by joshiste** [comment]
did you have a look into your browser's console? Have an eye on XHR errors

**Comment by joshiste** [comment]
closed du to missing feedback

**Comment by mayureshharsha** [comment]
I am also facing similar issue. Only details and trace tab visible when deployed on cloud foundry. and other endpoints return a 404 for HEAD request . I have exposed the management endpoints but to no avail .
