### ISSUE TITLE
how to successfully do POST Request to SpringbootAdmin register API?

### ISSUE THREAD

**Issue by tetsushiawano** [codecentric/spring-boot-admin#632]
I am facing an issue. I am trying to make a HTTP Post request to register API but I am failing.
Do you know what I am doing wrongly?

![screen shot 2018-01-29 at 6 33 01 pm](https://user-images.githubusercontent.com/24989207/35503248-ea22dc64-0522-11e8-85cd-2a1d6a4781d4.png)
![screen shot 2018-01-29 at 6 33 14 pm](https://user-images.githubusercontent.com/24989207/35503252-ed579cf8-0522-11e8-9493-025102f4ec01.png)

**Comment by joshiste** [comment]
how does your request look like?

**Comment by joshiste** [comment]
Try submitting `application/json` and not formdata

**Comment by tetsushiawano** [comment]
thanks! it worked.
![screen shot 2018-01-29 at 7 05 23 pm](https://user-images.githubusercontent.com/24989207/35504840-7da5a8b4-0527-11e8-98b0-9ded09819245.png)
