### ISSUE TITLE
Failed to register application as Application -registeredId is null

### ISSUE THREAD

**Issue by salomon1184** [codecentric/spring-boot-admin#634]
when using spring-boot-admin 1.5.0, an error occur, error message:
Failed to register application as Application [name=amap-tesla-admin, managementUrl=http://30.28.161.10:8888, healthUrl=http://30.28.161.10:8888/health, serviceUrl=http://30.28.161.10:8888] at spring-boot-admin ([http://xxx.xxx.xxx.net/api/applications]): null

debug mode to trace this error, found that response.getBody().get("id") is null
it confuse me, the server response is
```
{
	"data": {
		"id": "4b27083b",
		"name": "amap-tesla-admin",
		"managementUrl": "http://30.28.161.10:8888/",
		"healthUrl": "http://30.28.161.10:8888/health/",
		"serviceUrl": "http://30.28.161.10:8888/",
		"statusInfo": {
			"status": "OFFLINE",
			"timestamp": 1517312206383,
			"details": {
				"exception": "org.springframework.web.client.ResourceAccessException",
				"message": "I/O error on GET request for \"http://30.28.161.10:8888/health/\": Connect to 30.28.161.10:8888 [/30.28.161.10] failed: Connection refused; nested exception is org.apache.http.conn.HttpHostConnectException: Connect to 30.28.161.10:8888 [/30.28.161.10] failed: Connection refused"
			}
		},
		"source": "http-api",
		"metadata": {},
		"info": {
			"data": {},
			"errCode": 0,
			"errMsg": "success"
		}
	},
	"errCode": 0,
	"errMsg": "success"
}
```

**Comment by joshiste** [comment]
the `data` element is superfluous in the response. Do you have any ControllerAdvice or ServletFilter active, that is adding this element?

**Comment by joshiste** [comment]
closed due to missing feedback
