### ISSUE TITLE
Spring boot admin uses localhost ip address

### ISSUE THREAD

**Issue by martinblaustein** [codecentric/spring-boot-admin#637]
Hi,

We are running our spring boot admin server in one machine and our clients in different machines connected by vpn.
When using  `spring.boot.admin.client.prefer-ip=true` instead of sending the Ip address of the machine, the spring boot client send the localhost ip.

Shouldn't it send directly the ip from the machine?

**Comment by joshiste** [comment]
it uses the adress the hostname resolves to (`InetAddress.getLocalHost()`) if you want to use some other address you can set the `server.adress`property.
