### ISSUE TITLE
@EnableZuulProxy + @EnableAdminServer

### ISSUE THREAD

**Issue by anxpp** [codecentric/spring-boot-admin#640]
Parameter 1 of method routesMvcEndpoint in org.springframework.cloud.netflix.zuul.ZuulProxyAutoConfiguration$EndpointConfiguration required a single bean, but 2 were found:
	- routesEndpoint: defined by method 'routesEndpoint' in class path resource [org/springframework/cloud/netflix/zuul/ZuulProxyAutoConfiguration$EndpointConfiguration.class]
	- zuulEndpoint: defined by method 'zuulEndpoint' in class path resource [de/codecentric/boot/admin/config/RevereseZuulProxyConfiguration$RoutesEndpointConfiguration.class]

**Comment by joshiste** [comment]
Why you want to do that? If the zuul is viable for your system. Please run it seperate.

**Comment by chenkline** [comment]
same trouble
