### ISSUE TITLE
SBA to support Application which is not Springboot.

### ISSUE THREAD

**Issue by tetsushiawano** [codecentric/spring-boot-admin#641]
Hello. I want to introduce SpringbootAdmin to manage the application list in the company. And I come across the issue of SpringbootAdmin to not support application which does not use the Springboot framework.

Does anyone here tried to add other framework application such as Rails(Ruby) or FrontEnd(Nodejs)? 

Personally, When considering to support FrontEnd(Nodejs), I realised that FrontEnd(Nodejs) application would not have a /health actuator endpoint by default. In such a case, I think it will be a good feature to only check the status code whether the application is UP or DOWN.

I would like anyones opinions or experiences or anything. Thanks!

**Comment by joshiste** [comment]
You can register a non-Boot application with a POST to `/api/applications` and only providing a name and healthUrl and SBA will monitor ist.
example request:
```json
{ "name" : "my-node", "healthUrl":"http://mynodehost/health"}
```
The monitored applications need to respond with a 200 when everything is ok and a 5xx if otherwise.

**Comment by tetsushiawano** [comment]
Good to know that it was already supported. And i checked that it works.
<img width="967" alt="screen shot 2018-02-06 at 3 42 56 pm" src="https://user-images.githubusercontent.com/24989207/35845192-986f3cd6-0b54-11e8-9193-50b1dd6900ff.png">
<img width="1229" alt="screen shot 2018-02-06 at 3 42 43 pm" src="https://user-images.githubusercontent.com/24989207/35845195-9db47ab2-0b54-11e8-9d0d-99105f9ffe77.png">
