### ISSUE TITLE
Display application metadata

### ISSUE THREAD

**Issue by tetsushiawano** [codecentric/spring-boot-admin#642]
Hello. Related to #641 .

We want to manage application of various framework in SBA.
And for non Springboot application, it does not have a /info actuator endpoint by default so it can not display information in the top page (page with the list of applications).  

Is there any method to display the data passed with the POST /api/applications endpoint. One idea I can think of is passing the data in metadata. And as for SBA, it will additionally display the data in the additionally created metadata column.

If metadata is used for different purpose and can not be displayed, another idea is to create a new POST object attribute which will  always display in SBA.

Sorry for bad english, but I hope you can catch my situation. 
Thank you in advance.

**Comment by tetsushiawano** [comment]
We need this feature so we can help.
@joshiste do you have any opinion whether its ok to add new column called metadata or another solution? We want to continue to use the latest version of SBA so if possible we want to fix with the ideal solution.

**Comment by joshiste** [comment]
What type of metadata you want to display? Can you give me some example?

Imho we should not add a additional column to the application list. Would it be enough to display it in the details view?

**Comment by tetsushiawano** [comment]
Below is example information we want to display somewhere in SBA. 

- contact information 
the person to contact to when the application is in trouble.
e.g hello.world(at)gmail.com
- application version
the version of the running application. 
e.g 1.0.0 

It does not have to be in application list. 
It would meet our requirement to display in details view or anywhere else.

Thanks for your help.

**Comment by joshiste** [comment]
if you want to see this happen soon please submit a PR.

**Comment by tetsushiawano** [comment]
I will try to submit one by the end of the week! Thank you for your support.

**Comment by joshiste** [comment]
closed with #645

**Comment by joshiste** [comment]
with 19baa38e4c9e68b8e039f61a8e6c66903e24c478 the version is taken from the metadata as well.  Either the key `version` or `build.version` must be present in the metadata.
