### ISSUE TITLE
Client applications registers as Offline in Kubernetes

### ISSUE THREAD

**Issue by RawSanj** [codecentric/spring-boot-admin#644]
I deployed Spring Boot Admin app on Kubernetes and used SBT client on Spring Boot apps.
The applications gets registered but as Offline.

I then removed the SBT client and deployed Spring Eureka and updated SBT admin and other Spring boot apps for Eureka discovery.
But still the apps are getting registered as Offline in SBT admin.

All the apps, including SBT Admin is getting registered in Spring Eureka.

The interesting thing is that I can see the SBT Admin app getting registered in itself and I can check the Details, Metrics, Trace, etc. but if I increase the no. of instances of SBT Admin app, all the other instances are getting registered as Offline.

Has anyone able to deploy SBT Admin and register apps with more instances?

**Comment by joshiste** [comment]
Did you check the admins server's log? If an application is reported as offline the server can't reach the client and there should be an exception logged...

**Comment by RawSanj** [comment]
I didn't check the server logs, but here's what I observed -
The server tries to access http://pod-name:8080. In Kubernetes pods are accessed via Services and not directly.
I have LoadBalancer type Service for SBT Admin app, and I can able to curl http://sbt-admin-pod-name:8080 from inside k8s cluster.
When I increase the no. of SBT Admin instance, i.e. more pods of SBT Admin, then the other instances gets registered as offline.
And when I try to curl http://sbt-admin-pod-name-2:8080 then I'm not able to access it from inside the cluster. I'm only able to access the first instance.

How do make all instances accessible?

I'll check the exact logs and add more info, but seems like you are right, server is not able to access.
But I don't understand why!

**Comment by joshiste** [comment]
closed due to missing feedback
