### ISSUE TITLE
DefaultServiceInstanceConverter for Eureka

### ISSUE THREAD

**Issue by n0mer** [codecentric/spring-boot-admin#647]
hello, quick question:
i have bean `serviceInstanceConverter` in spring context (reported by spring-boot-actuator's `beans` endpont)

```json
serviceInstanceConverter: {
aliases: [ ],
scope: "singleton",
type: "de.codecentric.boot.admin.server.discovery.DefaultServiceInstanceConverter",
resource: "class path resource [de/codecentric/boot/admin/server/config/AdminServerDiscoveryAutoConfiguration.class]",
dependencies: [ ]
}
```

although in `de.codecentric.boot.admin.server.config.AdminServerDiscoveryAutoConfiguration.EurekaConverterConfiguration` there is instruction `@ConditionalOnBean(EurekaClient.class)` , and i have `EurekaClient` bean as well:

```json
eurekaClient: {
aliases: [ ],
scope: "singleton",
type: "com.sun.proxy.$Proxy117",
resource: "BeanDefinition defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.class]",
dependencies: [
"refreshScope"
]
}
```

So, my question is "how to force auto-configuration to instantiate `EurekaServiceInstanceConverter`" ?

**Comment by joshiste** [comment]
version?

**Comment by n0mer** [comment]
EurekaClient is present. 

```
        springbootVersion = '2.0.0.RC1'
        springCloudVersion = 'Finchley.M6'
        springCloudNetflixVersion = '2.0.0.M6'
        springbootAdminVersion = '2.0.0-SNAPSHOT'
        springIoPlatformVersion = 'Cairo-BUILD-SNAPSHOT'
```

**Comment by tetsushiawano** [comment]
Sorry if it'd not related but are you trying to override the default auto configuration? If so you need to have spring.factories file under resources/META-INF? I think it is required to force the customized auto configuration.

Also, you need to set the customized autoconfiguration inside like below. 

org.springframework.boot.autoconfigure.EnableAutoConfiguration={customized autoconfiguration}

**Comment by n0mer** [comment]
fixed, thanks!

```
serviceInstanceConverter: {
aliases: [ ],
scope: "singleton",
type: "de.codecentric.boot.admin.server.discovery.EurekaServiceInstanceConverter",
resource: "class path resource [de/codecentric/boot/admin/server/config/AdminServerDiscoveryAutoConfiguration$EurekaConverterConfiguration.class]",
dependencies: [ ]
}
```
