### ISSUE TITLE
Custom RestTemplate not being used

### ISSUE THREAD

**Issue by andyd2002** [codecentric/spring-boot-admin#648]
I've added my own ZuulFiter to add an authenticated cookie which i need when hitting the actuator endpoints, this all works fine when clicking into the application pages to view metrics, env, trace etc.
However when viewing the main dashboard showing the list of spring boot services my filter is never invoked, i see the list of services from eureka and details from the /health page but as my /info pages are protected i get no version numbers and an exception in the logs caused by the missing auth cookie.

Looking at StatusUpdater.queryInfo(StatusUpdater.java:85) I can see RestTemplate is being used for these calls, I tried defining by own @Bean RestTemplate with the added cookie header however this doesn't seem to be used.  Is there another way I can add my own auth cookie for use by the StatusUpdater?

Thanks

**Comment by joshiste** [comment]
For adding additional headers just implement a `HttpHeadersProvider`
