### ISSUE TITLE
Sample for Spring boot admin with jmx using jolokia

### ISSUE THREAD

**Issue by shshankar1** [codecentric/spring-boot-admin#651]
Can you please add a sample for spring boot admin with jmx using jolokia. Or if you help me with pointing out the mistake, I can fix and create a pull request to add the sample. I tried to create a sample project but admin UI doesn't show up any option for JMX beans. However I do see that jolokia endpoint is up and running:
--------------------------------
url:
http://localhost:9090/jolokia
response:
{"request":{"type":"version"},"value":{"agent":"1.3.7","protocol":"7.2","config":{"agentId":"10.97.55.207-10944-39e75e88-servlet","agentType":"servlet"},"info":{"product":"tomcat","vendor":"Apache","version":"8.5.27"}},"timestamp":1519192759,"status":200}
-----------------------------
![spring_boot_admin](https://user-images.githubusercontent.com/13238017/36465678-39981256-16fc-11e8-8e65-8143535f9f18.JPG)
----------------------------
build.gradle:

import net.researchgate.release.GitAdapter
import org.apache.tools.ant.filters.*

buildscript {
    project.ext {
        anzMarketsLocalUrl = "https://artifactory.service.anz/artifactory/markets-local"
    }

    repositories {
        maven {
            url anzMarketsLocalUrl
        }
        maven {
            url "https://artifactory.service.anz/artifactory/mavencentralrepo"
        }
    }

    dependencies {
        classpath "net.researchgate:gradle-release:${releasePluginVersion}"
        classpath "org.hibernate.build.gradle:gradle-maven-publish-auth:2.0.1"
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'maven'
apply plugin: 'maven-publish'
apply plugin: 'application'
apply plugin: 'org.springframework.boot'

repositories {
    mavenLocal()
    maven {
        url "https://artifactory.service.anz/artifactory/markets-local"
    }
}

compileJava {
    options.encoding = "UTF-8"
    options.compilerArgs << "--add-modules" << "java.xml.ws.annotation"
    options.compilerArgs << "--add-modules" << "java.xml.bind"
}
compileTestJava {
    options.encoding = "UTF-8"
    options.compilerArgs << "--add-modules" << "java.xml.ws.annotation"
    options.compilerArgs << "--add-modules" << "java.xml.bind"
}

jar {
    baseName = 'client-stp-grid-publisher'
    version = version
}

sourceCompatibility = 9
targetCompatibility = 9

/**
 * Please do not delete lines from 65-89
 * This is used to generate QueryDSL for persistence models.
 */
ext {
    generatedSourcesDir = file("${buildDir}/generated-sources")
}
sourceSets {
    main {
        java {
            srcDir "src/main/java"
            srcDir generatedSourcesDir
        }
    }
}

configurations {
    querydslapt
}

task generateQueryDSL(type: JavaCompile, group: 'build', description: 'Generates the QueryDSL query types') {
    source = sourceSets.main.java
    classpath = configurations.compile + configurations.querydslapt
    options.compilerArgs = [
            "-proc:only",
            "-processor", "com.querydsl.apt.jpa.JPAAnnotationProcessor"
    ]
    destinationDir = generatedSourcesDir
}

group = projectGroup
version = version

dependencies {
    compile files("${System.properties['java.home']}/../lib/tools.jar")

    compile group: 'net.openhft', name: 'chronicle-core', version: chronicleCoreVersion
    compile group: 'net.openhft', name: 'chronicle-queue', version: chronicleQueueVersion
    compile group: 'net.openhft', name: 'chronicle-threads', version: chronicleThreadsVersion
    compile group: 'net.openhft', name: 'chronicle-wire', version: chronicleWireVersion
    compile group: 'net.openhft', name: 'chronicle-bytes', version: chronicleBytesVersion
    compile group: 'org.springframework', name: 'spring-context', version: springVersion
    compile group: 'org.springframework', name: 'spring-orm', version: springVersion
    compile group: 'org.springframework', name: 'spring-tx', version: springVersion
    compile group: 'org.springframework', name: 'spring-expression', version: springVersion
    compile group: 'org.springframework', name: 'spring-beans', version: springVersion
    compile group: 'org.springframework', name: 'spring-core', version: springVersion
    compile group: 'org.springframework.integration', name: 'spring-integration-jmx', version: springVersion
    compile group: 'org.springframework.boot', name: 'spring-boot-dependencies', version: springBootVersion
    compile group: 'org.springframework.boot', name: 'spring-boot-autoconfigure', version: springBootVersion
    compile group: 'org.springframework.boot', name: 'spring-boot-starter', version: springBootVersion
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa', version: springBootVersion
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: springBootVersion
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version: springBootVersion
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: springBootVersion
    compile group: 'com.oracle', name: 'ojdbc14', version: ojdbc14Version
    compile group: 'com.anz.markets.efx.event', name: 'event-sourcing-chronicle', version: eventSourcingFrameworkVersion
    compile group: 'com.anz.markets.efx.event', name: 'event-sourcing-framework', version: eventSourcingFrameworkVersion
    compile group: 'com.anz.axle.spdee-direct', name: 'spdee-direct-persistence', version: spdeeDirectVersion
    compile group: 'com.google.guava', name: 'guava', version: googleGuavaVersion
    compile group: 'org.mockito', name: 'mockito-core', version: mockitoVersion
    compile group: 'javax.xml.bind', name: 'jaxb-api', version: jaxbVersion
    compile group: 'javax.annotation', name: 'javax.annotation-api', version: javaxAnnotationApiVersion
    compile group: 'com.querydsl', name: 'querydsl-apt', version: querydslVersion
    compile group: 'com.querydsl', name: 'querydsl-jpa', version: querydslVersion
    compile group: 'com.querydsl', name: 'querydsl-core', version: querydslVersion
    compile group: 'commons-io', name: 'commons-io', version: commonIoVersion
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: httpClient
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: jacksonVersion
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: jacksonVersion
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: jacksonVersion
    compile group: 'de.codecentric', name: 'spring-boot-admin-server', version: springBootAdminServerVersion
    compile group: 'de.codecentric', name: 'spring-boot-admin-starter-client', version: springBootAdminServerVersion
    compile group: 'de.codecentric', name: 'spring-boot-admin-server-ui', version: springBootAdminServerVersion
    compile group: 'de.codecentric', name: 'spring-boot-admin-server-ui-login', version: springBootAdminServerVersion
    testCompile group: 'org.mockito', name: 'mockito-core', version: mockitoVersion
    querydslapt "com.querydsl:querydsl-apt:4.1.0"
}

mainClassName = "com.anz.markets.efx.client.stp.ClientStpGridPublisherMain"
applicationDefaultJvmArgs = ["-Xmx512m"]
distZip.enabled = true
distTar.enabled = false
startScripts.enabled = false

jar {
    exclude("bin/**")
}

test {
    afterTest { desc, result ->
        logger.quiet "Executing test ${desc.name} [${desc.className}] with result: ${result.resultType}"
    }
}

// maven publishing
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
        installer(MavenPublication) {
            artifact fatJarZip {
                classifier "bin"
            }
        }
    }

    repositories {
        maven {
            url "https://artifactory.service.anz/artifactory/markets-internal"
            credentials {
                username mavenUser
                password mavenPassword
            }
        }
    }
}

processResources{
    filter(ReplaceTokens,tokens:['buildVersion':version])
}

def distributionsCopySpec = copySpec {
    into('') {
        from libsDir
        include '*.jar' //copy the fat jar created by bootRepackage
    }
    into('bin') {
        from "${buildDir}/resources/main/bin" //custom start script based on startScripts task output
    }

    into('config'){
        from "${buildDir}/resources/main/config" //copy config directory
    }
}

//This is to generate our binaries in the "ZIP" structure that we need.
task fatJarZip(type: Zip, dependsOn: 'bootRepackage') {
    with distributionsCopySpec
    archiveName "${projectName}-${version}.zip"
}

// release plugin
apply plugin: 'net.researchgate.release'
release {
    failOnUnversionedFiles = false
    scmAdapters = [
            GitAdapter
    ]
    git {
        // set requiredBranch to '' to test on non-master branch
        requireBranch = ''
        pushToRemote = 'origin'
        pushToBranchPrefix = ''
    }
}

publish.dependsOn fatJarZip
afterReleaseBuild.dependsOn publish
----------------------------------
----------------------------------

gradle.properties:
version=1.0.0
projectName=client-stp-grid-publisher
projectGroup=com.anz.markets.efx.client.stp
springBootVersion=1.5.10.RELEASE
springVersion=4.3.5.RELEASE
spdeeDirectVersion=4.1240
slf4jVersion=1.7.25
log4jVersion=2.8.1
chronicleBytesVersion=1.10.13
chronicleCoreVersion=1.10.1
chronicleQueueVersion=4.6.69
chronicleThreadsVersion=1.9.5
chronicleWireVersion=1.10.16
ojdbc14Version=10.2.0.5.0
eventSourcingFrameworkVersion=1.15
googleGuavaVersion=15.0
mockitoVersion=2.13.0
jaxbVersion=2.3.0
javaxAnnotationApiVersion=1.3.1
querydslVersion=4.1.0
jacksonVersion=2.8.9
commonIoVersion=2.4
httpClient=4.5.5
springBootAdminServerVersion=1.5.1
# artifactory
mavenUser=dummy
mavenPassword=dummy
localMavenRepo=c:/maven-repo
#release plugin
releasePluginVersion=2.6.0

**Comment by joshiste** [comment]
The Samples contain jolokia. I won't read the pasted code - it's too much to paste as plain text. Either provide a zip file or a git repository that contains the project so that I y execute it.

**Comment by joshiste** [comment]
Also your screen shot shows no registered application. you should fix that first.

**Comment by shshankar1** [comment]
@joshiste Can you please help in pointing to jolokia jmx sample?

**Comment by joshiste** [comment]
https://github.com/codecentric/spring-boot-admin/tree/1.5.x/spring-boot-admin-samples/spring-boot-admin-sample

**Comment by shshankar1** [comment]
@joshiste thanks I will give a try and in case of any issue I will share the git repo url to replicate the issue.

**Comment by shshankar1** [comment]
@joshiste finally I figured out the main cause. The application registry with SBA was not working in my case. Application main class implements CommandLineRunner (refer attached file) since application is supposed to work as command line process. If I remove "implements CommandLineRunner" then application registry with SBA works fine and I get required JMX endpoints.

So is there any way to have SBA along with spring boot CommandLineRunner?
[ClientStpGridPublisherMain.txt](https://github.com/codecentric/spring-boot-admin/files/1745102/ClientStpGridPublisherMain.txt)
