### ISSUE TITLE
Offline applications are never removed with custom ServiceInstanceConverter implementation

### ISSUE THREAD

**Issue by manojuk** [codecentric/spring-boot-admin#652]
We are using consul with SBA, and implemented a custom ServiceInstanceConverter where we change serviceId to user friendly name

public class ConsulServiceInstanceConverter extends DefaultServiceInstanceConverter {
.......
	@Override
	public Application convert(ServiceInstance instance) {
....
                final String appName = instance.getServiceId().replaceAll("XYZ", "App");

		return Application.create(appName).withHealthUrl(healthUrl)
				.withManagementUrl(managementUrl).withServiceUrl(serviceUrl)
				.build();
	}

Things work fine, but if the app is undeployed/shutdown, its shown as OFFLINE forever and never removed. If we dont do the serviceId conversion then it works fine.

**Comment by joshiste** [comment]
Which version of SBA you are referring to?

**Comment by joshiste** [comment]
For `1.x` the `ApplicationDiscoveryListener` relies on the service name to be equal the application name. 
So if you really wan't to alter the names you need to Replace the `ApplicationDiscoveryListener` with a custom one. For 1.x I'll do only critical fixes. I consider this at best a minor bug if not an enhancement.

With Spring Boot Admin 2.x this problem does not occur - therefore I'm closing this issue as won't fix.
