### ISSUE TITLE
spring boot admin logfile

### ISSUE THREAD

**Issue by GuoxinL** [codecentric/spring-boot-admin#653]
What should I do to add the log module to my spring-boot-admin?
I hope you can direct me, Thank you in advance.
![logfile](https://github.com/codecentric/spring-boot-admin/blob/master/images/screenshot-logfile.png?raw=true "logfile")

**Comment by tetsushiawano** [comment]
speaking of assumption, probably you need to enable logfile endpoint.
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html

I think by default, only a few endpoint is enabled.

**Comment by joshiste** [comment]
That's correct

**Comment by GuoxinL** [comment]
Thank you for your help.

**Comment by GuoxinL** [comment]
logging.file=/file/to/path/xxx.log

**Comment by SylvainAssemat** [comment]
Hello

I can't find the solution in my projet to display this LOG tab

`spring.application.name=@project.build.finalName@
info.version=@project.version@
info.build.artifact=@project.artifactId@
info.build.name=@project.name@
info.build.description=@project.description@
info.build.version=@project.version@

server.address=localhost
server.port=8080
server.contextPath=/@project.build.finalName@

management.context-path = /manage
management.security.enabled: false

#configs to connect to self register the admin server as a client
spring.boot.admin.url=http://${server.address}:${server.port}${server.contextPath}
spring.boot.admin.client.management-base-url=http://${server.address}:${server.port}${server.contextPath}
spring.boot.admin.service-base-url=http://${server.address}:${server.port}${server.contextPath}
spring.boot.admin.client.service-url=http://${server.address}:${server.port}${server.contextPath}
#spring.boot.admin.context-path=${server.contextPath}

spring.boot.admin.monitor.connect-timeout: 5000
spring.boot.admin.monitor.read-timeout: 30000

spring.boot.admin.routes.endpoints: logfile,loggers,info,trace,health,refresh,metrics,jolokia

logging.file=myapplication.log`

**Comment by joshiste** [comment]
looks good from my point of view. you should debug the `EndpointWebMvcManagementContextConfiguration` of spring boot if you're having problems. This is not a spring boot admin issue.
