### ISSUE TITLE
Question about Hystrix UI

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#657]
Anyone has successfully using Hystrix UI?

According to this comment https://github.com/Netflix/zuul/issues/376#issuecomment-347356803 Zull 1.x does not support SSE.

SBA uses Zuul 1.3. When I hit Hystrix endpoint over SBA: http://localhost:8080/spring-boot-admin/api/applications/7216745c/hystrix.stream it does not work as expected. Actually I get some data every few minutes!

**Comment by joshiste** [comment]
It worked for my demo project. Did you check that the underlying endpoint is not just spilling out data every few minutes?

**Comment by tjuchniewicz** [comment]
When go directly to my service e.g:  http://localhost:8181/management/hystrix.stream it works fine.

**Comment by tjuchniewicz** [comment]
We are also using Hystrix dashboard in standalone configuration (spring-cloud-netflix-hystrix-dashboard) and in this case it works fine but communication goes through [ProxyStreamServlet ](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-hystrix-dashboard/src/main/java/org/springframework/cloud/netflix/hystrix/dashboard/HystrixDashboardConfiguration.java#L110) e.g. http://localhost:8080/proxy.stream?origin=http://localhost:8080/turbine.stream.

Looks like spring-cloud-netflix-hystrix-dashboard provides workaround for SSE?

```java
/**
 * Proxy an EventStream request (data.stream via proxy.stream) since EventStream does
 * not yet support CORS (https://bugs.webkit.org/show_bug.cgi?id=61862) so that a UI
 * can request a stream from a different server.
 */
public static class ProxyStreamServlet extends HttpServlet {}
```

**Comment by joshiste** [comment]
Yeah I guess we have to avoid the zuul for hystrix somehow.
I'm not sure I'll fix this in 1.5.x as 2.x doesn't uses zuul anymore - but 2.x currently doesn't include hystrix (yet)

**Comment by joshiste** [comment]
Hmm the hystrix-dashboard has been moved to https://github.com/Netflix-Skunkworks/hystrix-dashboard and seems abandoned to me. I'm not keen on integrating this into 2.0.

**Comment by Anonymous-Coward** [comment]
Still, the hystrix metrics are useful. Showing just hystrix: up in spring boot admin doesn't really add value.

**Comment by joshiste** [comment]
Yeah it's possible to write a custom visualization for the `/actuator/hystrix.stream` data not relying on the hystrix dashboards. PRs are any time welcome.

**Comment by MartinDevillers** [comment]
I've published a plugin for Spring Boot Admin 2 that adds Hystrix Dashboard. To use it, simply drop the following Maven dependency in your Spring Boot Admin's `pom.xml`
```xml
<dependency>
    <groupId>nl.devillers</groupId>
    <artifactId>spring-boot-admin-hystrix-dashboard</artifactId>
    <version>1.0.1</version>
</dependency>
```
More info: https://github.com/MartinDevillers/spring-boot-admin-hystrix-dashboard

Hope it helps someone :-)
