### ISSUE TITLE
(Open Discussion) (SBA client) what should be the default value of spring.boot.admin.client.auto-deregistration?

### ISSUE THREAD

**Issue by tetsushiawano** [codecentric/spring-boot-admin#658]
There was a discussion about the what should be the default value of `spring.boot.admin.client.auto-deregistration`. By default, SBA client's `spring.boot.admin.client.auto-deregistration` is set as false so that it does not deregister the application when the Springboot application process is down. I agree this is the correct specification for application running on permanent environment such as IaaS and real servers. Because, When the process is down, the application would not deregister itself and can show that the application is down in SBA as the access to the health endpoint will fail.

On the other case, ephemeral environment such as PaaS environment does not have a permanent environment so it would be correct to set the `spring.boot.admin.client.auto-deregistration` as true. When a application process goes down, the same process can not startup in the future so it should deregister itself from the application catalogue in SBA.

I would like to hear anyones opinion whether `spring.boot.admin.client.auto-deregistration` should be set to true or false.

Thank you.

I will post the original discussion below.

https://github.com/codecentric/spring-boot-admin/pull/655
<img width="733" alt="screen shot 2018-03-02 at 23 46 31" src="https://user-images.githubusercontent.com/24989207/36904415-fa569cdc-1e73-11e8-9699-372d1852117a.png">

**Comment by joshiste** [comment]
As there is no one fit's all solution, I implemented that the default value is chosen on whether an active `CloudPlatform` is present or not.

**Comment by pltchuong** [comment]
IDK but It might be a good idea if all instances of one applications went down, with spring.boot.admin.client.auto-deregistration=true, SBA could keep the last instance and says that application is completely down.
