### ISSUE TITLE
Connect to external JMX service

### ISSUE THREAD

**Issue by JTWalraven** [codecentric/spring-boot-admin#659]
Is there a good way to hook up to a non Spring Boot JMX service to control with the admin console? Or to connect to the JMX service in the Spring Boot application and hook it into Spring Boot Admin through there?

For example: If I wanted to set up an ActiveMQ server and control it from the Spring Boot Admin console, is there a way I could do this without using an Embedded ActiveMQ instance?

Thanks for your awesome project!

**Comment by joshiste** [comment]
Hmm jolokia has the capaility of proxying requests for rmi connected jmx beans... May be you could setup a kind of sidecar which exposes the activeMq beans via jolokia...
