### ISSUE TITLE
Long flyway migration names, versions, and descriptions overflow poorly in the UI

### ISSUE THREAD

**Issue by gauravspatel** [codecentric/spring-boot-admin#660]
When the VERSION and DESCRIPTION and SCRIPT values are long, the contents of those fields overflow in weird ways.

VERSION: 2018011715235112234
DESCRIPTION:Environments and Servers
SCRIPT: V2018011715235112234__Environments_and_Servers.sql

Attached a screenshot depicting the overflow.

<img width="1020" alt="screen shot 2018-03-05 at 4 28 01 pm" src="https://user-images.githubusercontent.com/740432/37003297-35737284-2092-11e8-88ca-bf0b05a56ec4.png">

**Comment by joshiste** [comment]
We won't fix any minor issues for 1.5.x. Please check the 2.0.0-SNAPSHOT, it shouldn't have this issue.
