### ISSUE TITLE
HYSTRIX UI PROBLEM : MaxConcurrentConnections reached: 5

### ISSUE THREAD

**Issue by jt0526** [codecentric/spring-boot-admin#661]
I can use the hystrix ui. But when i refresh the hystrix page a few times, 
i can see this tip: ```Unable to connect to Command Metric Stream 'api/applications/dafb6816/hystrix.stream'.
Error: {"isTrusted":true}```.

 I find the `hystrix.stream` request url. The response info is ```{"timestamp":1520404344031,"status":503,"error":"Service Unavailable","message":"MaxConcurrentConnections reached: 5","path":"/hystrix.stream"}```

How should I solve this problem?

**Comment by tjuchniewicz** [comment]
Use following settings to increase connection count limit in Hystrix:
```json
hystrix:
  stream:
    maxConcurrentConnections: 10
  config:
    stream:
      maxConcurrentConnections: 10
```

You have to use both properties because property name was changed between Hystrix versions.

**Comment by jt0526** [comment]
I used the settings. If i refresh more times. 
The response info will be ```MaxConcurrentConnections reached: 10```.
The refresh behavior is abnormal?

**Comment by joshiste** [comment]
Duplicates #657. It's due to zuul's incapability to handle the infinite chunked http-stream

**Comment by jt0526** [comment]
thanks
