### ISSUE TITLE
Spring Boot Admin with Spring Boot 2.0.0 don't work

### ISSUE THREAD

**Issue by Danepic** [codecentric/spring-boot-admin#662]
When I migrated my application to Spring Boot 2.0.0 containing a Spring Boot Admin project, the error `java.lang.ClassNotFoundException: org.springframework.boot.bind.RelaxedPropertyResolver` appears, I deduced that the problem would be packages that are different in new version of Spring Boot, and Admin can not find this class, where the missing class is `org.springframework.boot.bind.RelaxedPropertyResolver`, could you clarify this doubt?

**Comment by joshiste** [comment]
you need to use Spring Boot Admin 2.0.0 (currently only 2.0.0-SNAPSHOT available) for Spring Boot 2.0
