### ISSUE TITLE
Question: Where does the dashboard derive the application version?

### ISSUE THREAD

**Issue by silentFred** [codecentric/spring-boot-admin#663]
Hey there,

Once again, thank you so much for this awesome contribution. Loving it!

Quick one: What property is used to set the application version of your eureka enabled application? (i'm just getting "unknown")

Kind regards,
Fred

**Comment by tjuchniewicz** [comment]
From `version` property at `/management/info`

**Comment by joshiste** [comment]
http://codecentric.github.io/spring-boot-admin/1.5.7/#show-version-in-application-list

**Comment by silentFred** [comment]
The management info approach does not work:

![image](https://user-images.githubusercontent.com/1550207/37168782-afd47f18-230e-11e8-8eac-ce15d9f8dc0b.png)

I'll have to play around with the maven boot plugin build info to see if that works

**Comment by silentFred** [comment]
Meta info with build version gets populated into build-info.properties but the version property is still not populated in the service instance info. Running spring-boot-starter-parent 1.5.10.RELEASE with spring-cloud-dependencies Camden.SR7

**Comment by joshiste** [comment]
Please show me the output of `/info`

**Comment by silentFred** [comment]
`{
build: {
version: "1.1.0-SNAPSHOT",
artifact: "some-msrv",
name: "Some Name",
group: "some.groupId",
time: 1520573631000
}
}`

**Comment by joshiste** [comment]
Which version of spring boot admin do you use? In 1.5.x there is an issue for the application list showing stale info... #556

**Comment by silentFred** [comment]
We are running 1.5.2 i'll try and update and see how far I get. What is a bit confusing is on the instance info object there is a version property (that has been deprecated in our version) that is populated as "unknown" has this field been discarded for tracking service versions? Apart from the version showing on boot admin we would also like to leverage versioning in other ways.

Thanks for the feedback!

**Comment by joshiste** [comment]
>  What is a bit confusing is on the instance info object there is a version property (that has been deprecated in our version on spring cloud) that is populated as "unknown" has this field been discarded for tracking service versions?

Sorry, but what are you referring to? SBA uses `version` or `build.version` from the `/info`-endpoint (in that order) for displaying the version - nothing else
