### ISSUE TITLE
project has server.context-path registry into eureka, springbootadmin only has "Details" and "Trace"

### ISSUE THREAD

**Issue by chentging** [codecentric/spring-boot-admin#665]
I have one project  that configure "server.context-path=/help" "server.port=61122","management.port=61122"
it registry into eureka, sringbootadmin only has "Details" and "Trace",
when i delete "server.context-path=/help",spring boot admin is "OK"
The following is my config file context:

application.properties
server.port=61122
server.context-path=/help
management.port=61122
management.security.enabled=false

eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port}
eureka.instance.metadata-map.management.context-path=${server.context-path}
eureka.instance.metadata-map.management.port=${management.port}
eureka.instance.health-check-url=http://${spring.cloud.client.ipAddress}:${server.port}${server.context-path}/health
eureka.client.serviceUrl.defaultZone=http://registry3.default.svc.cluster.local:61101/eureka
eureka.client.healthcheck.enabled=false

**Comment by joshiste** [comment]
can you show me the urls in the top-right of the details view?

**Comment by joshiste** [comment]
closed du to missing feedback
