### ISSUE TITLE
Support hyperlinks and ansi colors in output logs

### ISSUE THREAD

**Issue by y-luis** [codecentric/spring-boot-admin#670]
It would be nice Spring Boot Admin Logs tab support color-coded output (ANSI support) according to log levels.

**Comment by joshiste** [comment]
Usually you don't writ color output to plain files. As the `/logfile` endpoint just serves the logfile as resources I don't expect it to contain ascii escapes....

**Comment by joshiste** [comment]
p.s. PRs welcome :)

**Comment by joshiste** [comment]
I extendended this issue to support also hyperlinks for everything that looks like an url.
