### ISSUE TITLE
Custom logout URL

### ISSUE THREAD

**Issue by y-luis** [codecentric/spring-boot-admin#676]
I am running SBA integrated within an internal monitoring solution (which handles authentication). SBA runs in a specific context path (`spring.boot.admin.context-path=/sba`). The login is handled by a custom page. SBA logout button points to `sba/#/logout` but I need to use a custom logout page (not in `sba/` path). Is there any way to change this URL?

I am using `spring-boot-admin-server-ui-login` on my `pom.xml`, but I think that maybe other possible solution would be not to use that module and use a custom logout button on the navigation bar. Is this possible/recommended?

**Comment by joshiste** [comment]
copy and modify sources from spring-boot-admin-server-ui-login and include your custom jar instead of our.

**Comment by y-luis** [comment]
Thanks @joshiste for the suggestion. Since I do not know SBA source code, that is a time consuming task I can not afford right now. I came up with the idea of intercepting SBA logout request and redirect it to my custom path:

```java
@PostMapping("${spring.boot.admin.context-path}/logout")
public ModelAndView logout(HttpServletRequest request){
    request.setAttribute(View.RESPONSE_STATUS_ATTRIBUTE, HttpStatus.TEMPORARY_REDIRECT);
    return new ModelAndView("redirect:/logout");
}
```

which seems to work.
