### ISSUE TITLE
Instance Detail UI => Error in  Process, Threads, GC, Heap / Non Heap. Admin server using https eventhough instance is registered with http

### ISSUE THREAD

**Issue by shekharDivyanshu** [codecentric/spring-boot-admin#678]
Admin SERVER : 2.0.0.SNAPSHOT
Admin Client : 2.0.0.SNAPSHOT
Spring boot 2.0.0.Release

My admin client is registered with admin server using http 
http://**.**.***.***:****/manage
http://**.**.***.***:****/manage
http://**.**.***.***:****/manage/health

Admin server instance detail UI page shows error for Process, Threads, GC, Heap / Non Heap.
When i did inpect in chrome , i see it is trying to access using https.
https://**.**.***.***:****/manage/metrics/jvm.memory.committed?tag=area:heap

We believe, admin server UI instead of calling admin server url, it is trying to access instance url from local. Can we fix this bug in code so that it calls admin server url to fetch details for the instance?

**Comment by joshiste** [comment]
The UI does hit the SBA server and not the registered instances. The XHR requests are resolved against the address the html file is served from.
