### ISSUE TITLE
like #665 ,project has server.context-path registry into eureka, springbootadmin only has "Details" and "Trace"

### ISSUE THREAD

**Issue by piaohao** [codecentric/spring-boot-admin#681]
application.yml

server:
  context-path: /b-nb-mall-admin
spring:
  boot:
    admin:
      context-path: /admin

then the page only shows detail and trace, but has no data,  the firefox console shows many 404 request:
![default](https://user-images.githubusercontent.com/2724549/37884784-4302d5a4-30e4-11e8-896c-2e3d8ddcb849.png)

when i set server.context-path: / ,  it works fine.

**Comment by joshiste** [comment]
When using non-default context-/servlet-path you need to set the metadata accordingly. See reference guide: http://codecentric.github.io/spring-boot-admin/1.5.7/#_converting_serviceinstances_into_monitored_applications

**Comment by piaohao** [comment]
thank you ,as you say, i add a config in application.yml,
```
eureka:
  instance:
    metadata-map:
      management.context-path: /${server.context-path}
```
then, it works all right!
