### ISSUE TITLE
Support custom ui views in Spring Boot Admin 2.x

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#683]

**Comment by tetsushiawano** [comment]
can I try to solve this?

**Comment by iGitHubJ** [comment]
Not support Spring Boot Admin 2.x currently

**Comment by joshiste** [comment]
@tetsushiawano if you want to try please sketch the solution first and let's discuss it.

**Comment by tetsushiawano** [comment]
@joshiste thanks for advice. yes, let me sketch a probable solution first and move to discussion afterwards. I think I can sketch the solution by April 8th (Sunday).

**Comment by joshiste** [comment]
@tetsushiawano do you have any outcomings so far?

**Comment by tetsushiawano** [comment]
@joshiste
Sorry, I was busy and did not do it. I have time next week so let me look into it and try to have a proposal within a week.

**Comment by tetsushiawano** [comment]
@joshiste 
Sorry, I was busy with other things and could not cope it.
Let me get out of this ticket so someone else can solve it. 
Deeply sorry for delaying the resolution of this ticket.

**Comment by joshiste** [comment]
Closed with 75a960a7e631def8d5e0536a2677b4a20ca152d7 and aac3f00a829e80b74ca33d0592b026657dac1d54

docs: http://codecentric.github.io/spring-boot-admin/current/#customizing-custom-views

/cc @MrBW
