### ISSUE TITLE
Empty metrics values

### ISSUE THREAD

**Issue by tjuchniewicz** [codecentric/spring-boot-admin#687]
I get empty metrics value in SBA UI (1.5.4): 
```
cache.ObjectManager.size (count: ) 
gauge.hystrix.HystrixCommand.ABC:XYZ:abc.ABC:XYZ:abc:abcdefghijklmnopersuvxyzabcdefghijklmnopersuabcdefghij.propertyValue_abcdefghijklmnopersuvxyzabcdefghijklmnopersuabcd (count: ) 
```

Not sure but it may be related to long keys as in example above. This affects UI only. JSON returned by "raw JSON" link looks fine. 
Any limitations in keys length?

No errors in browser console.

**Comment by joshiste** [comment]
There is no limit that I'm aware of.
As the ui is completely re-written with 2.x and I haven't planned non-critical fixes for 1.5.x I'm closing this issue.
