### ISSUE TITLE
Integration with Spring Cloud Config

### ISSUE THREAD

**Issue by magaton** [codecentric/spring-boot-admin#69]
Is this maybe in your plans?

**Comment by joshiste** [comment]
So what features you'd like to see? refresh? restart?

**Comment by magaton** [comment]
Mainly configuration management: 
https://github.com/spring-cloud/spring-cloud-config

Restart,etc could be part of Docker UI, if spring boot apps are running as docker containers, but I think this is out of spring-boot admin scope.

**Comment by joshiste** [comment]
Please be a bit more specific. 

I don't think we will provide functionality for config-servers..
For config-client there are /refresh /restart /pause /resume and /env endpoints.
Reading /env is already implemented.
So which feature you desire most?

**Comment by magaton** [comment]
Put /env for each of the apps.
For example changing Db settings, external urls, operation modes, enything related to Environment which is read by ConfigurationProperties in Spring Boot

**Comment by jacquesboucher** [comment]
yes, /env would be great as well as reloading properties please
