### ISSUE TITLE
Question about TURBINE UI.  the threadpool does not display right TPS

### ISSUE THREAD

**Issue by bensonHe** [codecentric/spring-boot-admin#692]
I find Hystrix-Dashboard had fix this bug. https://github.com/Netflix/Hystrix/issues/1697 . but when i use spring boot admin , the Question is still exist.

EX:

I have 5 host, and every host have  about 190 TPS.
but the TURBINE UI display total tps is 190 TPS.  (the right tips should 900TPS)

![image](https://user-images.githubusercontent.com/2820041/38194031-b65ef03c-36a7-11e8-8eac-ec3b6645663b.png)

![image](https://user-images.githubusercontent.com/2820041/38193877-e77d77e8-36a6-11e8-8c44-23f6ae74edd0.png)

**Comment by bensonHe** [comment]
when i use hystrix-dashboard.  the display tps is right.

the version of SBA is 1.5.7

**Comment by joshiste** [comment]
I won't do fixes for the old UI in 1.5.x and therefore close this issue...

Btw the issue for hystrix is still unresolved according to the bugtracker
