### ISSUE TITLE
jvm.gc.memory.allocated is high

### ISSUE THREAD

**Issue by n0mer** [codecentric/spring-boot-admin#702]
![image](https://user-images.githubusercontent.com/1862997/38626803-b05728b4-3dad-11e8-8e2f-7a351c9ad437.png)

Hello, spring-boot-admin 2.0.0-BUILD.SNAPSHOT reports high value for metric `jvm.gc.memory.allocated` (2-4 GiB). This is strange, as another spring-boot based apps report values around 100MiB for the same metric:

![image](https://user-images.githubusercontent.com/1862997/38627047-4a84de86-3dae-11e8-808b-20316299d0a0.png)

If this is expected and known behaviour - then sorry for bothering.

**Comment by joshiste** [comment]
No it's not expected. Did you take a heap dump and inspected what's causing this issue?

**Comment by joshiste** [comment]
Did you use a recent snapshot (including the fix for #666)?

**Comment by n0mer** [comment]
@joshiste i can provide heap dump - but exact command to do it on Ubuntu would be appreciated :)

**Comment by joshiste** [comment]
@n0mer you can just download it via SBA. But please send it as a compressed file via mail since it may contain sensitive data.
Did you check which snapshot version you are using?

**Comment by n0mer** [comment]
@joshiste sure - what e-mail address i should use?

**Comment by n0mer** [comment]
![image](https://user-images.githubusercontent.com/1862997/39073161-235e5d32-44ed-11e8-8e70-1d8e23408d02.png)

this is strange for application started with `-Xms128m -Xmx512m -XX:MaxDirectMemorySize=256m`

**Comment by joshiste** [comment]
>How is this MAX calculated in "Memory: Non heap" section?

It's the `jvm.memory.max` value from micrometer (which uses the `MemoryPoolMXBean#getUsage().getMax()`

> sure - what e-mail address i should use?

https://github.com/codecentric/spring-boot-admin/blob/master/pom.xml#L94

**Comment by joshiste** [comment]
I guess it's the same underlying cause as in #713. Please try our latest snapshot.

**Comment by wind57** [comment]
@joshiste 

Why is a big number this value `jvm.gc.memory.allocated` bad? This makes no sense according to the code that [https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmGcMetrics.java#L177](computes it).

Specifically, this creates the "difference" what Eden used to look like and what it is now. In the majority of cases, _after_ is supposed to be zero (that is why GC exists to begin with) and _before_ is probably a bigger number. These differences are added together to produce that value. 

So as far as I understand the code, the value of `jvm.gc.memory.allocated` is only supposed to get bigger.
