### ISSUE TITLE
RemindingNotifier with initial delay

### ISSUE THREAD

**Issue by y-luis** [codecentric/spring-boot-admin#704]
I want the notification to be triggered periodically every X milliseconds, but with an initial delay of Y milliseconds.

How can I achieve that with the proposal mentioned at #498 of a combination of the `RemindingNotifier` and `FilteringNotifier`?

**Comment by joshiste** [comment]
Currently it's not possible to have an initial delay. But it should be possible to implement this by implementing a custom `NotificationFilter`
