### ISSUE TITLE
Spring boot admin 2.0 Endpoints not working

### ISSUE THREAD

**Issue by marifsami** [codecentric/spring-boot-admin#705]
Hi,

Getting following response for Spring boot admin 2.0 to all the endpoints
http://localhost:8081/instances/02f6c81bea9d/actuator/env

{
    "timestamp": "2018-04-17T21:00:30.921+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "org.springframework.web.reactive.function.client.ClientResponse.create(Lorg/springframework/http/HttpStatus;)Lorg/springframework/web/reactive/function/client/ClientResponse$Builder;",
    "path": "/instances/02f6c81bea9d/actuator/env"
}

**Comment by Himly1** [comment]
which spring boot version you useing？

**Comment by Himly1** [comment]
I got same error before，I think you need to use spring boot 2.1 for resolve this.

**Comment by limbaku** [comment]
Hi,

We've got the same error using SBA 2.0.0-SNAPSHOT and spring-boot-starter-web:2.0.1.RELEASE.

Any idea why?

Thanks,

Sandra

**Comment by limbaku** [comment]
Thanks for your quick reply :)

In fact we are using it.

org.springframework.boot:spring-boot-starter-webflux:2.0.1.RELEASE

This dependency has the 5.0.5 spring-webflux version
