### ISSUE TITLE
Two springbootamdin, different application status.

### ISSUE THREAD

**Issue by 82398485** [codecentric/spring-boot-admin#706]
Hello guru，
in the same environment, two springbootadmin ui show the app's status are defferent. 
One show is up, one show unkonwn(I wait more than 5 minutes)....  

Then i try to start another admin, all the application's status is up.
Can you give me some suggestions?  
Thanks.

**Comment by joshiste** [comment]
I guess the UNKNWON instance can't reach the application. You should have a look into the servers log...

**Comment by joshiste** [comment]
So any findings in your logs?

**Comment by joshiste** [comment]
closed due to missing feedback
