### ISSUE TITLE
SBA server 2.0.0-SNAPSHOT with Spring Boot 2.0.0.RC1 Issue

### ISSUE THREAD

**Issue by ernakulgoyal** [codecentric/spring-boot-admin#707]
Hello Guys!

I want to use SBA with Spring Boot v2, **client application is able to register with admin application** but I am **facing issue on viewing application details**, on my **admin application console** it gives,

**java.lang.NoSuchMethodError: org.springframework.web.reactive.function.client.ClientResponse.create**

have **included following dependencies**:

1)**Admin application**
spring-boot-starter-web 2.0.0.RC1
spring-boot-starter 2.0.0.RC1
spring-boot-admin-starter-server 2.0.0-SNAPSHOT
spring-boot-admin-server-ui 2.0.0-SNAPSHOT

2)**Client application**
spring-boot-starter-web 2.0.0.RC1
spring-boot-starter 2.0.0.RC1
spring-boot-admin-starter-client 2.0.0-SNAPSHOT
spring-boot-starter-security 2.0.0.RC1

**I followed** : http://codecentric.github.io/spring-boot-admin/current/#_what_is_spring_boot_admin

Any suggestions or leads would be really helpful.

**Kindly respond ASAP.**

**Comment by shakuzen** [comment]
Please try with the latest release version of Spring Boot. Currently that is `2.0.1.RELEASE`. The RC1 version you are using won't be compatible with the latest snapshots of Spring Boot Admin.

**Comment by joshiste** [comment]
what @shakuzen said - use boot 2.0.1

**Comment by ernakulgoyal** [comment]
Thanks @shakuzen @joshiste , it worked fine.
