### ISSUE TITLE
boot admin server behind and HAPROXY

### ISSUE THREAD

**Issue by bisegni** [codecentric/spring-boot-admin#708]
hi,
i have trouble to use admin server (2.0.0 SNAPSHOT) being messo ha proxy. U publish it to an HA path bu internally the ui seems to revere directly to "/" base path. I haven't seen in the documentation how changed the this behaviour and use  it behind a reverse proxy.

**Comment by joshiste** [comment]
I'll have a look on that. If I understand correctly you're doing url rewriting?

**Comment by bisegni** [comment]
When I call admin io from external url, “https://host/path” it try to load the js and other resource from https://host and not from https://host/path

**Comment by joshiste** [comment]
The simplest way of achieving this with the current 2.0.0-SNAPSHOT is to not do url rewriting and setting a contetxt-path in addition. This way a request to `/sba/` will be forwarded to `/sba/`.

excerpt from  application.properties:
```
server.servlet.context-path=/sba
```

excerpt from haproxy.cfg:
```
frontend public
    bind *:80
    use_backend spring-boot-admin if { path_beg /sba/ }
    default_backend default-backend

backend spring-boot-admin
    server host 192.168.179.26:8080
```
