### ISSUE TITLE
Problem with context path

### ISSUE THREAD

**Issue by diego522** [codecentric/spring-boot-admin#71]
I'm using this variable 'server.contextPath:/rio' in my applications.properties, but when the application starts, had problems
Did not find handler method for [/api/applications], and the applications fails to registry. 

 i tried to change this property

spring.boot.admin.contextPath=rio/api/applications

but the problem its the same, I can registry but now

Did not find handler method for [/rio/api/applications],

**Comment by joshiste** [comment]
Is the admin server a separate application? Sounds like it's the same you want to monitor?

So how are following properties set in the spring boot admin server:
* server.contextPath

And following in the client who wants to register:
* spring.boot.admin.url
* spring.boot.admin.contextPath

Note you can also just append the /rio to spring.boot.admin.url ... internally spring.boot.admin.url and .contextPath are just getting concatenated...

**Comment by stealed** [comment]
Hi, the admin server is in the same application. 
server.contextPath=/rio
spring.boot.admin.url=http://localhost:8080
spring.boot.admin.contextPath=/rio/api/applications
The app appears in the list of spring admin, but only appears as OFFLINE.
If we check the logs  the " Did not find handler method for [/api/applications]" Debug message appear.

If we remove the server.contextPath from the app its registered correctly.

Thanks in advance!

**Comment by joshiste** [comment]
First of all I recommend no to include the admin into the app you want to monitor..

This bug is due to this bug https://github.com/spring-cloud/spring-cloud-netflix/issues/270
Try pinning the version of spring-cloud-starter-zuul to 1.0.1.RELEASE
I' the meantime i update Spring Boot Admins dependencies.

**Comment by bosofelipe** [comment]
How to solve this problem?
