### ISSUE TITLE
New spring boot admin 2.0*

### ISSUE THREAD

**Issue by Tumeloq** [codecentric/spring-boot-admin#712]
I have just tried new spring boot admin and UI just shows instances running with no other actuator information like previous version.

**Comment by joshiste** [comment]
What did you expect?

**Comment by Tumeloq** [comment]
The previous version had all UI stuuf, like view Threads , beans, JMX  etc.

**Comment by joshiste** [comment]
Yeah the 2.0 version has too.
With spring boot you need to expose the actuator endpoints explicitly

**Comment by joshiste** [comment]
Use management.endpoints.web.exposure.include=*
