### ISSUE TITLE
Extreme high CPU utilization and CPU usage when on the details screen

### ISSUE THREAD

**Issue by andrashatvani** [codecentric/spring-boot-admin#713]
When on the details screen extreme high amount of memory will be used and freed cyclically causing also a high ~ 50% CPU usage. Since the heap dump is 200 MB after a fresh start and even with compression 40 MB, I can't attach it, but only a screenshot of the heap usage.

<img width="663" alt="screen shot 2018-04-24 at 08 54 37" src="https://user-images.githubusercontent.com/695746/39170996-c63b224e-479d-11e8-8e98-9b67e51378a3.png">

Once I switch to another tab, then the memory and CPU usage go back to normal.

Attached further screenshots after creating a heap dump.

<img width="663" alt="screen shot 2018-04-24 at 09 03 58" src="https://user-images.githubusercontent.com/695746/39171256-7b144510-479e-11e8-95e6-8734c6146718.png">
<img width="941" alt="screen shot 2018-04-24 at 09 03 29" src="https://user-images.githubusercontent.com/695746/39171265-7dac7c16-479e-11e8-9253-6cb42aa3ce0d.png">

**Comment by joshiste** [comment]
The requests to actuator endpoints causes memory allocation and this in turn causes garbage collections which burn some CPU. I don't see a problem here as long as no memory is leaking...

To reduce the GC pressure i've reduced the buffer size for the proxy requests. Previously 16K were initially allocated per requests. And the details page is doing a lot of requests. I've lowered the buffer size to 4K. Memory and GC usage should benefit from that.
