### ISSUE TITLE
 There are some unrelated applications 

### ISSUE THREAD

**Issue by 1140920375** [codecentric/spring-boot-admin#723]
Hello, my Admin has more OFFLINE applications and there are no useless applications in my Eureka. For example: http://localhost:8887/. This is for my local debugging. I confirm that these have been stopped. Can't get rid of it.

**Comment by joshiste** [comment]
Please query the `/applications` endpoint from the SBA server. If the unwanted applications have (source = http-api) they are registered via the sba admin client. (what I guess is just the case here)
