### ISSUE TITLE
Metrics in SBA 2.0.0

### ISSUE THREAD

**Issue by iamjohnwang** [codecentric/spring-boot-admin#724]
i have succesfully set up spring admin (with eureka discovery, actuator 2.x), services/instances can be discovered successfully, however, in serivce detail page, there's no metirs tab inforamtion, however other tab such as Environment/Loggers/Threads/HttpTraces/AuditLog/Heapdump can be showed correctly. I have confirmed metrics works find at those services(/metrics mapping)

Does anyone enconter this issue before and how can it be solved? Thanks.

**Comment by iamjohnwang** [comment]
@joshiste what's the plan to support metircs view in SBA2.0.0?

**Comment by joshiste** [comment]
I'm currently working on this, but I can't promise it to be included in the 2.0.0 release

**Comment by joshiste** [comment]
closed by ec449eeb9dea801d3b98e42325ef5d3621398223 and ec449eeb9dea801d3b98e42325ef5d3621398223
