### ISSUE TITLE
about spring boot and spring cloud version

### ISSUE THREAD

**Issue by dchack** [codecentric/spring-boot-admin#725]
Are there a list to show us what version about spring boot and spring cloud version to work with spring-boot-admin.
when i use 1.5.7.RELEASE spring-boot-starter-parent , there are a error .
`ERROR 60575 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.ewt360.cloud.admin.CloudAdminApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/cloud/commons/httpclient/HttpClientConfiguration.class] cannot be opened because it does not exist`

i can found single pom to show me what must be dependency, because  in the reference document, there is only like this:
`<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>`

but if you only write like this ,it can't work.

**Comment by joshiste** [comment]
The root pom contains the version SBA is using.
https://github.com/codecentric/spring-boot-admin/blob/master/pom.xml
