### ISSUE TITLE
2.0.x release

### ISSUE THREAD

**Issue by geirgp** [codecentric/spring-boot-admin#727]
The latest version I can find mvnrepository.com -search is 1.5.7 released in jan 2018. Since then the code has migrated to Spring Boot 2, yet I cannot find any releases. Am I looking in the wrong places or is 2.0.x yet to be released?

**Comment by joshiste** [comment]
duplicates https://github.com/codecentric/spring-boot-admin/issues/465#issuecomment-384539538
