### ISSUE TITLE
Can I use Spring Boot Admin Client in Spring Cloud client projects?

### ISSUE THREAD

**Issue by stdupanda** [codecentric/spring-boot-admin#729]
Can I use `spring-boot-admin-starter-client` in a Spring Cloud Project that has registered with an eureka server ?

like this: 
2.2.1 [http://codecentric.github.io/spring-boot-admin/1.5.7/#register-clients-via-spring-boot-admin](http://codecentric.github.io/spring-boot-admin/1.5.7/#register-clients-via-spring-boot-admin)

**Comment by joshiste** [comment]
http://codecentric.github.io/spring-boot-admin/1.5.7/#spring-cloud-discovery-support
