### ISSUE TITLE
Documentation needs to explain that client app needs info.id set, client needs to validate its presence

### ISSUE THREAD

**Issue by paulnuk** [codecentric/spring-boot-admin#73]
When a client tries to register with the server, the server code will throw an exception is info.id is not passed over in the client Application instance.

There should be validation in the client code to check whether or not info.id is set, and log if it isn't, rather than the server side code just failing and throwing a 500 back to the client.

The documentation needs to be updated to say that into.id must be set in the client application.properties/yaml

**Comment by joshiste** [comment]
Hmm I think you're using an older version of spring-boot-admin right? In the current 1.2.0 this isn't necessary...
