### ISSUE TITLE
Jolokia Auto-Configuration Does not Respect server.servlet.path property

### ISSUE THREAD

**Issue by gmcouto** [codecentric/spring-boot-admin#730]
If you have server.servlet.path property set on your application, all actuator endpoints will be moved to it accordingly, except the jolokia endpoints.

How the jolokia endpoint is:
http://host:port/context-path/actuator/jolokia

How the jolokia endpoint should be:
http://host:port/context-path/servlet-path/actuator/jolokia

Examples of other endpoints:
http://host:port/context-path/servlet-path/actuator/health
http://host:port/context-path/servlet-path/actuator/auditevents
http://host:port/context-path/servlet-path/actuator/beans

Soon I'll be posting a sample project.

**Comment by joshiste** [comment]
This is a spring boot issue not a spring boot admin issue.
see https://github.com/spring-projects/spring-boot/issues/12934.

**Comment by gmcouto** [comment]
Oh my god, sorry. With so many tabs open I haven't noticed I was posting in the wrong repository.
