### ISSUE TITLE
Spring Boot Admin&Client 2.0.0.SNAPSHOT with Spring - 2.0.1.RELEASE

### ISSUE THREAD

**Issue by ernakulgoyal** [codecentric/spring-boot-admin#731]
I am trying to use Spring Boot Admin, with mentioned versions, but facing issues setting it up using spring spring security. [client don't get registered to admin server.]

I didn't found any appropriate links/resources to start with.

Can you guys help or share some resources if any? Or any working client-admin with spring security sample  if you can share will be awesome. Thanks in advance.

you can also communicate on er.nakulgoyal@gmail.com

**Comment by joshiste** [comment]
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SpringBootAdminApplication.java

http://codecentric.github.io/spring-boot-admin/current/#securing-spring-boot-admin
