### ISSUE TITLE
Enabling HTTPS client end-points from Consul on SBA UI

### ISSUE THREAD

**Issue by gauravjavadeveloper** [codecentric/spring-boot-admin#733]
Hi,

We are using Consul to register our services and trying to get HTTPS end-points from Consul on SBA. Before, all of our applications were registered on the consul with HTTP and SBA was able to identify those HTTP end-points. But now we have HTTPS end-points and SBA is not able to identify the secured HTTPS end-points. SBA is still showing all the HTTP end-points and status as "OFFLINE". How can we achieve this?
<img width="1035" alt="screen shot 2018-05-09 at 1 47 42 pm" src="https://user-images.githubusercontent.com/25871974/39833627-45dce638-5390-11e8-800e-972e3e522edb.png">

**Comment by joshiste** [comment]
Are you using the  Spring Boot Admin Client (1) or the Service Discovery (2) based on consul?

1) You need to alter the url which is used to register at the server e.g. using the `spring.boot.admin.client.service-base-url``

2) the url is taken as is from the service discovery - I guess you need to reconfigure something. I can
t help you with that. As last resort you could add a custom `ServiceInstanceConverter` to your SBA server which rewrites the URL.

p.s. please also make sure that there is no other error (e.g. invalid certificate chain) present...
