### ISSUE TITLE
SBA with Multitenant Spring Boot Client Application 

### ISSUE THREAD

**Issue by ernakulgoyal** [codecentric/spring-boot-admin#735]
Hi @joshlong,

I have a multi-tenant [db per tenant] client application having one log file for each tenant.

Is there any alternative way to have 'logfile' endpoint configured / SBA configuration so that I can list all the log files or get log file based on the tenant identifier in SBA application?

Any leads will be really helpful. Thanks in advance.

**Comment by joshiste** [comment]
I guess there is no easy way around to write a custom endpoint and to customize the sba ui
