### ISSUE TITLE
Not Able to get HTTPS on SBA UI from discovered services in consul

### ISSUE THREAD

**Issue by gauravjavadeveloper** [codecentric/spring-boot-admin#737]
@joshiste @Nivedan3112 From closed Issue #574, I can see that you are able to get https client URL on spring boot admin UI. Can you please share the configuration to get https URLs on SBA UI? We're using consul for Service Discovery. Hence, we are using @enablediscoveryclient annotation in both SBA server and client app. On consul, our services are getting registered with https but on SBA UI, it is still showing http only and status as OFFLINE. If I hover on OFFLINE, I am getting "org.springframework.web.client.ResourceAccessException" with "ClientProtocolException". Please help!

**Comment by joshiste** [comment]
I'm no spring cloud consul user, but doing a quick search on the web tells me that you should go for setting `spring.cloud.consul.discovery.scheme=http`. 
This is no spring boot admin issue and in future please consult the according documentation first (Reference for Spring Cloud Consul in this case)
