### ISSUE TITLE
auto-deregistration is not working on our environment and want to raise a question.

### ISSUE THREAD

**Issue by tetsushiawano** [codecentric/spring-boot-admin#738]
I am investigating why auto-deregistration is not working for our running SBA (we are running the latest master as of yesterday.). And I come upon the following logic in spring-boot-admin-client's `RegisterApplicationListener.java`.
```
    @EventListener
    @Order(Ordered.LOWEST_PRECEDENCE)
    public void onClosedContext(ContextClosedEvent event) {
        if (event.getApplicationContext().getParent() == null) {
            stopRegisterTask();
            if (autoDeregister) {
                registrator.deregister();
            }
        }
    }
```
And the logic say that it will only execute `registrator.deregister()` when event.getApplicationContext().getParent() is null. So, I checked what the value of `event.getApplicationContext().getParent() and it was the following when we output with LOGGER.info("event.getApplicationContext().getParent() = {}", event.getApplicationContext().getParent());.
```
event.getApplicationContext().getParent() = org.springframework.context.annotation.AnnotationConfigApplicationContext@12843fce: startup date [Mon May 14 07:40:16 UTC 2018]; root of context hierarchy
```
so i was thinking maybe the logic should be as follows?
```
    @EventListener
    @Order(Ordered.LOWEST_PRECEDENCE)
    public void onClosedContext(ContextClosedEvent event) {
        if (event.getApplicationContext().getParent() != null) {
            stopRegisterTask();
            if (autoDeregister) {
                registrator.deregister();
            }
        }
    }
```
Would like anyones feedback! Thanks!

Note) We are sure that `spring.boot.admin.client.auto-deregistration` is set to true.

**Comment by joshiste** [comment]
`event.getApplicationContext().getParent() == null` ist used to only dereigster once when the root context ist closed.
Could you investigate why the `ClosedContextEvent` isn't published for your root context?

**Comment by tetsushiawano** [comment]
Thanks! I will check this point today!

**Comment by tetsushiawano** [comment]
I checked the program today but I don't have enough knowledge to understand the lifecycle of the application context. @joshiste , can you give me advice where I should start looking? I asked some people and it seems application context is not created by spring-boot-admin-client but rather in the spring-boot application itself.

**Comment by shakuzen** [comment]
@joshiste I debugged this some, and the root context is the Spring Cloud bootstrap context. For reasons I still don't understand, it doesn't get the `ClosedContextEvent`, which I can reproduce in an application with only the `spring-cloud-starter` dependency and an `@EventListener` for `ContextClosedEvent`. It is only called for the main application's `ClosedContextEvent`. So I don't think the auto-deregistration when on a cloud platform feature is working for any applications using Spring Cloud.

**Comment by joshiste** [comment]
@shakuzen ah yeah thanks. IIRC we had this once before....
