### ISSUE TITLE
How avoid the certificate validation in spring-boot-admin?

### ISSUE THREAD

**Issue by cameno94** [codecentric/spring-boot-admin#740]
The endopoint is displayed as offiline, I want to avoid validating the certificate, this would have to be done from the client?

I have the class that omits the validation of the certificate, but I do not know how to send it to call, the spring-boot-client-admin works automatically.

![image](https://user-images.githubusercontent.com/38191156/39971971-515ed244-56cb-11e8-8eda-2db9e35c41d5.png)

This is my class for skip the certificate validation
```
public RestTemplate getRestTemplate() throws KeyStoreException, NoSuchAlgorithmException, KeyManagementException {
TrustStrategy acceptingTrustStrategy = new TrustStrategy() {
@override
public boolean isTrusted(X509Certificate[] x509Certificates, String s) throws CertificateException {
return true;
}
};
SSLContext sslContext = org.apache.http.ssl.SSLContexts.custom().loadTrustMaterial(null, acceptingTrustStrategy)
.build();
SSLConnectionSocketFactory csf = new SSLConnectionSocketFactory(sslContext, new NoopHostnameVerifier());
CloseableHttpClient httpClient = HttpClients.custom().setSSLSocketFactory(csf).build();
HttpComponentsClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory();
requestFactory.setHttpClient(httpClient);
RestTemplate restTemplate = new RestTemplate(requestFactory);
return restTemplate;

```

**Comment by joshiste** [comment]
I encourage you to add the certificate to your key chain so that the validation does not fail.

If there is no alternative to disable the validation you'd need to do roughly two things:
1) Instantiate the `StatusUpdater` in the SBA Server yourself with your custom RestTemplate
2) Disable the certificate validation for zuul. I don't have any clue on how to do this.

**Comment by crea1** [comment]
I found a workaround that skips certificate validation. Not sure if it is optimal, but I have not found any other solutions. 

https://stackoverflow.com/questions/50320573/how-avoid-the-certificate-validation-in-spring-boot-admin/55258603#55258603

**Comment by vanicekv** [comment]
Is there any way in the new version to avoid validating the certificate on both the server side and the client side? No solution found does not work. Is there a parameter that can disable cert validation?

Thank you!

_Spring Boot v2.5.4 & Kotlin & Spring Boot Admin v2.5.1_

**Comment by mina-bedier** [comment]
> Is there any way in the new version to avoid validating the certificate on both the server side and the client side? No solution found does not work. Is there a parameter that can disable cert validation?
> 
> Thank you!
> 
> _Spring Boot v2.5.4 & Kotlin & Spring Boot Admin v2.5.1_



> Is there any way in the new version to avoid validating the certificate on both the server side and the client side? No solution found does not work. Is there a parameter that can disable cert validation?
> 
> Thank you!
> 
> _Spring Boot v2.5.4 & Kotlin & Spring Boot Admin v2.5.1_

@vanicekv did you find any way or workaround to overcome this issue ?

**Comment by vanicekv** [comment]
> > Is there any way in the new version to avoid validating the certificate on both the server side and the client side? No solution found does not work. Is there a parameter that can disable cert validation?
> > Thank you!
> > _Spring Boot v2.5.4 & Kotlin & Spring Boot Admin v2.5.1_
> 
> @vanicekv did you find any way or workaround to overcome this issue ?

@mina-bedier Unfortunately not - still the same problem.

**Comment by mina-bedier** [comment]
> > > Is there any way in the new version to avoid validating the certificate on both the server side and the client side? No solution found does not work. Is there a parameter that can disable cert validation?
> > > Thank you!
> > > _Spring Boot v2.5.4 & Kotlin & Spring Boot Admin v2.5.1_
> > 
> > 
> > @vanicekv did you find any way or workaround to fix this issue ?
> 
> @mina-bedier Unfortunately not - still the same problem.

@vanicekv  Finally I did it and it works properly . All you need to do is to export your client SSL Certificate and import it in JVM which run you spring admin server .

**Comment by vanicekv** [comment]
> 
> 
> @vanicekv Finally I did it and it works properly . All you need to do is to export your client SSL Certificate and import it in JVM which run your spring admin server . check through this link https://stackoverflow.com/questions/69318387/general-sslengine-exception-at-spring-boot-dmin-server-when-spring-admin-client

Thank you, I will try this procedure! So although it is not an ideal solution and it should definitely be solved directly in Spring Boot.

**Comment by vanicekv** [comment]
Did anyone accidentally turn off the validation of the hostname against the certificate? I would need to run this for the internal API, so it is not possible to add all possible IP addresses and domain names to the certificate. 

`javax.net.ssl.SSLPeerUnverifiedException: Certificate for <x.x.x.x> doesn't match common name of the certificate subject: X X X Name`

I was unable to implement the use of Spring RestTemplate. Has anyone solved it yet?
