### ISSUE TITLE
Send Notifications when Heap crosses a certain threshold

### ISSUE THREAD

**Issue by indraneelb1903** [codecentric/spring-boot-admin#742]
Hello
Would it be a good idea to allow sending notifications , when the heap for an application crosses a certain threshold which would be configurable like 80 percent of the Heap size.  I see right now , the only trigger to send a notification is a Status Change, which is good and covers a lot of use-cases but would this be a good addition?

**Comment by joshiste** [comment]
duplicates #695
please read my comment on this: https://github.com/codecentric/spring-boot-admin/issues/695#issuecomment-378718207
