### ISSUE TITLE
spring boot admin 2.0.0 can't find service with DiscoverClient  via zookeeper

### ISSUE THREAD

**Issue by ExtremeYu** [codecentric/spring-boot-admin#745]
this is the demo project ,only when set the absolute url(eg.spring.boot.admin.client.url=http://localhost:8070 ) , then the sba can find the service.
[workspace.zip](https://github.com/codecentric/spring-boot-admin/files/2023243/workspace.zip)

**Comment by gwr0-0** [comment]
升级到spring boot 2.0.2就这样了

**Comment by ExtremeYu** [comment]
@gwr0-0  我用的spring boot 2.0.1 spring boot admin 是2.0.0 照着教程做就这样了

**Comment by joshiste** [comment]
As Spring Cloud Finchley isn't released yet, the 2.0.0 release doesn't include discovery support as noted here: https://github.com/codecentric/spring-boot-admin/releases/tag/2.0.0
If you need Spring Cloud Finchley support you need to switch to out 2.0.1 snapshot version

**Comment by ExtremeYu** [comment]
okay, the doc does not indicate the sba 2.0.0 not support the feature. but the doc introduced. [](http://codecentric.github.io/spring-boot-admin/2.0.0/)
