### ISSUE TITLE
Question: spring boot admin 2.0.0 default username and password

### ISSUE THREAD

**Issue by mrcasablr** [codecentric/spring-boot-admin#746]
Thank you for this wonderful project! I'm new to spring boot admin 2.0.0 and have the following in my gradle build file - 

```
        compile( "org.springframework.boot:spring-boot-starter-web:${springBootVersion}" )
        compile( "org.springframework.boot:spring-boot-starter-mail:${springBootVersion}" )
        compile( "org.springframework.boot:spring-boot-starter-aop:${springBootVersion}" )
        compile( "org.springframework.boot:spring-boot-starter-security:${springBootVersion}" )
        compile( 'org.springframework.retry:spring-retry:1.2.2.RELEASE' )
        compile( "org.springframework.cloud:spring-cloud-starter-config:2.0.0.RC1" )
        compile( 'de.codecentric:spring-boot-admin-starter-server:2.0.0' )
        compile( 'de.codecentric:spring-boot-admin-server-ui:2.0.0' )
//      compile( 'de.codecentric:spring-boot-admin-server-ui-login:2.0.0' )
        testCompile( 'org.springframework.boot:spring-boot-starter-test' )
```
Spring Boot version is 2.0.2. On running the spring-boot-admin.jar, I get a default login page (I think from spring boot security). I googled around for a default username and password and could not find any references. How do I set the username and password on the server configuration as I do not see any configuration options on the server (or maybe I overlooked :)

**Comment by mrcasablr** [comment]
After a bit of reading and experimentation, the following configuration in the spring boot admin application properties worked -

```
spring.security.user.name=${SBA_USER}
spring.security.user.password=${SBA_PASS}
```

**Comment by joshiste** [comment]
The sample https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet contains a spring security config and also uses fixed username / password
