### ISSUE TITLE
Clustering of Spring boot Admin?

### ISSUE THREAD

**Issue by Nivedan3112** [codecentric/spring-boot-admin#747]
Hello Folks , 

We started using spring boot admin tool in our organization , we would like to know how to achieve clustering for this tool.

Example Server 1 , Server 2 and Server 3 has 3 instances of spring boot admin. Do we specify clustering configuration any where for admin server?. Any help or examples on this would help as i didnt understand much on hazelcast config.

Thank you

**Comment by joshiste** [comment]
It's essential to gain a bit of hazelcast knowledge. There is a sample for hazelcast https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-hazelcast
