### ISSUE TITLE
Can  2.0.1-SNAPSHOT SBA support  spring cloud Finchley.RC1 and spring boot 2.0.1.RELEASE

### ISSUE THREAD

**Issue by cy1ng** [codecentric/spring-boot-admin#748]
hello! 
 I found that  client can't register to spring boot admin server  with eureka!
 Is my version not support?
  thx!

**Comment by GertVil** [comment]
I think you have to add the following dependency too atm:
`            <dependency>
                <groupId>de.codecentric</groupId>
                <artifactId>spring-boot-admin-server-cloud</artifactId>
                <version>2.0.1-SNAPSHOT</version>
            </dependency>`

cfr this commit: https://github.com/codecentric/spring-boot-admin/commit/caf44221c200cbaeb281124f9c47a606c5dfbd33

**Comment by cy1ng** [comment]
Problem solved ! thank you very much!

**Comment by joshiste** [comment]
The `de.codecentric:spring-boot-admin-starter-server:2.0.1-SNAPSHOT` includes the -cloud module as dependency. I suggest you use our starter and you don't need to include the dependency yourself
