### ISSUE TITLE
Actuator data of older Spring Boot version (1.4) are not rendered with sba 2.0.0

### ISSUE THREAD

**Issue by lidkowiak** [codecentric/spring-boot-admin#749]
Hi, 
actuator data of older Spring Boot version (1.4) are not rendered with sba 2.0.0. 

There are errors in JavaScript: e.g. for Environment tab:` TypeError: Cannot read property 'length' of undefined at i.va (index.vue?689e:1) at i.e._render (vue.runtime.esm.js:4540).` Is it possible to solve this?

**Comment by joshiste** [comment]
which endpoint are you referring to? all of 'em?

**Comment by lidkowiak** [comment]
There are problems with metrics, environment, threads and http traces tab.
Actuator data are fetched successfully. The errors occous in JS.
![przechwytywanie](https://user-images.githubusercontent.com/7756916/40420076-78a1f52a-5e87-11e8-8b49-4fe65b066178.PNG)

**Comment by SeanWangDev** [comment]
I run into the same thing. 

Currently we have all services with spring boot 1.4 on spring cloud Camden.SR7.  But sba 1.4.6 can only render health. Did I miss something? or should I just use sba 2.0 instead😳😳

**Comment by tjuchniewicz** [comment]
@SeanWangDev Please take a look at this issue: https://github.com/codecentric/spring-boot-admin/issues/527

**Comment by SeanWangDev** [comment]
Thanks @tjuchniewicz ,  HEAD requests do fail. I'll check this out.

**Comment by zhourongyu** [comment]
I use sprint-boot2.0, There was also this error

**Comment by SeanWangDev** [comment]
I've got sbt 1.5.7 work on eureka Camden and spring boot 1.5.x clients. 

#527 does help, thanks to @tjuchniewicz again.

The key of debugging was the routes/ endpoint exposed by sba. This endpoint prints the current zuul mapping from sba endpoints to eureka clients' actuator endpoints. 

My zuul mapping shows wrong context-path to spring boot actuator end points. So I set `spring.boot.admin.discovery.converter.management-context-path` to correct it.

**Comment by joshiste** [comment]
so is this issue now resolved?

**Comment by joshiste** [comment]
1.4.x and older doesn't have the vendor content-type for spring boot actuator. We need to take plain json content type into account for the legacy converters
