### ISSUE TITLE
Actuator endpoints of client apps have to be public reachable?

### ISSUE THREAD

**Issue by MichaelF25** [codecentric/spring-boot-admin#75]
I was wondering if the actuator endpoints of my monitored client apps have to be reachable by the respective browser which is accessing SpringBootAdminServer UI.

I am currently running an application which consists of 4 (including SpringBootAdminServer) Spring Boot applications. Everything works as expected in my local vagrant based setup.
However in my staging environment (which is identically configured to prod environment) we're using some Nginx HTTPS reverse proxies in front of our Spring Boot applications which are only exposing required endpoints to the public internet. So the Spring Boot Admin Server is able to access for example the `/logfile` endpoint of it's client applications. I was assuming that the Spring Boot Admin Server is also acting as some kind of proxy between the users browser and the monitored client apps but that is (at least in my setup) not the case.

Is this from an architectural approach intended?

**Comment by joshiste** [comment]
The admin server is indeed a reverse proxy to the application. But the UI references not the proxy url for the logfile :(
Do the other views in admin ui work?

**Comment by MichaelF25** [comment]
Ok, so is there any planned improvement regarding the logfile?

More important to me currently is logging and JMX - both are not working (just empty).

**Comment by joshiste** [comment]
Can you provide a small sample to reproduce and clarify how your network is
setup and what urls are reachable from browser and admin server?

**Comment by MichaelF25** [comment]
- Spring Boot Admin server running on Port 8080
- Spring Boot Client app running on Port 8090
- Nginx forwards all HTTP traffic automatically to HTTPS and acts as reverse proxy for service endpoints provided by Spring Boot Client app running on Port 8090
- All services are running on the same machine

**Comment by joshiste** [comment]
So the Admin-UI and REST-Interface is also routed via nginx? I don't see any reason why this shouldn't work. The POST-requests to the jolokia endpoint are routed via `/api/applications/{id}/jolokia`. Please check your browser console and network monitor to see what's happening.
And you can try the 1.2.1-SNAPSHOT in the [sonatype repo](https://oss.sonatype.org/content/repositories/snapshots/) 

Regarding the logfile link i will fix it before the 1.2.1.RELEASE

**Comment by MichaelF25** [comment]
Upgraded to 1.2.1-SNAPSHOT (both admin and client app) without change (except of changed property name in client configuration [`serviceUrl` now instead of `url`]).

The endpoint `/api/applications/{id of my client app}/jolokia` is reachable from my browser.

**Comment by joshiste** [comment]
Have you tried if post requests are well served from there?

**Comment by joshiste** [comment]
I did a small docker setup using haproxy in front of an admin-server and client. The haproxy port is exposed and only forwarding to the admin server.
Everything looks good. I guess there is something wrong in your setup...

**Comment by MichaelF25** [comment]
Checked again today and now everything works as expected - double checked the deployment logs of your CD system and there was definitely no other deployment in between. So my best guess is that Chrome tricked my yesterday with it's caching :-(

Sorry for any inconvenience and many thanks for your support!
