### ISSUE TITLE
spring-boot-admin-server-cloud on maven central

### ISSUE THREAD

**Issue by sluglit** [codecentric/spring-boot-admin#752]
I am trying to use spring-boot-admin-server 2.0.0 with eureka auto discovery and none of the clients are being detected.

Looking through the source code I noticed that spring-boot-admin-server doesn't use DiscoveryClient.
It appears that this code has moved into spring-boot-admin-server-cloud.

Unfortunately spring-boot-admin-server-cloud doesn't exist in central.

Could you help point me in the right direction?

**Comment by joshiste** [comment]
As spring-boot-admin-server-cloud is depending on Spring Cloud Finchley which isn't released yet I had to remove the module for the 2.0.0 release. 
Either you use our 2.0.1-SNAPSHOT version or wait for the 2.0.1 release which will follow close to the Finchley release and will include support for it.
