### ISSUE TITLE
SBA client on CloudFoundry, routes value ("vcap.applications.uris") does not update when changed at runtime.

### ISSUE THREAD

**Issue by tetsushiawano** [codecentric/spring-boot-admin#761]
Sharing the issues we faced recently.

On CloudFoundry, routes is like "sub-domain.domain.com/applicationA". routes is for defining the access url to the CloudFoundry application. and this routes can change dynamically at runtime using CloudFoundry commands ("cf").

For SBA client running on CloudFoundry environment, routes is retrieved (as "vcap.application.uris") from the below class ("CloudFoundryApplicationProperties") at the timing of starting up the application.
https://github.com/codecentric/spring-boot-admin/blob/976619f4ea4357d85d551637bc3de8b483cdeb58/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/config/CloudFoundryApplicationProperties.java#L28
And we confirmed that even when the routes is changed to "sub-domain.domain.com/applicationA-temp" for example, the class ("CloudFoundryApplicationProperties") remains to have the original value of "sub-domain.domain.com/applicationA". 

Ideally,
routes information should be updated on SBA client side.

(remarks)
actually only confirmed that the serverUrl and healthUrl does not change to the new one. so we are assuming that routes "vcap.application.uris" is not changing.

**Comment by joshiste** [comment]
> For SBA client running on CloudFoundry environment, routes is retrieved... at the timing of starting up the application.

That's right. The information is currently taken from the environment variables, which can't be changed for a running process. So we need to obtain the needed information somehow differently. Is there an api we can query?

**Comment by tetsushiawano** [comment]
do you mean an api which return routes information? 
let me check it tomorrow and write what i find out.

**Comment by tetsushiawano** [comment]
I find cloud foundry api which return all routes of the application.
https://apidocs.cloudfoundry.org/1.37.0/apps/list_all_routes_for_the_app.html

Also, I checked the environment variable of cf instance. 
https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html
It have cf_api which is the base endpoint of the cf api. 
So maybe it is possible to call the cf api from the cf instance.
<img width="802" alt="screen shot 2018-05-31 at 14 14 05" src="https://user-images.githubusercontent.com/24989207/40762783-0506d656-64dd-11e8-8c41-57054a8584a1.png">

**Comment by joshiste** [comment]
@tetsushiawano are you willing to provide a PR which enhances the `CloudFoundryApplicationFactory`. I am no CF user and so this enhancement is low priority for me.

**Comment by stwomack** [comment]
Hey @tetsushiawano , any updates here? We could use this feature for sure!

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.
