### ISSUE TITLE
Spring boot admin client status down up up down again and again

### ISSUE THREAD

**Issue by qiubigbig** [codecentric/spring-boot-admin#763]
I have spring boot admin integrate with eureka, and they two is in the same server, e.g. now I have three servcies, eureka server, config server and business service(call service A), servcie A register with eureak and fetching configration from config server(register with eureak too), at first, all they three set up, everything goes well, when I stop the config server, the servcie A status from up to down, and after about 15 seconds, it's status from down to up, and then after 5 minutes, service A status from up to down, then loop... until I setup config server, service A works well back.
I use spring boot 1.5.8 and spring boot admin server 1.5.7

**Comment by qiubigbig** [comment]
![instance](https://user-images.githubusercontent.com/39792576/40772030-8037cd30-64f1-11e8-94dd-4551a4f7db45.png)
I wite code to listen to ClientApplicationEvent

@EventListener
	public void listenAndMailNotify(ClientApplicationEvent event) {
		boolean notRestart = TimeUtil.isNotBelongToRestartTime(env.getProperty(RESTART_BEGIN_TIME),
				env.getProperty(RESTART_END_TIME), env.getProperty(RESTART_TIMEZONE), env.getProperty(DATE_FORMAT));
		String eventType = event.getType();
		if (notRestart) {
			Application app = event.getApplication();
			String from = null;
			if (event instanceof ClientApplicationStatusChangedEvent) {
				ClientApplicationStatusChangedEvent statusChange = (ClientApplicationStatusChangedEvent) event;
				from = statusChange.getFrom().getStatus();
			}
			LOGGER.info("{}({}) current status is {}, event type is [{}], healthUrl is [{}], mail from server [{}]",
					getServiceNameFromMetadata(app), getInstanceId(app), getInstanceCurrentState(app),
					getEventType(event), getHealthUrl(app), localHostName);
			LOGGER.info("instance status changed, ready to send an email.");
			mailServiceInitAndSend(app, eventType, from);
			LOGGER.info("send mail already.");
		} else {
			LOGGER.info(
					"the time [ " + TimeUtil.dateFormat(env.getProperty(RESTART_TIMEZONE), env.getProperty(DATE_FORMAT))
							+ " ] is during restart time(19:05:00.000-19:48:00.000).");
		}
	}

**Comment by joshiste** [comment]
Imho this is a problem with your health indicator reporting the application is down.
