### ISSUE TITLE
Flyway tab doesnt display anything

### ISSUE THREAD

**Issue by geniusit** [codecentric/spring-boot-admin#766]
Hi,

I have a SB2 application with actuator. Flyway endoint is enabled.

I can see flyway data migration when i curl http://localhost:8090/actuator/flyway

But when I start the SBA2 application, the Flyway tab is visible but nothing happens when Im clicking on it ... No client error in console... Why ? I also can see Flyway migration when using the JMX tab on SBA2. Why the Flyway tab doesnt display anything? Please help

**Comment by joshiste** [comment]
I can't reproduce the issue. It works for me using the [spring-boot-sample-flyway](https://github.com/spring-projects/spring-boot/tree/2.0.x/spring-boot-samples/spring-boot-sample-flyway)
Please provide a project (GH repo or zip file to reproduce the error).

response for `/actuator/flyway`:
```
{
  "contexts": {
    "application": {
      "flywayBeans": {
        "flyway": {
          "migrations": [
            {
              "type": "SQL",
              "checksum": 2067935395,
              "version": "1",
              "description": "init",
              "script": "V1__init.sql",
              "state": "SUCCESS",
              "installedBy": "SA",
              "installedOn": "2018-06-09T22:33:47.922Z",
              "installedRank": 1,
              "executionTime": 19
            }
          ]
        }
      },
      "parentId": null
    }
  }
}
```

**Comment by geniusit** [comment]
I understood, the problem is due to this line in my configuration : property-naming-strategy: SNAKE_CASE
I don't know if i can override the property for actuator (CAMEL_CASE)
Or may be it can be interesting to add the possibility to SBA to deal with a different case ?

**Comment by joshiste** [comment]
duplicates #751
