### ISSUE TITLE
About server.context-path

### ISSUE THREAD

**Issue by shmilyah** [codecentric/spring-boot-admin#770]
when spring boot application has registered in eureka set server.context-path=/gateway, what spring boot admin should to do? Because spring boot admin does not monitor the spring boot application, and dose not get the spring boot application data. Please help me ,thanks!

**Comment by dickerpulli** [comment]
There is nothing extra configuration to do when server.servlet.context-path is set. 
Which version of Spring Boot (Admin) are you using?

**Comment by shmilyah** [comment]
Thanks for your reply. I have found the answer.If the application has registered in eureka set server.servlet.context-path, at the same time, the application must set eureka.instance.health-check-url and metadata-map and so on. Thanks again!

**Comment by shmilyah** [comment]
Each version is the same.

**Comment by waincent** [comment]
`eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    **metadata-map:
      "management.context-path": ${server.servlet.context-path}/actuator**
    home-page-url-path: ${server.servlet.context-path}
  client:
    service-url:
      defaultZone: http://${SERVER_EUREKA_HOST:localhost}:8761/eureka/`

this work fine.
