### ISSUE TITLE
Introduce possiblity to influence grouping of applications with multiple pods

### ISSUE THREAD

**Issue by HolgerNeub** [codecentric/spring-boot-admin#773]
In a cluster environment (e.g. K8s) SBA neatly grops applications with the same name or IP, So multi pod applications are presented as one. 

However in situations where lets say the same application is deployed in multiple namespaces, then the are by mistake grouped as one application in SBA. 

Therefore I would like to have the possiblity to either

- instruct SBA how to group the applications by adding configurable dimensions. (e.g spring.boot.admin.client.group : "namespace-name")
- determine the namespace automatically from the application env and group by it.

(We talked about that during spring io conf).

Cheers
Holger

**Comment by joshiste** [comment]
> In a cluster environment (e.g. K8s) SBA neatly grops applications with the same name or IP,

just by name, not by ip

I think the easiest is to use @dickerpulli's solution and just prefix the application-name with the namespace. We don't have a notion of application-groups and currently I refuse to add this complexity. 
In case you are using the sba client you could implement your own `ApplicationFactory` which takes the namespace from the environment and does the prefixing automatically...

**Comment by uqix** [comment]
You can add k8s namespace to service name like [this](https://github.com/uqix/spring-boot-admin-k8s/blob/master/src/main/java/app/K8sNamespacedServiceInstanceConverter.java):

```java
package app;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.cloud.client.ServiceInstance;
import org.springframework.stereotype.Component;

import de.codecentric.boot.admin.server.cloud.discovery.KubernetesServiceInstanceConverter;
import de.codecentric.boot.admin.server.domain.values.Registration;

@Component
@ConfigurationProperties(prefix = "spring.boot.admin.discovery.converter")
class K8sNamespacedServiceInstanceConverter extends KubernetesServiceInstanceConverter {

    @Override
    public Registration convert(final ServiceInstance instance) {
        return Registration.copyOf(super.convert(instance))
            .name(instance.getMetadata().get("k8s_namespace") + "/" + instance.getServiceId())
            .build();
    }
}
```
