### ISSUE TITLE
Hystrix in 2.x

### ISSUE THREAD

**Issue by nperry0** [codecentric/spring-boot-admin#774]
Is the hystrix dashboard coming to 2.x?

**Comment by joshiste** [comment]
duplicates #657

**Comment by MartinDevillers** [comment]
I've published a plugin for Spring Boot Admin 2 that adds Hystrix Dashboard. To use it, simply drop the following Maven dependency in your Spring Boot Admin's `pom.xml`
```xml
<dependency>
    <groupId>nl.devillers</groupId>
    <artifactId>spring-boot-admin-hystrix-dashboard</artifactId>
    <version>1.0.2</version>
</dependency>
```
More info: https://github.com/MartinDevillers/spring-boot-admin-hystrix-dashboard

Hope it helps someone :-)
