### ISSUE TITLE
Version 2.0 doesn't support auto registration with discovery client?

### ISSUE THREAD

**Issue by iBryan99** [codecentric/spring-boot-admin#776]

**Comment by lehuqizhong** [comment]
I hava the same question spring.boot.admin.client.url is work well but discovery client doesn't work

**Comment by christianschaible** [comment]
I have the same problem. Clients aren't automatically discovered from eureka. The UI of SBA is accessible but doesn't display any data.

My configuration uses: 
- Spring Boot 2.0.2
- Finchley.RC2
- SBA 2.0.0

**Comment by joshiste** [comment]
The discovery feature was removed from 2.0.0 as Spring Cloud Finchley is not released yet, currently you need to use our 2.0.1-SNAPSHOT.

**Comment by Macrame** [comment]
Now, Spring Cloud Finchley was released. But the spring boot admin does not  display any data.

**Comment by joshiste** [comment]
Did you switch to sba 2.0.1?

**Comment by n0mer** [comment]
@joshiste i have the same problem, with the following versions:

```yaml
    ext {
        springbootVersion = '2.0.3.RELEASE'
        springCloudVersion = 'Finchley.RELEASE'
        springCloudNetflixVersion = '2.0.0.RELEASE'
        springbootAdminVersion = '2.0.1'
        springIoPlatformVersion = 'Cairo-SR2'
    }
```

**Comment by joshiste** [comment]
IIRC gradle has some slightly different resolution algorithm than maven. 

Using this easy sample using maven works for me:
[sba-eureka.zip](https://github.com/codecentric/spring-boot-admin/files/2133996/sba-eureka.zip)

**Comment by joshiste** [comment]
p.s. since 2.0.0 Spring Boot Admin itself has a BOM `de.codecentric:spring-boot-admin-dependencies`.

**Comment by joshiste** [comment]
yes it contains the disocvery stuff... either you depend on that or you use the
`spring-boot-admin-starter-server` which pulls it in.

**Comment by n0mer** [comment]
@joshiste indeed - i use plain dependencies:

```
    compile 'de.codecentric:spring-boot-admin-server'
    compile 'de.codecentric:spring-boot-admin-server-ui'
    compile 'de.codecentric:spring-boot-admin-server-cloud'
```

**Comment by LiudmilaObregon** [comment]
> IIRC gradle has some slightly different resolution algorithm than maven (esp. when using BOMs)
> 
> Using this simple sample using maven works for me: [sba-eureka.zip](https://github.com/codecentric/spring-boot-admin/files/2133996/sba-eureka.zip)

Hello. Please is any example with securiy configuration for eureka and sba in one application?
