### ISSUE TITLE
Periodically check for `/actuator/info` updates

### ISSUE THREAD

**Issue by GertVil** [codecentric/spring-boot-admin#786]
I had an app deployed with version 1.0.0-SNAPSHOT and then deployed the release version 1.0.0. When clicked on the application through the Applications tab it shows the correct version in the info/build overview. On the Wallboard and Applications tab however it shows the old 1.0.0-SNAPSHOT version. 
Is this data retrieved from another source?

Using the spring-boot-admin 2.0.1-SNAPSHOT, instances registered using SimpleDiscoveryClient configuration

**Comment by joshiste** [comment]
see this commit: https://github.com/codecentric/spring-boot-admin/commit/fa35de89c3a4a40f14ef2dae0fec029d1600aca7

**Comment by GertVil** [comment]
I'm not sure if this would work in our case, with the SImpleDiscoveryClient, where there is no external DiscoveryClient and the configuration is in spring-boot-admin-server itself (we're only using the server not the client).  Hence we can't just add random metadata on every restart? I might be missing something though.

**Comment by joshiste** [comment]
You're right. The solution from the commit doesn't work when using a static configuration...

**Comment by GertVil** [comment]
Just making sure that I understand some of the inner workings, the information you see on the detail page that's information that spring-boot-admin-server retrieves "live" from the instance by passing the request through to the instance using an InstancesProxyController. While the information shown on the Application list or the Wallboard are cached inside spring-boot-admin-server (which gets collected by the triggering of domain events), so the problem we're facing here is that existing cache invalidation doesn't work with the static config?

**Comment by joshiste** [comment]
correct.

**Comment by GertVil** [comment]
That's what I've been trying to do, but I'm having issues finding a correct "entry-point" to accomplish this. I've tried some and it never seemed to reach the eventual `doUpdateInfo` in `InfoUpdater`

I also tried to replicate the behaviour of the regular StatusUpdateTrigger in my own InfoUpdateTrigger to make it have an update interval too but that doesn't seem to do anything either. 

``` java
package com.ownapp;

import java.time.Duration;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;

import org.reactivestreams.Publisher;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import de.codecentric.boot.admin.server.domain.events.InstanceEndpointsDetectedEvent;
import de.codecentric.boot.admin.server.domain.events.InstanceEvent;
import de.codecentric.boot.admin.server.domain.events.InstanceRegistrationUpdatedEvent;
import de.codecentric.boot.admin.server.domain.events.InstanceStatusChangedEvent;
import de.codecentric.boot.admin.server.domain.values.InstanceId;
import de.codecentric.boot.admin.server.services.InfoUpdateTrigger;
import de.codecentric.boot.admin.server.services.InfoUpdater;
import reactor.core.Disposable;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;
import reactor.retry.Retry;

public class OwnInfoUpdateTrigger extends InfoUpdateTrigger {
	private Duration updateInterval = Duration.ofSeconds(10);
	private Duration statusLifetime = Duration.ofSeconds(20);
	private static final Logger log = LoggerFactory.getLogger(OwnInfoUpdateTrigger.class);
	private Disposable intervalSubscription;
	private Map<InstanceId, Instant> lastQueried = new HashMap<>();
	private InfoUpdater infoUpdater;

	public OwnInfoUpdateTrigger(final InfoUpdater infoUpdater, final Publisher<InstanceEvent> publisher) {
		super(infoUpdater, publisher);
		this.infoUpdater = infoUpdater;
	}

	@Override
	public void start() {
		super.start();
		intervalSubscription = Flux.interval(updateInterval)
				.doOnSubscribe(subscription -> log.debug("Scheduled info update every {}", updateInterval))
				.log(log.getName(), Level.FINEST)
				.subscribeOn(Schedulers.newSingle("info-monitor"))
				.flatMap((i) -> this.updateInfoForAllInstances())
				.retryWhen(Retry.any()
						.retryMax(Integer.MAX_VALUE)
						.doOnRetry(ctx -> log.error("Resubscribing after uncaught error", ctx.exception())))
				.subscribe();
		log.debug("Started!");
	}

	@Override
	public void stop() {
		super.stop();
		if (intervalSubscription != null) {
			intervalSubscription.dispose();
		}
	}

	@Override
	protected Publisher<?> handle(Flux<InstanceEvent> publisher) {
		log.debug("handling publisher");
		return publisher.subscribeOn(Schedulers.newSingle("info-updater"))
				.filter(event -> event instanceof InstanceEndpointsDetectedEvent
						|| event instanceof InstanceStatusChangedEvent
						|| event instanceof InstanceRegistrationUpdatedEvent)
				.flatMap(this::updateInfo);
	}

	protected Mono<Void> updateInfo(InstanceEvent event) {
		return updateInfo(event.getInstance());
	}

	Mono<Void> updateInfoForAllInstances() {
		log.debug("Updating info for all instances");
		Instant expiryInstant = Instant.now()
				.minus(statusLifetime);
		return Flux.fromIterable(lastQueried.entrySet())
				.filter(e -> e.getValue()
						.isBefore(expiryInstant))
				.map(Map.Entry::getKey)
				.flatMap(this::updateInfo)
				.then();
	}

	Mono<Void> updateInfo(InstanceId instanceId) {
		log.debug("Updating info for instance");
		return infoUpdater.updateInfo(instanceId)
				.doFinally(s -> lastQueried.put(instanceId, Instant.now()));
	}

}

```

If you could point me in any general direction where I could launch an event or something to trigger an update. I've also tried getting the Instances from the Registry directly and using those to call the InfoUpdater but that didn't seem to work neither.

Thank you in advance!

**Comment by joshiste** [comment]
Without digging deeper into the code - imho this is the right direction and should work

**Comment by GertVil** [comment]
It did the trick after all, thanks, would you accept a merge request with a class like this (with a proper name) and enabled through a property to close this issue? Or were you thinking of fixing it in a better/other way?

**Comment by joshiste** [comment]
The problem is that not only the info gets stale but also the discovered endpoints, so it wouldn't fix all the problems....
