### ISSUE TITLE
Fail to update environment property/log level

### ISSUE THREAD

**Issue by vxavictor513** [codecentric/spring-boot-admin#787]
I got 403 Forbidden error when:
- Updating property in Environment Tab
- Refresh context in Environment Tab
- Updating log level in Logger tab

Error when updating property:
```
{"timestamp":"2018-06-17T00:33:51.331+0000","status":403,"error":"Forbidden","message":"Forbidden","path":"/instances/00ac87c0ed95/actuator/env"}
```

Error when refreshing context:
```
{"timestamp":"2018-06-17T01:22:48.163+0000","status":403,"error":"Forbidden","message":"Forbidden","path":"/instances/00ac87c0ed95/actuator/refresh"}
```

Error when updating log level:
```
{"timestamp":"2018-06-17T01:07:30.475+0000","status":403,"error":"Forbidden","message":"Forbidden","path":"/instances/00ac87c0ed95/actuator/loggers/com.demo.controller"}
```

I verified that `POST /env` and `/refresh` endpoints of my service are working as I am able to curl them and get a success.

Note that I have set `eureka.instance.metadata-map.management.context-path=/` at my client service side (Spring Cloud default value should be `/actuator`), not sure if it impacts anything.

Any idea how to get this working?

**Comment by joshiste** [comment]
I guess you have some error in your spring security config as a 403 is issued by spring security.

**Comment by vxavictor513** [comment]
@joshiste Thanks for the tips. I added configuration as suggested [here](https://docs.spring.io/spring-boot/docs/2.0.3.RELEASE/reference/html/production-ready-endpoints.html#production-ready-endpoints-security) and it worked!
