### ISSUE TITLE
Support for publishing audit events on kafka or jms

### ISSUE THREAD

**Issue by indraneelb1903** [codecentric/spring-boot-admin#788]
I was wondering if it would be possible to publish audit events on a jms or a kafka topic for analysis , using a user defined record . The user defined record would consist of the application’s name ( id maybe) and value would be the actual audit event . Further , this can be turned on only for certain applications.

**Comment by joshiste** [comment]
Imho exporting/publishing the audit-events is out-of-scope for Spring Boot Admin.
Exporting/publishing the events can be easily implemented in Spring Boot applications (e.g. by implementing `AuditListener`). It should not rely on Spring Boot Admin to be running and shoveling the audit events from the endpoints to a message queue.
