### ISSUE TITLE
Is there a spring boot server which is compatible with both 1 and 2 

### ISSUE THREAD

**Issue by murphp15** [codecentric/spring-boot-admin#794]
Love the product guys! excellent work! 
We want to start migrating our services to spring boot 2. 
So some of our services will be using the spring-boot-admin-starter-client version 1 and others will be using version 2. 
Will spring-boot-admin-starter-server version 2 support backwards compatibility?

**Comment by dickerpulli** [comment]
Yes, it is backwards compatible with little limitations.

See http://codecentric.github.io/spring-boot-admin/2.0.0/#monitoring-spring-boot-1.5.x
