### ISSUE TITLE
 couldn't determine local port. Please supply service-base-url.

### ISSUE THREAD

**Issue by magicsgxie** [codecentric/spring-boot-admin#796]
java.lang.IllegalStateException: couldn't determine local port. Please supply service-base-url. how can i solve it? I used spring-boot-admin in spring cloud Finchley.RELEASE version

**Comment by joshiste** [comment]
Either set `spring.boot.admin.client.instance.service-base-url`. Or just make `jar` instead of `war`.

**Comment by joshiste** [comment]
the property name was in my comment https://github.com/joshiste

**Comment by simoneggler** [comment]
my spring boot application is deployed on a kubernetes (openshift) cluster. i have no way of knowing the service-base url. 
when debugging the application startup, it becomes obvious that the application registration event ist fired before the @EventListener. the eventlistener would set the localServerPort needed by the getServiceBaseUrl method.

**Comment by Muzietto** [comment]
I reckon this issue has been closed in too much haste....

**Comment by joshiste** [comment]
For a k8s environment i suggest you just include the spring-cloud-kubernetes discovery in the SBA server and get rid of the sba clients.

**Comment by joshiste** [comment]
>yes, please reopen.

Before I reopen this issue, please update to a recent version of SBA and provide a sample project to reproduce the issue.

**Comment by BuddhimaN** [comment]
This can be happen when you are running your client in separate container. So client does not know its own port. So it should be configured. 

use the following properties (credits : @vishnumanohar7)

spring.boot.admin.client.url=http://localhost:8080/admin-server (admin server url)
spring.boot.admin.client.instance.serviceBaseUrl=http://localhost:8080 (application url)
