### ISSUE TITLE
Some UI authentication schemes are broken

### ISSUE THREAD

**Issue by deathdric** [codecentric/spring-boot-admin#799]
Hi,

Since version 2.0.1 of spring boot admin server ui, some authentication schemes are no longer working (we're using SSL client certificate).

After looking at the exception stack trace in the logs (can't copy it because of some restrictions in my workplace, however it is a failure to apply a Thymeleaf template because jackson fails to serialize one field of PreAuthenticatedAuthenticationToken) and the source code, I found the root cause of the issue.

On the de.codecentric.boot.admin.server.ui.web.UiController class, you try to serialize the current instance of java.security.Principal which, depending on the implementation, may not be serializable. Since this is only used to display the user name, a fix would be to create a simple DTO containing the principal name which is filled from the current principal, or just use the principal name as a string.

Regards,

Cedric

**Comment by joshiste** [comment]
> Since this is only used to display the user name, a fix would be to create a simple DTO containing the principal name which is filled from the current principal, or just use the principal name as a string.

yep. Are you willing to submit a PR? currently short on time.

**Comment by joshiste** [comment]
just fixed it. Until the next release you can override the UiController to work around this problem.

**Comment by deathdric** [comment]
Thanks a lot.
