### ISSUE TITLE
Can't open UI

### ISSUE THREAD

**Issue by theindra** [codecentric/spring-boot-admin#80]
Hi.

I tried to use spring-boot-admin. So i downloaded the sources and compiled the spring-boot-admin-sample project with intellij 14.

In the logs i can see that an application was registered, the rest api is working, but i can't open the ui. Acutally i don't know how to open it. Which url should i open to see UI? 

Could you please provide a documentation for this?

Thank you

**Comment by joshiste** [comment]
Did  the spring-boot-admin-server-ui project compile (it needs node.js and npm)?
Either you make it compile or you stick to the artifacts availibe in maven central. For the latter you must not use the SNAPSHOT-versions. And choose version 1.2.1.
The UI is served on the root url.

**Comment by theindra** [comment]
I created a fresh empty gradle project and added the dependencies via gradle. 
Know i want it to integrate in my project. How can i change the url of the UI to /backend/admin ?

**Comment by joshiste** [comment]
I advise you to not include the admin into the application yo-adminu want to monitor...

In case you want to change the url you can use spring boots `server.context-path`.
But this changes the "root" context-path for the whole servlet container.

The UI is a bunch of static files in `spring-boot-admin-server-ui.jar/META-INF/resources` (compliant as of servlet 3.0 spec). So if you want to serve the files from elsewhere you need to customize the way spring mvc is servering these resources. 
If you  move the UI from a different location, you also have to move the REST-interface used by UI and clients for registering

**Comment by theindra** [comment]
Ok thank you.

Maybe you can add this information to the readme-file?

**Comment by cforce** [comment]
It would be usefull to configure the path where the service's (ui/REST-interface) is published
