### ISSUE TITLE
Using Eureka dicovery, Eureka itself is not appearing in SBA

### ISSUE THREAD

**Issue by illingtonFlex** [codecentric/spring-boot-admin#801]
Using SBA 2.0.1 and Finchley.RELEASE with replicated Eureka.

I see Eureka listed in the Eureka console, and in the /eureka/apps endpoint, but it does not appear in SBA. Everything else in Eureka appears in SBA. Is this the expected behavior?

**Comment by joshiste** [comment]
by default SBA does not filter instances from discovery - so I guess you should look at the DiscoveryClient implementation
