### ISSUE TITLE
Spring boot admin 1.5 How to monitor spring boot 2.0?

### ISSUE THREAD

**Issue by ricefish888** [codecentric/spring-boot-admin#802]
Spring boot admin 1.5 How to monitor spring boot 2.0?
Spring boot admin 2.0 how to monitor spring boot 1.5?

Need two solutions.

Thank you！

**Comment by joshiste** [comment]
> Spring boot admin 1.5 How to monitor spring boot 2.0?

you can't

>Spring boot admin 2.0 how to monitor spring boot 1.5?

see http://codecentric.github.io/spring-boot-admin/current/#monitoring-spring-boot-1.5.x
