### ISSUE TITLE
Failed to register application as Application 401 null

### ISSUE THREAD

**Issue by vir2610** [codecentric/spring-boot-admin#803]
Question :

I have been trying to register my spring boot application (client) to the SBA server. When I start the client application, it gives error message as below:

`[2018-06-29T13:26:30,069] WARN  de.codecentric.boot.admin.client.registration.ApplicationRegistrator - Failed to register application as Application(name=spring-boot-application, managementUrl=http://hostmachine:9062/boot/actuator, healthUrl=http://hostmachine:9062/boot/actuator/health, serviceUrl=http://hostmachine:9062/boot) at spring-boot-admin ([http://host.com:6789/admin/instances]): 401 null. Further attempts are logged on DEBUG level`

Following is my SBA server application properties:

```
spring.boot.admin.context-path=/admin
spring.boot.admin.ui.title=test admin
server.address=host.com
server.port=6789
spring.security.user.name=user
spring.security.user.password=password
```
and following is my client application properties
```
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
spring.boot.admin.client.url=http://host.com:6789/admin
spring.boot.admin.username=user
spring.boot.admin.password=password
```

What am I doing wrong here ?

**Comment by joshiste** [comment]
it is `spring.boot.admin.client.username` and `spring.boot.admin.client.password`

**Comment by Beifangyouxia** [comment]
[gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application(name=MySpringBootAdminClient, managementUrl=http://Admin-PC:10003/actuator, healthUrl=http://Admin-PC:10003/actuator/health, serviceUrl=http://Admin-PC:10003/) at spring-boot-admin ([http://localhost:10001/instances]): 401 Unauthorized. Further attempts are logged on DEBUG level

**Comment by Beifangyouxia** [comment]
I am also the problem above, how to solve it?
Very anxious！

**Comment by cemdrman** [comment]
I'm getting same error. I checked my configurations many times but I didn't fix it.

**Comment by joshiste** [comment]
@cemdrman did you check your CSRF config?

**Comment by yaoxipenga** [comment]
how to solve this questions?
