### ISSUE TITLE
Add new `spring.boot.admin.client.instance.service-path`

### ISSUE THREAD

**Issue by getalphacode** [codecentric/spring-boot-admin#804]
Hi guys.
Thanks for this awesome tool. I've many microservices which are all being registered with spring boot admin. However, I've a couple of services which have set their context path using `ServletRegisterationBean` programmatically. So their endpoints are `localhost:8080/app/health` instead of `localhost:8080/health`. 
In services which have context-path set via properties, everything is working fine. But I'm not able to get spring boot admin client to use `/app` as context path of health endpoint. I don't want to provide absolute url as I saw in some property. 

Is there any property via which I can set the context-path in spring boot admin client?

**Comment by joshiste** [comment]
Currently not, but you can subclass out `DefaultApplicationFactory` and add a modified version as bean.

**Comment by joshiste** [comment]
But maybe it would be good to have one. We could add a `spring.boot.admin.client.instance.service-path` (default: `/`) to make things configurable. Would you like to submit a PR?

**Comment by getalphacode** [comment]
sure, would love to.

**Comment by dkirrane** [comment]
@joshiste I assume this is same issue?
https://stackoverflow.com/questions/54234816/failed-to-load-resource-when-setting-server-servlet-context-path/

How can I subclass `DefaultApplicationFactory`
