### ISSUE TITLE
Support for calling admin-server endpoints securely from admin-ui

### ISSUE THREAD

**Issue by Sarvesh-D** [codecentric/spring-boot-admin#819]
It would be good in terms of security to call admin-server endpoints securely from admin-ui. In terms of security, admin server can be called securely by registering clients using `ApplicationRegistrator` which uses `Oauth2RestTemplate`. However, there seems to be no configuration (atleast i could not find one) for admin-ui to securely calling admin-server. Can we have some configuration to make UI call admin-server securely?
Currently i have to exclude few apis from security as below:
```
   /**
     * Ignoring all self-APIs/SBA server APIs which are called by SBA-UI internally.
     */
    @Override
    public void configure(final WebSecurity web) throws Exception {
        web.ignoring()
           .antMatchers(HttpMethod.OPTIONS)
           .antMatchers(HttpMethod.GET, "/**/applications", "/**/applications/*", "/**/notifications/*", "/**/instances/**");
    }
```

**Comment by joshiste** [comment]
> Can we have some configuration to make UI call admin-server securely?

Could you describe what exactly you are missing? 
The ui just does ordinary http calls which usually use some kind of session token in the cookies. Imho there is nothing to do here.
Referring to https://github.com/codecentric/spring-boot-admin/issues/817#issuecomment-403501693 you should first figure out what your internal security library is missing there before opening a very vague and unprecise issue.

**Comment by Sarvesh-D** [comment]
Sorry for not being clear with the description. I got the security thing figured out finally. As you see in the description, i had to disable security on some endpoints. But now security on all endpoints is enabled and i am able to access application UI perfectly. Below was the change (i had to add a filter) i made to the security config:
`http.addFilterAfter(new RequestContextFilter(), CsrfFilter.class)`
I am not expert in security or reactive WebClient, but my understanding is `WebClient` runs and makes request from a separate thread due to which i was getting Spring's *No thread-bound request found* exception (which was causing authorization to fail). Please correct me if i am wrong. I will close the issue anyways.
