### ISSUE TITLE
TimeGauge Metrics (e.g. process.uptime) can be wrong depending on metrics registry

### ISSUE THREAD

**Issue by deathdric** [codecentric/spring-boot-admin#829]
Hi,

- Spring Boot Version : 2.0.3-RELEASE
- Micrometer version : 1.0.5
- Spring Boot Admin UI Version : 2.0.1

Spring Boot Admin UI is currently relying on the result of /actuator/metrics/process.uptime in order to display the base uptime of the process details tab and AFAIK assumes that the uptime is in seconds.

However depending on the micrometer registry used the value exposed in the metrics endpoints can sometimes be in milliseconds (for example if micrometer-registry-jmx is used the process uptime showed in actuator is in milliseconds), as a result the displayed uptime may be off by a 1000-factor.

Other displayed values such as the Garbage Collection times suffers the same issue.

Unfortunately I don't see a reliable way to automatically detect the unit used client-side (getBaseTimeUnit() is protected in MeterRegistry). :(

Regards,

Cedric

**Comment by joshiste** [comment]
I guess we need to raise an issue in Spring Boot so that either the time unit is fixed or given for the metrics endpoint...

**Comment by joshiste** [comment]
This just fixes the date conversion. We could do more awesome using the base unit, but time is lacking.
Please note that the fix will only work for monitored applications using the spring boot 2.0.4 release.
