### ISSUE TITLE
SBA 2.0.1 logviewer does not display hateaos links correctly

### ISSUE THREAD

**Issue by tiernanscully** [codecentric/spring-boot-admin#831]
Hateoas links captured in logs are malformed when viewing them in the SBA logviewer.

**Actual log contents:**
```16-07-2018 22:12:19.688  INFO 58306 --- [http-nio-8902-exec-4] com.example.dummy.DummyController        : Dummy object toString:    DummyObject(name=John Smith, age=44)
16-07-2018 22:12:19.689  INFO 58306 --- [http-nio-8902-exec-4] com.example.dummy.DummyController        : Dummy object  jackson:    {"name":"John Smith","age":44,"links":[{"rel":"random-link1","href":"https://localhost:8000/api/123/query?action=do_something&age=21","hreflang":null,"media":null,"title":null,"type":null,"deprecation":null},{"rel":"random-link2","href":"https://localhost:8000/api/123/query?action=do_something&age=21&name=John","hreflang":null,"media":null,"title":null,"type":null,"deprecation":null},{"rel":"random-link3","href":"https://localhost:8000/api/query?action=do_something&name=John","hreflang":null,"media":null,"title":null,"type":null,"deprecation":null}]}
```
**Logviewer display**
<img width="1368" alt="sba_logviewer" src="https://user-images.githubusercontent.com/14013609/42815636-dc9db3ee-89bf-11e8-9c8e-fc3748dcb0f2.png">

**Comment by joshiste** [comment]
I've raised https://github.com/SoapBox/linkifyjs/issues/239 for the npm module used to to the hyperlink detection.

**Comment by altfatterz** [comment]
SOAP messages in the logs through Spring Boot Admin are also malformed
 
<img width="1577" alt="screen shot 2018-07-25 at 11 54 30" src="https://user-images.githubusercontent.com/1025546/43194002-ad042a30-9001-11e8-9e4a-0cda6d99a6d9.png">
