### ISSUE TITLE
java.lang.IllegalArgumentException: 'healthUrl' is not valid: /actuator/health

### ISSUE THREAD

**Issue by zurhan** [codecentric/spring-boot-admin#834]
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS
eureka.instance.health-check-url=/actuator/health

java.lang.IllegalArgumentException: 'healthUrl' is not valid: /actuator/health

**Comment by joshiste** [comment]
you need to specify an absolute URL
