### ISSUE TITLE
What's the status about the ui-hystrix and ui-turbine?

### ISSUE THREAD

**Issue by weiwunb** [codecentric/spring-boot-admin#836]
Hi team,
I found these two components(spring-boot-admin-server-ui-hystrix, spring-boot-admin-server-ui-turbine) both tagged at v1.5.7 and SBM V2.0 note that **Removed Hystrix-Dashboard integration (subject to change)**, what's the status about the two components? Will SBM integrate hystrix/turbine in future? Thank you.

**Comment by joshiste** [comment]
duplicates https://github.com/codecentric/spring-boot-admin/issues/657#issuecomment-396177252
