### ISSUE TITLE
about spring-boot-admin master and slave

### ISSUE THREAD

**Issue by dchack** [codecentric/spring-boot-admin#837]
hi, I want to know is there any master and slave solution.
because I can't found any documents describe about it.

**Comment by joshiste** [comment]
What's the purpose?

**Comment by dchack** [comment]
@joshiste as you konw, I want use spring-boot-admin to monitor our applications.If i use on prod environment, I want it more available,in case one spring-boot-admin down.I will can't know all applications's state if I use alert application down state. so I think it's dangerous.  
in addition, in my team, there is no single-point application on prod environment.  
How do you think about this, hope your reply.

**Comment by joshiste** [comment]
Currently you have two choices:
1) cluster two Instances by using Hazelcast (see http://codecentric.github.io/spring-boot-admin/current/#clustering-support)
2a) If you use SBA client: Register your monitored apps at multiple instances (`spring.boot.admin.client.url` takes an array with the urls and `spring.boot.admin.client.register-once=false`)
2b) If you use Spring Cloud Disocvery: Just spin up multiple SBA instances
