### ISSUE TITLE
SBA 2.0.1 logfile response status 206 

### ISSUE THREAD

**Issue by shixueshang** [codecentric/spring-boot-admin#840]
I have set logging.file correct,  but display  "Fetching logfile failed".

**Comment by joshiste** [comment]
please provide a project to reproduce the problem

**Comment by shixueshang** [comment]
I‘m sorry about that I can't offer a public project for now.
I try it on another project , it works.  They have the same configuration， but this project still report errors.   
the logfile interface response data : {"description":"file [E:\\usr\\local\\web\\logs\\support\\support.log]","file":"\\usr\\local\\web\\logs\\support\\support.log","filename":"support.log","inputStream":{},"open":false,"outputStream":{},"path":"/usr/local/web/logs/support/support.log","readable":true,"uRI":"file:/E:/usr/local/web/logs/support/support.log","uRL":"file:/E:/usr/local/web/logs/support/support.log","writable":true}

**Comment by joshiste** [comment]
A problem that I can't reproduce cannot be fixed....

**Comment by shixueshang** [comment]
I know where the problem is. The HttpMessageConverters code is not set correctly in the project .
