### ISSUE TITLE
Invalid Metric Duration on the Metrics Tab

### ISSUE THREAD

**Issue by tiarebalbi** [codecentric/spring-boot-admin#842]
Hi guys, I just noticed that on the Metrics tab the duration is not right.

Based on the fixed delay that I added to my code I should have only **2.03 Seconds** but as you can see the dashboard is showing **0d 0h 33m 54s**. The problem seems to be with the decimals **(2034.280415)**.

**Versions:**
* **Spring Boot:** 2.0.1
* **Micrometer:** 1.0.5
* **Spring Boot Admin:** 2.0.1

<img width="1410" alt="screen shot 2018-07-21 at 10 01 50 pm" src="https://user-images.githubusercontent.com/103419/43040054-3671d790-8d32-11e8-9e45-56359099cf12.png">

<img width="302" alt="screen shot 2018-07-21 at 10 01 57 pm" src="https://user-images.githubusercontent.com/103419/43040080-ca9d6f1a-8d32-11e8-9cec-b36daca342c6.png">

```
{
   name:"time.sample",
   measurements:[
      {
         statistic:"COUNT",
         value:1
      },
      {
         statistic:"TOTAL_TIME",
         value:2034.415644
      },
      {
         statistic:"MAX",
         value:2034.415644
      }
   ],
   availableTags:[
      {
         tag:"method",
         values:[
            "sample"
         ]
      },
      {
         tag:"application",
         values:[
            "web-service"
         ]
      },
      {
         tag:"class",
         values:[
            "com.tiarebalbi.cloud.web.controller.SampleController"
         ]
      }
   ]
}
```

**Comment by tiarebalbi** [comment]
Just noticed, on the file: 
https://github.com/codecentric/spring-boot-admin/blob/75a960a7e631def8d5e0536a2677b4a20ca152d7/spring-boot-admin-server-ui/src/main/frontend/views/instances/metrics/metric.vue#L71

Why the time is being multiplied by 1000? Checking the documentation seems that the default unit to the duration method is milliseconds, the same returned from the API.

https://momentjs.com/docs/#/durations/creating/

**Comment by joshiste** [comment]
It's due to the same reason as in https://github.com/codecentric/spring-boot-admin/issues/829
