### ISSUE TITLE
IE Menu Issue

### ISSUE THREAD

**Issue by MrBogue** [codecentric/spring-boot-admin#851]
Hello,
We identified a bug in the new version of spring boot admin server 2.0.1 for the IE browser. 
The menus at the top are not working. 
No issues found with Chrome. Can you please find a solution?

Kind Regards,
MrBogue

**Comment by joshiste** [comment]
For IE 11 I won't do any fixes, but feel free to send a PR.

**Comment by goyaldevender** [comment]
Hello, 

Kindly provide support for I.E.

In my organisation, we are mandated to use Internet explorer 11.

Warm Regards,
Devender
