### ISSUE TITLE
Add tags/labels to instances to allow for filtering and grouping

### ISSUE THREAD

**Issue by asibross** [codecentric/spring-boot-admin#855]
Hey,

I am thinking it would be great to be able to add tags/labels to instances and have them visible in UI, similar to how Github/StackOverflow have these notion.

In my case I have multiple applications running in different AWS regions and accounts, so adding this information would greatly improve usability.

I am thinking of adding it in [Instance](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server/src/main/java/de/codecentric/boot/admin/server/domain/entities/Instance.java) and display it in [header.vue](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/shell/header.vue#L23).

I am willing to start a PR if this is acceptable.

**Comment by joshiste** [comment]
@asibross sounds like a nice addition. The information should be taken from the metadata so that the SBA client and SC discovery users can benefit from this enhancement.

**Comment by asibross** [comment]
Metadata may include entries that are not necessarily tags.
We need a way to distinguish between metadata entries that are tags and other entries, I see two options for this:
1. Key convention, i.e. **tag:environment -> test** 
2. A property that a consumer can set to define the tag keys, i.e. 
**spring.boot.admin.metatdata-tags=environment,region**

**Comment by joshiste** [comment]
how about `spring.boot.admin.metatdata.tags.*``
e.g. `spring.boot.admin.metatdata.tags.environment=test`

**Comment by asibross** [comment]
Metadata is a flat string -> string map so adding another layer requires changes in multiple components.
Regardless, the configuration you suggested only relates to how SBA client will define the tags not how it is defined for other registration options.
To keep things simple I sent a PR which if metatdata contains **tags** key, then based on the metadata values tags will be added in the instance header.

This is how it looks:
![image](https://user-images.githubusercontent.com/11426802/43554511-aebe18ec-95a9-11e8-8572-dfd08970310e.png)

**Comment by edeandrea** [comment]
Sorry I'm a bit late to this ticket - but another thing that would stand out would be to automatically add the `spring.profiles.active` tags.
