### ISSUE TITLE
Multiple instance not getting registered using discovery

### ISSUE THREAD

**Issue by Sarvesh-D** [codecentric/spring-boot-admin#856]
Hi, i am using spring boot admin's discovery feature to auto-register instances from Eureka. However,  when an application has multiple instances on Eureka, Spring Boot Admin is not able to register both the instances, it is showing only single instance.
When testing on local machine, i have to deploy same application on different ports. And doing so registers both the instances to Eureka and thus to Spring Boot Admin.
But, on PCF, since the hostname is same for both instances, SBA is not able to register both instances ( i am guessing this).
I have overrode the `de.codecentric.boot.admin.server.cloud.discovery.DefaultServiceInstanceConverter.getServiceUrl(ServiceInstance)` as below to add the context-path of instances:
```
   @Override
    protected URI getServiceUrl(final ServiceInstance instance) {
        return UriComponentsBuilder.fromUri(super.getServiceUrl(instance))
                                   .path(getContextPath(instance))
                                   .build()
                                   .toUri();
    }
```
Do i need to configure something additional for PCF?

**Comment by joshiste** [comment]
Currently the docs for this is missing for Discovery on CF but in short: You need to add the and `applicationId` to the metadata `instanceId` (like https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-client/src/main/java/de/codecentric/boot/admin/client/registration/metadata/CloudFoundryMetadataContributor.java) does. 
Everything else should work ootb (except when sba server itself runs outside CF - then you need to add the CloudFoundryHttpHeaderProvider and CloudFoundryInstanceIdGenerator as beans)

**Comment by joshiste** [comment]
@Sarvesh-D Would you volunteer for a PR on our documentation for this?

**Comment by joshiste** [comment]
@Sarvesh-D at best a new paragrapgh on cloudfoundry in https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-docs/src/main/asciidoc/server-discovery.adoc
