### ISSUE TITLE
Best practice on connecting multiple instances of an application (running on K8S) to Spring Boot Admin

### ISSUE THREAD

**Issue by jochenhebbrecht** [codecentric/spring-boot-admin#858]
Hi,

First of all, not really a bug or feature request - more a request in search of some best practices :-).

I currently have Spring Boot Admin 2.0.2 running on an ECS cluster in AWS. Running really fine, happy with this service! Great work!

I have a Spring Boot 2.X application running on a K8S cluster. That application is scalable and we have 2 pods running in the cluster (but that number can increase)

I enabled the Spring Boot Admin client and both of them are now linked to the SBA server. I also see the 2 instances popping up, which is very nice!
However, I'm for example not able to connect for both of the instances from within the SBA server to the individual pods because the pods are protected from outside (remember, the SBA server is running on ECS, not on the K8S cluster). On the outside of the K8S cluster, there's a loadbalancer (AWS ELB) and I can access the /actuator endpoints using the loadbalancer URL.

My idea was to reconfigure the URL's (spring.boot.admin.client.instance.health-url, spring.boot.admin.client.instance.management-url, spring.boot.admin.client.instance.service-url) to use the hostname of the loadbalancer. The downside of this situation is that I would only monitor 1 of the pods of course, but at least it would turn my application 'green' instead of 'grey'.

I was curious how other people handle this situation correctly?

**Comment by joshiste** [comment]
Possible solutions:
1) Pull the SBA into the K8s cluster
2) Do similar solution like it's implemented on CloudFoundry: Add a special header to the loadbalancer request which instruct the LB to route the request to a specific instance. SBA would need to take the header value into account for identifying individual instances and add the header to the requests.
3) Add special routes to your ELB which point to the individual instances

Monitoring just a single instance is imho a rather bad solution as you never know which instance you are looking at and e.g. setting log levels will for a specific instance becomes a roulette...

**Comment by jochenhebbrecht** [comment]
Thanks @joshiste! Very clear summary. We will implement 1 of the above solutions.

**Comment by magnusheino** [comment]
...or just configure spring.boot.admin.client.instance.prefer-ip: true
