### ISSUE TITLE
[http trace] the http trace view will cause browser memory raise

### ISSUE THREAD

**Issue by hirohe** [codecentric/spring-boot-admin#861]
is about http trace problem, in `/instances/219a2939eb94/httptrace` view, the browser memory usage will raise and page dead in seconds.

chartData is too big...
![_20180802124313](https://user-images.githubusercontent.com/14357567/43562846-aa19ebce-9651-11e8-8261-108f40e1be45.png)

so i have make some log output on [this loop](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/httptrace/traces-chart.vue#L81) from `traces-chart.vue`,
```js
let i = 0;
for (let time = Math.floor(oldest.valueOf() / interval) * interval; time < now; time += interval) {
          i++;
          console.log('loop', i);
          console.log('loop --- time', time);
          console.log('loop --- now', now);
       //...
}
```
i found it is because the timestamp unit of `now` and `time` is different
![_20180802124531](https://user-images.githubusercontent.com/14357567/43562949-40159eca-9652-11e8-875e-a1fd510150a8.png)
so the loop will run many times till the page dead.

the `time` is come from server's httptrace response, something like this..., timestamp unit is second
![image](https://user-images.githubusercontent.com/14357567/43563200-8881dd26-9653-11e8-8ef6-9c94327331a4.png)

**Comment by joshiste** [comment]
I don't have this problem:
![image](https://user-images.githubusercontent.com/8779225/43565312-ab96b512-962a-11e8-972f-f5bfb6aacaa3.png)

Maybe it's locale/platform/browser specific. Which browser on what platform and local you're running on?

**Comment by joshiste** [comment]
Ok i guess it's related to the timestamp from the `httptrace` endpoint. Could you please post a excerpt from your `httptrace` output showing the timestamp?

**Comment by hirohe** [comment]
platform: Windows 10
browser: Chrome 67
locale: zh_CN

so it is something make the server's httptrace response return timestamp in seconds unit?

**Comment by hirohe** [comment]
additionlly

i had set `spring.jackson.serialization.write-dates-as-timestamps: true` in application.yaml

**Comment by joshiste** [comment]
> so it is something make the server's httptrace response return timestamp in seconds unit?

I guess so. Did you check the json response?

**Comment by hirohe** [comment]
i try debug step by step..
find out `httptrace.timestamp` is serialized in `com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase#serialize`
```java
if (useTimestamp(provider)) { // pass when serialization.write-dates-as-timestamps is true
    if (useNanoseconds(provider)) { 
        // pass by default,
        // have to set serialization.write-date-timestamps-as-nanoseconds to false,
        // to prevent timestamp format in seconds unit
        generator.writeNumber(DecimalUtils.toBigDecimal(
                getEpochSeconds.applyAsLong(value), getNanoseconds.applyAsInt(value)
        ));
        return;
    }
    generator.writeNumber(getEpochMillis.applyAsLong(value));
    return;
}
```

- without any `spring.jackson.serialization` config. `httptrace.timestamp` is ISO format
![image](https://user-images.githubusercontent.com/14357567/43573085-8387428c-9673-11e8-89e4-3f7a95f1d3d9.png)

- with `spring.jackson.serialization.write-dates-as-timestamps: true`, `httptrace timestamp` is timestamp of second unit
![image](https://user-images.githubusercontent.com/14357567/43572857-0db287ba-9673-11e8-9246-1350bb6fbb95.png)

- with
`spring.jackson.serialization.write-dates-as-timestamps: true`
and
`spring.jackson.serialization.write-date-timestamps-as-nanoseconds`
`httptrace timestamp` is timestamp of miliisecond unit
![image](https://user-images.githubusercontent.com/14357567/43572805-f3b4951a-9672-11e8-919d-1ce156bc00f5.png)

three different format will happen🤔

**Comment by hirohe** [comment]
maybe before [here](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/views/instances/httptrace/index.vue#L101) can do some format checking

**Comment by joshiste** [comment]
Are you using Boot 1.5.x?

**Comment by joshiste** [comment]
There is an issue in Spring Boot for having stable actuator json mappings. There isn't not much we can do about this. https://github.com/spring-projects/spring-boot/issues/12951

**Comment by GaetanWi** [comment]
Adding a bit of informations to @hirohe explanation about spring serialization properties. 

From our app, we had a custom `JacksonBuilder` to avoid NULL values.

```
@SpringBootApplication
public class JavaConnecteurESApplication {

	public static void main(String[] args) {
		SpringApplication.run(JavaConnecteurESApplication.class, args);
	}
	
	@Bean
	public Jackson2ObjectMapperBuilder objectMapperBuilder() {
	    Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder();
	    builder.serializationInclusion(JsonInclude.Include.NON_NULL);
            // This line below is the magic one for me. Obviously, if need to switch properties to true, use featuresToEnable 
	    builder.featuresToDisable(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS);
	    return builder;
	}
}
```

**Comment by dazhi007** [comment]
Thank you, I have encountered such a problem..
