### ISSUE TITLE
Authorization headers not sent instances page resulting in 401

### ISSUE THREAD

**Issue by RemiBou** [codecentric/spring-boot-admin#863]
Hi,

On the instances page I got the error "Fetching metrics index failed." :

- SBA receives the credential from the service as the part "Metadata" is filled
- The Basic Authorization header is not sent as I can see in chrome debugging tools
- On the client "management.endpoints.web.cors.allowed-headers" contains "Authorization"
- If I get the query as cUrl in chrome devtools and append the credentials with "-u" the request returns 200
- Here is the curl from chrome dev tools
`curl 'https://XXX.com/actuator/metrics' -H 'Pragma: no-cache' -H 'Origin: https://springbootadmin.XXX.com' -H 'X-XSRF-TOKEN: d6deb64f-c5f7-4fc0-b43f-561d4c7fa4f8' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,fr;q=0.8,und;q=0.7' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36' -H 'Accept: application/vnd.spring-boot.actuator.v2+json,application/vnd.spring-boot.actuator.v1+json,application/json' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Referer: https://springbootadmin.XXX.com/' --compressed `

Here is the response headers

> HTTP/1.1 401
> Server: nginx/1.6.2
> Date: Thu, 02 Aug 2018 12:01:52 GMT
> Content-Length: 0
> Connection: keep-alive
> X-Content-Type-Options: nosniff
> X-XSS-Protection: 1; mode=block
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> Pragma: no-cache
> Expires: 0
> X-Frame-Options: DENY

**Comment by joshiste** [comment]
The authorization info from the metadata is not passed to the UI - it should never leave the backend server except to the instance which submitted the metadata. 

The server enriches the request headers made to the individual instances. So it's no surprise that the requests from the chrome browser doesn't contain the `Authorization` header.

For security between SBA-UI and SBA-Server you should use some session based security...

**Comment by RemiBou** [comment]
I think the bug is there is a redirect. First my browser tries to call "https://springbootadmin.XXX.com/instances/cbe06877b98c/actuator/info" in response I get a 301 to "https://XXX.com/actuator/info". How could this happen ? If I ssh onto the  spring boot admin server and curl the actuator/info of the server I got a 200 not a 301

**Comment by RemiBou** [comment]
@joshiste  I found the bug. if I put a serviceUrl with https, the protocol is ignored because of how the port is computed on DefaultServiceInstanceConverter line 96. URI.getPort doesn't return 443 if we pass a https url without port specified, I think as a workaround I can force the port on the url or use the managementPort configuration. If you can re-open the bug, I will send a PR handling when getPort returns "-1".

**Comment by joshiste** [comment]
You can do a PR right away - there is no need to have an open issue. I'll use the PR for the changlog then.

**Comment by RemiBou** [comment]
@joshiste my bad ! the called url was good but my app actuator/endpoint contained http url because my app is behing a nginx reverse proxy, I had to use nginx subfilter module for fixing the outgoing urls. Thanks for your hep and you amazing work !
