### ISSUE TITLE
Custom views on classpath are not loaded automatically

### ISSUE THREAD

**Issue by shakuzen** [codecentric/spring-boot-admin#867]
Using Spring Boot Admin 2.0.2 and following the [instructions in the documentation](http://codecentric.github.io/spring-boot-admin/current/#customizing-custom-views), I tried to make my own custom view. It works well in "development" mode where the Server is configured to look at the filesystem directly.

However, the custom views will not be detected/loaded when the views are on the classpath instead. This can be tested by adding the sample dependency to a working Spring Boot Admin server:

```xml
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-sample-custom-ui</artifactId>
	<version>2.0.2</version>
</dependency>
```

Debugging the `UiExtensionsScanner`, the following is only returning `classpath:/META-INF/spring-boot-admin-server-ui/extensions/` and not the folders and subsequent files nested within.
https://github.com/codecentric/spring-boot-admin/blob/75a960a7e631def8d5e0536a2677b4a20ca152d7/spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/extensions/UiExtensionsScanner.java#L37

If `spring.boot.admin.ui.extension-resource-locations` is explicitly set to `classpath:/META-INF/spring-boot-admin-server-ui/extensions/custom/`, then the custom view is loaded as expected.

**Comment by joshiste** [comment]
It works for me using `mvn spring-boot:run` (without any further location) but not running as fat-jar...

**Comment by joshiste** [comment]
Sounds weird, but: 
If you place the custom-ui dependency as first dependency in your `pom.xml` it will be placed in the fat jar before the spring-boot-admin-server-ui and then it works as expected.
I guess the pattern needs to be `classpath*:..` instead of `classpath:..`
