### ISSUE TITLE
Securing Eureka with user/password causes recurring login popup

### ISSUE THREAD

**Issue by rubesMN** [codecentric/spring-boot-admin#87]
If I secure Eureka with a user/password as so

application.yml in Eureka Server:

     security:
       user:
         password: ${eureka.password} # Don't use a default password in a real app

And if the spring-boot-admin bootstrap.yml contains:

    cloud:
      config:
        uri: http://localhost:8888/diagnostics/admin/config
        failFast: true

    spring.boot.admin.discovery.management.context-path: /diagnostics/admin

    eureka:
      instance:
        leaseRenewalIntervalInSeconds: 10
        statusPageUrlPath: /diagnostics/admin/info
        healthCheckUrlPath: /diagnostics/admin/health
        metadataMap:
          password: password
      client:
        enabled: true
        serviceUrl:
          defaultZone: http://user:password@localhost:8761/eureka/

Then when I bring up spring-boot-admin ui, the following prompt for user/password happens over and over.  When it happens, log is `Finding route for path: /api/applications/xxxx/yyy`  where yyy are /info|configprops/ and xxx are some kind of hash.

<img width="1382" alt="screen shot 2015-07-23 at 10 03 04 am" src="https://cloud.githubusercontent.com/assets/633015/8853973/07b0e4f0-3123-11e5-96e7-07bb4831af95.png">

**Comment by joshiste** [comment]
The boot admin server hat a zuul proxy integrated to forward the requests from the angular UI to the registered client-applications' endpoints. I would guess the 401-Response you see is from you client and was proxied by the boot admin.
 
currently there is no special authentication handling in the UI and the server forwards the requests/responses as they are...
So at the moment only basic auth for the client management-endpoints using all the same user/password works properly...

**Comment by joshiste** [comment]
So do you have any suggestions how things should work properly?

**Comment by joshiste** [comment]
By now I wrote some examples on how to solve authentication. Have a look at https://github.com/joshiste/spring-boot-admin-samples
So I'm closing this issue.

**Comment by ravighanate** [comment]
Is there any update on this issue? Using basic-auth on all client endpoints with same user/name password still doesn't work and still keeps prompting for login. Is there any better way to handle in 1.4.X?

**Comment by joshiste** [comment]
@ravighanate did you set `zuul.sensitiveHeaders=` ? (empty). So the auth header gets passed by zuul?

There will be an improvement for Boot 1.5.x to work with proteceted endpoints.
