### ISSUE TITLE
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instancesProxyController'

### ISSUE THREAD

**Issue by bhagyaperera123** [codecentric/spring-boot-admin#873]
my configuration 100% working with another project. but my current project have ui created by angular.

**Comment by joshiste** [comment]
Without a complete stacktrace or a sample project to reproduce hard to tell what the reason is.
One of the worst issue descriptions ever.

**Comment by bhagyaperera123** [comment]
2018-Aug-08 10:11:20.314 INFO  [main] o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-Aug-08 10:11:20.315 INFO  [main] o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-Aug-08 10:11:20.327 DEBUG [main] o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Looking for exception mappings: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2898ac89: startup date [Wed Aug 08 10:11:16 JST 2018]; root of context hierarchy
2018-Aug-08 10:11:20.388 WARN  [main] o.s.b.a.t.ThymeleafAutoConfiguration$DefaultTemplateResolverConfiguration - Cannot find template location: classpath:/templates/ (please add some templates or check your Thymeleaf configuration)
2018-Aug-08 10:11:20.424 INFO  [main] o.s.b.a.w.s.WelcomePageHandlerMapping - Adding welcome page: class path resource [static/index.html]
2018-Aug-08 10:11:20.440 WARN  [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instancesProxyController' defined in class path resource [de/codecentric/boot/admin/server/config/AdminServerWebConfiguration$ServletRestApiConfirguation.class]: Unsatisfied dependency expressed through method 'instancesProxyController' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceRegistry' defined in class path resource [de/codecentric/boot/admin/server/config/AdminServerAutoConfiguration.class]: Unsatisfied dependency expressed through method 'instanceRegistry' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'de.codecentric.boot.admin.server.domain.entities.InstanceRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2018-Aug-08 10:11:20.441 INFO  [main] o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'webMvcAsyncTaskExecutor'
2018-Aug-08 10:11:20.441 INFO  [main] o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'poolScheduler'
2018-Aug-08 10:11:20.441 INFO  [main] o.s.o.j.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2018-Aug-08 10:11:20.442 INFO  [main] o.h.t.s.i.SchemaDropperImpl$DelayedDropActionImpl - HHH000477: Starting delayed drop of schema as part of SessionFactory shut-down'
2018-Aug-08 10:11:20.447 INFO  [main] c.z.h.HikariDataSource - HikariPool-1 - Shutdown initiated...
2018-Aug-08 10:11:20.449 INFO  [main] c.z.h.HikariDataSource - HikariPool-1 - Shutdown completed.
2018-Aug-08 10:11:20.451 INFO  [main] o.a.c.c.StandardService - Stopping service [Tomcat]

**Comment by joshiste** [comment]
Could you please provide a sample project to reproduce the issue as the log output doesn't give a hint about the underground cause.

**Comment by bhagyaperera123** [comment]
sorry i had 2 bean with same name
