### ISSUE TITLE
how update the Spring-boot-admin Port

### ISSUE THREAD

**Issue by bhagyaperera123** [codecentric/spring-boot-admin#874]
http://localhost:8080/myproject :- project  UI
http://localhost:8090/admin :- admin UI

**Comment by joshiste** [comment]
Inside the same application you can't - but you can run SBA on a different port by just running it as a single (standalone) application

**Comment by bhagyaperera123** [comment]
how to change SAB? i tried using server.port

**Comment by bhagyaperera123** [comment]
im stuck. can you please give me idea?

**Comment by joshiste** [comment]
Changing the port of a spring boot application is not a spring boot admin issue. Please consult the [Spring Boot Reference Guide](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/)

**Comment by bhagyaperera123** [comment]
yes i understand! i meant changed server.port: 8090
the admin will use i changed port.
