### ISSUE TITLE
Use history mode in Vue Router for better redirects after login for deep links

### ISSUE THREAD

**Issue by asibross** [codecentric/spring-boot-admin#876]
I am using Spring boot 2.0.2 and have OAuth 2 configured.

When trying to access an instance page directly (when I am not yet authenticated), I am correctly redirected to the login page, but when authentication is complete I am not being redirected to the initial instance page but rather to the main page (applications list).

I believe the reason is the way Vue Router is configured (by default it uses `hash` mode).
https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

In `hash` mode the server is not aware of the actual path (after #), so the final redirect just points it back to the root path.

This could be addressed by:
1. Setting mode to history in VueRouter.
2. Adding a server fallback to redirect to index when mapping does not exist.
3. Change the instances/applications mapping to something else, so that it won't collide.

**Comment by joshiste** [comment]
Iirc, if you don't protect the static assets (ie `/` and `/assets`) then the UI redirects to the login (and not the server) and the fragments should be kept.

**Comment by joshiste** [comment]
> 3. Change the instances/applications mapping to something else, so that it won't collide.

This is not necessary if the requested content-type is correctly considered, so that the html is not delivered for the rest-requests....

**Comment by joshiste** [comment]
@asibross I'd be happy if you could test one of our snapshot versions...

**Comment by asibross** [comment]
Hey @joshiste, thanks for merging. I see that this is part of the 2.2 release. I currently don't have a stable version for our internal solution with 2.2. I will try to get something this week, so I will be able to test it.
