### ISSUE TITLE
Can't reach info endpoint of client behind proxy

### ISSUE THREAD

**Issue by TheScientist** [codecentric/spring-boot-admin#881]
Following Setup (SBA 2.0.2):
Spring Boot App (2.0.2) registers itself as client at admin service with _spring.boot.admin.client.instance.service-url_ property set, because the app is hidden behind a reverse proxy.
Admin Server receives the registration and uses the given URL for healthcheck (works as expected)
Admin Server then tries to get other endpoints via actuator (info, metrics, ...), but actuator delivers those endpoints with the internal hidden url, so the server gets a 502 error when querying those endpoints.

Is it possible to apply spring.boot.admin.client.instance.service-url to the actuator endpoints too?
Or can I tell actuator to rewrite those endpoints?

**Comment by joshiste** [comment]
Please read https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server

iirc spring boot rewrites the urls if proxy and spring boot app is configured properly.

**Comment by TheScientist** [comment]
Found a solution [here](https://github.com/spring-projects/spring-boot/pull/13495) by adding the mentioned ProxyFilterConfiguration, because server.use-forward-headers=true didn't work for me.
