### ISSUE TITLE
domain issue with SSL

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [codecentric/spring-boot-admin#882]
I am using the latest version of spring boot and spring boot admin.

The application failed to be registered (403 forbidden). I read that this is caused by Spring Security, but I can't solve this problem.

The problem appeared after I changed from public IP to use a domain.

I changed the localhost to the real domain (with localhost I got a DNS issue):

```
spring.boot.admin.client.url=https://example.com:8443
spring.boot.admin.client.instance.service-url=https://example.com:8443
```

**Comment by JavierSegoviaCordoba** [comment]
This is the error if I use localhost.

`java.security.cert.CertificateException: No subject alternative DNS name matching localhost found`

**Comment by JavierSegoviaCordoba** [comment]
My configuration class:

```
@Configuration
    public static class SecuritySecureConfig extends WebSecurityConfigurerAdapter {
        private final String adminContextPath;

        public SecuritySecureConfig(AdminServerProperties adminServerProperties) {
            this.adminContextPath = adminServerProperties.getContextPath();
        }

        @Override
        protected void configure(HttpSecurity http) throws Exception {

            SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
            successHandler.setTargetUrlParameter("redirectTo");
            successHandler.setDefaultTargetUrl(adminContextPath + "/");

            http.authorizeRequests()
                    .antMatchers(adminContextPath + "/assets/**").permitAll()
                    .antMatchers(adminContextPath + "/login").permitAll()
                    .antMatchers("/lol/**").permitAll()
                    .antMatchers("/favicon.ico").permitAll()
                    .anyRequest().authenticated()
                    .and()
                    .formLogin().loginPage(adminContextPath + "/login").successHandler(successHandler).and()
                    .logout().logoutUrl(adminContextPath + "/logout").and()
                    .httpBasic().and()
                    .csrf()
                    .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                    .ignoringAntMatchers("/instances", "/actuator/**");
        }
    }

```

**Comment by JavierSegoviaCordoba** [comment]
I tried `spring.boot.admin.client.instance.prefer-ip=true` (I am using docker).

With localhost and domain, both not working (DNS and 403 problems respectively).

**Comment by joshiste** [comment]
I don't think this is a issue related to Spring Boot Admin, but more that your HTTPS setup is incorrect or you  are missing some certificates in your keystore.
And when reading `java.security.cert.CertificateException: No subject alternative DNS name matching localhost found` I'd suggest just use plain http for localhost.

**Comment by JavierSegoviaCordoba** [comment]
It is a let's encrypt certificate converted to p12. All is working except I can register the application with spring boot admin.

**Comment by JavierSegoviaCordoba** [comment]
Is there some tutorial about spring boot admin working on SSL @joshiste ?

**Comment by marikt** [comment]
Hi @JavierSegoviaCordoba I have the same problem. Did you managed to solve it?

**Comment by marikt** [comment]
try to set in your application.properties:

```
spring.boot.admin.client.instance.management-base-url=https://www.mydomain.cz:YOUR-APP-PORT
spring.boot.admin.client.instance.management-url=${spring.boot.admin.client.instance.management-base-url}/actuator
spring.boot.admin.client.instance.health-url=${spring.boot.admin.client.instance.management-base-url}/actuator/health
spring.boot.admin.client.instance.service-url=${spring.boot.admin.client.instance.management-base-url}
```

also 
spring.boot.admin.client.url=http://localhost:8080 looks incorrect, does your spring boot admin really runs on 8080?
