### ISSUE TITLE
Logout Not working 

### ISSUE THREAD

**Issue by bhagyaperera123** [codecentric/spring-boot-admin#884]
i configured my main class like this. after that login to spring boot admin and click logout. when i click logout button automatically redirect to  this address http://localhost:8888/logout
if i press enter on URL bar then logout is working. 

@SpringBootApplication
@EnableAdminServer
public class DemoApplication {
    
	@Configuration
	static class SecurityPermitAllConfig extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http.authorizeRequests()
					.antMatchers("/assets/**").permitAll()
					.antMatchers("/login").permitAll()
					.antMatchers("/logout").permitAll()
					.anyRequest().authenticated()
					.and()
					.formLogin().loginPage("/login").and()
					.httpBasic().and()
					.csrf()
					.csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
					.ignoringAntMatchers("/instances", "/actuator/**").and()
					.logout()
					.logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
					.permitAll();
		}
	}
	
	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}

**Comment by bhagyaperera123** [comment]
done! i disabled csrf.
.csrf().disable()

**Comment by joshiste** [comment]
duplicates #868
