### ISSUE TITLE
Support for custom management.server.address

### ISSUE THREAD

**Issue by phiber** [codecentric/spring-boot-admin#885]
Hello,

We are using spring boot admin to monitor multiple spring boot 2 containers over an eureka registry. In our environment, it is mandatory to configure each container's management address different from the service address, so that the management port is bound to a different network address than the service port. 

Therefore, each container has the configuration property "management.server.address" set to a different value than "server.address", as well as different values for "management.server.port" and "server.port". 

For port configurations, spring boot admin offers the possibility to set the property "management.port" in Eureka's Metadata map, which works great. But for the management address, there is no such solution, so all monitoring (except for health) does not work. 

Would it be possible to change [DefaultServiceInstanceConverter.getManagementUrl()](https://github.com/codecentric/spring-boot-admin/blob/2.0.x/spring-boot-admin-server-cloud/src/main/java/de/codecentric/boot/admin/server/cloud/discovery/DefaultServiceInstanceConverter.java#L90/DefaultServiceInstanceConverter.java#L90) to also read an additional property from the metadata map?

**Comment by joshiste** [comment]
closed in favor of the PR
