### ISSUE TITLE
embeddable spring-boot-admin 

### ISSUE THREAD

**Issue by andresoviedo** [codecentric/spring-boot-admin#887]
Please allow embedding spring-boot-admin into existing spring-boot application by exposing the spring-boot-admin end-points directly into the app and not requiring a dedicated http port.

The motivation of this feature request is because I am using PCF Dev (Pivotal Cloud Foundry Dev Environment) and I cannot deploy it because of it's memory restrictions (Max 4GB and I'm using 4GB already).

The motivation is also because I don't want to mantain so many applications (3 applications minimum: spring-boot-config, spring-boot-eureka, spring-boot-admin, ...) just to support my micro-services cloud.

**Comment by joshiste** [comment]
you already can by moving the ui using the `spring.boot.admin.context-path` property.
As SBA will use the same ApplicationContext you may have some trouble

**Comment by andresoviedo** [comment]
Thanks @joshiste  It works on Cloud Foundry (eureka + boot-admin).

However, could you please elaborate a bit more on?

> you may have some trouble

**Comment by joshiste** [comment]
The sba servers may interfere with your application config and vice versa
