### ISSUE TITLE
Can't integrate Spring Boot Admin Server 2 and Spring Boot Admin Client 2 with Spring Boot 2 in a single application

### ISSUE THREAD

**Issue by dmitrysenkovich** [codecentric/spring-boot-admin#889]
I'm migrating an application from Spring Boot to Spring Boot 2. Previously we had to use Spring Boot Admin Server and Client in a single application (i.e. the application was both a server and a client at the same). That is weird but we have to continue use it the same way at least for now.

At first I decided to make it work using a demo project:
https://github.com/dmitrysenkovich/spring_boot_admin_2_not_working

However, I'm getting an error:

`ApplicationRegistrator: Failed to register application as Application(name=spring-boot-admin-sample-servlet, managementUrl=http://localhost:8080/actuator, healthUrl=http://localhost:8080/actuator/health, serviceUrl=http://localhost:8080/actuator/admin) at spring-boot-admin ([http://localhost:8080/instances]): 404 null. Further attempts are logged on DEBUG level`

Maybe it may be a bug because a similar configuration (moved some properties under `instance`) works with Spring Boot Admin Server/Client 1.5.7 and Spring Boot 1.5.14.RELEASE. Now Spring Boot version is 2.0.4.RELEASE and Spring Boot Admin Client/Server is 2.0.2.

I need your help, here the link for the stackoverflow question releated:
https://stackoverflow.com/questions/51912880/cant-integrate-spring-boot-admin-server-2-and-spring-boot-admin-client-2-with-s

Many thanks!

**Comment by joshiste** [comment]
If you set the spring.boot.admin.context-path, you also have to include this suffix in the spring.boot.admin.client.url

**Comment by dmitrysenkovich** [comment]
@joshiste works, thanks! but what about having a complete example somewhere in docs? I could add it myself. and I've got one more idea: is it worth adding a starter for such case as I have? I mean having both server and client in the same app?

**Comment by joshiste** [comment]
@dmitrysenkovich Sorry, but as mentioned in the FAQ running SBA included in your business application might bear some problems - so I don't want to embrace this setup. Hence there are intentionally no starters, guides or samples.
