### ISSUE TITLE
Do not display down status service

### ISSUE THREAD

**Issue by GreatGarlic** [codecentric/spring-boot-admin#891]
Such as Eureka UI:
![image](https://user-images.githubusercontent.com/9128851/44385807-223b9980-a553-11e8-967b-50e6bd526ad0.png)

Spring-boot-admin UI:
![image](https://user-images.githubusercontent.com/9128851/44385897-629b1780-a553-11e8-966d-4921b152afd0.png)

Missing SZY_COMMUNICATION service item.

This is a bug or feature?

Why ? I don't know.

**Comment by joshiste** [comment]
Looks like a eureka issue to me.
Please check the eureka api for listing all services and/or debug the ServiceDiscoveryListener.
SBA doesn’t filter any services by default

**Comment by GreatGarlic** [comment]
@joshiste 
![image](https://user-images.githubusercontent.com/9128851/44388284-536b9800-a55a-11e8-917e-5cefac5ed272.png)
SZY_COMMUNICATION on the eureka is exist.
