### ISSUE TITLE
Configurable extra information in application list 

### ISSUE THREAD

**Issue by Zeka13** [codecentric/spring-boot-admin#893]
Version 2.0.1

Is it possible to show anything other than name and version  in application list?

If not, please provide this feature, for example, I want to see build.time there

Thx

**Comment by gunnarro** [comment]
maybe uptime and/or start time can be added

**Comment by shershen08** [comment]
Is that one still active for picking up? 

We could generalize it even more by providing some kind of a template config as a parameter

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.
