### ISSUE TITLE
How to change timezone? 

### ISSUE THREAD

**Issue by bhagyaperera123** [codecentric/spring-boot-admin#895]
my current timezone is JST. but admin application showing me wrong timezone. i don't have idea about this.

**Comment by dtodt** [comment]
Not sure if is the better solution but, here I'm using something like this:

```
    @PostConstruct
    void started() {
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
    }
```

**Comment by bhagyaperera123** [comment]
@dtodt before that i tried this. not working.

**Comment by bhagyaperera123** [comment]
@dtodt i tried this not working!
