### ISSUE TITLE
 is there any possibility to convert 2.0 actuator data to 1.5 actuator format?

### ISSUE THREAD

**Issue by Japca** [codecentric/spring-boot-admin#897]
Hi Johannes,

Sorry that I ask the question on this channel but I do not know how else to contact you.

I'm currently solving issues with spring boot admin server 1.5.4 which monitor our services via Eureka. All app are SpringBoot 1.5.7 but are we creating a new app with SpringBoot version 2.0.X. App successfully is registered but it is problem with some tabs show corrupted info.

If there any possibility to convert 2.0 actuator data to 1.5 actuator format?

Thanks for reply 
Jakub

**Comment by joshiste** [comment]
You could write some zuul filters to achieve that, but I wouldn't recommend end.

Why you just don't upgrade to Spring Boot Admin 2.x which [can monitor 1.5.x applications (and will do the necessary conversions for you)](http://codecentric.github.io/spring-boot-admin/current/#monitoring-spring-boot-1.5.x)
