### ISSUE TITLE
Can't run SBA server-ui on a SBA Server instance

### ISSUE THREAD

**Issue by solangesv** [codecentric/spring-boot-admin#899]
I'm trying to use the ui from the project on a running SBA instance, in order to modify the style of the admin page, but it's not taking. I'm not getting any error when I run my SBA app. On the project's README it says:

```
Run  a Spring Boot Admin Server instances with the template-location and resource-location pointing to the build output and disable caching:
spring.boot.admin.ui.cache.no-cache: true
spring.boot.admin.ui.extension-resource-locations: file:@project.basedir@/../spring-boot-admin-sample-custom-ui/target/dist/
spring.boot.admin.ui.cache-templates: false
```

Where do these values go? I have them on my applications.properties but it's not working.

**Comment by joshiste** [comment]
`application.properties` is correct please make sure that the maven filtering is active and also that the resource location points to the correct path. (The given value is for the `spring-boot-admin-sample-custom-ui`-module...)
There is a working sample config in [spring-boot-admin-sample-servlet](https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet)
