### ISSUE TITLE
Provide option to use favicon file

### ISSUE THREAD

**Issue by anandvarkeyphilips** [codecentric/spring-boot-admin#903]
** Enhancement **
Please provide a configuration option to set custom favicon image. It would be great for customization.

**Comment by Glosur** [comment]
@joshiste How would you approch this one?
I'd like to give it a try

**Comment by joshiste** [comment]
In a similar fashion as we do for the title. But be aware that we use 2 different favicons depending on the status of all applications.

**Comment by shershen08** [comment]
@joshiste I've started implementing it like this, what do you think ?
 - https://github.com/shershen08/spring-boot-admin/commit/632dba732f8715bb9e94d7beea99ffdf99bbc30d

**Comment by joshiste** [comment]
@shershen08 looking good so far. Just the documentation for the property is lacking. I'd be happy if you submit a PR.

**Comment by shershen08** [comment]
Done, @joshiste - https://github.com/codecentric/spring-boot-admin/pull/1070

Didn't find a place where to put the documentation though
