### ISSUE TITLE
Tab overflow when there are many Actuator endpoints exposed

### ISSUE THREAD

**Issue by shakuzen** [codecentric/spring-boot-admin#904]
As [mentioned on Gitter](https://gitter.im/codecentric/spring-boot-admin?at=5b6105a44481225844491cab):

> I’m not sure what is best to do about it since I’m not a designer, but the tabs for the different actuator endpoints are not fitting together well (on a screen that isn’t big enough) now that there are so many of them.

![image](https://user-images.githubusercontent.com/8924140/44780639-5e0ed880-abbd-11e8-8336-11fe1f3baea9.png)

@joshiste talked about grouping them as a potential solution. I wanted to open this issue to make sure some solution could be tracked for this problem.

**Comment by shakuzen** [comment]
For reference, the groupings @joshiste proposed were:

> - details
> - metrics
> - config
>   - env
>   - (configprops in future may be - at least there is a feature request)
> - logging
>   - logfile
>   - loggers
> - jvm:
>   - jmx
>   - heapdump
>   - threadump
> - web
>   - mappings
>   - http-traces
> - security
>   - auditevents
>   - sessions
> - data
>   - caches (with 2.1.x)
>   - flyway
>   - liquibase
> - scheduled tasks

**Comment by joshiste** [comment]
yep. I'm currently working on this.

**Comment by joshiste** [comment]
Currently I'm thinking of this:

> - Insights (or just Instance)
>   - details
>   - metrics
>   - env
>    - scheduled tasks
>   - (configprops in future may be - at least there is a feature request)
> - logging
>   - logfile
>   - loggers
> - jvm:
>   - jmx
>   - heapdump
>   - threadump
> - web
>   - mappings
>   - http-traces
> - security
>   - auditevents
>   - sessions
> - data
>   - caches (with 2.1.x)
>   - flyway
>   - liquibase
