### ISSUE TITLE
Add audit log filter parameters

### ISSUE THREAD

**Issue by alexwais** [codecentric/spring-boot-admin#909]
Re-add the filter parameters for principal, type, and timeframe, which disappeared in SBA 2.0.

Especially when audit logs are permanently persisted (in DB), it is inevitable to filter the logs by date. Otherwise the request to /auditevents would take too long.

Currently the first request is made with /auditevents?after=1970-01-01T00:00:00.000Z.
Adding some form inputs for appending the request params would be a simple solution.

![image](https://user-images.githubusercontent.com/6129941/44872611-4eaf8e00-ac96-11e8-86af-6f65b359bcbc.png)

**Comment by joshiste** [comment]
closed with #943
