### ISSUE TITLE
How can I customize admin UI

### ISSUE THREAD

**Issue by alfredzhang** [codecentric/spring-boot-admin#91]
I want to customize some text/function on the admin UI, is there an easy way to do it? Thanks

**Comment by joshiste** [comment]
You have to copy the spring-boot-admin-server-ui submodule into your own project. Customize the sources, build it and include the your own built module in your server instead of the official.
There is currently no other solution. If you got something in mind, please leave a note.

**Comment by alfredzhang** [comment]
Thanks!
