### ISSUE TITLE
Incorrect timestamp for httpstrace

### ISSUE THREAD

**Issue by kivens** [codecentric/spring-boot-admin#912]
For 2.0.2 version
I found the incorrect timestamp about httpstrace from ui
the endpoint is return  like this
{timestamp:{nano:672000000,epochSecond:1536055350},.....}
but the ui show
2018/09/04 00:00:00.000

**Comment by joshiste** [comment]
Your output should contain timestamps formatted this way `"timestamp":"2018-09-04T13:07:18.226Z"`

So I guess you've customized your object mapper. For SBA we depend on the default configuration.
Also see https://github.com/spring-projects/spring-boot/issues/12951
