### ISSUE TITLE
SpringBootAdmin Not Showing All Clients in Admin Dashboard

### ISSUE THREAD

**Issue by sandyjohn** [codecentric/spring-boot-admin#913]
I am using spring boot admin module for monitoring the Spring-Boot MicroServices Application. Admin and client applications are registered successfully but in admin dashboard I cannot able to see all the MicroServices at a time. Only one Spring-Boot Client Application was visible and after few refresh, other application was loading same like it goes on. How to see all the Client Applications at a time in springbootadmin dashboard?

**Comment by joshiste** [comment]
Sorry I don't understand your problem. Could you give some more details (and maybe screenshots)

**Comment by sandyjohn** [comment]
I have added springboot admin to monitor the microservices, There are 5 client springboot applications which is running on the same server where springboot admin was running. In Dashboard i can able to see either any one of the application out of the 5 client applications. But whereas i expect to see all the 5 Applications.
![image](https://user-images.githubusercontent.com/10896779/45036108-3914dc80-b079-11e8-837a-56961e542b05.png)

**Comment by sandyjohn** [comment]
Registeration was successful for all the 5 applications. And when i refresh the browser other client application will load by replacing the previous application loaded which means only one applications loading at one time.

**Comment by joshiste** [comment]
Do they all register with the same healthcheck url?

**Comment by sandyjohn** [comment]
yes, healthurl was same for all the client applications.

**Comment by joshiste** [comment]
applications are identified by the health url so the overwrite each others registration

**Comment by sandyjohn** [comment]
Thanks a lot...I have changed the health-url for all client apps.Now its working fine. Thanks a lot @joshiste
