### ISSUE TITLE
sba client to use discovery client

### ISSUE THREAD

**Issue by andresoviedo** [codecentric/spring-boot-admin#915]
I don't want to / can't  use discovery from boot-admin-server.

It would be nice to support discovery from boot-admin-client,  in order to register client to all boot-admin instances.

     spring.boot.admin.client.url=http://my-boot-admin-host/admin

The reason for this request is that in Cloud Foundry there is no need to have an extra Discovery Service because Cloud Foundry already supports that (GoRouter).  However, I still want to register my clients to boot admin using a Virtual Hostname.  This way registration would work with both cloud and non cloud profiles.

**Comment by joshiste** [comment]
The spring boot admin clients uses a `RestTemplate`. You can instantiate the `ApplicationRegistrator` with a custom configured `RestTemplate` which resolves your virtual hostname.
