### ISSUE TITLE
Check for updates, and update dependencies 

### ISSUE THREAD

**Issue by datasmurfen** [codecentric/spring-boot-admin#916]
It's very hard to keep track on versions/updates in all our project dependencies . Would been great with an notify on new updates in the pom dependencies, and display this in the Spring Boot Admin ui

**Comment by joshiste** [comment]
We only depend on Spring Boot and Spring Cloud. I try to keep track of version updates with a issue in the milestone for the corresponding release (e.g. [2.1.0](https://github.com/codecentric/spring-boot-admin/milestone/21?closed=1)).
