### ISSUE TITLE
Application Page Not Rendering

### ISSUE THREAD

**Issue by sandyjohn** [codecentric/spring-boot-admin#917]
Springbootadmin application page was not rendering and instead while i loading the application in browser, login file was automatically downloading. Everything was working fine till yesterday but suddenly this issue was occurs.

**Comment by joshiste** [comment]
Sorry but I don't understand your problem. Please provide a detailed description of your problem and a project to reproduce the problem.

**Comment by sandyjohn** [comment]
I am using SpringbootAdmin Application file as a war application and used the below code. After deploying in tomcat, while loading the application page as localhost:8080/admin/login.html. Application Signin Page was not rendering and instead  file named as "login" is downloading.

@Override
        protected void configure(HttpSecurity http) throws Exception {
            /*// @formatter:off
            SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
            successHandler.setTargetUrlParameter("redirectTo");
            successHandler.setDefaultTargetUrl(adminContextPath + "/");

            http.authorizeRequests()
                .antMatchers(adminContextPath + "/assets/**").permitAll()
                .antMatchers(adminContextPath + "/login.html").permitAll()
                .anyRequest().authenticated()
                .and()
            .formLogin().loginPage(adminContextPath + "/login.html").successHandler(successHandler).and()
            .logout().logoutUrl(adminContextPath + "/logout").and()
            .httpBasic().and()
            .csrf().disable();

**Comment by joshiste** [comment]
Please provide a detailed description of your problem and a project to reproduce the problem.

**Comment by joshiste** [comment]
Despite the fact that the csrf config is wrong (already reported and fixed in the docs with https://github.com/codecentric/spring-boot-admin/issues/894) your sample works perfectly fine for me.
