### ISSUE TITLE
Allow configuring a delay for the registration task

### ISSUE THREAD

**Issue by ArloL** [codecentric/spring-boot-admin#919]
First of all thanks for this tool. It's very helpful in our organization since I don't have to explain configuring VisualVM to every developer and is also easier to use.

I deploy an application that contains both the SBA server and the client to register with itself to a Tomcat application server. When I deploy them I get this warning:

````
Failed to register application as Application(name=spring-boot-admin##20180906T085329Z, managementUrl=http://localhost:8080/spring-boot-admin/actuator, healthUrl=http://localhost:8080/spring-boot-admin/actuator/health, serviceUrl=http://localhost:8080/spring-boot-admin) at spring-boot-admin ([http://localhost:8080/spring-boot-admin/instances]): 404 null. Further attempts are logged on DEBUG level
````

Later the registration succeeds and I can see the application in the GUI. Apparently the application is not fully deployed in the moment the registration is first attempted. Would it be possible to add a configurable delay (with zero being the default)?

Maybe something like this:

````
if (initialDelay.isZero()) {
	scheduledTask = taskScheduler
	    .scheduleAtFixedRate(registrator::register, registerPeriod);
} else {
	taskScheduler.scheduleAtFixedRate(registrator::register,
	    Instant.now().plus(initialDelay), registerPeriod);
}
````

Thanks!

**Comment by joshiste** [comment]
The benefit for adding the initial delay is just getting rid of the single log event. Imho it's not worth doing it as the registration is repeated and succeeds.

**Comment by ArloL** [comment]
Thanks for the consideration. My idea with the delay was not *just* to get rid of a log event. All following messages are not logged at all due to the one log message having been sent. Thus it's not possible to know if there is something misbehaving since the log is always hidden.

**Comment by chrislhardin** [comment]
I know this is closed but I could also use a delay or manual trigger of registration... My Application does a lot of initialization up front and the registration happens too early and then the health checks start causing the application start to struggle. I'm actually shutting down spring boot admin and then waiting until my production application has started to restart it to avoid this...

**Comment by joshiste** [comment]
@chrislhardin there is a `spring.boot.admin.client.auto-registration` property. If it is false it prevents that the application wont register automatically. The `ApplicationRegistrator#register()` will register the application when it is called.

**Comment by chrislhardin** [comment]
That is absolutely perfect for me... Thanks...
