### ISSUE TITLE
HealthUrl in ApplicationRegistrator

### ISSUE THREAD

**Issue by jocax** [codecentric/spring-boot-admin#92]
I have a strange error with ApplicationRegistrator and Json mapping. HealthUrl is a property of class de.codecentric.boot.admin.model.Application.

`
@JsonCreator
	public static Application create(@JsonProperty("url") String url,
			@JsonProperty("managementUrl") String managementUrl,
			@JsonProperty("healthUrl") String healthUrl,
			@JsonProperty("serviceUrl") String serviceUrl,
			@JsonProperty("name") String name, @JsonProperty("id") String id,
			@JsonProperty("statusInfo") StatusInfo statusInfo) {
		Assert.hasText(name, "name must not be empty!");
		if (StringUtils.hasText(url)) {
			// old format
			return new Application(url.replaceFirst("/+$", "") + "/health", url, null,
					name, id, statusInfo);
		}
		else {
			Assert.hasText(healthUrl, "healthUrl must not be empty!");
			return new Application(healthUrl, managementUrl, serviceUrl, name,
					id, statusInfo);
		}
	}
`

The exception claims that the property 'healthUrl' is not empty. But as you can see from the log message it self in the healthUrl is set to: http://config-1.dev:8443/manage/health

`
[remote] [config-1] [quiply-config-service] [user] [trackId] [remote] 2015-08-19 13:27:59.048  WARN 1 --- [pool-1-thread-1] d.c.b.a.services.ApplicationRegistrator  : Failed to register application as Application [id=null, name=quiply-config-service, managementUrl=http://config-1.dev:8443/manage, healthUrl=http://config-1.dev:8443/manage/health, serviceUrl=http://config-1.dev:443] at spring-boot-admin (http://admin-1.dev:443/api/applications): Could not read document: Instantiation of [simple type, class de.codecentric.boot.admin.model.Application] value failed: healthUrl must not be empty!; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class de.codecentric.boot.admin.model.Application] value failed: healthUrl must not be empty!
`
Any idea what causes the jsom mapper to throw the exception?

**Comment by joshiste** [comment]
The exception occurs when the client wants to read the registration-response. So you have to inspect the response for missing healthUrl.

Is it possible that your client has a newer version then the server and there is a version mismatch?
In the version 1.2.3 i've made changes to the client to be more lenient to model changes...

**Comment by jocax** [comment]
I finally find out what the problem is. It was a routing problem between docker instances .... the client received a different response and could not parse it to Application class .... I will close the ticket.
