### ISSUE TITLE
Manage page is blank when sba run on remote server

### ISSUE THREAD

**Issue by fabadoo** [codecentric/spring-boot-admin#920]
Hi,

The problem only appear when it runs on a remote server, 
Everything's fine on my computer (http://127.0.0.1 or http://<computer-name>)

At the begin, the app redirect me to the login form correctly.
But when logged, i've a blank page... 

Firefox Network observer gives ;
> 200 - http://.../manage/     
> 200 - sba-core.css
> 200 - sba-core.js
> 200 - vendors.js

But i've have the following error in the console :
> ReferenceError: webpackJsonp is not defined[Learn More] sba-core.js:1

My project contains this dependencies : web / sba/ security/ cloud config.
I've tried with both following versions 2.0.5 & 2.1.M2, exacts same result.

An then nothing... just a blank page.
Security misleading or angular path problem..

Could you help me.

In case of, this is the "HttpSecurity" set tup :
```
SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
            successHandler.setTargetUrlParameter("redirectTo");
            successHandler.setDefaultTargetUrl(adminContextPath + "/");

            http.authorizeRequests()
                .antMatchers(adminContextPath + "/assets/**").permitAll()
                .antMatchers(adminContextPath + "/login").permitAll()
                .anyRequest().authenticated()
                .and()
                    .formLogin()
                    .loginPage(adminContextPath + "/login").successHandler(successHandler)
                .and()
                    .logout().logoutUrl(adminContextPath + "/logout")
                .and()
                    .httpBasic().realmName("AdminPortal")
                .and()
                    .cors().disable()
                    .csrf()
                        .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                        .ignoringAntMatchers(adminContextPath + "/instances", adminContextPath + "/actuator/**");
```

**Comment by joshiste** [comment]
Please provide a project to reproduce the problem

**Comment by fabadoo** [comment]
Ok, quite complicate for me to give you all, but here is the bundled project.
Need a 'cloud-config-server' to the cloud-config/service-admin-portal-default.yml

[tp.zip](https://github.com/codecentric/spring-boot-admin/files/2358753/tp.zip)

**The other option would be to do a short Teamviewer Or Skype session...**

**Comment by fabadoo** [comment]
I see that the GET "vendors.js" is systematically cut while loading... 'So not a angular or boot config problem.
Could say : case closed.
sorry.

**Comment by fabadoo** [comment]
I see that the GET "vendors.js" is systematically cut while loading... 'So not a angular or boot config problem.
sorry.
