### ISSUE TITLE
Spring Boot Admin 2.0.2 Ignores Eureka Client Instance Id

### ISSUE THREAD

**Issue by matzegebbe** [codecentric/spring-boot-admin#923]
Hi,
thanks for the awesome admin server.

We have two global docker swarm services with the same application name. In the Eureka server I can see that all services registers with a different instance id

```
eureka.client.instance.instanceId:${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.
value}}}
```

![image](https://user-images.githubusercontent.com/3482021/45228292-183fc780-b2c3-11e8-980d-e92d045ceadd.png)

But the Admin Server seems to ignore the Instance Id. In the Admin Server I only show two instances:

![image](https://user-images.githubusercontent.com/3482021/45228421-6d7bd900-b2c3-11e8-85ba-81c22b69fe0e.png)

In the journal I can also see that I got many REGISTRATION_UPDATED for the same "instance". Can I only change that behavior by modifying the ServiceInstanceConverter?

**Comment by joshiste** [comment]
Applications are per default identified by the health url. If you are running on cloud foundry you can alternate this behaviour. see http://codecentric.github.io/spring-boot-admin/current/#_cloudfoundry

**Comment by matzegebbe** [comment]
this property for my clients solved the issue. preferIpAddress: false was not enough. 
```
eureka.instance.hostname: ${HOSTNAME}
```
