### ISSUE TITLE
Use lib Gson instead of Jackson

### ISSUE THREAD

**Issue by eduardocintra** [codecentric/spring-boot-admin#925]
In the application that I work we use the Lib Gson instead of Jackson for this we exclude Jackson lib using:

```
@EnableAutoConfiguration(exclude = { JacksonAutoConfiguration.class })
```

But when I use this notation the SBA not works.

![teste](https://user-images.githubusercontent.com/2051934/45299903-59162700-b4e3-11e8-8717-7c34eb052f1c.png)

It is possible to adapt SBA to use Gson lib?

**Comment by joshiste** [comment]
We make use of some Jackson annotations and some custom serializers. So you'd need to replace all of this.

I'd just suggest that you split up the SBA server (using Jackson) and your own application (using Gson) into two separate boot applications and you shouldn't have any problem

We won't support running SBA server with Gson, the SBA client should work using Gson.

**Comment by eduardocintra** [comment]
@joshiste 
Thank you for your idea! 
I tried, I splitted in two application one is the server and my application as client, but not works, the dashboard opens now but some features not works, for example, the Health of Instance and the Mappings.

![1](https://user-images.githubusercontent.com/2051934/45320046-e96e5f00-b517-11e8-9f38-d9f3a34e6830.png)

![2](https://user-images.githubusercontent.com/2051934/45320052-ed9a7c80-b517-11e8-9811-5b371b88d643.png)

When I back to use Jackson works fine.

That is, the SBA client not working well with Gson.

**Comment by joshiste** [comment]
The problem isn't the SBA client. The client just registers at the SBA server all data are taken from the spring boot actuator endpoint. SBA depends on the default format of the Spring Boot actuator endpoints. My (false?) assumption was that the actuator endpoints look the same using gson and jackson.

**Comment by zhaoxi1988** [comment]
@joshiste 
SpringMVC output reposne "ContentType=application/json", if JacksonAutoConfig + @RestController.
But GsonAutoConfiguration not. How can I fix it?
