### ISSUE TITLE
remove shorthand-syntax in index.html

### ISSUE THREAD

**Issue by rhosman** [codecentric/spring-boot-admin#926]
Spring Boot Admin: 2.0.2
Spring Boot: 2.0.4.RELEASE
Firefox: 31.6.0
Chrome: 37.0.....

In the clearly old versions of Firefox and Chrome that some of my users are still required to use [lines 59-61 of index.html](https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-server-ui/src/main/frontend/index.html#L59) cause a syntax error which results in nothing being displayed on the page because the SBA variable is then seen as undefined when the main application tries to read it.

I would like to be able still have SBA work in older browsers that don't support having non-key-value members in JSON objects.

I would expect this issue to be visible with any minimal SBA server project  when  attempting to load it in a sufficiently old browser.

**Comment by joshiste** [comment]
I fixed this in 86ba5b9 as it was a quick one.
But I don't tested support for these browsers and we won't support the in the future. The browsers are more than three years old and have a global usage of 0.01% so the effort of supporting them has no relation to the benefit.
