### ISSUE TITLE
OutOfMemory: Java heap space

### ISSUE THREAD

**Issue by mfrehe** [codecentric/spring-boot-admin#932]
Hi,

i am using

Spring Boot Admin Version: Version 2.0.2

The Application is running as a service inside of docker swarm. 

After "a while" the frontend can't reach the backend anymore. (Yellow Exclamation Mark).

![6e9d7eba8f140cfd](https://user-images.githubusercontent.com/43266827/45541695-094f9c80-b810-11e8-9d1b-045ea142e78c.jpg)

![3a8c97131d883ddf](https://user-images.githubusercontent.com/43266827/45541704-110f4100-b810-11e8-807d-442eef9815c5.jpg)

So i watched into the log of the docker service....

![ca1ffc68b435ab2](https://user-images.githubusercontent.com/43266827/45541719-1c626c80-b810-11e8-850f-358cc6863bd9.jpg)

And i watched the service details in Spring Boot Admin itself....

![bildschirmfoto vom 2018-09-14 11-19-09](https://user-images.githubusercontent.com/43266827/45541766-37cd7780-b810-11e8-9ef5-b5e4de48f4b8.png)
As you can see, after two hours the USED MEM is three times as much as at the start.

Initial memory limit for the container was set to 512M, we doubled it up to 1024M but the result is the same. Only a restart of the service can fix the problem.

Is there a problem with the garbage collector?

Thanks it advance

**Comment by joshiste** [comment]
Hard to tell. Did you investigate a heapdump from that OOM?
Are there many client applications registering and deregistering over and over again?
Could you provide a problem to reproduce the issue?

**Comment by mfrehe** [comment]
It doesn't tell me much, but maybe you can get some information out of this.

![bildschirmfoto vom 2018-09-14 12-04-50](https://user-images.githubusercontent.com/43266827/45544033-7e25d500-b816-11e8-964b-561fc22f44ae.png)

**Comment by joshiste** [comment]
Which version of tomcat / spring boot are you using and do you use the embedded container or a war-file deployment?

**Comment by mfrehe** [comment]
Starting Servlet Engine: Apache Tomcat/8.5.32
Spring Boot Version: 2.0.4.RELEASE

it is a container deployment

**Comment by joshiste** [comment]
For me running the application over a long time doesn't yield any issue for me. 
From your screenshots it looks like that some of tomcats buffers aren't released.
Please provide a project to reproduce the issue.

**Comment by joshiste** [comment]
closed due to missing feedback
