### ISSUE TITLE
http trace no  response

### ISSUE THREAD

**Issue by YangAnLin** [codecentric/spring-boot-admin#934]
![image](https://user-images.githubusercontent.com/30170561/45610037-14633080-ba8d-11e8-8dc5-ffe8679dc1cc.png)

application.properties
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

already add this package
org.springframework.boot:spring-boot-starter-actuator:2.0.3.RELEASE

**Comment by dickerpulli** [comment]
I don't get the point. What is exactly the problem?

**Comment by joshiste** [comment]
looking at the timestamps it looks like a duplicate of https://github.com/codecentric/spring-boot-admin/issues/861
