### ISSUE TITLE
Error resolving template "login", template might not exist or might not be accessible by any of the configured Template Resolvers

### ISSUE THREAD

**Issue by zzd0058** [codecentric/spring-boot-admin#935]

**Comment by zzd0058** [comment]
Error resolving template "login", template might not exist or might not be accessible by any of the configured Template Resolvers

**Comment by dickerpulli** [comment]
Did you follow the instructions in the documentation? http://codecentric.github.io/spring-boot-admin/current/#_securing_spring_boot_admin_server

**Comment by zzd0058** [comment]
> 您是否按照文档中的说明进行操作？http://codecentric.github.io/spring-boot-admin/current/#_securing_spring_boot_admin_server

I can't start this app, it' error when i post 'localhost:8080'
![Uploading image.png…]()

**Comment by dickerpulli** [comment]
Do you have a eureka server running? If not try another, simpler example like https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet

**Comment by zzd0058** [comment]
> Do you have a eureka server running? If not try another, simpler example like https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet

yes ,the eureka is running,and I tried the example you said, or the same result.May be caused by thymself.
The strange thing is that I have not changed anything.

**Comment by dickerpulli** [comment]
spring-boot-admin-sample-servlet is working, I'm sure. Could you provide your sources, i.e. in github?

**Comment by zzd0058** [comment]
> spring-boot-admin-sample-servlet is working, I'm sure. Could you provide your sources, i.e. in github?

thanks,i can't build the app,could you tell me how i can do it

**Comment by dickerpulli** [comment]
Please follow the documentation  http://codecentric.github.io/spring-boot-admin/current

**Comment by joshiste** [comment]
If you want to build from sources see https://github.com/codecentric/spring-boot-admin#build
