### ISSUE TITLE
Reminder notifications start error

### ISSUE THREAD

**Issue by readazusa** [codecentric/spring-boot-admin#936]
hello，I user Reminder notifications the code
@Configuration
public class NotifierConfig {

    private final InstanceRepository repository;

    private final ObjectProvider<List<Notifier>> otherNotifiers;

    public NotifierConfig(InstanceRepository repository, ObjectProvider<List<Notifier>> otherNotifiers) {
        this.repository = repository;
        this.otherNotifiers = otherNotifiers;
    }

    @Bean
    public FilteringNotifier filteringNotifier() {
        CompositeNotifier delegate = new CompositeNotifier(otherNotifiers.getIfAvailable(Collections::emptyList));
        return new FilteringNotifier(delegate, repository);
    }

    @Bean(initMethod = "start", destroyMethod = "stop")
    public RemindingNotifier remindingNotifier() {
        RemindingNotifier notifier = new RemindingNotifier(filteringNotifier(), repository);
        notifier.setReminderPeriod(Duration.ofMinutes(10));
        notifier.setCheckReminderInverval(Duration.ofSeconds(10));
        return notifier;
    }
}

then Project start 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-09-17 17:53:19.532 [main] org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter.report  ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  filteringNotifier defined in class path resource [com/yiwangqingshui/springboot/admin/notify/NotifierConfig.class]
↑     ↓
|  compositeNotifier defined in class path resource [de/codecentric/boot/admin/server/config/AdminServerNotifierAutoConfiguration$CompositeNotifierConfiguration.class]
└─────┘

**Comment by readazusa** [comment]
sorry I ses

**Comment by miterial** [comment]
@readazusa so how did you fix it?

**Comment by mxab** [comment]
I think I had the same issue. That happens if no Notifier other are available (expect the ones defined in this config)

Providing a LoggingNotifier per default (e.g. if this error happens in the context loads test or if your app hasn't configured any of the common notifiers) resolved the issue for me it looks like.

**Comment by ShuningWan** [comment]
这个问题应该怎么处理
