### ISSUE TITLE
Info End Point Returning Empty

### ISSUE THREAD

**Issue by sandyjohn** [codecentric/spring-boot-admin#938]
Info End point for Client application returns empty object and In Admin dashboard also, no data available under Application Section in Details Tab. Below are the properties used in Client Application.

#basic auth creddentials
security.user.name=admin
security.user.password=password

#configs to connect to a secured server
spring.boot.admin.url=http://localhost:8081/admin
spring.boot.admin.client.service-url=http://localhost:8081/msp
spring.boot.admin.username=admin
spring.boot.admin.password=password
spring.boot.admin.client.health-url=http://localhost:8081/msp/health
#spring.boot.admin.client.url= http://localhost:8081

endpoints.jmx.domain=com.xxxx.xxx.mspservice
endpoints.jmx.unique-names=true
management.security.enabled=false

#configs to give secured server info
spring.boot.admin.client.metadata.user.name=admin
spring.boot.admin.client.metadata.user.password=password

**Comment by dickerpulli** [comment]
Is this the complete configuration? Or just a part of it?

**Comment by joshiste** [comment]
By default spring boot's info endpoint contains no data. Consider to add information via adding `info.*` properties or implementing a `InfoContributor`
