### ISSUE TITLE
Display registered Beans 

### ISSUE THREAD

**Issue by fionera** [codecentric/spring-boot-admin#942]
It would be nice to display all registered Beans. The "/actuator/beans" actuator would provide the Informations for this.

**Comment by fionera** [comment]
I created a hacked version for my Project... https://github.com/CleanstoneMC/Cleanstone/commit/a785ed6a95f199f3340446e4c591dc13ffe2d277

**Comment by joshiste** [comment]
Would you volunteer for a PR on this?

**Comment by Glosur** [comment]
I'd like to take a shot at this one, would you mind if I do a PR ?

**Comment by joshiste** [comment]
I'd appreciate a PR.

**Comment by fionera** [comment]
Oh sorry :) Since I am not very good at vueJS I only created a hacked version, so yeah please do a Vetter Version :)
