### ISSUE TITLE
JS errors breaking UI

### ISSUE THREAD

**Issue by znevrly** [codecentric/spring-boot-admin#944]
Hi,
SBA 2.0.3, Spring Boot 2.0.5. I have configured according to docs and client registration for Petclinic project works OK in the same instance SBA instance. 

But for our Spring Boot application I have JS errors in Metrics tab, Threads and Enviroments - all leads to stop rendering page without any message to user.

1) JVM->Threads tab
[localhost-1537791740863.log](https://github.com/codecentric/spring-boot-admin/files/2410725/localhost-1537791740863.log)

2) Insight->Environment (leads to spinner loader spinning forever )
[localhost-env.log](https://github.com/codecentric/spring-boot-admin/files/2410768/localhost-env.log)

thx.

**Comment by joshiste** [comment]
At best please provide a project to reproduce the error, at least please provide the responses from the corresponding actuator endpoints

**Comment by znevrly** [comment]
Hi,
[responses.zip](https://github.com/codecentric/spring-boot-admin/files/2424546/responses.zip)
added metrics, on this tab I can see only select box with metrics but no more.

I just reliazed that can be caused, that we have configured Jetty but did not expose MBeans so I going to redeploy app and see if it helps. But generally I think that UI should be safer for misleading data (some error messages e.g.)

**Comment by joshiste** [comment]
You have configured jackson to use snake case. SBA depends on using the spring boot default for the actuator endpoints. This duplicates https://github.com/codecentric/spring-boot-admin/issues/751 - please have a look at it for further information.
