### ISSUE TITLE
click the service url prompt error

### ISSUE THREAD

**Issue by qwwfxl** [codecentric/spring-boot-admin#948]
I click the url  http://DEV-SW-DK-A:30136/  ,it display follow error ,thanks for help!

![default](https://user-images.githubusercontent.com/17565026/46075209-53476380-c1bc-11e8-9304-1d5348361ad1.png)
![default](https://user-images.githubusercontent.com/17565026/46075240-6c501480-c1bc-11e8-90e3-8e249fdf212d.png)

**Comment by joshiste** [comment]
The service url is just a link to the the address the application submits during registration. It's not proxied by the url and thus needs to be reachable for your browser, which it isn't in your case.
If you can change this url via `spring.boot.admin.client.instance.service-url`.

**Comment by qwwfxl** [comment]
thanks very much!
