### ISSUE TITLE
Fetching /info and /configprops on Application tab

### ISSUE THREAD

**Issue by lidkowiak** [codecentric/spring-boot-admin#95]
Endpoints /info and /configprops are fetched quite often on Application tab. From my perspective these endpoints are quite constant (especially /info). Is there any way to disable this fetching on this tab or change frequency of such fetching.

**Comment by lidkowiak** [comment]
What do you think about removing this constant requesting of /info and /configprops on Application tab. Is there any use case it supports? Or perhaps add possibility similar to refreshing on Trace tab?

**Comment by joshiste** [comment]
the /info is requested to show the version info and /configprops to detect if logfile/avtiviti is available. This can change anytime due to deployments. So the endpoints are requested regularly.

**Comment by lidkowiak** [comment]
Let me understand it better. When new version of application is deployed it deregisters from spring-boot-admin and new one is registered with new version and configuration. 
From other perspective I see cases when configuration of application is changed during runtime using Spring Cloud Config.

**Comment by joshiste** [comment]
1. Deregistration on application shutdown isn't enabled by default, so accidental shutdown can be noticed.
2. The registration doesn't contain any data from /info or /configprops. The admin server backend is totally unaware of that.
3. The UI is totally unaware when /info and /configprops might could have changed.

But what could be reasonable:
Fetch /info and /configprops only once (first render) and whenever the app-status changes. When the information is outdated the user has to hit refresh.

**Comment by lidkowiak** [comment]
Thanks for explanations. I agree.

**Comment by lidkowiak** [comment]
Thanks!

**Comment by joshiste** [comment]
@lidkowiak  It would be great if you could try the snapshot build and proof that everything is as you expectet.
