### ISSUE TITLE
Docs: running SBA on ECS

### ISSUE THREAD

**Issue by FedorRomanov** [codecentric/spring-boot-admin#957]
I understand it is rather common case: run SBA in ECS and monitor other ECS services. Can you, may be, summarise(include into the docs) what needs to be done to have SBA properly recognise instances  running in ECS(service port number is assigned by ECS and not 8080 )?

Currently, SBA displays the apps as 'offline'(obviously two-way communication does not work): ECS
34m | http://2c80fa682f47:8080/api

**Comment by joshiste** [comment]
I'm no ECS user so I can't help you with that.
But if you google a bit you find an article on how to determine host and port for your task (https://medium.com/@pedrojuarez/ec2-ecs-instance-metadata-2939d7a6f2ce).

Using this information you just need to set the `spring.boot.admin.client.instance.service-base-url` for the admin client.

**Comment by dnellutla** [comment]
Hi @FedorRomanov , I am deploying Admin server and all the services in ECS and have been facing the same issue.
What did you do to resolve the issue.

**Comment by sayadi** [comment]
Not exactly complete documentation, but you might find my comment on issue #430 helpful:
https://github.com/codecentric/spring-boot-admin/issues/430#issuecomment-643675296

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.
