### ISSUE TITLE
Out of memory during HTTP trace view

### ISSUE THREAD

**Issue by lucwillems** [codecentric/spring-boot-admin#958]
we have 9 small spring boot based containers. 8 of this containers, we can easily trace all HTTP request.
1 container always cause the browser to freeze and end with a out of memory issue. 
this was seen in current 2.0.3 and previous versions.

i started debugging this using chrome debugger and noticed that with the container which causes the out of memory issue , the for loop in traces-chart.veu (line 81) was running forever

        for (let time = Math.floor(oldest.valueOf() / interval) * interval; time < now; time += interval) {
          const bucket = {
            timeStart: time,
  
root cause of this was that time < now did not end because now was in milliseconds and time was in seconds , causing this loop to run 1000 more than required. (see screenshots)

looking deeper into this issue i noticed that there was a difference in JSON timestamp between de 8 working servers and the 1 failing server.

the failing server would send following HTTP trace json 
```
{
    "traces": [
        {
            "timestamp": 1538801577.562,
            "principal": null,
            "session": null,
            "request": {
                "method": "GET",
```
note this is a FLOAT of seconds

the working containers , which are plain REST services , returned a TEXT formatted data stamp
```
{
    "traces": [
        {
            "timestamp": "2018-10-06T03:35:49.510Z",
            "principal": null,
            "session": null,
            "request": {
```

so the failing container , cause the time to be parsed as a integer value , ignoring the ".xxx" milliseconds and causing the timestamp to be 1000x to small.

currently i'm trying to find a solution to let spring boot actuator use always the same timestamp format
but no progress on that.
it's maybe not a spring-boot-admin bug but maybe there is a way to work around this or document the issues.
<img width="1440" alt="screenshot_20181006_062002" src="https://user-images.githubusercontent.com/1294663/46567680-0ccdd380-c937-11e8-8646-83633404ad29.png">

about the screenshot :
you see that the variables time & oldest have same number of digest , but now has 3 digits more, so showing epoch time in milliseconds
```
oldest = 1538798009
time   = 1538798000
now    = 1538799286339
```

**Comment by joshiste** [comment]
duplicates #861
