### ISSUE TITLE
Error using Spring Boot 1.3.0.M2 Actuator HATEOAS on Threaddump and Traces

### ISSUE THREAD

**Issue by remylesiak** [codecentric/spring-boot-admin#96]
Since Spring-Boot-1.3.0-M2, Actuator HTTP endpoints are enhanced with hypermedia links when Spring HATEOAS is on the classpath. There are errors on Trace and Threads tabs when they parse the response.

**Comment by kongchen** [comment]
Hi, I'm using SrpingBoot-1.3.0-M5 as my server application and got following errors when try to dump threads by spring-boot-admin:
```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.2.28/ngRepeat/dupes?p0=thread%20in%20dump%20%…ang.ref.Reference%24Lock%22%2C%22identityHashCode%22%3A2077587380%7D%7D%5D
    at Error (native)
    at http://localhost:8081/js/app.js:2024:450
    at http://localhost:8081/js/app.js:2219:179
    at Object.fn (http://localhost:8081/js/app.js:2127:293)
    at h.$digest (http://localhost:8081/js/app.js:2128:373)
    at h.$apply (http://localhost:8081/js/app.js:2131:362)
    at m (http://localhost:8081/js/app.js:2090:454)
    at w (http://localhost:8081/js/app.js:2095:463)
    at XMLHttpRequest.B.onreadystatechange (http://localhost:8081/js/app.js:2097:24)
```

Is it the issue as same as this thread described?

**Comment by joshiste** [comment]
Yes it is. Try the boot-admin from my private repo to work with boot-1.3.
When they have the RC1 release i will merge into this repo

**Comment by kongchen** [comment]
Have done that, it works pretty good. Thanks!

2015-10-10 2:42 GMT+08:00 Johannes Edmeier <notifications@github.com>:

> Yes it is. Try the boot-admin from my private repo to work with boot-1.3.
> When they have the RC1 release i will merge into this repo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codecentric/spring-boot-admin/issues/96#issuecomment-146957951>
> .
>



-- 
Regards,
Kong
