### ISSUE TITLE
Insights>Details not showing horizontal scroll bar

### ISSUE THREAD

**Issue by prafsoni** [codecentric/spring-boot-admin#960]
If any of the property in health has extremely long value, the responsive view is trying to stretch the view to the whole length of value. Which is extending the view beyond the screen view. lack of horizontal scroll bar makes impossible to view details unless zooming out.

In my case couchbase.nodes is the culprit as it lists dns and ip address for each connected node. For other services view is fine.

**Comment by joshiste** [comment]
Could you post you output from the `health` endpoint?

**Comment by prafsoni** [comment]
![screen shot 2018-10-09 at 9 48 42 am](https://user-images.githubusercontent.com/6965165/46677785-e1521f80-cba8-11e8-8ce3-a180d2a3ba16.png)

**Comment by joshiste** [comment]
@prafsoni I guess the `nodes` property is just a single string or an array? 
What is used for delimiter? Just a single comma or is it comma + space?

**Comment by prafsoni** [comment]
@joshiste its a single comma separated string. dns1/ip1,dns2/ip2,...
