### ISSUE TITLE
spring boot admin 2.0.3 - show only metadata and health 

### ISSUE THREAD

**Issue by rafgitdz** [codecentric/spring-boot-admin#961]
Hello,
I use spring boot admin v2.0.3, when i launch the ui admin, i have only "Health" and "Metadata" views...
No details, metrics, etc.

i have these properties : 

application.properties of client :

```
# Spring Boot Admin
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.boot.admin.client.password=user
spring.boot.admin.client.username=changeme
spring.boot.admin.client.enabled=true
spring.boot.admin.client.url=http://localhost:8080
spring.application.name=d3-arret-travail
#using the metadata
spring.boot.admin.client.instance.metadata.tags.environment=${mail.environment}
#using the info endpoint
info.tags.environment=${mail.environment}
```

"application.properties" of admin part :

`spring.boot.admin.ui.title=Spring Boot Admin`

With no spring security.

![image](https://user-images.githubusercontent.com/14233112/46633621-85f34380-cb4e-11e8-9199-30a883cceb35.png)

I follow normally this doc : http://codecentric.github.io/spring-boot-admin/2.0.3/ 

Thanks in advance for your support.

RF

**Comment by joshiste** [comment]
It looks to me that the `application.properties` you have posted belongs to a different application or is not in effect (as it configures a different application name as show in the screenshot).
Please also test that the actuator endpoints are in fact accessible via http

**Comment by rafgitdz** [comment]
No i posted the wrong ui 
I tested the actuator endpoints via http and it is ok 
I have only Health page displayed
