### ISSUE TITLE
DefaultServiceInstanceConverter should be null-safe on Metadata

### ISSUE THREAD

**Issue by jochenchrist** [codecentric/spring-boot-admin#962]
`KubernetesDiscoveryClient` sets `ServiceInstance#metadata` to `null`, when no Kubernetes [label](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) is set in the Deployment yaml.
See: https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c2dc809469bf547eec4508971a580a9722f042f5/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClient.java#L90

The `DefaultServiceInstanceConverter` fails with NullPointerException, when trying to access health-URL, etc.

Enhancement: Make all access to `instance.getMetadata()` null-safe (or provide an autoconfigured KubernetesServiceInstanceConverter)

**Comment by joshiste** [comment]
I've raised https://github.com/spring-cloud/spring-cloud-kubernetes/issues/247
