### ISSUE TITLE
java.lang.IllegalStateException: The port contains a URI variable but has not been expanded yet 

### ISSUE THREAD

**Issue by yevtsy** [codecentric/spring-boot-admin#964]
Hello,

I've discovered an issue in `DefaultServiceInstanceConverter` while extracting `management.port` to create `managementUrl`. 

I'm using SBA 2.0.3, SB 2.0.5-SNAPSHOT, Eureka as service discovery.

Suppose Eureka defines `management.port` as a placeholder (for example, `${management.port}`) and each client service provides it. If the client doesn't provide it, SBA receives placeholder value as is.

```
java.lang.IllegalStateException: The port contains a URI variable but has not been expanded yet: ${management.port}
    at org.springframework.web.util.HierarchicalUriComponents.getPort(HierarchicalUriComponents.java:191) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
    at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:510) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
    at de.codecentric.boot.admin.server.cloud.discovery.DefaultServiceInstanceConverter.convert(DefaultServiceInstanceConverter.java:67) ~[spring-boot-admin-server-cloud-2.0.3.jar:2.0.3]
    at de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener.registerInstance(InstanceDiscoveryListener.java:138) ~[spring-boot-admin-server-cloud-2.0.3.jar:2.0.3]
```

Moreover, we can extract `port` from `serviceUrl`, but it never executes, because `managementPort` is not empty.

Even if it's not the serious error,  as a client of a library I don't expect this exception may appear and `managementUrl` builds incorrectly

If you agree with it, I can create PR to fix this issue

**Comment by joshiste** [comment]
This is not a SBA problem. The placeholders are resolved by Spring at startup time and when a placeholder can't be resolved it will be left as is. In your case the url the UriComponentsBuilder recieves the property with the unresolved placeholder and tries to resolve it again but lacks the needed context for this.
The property must not contain any unresolved placeholders. When the `management.port` is unset the best thing to do is to default the value like this: `${management.port:${server.port:8080}}`

**Comment by joshiste** [comment]
In case you want to prevent any unresolved placeholders do it like this: 
```
    @Bean
    public static PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer() {
        PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer = new PropertySourcesPlaceholderConfigurer();
        propertySourcesPlaceholderConfigurer.setIgnoreUnresolvablePlaceholders(true);
        return propertySourcesPlaceholderConfigurer;
    }
````
