### ISSUE TITLE
org/thymeleaf/spring5/templateresolver/SpringResourceTemplateResolver not found

### ISSUE THREAD

**Issue by xiaoyu10714024** [codecentric/spring-boot-admin#967]
I just add Spring Boot Admin Server starter to my dependencies. And then run the application, the error occurs like this: 
java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$EndpointWebMvcConfiguration due to org/thymeleaf/spring5/templateresolver/SpringResourceTemplateResolver not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)

The following is my gradle dependency configuration:
	compile("de.codecentric:spring-boot-admin-starter-server:2.0.3")
	compile("org.springframework.boot:spring-boot-starter-thymeleaf")

Has anyone else encountered this problem?

**Comment by joshiste** [comment]
Could you please provide a sample project to reproduce the issue?

**Comment by gusbossini** [comment]
Maybe your problem is that you're using old version of spring boot, try to use spring boot 2.0.5.

**Comment by xiaoyu10714024** [comment]
> Maybe your problem is that you're using old version of spring boot, try to use spring boot 2.0.5.

That's right. The problem has solved after I update version of spring boot into 2.0.5.RELEASE. Thank you again.
