### ISSUE TITLE
Need to hot admin-ui on different URl and Admin server on different

### ISSUE THREAD

**Issue by apoorvGupta1492** [codecentric/spring-boot-admin#968]
Right now i connect using spring.boot.admin.url my different apps to admin server ui and this is same as server.port
But i require my admin-ui hosted on separate port and admin server on seperate how to do that?

**Comment by joshiste** [comment]
You can't. If you want to restrict the access from the ui to the server the only thing you can do is to set a reverse proxy in front of the SBA server.

**Comment by apoorvGupta1492** [comment]
Ok. Thanks but my purposse is not "restrict the access from the ui to the server".Actually my production machines dont allow any other port than 8080 to be accessed from browser and i already made my to be monitored app to point to port 8096.So instead of changing all theses apps i was looking an option to somehow change the Ui host on admin server ui and keep server url same as before
