### ISSUE TITLE
Error if /health-endpoint is secured

### ISSUE THREAD

**Issue by lbeuster** [codecentric/spring-boot-admin#97]
With 1.2.1 the admin-server could work with a protected client-health-endpoint (e.g. with basic auth). Since 1.2.2 the client is listed as OFFLINE if /health is protected.

It's still possible to protected all other endpoints but /health has to be open.

Best regards
Lars

**Comment by joshiste** [comment]
In previous versions the user had to supply  a username and password and the. browser did the check. With 1.2.2 the health-check has moved to the admin server and the server is lacking the credentials. So the best would be to provide the status if the request is unathorized as described in [Spring Boot Reference - Security with HealthIndicators ](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#_security_with_healthindicators)

**Comment by lbeuster** [comment]
Thanks for the hint to the spring-boot behavior - it's ok for use to open the health endpoint that way.
