### ISSUE TITLE
Suggestion and issue

### ISSUE THREAD

**Issue by HaojunRen** [codecentric/spring-boot-admin#971]
1. I would rather like tabs layout in 2.0.2, it is ugly  to set those tabs in left-top corners in 2.0.3
2. After I upgraded 2.0.2 to 2.0.3, the JMX tab is missing

**Comment by joshiste** [comment]
> I would rather like tabs layout in 2.0.2, it is ugly to set those tabs in left-top corners in 2.0.3

On smaller screens the tabs didn't fit on the screen so we moved the navigation to the sidebar. Do you have any suggestion how we can solve this problem in a more elegant way? Besides telling me that you don't like the sidebar I'm really missing a suggestion here.

> After I upgraded 2.0.2 to 2.0.3, the JMX tab is missing

It's under the JVM group in the sidebar. If it's missing, most probably the `jolokia` actuator endpoint isn't exposed.
