### ISSUE TITLE
Dashboard event-stream

### ISSUE THREAD

**Issue by simo385** [codecentric/spring-boot-admin#972]
Currently, we're using the following versions:

> Spring Boot Version: 1.5.14
> Spring boot Admin: 1.5.7

We need to use these versions for architecture constraints.

We've developed a web application with some microservices and we want to use spring-boot-admin to monitor them. To do this, we open two or more SBA dashboard in more than one browser. When the data change, the server sends an update to interface using event-stream protocol. Sometimes, the interface doesn't receive the updates and do not update itself.

We're seeing this issue both for multiple dashboards and one dashboard monitoring.

What can we check? What can we find the logs?

Thanks in advance for the support.
Simone

**Comment by joshiste** [comment]
You should check the eventstream request in the browsers console.

**Comment by simo385** [comment]
I did. If I check the browser's console, I see the following scenario:
- In the first browser, I can see the updating data in the journal event stream
- In the second browser, I CANNOT see the updating data in the journal event stream

After server debugging, in particular, _JournalController_ class, it seems the server doesn't send the event for the second client (browser). However, this happens sometimes.

How is the client added to the _JournalController.emitters_? What could I check on the server side?

Thanks in advance,
Simone

**Comment by joshiste** [comment]
It's a request to the `JournalController#getJournalEvents` adds the SseEmitter

**Comment by simo385** [comment]
The request works correctly, but sometimes, it seems the server LOSES some client during the execution, in particular when it sends the events.

Is it possible, during the execution, the server removes a _SseEmitter_ wrongly?

**Comment by joshiste** [comment]
> Is it possible, during the execution, the server removes a SseEmitter wrongly?

I don't know.

The best is to upgrade to SBA 2.0 as it doesn't use the Sse emitters. Also I won't do any fix for 1.5.x unless it's critical. Which is imho not the case here.

**Comment by simo385** [comment]
I get it. 
I'll try to fix it.

Thanks for your support.
