### ISSUE TITLE
SBA doesn't display actuator endpoints for services (150+) discovered by Eureka registry

### ISSUE THREAD

**Issue by yevtsy** [codecentric/spring-boot-admin#973]
**Main issue**: I have 150+ Spring Boot microservices registered to Eureka. When I run SBA with cloud discovery, all services appear and show Details pages, but just a few of them show the other tabs (ENV, JMX, Loggers, ...)

**Initial configuration**: Spring Boot Starter 2.0.5, Spring Boot Admin 2.0.3 (also compiled from sources based on 2.0.x branch). SBA discovery - Eureka

I have some investigations and want to share it. It can be useful or at least helps to determine what's wrong with my assumptions:

1. All instance endpoints register in `Instance` class : `Instance apply(InstanceEvent event, boolean isNewEvent)`
These events are `InstanceRegistrationUpdatedEvent`, `InstanceEndpointsDetectedEvent` and so on. As Eureka doesn't send such events with filled endpoints,
I decided to fix it with overriding `InstanceDiscoveryListener` which allows me to force endpoints detection.

```
  @Override
    protected Mono<InstanceId> registerInstance(ServiceInstance instance) {
        return super.registerInstance(instance)
                .doOnNext(endpointDetector::detectEndpoints);
    }
```

After that about half of the services show required tabs. Unfortunately, there are another half fo services are still with single `Details` tab

2. Despite the fix above there's some magic is present here. After restarting SBA application some of previously "correctly worked" services show single `Details` tab, while some other "incorrectly worked" ones show full set of tabs. After next restart it repeats with other services. And so on.

While debug source code I noticed that `ProbeEndpointsStrategy` detect actuator endpoints for all services, but then it cannot propagate next. 

Moreover, the issue I found relates to this method:

```
    public Mono<Endpoints> detectEndpoints(Instance instance) {
        return Flux.fromIterable(endpoints) // 1
                .flatMap(endpoint -> detectEndpoint(instance, endpoint))// 2
                .collectList()// 3
                .flatMap(this::convert);// 4
    }
```

While after //1 and //2 all endpoints are present, // 3 step returns empty list unpredictably, so //4 doesn't even run

I've shared all my investigations with you and I suppose some of them can be going in wrong direction, but anyway the issue is still exists

**Comment by joshiste** [comment]
1) The endpoint detection runs either when the application changes it status or when the registration (including metadata) is updated. 

To enforce a endpoint detection after a (re-)deployment just add a timestamp with the startuptime in the instance metadata (when using the SBA client it will be done automatically). I guess our docs currently lack some docs on this.

2) The `ProbeEndpointsStrategy` is merely just for (old 1.5.x) spring boot applications not providing an actuator index and probes the endpoints by doing a `OPTION` request to every endpoint. I guess when you have no endpoints present at all, your application failed to respond to the request. Please note that in the upcoming 2.0.4 there will be an option to retry the probing requests.

**Comment by joshiste** [comment]
I've added a hint in the docs for triggering the update with 2d05959bba6ecda431611208d410100b50c4c61d

**Comment by yevtsy** [comment]
1. In my case, I register SBA with Eureka registry, where services are already UP, so I just attach SBA to it. The expected behavior of SBA, in this case, is to fetch all metadata from services and execute endpoint detection for each of them (even if they don't change statuses)

If SBA doesn't process such scenario, what can you advise to avoid the limitations? 

2. I spent some time to dig into source code, so for each endpoint
```
public Mono<Endpoints> detectEndpoints(Instance instance) {
        return Flux.fromIterable(endpoints) 
                .flatMap(endpoint -> detectEndpoint(instance, endpoint))
                .doOnNext(next -> println(instance.getRegistration().getName() + ": ProbeEndpointsStrategy detect " + next.endpoint))
                ...
    }
```


actually prints all endpoints (they are present, though your guess they aren't).



 Moreover, when I manually restart chosen services they appear at SBA after auto-registration in Eureka and all tabs appears as expected.
 But manuall restarting is not a solution, so do you have any ideas how to fix it?

**Comment by joshiste** [comment]
> 1. In my case, I register SBA with Eureka registry, where services are already UP, so I just attach SBA to it. The expected behavior of SBA, in this case, is to fetch all metadata from services and execute endpoint detection for each of them (even if they don't change statuses)

This should happen right now as with the first registration they should change from offline to up. So If you have a look at the Journal there should be STATUS_CHANGE Events for every new instance.

**Comment by igorermolenko** [comment]
> 2\. Please note that in the upcoming 2.0.4 there will be an option to retry the probing requests.

Hi, Johannes
Is this option really in the released 2.0.4?
Because I look at the source de.codecentric.boot.admin.server.config.AdminServerProperties.MonitorProperties and do not see new properties (defaultRetries and retries):

    public static class MonitorProperties {
        /**
         * Time interval to update the status of instances with expired statusInfo
         */
        @DurationUnit(ChronoUnit.MILLIS)
        private Duration period = Duration.ofMillis(10_000L);

        /**
         * Lifetime of status. The status won't be updated as long the last status isn't
         * expired.
         */
        @DurationUnit(ChronoUnit.MILLIS)
        private Duration statusLifetime = Duration.ofMillis(10_000L);

        /**
         * Connect timeout when querying the instances' status and info.
         */
        @DurationUnit(ChronoUnit.MILLIS)
        private Duration connectTimeout = Duration.ofMillis(2_000);

        /**
         * read timeout when querying the instances' status and info.
         */
        @DurationUnit(ChronoUnit.MILLIS)
        private Duration readTimeout = Duration.ofMillis(20_000);
    }

**Comment by igorermolenko** [comment]
And InstanceWebClient creation remains the same:

    public InstanceWebClient instanceWebClient(HttpHeadersProvider httpHeadersProvider,
                                               ObjectProvider<List<InstanceExchangeFilterFunction>> filtersProvider) {
        List<InstanceExchangeFilterFunction> filters = filtersProvider.getIfAvailable(Collections::emptyList);
        WebClientCustomizer customizer = (webClient) -> filters.forEach(instanceFilter -> webClient.filter(
            InstanceExchangeFilterFunctions.toExchangeFilterFunction(instanceFilter)));

        return new InstanceWebClient(httpHeadersProvider, adminServerProperties.getMonitor().getConnectTimeout(),
            adminServerProperties.getMonitor().getReadTimeout(), customizer);
    }

**Comment by joshiste** [comment]
Yeah, sorry my mistake it's in the upcoming 2.1.0

**Comment by joshiste** [comment]
see https://github.com/codecentric/spring-boot-admin/issues/862

**Comment by igorermolenko** [comment]
OK
Thank you

**Comment by igorermolenko** [comment]
Johannes, can you tell me, please, when 2.1.0 release is planned?

**Comment by joshiste** [comment]
see https://github.com/codecentric/spring-boot-admin/milestones
