### ISSUE TITLE
Failed to register application as Application 401 Authorization Required

### ISSUE THREAD

**Issue by Nick9502** [codecentric/spring-boot-admin#974]
I have been trying to register my spring boot application (client) to the SBA server. The application works locally however when deployed to development it cannot detect the applications.  Initially it worked fine however without warning the applications began failing to connect. The logs show the following error in the client application:

-- Failed to register application as Application [name=appName, managementUrl=http://hostmachine:9091, healthUrl=http://hostmachine:9091/health, serviceUrl=http://hostmachine:9091] at spring-boot-admin ([http://host/admin/instances]): 401 Authorization Required 

**Application Properties**
eureka.client.service-url.defaultZone=http://host/eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.boot.admin.context-path=/admin
spring.application.name=app_name
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS

**Client Application Properties using Spring Boot 1.5**
spring.boot.admin.client.enabled=true
endpoints.metrics.sensitive=false
management.security.enabled=false
spring.boot.admin.url=http://host/admin
spring.boot.admin.client.service-url=http://hostname:9089
spring.application.name=client_app_name
eureka.client.service-url.default-zone=${EUREKA_URI:http://host/eureka}
spring.boot.admin.api-path=instances

Any ideas?

**Comment by joshiste** [comment]
Why do you use the spring boot admin client and eureka? There is no need for using both.

A 401 indicates that the application does need some credentials (e.g. username/password) to access the http endpoint. You provided config totally lacks such information. 

Please also be aware that Spring Boot 1.5.x autoconfigures some defaults when spring security is found no the classpath.

**Comment by Nick9502** [comment]
I disabled the security in my SecurityConfiguration class using

**Comment by Nick9502** [comment]
My main application is a Spring Boot Admin 2.0 Eureka Admin Server that monitors the client applications. The Server application also has a custom security filter to restrict access to certain endpoints via third party credentials. 

There shouldnt be any client credentials necessary. I've configured the SecurityConfiguration to permit all. Also as mentioned. The application works fine locally. Would you require more details to help understand the issue?

**Comment by joshiste** [comment]
As SBA doesn't provide any security config. I can't help you much.

**Comment by joshiste** [comment]
> My main application is a Spring Boot Admin 2.0 Eureka Admin Server

The why don't you get rid of the SBA client? The 401 should vanish and the registration is made by eureka.
