### ISSUE TITLE
Integrate Zipkin or other OpenTracing Compatible Module

### ISSUE THREAD

**Issue by rowi1de** [codecentric/spring-boot-admin#979]
### Enhancement 
- Currently Spring Boot Admin provides Application Logs and Actuator Http Trace
- Since Spring Boot Admin is often used in Microservice Setups, it would be very useful to integrate some OpenTracing Compatible Module 

#### Zipkin Server Integration
- My first Idea was to have a Zipkin Server integrated into SBA, so that enabled clients could automatically send Tracing Data to Spring Boot Admin (as Zipkin Server)  

#### Zipkin UI Integration
- If integration of Zipkin Server integration is not possible / maintainable, it would be nice to pull Zipkin/OpenTrace Data from an external Instance

#### Simple UI
- Integrate Zipkin UI into SBA  and link Service/Application/Instances

https://gitter.im/codecentric/spring-boot-admin?at=5bcebc1fbbdc0b2505860c21

**Comment by joshiste** [comment]
Imho we should strive for the lightest integration possible, e.g. placing some useful links or doing a ui integration via iframes.

**Comment by Anoopc444** [comment]
Hello, I am also into the same requirement.U guys made any progress on this so far? if so could you please share your experiences

**Comment by arunkpatra** [comment]
> Imho we should strive for the lightest integration possible, e.g. placing some useful links or doing a ui integration via iframes.

Would Jaeger be an option. It's compliant with io.opentracing and its trace format is Zipkin compliant. It's trace propagation format is neat and the W3c propagation format is underway. The UI appears to be much more fluid and manages a very very large number of spans very well as well.

It can be included as an iframe.

**Comment by andreashouben** [comment]
There has not been an update to this issue in a long time. Therefore I'm closing it. Feel free to reopen it if you think there is still something to be done.
