### ISSUE TITLE
Tags are not getting updated

### ISSUE THREAD

**Issue by Glosur** [codecentric/spring-boot-admin#981]
The tags are never updated, even though the info part of the details page is updated.

**Comment by Glosur** [comment]
![capture](https://user-images.githubusercontent.com/14371287/47427908-055d5580-d792-11e8-88b9-d5e332efbe54.PNG)

Here is an example. Sorry, I had to remove sensitive data

**Comment by joshiste** [comment]
When using a Discovery Client you need to add some unique metadata entry so that the info and endpoints are refreshed after updating the application. See https://github.com/codecentric/spring-boot-admin/commit/2d05959bba6ecda431611208d410100b50c4c61d

**Comment by joshiste** [comment]
> What if I update the endpoint without restarting my app ?

To trigger the refresh the metadata needs also to be updated.
