### ISSUE TITLE
Add option to configure the basePath if running behind a reverse proxy

### ISSUE THREAD

**Issue by slindenberg** [codecentric/spring-boot-admin#983]
If the SBA app is run in an environment which uses a web proxy server for security, the prefixed context path segments are ignored:

**Real application path:**
`http://tomcatservername.xyz/sba-app`

**Proxied application path**
`http://tomcatservername.xyz/proxy-junction/sba-app`

**The app tries to access:**
`http://tomcatservername.xyz/sba-app/applications`, but should be
 `http://tomcatservername.xyz/proxy-junction/sba-app/applications`

The junction is missing, which causes an HTTP 500 status (from the proxy server). I have tried setting the `spring.boot.admin.context-path`-setting, but since this is relative to the DispatcherServlet (``http://tomcatservername.xyz/sba-app/`) this does not work, too.

**Comment by joshiste** [comment]
How do you deal with this problem for your other applications (which need to to a 302 or include links back to itself)?

What you could do right now: 
Deploy SBA as root app and set the `spring.boot.admin.context-path` to `/proxy-junction/sba-app/applications` and disable url rewriting.

**Comment by joshiste** [comment]
closed due to missing feedback.

**Comment by matzegebbe** [comment]
With the 2.1.0 its a bit mixed up... The base path is not set in the templates and there are resources loaded from root.
But with the setting spring.boot.admin.ui.template-location: "classpath:/public/" you can overwrite the index / login.html

**Comment by joshiste** [comment]
@matzegebbe  see #990

**Comment by dassebi** [comment]
My Spring-Boot-Admin-service is running in a docker-container behind a Spring-Gateway. For this I configured the public-url this way:

spring:
  boot:
    admin:
      ui:
        public-url: "https://myAppname.intranet.cnb/monitoring/"

My problem now is, that spring-admin by default adds a port (in my case "8080"), if it is omitted. And I dont't want a port in this public-url. How can I configure this public-url without a port?

Tank you
Sebi

**Comment by JasonJunJun** [comment]
@dassebi change `spring.boot.admin.ui.public-url` from `https://myAppname.intranet.cnb/monitoring/` to `https://myAppname.intranet.cnb:443/monitoring/`, [de.codecentric.boot.admin.server.ui.web.UiController.getBaseUrl](https://github.com/codecentric/spring-boot-admin/blob/641f660082b9b10f4d80c9d4a7f7ebf449d6ba10/spring-boot-admin-server-ui/src/main/java/de/codecentric/boot/admin/server/ui/web/UiController.java#L58) is the method that builds baseUrl. If scheme is http, change 443 to 80.

**Comment by JenoDK** [comment]
@JasonLaw1994 Thanks so much. This is indeed the way for when your SBA is running on a reverse proxy that doesn't allow any http connections. In my case my server is completely blocked off except for everything cloudflare related.
