### ISSUE TITLE
use admin UI to remote start/stop registered boot applications

### ISSUE THREAD

**Issue by zergxyz** [codecentric/spring-boot-admin#99]
Is there a way to use Spring-boot-admin UI to remote start/stop registered spring boot apps? Since right now we can only view its registered app status but I wish we can get some remote control on these apps.
PS. I would love to do the implementation if someone can give me some instructions on this.

**Comment by steve-oakey** [comment]
The JMX endpoints should give you this ability. Restart will only be
available (to my knowledge) if you are using Spring Cloud or have written
your own JMX operation but the shutdown of available via Spring Actuator
should be available.

-Steve

**Comment by joshiste** [comment]
as steve pointed out, we could add support for the spring-cloud features. But in case you haven't got a running process to interact with, spring boot admin can't do a( nything.
In my opinion you should rely on your OSs features to start and stop a process. For example as a init.d-service or in cas you are using docker by controlling your container via kubernetes or sth. else.

**Comment by zergxyz** [comment]
thanks for the information. I will go for the OS way to do the remote control.

**Comment by RobWin** [comment]
Spring Boot and [Supervisord](http://supervisord.org/) are a nice combination. 
I created a small Python tool which combines Ansible and Supervisor to control a cluster of Supervisor daemons remotly.

https://github.com/RobWin/supervisorclusterctl

**Comment by rubenibarra** [comment]
via the login ui can I authenticate to the microservice oauth2? for later through the token obtained to be able to visualize the most exposed in the spring admin?

**Comment by knockingOn** [comment]
Is this enhancement implemented now?
to start/stop a client application registered to the admin-server?

**Comment by andreashouben** [comment]
As there has not been an update to this issue in a long time I'm closing it. Feel free to reopen it if you think there is still something to be done.
