### ISSUE TITLE
Add filter/search to application list

### ISSUE THREAD

**Issue by kna0085** [codecentric/spring-boot-admin#998]
Hi @joshiste 
I'm currently using SBA 2.0.2 and I'm not able to see search bar in the application list neither in wallboard. Is that functionality available in this version?

**Comment by joshiste** [comment]
Currently not implemented

**Comment by kna0085** [comment]
Can it be added as an enhacement?

**Comment by joshiste** [comment]
Contributions are always welcome.

**Comment by ronnberg** [comment]
I too really miss this function from the old version. We have over 60 micro services registered and the filter bar was really helpful when locating a service. You got my vote :)

**Comment by joshiste** [comment]
Feel free to submit a PR

**Comment by ozkanpakdil** [comment]
please check https://github.com/codecentric/spring-boot-admin/compare/master...ozkanpakdil:patch-1.

I dont know if I need to create a pull request ? it was one file change.
