### ISSUE TITLE
Detect logging.config

### ISSUE THREAD

**Issue by nwhessel** [codecentric/spring-boot-admin#999]
The guide says we can use logging.path or logging.file. How about detecting logging.config as well?

https://codecentric.github.io/spring-boot-admin/2.1.0/#logfile

**Comment by joshiste** [comment]
SBA just takes tho log output from the spring boot actuator `/logfile` endpoint so this is a request for spring boot actuator (and not admin).
But there is a property in spring boot to serve any file: `management.endpoint.logfile.external-file`
